drape_frontend/user_event_stream.cpp
Краш возникал во время масштабирования, когда добавлялось касание еще одним пальцем.
=> [drape] Fixed crash on assert in UserEventStream.

qt/res/Info.plist
Delete either build folder or MAPS.ME.app folder and rebuild for it to work.
=> Mac OS X El Capitan: fixed http download error introduced by Apple for more security.

common.pri
This fixes picking up system libraries instead of ones from 3party/
=> Fix library path: prepend local lib path instead of appending

routing/routing_integration_tests/routing_integration_tests.pro
Fixes link error:
...omim/search/intermediate_result.cpp:44: undefined reference to OSMTimeRange::OSMTimeRange...
=> Add missing dependency

sound/tts/sound.txt
Another translation fix, this time for sound directory. Funny enough, it's not typos this time, but completely wrong numbers, probably due to copy-paste errors.
=> German translation fixes for sound texts.

tools/unix/build_omim.sh
Two minor fixes for Linux builds
Linux Qt target should change to linux-clang-libc++ as g++ stdlib headers gave some problems with thread model. This was at least with gcc 4.8.4. AFAIK libc++ is standard library for clang anyway, so might be best to avoid the mixup on systems where clang and g++ are found.
Second is a problem with smaller machines where only one processor is available. The build script terminates with command line 'make -j 0', as 1/2 processors gets rounded to 0. I'm working in a VM, so only one proc here. Could be extended to avoid the 0 instead, but having PROCESSES at num_proc seems more suitable.
=> Buildscript

routing/routing_tests/turns_sound_test.cpp, routing/turns_sound.cpp, routing/turns_sound.hpp
В при движении по маршруту, если два последующих поворота идут близко, то пользователь услышит: Поворот на право, затем поворот на лево. В данном случае не должно быть оповещение Поворот на лево через 200 метров после прохождения поворота на право.
Данный PR решает эту задачу.
https://trello.com/c/3sgwHYi1/1883--
=> Preventing first turn sound notification if this turn was noticed after word then.

routing/routing_session.cpp
Состояние системы звуковых оповещений должно сбрасываться после перепрокладки маршрута включая автоматические перепрокладки. Чтоб оповещения сказанные для предыдущего маршрута ни как не влияли на перестроенный.
https://trello.com/c/NL1mpIW7/1897--
=> Reseting turn sound system after every rerouting.

tools/unix/generate_planet.sh
Ветка котика уехала вперёд (полагаю, в дрейпе она более актуальна). Также, список регионов в `generate_planet.sh`, как оказалось, не работал под линуксом: починил.
=> [generator] Update osmctools and kothic; fix a bug in generate_planet

routing/routing_tests/turns_sound_test.cpp, routing/turns_sound.cpp, routing/turns_sound_settings.cpp, routing/turns_sound_settings.hpp
При проигрывании поворота правильно использовать расстояние оставшееся до поворота, а не расстояние, которое вычисляется из скорости и времени активации оповещения.
Бывают случаи (после перестроения маршрута), когда эти расстояния могут сильно различаться.
PR помечен DO NOT MERGE, поскольку я жду, когда в мастер попадет https://github.com/mapsme/omim/pull/164 и я смогу доделать юнит тесты без конфликтов.
https://trello.com/c/xTfj3uHV/1898--
=> [turns][sound] Using for turn notification a real distance to the closest turn instead of a distance based on speed.

platform/local_country_file_utils.cpp
Discovered this crash when tried to send debug version to our users.
=> Fixed crash on Android in debug mode when World maps are absent (not downloaded yet).

drape_frontend/stylist.cpp, drape_frontend/stylist.hpp
Added text styles property support (https://trello.com/c/aPuwQXzh/35-- port to the Drape).
plus minor changes:
- Fixed misprints "Finded" -> "Found";
- Added method const.
=> Added text style property support, fixed misprints

map/framework.cpp, platform/settings.hpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/turns_sound_test.cpp, routing/routing_tests/turns_tts_text_tests.cpp, routing/turns_sound.cpp, routing/turns_sound.hpp, routing/turns_sound_settings.cpp, routing/turns_sound_settings.hpp, routing/turns_tts_text.cpp
Использование enum Units по всем приложению для единиц измерения.
Ранее я ввел enum class LengthUnits, который обладал дефолтным значением для использования в TTS для выражения единиц измерения. В последствии, дефолтного значения не потребовалось. Чтоб не  плодить сущности теперь по все подсистеме озвучки используются старый emum Units.
https://trello.com/c/pN1344WJ/1902-enum-units
=> Using enum Units through all the application for meters and feet.

docs/MAPS.md, tools/unix/generate_planet.sh, tools/unix/generate_planet_routing.sh
Поспешил, не почитал свою же документацию и сломал функцию передачи списка регионов. Вернул, и уточнил документацию. Также:
* Добавил проверку, чтобы было не меньше 250 гигабайт на диске под промежуточные данные.
* Больше не шлём письмо при нажатии Ctrl+C, но шлём при возникновении ошибки (странно, раньше не было, и не замечал).
* Скрипт генерации роутинга находил «спрятанные» в подкаталоге промежуточные файлы. Теперь не будет.
=> [generator] Revert regions fix, warning on low disk space

map/framework.hpp, platform/get_text_by_id.cpp, platform/get_text_by_id.hpp, platform/platform_tests/get_text_by_id_tests.cpp, routing/routing_tests/turns_sound_test.cpp, routing/routing_tests/turns_tts_text_tests.cpp, routing/turns_tts_text.cpp, routing/turns_tts_text.hpp
1. Если sound.txt не содержит язык установленный по средствам SetLocale, то в качестве языка по умолчанию используем английский;
2. Рефакторинг, связанный с тем, что экземпляры GetTextById не создаются не валидными. Или создаются. Или возвращается unitque_ptr от нуля.
https://trello.com/c/3CTbz09t/1923-tts
=> Using English in TTS if sound.txt doesn't contain the current languag

routing/routing_tests/turns_sound_test.cpp, routing/turns_sound.cpp, routing/turns_sound.hpp
- Юнит тесты TTS отвязаны от ряда коэффициентов (чтоб юнит тесты не переписывать при настройке каждый раз);
- Изменены коэффициенты ответственные за озвучку;
https://trello.com/c/NwPYZq1H/1927--
=> [sound] Ability to change TTS factors without rewriting unit tests. Changing some TTS factors.

routing/routing_integration_tests/osrm_route_test.cpp
Сейчас мы не можем его починить. Путь в Лондон проходит по туннелю со свойством render:no. В итоге в mwm не попадает геометрия переправы и межмвмный роутинг не может найти точку выхода с карты. Для ремонта нужно либо научиться включать в mwm нерисуемую геометрию, либо придумать что-либо ещё. Таск на ремонт: https://trello.com/c/WPSQUu9J/1932-francepariscenternglandlondoncenterroutetest
=> Comment London ferry integration test.

tools/run_desktop_tests.py
There are some problems on linux starting and stopping the server for some reason. If we start the server before all the tests, and stop it after all the tests, we might not have those problems.
=> [DO NOT MERGE] Start server for all tests

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/sound/TtsPlayer.java, iphone/Maps/Classes/CustomViews/NavigationDashboard/Sound/MWMTextToSpeech.mm, map/framework.hpp, routing/routing.pro, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/turns_sound_test.cpp, routing/turns.hpp, routing/turns_notification_manager.cpp, routing/turns_notification_manager.hpp, routing/turns_sound.cpp, routing/turns_sound.hpp, routing/turns_sound_settings.cpp, routing/turns_sound_settings.hpp
Теперь ядро дает команду на демонстрацию плашки терна, который за следующим, наеа долго до произношения данной информации (если озвучка включена).
В любом случае, информация о терне за следующим теперь показывается за 30 секунд + "поправка" до следующего терна, при условии, что между следующим тернам и терном "за" следующим менее 400 метром.
https://trello.com/c/oJMfs37M/1971--
=> Displaying the turn after the next simultaneously with pronouncing the info about the turn after the next.

3party/opening_hours/osm_time_range_tests.cpp
Взял [вот эти тесты](https://github.com/ypid/opening_hours.js/blob/master/test.js) (осторожно, 360 кБ) библиотеки opening_hours.js и с помощью регэкспов и такой-то матери сделал из них код на C++. Убрал только тесты, зависимые от стран и координат (в том числе, `PH`, `SH`, часть `sunrise` и `sunset`).
Получилось 532 теста (вернее, групп из 4-5 тестов), из них сейчас проходят около 160. Большая часть непроходимости — из-за либерального отношения к ошибкам (чуть что — 24/7 и не волнует), либо неумения распарсить другие ошибки.
=> [oh] New tests from opening_hours.js

iphone/Maps/Classes/CustomViews/NavigationDashboard/Sound/MWMTextToSpeech.mm
1. Changing TTS volume all the time MAPS.ME is in foreground.
https://trello.com/c/WrHgKK0M/1987-ios-maps-me-foreground
2. Recovering playing background music after TTS notification.
https://trello.com/c/WrHgKK0M/1987-ios-maps-me-foreground
=> iOS. Changing TTS volume all the time MAPS.ME is in foreground.

android/jni/com/mapswithme/opengl/androidoglcontextfactory.cpp, drape/font_texture.hpp, drape/stipple_pen_resource.cpp, drape/stipple_pen_resource.hpp, drape/texture_manager.cpp, drape/texture_of_colors.cpp, drape/texture_of_colors.hpp, iphone/Maps/Classes/EAGLView.mm
Формат заднего буфера изменен в R5G6B5 на RGB8 для всех устройств. На Андроидах, если устройство вдруг не поддерживает RGB8 (что практически невероятно, но китайским телефонам законы не писаны), будет произведен фолбэк на R5G6B5.
=> [drape] Back buffer format changed to RGB8

routing/routing_integration_tests/osrm_route_test.cpp
Тест начал падать из-за изменения графа.
https://www.openstreetmap.org/way/375695929
С появлением новой дороги (места для разворота) итоговый маршрут стал короче.
=> Routing integration test fix.

map/framework.hpp, routing/routing_session.cpp, routing/routing_session.hpp
Возможность не сопровождать по маршруту от роутера. Чтобы включить этот режим нужно вызвать метод DisableFollowMode.
Заменяет PR https://github.com/mapsme/omim/pull/327
https://trello.com/c/zUWVOrZX/2000-gps
=> [routing] No following router mode.

routing/osrm_helpers.cpp, routing/routing_integration_tests/osrm_route_test.cpp
https://trello.com/c/oYT0xiwa/1609--
Фиксит выборку ближайших OSRM вершин при поиске начальной и конечной точек. До этого случались сбои (например, в Штутгарте или Шереметьево), если в районе точек находилось много дорог, которые по каким-либо причинам не попадали в OSRM. Например, потому что они закрыты для общего пользования. 
Добавлен специальный интеграционный тест MoscowToSVOAirport, который проверяет эту функциональность.
=> [routing] OSRM candidates filter fix.

generator/feature_builder.cpp, generator/osm2meta.hpp, generator/osm2type.cpp, generator/osm_element.cpp, indexer/feature_data.hpp, indexer/feature_meta.hpp
В общем, оказалось, `addr:flats` у нас не используется вообще нигде. Страннота. Выпилил `params.flats` и все его упоминания, добавил поле метаданных.
Заодно убрал пропуск тега seamark, чтобы потенциально можно было сделать морские карты.
=> [generator] Replace params.flats with metadata string

tools/python/stylesheet/drules_merge.py
Одна из тысяч неочевидных вещей насчёт наших стилей — они должны быть отсортированы по названию типа. Я этого не знал, и стили от `drules_merge.py` вызывали ошибку сборки. При этом, почему-то, не всегда. Этот пул-реквест добавляет сортировку результирующего стиля.
=> [styles] Merged rules should be sorted, it turns out

drape/overlay_handle.cpp, drape/render_bucket.cpp, drape_frontend/poi_symbol_shape.cpp
Исправлено определение прямоугольника POI при отсечении.
Добавлено обновление индексного буфера при перерисовке, раньше могли продолжать отображаться объекты, которые уже были вытеснены.
Исправлена функция определения точки привязки, которая используется при поиске объекта для выделения.
=> [drape] Fixed POI bounding rect calculation. Fixed index buffer updating. Fixed pivot calculation.

drape/drape_tests/font_texture_tests.cpp, drape/drape_tests/glyph_mng_tests.cpp
Убраны тесты, открывающие GUI-окна, из линукса.
=> [drape] Disabled some Drape tests on Linux

routing/routing_session.cpp, routing/routing_session.hpp
https://trello.com/c/pALZvBhF/2021--
Фикс подтормаживания роутинга после первого обновления позиции на длинных маршрутах.
Фикс связан с ограничением глубины просмотра точек маршрута, где мы ищем камеры. Раньше такого ограничения не было и при первом поиске мог быть проверен и весь маршрут, если на нём не было ни одной камеры.
Сейчас проверяется только kSpeedCameraLookAheadCount количество точек (50). Количество точек менее надёжная проверка, чем длина проверенного участка, но она значительно более быстрая. Каждое обновление позиции будут проверяться новые 50 точек пока не найдётся камера или маршрут не закончится. Таким образом за несколько обновлений позиции алгоритм сможет просмотреть весь маршрут.
=> Router freezing fix.

tools/unix/build_omim.sh
Из #451 понял, зачем нужна была установка переменной `MANPATH` в скрипте сборки. Вернул её.
=> [build] Return MANPATH to build_omim

.gitmodules, configure.sh, docs/INSTALL.md
Попробовал сейчас собрать проект под Ubuntu 14.04, обнаружил, что пропустил один пакет.
Также, подмодуль Alohalytics был встроен через ssh-ссылку, которая не позволяет клонировать анонимно. Поправил ссылку, но хз, как теперь обновление отработает.
Ещё добавил определение пути в `configure.sh`, так что его не обязательно теперь запускать из каталога репы.
=> Update documentation, git modules and configure.sh

routing/routing_session.hpp
Судя по тесту мы обращаемся к RoutingSession::m_state  из 3 потоков. Вот результаты теста на Андроид.
10-29 18:03:37.959 14940 14940 I MapsWithMe_JNI: routing/routing_session.cpp:109 RemoveRouteImpl()  MSTATE. thread id is -1225434316
10-29 18:03:44.716 14940 15364 I MapsWithMe_JNI: routing/routing_session.cpp:109 RemoveRouteImpl()  MSTATE. thread id is -1649907408
10-29 18:03:48.141 14940 15364 I MapsWithMe_JNI: routing/routing_session.cpp:76 RebuildRoute()  MSTATE. thread id is -1649907408
10-29 18:03:48.141 14940 15364 I MapsWithMe_JNI: routing/routing_session.cpp:109 RemoveRouteImpl()  MSTATE. thread id is -1649907408
10-29 18:03:50.401 14940 15325 I MapsWithMe_JNI: routing/routing_session.cpp:319 AssignRoute()  MSTATE. thread id is -1452279504
10-29 18:03:52.943 14940 15364 I …
=> Bugfix. Using atomic instead of direct calls for RoutingSession::m_state which is used at least from 3 threads.

map/framework.cpp, routing/route.cpp, routing/route.hpp, routing/routing_session.cpp, routing/routing_tests/routing_session_test.cpp, routing/routing_tests/routing_tests.pro, std/mutex.hpp
Фиксит баг неперестроения маршрута при уходе с него https://trello.com/c/9CzZo4fR/2029--
и покрывает этот кейс юнит тестом. Чтобы больше такого не повторялось.
=> Routing rebuild fix

tools/unix/generate_mwm.sh
Просто поддержка ещё одного типа файлов нулевой ценой. Нужна для HOT Export Tool 2 (думал, что там pbf на входе, оказалось — нет).
=> [generator] Add .osm files support to generate_mwm.sh

docs/MAPS.md, tools/unix/diff_features.py, tools/unix/diff_size.py, tools/unix/generate_planet.sh, tools/unix/test_planet.sh
Прошлый релиз оказался битым, и тесты этого не отловили: там пропали некоторые фичи (в основном, building-address и landuse-orchard), и файл Нидерландов, например, стал меньше на 150 мегабайт.
Теперь если указать переменную `DELTA_WITH` для generate_planet.sh с путём к старой сборке, в тестовом логе будут результаты сравнения как размеров файлов, так и состава фич внутри. Можно запустить тестирование отдельно, разумеется: путь к старым данным нужно передать вторым параметром test_planet.sh.
=> [testing] Add delta tests for map data

omim.pro, tools/unix/build_omim.sh
Поспешили убрать `CONFIG+=ordered` в #469: теперь не собираются исполняемые файлы, причём каждый раз разные. При этом сборка завершается без ошибки, т.е. не отследить никак. Нужно, конечно, умное решение, но пока его нет, а работать надо, — сделаем так. Все остальные правки в `omim.pro` выглядят нормально (хотя, конечно, вспоминаю, как меня ругали, что `omim.pro` стал сложен для восприятия, и ээээ).
Также, походя правлю тут ошибку в `build_omim.sh`, которая не позволяла собрать одновременно релиз и дебаг. И из-за которой скрипт всё время возвращал ненулевой код выхода.
=> [build] Restore CONFIG+=ordered

platform/platform_android.cpp
This is a follow-up fix for Android build.
https://trello.com/c/AUFaxzkF/2037-boost-xpressive
=> [base, std] Followup fix - replace base/regexp.hpp by base/regex.hpp

tools/unix/build_omim.sh
Последняя проверка (что запустили с ключом `-o` без остальных) почти никогда не срабатывала, и код возврата был не 0, а результатом этой проверки, т.е. 1. Поэтому `build_omim.sh` почти никогда не возвращал нулевого кода.
=> [build] Exit with 0 code when build is successful

map/api_mark_container.cpp, map/api_mark_container.hpp, map/api_mark_point.hpp, map/bookmark.cpp, map/bookmark.hpp, map/framework.hpp, map/map.pro, map/mwm_url.cpp, map/mwm_url.hpp, map/styled_point.cpp, map/styled_point.hpp, map/user_mark.hpp, map/user_mark_container.cpp, map/user_mark_container.hpp
As outlined in #238:
* Introduce StyledPoint class, and move style handling from Bookmark up to it.
* Make ApiMarkPoint a StyledPoint.
* Parse s= optional parameter in URL as the style.
Before and after shot below, for the same URL. The uppermost point is not styled (so defaults to red on the right). The original code (on left) ignores the style parameter and always shows a pink circle. After this PR (on right) the style parameter controls the appearance of the place marker.
Existing tests all pass. Which tests should I be modifying to regression-test this fix?
=> Parse URL s= parameter as point style

platform/local_country_file_utils.cpp
LERROR is too serious and causes crashes for debug builds. It should be replaced by LWARNING.
=> [platform] Fixed logging severity for LocalCountryFileUtils.

generator/osm2meta.cpp, tools/unix/diff_features.py, tools/unix/diff_size.py, tools/unix/generate_planet.sh
Собралась планета, я получил гигантский отчёт, и этот пул-реквест его немного подсжимает.
* Предупреждение про неправильное значение тега википедии понижено до `LINFO`.
* И убрана проверка на слэш в названии викистатьи: слэши там допустимы.
* Файлы сравниваются в алфавитном порядке.
* И явно пишется, увеличился размер или уменьшился, чтобы быстрее сканировать глазами.
* Промежуточные роутинговые файлы убираются чуть раньше, до тестов.
* Обновление countries.txt сделано опциональным шагов: скрипт не вываливается, если не прошло.
* Повысил грань проблемы в сравнивалке количества фич по типам до 100% (изменение вдвое в любую сторону). Но, конечно, придётся смириться, что пока картостиль допиливается, эта новая секция будет занимать три четверти отчёта.
=> Fixes for new tests

docs/INSTALL.md
* The Qt 5.5 env setup has to be done each time, not just once, so separate it from the other Qt commands.
* For Ubuntu 14.04 I needed a PPA for libc++.
* Explain where the output of the build goes.
Based on my experience of beikng a first-time MAPS.ME developer, these would have helped me. Also mentioning libc++-dev, but I see that's already been added - thank you.
=> Minor install docs fixes

drape/overlay_handle.hpp, drape/overlay_tree.cpp, drape_frontend/path_text_shape.cpp
- Добавлены маски для сравнения оверлеев;
- Текста на дорогах теперь сравниваются без учета минимального уровня зума.
=> [drape] Fixed overlay priority comparison for text path shapes

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/nvidia/devtech/NvEventQueueFragment.java, graphics/defines.cpp, graphics/defines.hpp, graphics/glyph_cache.cpp, graphics/glyph_cache.hpp, graphics/glyph_cache_impl.cpp, graphics/resource_manager.cpp, graphics/resource_manager.hpp, gui/controller.cpp, gui/controller.hpp, iphone/Maps/Classes/EAGLView.mm, iphone/Maps/maps.me WatchKit Extension/FrameworkUtils/MWMFrameworkUtils.mm, map/framework.cpp, map/framework.hpp, qt/draw_widget.cpp, render/render_policy.cpp, render/render_policy.hpp
Данный PR позволяет вычислять visualScale на базе более точных значений dpi, чем это было раньше. Что в свое очередь позволяет отображать тексты на карте и толщины линий почти одинаковыми в миллиметрах на экранах разного разрешения.
Замечания:
1. Ввиду большого размера и низкого разрешения iPad 2 для лучшей читаемости тестов для подобных девайсов используется специальная поправка для visualScale;
2. Для drape будет подготовлен отдельный PR;
https://trello.com/c/DRnhWD70/2045-dpi
=> Calculation visualScale based on more exact dpi.

configure.sh, data/faq.html
Fixes issue with a crash mentioned in #559, when Flurry key is empty (internal Flurry library check for empty string).
=> Minor faq & configure script fixes.

android/src/com/mapswithme/maps/routing/RoutingInfo.java, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardEntity.mm, routing/osrm_router.cpp, routing/routing_integration_tests/osrm_route_test.cpp, routing/routing_integration_tests/osrm_turn_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_tests/turns_generator_test.cpp, routing/routing_tests/turns_tts_text_tests.cpp, routing/turns.cpp, routing/turns.hpp, routing/turns_generator.cpp, routing/turns_generator.hpp, routing/turns_tts_text.cpp, std/cmath.hpp
https://trello.com/c/FCT2moyo/2050--
Добавляет поддержку разворотов в легенду для роутинга. Для того чтобы добавить эту функциональность, пришлось провести рефакторинг процедур построения легенды маршрута.
PR добавляет 2 состояния разворота : UTurnLeft и UTurnRight (для стран с правосторонним движением).
=> [routing] Uturns support.

platform/local_country_file_utils.cpp, platform/platform_tests/local_country_file_tests.cpp, routing/routing_integration_tests/cross_section_tests.cpp, routing/routing_integration_tests/routing_test_tools.cpp
https://trello.com/c/ou4IMisg/2063-ui
This is wrong to try to add maps newer than the app, because:
* Newer maps can not be supported by the app, but all older maps already have been deleted.
* Even if they're supported by the app, it'll be suggested to user to update them, because app version is not equal to newer maps version. All these updates will be discarded after downloading.
=> [platform] Do not add/register maps newer than App.

drape/drape.pro, drape_frontend/drape_frontend.pro
It should fix build errors on Drape.
Technically, libraries do not depend on each other and can be built in parallel. Dependencies are needed only when libraries are linked to any executable.
=> Fixed drape qmake dependencies.

iphone/Maps/Classes/CustomViews/MapViewControls/Search/TableView/MWMSearchTableViewController.mm
- Пришлось отказаться от колесика когда идет поиск в окне карты
- При вводе букв в окне карты пришлось сделать так что сначала чистятся старые результаты на карте, потом идет поиск, потом добавляются новые. На слабых девайсах может быть временный лаг.
=> [iOS][search] Fixed logic while editing search query in the map view.

android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
При пересоздании drape engine терялась информация о показе метки.
=> [drape] Show bookmark android fix.

iphone/Maps/Classes/EAGLView.mm
cherry-pick https://github.com/mapsme/omim/pull/677
https://trello.com/c/6J3BeR4U/2080-ios-pois
=> iOS. Bugfix. POIs icons were overlapped with text.

routing/osrm_data_facade.hpp, routing/osrm_router.cpp
PR не выгружает роутинг индексы текущей карты, чтобы роутингу на 7ой iOS хватало памяти при перестроении маршрута.
=> [routing] iOS no memory routing fix.

drape/drape.pro, drape_frontend/drape_frontend.pro, generator/generator_tests_support/generator_tests_support.pro, stats/stats.pro
Static libs don't need our DEPENDENCIES macro. It should be used for binaries projects only.
=> Removed not needed dependencies for static libraries, which only slow down the build.

drape_frontend/read_mwm_task.cpp, drape_frontend/read_mwm_task.hpp
Использование weak_ptr внутри таски, чтобы не держать память под уже ненужный TileInfo.
=> [drape] Free tile info immediately on cancel.

tools/unix/find_generator_tool.sh, tools/unix/generate_planet.sh, tools/unix/generate_planet_routing.sh
Рефакторинг скрипта `generate_planet_routing.sh` и немного фиксов для удобства:
* Поиск generator_tool теперь знает про xcode.
* В скрипте роутинга включен режим `set -e`, просто для порядка.
* Обработка флага osrm_done выкорчевана из скрипта роутинга, осталась в `generate_planet`.
* Добавлен флаг osrm_done_pbf, чтобы не пересобирать pbf, если сломалась сборка osrm.
* Не работало указание `DATA_PATH`.
* Нормально определяем количество процессоров в маке.
* Ещё опечатался: сборка планеты требует не 250 МБ, а 250 ГБ.
=> [generator] Multiple fixes, mostly for routing

base/base.pro, base/base_tests/base_tests.pro, base/base_tests/timegm_test.cpp, base/base_tests/timer_test.cpp, base/timegm.cpp, base/timegm.hpp, base/timer.cpp
timegm() is not a standard function and may be missed on some platforms.
This request provides custom realization.
=> String to timestamp and timestamp to string

platform/location.hpp, routing/routing_session.cpp
Фикс не инициализированных полей для FollowingInfo. Иногда это приводит к крешу на андройде.
=> Routing following info fix.

routing/routing_integration_tests/osrm_turn_test.cpp, routing/turns_generator.cpp
https://trello.com/c/WG2mTxLB/2114-android
Фикс указания разворота в районах где есть много местных дорог с одинаковыми тегами, которые делят район на квадраты. Интеграционные тесты прилагаются.
=> UTurn fix.

drape_frontend/watch/cpu_drawer.hpp, map/framework.cpp, map/framework.hpp, routing/road_graph.cpp, routing/road_graph.hpp
FeatureID has heavy shared_ptr copying. It's better and faster to pass it by const reference.
=> Avoid heavy and unnecessary FeatureID copying.

tools/run_desktop_tests.py
The idea is to run boost and non-boost tests separately on our build-servers so that we can process their results differently and not make the test runner script overly complicated.
The output xml will be processed by a jenkins plugin instead of a java programme.
=> Process boost tests in python.

drape_frontend/drape_frontend_tests/user_event_stream_tests.cpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp, iphone/Maps/Classes/MapViewController.mm
Возвращено использование force touch в приложение (теперь FT не заменяет длительное нажатие, а дополняет его)
=> Fixed force touch

android/src/com/nvidia/devtech/NvEventQueueFragment.java
На двух девайсах
High screen Boost 2 SE
Xiaomi Red Rice 1s
способ точного получения dpi возвращал не корректные значения. Вернем приближенный способ получения dpi, который был в прежних версиях.
Отдельно хочу отметить, что на девайсах со сверх высоким dpi названия на карте должны остаться читаемыми.
https://trello.com/c/pIbsel7z/2131-android
=> [FOR ANDROID BUGFIX RELEASE] An approximate (but reliable) way getting dpi.

map/gps_track_file.cpp, map/gps_track_file.hpp, map/map.pro, map/map_tests/gps_track_file_test.cpp, map/map_tests/map_tests.pro, platform/location.hpp, std/fstream.hpp
Этот файл нужен для записи сырых данных gps треков при незапущенном приложении и записи в запущенном приложении с целью восстановления трека после падения приложения.
В файл циклически записываются точки gps трека, при overflow выкидываются старые точки, сохраняются новые точки. каждая точка при добавлении получает уникальный идентификатор, при выкидывании старых точек (Clear, DropEarlierThan или Append) возвращаются их идентификаторы.
Файл бинарный и не требует разбора в отличие от gpx и nmea.
Файл может быть экспортирован/импортирован в/из gpx или nmea.
В отличие от #833, этот реквест содержит только реализацию файла.
=> [gpstracks] Gps track file

omim.pro
На серверах для сборки карт я собираю omim с ключом `CONFIG=gtool`. Там из-за недавнего улучшения тестов не хватает одного исполняемого файла. Этот PR добавляет его в сборку.
=> [build] Build routing consistency tests for gtool project

coding/file_container.cpp, routing/osrm_data_facade.hpp, routing/osrm_router.cpp
https://github.com/mapsme/omim/issues/654
We will not unmap the routing facade for the current map while routing is active. iOS7 often returns NOMEM error when we are trying to map the fano matrix section.
=> Nomem routing fix.

drape/drape_tests/drape_tests.pro, drape/drape_tests/glfunctions.cpp, drape_frontend/drape_frontend_tests/drape_frontend_tests.pro, map/style_tests/style_tests.pro
This patch is needed mostly for sanitizer. We need these dependencies only because address sanitizer does not work with dead code elimination at link time (https://github.com/google/sanitizers/issues/260). This patch does not affect release build or build to mobile clients.
=> [build] Fixes to linux build.

docs/MAPS.md, tools/unix/generate_mwm.sh
It seems that ```generate_mwm.sh``` is unable to compile ```osmconvert``` with GNU C Compiler 4.8.4 on Ubuntu 14.04 if -lz is provided as an early argument. It fails with the error message ```undefined reference to `gzopen'```
~~Also I added boost-libraries to the docs. This is not ultimately neccessary as the build fails with appropriate messages if the libraries are unavailable and can be reverted if seen fit.~~
=> fix generate_mwm

docs/INSTALL.md
I added libraries to the docs required on a fresh Ubuntu 14.4 in order to compile out-of-the-box.
( Sorry for the inconvenience of the previous pull-request, it should be the correct position in the docs now I hope! )
=> fix generate_mwmoc

drape_frontend/frontend_renderer.cpp
Исправлено выделение объекта на Android (в редких случаях старый код мог приводить к крэшу, если графический движок не успевал инициализироваться)
=> Fixed POI selection on Android

drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/read_manager.cpp, drape_frontend/rule_drawer.cpp, drape_frontend/rule_drawer.hpp, drape_frontend/tile_info.cpp, drape_frontend/tile_key.cpp, drape_frontend/tile_key.hpp
На 18 и 19 зумах ранее создавались логические тайлы, размеры которых были меньше, чем позволяла система вычитки (там максимум - 17ый зум). Это приводило к тому, что в тайл объединялись большие области карты вне фактического размера тайла, что, в свою очередь, приводило к избыточным перевычиткам. Это проявлялось в том числе как мигание больших областей карты при драге.
Сейчас на 18 и 19 зумах используются тайлы такого же размера, как и на 17 уровне зума. При этом при смене уровней зума происходит обновление геометрии в полном соответсвии со стилями.
Необходимо протестировать на разных девайсах перед мержем!
=> Improved tiles loading on 17-19 zoom levels

generator/coastlines_generator.cpp
This reverts commit 71f0b98f306e198b5757e6f89f0dc886d9bbd2e3.
=> Revert "[generator] Set maximum points per coastline feature to 1000."

search/reverse_geocoder.cpp, search/reverse_geocoder.hpp, search/search_tests/house_numbers_matcher_test.cpp, search/v2/features_layer.hpp, search/v2/features_layer_matcher.cpp, search/v2/features_layer_matcher.hpp, search/v2/features_layer_path_finder.cpp, search/v2/features_layer_path_finder.hpp, search/v2/geocoder.cpp, search/v2/house_numbers_matcher.cpp, search/v2/search_model.cpp, search/v2/search_model.hpp, search/v2/street_vicinity_loader.cpp
This CL includes following fixes:
* fix to house numbers matching --- all tokens from query must be matched in feature.
* fix to lookup radius - now it's shared between ReverseGeocoder and Geocoder.
* fix to matching algorithm - optimized layers intersection, now DFS is incorporated into layers intersection.
* fixed architecture - stack of layers is constant now and can't be modified by path finder or matcher.
=> [search] Numerous fixes to Geocoder (search query v2).

iphone/Maps/Classes/CustomViews/NavigationDashboard/Sound/MWMTextToSpeech.mm, iphone/Maps/Classes/MapsAppDelegate.mm
Звуковое сопровождение по маршруту на iOS 8 и более ранних теперь работает.
https://trello.com/c/zLxxqY8n/2182-ios-8-ios-7
=> iOS. Bugfix. Playing TTS on iOS 8 and earlier.

qt/main.cpp, std/cstdio.hpp, std/cstdlib.hpp
Fixes crashes on desktop project startup on some systems, if locale has comma delimiter for float numbers.
=> Float parsing workaround.

drape/font_texture.cpp, drape_frontend/visual_params.cpp
Исправлены артефакты при выборке из текстуры глифов, когда глиф при выборке захватывал часть другого глифа
=> Fixed artefacts on fetching from symbols texture

search/search_query_factory.hpp
Usage of USE_SEARCH_QUERY_V2 macro makes it hard to build new-search version for platforms. I think it would be nice to enable it by default, as it lives on a separate branch.
=> [search] Enable SearchQueryV2 by default.

drape_frontend/gui/country_status.cpp
Добавлено прекеширование глифов для отображения прогресса скачивания страны. Может исправить редкий баг с непоявлением прогресса
=> Added progress symbols precaching

map/gps_track_storage.cpp, map/map_tests/gps_track_storage_test.cpp, map/map_tests/gps_track_test.cpp
С целью анализа и отладки фильтра файл данных надо иметь возможность открывать файл на любой платформе, поэтому способ копирования POD структур в файл не подходит так как разное выравнивание полей на разных платформах. Поэтому способ записи полей в файл изменен. Теперь файлы кросс-платформенные.
=> [gpstracks] write gpstrack file in platform independent format

map/gps_tracker.cpp
Для тестовых целей предполагается, что gps tracking включен по умолчанию, глубина 48 часов.
=> Test: use 48h duration gps track and assume it enabled by default

routing/routing_integration_tests/osrm_turn_test.cpp, routing/turns_generator.cpp
https://trello.com/c/LFDaNJUR/2178-routing
Фикс рассчёта номера съезда. Теперь как съезд учитываются все дороги кроме highway=service.
Интеграционные тесты прилагаются.
=> Roundabout exit number fix.

routing/routing_integration_tests/osrm_turn_test.cpp, routing/turns_generator.cpp
https://trello.com/c/ZAit79Gj/2202--
Фикс определения разворота через примыкающий проезд на себя.
Тест прилагается.
=> Turnaround direction fix.

omim.pro, search/search_integration_tests/search_integration_tests.pro, search/search_integration_tests/smoke_test.cpp, search/search_tests_support/search_tests_support.pro, search/search_tests_support/test_search_engine.cpp, search/search_tests_support/test_search_engine.hpp, search/search_tests_support/test_search_request.cpp, search/search_tests_support/test_search_request.hpp
Идея аналогична platform_tests_support.
Сейчас это нужно для тестирования поиска без запуска framework'а. Более аккуратно эта работа проведена на ветке new-search, поэтому в этом PR только самое необходимое.
=> [search] Moved out common test code to search_tests_support.

routing/routing_consistency_tests/routing_consistency_tests.cpp
Фикс падения теста роутинга по открытию слишком большого числа файлов.
https://trello.com/c/w9EfiGqI/2190-consistency-tests
=> Consistency test too many open files fix.

android/jni/com/mapswithme/opengl/android_gl_utils.cpp, android/jni/com/mapswithme/opengl/android_gl_utils.hpp
При создании EGL контекста выбирались параметры backbuffer'а с ненулевой альфой. Это приводило к аду при альфа-блендинге. Теперь в приоритете выбирается конфигурация backbuffer'а без альфы.
Надо проверить на других Андроидах, что все в порядке.
=> Fixed EGL context creation which led to artifacts on Meizu MX4

3party/osrm/osrm-backend/profile.lua, 3party/osrm/osrm-backend/profiles/car.lua, routing/routing_integration_tests/osrm_turn_test.cpp
https://trello.com/c/XB4C9EfX/2144--
Добавляет замедление при учёте боковых проездов в OSRM профиле для машин.
=> A side_road tag support for the OSRM car profile.

drape/drape_tests/compile_shaders_test.cpp, drape/drape_tests/glfunctions.cpp, drape/drape_tests/glmock_functions.hpp, drape/glconstants.cpp, drape/glconstants.hpp, drape/glfunctions.cpp, drape/glfunctions.hpp, drape/glstate.cpp, drape/gpu_program_manager.cpp, drape/gpu_program_manager.hpp, drape/shaders/route_fragment_shader.fsh, drape/texture_manager.cpp, drape/texture_manager.hpp, drape_frontend/route_shape.cpp
Черрипик одноименного коммита с ветки gps-tracks-3 (3Д-навигация теперь релизится раньше, а этот коммит нужен еще и для ветки drape-3d-view).
Оригинальный PR - https://github.com/mapsme/omim/pull/985
=> Fixed GPS track rendering on Samsung Galaxy Nexus

tools/autobuild/build.sh
Typical error appears when some new source files were added on a one branch and are missing on another one. Another possible fix would be to create an unique build folder for each branch to avoid their sharing, but it's a bigger overhead.
We had correct implementation for years but it was changed around a year ago to make builds faster.
I prefer to have slower but stable builds than faster but unstable.
=> Restored qmake call for all Android and iOS builds to fix build errors when switching branches in git.

data/countries.txt
Файл планеты тот же, что и в прошлый раз, от 16 декабря. Видимо, поэтому размер `World*.mwm` не поменялся.
=> [planet][new-search] Update maps, build from December 25 checkout

routing/routing_mapping.hpp
Фикс некорректного кода ошибки в ситуации, когда по точке не получилось определить карту.
=> Routing no map error code fix.

3party/3party.pro, tools/unix/build_omim.sh
Мелкая правка сборки в профилях, которые вы всё равно не используете. Ускоряет сборку `gtool` минут на десять, отключая тесты opening_hours, и слегка ускоряет сборку osrm.
=> [build] Disable opening_hours tests for gtool profile

routing/routing_mapping.hpp
https://trello.com/c/HfH28zBP/2223-warning-fix-routingmapping
=> Warning fix. Correct order of values in init list of constructor.

drape_frontend/apply_feature_functors.cpp, drape_frontend/text_shape.cpp, drape_frontend/text_shape.hpp
Для номеров дорог на карте теперь не учитывается минимальный уровень зума при расчете приоритетов оверлеев. Решение аналогичное подписям на дорогах.
=> Fixed road numbers' priority calculation

map/framework.cpp, map/framework.hpp, storage/country.cpp
1. Исправление ошибки. При переходе на строчный индекс он не корректно работал в случае старых mwm, если в countries.txt различались поля "n" и "f".
2. Восстановление показа кнопок загрузить карты.
https://trello.com/c/jIMM984W/2231--
=> [Map downloader] Button on map downloading recovering.

drape_frontend/backend_renderer.cpp, drape_frontend/drape_engine.cpp, drape_frontend/gui/country_status_helper.cpp, drape_frontend/gui/country_status_helper.hpp, drape_frontend/map_data_provider.cpp, drape_frontend/map_data_provider.hpp, map/framework.cpp, map/framework.hpp, qt/draw_widget.cpp, qt/update_dialog.cpp, qt/update_dialog.hpp, storage/country.hpp, storage/index.cpp, storage/index.hpp, storage/queued_country.cpp, storage/queued_country.hpp, storage/storage.cpp, storage/storage.hpp, storage/storage_tests/queued_country_tests.cpp, storage/storage_tests/storage_tests.cpp
Для идентификации mwm (или группы) мы используем строчный id. 
За ним закреплено имя TIndex. Кроме того вместе с новым интерфейсом прибыло имя node id.
Я переименовал все эти имена в CountryId. Для сохранения консистентности переименованы соответствующие локальные переменные и данные члены класса.
Это сделано, т.к. TIndex - очень общее имя, определено по разному в разных подсистемах и не совсем точно передает смысл, на мой взгляд.
https://trello.com/c/ikSl5kF2/2234-tindex-nodeid
=> [Map downloader] Renaming TIndex, node id and so on to TCountryId.

android/res/values-sv/strings.xml, iphone/Maps/sv.lproj/Localizable.strings, strings.txt
Change: Get --> Ge
"Get" means goat in Swedish. Ge means "give", which is correct.
Also add translation for Compass calibration.
=> Improve Swedish translation

tools/integration_tests_runner.py, tools/run_desktop_tests.py
Allows to run (integration) tests in parallel, reducing the total running time from 8 hours to about 2 (depending on the number of cores). Could be modified to run the rest of the tests as well, but later.
=> Py integration parallel

pedestrian_routing_tests/pedestrian_routing_tests.cpp
По просьбе Тимофея выключил несколько интеграционных тестов для пешеходного роутинга. Эти тесты не критичны и мы можем обойтись без них в ночных сборках.
=> Comment some slow pedestrian tests.

drape/drape_tests/glfunctions.cpp, drape/glconstants.cpp, drape/glconstants.hpp, drape/glextensions_list.cpp, drape/glextensions_list.hpp, drape/glfunctions.cpp, drape/glfunctions.hpp, drape/glstate.cpp, drape/render_bucket.hpp, drape/vertex_array_buffer.hpp, drape_frontend/batch_merge_helper.cpp, drape_frontend/batch_merge_helper.hpp, drape_frontend/drape_frontend.pro, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/render_group.hpp
Копия https://github.com/mapsme/omim/pull/1069 с ребейзом на свежий мастер
Что это и зачем надо:
У drape есть одна болезнь - фрагментация данных по разным батчам. Это значит геометрия которая может быть отрисована за один drawCall рисуется за много.
Как это происходит:
1) На некотором тайле слишком много однотипной информации и она не влазит в наш стандартный батч 5к на 5к (индексов надо бы поставить 7к), поэтому мы разбиваем геометрию на несколько батчей что бы быстрее показать пользователю картинку.
2) Пользователь активно драгает карты не меняя масштаба. Это приводит к переодическим дочиткам геометрии, которая кладется в отдельный батч, в результате чего со временем фпс падает, что хорошо заметно на густых областях.
Решение простое: раз в 60 кадров собираем геометрию которую можно …
=> [DO NOT MERGE] merge batches on iOS and desktop

map/framework.cpp, routing/osrm2feature_map.cpp, routing/osrm2feature_map.hpp, routing/osrm_helpers.cpp, routing/routing_session.cpp, routing/routing_session.hpp
https://trello.com/c/MZ1O0SaH/265-3d-view-3d
Дополнительный состояние роутинг сессии, которое определяет состояние программы после нажатия кнопки "Старт" на маршруте. Нужно для правильного включения 3d режима.
=> Routing follow state

android/jni/com/mapswithme/opengl/android_gl_utils.cpp, android/jni/com/mapswithme/opengl/android_gl_utils.hpp, android/jni/com/mapswithme/opengl/androidoglcontextfactory.cpp
Исправлен выбор параметров контекста. Должно помочь с бедой с альфаканалом, которую видели на Samsung S4 mini.
=> Fixed OpenGL context creation on Android

data/hierarchy.txt, data/old_vs_new.csv, tools/python/hierarchy_to_countries.py, tools/unix/generate_planet.sh
Собственно, вот как выглядит исходный файл иерархии mwm, из которого получается `countries.txt`, все переводы и т.п. Этот PR меняет систему построения файла countries.
=> Hierarchy.txt and a script to create countries.txt from it

platform/local_country_file.hpp, platform/local_country_file_utils.cpp, platform/local_country_file_utils.hpp, platform/platform_tests/local_country_file_tests.cpp, routing/routing_integration_tests/cross_section_tests.cpp, routing/routing_integration_tests/routing_test_tools.cpp, storage/storage.cpp, storage/storage.hpp, storage/storage_tests/storage_tests.cpp
Данный PR позволяет создавать несколько экземпляров Storage с разными countries.txt и скачивать карты при помощи них в разные директории.
Это нужно, поскольку до обновления, работая с большими mwm, нам необходимо перед началом обновления, скачать маленькую mwm около клиента.
@syershov @ygorshenin @vng @deathbaba посмотрите по возможности.
https://trello.com/c/KaGuXfOM/2255-storage-counries-txt
=> [Downloader] Parametrization Storage with countries.txt file name and with downloading folder.

android/src/com/mapswithme/maps/bookmarks/data/Metadata.java, drape_frontend/rule_drawer.cpp, generator/generator_tests/metadata_parser_test.cpp, generator/osm2meta.cpp, generator/osm2meta.hpp, indexer/feature_meta.hpp
Разделил сохранение в метаданные height и building:levels. Поправил рендерер, чтобы читал оба значения.
=> [metadata] Split height and building:levels

drape_frontend/frontend_renderer.cpp, indexer/classificator.cpp, indexer/classificator.hpp, indexer/classificator_loader.cpp, indexer/drawing_rules.cpp, indexer/drawing_rules.hpp
При изменении стиля происходит переинициализация classificator, который может использоваться в search. в этом случае возникает крэш.
=> Fixed crash on style change

routing/osrm_router.cpp, routing/route.cpp, routing/route.hpp, routing/routing_integration_tests/online_cross_tests.cpp, routing/routing_integration_tests/routing_test_tools.cpp
https://trello.com/c/wmKPRzvU/2254-online-routing
фиксит нахождение страны без названия (и вылет по ассерту в дебаге), если строить маршрут в центр моря.
+ Фиксит работу интеграционных тестов с новым онлайн сервером.
=> Online routing fixes

data/faq.html
Deleted Blue Stack player reference, since it doesn’t work with current version from Google Play
=> F.A.Q. update

tools/python/hierarchy_to_countries.py, tools/unix/generate_planet.sh
Основное, что PR добавляет, это указание номера версии в параметрах скрипта, делающего `countries.txt`. Это потребовало переработки системы указания параметров, что позволило сделать вызов в `generate_planet.sh` более наглядным.
Кроме того, теперь скрипту генерации планеты можно передать версию данных в ключе `VERSION` (едва ли кому пригодится), и скрипт создания countries не записывает пустые группы: если обрабатывали не все mwm, а какое-то подмножество, в итоговом countries.txt будет только оно.
=> [generator] Add version parameter to planet generator

generator/osm2meta.cpp
Сообщения о неправильных значения тега `wikipedia` замусоривают лог, и ничего не дают тем, кто его читает. Не будем же мы бросаться исправлять в планете все криво записанные адреса вики. Алгоритм хорошо парсит правильные значения тега, большего и не нужно.
=> [generator] Demote log message about invalid wikipedia tag value

routing/routing_integration_tests/online_cross_tests.cpp, routing/routing_integration_tests/routing_test_tools.cpp
Починил интеграционные тесты для маленьких mwm и нового packed_polygons.bin. Всё должно работать после обновления OSRM на наших серверах (а большая часть тестов начнёт работать и до обновления) и сразу с внутреннего сервера OSRM. Важный коммит последний. Первые 2 - это cherry-pick нужных изменений с мастера.
=> Downloader online fixes

map/map_tests/bookmarks_test.cpp
New geocoder (and editor branch too) does not use name and type fields of AddressInfo structure.
It will be refactored on the editor branch to contain only address-related fields.
=> Fixed tests. AddressInfo does not have name and type now.

data/faq.html
It caused errors like:
```
01-18 17:34:34.478 I/chromium( 3807): [INFO:CONSOLE(5)] "The value "device-width;" for key "width" is invalid, and has been ignored.", source: file:///android_asset/faq.html (5)
01-18 17:34:34.478 I/chromium( 3807): [INFO:CONSOLE(5)] "The value "1.0;" for key "initial-scale" was truncated to its numeric prefix.", source: file:///android_asset/faq.html (5)
01-18 17:34:34.478 I/chromium( 3807): [INFO:CONSOLE(5)] "The value "1.0;" for key "maximum-scale" was truncated to its numeric prefix.", source: file:///android_asset/faq.html (5)
01-18 17:34:34.478 I/chromium( 3807): [INFO:CONSOLE(5)] "Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.", source: file:///android_asset/faq.html (5)
```
=> Fixed syntax error in meta viewport tag.

routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/routing_session_test.cpp
https://trello.com/c/LHYf6H68/2285-3
Вынес флаг того, что кнопка start нажата в отдельную переменную. Теперь, если в процессе езды по маршруту его нужно перестроить, то мы не теряем информацию о следовании по маршруту. + тест на эту логику.
=> Extract following flag from routing session state.

map/gps_track_storage.cpp
1. gcc < 5 does not support move ctor for fstream;
2. missed include for memcpy.
=> [build] Fixed compilation errors

platform/local_country_file.cpp
Предотвращение повторного удаления *.mwm файла при однокомпонентных (мелких) mwm.
Что убрало ASSERT при запуске Storage tests.
https://trello.com/c/qQxQrDBl/2322-mwm-2-mwm
@syershov PTAL
=> [old map downloader] Fixing assert in Storage tests.

configure.sh, tools/unix/build_omim.sh
Снова люди пытаются собрать проект, забыв про `configure.sh`. Поэтому я добавил проверку на наличие нужных файлов прямо в скрипт сборки.
Заодно поправил ошибку при запуске `configure.sh` не из каталога omim.
=> [build] Check for private.h in build_omim.sh

android/res/values-de/strings.xml, iphone/Maps/de.lproj/Localizable.strings, strings.txt
В немецком строчки Вкл и Выкл были перепутаны. Исправил.
=> Fix german night strings

README.md, docs/INSTALL.md
Пользователи заметили, что еженочные сборки для iOS отключены. Также, добавил пару заметок про сборку проекта под Fedora Linux.
=> [docs] No iOS nightly builds; building instructions for Fedora 23

drape_frontend/color_constants.cpp, drape_frontend/color_constants.hpp, drape_frontend/drape_engine.cpp, drape_frontend/gui/button.cpp, drape_frontend/gui/button.hpp, drape_frontend/gui/compass.cpp, drape_frontend/gui/copyright_label.cpp, drape_frontend/gui/country_status.cpp, drape_frontend/gui/country_status_helper.cpp, drape_frontend/gui/country_status_helper.hpp, drape_frontend/gui/gui_text.cpp, drape_frontend/gui/gui_text.hpp, drape_frontend/gui/layer_render.cpp, drape_frontend/gui/layer_render.hpp, drape_frontend/gui/ruler.cpp, drape_frontend/gui/shape.cpp, drape_frontend/gui/shape.hpp, drape_frontend/gui/skin.hpp, drape_frontend/map_data_provider.cpp, drape_frontend/map_data_provider.hpp, iphone/Maps/Classes/MapViewController.mm, map/framework.cpp, map/framework.hpp
Что есть в этом пулреквесте:
1) Добавлена кнопка "Отменить" скачивание;
2) Добавлен колбэк на отмену скачивания;
3) Добавлен колбэк на автоматическое скачивание карты.
Чего нет и не будет в этом пулреквесте (доверим это специалистам):
1) Реализации колбэков в платформенно-зависимом коде (для iOS, правда, добавлены заглушки для тестирования);
2) JNI оберток для добавленных колбэков;
3) Добавления строки локализации для кнопки "Отменить".
Особо хочу заострить внимание, что в реквесте код, который должен прожить ровно один релиз и потом будет выкинут. Поэтому прошу комментировать по-существу, без ревью-нацизма. 
Не мержить реквест! Этот реквест только для ревью. После слияния old-map-downloader, будет создан новый PR на new-search, который и будем мержить.
=>  [old-map-downloader] Added cancel button and auto-downloading callback

indexer/osm_editor.cpp
Fixes possible crash for mwm migration case,
=> [editor] Temporarily ignore edited features from old mwm files.

platform/local_country_file.cpp, search/search_integration_tests/retrieval_test.cpp, search/search_integration_tests/smoke_test.cpp, search/search_quality_tests/search_quality_tests.cpp
Migration to small MWMs conicided with removing separate
routing files (thus incorporating routing into regular map files).
This CL fixes the corresponding behaviour of search integration tests.
Also, fixed quality tests to account for a new World file.
=> [search] Fixed tests.

android/build.gradle, android/gradle.properties, data/external_resources.txt
Пока не понял, почему размеры World[Coasts].mwm отличались от реально лежащих в папке data/*, поменял на актуальные размеры.
Так же вернул 07_roboto_medium в список внешних ресурсов.
=> Obb for worldcoasts_migrate.

map/style_tests/classificator_tests.cpp
It seems the compilation fails due to case-sensitivity under Linux.
=> case-sensitive search on linux-systems

base/buffer_vector.hpp, indexer/feature_impl.cpp, indexer/feature_impl.hpp, search/search_string_utils.cpp, search/search_tests/house_numbers_matcher_test.cpp, search/v2/cbv_ptr.cpp, search/v2/cbv_ptr.hpp, search/v2/features_layer.cpp, search/v2/features_layer.hpp, search/v2/features_layer_matcher.hpp, search/v2/features_layer_path_finder.cpp, search/v2/geocoder.cpp, search/v2/geocoder.hpp, search/v2/house_numbers_matcher.cpp, search/v2/house_numbers_matcher.hpp
During greedy street matching we need to spawn sub-calls to MatchPOIsAndBuildings() each time we met a token that looks like a start of a house number. For example, on a query "тверь советская 1" тверь will be matched to a city, but as there exists "1-я советская улица", current implementation will consume both tokens, whereas the user's intent is to find house No1 on the sovetskaya street in Tver.
=> [search] Fixed greedy street matching.

data/categories.txt
I have two feature requests for the translations:
* Split up the shops a bit more, and add some more types. Currently there are a lot of shops that just fall under "shop"
* Get rid of the religion translation. F.e. a Christian religious place can be anything from a wayside cross over a chapel to a cathedral. So I can't just put "church", as in a well-mapped area, most of the religious places will be the smaller wayside crosses and shrines. An existing proposal to solve this is by using the tag place_of_worship:type=* (see http://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dplace_of_worship#place_of_worship:type_.28Chapels.2C_Small_POWs.29 and http://taginfo.openstreetmap.org/keys/place_of_worship%3Atype#overview ). it would be nice if this could be supported instead of the religion tag. …
=> Improving Dutch translations

platform/local_country_file.cpp, platform/local_country_file.hpp, routing/routing_mapping.cpp, routing/routing_tests/routing_mapping_test.cpp
Перенос изменений из map-downloader в new-downloader.
Поправил тесты на роутинг.
https://trello.com/c/E8Oy10Ka/2442-routing
@gardster @syershov @kshalnev PTAL
=> [new downloader] Fixing routing tests. Compatibility local_country_files with two components mwms.

drape_frontend/stylist.cpp
PR fixes France capital caption. Now it is shown as 'Paris (19)' because capital POI has a house number.  Fix is: construct main text as "name (houseNumber)" only for buildings.
=> Do not shown house number if name exists

tools/run_desktop_tests.py
It turns out that the server or the downloader tests would sometimes fail if the tests are run immediately after the server has been started.
=> Added a timeout after server start.

storage/country.cpp, storage/country.hpp, storage/storage.cpp, storage/storage_tests/storage_tests.cpp
Вычисление и сохранение родительского country id для каждого узла дерева.
Доработка метода Storage::GetNodeAttrs()
https://trello.com/c/b2VCAKE9/2449-storage-getnodeattrs
@syershov и(или) @kshalnev по возможности посмотрите.
=> [new downloader] Keeping parent id while parsing countries.txt

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, iphone/Maps/Classes/EAGLView.mm, iphone/Maps/Classes/MapViewController.mm, map/framework.cpp, map/framework.hpp, platform/platform.cpp, qt/draw_widget.cpp, qt/draw_widget.hpp, qt/mainwindow.cpp, qt/mainwindow.hpp
@yunikkk Please check out SimulateLastTapEventIfNeeded() method. It is already called now right after Drape engine is created (and it is always recreated when you start maps activity). You should automatically get correct callback with UserMark at CallOnUserMarkActivated
@vng @rokuz please take a look too.
=> Framework refactoring for correct Android events handling.

tools/integration_tests_runner.py
Now we pass the path to a temporary folder as a parameter to the search_integration_tests, but so far they ignore this key.
=> Added the line lost while cleaning up the code, plus some debug logging.

indexer/indexer.pro
Cherry-pick. See https://github.com/mapsme/omim/pull/1873.
=> Fixed misprint: .cpp -> .hpp

map/framework.cpp, qt/search_panel.cpp, storage/storage.cpp, storage/storage.hpp, storage/storage_integration_tests/migrate_tests.cpp
Added thread checker to check:
- observers are used from the main thread
- downloading queue is used from the main thread
=> [new downloader] Added thread checkers in Storage

android/jni/com/mapswithme/maps/MapManager.cpp, geometry/geometry_tests/tree_test.cpp, iphone/Maps/Classes/MapDownloader/Cells/MWMMapDownloaderTableViewCell.mm, iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm, qt/update_dialog.cpp, qt/update_dialog.hpp, storage/country.cpp, storage/country.hpp, storage/country_tree.hpp, storage/index.hpp, storage/simple_tree.hpp, storage/storage.cpp, storage/storage.hpp, storage/storage.pro, storage/storage_defines.cpp, storage/storage_defines.hpp, storage/storage_tests/simple_tree_test.cpp, storage/storage_tests/storage_tests.cpp
В этом PR реализован ряд вещей:
1. Вызываются колбеки прогресса загрузки для групповых и для обычных mwm;
2. Удален статус Mixed и вместо него для групповых узлов приходят статусы согласно ТЗ; (https://confluence.mail.ru/display/MAPSME/Maps+downloader+v3)
3. Метод GetNodeAttrs заполняет поля структуры, кроме недавно появившегося поля m_present;
PR рекомендую смотреть по коммитам. Комментарий к каждому коммиту поясняет, что сделано.
Тикеты:
https://jira.mail.ru/browse/MAPSME-76
https://jira.mail.ru/browse/MAPSME-75
Перенесен с https://github.com/mapsme/omim/pull/1941
Замечания учтены.
=> [new downloader] Statuses. Downloading progress. GetNodeAttrs.

platform/preferred_languages.cpp
На некоторых системах переменная окружения `LANGUAGE` может быть установлена, но равна пустой строке. В этом случае тоже нужно проверять дальше по списку.
=> [platform] Fix language detection on some linux systems

storage/storage.cpp, storage/storage.hpp
Вызов колбеков на изменение статуса не только для текущего элемента, но и для предков в дереве стран.
Этот PR дорабатывает тикет: https://jira.mail.ru/browse/MAPSME-75
@kshalnev @syershov PTAL
=> [new downloader] Calling status change callback in Storage for ancestors.

base/thread_checker.hpp
С архитектурой DRAPE очереди NV больше нет, мы можем использовать ThreadChecker.
=> Use THREAD_CHECKER under Android

generator/coastlines_generator.cpp, generator/feature_builder.cpp, generator/feature_builder.hpp
Меня задолбало, что при ошибке мёржа костлайнов присылается длиннющая бесполезная простыня. Этот PR заменяет сообщение на простое, с идентификаторами только крайних линий.
=> [generator] Shorter error message for unmerged coastline

storage/storage.cpp, storage/storage_tests/storage_tests.cpp
Привел статусы загрузки для групповых mwm:
This section contains list of previously downloaded maps with their current statuses: (listed according to priority in case of group mwms) in any kind of download process, update available or some errors exist, up-to-date with no fragments to download and up-to-date with some fragments to download. Groups of mwms inherit their statuses.
@igrechuhin @syershov  PTAL
https://jira.mail.ru/browse/MAPSME-22
=> [new downloader] Calculating for statuses for group mwm.

platform/platform_tests/mwm_version_test.cpp
Починил проблему из #1989. В [google style guide](https://google.github.io/styleguide/cppguide.html#auto) использовать auto рекомендуется только чтобы избежать длинных деклараций. Для uint и string это не замена.
=> [tests] Replace auto with exact types

tools/unix/generate_mwm.sh
Давно висела на мне эта задача, нашёл пять минут сделать. Generate_mwm.sh не поддерживал файлы с пробелами в названиях.
=> [generator] Support names with spaces in generate_mwm.sh

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, iphone/Maps/Classes/LocalNotificationManager.mm, map/framework.cpp, map/framework.hpp
Реализовал метод: Framework::ShowNode(), который позволяет показать произвольный (групповой или не групповой) узел дерева стран на карте.
Удалил методы: GetCountryBounds и ShowCountry и поправил, чтоб собиралось на iOS и на Android.
Проверил работоспособность метода Framework::ShowNode() на листовых нодах на iOS.
@trashkalmar @igrechuhin Саша, Илья, посмотрите п-та тикет и используйте метод, чтоб клик на п-те меню Show on map корректно отрабатывался.
https://jira.mail.ru/browse/MAPSME-178
=> [new downloader] Show on the map implementation.

map/framework.cpp, map/framework.hpp
Частично реализовать ф-цию, которая по countryid (групповому или нет), возвращает есть не сохраненные изменения или нет. В случае групповых mwm она должна проходить по всем листьям.
https://jira.mail.ru/browse/MAPSME-199
=> [new downloader, editor] Partly implementing a function for checking if some changed is made with a map(mwm).

geometry/mercator.hpp, search/search_quality_tests/search_quality_tests.cpp
Previous version was using lat-lons as mercator X and Y points.
=> [search] Fixed viewports in the quality tool.

android/src/com/mapswithme/maps/downloader/CountryItem.java, storage/storage.cpp, storage/storage.hpp, storage/storage_defines.cpp, storage/storage_defines.hpp
Реализация новой логики получения статусов для групповых mwm-ок.
Поведение должно быть такое:
Реализовать объединение статусов групповых элементов согласно следующему ТЗ:
Groups of mwms inherit their statuses according the following rules:
If an mwm in a group has Downloading status the group has Downloading status
If not and if an mwm in the group has InQueue status the group has InQueue status
If not and if an mwm in the group has Error status the group has Error status
If not and if an mwm in the group has OnDiskOutOfDate the group has OnDiskOutOfDate status
If not and if all the mwms in the group have OnDisk status the group has OnDisk status
If not and if all the mwms in the group have NotDownloaded status the group has NotDownloaded status
If not (that means a part of mwms in the …
=> [new downloader] Implementation new rules for calculating group mwm statuses.

indexer/displacement_manager.hpp
MAPSME-145 
После применения этого фикса и перегенерации данных, на обзорных зумах должно появиться больше иконок.
Вытеснение теперь считается через магические пиксели, вместо магического делителя тайла зума.
=> Styles displacement fix.

omim.pro
search quality tools depends on search_tests_support, so it must be declared first in SUBDIRS.
=> [search][build] Fixed build deps for search quality tools.

3party/jansson/jansson.pro, 3party/jansson/myjansson.cpp, 3party/jansson/myjansson.hpp, map/framework.cpp, search/search_quality/sample.cpp, storage/country.cpp, storage/country.hpp, storage/country_tree.hpp, storage/storage.cpp, storage/storage.hpp, storage/storage_tests/simple_tree_test.cpp, storage/storage_tests/storage_tests.cpp
1. Рефакториг класса CountryTree. Теперь корень дерева хранится так же, как и ноды (unique_ptr), что позволило удалить ряд "if-ов" при работе с деревом. (Витя и Юра, вы обращали внимание на эту особенность реализации в https://github.com/mapsme/omim/pull/2068 и других PR)
2. Я добавил обработку поля affiliations в countries.txt. Теперь при разборе countries.txt (новый вариант) заполнятся unordered_multimap<TCountryId, string>. Это происходит при инициализации приложения или в процессе миграции со старых mwm на новые. Во время работы программы по CountryId можно получить те строчки, что были записаны в поле affiliations в countries.txt. Предполагается вот такой формат countries.txt:
```
{
"id": "Countries",
"v": 160224,
"g": [
{
"id": "Abkhazia",
"s": 4651119,
"old": [
"Georgia"
], …
```
=> [new downloader] CountryTree refactoring. Processing affiliations field in countries.txt

map/framework.cpp, map/framework.hpp
Частично откатил изменения в https://github.com/mapsme/omim/pull/2101.
Теперь m_currentCountryChanged вызывается сразу, а не отложено.
@syershov @rokuz @trashkalmar @igrechuhin PTAL
=> [new downloader] Reverting deferred country update in auto map downloading.

search/v2/geocoder.cpp, search/v2/locality_scorer.cpp
It is enough that search model reports a feature to be a country
and there is no need for additional checks. Besides, the infoGetter
check looks broken: "Kingdom of Lesotho" does not have "Lesotho" as
a prefix.
This change cannot be applied to the current implementation of
states checker, however, so the prefix check is infoGetter is not
removed in this CL.
=> [search] Relax the condition of matching a locality to a country.

search/v2/features_layer_matcher.cpp, search/v2/features_layer_matcher.hpp, search/v2/mwm_context.cpp, search/v2/mwm_context.hpp
All features layer matchers are kept in Geocoder cache, and it's ok since we do not want to re-read street s or buildings vicinities, but it's wrong to keep m_houseToStreetTable in features layer matcher, because:
* HouseToStreetTable contains Reader, therefore, Geocoder actually had been kept Readers to all mwms, even when idle
* there is no reason to keep HouseToStreetTable between search sessions, because it's impossible to use FeaturesLayerMatcher without MwmHandle, and MwmHandle is impossible without MwmValue, and MwmValue contains a Reader.
* we already have a cache of MwmValues in MwmSet, so some kind of caching already exists
@mpimenov PTAL
=> [search] Removed wrong and faulty cache.

data/editor.config
Убрал создание `shop=doityourself`, потому что даже осмеры не знают, в чём отличие от `shop=hardware`. Заодно поубирал лишние поля, типа e-mail и address, с мелких POI, вроде остановок.
=> [editor] Remove extra fields for some types

storage/storage.cpp, storage/storage.hpp
Данный PR закрывает 2 тикета. Он
1. Восстанавливает работу Storage::CancelDownloadNode and Storage::RetryDownloadNode для листовых нод;
2. Делает корректную отмену при обновлении;
3. Предовращает перекачку карт, при вызове Storage::DownloadNode(), если карты на диске и up to date.
https://jira.mail.ru/browse/MAPSME-275
https://jira.mail.ru/browse/MAPSME-213
@syershov PTAL
=> [new downloader] Fixing Storage::CancelDownloadNode and Storage::RetryDownloadNode

storage/storage.cpp, storage/storage.hpp
Корректное заполнение прогресса при вызове GetNodeAttrs. Как следствие:
1. корректные данные отдаются для Андроид;
2. исправлена загрузка в qt приложении при загрузке крупных карт;
https://jira.mail.ru/browse/MAPSME-214
@ygorshenin PTAL
=> [new downloader] Bugfix. Correct filling m_downloadingProgress field in GetNodeAttrs for leaf node.

storage/storage.cpp, storage/storage.hpp, storage/storage_tests/storage_tests.cpp
Баг фиск. Падение при наличии пользовательской карты, имя которой совпадает в узловой нодой.
https://jira.mail.ru/browse/MAPSME-278
=> [new downloader] Implementation and using Storage::IsCoutryIdCountryTreeLeaf instead of IsCountryIdInCountryTree.

generator/borders_loader.cpp, generator/borders_loader.hpp, generator/generator_tool/generator_tool.cpp
Для проверки packed_polygons понадобилось как-то визуализировать границы. Я решил вернуть их в формат `*.poly` и загрузить в свой редактор границ. Получилось просто и быстро. Думаю, код распаковки стоит замёржить в основную ветку.
=> [generator] Unpack packed_polygons.bin

editor/server_api.cpp
Чтобы найти заметки, созданные из нашего приложения, и иметь по ним какую-то статистику.
=> [editor] Append #mapsme to notes created from withing the app

base/base_tests/string_utils_test.cpp, base/string_utils.hpp, search/intermediate_result.cpp, search/intermediate_result.hpp, search/search_query.cpp, search/search_query.hpp, search/v2/geocoder.cpp, search/v2/geocoder.hpp, search/v2/search_query_v2.cpp, std/random.hpp
Because of precision errors when pivot rectange is calculated from a position, a significant error was in computations of distance from search results to the pivot rectangle center. This PR resolves this issue, and, as a side effect, resolves a problem with buggy integral to string conversion.
@vng @mpimenov PTAL
=> [search] Fix flickering search results

generator/generator_tests/metadata_parser_test.cpp, generator/generator_tests/osm2meta_test.cpp, generator/osm2meta.cpp, platform/measurement_utils.cpp, platform/measurement_utils.hpp, platform/platform_tests/measurement_tests.cpp
Do not store insignificant zeroes after dot in metadata.
It also fixes https://trello.com/c/vZ1NxG4U/60-building-levels-1-1-0
=> Editor fixes, also reduced mwm size by ~0.5%.

storage/storage.cpp, storage/storage.hpp
При вызове Storage::CancelDownloadNode() для ноды у которой status == error статус будет сбрасываться.
https://jira.mail.ru/browse/MAPSME-397
@syershov @ygorshenin - посмотрите по возможности.
=> [new downloader] Cleaning status in case of canceling node with status error.

iphone/Maps/Classes/MWMPlacePageEntity.mm
Ассерт падал в дебаге на объектах со звездочками или горах. Например, отель adagio в Москве.
=> [ios] Fixed assert for unsupported cell types in Place Page.

data/editor.config, editor/editor_config.cpp
Добавление поля `atm` в банки и обмен валют сломало матчинг типов. Закомментировал поле и добавил TODO.
=> [editor] Remove atm fields

routing/routing_session.cpp
Не сбрасываем счётчик удаления от маршрута при приближении к нему. При "шумном" сигнале значительно ускоряет момент, когда дорога начинает перестраиваться. Других причин для MAPSME-182 и MAPSME-421 найти пока не получилось.
+ Вывод в лог переключения состояний Follow/NoFollow. Если мы что-то упустили.
=> Route no following in same cases fix.

drape_frontend/animation_utils.cpp, drape_frontend/animation_utils.hpp, drape_frontend/drape_frontend.pro, drape_frontend/my_position_controller.cpp, drape_frontend/user_event_stream.cpp
Настроено поведение анимации таким образом, чтобы на низких зумах не было мгновенных анимаций. Это решает проблему MAPSME-481.
=> Tuned instant animation

storage/storage.cpp, storage/storage.hpp, storage/storage_tests/storage_tests.cpp
В структуру NodeAttr добавил поля:
nodeAttrs.m_downloadingMwmCounter;
nodeAttrs.m_downloadingMwmSize;
В этих полях содержится информация о количестве и размере тех mwm которые:
- принадлежат поддереву с указаной в GetNodeAttrs вершиной;
- имеют любой статус отличный не загруженных (Т.е. находятся в секции downloaded);
При доработке UI по отображению кол-ва загруженных карт и их размеров необходимо использовать именно его.
Т.е. на пункте, соответствующем карте пишем:
Загружено карт: m_downloadingMwmCounter из m_mwmCounter
Размер того что загружено m_downloadingMwmSize из m_mwmSize
https://jira.mail.ru/browse/MAPSME-482
=> [new downloader] Adding downloading size and downloading counter.

tools/unix/generate_planet.sh
Приходилось руками строчку добавлять, вместо того, чтобы одну строчку в скрипт добавить.
Вместо #2352.
=> [generate] Copy coasts_obsolete for external_resources

editor/changeset_wrapper.cpp, editor/changeset_wrapper.hpp, editor/editor_tests/server_api_test.cpp, editor/server_api.cpp, editor/server_api.hpp
Fixes issues when newly created/edited features are incorrectly matched to existing nearby features in the OSM.
=> [editor] Reduced radius to match features for exactly 1 meter.

data/editor.config
Нам пишут:
>https://www.openstreetmap.org/changeset/38034497#map=19/55.76393/37.56298 
> Судя по всему, для "проездных билетов" и "Прессы" вместо соответствующих тегов ставится shop=kiosk, что очень прискорбно (по факту именно shop=kiosk, т.е. киосков в которых продают сразу все - и газеты, и лотерейные билеты, и напитки, и лицензии на рыбалку, в России крайне мало). Лучше сделать отдельные пресеты на билетный магазин/киоск, на магазин прессы.
> С уважением,
> literan
По-моему, нужно отключить тип киосков. Не так много стран, где этот тип имеет смысл.
=> [editor] Disable creation of kiosks

editor/changeset_wrapper.cpp
Правлю no matching function for call to 'min'. Работа с типами в шаблонных функциях, скажем так, хромает.
=> [editor] Fix std::min call

storage/storage.cpp, storage/storage.hpp, storage/storage_tests/storage_tests.cpp
Получение родителей первого уровня (детей корня) для узлов в country tree.
https://jira.mail.ru/browse/MAPSME-552
@syershov @ygorshenin @trashkalmar @igrechuhin по возможности посмотрите.
=> [new downloader] Getting topmost parent info for country tree nodes

storage/storage.cpp
Спорные территории учитывались дважды. Исправлено.
https://jira.mail.ru/browse/MAPSME-578
=> [new downloader] Bugfix. Double checking disputed territories.

editor/xml_feature.hpp, indexer/feature.cpp, indexer/feature.hpp, indexer/indexer_tests/feature_xml_test.cpp, indexer/osm_editor.cpp
https://trello.com/c/lQs9wLzq/130--
@Zverik нужно проверить этот код, попробовав отредактировать одну и ту же фичу в maps.me и в осме, и убедиться, что maps.me не перетирает тип.
=> [editor] Do not overwrite OSM type when feature is modified (not created by user).

editor/osm_auth.cpp
Правим тесты, дебажный сервер теперь доступен не по ip, а по нормальному адресу `test.osmz.ru`.
=> [editor] Update debug server link (release-60)

editor/osm_auth.cpp
Правим тесты, дебажный сервер теперь доступен не по ip, а по нормальному адресу `test.osmz.ru`.
=> [editor] Update debug server link (master)

storage/storage.hpp
https://jira.mail.ru/browse/MAPSME-592
@ygorshenin PTAL
=> [new downloader] In Storage::ForEachAncestorExceptForTheRoot checking visited nodes by pointer in tree but not by country id.

map/framework.cpp, routing/routing_session.cpp, routing/routing_session.hpp
Добавил детали маршрута, который мы закрываем в сообщение статистики. Чтобы потом мучительно долго не собирать информацию о том какой же маршрут это был.
=> More details to close routing statistics.

routing/cross_mwm_road_graph.cpp, routing/routing_integration_tests/osrm_route_test.cpp
MAPSME-604
Фикс случая, когда кратчайший маршрут пересекает последнюю карту несколько раз.
@bykoianko PTAL
=> Cross mwm routing fix. Final map twise case.

storage/storage.cpp
При раскатывании версии на 1% у 2 клиентов было падение программы при восстановлении сохраненной очереди. Данное падение, скорее всего не давало запустить программу. Согласно crashlytics у 2 пользователей не нашлось, country id, которой было сохранено в download queue в setting.ini. 
https://jira.mail.ru/browse/MAPSME-654
@syershov PTAL
Вот такие callstack-и были у пользователей:
libmapswithme.so  
logging.cpp line 49
jni::AndroidAssertMessage(my::SrcPoint const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
6
libmapswithme.so  
storage.cpp line 80
storage::Storage::CountryLeafByCountryId(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const
7
libmapswithme.so  
storage.cpp line 338 …
=> [new downloader] Checking availability of country id in country tree before adding it from the queue.

routing/osrm_router.cpp, routing/osrm_router.hpp, routing/road_graph_router.cpp, routing/route.cpp, routing/route.hpp, routing/routing_integration_tests/osrm_street_names_test.cpp, routing/routing_integration_tests/routing_integration_tests.pro, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/routing_test_tools.hpp, routing/routing_session.cpp, routing/routing_tests/route_tests.cpp
MAPSME-451
Храним названия улиц в отдельном хранилище внутри класса маршрута. Название улицы берётся из поля name.
Эти названия показываются в интерфейсе пользователя при ведении по маршруту. 
Интеграционный тест прилагается.
=> Street names

platform/http_request.cpp
Добавлена диагностическая информация, чтоб понять, почему возникают ошибки при вызов rename.
=> Adding diagnostic info in case of my::RenameFileX error.

data/countries.txt, data/hierarchy.txt
По ходу, не все согласны, что Фолкленды должны быть в UK.
=> [countries] Move Falkland Island to the top level (release)

iphone/Maps/Classes/CustomAlert/DownloadTransitMapsAlert/MWMDownloadTransitMapAlert.mm, iphone/Maps/Classes/MapDownloader/MWMBaseMapDownloaderViewController.mm, iphone/Maps/Classes/Storage/MWMStorage.mm, map/framework.cpp, platform/local_country_file.cpp, platform/local_country_file.hpp, qt/draw_widget.cpp, storage/country.cpp, storage/country.hpp, storage/storage.cpp, storage/storage.hpp, storage/storage_defines.hpp, storage/storage_integration_tests/storage_group_download_tests.cpp, storage/storage_tests/storage_tests.cpp
1. Замена типа с size_t на uint64_t для размера стран в байтах. size_t переполнялось для США на 32 битных девайсах;
2. Поменял порядок в списке инициализации Framework, чтоб не было warning;
https://jira.mail.ru/browse/MAPSME-140
@syershov, @igrechuhin, @rokuz PTAL
=> Exchanging size_t to uint64_t for mwm and group mwm size in bytes.

routing/cross_mwm_road_graph.cpp, routing/routing_integration_tests/osrm_route_test.cpp
MAPSME-707
Иногда при упрощении точки пересечения границы попадают в соседние квадраты. Это надо учитывать при их сравнении.
=> Routing crosses finding fix.

generator/tag_admixer.hpp
Неделю назад в TagReplacer проникла ошибочка, из-за которой сборка планеты вылетает на шаге 4. Кто-то забыл, что первая пара ключ-значение уходит в индекс мэпки.
=> [generator] Fix a nasty bug in tag replacer

iphone/Maps/Classes/MapDownloader/MWMBaseMapDownloaderViewController.mm
MWM<Base>MapDownloaderViewController retains its dataSources.
However its tableView does not retain its dataSource.
During switch of active dataSource, tableView was loosing its dataSource.
Table reload during dataSource switch led to crashes.
=> [ios] Fixed crash.

data/replaced_tags.txt, defines.hpp, generator/osm_source.cpp, indexer/feature_data.cpp
Фоллоу-ап к #2698: поправил опечатку и добавил определение тегов для скамейки и крыши (полезно для остановок транспорта).
=> [generator] Add bench and shelter to replaced tags

generator/feature_builder.cpp, map/framework.cpp, qt/search_panel.cpp, routing/bicycle_model.cpp, routing/bicycle_model.hpp, routing/pedestrian_model.cpp, routing/pedestrian_model.hpp, routing/road_graph_router.cpp, routing/road_graph_router.hpp, routing/router.cpp, routing/router.hpp, routing/routing.pro, routing/routing_settings.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Сделан и задействован новый profile для прокладки вело маршрута двусторонним A* (Так же как, сейчас прокладывается пешеходный). Чтоб его активировать нужно в qt приложении ввести ?bicycle.
Строчек много, но суть очень проста.
1. Добавлен routing/bicycle_model.hpp/cpp, в котором для разных стран задан вело профайл (BicycleModel/BicycleModelFactory) на основании: http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions;
2. Вело профайл учтен в генераторе;
3. Сделано, чтоб при вводе в qt приложении ?bicycle прокладка маршрута осуществлялась по вело профайлу.
Тесты я планирую добавить позже.
@gardster обязательно посмотри.
@mpimenov @ygorshenin @syershov посмотрите по возможности.
https://jira.mail.ru/browse/MAPSME-797
=> Bicycle routing profile.

routing/osrm_router.cpp, routing/osrm_router.hpp, routing/turns_generator.cpp, routing/turns_generator.hpp
MAPSME-799
Рефакторинг участка генерации поворотов.
Вводит интерфейс "результат роутера". Который распаковывает данные и предоставляет информацию по которой функции аннотации маршрута смогут описать повороты.
Пока реализация предоставлена только для OSRM графа. В остальном перемещение кода из osrm_routed файлов в turns_generator.
@bykoianko PTAL
=> Turn generation massive refactoring.

routing/routing_integration_tests/osrm_route_test.cpp, routing/routing_integration_tests/osrm_turn_test.cpp
пара фиксов, чтобы интеграционные тесты не фейлили. Оба случая посмотрел глазами. В африке запретили поворот (мост вместо плоского перекрёстка) и маршрут стал длиннее. На планетной поравили геометрию. Хватило 2х метров чтобы обрушить тест.
=> Integration tests constant fixes.

routing/loaded_path_segment.cpp, routing/loaded_path_segment.hpp, routing/osrm_router.cpp, routing/routing.pro, routing/routing_result_graph.hpp, routing/turn_candidate.hpp, routing/turns.hpp, routing/turns_generator.cpp, routing/turns_generator.hpp
Главная цели этого PR - перенос ряда структур (IRoutingResultGraph, TurnCandidate, LoadedPathSegment) из модуля turn_generator в отдельные файлы. Это необходимо, чтоб потом их можно было использовать для велороутинга. За одно фалы turn_generator стали поменьше.
Кроме того, структура LoadedPathSegment в будущем будет заполняться не только при помощи osrm роутинга, но и при помощи вело роутинга (AStar). Чтоб это было удобнее добавлены типы: TUniversalNodeId и TUniversalEdgeWeight.
@gardster PTAL
=> [bicycle routing] Moving some data stuctures from turn_generator unit to separate files.

3party/osrm/osrm-backend/plugins/MapsMePlugin.hpp
После 34791b0168be4da436517deeae385c2928d954fb перестал собираться osrm.
=> [osrm] Fix osrm maps.me plugin build after renaming country.name

iphone/Maps/Classes/MapsAppDelegate.mm
Take a copy of pasteboard string since it can accidentally become nil while we still use it.
=> [ios] Crash fix.

base/string_utils.cpp, base/string_utils.hpp, generator/search_index_builder.cpp, indexer/search_string_utils.cpp, indexer/search_string_utils.hpp, search/feature_offset_match.hpp, search/retrieval.cpp, search/retrieval.hpp, search/search.pro, search/search_integration_tests/helpers.cpp, search/search_integration_tests/helpers.hpp, search/search_integration_tests/search_query_v2_test.cpp, search/search_query.cpp, search/search_tests/postcodes_matcher_tests.cpp, search/search_tests/ranking_tests.cpp, search/search_tests/search_tests.pro, search/search_tests_support/test_feature.hpp, search/search_trie.hpp, search/v2/geocoder.cpp, search/v2/locality_scorer.cpp, search/v2/postcodes_matcher.cpp, search/v2/postcodes_matcher.hpp, search/v2/ranking_utils.hpp, search/v2/token_slice.cpp, search/v2/token_slice.hpp, search/v2/tokens_slice.cpp, search/v2/tokens_slice.hpp
@vng @mpimenov PTAL
Note that postcodes are added to the search index in the categories branch, but not used right now. I'm going to add support to geocoder later (today or on weekends). This CL has a lot of cosmetic changes, but please, review carefully how postcodes are added to the search index and how postcodes matcher is implemented. My plan is to use postcodes matcher during Geocoder::LimitedSearch, extract postcodes and then use them to filter or add results (depends on the context).
=> [search] Postcodes are added to the search index.

routing/pedestrian_model.cpp
Я изучил ситуацию с профайлом для пешеходного роутинга для разных стран. По крупному, он ошибочно использовал только в США дефолтный профайл. Данный PR исправляет ошибку.
Но это быстрый фикс. Правильный фиск - это использовать для получения countryId страны Storage. (Для этого надо прокинуть колбек в routing.) Ввиду не хватки времени, я откладываю данное дело. В коде есть TODO на эту тему.
https://jira.mail.ru/browse/MAPSME-849
@gardster PTAL
=> Using special profile for pedestrian routing in the USA.

data/categories.txt, indexer/categories_holder.cpp, indexer/indexer_tests/categories_test.cpp
Мне надоело вводить переводы для слова «магазин» в сто разных категорий, поэтому я сделал группы: если в заголовок категории добавить `@shop`, к ней добавляются все переводы для магазинов. Ну и так далее, вытащил переводы из `strings.txt`.
Также добавил категории для новый типов.
=> [categories] New category translations and category groups support

tools/python/road_runner.py, tools/unix/generate_planet.sh, tools/unix/generate_planet_routing.sh
Скрипт подготовки данных и запуска локального OSRM сервера для рассчёта дорог на обзорных масштабах. Если скрипту generate_planet.sh не предоставить URL работающего OSRM'a он создаст свой. Данные будут собраны из текущей планеты, что гарантирует их свежесть.
@Zverik PTAL
=> Osrm rebuilding

indexer/edits_migration.cpp, map/framework.cpp, map/framework.hpp
Сохранение геометрии в редакторе происходит с потерей информации:
* сохраняются не треугольники, а набор точек без дубликатов;
* координаты записываются с точностью до 7го знака.
Для восстановления правки на карте нужно выполнить поиск по одной из ее точек.
Из-за потери точности при сохранении некоторые "внутрении" для фичи точки перестают 
таковыми восприниматься функциями расчета расстояния до фичи и приверки принадлежности точки лимит ректу фичи.
=> [editor] Fix xml feature loading var2

tools/integration_tests_runner.py
Now we can skip copying the mwm files to the omim/data folder, which saves a lot of space an time.
=> Added the --user_resource_path to the script.

indexer/search_delimiters.cpp, indexer/search_delimiters.hpp, search/search_integration_tests/search_query_v2_test.cpp, search/search_query.cpp, search/v2/geocoder.cpp
Added possibility to add hashtags before categorial tokens. In this case, these tokens will be used only as categorial filters, not as parts of name. This is an internal feature and should be used internally, mostly for debugging.
=> [search] Added hashtags.

editor/changeset_wrapper.cpp
Теперь если связь оборвалась, комментарий всё равно будет непустой, хотя и не особо осмысленный.
Также добавил пару тегов для создания комментария: даже если главный тег не будет найден, воспользуемся названием.
=> [editor] Avoid empty changeset comments on partial upload

indexer/classificator_loader.cpp
Чуть больше месяца назад Витя [сломал]https://github.com/mapsme/omim/commit/9d52efd6538cc3be684329888a9490c3428f653e#diff-e53ab62079f4a6c127313cb75e92c806[ кэширование стилей и классификаторов, оставив загрузку только стиля по умолчанию. Через неделю он [вернул](https://github.com/mapsme/omim/pull/2854/files#diff-e53ab62079f4a6c127313cb75e92c806) старый код, но при этом забыл про две фичи: 
* восстановление стиля перед запуском функции (вероятно, у нас сейчас сломано сохранение последнего стиля в приложении);
* обработку смёрженного стиля для генератора (поэтому по факту мы использовали стиль clear для последних данных).
Этот пул-реквест восстанавливает файл, как он был до витиного вмешательства.
=> [classificator] Restore old classificator loading algorythm

indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/directions_engine.cpp, routing/directions_engine.hpp, routing/loaded_path_segment.hpp, routing/osrm_router.cpp, routing/pedestrian_directions.cpp, routing/pedestrian_directions.hpp, routing/road_graph_router.cpp, routing/route.cpp, routing/route.hpp, routing/routing.pro, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/routing_integration_tests.pro, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/routing_test_tools.hpp, routing/routing_result_graph.hpp, routing/turn_candidate.hpp, routing/turns.cpp, routing/turns.hpp, routing/turns_generator.cpp, routing/turns_generator.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Генерация тернов для велороутинга. 
PR реализует простую идею: использовать генератор тернов от car-routing-га для вело-роутинга. 
+ написана тестовая инфраструктура для тестов вело маршрутов и написано пару routing_integration_test: на прокладку вело маршрута и на маневры в вело маршруте. Их кол-во будет увеличиваться.
@ygorshenin @mpimenov  по возможности посмотрите.
=> Bicycle turn generation.

routing/bicycle_model.cpp
Более внимательное изучение 
http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions#Russia
показало, что для России допустимо прокладывать велосипедные маршруты по дороге с highway=footway.
https://jira.mail.ru/browse/MAPSME-1311
@Zverik @yunikkk PTAL
=> [bicycle routing] Using highway=footway for bicycle routing in Russia.

data/countries.txt, data/external_resources.txt
Планета вам в пачку.
Починили мёрж стилей, поэтому суммарный размер вырос на гигабайт (2,7%). В основном из-за `railway-disused` и `power-line`. Можно по логу сборки посмотреть, что пришёл на dev@ вчера в 18:30.
=> [planet] Planet data from 24.05.2016

search/v2/geocoder.cpp
WithPostcodes must clean m_postcodes field after search, even in case of exceptions.
https://jira.mail.ru/browse/MAPSME-1334
=> [search] Fixed crash in postcodes search.

base/base_tests/stl_helpers_test.cpp, base/stl_helpers.hpp, map/framework.cpp, pedestrian_routing_tests/pedestrian_routing_tests.cpp, routing/bicycle_model.hpp, routing/features_road_graph.cpp, routing/features_road_graph.hpp, routing/road_graph.cpp, routing/road_graph.hpp, routing/road_graph_router.cpp, routing/road_graph_router.hpp, routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_tests/road_graph_builder.cpp, routing/routing_tests/road_graph_builder.hpp, routing/vehicle_model.hpp
Учет односторонних дорог, как односторонних, для всех типов (highway=cycleway, highway=primary и т.д.) при велороутинге.
https://jira.mail.ru/browse/MAPSME-1274
@ygorshenin @mpimenov @Zverik PTAL
=> [bicycle routing] "oneway" tag is taken into account while bicycle routing.

routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/bicycle_turn_test.cpp
Починка интеграционных тестов на велосипедную навигацию после ряда изменений:
- запрет для движения против хода на велосипеде для oneway дорог;
- разрешение ездить по пешеходным дорогам велосипедистам;
- выключение коррекции угла по исходящим дорогам для велосипедных маршрутов.
https://jira.mail.ru/browse/MAPSME-1376
=> Fixing bicycle integration test after allowing bicycle routing on highway=footway in Russia.

base/string_utils.cpp
Поправил тесты и, вероятно, какие-то случаи в приложении. С недавних пор мы проверяем `errno` в `to_int`, не обнуляя его перед преобразованием типа. Поскольку в случае успеха библиотечные функции этот код не обнуляют, иногда случается неуспех. Как мы и увидели в тестах.
=> [utils] Fix error checking in to_int

routing/bicycle_model.cpp, routing/routing_integration_tests/bicycle_route_test.cpp
Данный PR разрешает движение велосипедистов по лестницам в России и Украине (в остальных странах и было разрешено), но делает лестницам большой вес. Т.е. мы стараемся не вести вело маршрут через лестницы. Ведем, только если объезд очень далек.
Пояснение. Согласно правилам России и Украины велосипедист может стать пешеходам (спешившись) и идти по лестницам. 
Выдержки из ПДД, указывающие на допустимость движения пешехода с велосипедом в руках по пешеходной лестнице.
Россия:
1.2. В Правилах используются следующие основные понятия и термины:
...
"Пешеход" - лицо, находящееся вне транспортного средства на дороге либо на пешеходной или велопешеходной дорожке и не производящее на них работу. К пешеходам приравниваются лица, передвигающиеся в инвалидных колясках без двигателя, ведущие велосипед, …
=> Bicycle routing by stairs in Russian and Ukraine.

omim.pro
У нас генераторный тул не собирается, потому что тесты зависят от генератора, но собираются раньше его.
=> [tests] Fix tests dependencies in omim.pro

base/base_tests/string_utils_test.cpp, base/string_utils.cpp
Интересно, работали ли когда-нибудь проверки на пустые строки в `to_int` и им подобных? Поправил здесь.
=> [tests] Correctly process empty strings in to_whatever

editor/editor_tests/user_stats_test.cpp, indexer/editable_map_object.cpp, indexer/indexer_tests/editable_map_object_test.cpp
Заодно запретил вводить «0» в высоту здания. Ибо нефиг.
=> [tests] Fix user stats and building level validation tests

generator/booking_dataset.cpp, tools/python/booking_hotels.py
Забыли записывать в файл tsv тип гостиницы, и забыли добавлять тип `sponsored-booking` для импортированных гостиниц. Поправил тут.
Также убрал непонятный `namedtuple` из питоновского скрипта: цель его осталась невыясненной, т.к. названия полей нигде не использовались.
=> [booking] Fix for hotel types

search/engine.cpp, search/geocoder.cpp, search/geocoder.hpp, search/processor.cpp, search/processor.hpp
The problem is that SetViewport calls Reset(), which, in turn, resets the state of the cancellable. Therefore, all cancel signals that come after Processor::Init() but before Processor::SetViewport() are lost.
=> [search] Fixed cancellation of outdated queries.

indexer/osm_editor.cpp
Поправил предупреждение о неиспользуемой переменной при сборке. Теперь проверка на тип фичи будет и в релизной версии. В случае `FeatureStatus::Created`, например, код дальше вылетал из-за разыменования `nullptr`, теперь будем делать вид, что всё хорошо.
=> [editor] Fix warning

tools/integration_tests_runner.py, tools/run_desktop_tests.py
* Added storage integration tests to those that require temporary forlders for running normally;
* Added logging the process id for the shells running our tests (needed when a test hangs);
=> Fix for some integration tests:

search/features_layer_matcher.hpp, search/geocoder.cpp, search/search_integration_tests/processor_test.cpp, search/search_tests/house_numbers_matcher_test.cpp
https://jira.mail.ru/browse/MAPSME-1471
This CL slows down the worst case searches.
Below are the results of several runs on queries.txt.
Before:
Maximum response time: 6.546s
Average response time: 0.493s (std. dev. 1.035s)
Maximum response time: 6.713s
Average response time: 0.506s (std. dev. 1.061s)
Maximum response time: 6.548s
Average response time: 0.494s (std. dev. 1.034s)
After:
Maximum response time: 7.735s
Average response time: 0.573s (std. dev. 1.222s)
Maximum response time: 6.528s
Average response time: 0.497s (std. dev. 1.032s)
Maximum response time: 6.877s
Average response time: 0.514s (std. dev. 1.084s)
=> [search] Removed one aggressive house number check and replaced another.

indexer/feature_data.cpp
https://jira.mail.ru/browse/MAPSME-1247
Если сначала приходит `housename=улица с 41слом`, то она забивает номер дома. Теперь смотрим, если настоящий номер дома пришёл вторым, меняем их местами. Проверка очень простая, но и название улицы с числом пихают в `addr:housename` нечасто.
=> [generator] Switch housename and housenumber if needed

iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-1607
Restore location manager subscription on enter foreground.
Skip first session since we must ask user for permission on first launch.
=> [ios] Fixed location manager subscription restore.

indexer/search_string_utils.cpp
https://jira.mail.ru/browse/MAPSME-1580
Оказалось, мы ищем улицу для дома по нечёткому сравнению названий. То есть, «улица Челюскинцев» и «переулок Челюскинцев» — одно и то же для алгоритма сравнения, т.к. префиксы отбрасываем. Это неправильно, т.к. значение `addr:street` дома должно с точностью до буквы повторять значение `name` улицы.
<s>Этот пул-реквест заменяет нечёткое сравнение точным, удаляя последнее использование `search::GetStreetNameAsKey` и ` search::ReverseGeocoder::GetMatchedStreetIndex`. Другое осталось в `search/house_detector.hpp`, но им никто не пользуется.</s>
Просто убрал выкидывание статусных частей.
=> [generator] addr:street should be exactly equal to street name

routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_integration_tests/osrm_route_test.cpp, routing/routing_integration_tests/osrm_turn_test.cpp
Поправил 4 routing_integation_tests из 5-ти. Один оставил как есть: CheckOsrmToFeatureMapping. С ним нужно будет отдельно разбираться.
@therearesomewhocallmetim Запусти п-та этот PR на routing_integration_tests тесты. Ожидаемый релзультат - не пройдет один тест: CheckOsrmToFeatureMapping
=> [routing] Fixing routing integration tests.

editor/user_stats.cpp
По ходу, у нас не работает редирект. Впрочем, здесь не важно.
=> [editor] Https for user rank call

generator/feature_builder.cpp, indexer/feature.cpp, indexer/feature.hpp
Корректная инициализация полей класса FeatureType, которые раньше были не инициализированы.
+  mutable bool m_header2Parsed;
+  mutable bool m_pointsParsed;
+  mutable bool m_trianglesParsed;
+  mutable bool m_metadataParsed;
@mpimenov @ygorshenin и все кому интересно PTAL
=> FeatureType bugfix. Initialization of bool fiels of FeatureType class which was uninitialized before.

editor/xml_feature.cpp, editor/xml_feature.hpp, indexer/editable_map_object.cpp, indexer/editable_map_object.hpp
Фиксим #2902, навеяло [этой жалобой](https://lists.openstreetmap.org/pipermail/talk/2016-June/076231.html). Пользователи жалуются, что люди случайно пробелы в название вводят.
В этом PR не только обрезаются пробелы у значений тегов, но и у названия прямо после ввода его в редакторе. Это наглядно, и у пользователя не висит некрасивость до следующего обновления.
Протестировал на android.
=> [editor] Trim name

editor/user_stats.cpp
Посмотрел логи — а они полны `"GET /user?format=xml&name= HTTP/1.0" 404`. Давайте не будем слать бесполезные запросы на сервер. Лучше бы, конечно, вообще не вызывать статистику для пустого профиля, но для начала поставим защиту на самом низком уровне.
=> [editor] Do not send empty stats requests

editor/changeset_wrapper.cpp
https://jira.mail.ru/browse/MAPSME-1755
Убираю лишнюю `s` на конце для множественного числа, и пишу `an`, когда название типа начинается с гласной.
=> [editor] Fix English grammar in changeset comments

generator/osm2type.cpp
* `public_transport=platform` + `bus=yes` превращаем в `highway=bus_stop`
* то же не на точке, а на линиях-отношениях превращаем в `highway=platform`
* `public_transport=stop_position` + `tram=yes` превращаем в `railway=tram_stop`.
Думал сделать то же для железнодорожных остановок, но посмотрел по taginfo — там всё задублировано старым тегом `railway=station`.
=> [generator] Process public_transport tags

data/categories.txt
Danish translation of amenity=shelter was misleading. It was translated to "home" which lead to quite a few amenity=shelter's spuriously located on top of houses and other weird places. This has puzzled me for quite some time now...
=> Correct danish for amenity=shelter

generator/intermediate_data.hpp
У нас сломалась сборка планеты, потому что идентификаторы точек вылезли за 2³². Правлю в этом PR: увеличиваю лимит в два раза. Этого хватит года на четыре. Также добавляю проверку, чтобы в следующий раз не ломать голову.
=> [generator] Fix big node ids issue (→release 62x)

editor/changeset_wrapper.cpp, editor/editor_tests/xml_feature_test.cpp, editor/xml_feature.cpp
С помощью Сергея разобрался, почему проверка `.HasAnyTags()` не работала. Написал тесты соответствующих методов и попутно добавил пару тегов в проверку к комментариям ченджсетов.
=> [editor] Fix xml tag test

search/intermediate_result.cpp, search/locality_finder.cpp, search/locality_finder.hpp, search/mwm_context.hpp, search/processor.cpp, search/ranker.cpp, search/ranker.hpp, search/search_tests/locality_finder_test.cpp, std/algorithm.hpp
Locality matching code haven't supported a lot of mwms, and iterated
over the whole mwms set on each search result (sic!).  Moreover, for
locality selection it directly read all features in the rect instead of
RankTable usage.
This CL significantly speeds up search results generation stage, when
there're a lot of maps and a lot of search results.
=> [search] Fixed slooow locality matching.

3party/jansson/myjansson.cpp, 3party/jansson/myjansson.hpp, data/countries_meta.txt, defines.hpp, generator/feature_sorter.cpp, generator/generator.pro, generator/region_meta.cpp, generator/region_meta.hpp, generator/search_index_builder.cpp, indexer/data_factory.cpp, indexer/data_factory.hpp, indexer/feature_meta.cpp, indexer/feature_meta.hpp, indexer/index.cpp, indexer/index.hpp, indexer/indexer_tests/feature_metadata_test.cpp, indexer/mwm_set.hpp, tools/python/mwm/dump_mwm.py, tools/python/mwm/mwm.py
Ура, добавляем новую секцию в mwm! Это информация по региону, как когда-то обсуждали. Там хранятся языки региона, сторона движения, часовой пояс, формат адреса и т.п. Данные берутся из `omim/data/countries_meta.txt`, который в формате json, как и `countries.txt`. Его я сгенерю чуть позже.
Для получения объекта `RegionData` (который наследован от `MetadataBase` со всеми вытекающими) есть два способа, в зависимости от того, что у вас есть:
feature.GetID().m_mwmId.GetInfo().GetRegionData()
mwmHandle.GetValue<MwmValue>()->GetInfo().GetRegionData()
Ну и дальше там есть `GetLanguages()` и т.п.
=> [generator] Add region info section to mwms

data/countries_meta.txt
Поспешил — generator tool насмешил.
Забыл проверить `countries_meta.txt` на валидность, пропустил запятую.
=> [generator] Fix typo in countries_meta.txt

android/build.gradle, android/gradle.properties
У нас в сегодняшнем Andorid релизе появился запрос не нужного пермишен: READ_PHONE_STATE
Обновил pushwoosh, чтоб это вылечить. И поднял propVersionCode.
@yunikkk @trashkalmar PTAL
=> [FOR RELEASE] pushwoosh update to version 4.6.1. It'll remove unnecessary READ_PHONE_STATE permission.

android/build.gradle, android/gradle.properties
cherry-pick https://github.com/mapsme/omim/pull/3869 to master.
У нас в сегодняшнем Andorid релизе появился запрос не нужного пермишен: READ_PHONE_STATE
Обновил pushwoosh, чтоб это вылечить. И поднял propVersionCode.
@yunikkk @trashkalmar PTAL
=> [MASTER] pushwoosh update to version 4.6.1. It'll remove unnecessary READ_PHONE_STATE permission.

data/categories.txt
In spanish the most common way to say ATM is "Cajero automático"
=> Update spanish translation of ATM

generator/generator_tool/generator_tool.cpp
Он необходим, поскольку во время генерации секции с рельефом мы вызываем метод routing::IsRoad(feature::TypesHolder(f).
@ygorshenin or @mpimenov PTAL
=> [generator]Loading classificator before altitude generation.

android/build.gradle
Обновил pushwoosh. Это должно решить самый популярный креш релиза 6.2.5
@rokuz @yunikkk PTAL
https://jira.mail.ru/browse/MAPSME-2053
=> Pushwoosh update to version 4.6.3.

generator/srtm_parser.cpp
Выше 60-й параллели нет данных srtm. Это ожидаемо. Чтоб не загрязнять результирующий лог приоритет сообщения о том, что srtm tile не найден понижен с LWARNING до LINFO.
=> Reducing message priority if a tile of srtm is not found.

routing/bicycle_model.cpp, routing/car_model.cpp, routing/pedestrian_model.cpp, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_tests/vehicle_model_test.cpp, routing/vehicle_model.cpp, routing/vehicle_model.hpp
Bugfix. Возвращаем не нулевую скорость для валидных дорог для пешеходного и вело роутинга. 
Данный PR закрывает следующие тикеты:
https://jira.mail.ru/browse/MAPSME-1829
https://jira.mail.ru/browse/MAPSME-1506
https://jira.mail.ru/browse/MAPSME-1620
@ygorshenin @mpimenov @Zverik PTAL
=> [Release-63] Getting rid of returning zero speed while pedestrian and bicycle routing. Fixing routing along ferry.

indexer/editable_map_object.cpp, indexer/feature.cpp, indexer/feature_utils.cpp, indexer/feature_utils.hpp, map/place_page_info.cpp
Новый приоритет выбора названий объектов
// Names using priority:
+  // - device language name;
+  // - international name;
+  // - english name;
+  // - default name;
+  // - country language name.
Слегка подправлен приоритет выбора имен для важных объектов
+  // Primary name using priority:
+  // - default name;
+  // - country language name.
+  // Secondary name using priority:
+  // - device language name;
+  // - international name;
+  // - english name.
@mpimenov 
@mgsergio 
@Zverik
=> New naming rules for map objects

android/src/com/mapswithme/maps/location/BaseLocationProvider.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/location/TrackRecorder.java
Fix креша:
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/57a214e3ffcdc04250009918/sessions/57ae512e03cd00011197516153fe0d22
Вот кол стек. Проблемы была в циклическом вызове LocationHelper.notifyLocationUpdated 
com.mapswithme.util.Listeners.iterator (Listeners.java:26)
com.mapswithme.maps.location.LocationHelper.notifyLocationUpdated (LocationHelper.java:296)
com.mapswithme.maps.location.LocationHelper.onLocationUpdated (LocationHelper.java:245)
com.mapswithme.maps.location.TrackRecorder$2.onLocationUpdated (TrackRecorder.java:48)
com.mapswithme.maps.location.LocationHelper.notifyLocationUpdated (LocationHelper.java:297)
com.mapswithme.maps.location.LocationHelper.onLocationUpdated (LocationHelper.java:245) …
=> Crashfix. Recursive call of LocationHelper.notifyLocationUpdated().

android/AndroidManifest.xml, android/src/com/mapswithme/maps/location/GPSCheck.java, android/src/com/mapswithme/maps/location/LocationHelper.java
Если gps выключен и включается во время работы maps.me, то maps.me его сразу не подхватит, сколько не жди. Надо уводить приложение в backgroud и возвращать в foregroud, чтоб подхватило. 
Данный PR решает эту проблему. Идея проста: добавляем ресивер на включение GPS и если он включается переинициализируем систему.
Данный PR решает проблему, но что в текущей реализации мне не нравится:
- при включении GPS мы добавляем только native gps listener. Просто переиницилизировать (restart) не получается, поскольку ни один listener не добавлен в mListeners на момент вызова onReceive;
- у меня был native crash в Java_com_mapswithme_maps_LocationState_nativeSetListener+68, в момент еще одного вызова addListener(mLocationListener, true); Правдо, я не уверен, что он воспроизводится;
@trashkalmar …
=> Recovering location usage on GPS switch on.

platform/measurement_utils.cpp
The unit numbers is moving too fast between 100 and 1000.
It was useless information, this commit rounded to nearest ten between 100 and 1000 and the units numbers are only display under 100.
=> Display unit number only if <= 100 in the navigation maneuver panel.

android/res/values-ja/strings.xml, android/res/values-zh-rTW/strings.xml, android/res/values-zh/strings.xml, iphone/Maps/ja.lproj/Localizable.strings, iphone/Maps/zh-Hans.lproj/Localizable.strings, iphone/Maps/zh-Hant.lproj/Localizable.strings, strings.txt
Hi,
The Japanese and Chinese translations of the "book" button for booking.com are incorrect.
The original translations are nouns (📕) , not verbs.
I have fixed them in this pull request.
Please take a look. Thanks! 😄 
p.s. I have already signed the CLA.
=> Fix Japanese and Chinese translations of book button

indexer/feature_data.cpp
У нас сейчас на половине заведений в Европе выводится тип `wheelchair-no` или `-yes`. Мой косяк, забыл про список неважных типов. Здесь это правлю.
=> [types] Do not display wheelchair types in the PP

android/res/layout/item_localized_name.xml
При создании нового объекта заставляем вводить его название с заглавной буквы, а не со строчной. В iOS умолчание уже такое, а вот в андроиде было со строчной, приходилось каждый раз шифт нажимать.
Проверил на устройстве.
=> [editor] Capitalize names

android/res/layout/edit_bookmark_common.xml, iphone/Maps/Bookmarks/BookmarksRootVC.mm
В рамках федеральной программы «Хватит это терпеть!» заменил пословную капитализацию закладок на попредложенческую. То есть, с заглавной буквы теперь будет только Первое слово в названии, а не Все Слова В Закладке Блин.
(Протестировал на андроиде, айфона нет)
=> [bookmarks] Words → Sentences capitalization

map/framework.cpp, routing/routing_session.cpp, routing/routing_session.hpp
1. Обернул в shared_ptr текущий маршрута RoutingSession::m_route (Сейчас это используется только в InsertRoute(*m_routingSession.GetRoute());)
2. Поправил ряд ошибок с синхронизацией;
3. Использовать, то что RoutingSeccion::m_route не потребовалось. См. Framework::GenerateRouteAltitudeChart
https://jira.mail.ru/browse/MAPSME-2417
@ygorshenin PTAL
=> [routing] Wrapping RoutingSesson::m_route into shared_prt and some fixes some multithreading issues.

routing/routing_integration_tests/osrm_route_test.cpp, routing/routing_tests/turns_generator_test.cpp, routing/turns_generator.cpp, routing/turns_generator.hpp
Крешфис при построении маршрута на карте Санкт-Петербурга. (В CheckUTurnOnRoute)
https://jira.mail.ru/browse/MAPSME-1716
@ygorshenin @mpimenov PTAL
=> Crash fix in CheckUTurnOnRoute

android/src/com/mapswithme/maps/routing/RoutingController.java
Исправил.
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/57e3270f0aeb16625b938043
Мы падали, если приходил какой-нибудь Routing Event когда приложение находилось в background.
@alexzatsepin  @trashkalmar @yunikkk PTAL
=> Android. RoutingController crash fix.

map/framework.cpp
Add padding on the bounding box generated when "ShowTrack" framework function is called.
=> Add padding on the bounding box when focus on a track.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/routing/NavigationController.java
When i change the EAT information to display the arrival hour and i switch the ui into landscape/portait mode, the EAT information go back to display the remaining time.
Example : 
[Only under Android]
=> [Android] EAT display in navigation mode change when switching between landscape/portrait.

feature_list/feature_list.cpp, feature_list/feature_list.pro, omim.pro, platform/preferred_languages.cpp, search/reverse_geocoder.cpp, search/reverse_geocoder.hpp
Берёт каталог с mwm, из каждой берёт все фичи и последовательно для каждой, отвечающей критериям «есть имя» + «POI» + «не линия» выводит в псевдо-csv набор атрибутов. Из него потом с помощью разных скриптов получаются фиды для SEO.
Кроме того, этот PR позволяет переопределить язык системы из командной строки в macOS, объединяя обработку переменных окружения с linux.
=> Feature list tool

map/framework.cpp
В андройде не отключался продвинутый режим редактирования имен, т.к. в ядре не очищался EditableMapObject перед редактированием, а в андройде используется один глобальный EditableMapObject, который, как оказалось, тоже не очищается.
https://jira.mail.ru/browse/MAPSME-2506
https://jira.mail.ru/browse/MAPSME-2507
=> Clear editable map object before editing

drape_frontend/text_layout.cpp
This closes #3807 issue. Because of clang/libcxx 3.8 have overload of
`floor` function in math.h for `float` and `double` we got compilation
error, but obvious fix:
1.0 -> 1.0f
not works, because of at least on Android we have no `floor(float)`
overload. So to fix build force usage of floor(double) which exists on every platform.
=> fix build with clang/libcxx on linux

data/countries_meta.txt
Languages for Luxembourg, as requested in https://www.openstreetmap.org/user/Zverik/diary/39637
French, Luxembourgish and German are the country's official languages, ordered by frequency of usage in place names. Luxembourg is a pretty international place, and some places have English names, e.g. the European Court of Justice.
=> Luxembourg languages

common.pri, tracking/tracking_tests/tracking_tests.pro
Теперь у нас сокеты в платформе, что потребовало подключить библиотеку `CFNetwork`. Ну и забыли одну зависимость в tracking.
=> [tracking] Fix build on mac os

omim.pro
Проект не собирается с первого раза, потому что забыли прописать зависимость.
=> [tests] Fix build for tracking_tests

map/api_mark_point.cpp
Fixed issue, when bookmark with "hotel" color become red after app restart
100% reproducing on iOS, should reproduce on Android too:
1. Create bookmark.
2. Set bookmark color "hotel".
3. Save it.
4. Restart app.
Expected result: Created bookmark has "hotel" color
Actual result: It has red color
=> Fixed hotel bookmark color appearance after app restart

indexer/feature_data.cpp
MAPSME-2862
Раньше игнорировали только букинг, теперь не отображаем в РР любые типы из ветки `sponsored`.
=> [opentable] Ignore opentable and other sponsored types in PP

android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp, drape_frontend/stylist.cpp, drape_frontend/stylist.hpp, indexer/drules_selector.cpp, indexer/feature.cpp, indexer/feature_utils.cpp, indexer/feature_utils.hpp, indexer/indexer_tests/feature_names_test.cpp, map/place_page_info.cpp
Поменял приоритет имен для объектов на карте. 
Старая оказалась уже неподходящей потому, что после редактирования имени, мы удаляем дублирующее имя и чаще всего это имя на языке карты, а при отображении объектов на карте у нас приоритет такой
// - device language name;
// - international name;
// - english name;
// - default name;
// - country language name.
Если мы редактируем имя объекта в россии, имя на русском языке удалится, на карте будет отображаться английское имя, если оно есть.
@mpimenov 
@rokuz 
@Zverik
=> [indexer] Poi names priority are changed

indexer/feature_utils.cpp
Когда в результатах поиска вы нажимаете на город, карта к нему перемещается и масштабируется на уровень 9 (около 10 км). Кроме столиц: если ввести Москву и нажать на название города, увидите Кремль на 18-м масштабе. Потому что у неё тип `place-city-capital-2`, а проверка на город идёт только с типом `place-city`. Этот пул-реквест исправляет проверку.
Косвенно связано с MAPSME-2742.
=> [features] Fix zoom level test for city-capitals

android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java
@mpimenov  @milchakov PTAL
- Added clearing the banners when search returns nothing (In downloader)
- Fixed the bug when banners are not showing at all
The initial task was - https://jira.mail.ru/browse/MAPSME-2954
=> [android] Added clearing the banners when search returns nothing

omim.pro
Забыли прописать зависимость от `traffic` для проекта генератор-тула.
=> [build] Fix gtool project dependencies

generator/osm_translator.hpp
MAPSME-2900
Просачивались названия улиц в названия домов в некоторых городах.
=> [generator] Do not copy int_name from relations

map/framework.cpp
«Я сейчас на нескольких зданиях проставил этажность. На тех зданиях, у чьей улицы был name:en и name, без name:ru, addr:street заменился на англоязычный.»
https://editor-api.maps.me/?changeset=43911578
Кажется, я нашёл причину (больше не меняем языки primary и secondary). Проверил на устройстве. @milchakov
=> [editor] Fix localized street names when editing

routing/index_graph.cpp
inline ф-ция объявлена только в cpp.
Такие штуки могут на Android приводить к ошибке линковки, если ф-ция будет публичной или protected.
=> Potential build problem fix.

data/banners.txt, defines.hpp, docs/CPP_STYLE.md, generator/osm2meta.hpp, indexer/CMakeLists.txt, indexer/banners.cpp, indexer/banners.hpp, indexer/feature_meta.cpp, indexer/feature_meta.hpp, indexer/indexer.pro, indexer/indexer_tests/banners_test.cpp, indexer/indexer_tests/indexer_tests.pro, indexer/map_object.hpp, map/framework.cpp, map/framework.hpp, map/place_page_info.cpp, map/place_page_info.hpp
Поле в метаданных для кастомной ссылки и список данных для каждого баннера из файла `banners.txt`. Добавил чтение файла во фреймворк и использование данных в `place_page_info`.
Пока стоит DNM: не дописал тесты и не проверил на живых данных. Тем не менее, код компилируется и требует проверки.
=> [banners] Add banners infrastructure

android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java
Фикс крэша https://www.fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/583ef7150aeb16625b73c609 с 1% сборки.
Фикс заключается в том, что мы не должны вызывать метод handleBannersShow когда показываем баннеры из нашего кэша, так как myTarget сдк в этот момент может не проинициализирован корректно
=> Release 65 hot fix

android/jni/com/mapswithme/core/jni_helper.cpp, android/jni/com/mapswithme/core/jni_helper.hpp, android/jni/com/mapswithme/util/HttpClient.cpp, android/src/com/mapswithme/util/HttpClient.java, platform/http_client.cpp, platform/http_client.hpp, platform/http_client_apple.mm, platform/http_client_curl.cpp
Добавил возможность устанавливать и читать любые хедеры для http запросов.
По-умолчанию хедеры, полученные в ответе, не загружаются, т.к. это не всегда нужно, для загрузки полученных хедеров требуется вызвать LoadHeaders(true) перед отправкой запроса.
@syershov 
@alexzatsepin 
@igrechuhin
=> [platform] Raw headers for http client

drape_frontend/rule_drawer.cpp
Point<float> not init any fields in default constructor,
so TextViewParams::m_primaryOffset can have any value
(depending on previous stack content), which leads to
captions disappearing in DRAW_TILE_NET debug mode.
=> fix tile text disappearing in DRAW_TILE_NET mode

partners_api/booking_api.cpp, platform/network_policy.hpp, routing/routing_session.cpp, tools/unix/build_omim.sh
Пробуем на линуксе перейти на devtoolset-3, который разложили на mapsme3-5. Теперь для сборки не требуется спек, должно собираться просто с помощью gcc. Этот реквест правит три ошибки, которые мешали сборке.
=> [build] Fixed build on linux gcc 4.9

routing/car_router.cpp
Хакфикс странных маневров возле границ mwm.
Полноценное решение: избавиться от OSRM, а пока так.
PTAL @bykoianko
=>  [routing] Fix inadequate routing manoeuvres near the mwm border

routing/edge_estimator.cpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/applying_traffic_test.cpp, traffic/traffic_cache.cpp, traffic/traffic_cache.hpp
@rokuz @mpimenov @ygorshenin прошу оперативно посмотреть.
Оптимизация пробочного кеша для роутинга. 95% трафик информации сейчас составляют зеленые дуги и дуги трафик на которых не известен. В тоже время в роутинге они сейчас не используются. Так не будем их хранить в кеше. Кроме того, сейчас после закачки в TrafficInfo появилось поле vector<RoadSegmentId> m_keys. Оно тоже может быть большим и для роутнига не нужно.
Для Москвы в TrafficInfo передается 945438 дуг. Если из них выкинуть SpeedGroup::G5 и SpeedGroup::Unknown то останется 58518 дуг.
=> Traffic cache for routing memory optimization.

tracking/reporter.cpp
Увеличил период с 10 до 20 секунд, через который gps координаты отправляются на сервер.
=> [tracking] change gps reporter push period from 10 sec to 20 sec

drape_frontend/rule_drawer.cpp
Для левосторонних локаций мы не должны инвертировать порядок следования точек, т.к. этот порядок уже учитывается при расчете входящих и исходящих ребер при матчинге
=> Fixed traffic for left-handed mwms

routing/single_mwm_router.cpp
Вычисление route times основывалось на неявных предположениях о работе ReconstructRoute.
На некоторых маршрутах эти предположения не сбывались.
Починил предположения.
PTAL @bykoianko @ygorshenin
=> [release] [routing] fix route times

indexer/banners.cpp
Поправил формат get_time и убрал CHECK на всякий случай.
=> [banners] Fix crash in banners date parser

routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/car_router.cpp, routing/loaded_path_segment.hpp, routing/osrm_path_segment_factory.cpp, routing/routing_result_graph.hpp, routing/routing_tests/turns_generator_test.cpp, routing/turn_candidate.hpp, routing/turns.cpp, routing/turns.hpp, routing/turns_generator.cpp
Система генерации тернов для A* отдавала много меньше поворотов, чем нужно.
Причина была в том, что мы идентифицировали соединения между joints при помощи feature id. А нужно было чем-то уникальным. Например, mwm id + feature id + seg id + направление.
По интеграционным routing тестам данное исправление несколько улучшает ситуацию. Не проходило 39 из 140. Сейчас 35 из 140.
https://jira.mail.ru/browse/MAPSME-3260
@ygorshenin @dobriy-eeh PTAL
=> [release] Bugfix in turn generation system.

routing/car_model.cpp
Hotfix с прокладкой авто маршрута по highway/pedestrian. Когда будем пересобирать карты IndexGraph надо будет воообще из car_model удалить highway/pedestrian. 
@dobriy-eeh @ygorshenin @mpimenov @alexzatsepin @Zverik PTAL
=> [routing] Hotfix for preventing routing through highway pedestrian

data/banners.txt
Сказав вслух, что для RailEurope можно использовать те же строчки, что для Tutu, забыл закрепить это в конфигурационном файле.
=> [banners] Use tutu strings for raileurope banners

routing/road_graph_router.cpp, routing/routing_helpers.cpp, routing/routing_helpers.hpp, routing/single_mwm_router.cpp, routing/single_mwm_router.hpp
Раньше начало и конец маршрута могли быть только на концах сегментов.
Это приводило к сдвигу начала и конца относительно выбранных пользователем точек.
Поступали на это жалобы.
Этот PR корректирует начало и конец маршрута.
=> [release-70] [routing] Tune start and finish points

CMakeLists.txt
At least fixes the cmake build in Xcode, may also fix the build on the server.
=> Skip compiling desktop app when making ios.

routing/road_graph_router.cpp, routing/routing_helpers.cpp, routing/routing_helpers.hpp, routing/single_mwm_router.cpp
Обработка ошибок возникающих в IDirectionsEngine::Generate().
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5858f58b0aeb16625b352b6d
=> [routing] Crashfix. Processing errors while turn generation.

routing/index_graph_starter.cpp
Исправление креш фикс при прокладке маршрута до ул. Мосфильмовская д. 15:
http://www.openstreetmap.org/way/45423745#map=19/55.71633/37.52047
https://jira.mail.ru/browse/MAPSME-3323
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5858f58b0aeb16625b352b6d/sessions/585907EE039A00015B1E17E80345A767_d8f1cb777c2d4f15ac22bba69e239e9a_0_v1
=> [Routing] crashfix in case of routes passing through loop edges.

drape/oglcontext.hpp, drape/texture.hpp, drape/texture_manager.hpp, drape_frontend/gui/shape.hpp, drape_frontend/map_shape.hpp, geometry/cellid.hpp, indexer/cell_coverer.hpp, indexer/feature_covering.cpp, indexer/indexer_tests/cell_coverer_test.cpp, indexer/mwm_set.hpp, routing/osrm_data_facade.hpp
В двух словах. Раньше в функции ForEachInRect для произвольного ректа мы покрывали его всего 8 ячейками геометрического индекса. Как следствие - в функтор могло приходить много фич, которые не лежат в ректе. Я переписал функцию CoverRect. Теперь вместо 8 используем константу 512 и функция дробит именно крупные ячейки сначала.
Я делал тесты для другого проекта и это показывает хороший прирост в производительности, когда мы в функторе просто вычитываем фичу. Т е лучше провести чуть чуть больше времени на разбитии входного ректа, чем потом вычитывать лишние фичи.
Для убедительности, стресс тест на константу 8 vs 512 при желании сделаете сами.
=> Rect covering in Index::ForEachInRect

data/countries_meta.txt
MAPSME-3420
В Новой Зеландии движение определяется как правостороннее, потому что из-за моих кривых рук у нас нет Новой Зеландии. Есть Южная и Северная Н. З.
=> [generator] Fix New Zealand country names

map/framework.cpp, platform/mwm_version.cpp, platform/mwm_version.hpp
Мы сейчас позволяем редактировать карты, скачанные в марте прошлого года. Не очень хорошо. Этот PR немного сократит набор карт, позволяющих редактирование. По мотивам #5132.
=> [editor] Forbid editing old maps

iphone/Maps/Classes/EAGLView.h, iphone/Maps/Classes/EAGLView.mm, iphone/Maps/Classes/MapsAppDelegate.mm, map/framework.cpp, map/framework.hpp
Если восстанавливать приложение из фона в лэндскейпном режиме (при условии, что свернуто приложение было в портретном), размер вьюпорта вычислялся неправильно. Единственное достоверное место, откуда можно получить текущий размер, это вьюшка.
=> [iOS] Fixed recovering from background in landscape mode

routing/CMakeLists.txt, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/joint_index.cpp, routing/joint_index.hpp, routing/routing.pro, routing/routing_tests/applying_traffic_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/segment.hpp, routing/single_mwm_router.cpp, routing/single_mwm_router.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Смена формата IndexGraph: теперь в нем вершинами являются не Joint::Id, а направленные сегменты дорог.
Что это дает:
1. Более привычное представление для проектного кода в целом.
2. Сильно упрощается реализация restrictions.
3. Избавимся от неоднозначности дуг между Joint'ами. Эти неоднозначности приводили к различным багам в некоторых ситуациях (гонки между дорогами, петли).
4. Устранены ненадежные функции FindPointsWithCommonFeature и RedressRoute.
5. Упрощается починка бага со сдвигом стартовой точки.
PTAL
=> [routing] Invert index graph

generator/generator_tests/osm_type_test.cpp
Добавили новый тип, и его отловил `osm_type_test`. Чиню его.
=> [tests] Fix generator test after hwtag-yescar type was added

routing/car_model.cpp, routing/edge_estimator.cpp, routing/geometry.cpp, routing/geometry.hpp, routing/index_graph.cpp
1. Удалено highway=pedestrian из car_model;
2. Изменен код, чтоб работать в ситуациях, когда mwm в mwm и в исходниках(car_model) содержится разный набор highway.
@Zverik @dobriy-eeh @ygorshenin @mpimenov PTAL
=> Removing highway=pedestrian.

generator/osm2meta.cpp, generator/osm2meta.hpp, generator/osm2type.cpp, indexer/feature_meta.cpp
Fixes #1740. Тегов `wifi=*` десять тысяч, хорошо бы их поддержать.
При сохранении будут добавляться теги `internet_access=wlan`, но это даже хорошо.
Заодно убрал `FMD_URL`, это одно и то же, что `FMD_WEBSITE`.
=> [generator] Process wifi=* tags and discard FMD_URL

base/stl_iterator.hpp
У нас сейчас osrm-backend не собирается под centos с gcc, потому что в нашей копии boost какая-то фигня.
=> [boost] Use system boost in stl_iterator

routing/index_graph.cpp
Допущение разворота только на точках пересечения с другими фичами и на (висящих) концах фич.
Данное изменение уменьшает время прокладки маршрута (A* на IndexGraph) на 25%-30%.
Детали. Я провел ряд тестов тестов на десктоп (release). Два маршрута. С данным изменением и без. По 3 измерения для каждого маршрута. Вот результаты:
```
Без данного PR:
Сокол - Кузьминки
findEndsS: 0.00782377 loadingGraphS: 0.110006 findingRouteS: 0.669541 reconstructingPathS: 1.30794
findEndsS: 0.00169901 loadingGraphS: 0.106325 findingRouteS: 0.668534 reconstructingPathS: 1.28947
findEndsS: 0.00154356 loadingGraphS: 0.0969779 findingRouteS: 0.662691 reconstructingPathS: 1.28333
Деловой центр - Черкизовская
findEndsS: 0.00131356 loadingGraphS: 0.0981052 findingRouteS: 0.696425 reconstructingPathS: 1.68831 …
```
=> Prohibition of uturn on intermediate feature points

routing/routing_tests/index_graph_test.cpp
Действительно, тест проверяет наличие исходящих дуг из разных точек графа.
Но исходящие дуги, обеспечивающие разворот после 5195 не выходят.
=> Test fix after PR #5195

routing/CMakeLists.txt, routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/directions_engine.cpp, routing/directions_engine.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/pedestrian_directions.cpp, routing/pedestrian_directions.hpp, routing/road_graph.hpp, routing/routing.pro, routing/routing_helpers.cpp, routing/routing_helpers.hpp, routing/single_mwm_router.cpp, routing/single_mwm_router.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Первый этап рефакторинга ReconstructRoute: она теперь берет ребра не из геометрического индекса, а из IndexGraph. Это ускоряет общее время поиска примерно в два раза.
На ноутбуке маршрут от метро Аэропорт до метро Царицыно прокладывался 4 секунды, после изменений прокладывается за 2 секунды.
Также в изменения входят:
1. Корректировка старта и финиша маршрута (чтобы находились не на концах сегмента, а там где укажет пользователь).
2. Корректировка времени прокладки маршрута, умножение на 1.8
PTAL
=> [routing] reconstruct route refactoring, also fix endpoints and times

routing/car_router.cpp
Исправление часто встречаемой ошибки, когда около границы mwm путь делает странные скачки в сторону.
Много примеров бага есть в https://jira.mail.ru/browse/MAPSME-3456
=> [routing] fix cross mwm routes

routing/edge_estimator.cpp, routing/geometry.cpp, routing/vehicle_model.cpp
Исправление сломанных маршрутов, которые ломались при попытке проложиться через паром.
Примеры бага есть в https://jira.mail.ru/browse/MAPSME-3546 и https://jira.mail.ru/browse/MAPSME-3456
Суть бага была в том, что хотя паромная переправа верно определялась как дорога, через которую можно проехать, из-за неверно переданного параметра её скорость рассчитывалась как 0 и дальше роутинг ломался.
PLAL @bykoianko @syershov @Zverik
=> [routing] fix ferry routes

routing/index_graph_starter.cpp, routing/routing_tests/index_graph_test.cpp
В интеграционном тесте RussiaMoscowNagatinoUturnTurnTest было обнаружено срабатывание проверки инварианта в astar.
Ошибку удалось свести к более простому случаю, который описан в тесте OneSegmentWay (присутствует в этом PR) и починить.
PTAL @bykoianko @syershov
=> [routing] fix one segment way

data/banners.txt
Решили убрать дыру, позволяющую пользователям, которые не обновляются, лишиться удовольствия кликать на баннеры.
=> [banners] Postpone banner off date by three months

routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/segment.hpp
Ошибка найдена в https://jira.mail.ru/browse/MAPSME-3632
Суть в следующем: иногда маршрут петляет и проходит через один и тот же junction в разных направлениях. Класс IndexRoadGraph не учитывал такой случай и возвращал не все ребра, из-за чего маршрут не прокладывался.
PTAL
=> [routing] Fix double junction route

routing/car_router.cpp, routing/car_router.hpp
https://jira.mail.ru/browse/MAPSME-3632
Проблема в следующем. Если старт и финиш лежат внутри одной mwm и внутри mwm-й маршрут не может быть проложен, то мы пытаемся проложить крос mwm-й маршрут и если он прокладывается, то используем его.
На техническом уровне. Ввиду того, что в качестве результата прокладки маршрута выдаются односегментные дуги (и каждая вторая дуга имеет длину 0) ReconstructPath стал чаще возвращать, что не может реконструировать маршрут. Чаще всего проблема возникает в BicycleDirectionsEngine::Generate(...), которая вызывается из ReconstructPath. Правильным решением видится:
- сделать, чтоб BicycleDirectionsEngine::Generate(...) не создавала линию маршрута. Не правильно, что генератор тернов создает геометрию маршрута;
- сделать, чтоб в ReconstructPath …
=> [Release only] Block cross mwm routing in case of single mwm route cannot be found.

map/style_tests/classificator_tests.cpp
Перенумеровал тесты в соответствии с комментариями и добавил проверку, что реки не прячутся под полями и лесами.
=> [tests] Add riverbank to area priority tests

base/checked_cast.hpp
Добавил дополнительную проверку в checked_cast/asserted_cast для преобразования signed/unsigned типов.
Пример, где она необходима: checked_cast<uint8_t>( int8_t(-2) )
PTAL @syershov
=> [base] fix signed/unsigned checked_cast

skin_generator/skin_generator.cpp, skin_generator/skin_generator.hpp
Из-за строки с `my::clamp` генератор текстур вообще не собирался. Ну и попутно поправил ошибки с преобразованиями и сравнениями знаковых и беззнаковых типов.
=> [build] Fix warnings and an error in skin_generator

routing/CMakeLists.txt, routing/cross_mwm_index_graph.hpp, routing/routing.pro, routing/segment.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Реализация интерфейса для получения информации для меж mwm-го роутинга.
Для реализации mwm-го роутинга на базе разных версий карт требуется получать определенную информацию о меж mwm-х переходах. Данный интерфейс предназначен для этого. 
В плане данных возможны следующие варианты:
Карты ранее чем декабрь 2016 => используем полностью старый механизм меж mwm-го роутинга;
Карты декабрь 2016 - февраль 2017 => используем CrossMwmIndexGraph() интерфейс с информацией из osrm-ой меж mwm-ой секции.
Карты позже чем февраль 2017-го => используем CrossMwmIndexGraph() интерфейс с информаций из новой меж mwm-ой секции посчитанной на базе A* и не содержащей osrm информацию.
@dobriy-eeh @mpimenov @ygorshenin PTAL
=> [routing] Interface for getting cross mwm information CrossMwmIndexGraph.

map/framework.cpp, routing/CMakeLists.txt, routing/num_mwm_id.hpp, routing/routing.pro, routing/segment.hpp, storage/storage.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Добавил целочисленный идентификатор mwm.
Он нужен для эффективной идентификации сегментов дорог на всем земном шаре.
Это будет использоваться в cross mwm роутинге.
=> [routing] numeric mwm id

android/src/com/mapswithme/maps/downloader/DownloaderFragment.java
don’t show soft keyboard on downloader fragment(https://jira.mail.ru/browse/MAPSME-3791).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] don’t show soft keyboard on downloader fragment

routing/cross_mwm_index_graph.cpp
Поправил баг с тем, что OsrmFtSegMapping::m_handle был пуст при вызове CrossMwmIndexGraph::IsTransition()
=> Adding MappingGuard to CrossMwmIndexGraph::IsTransition().

routing/cross_mwm_index_graph.cpp, routing/cross_mwm_index_graph.hpp, routing/cross_mwm_road_graph.cpp, routing/cross_routing_context.cpp, routing/cross_routing_context.hpp, routing/routing_tests/cross_routing_tests.cpp
OSRM вариант реализации метода по получению близницов. 
Идея  по получению близницов проста (CrossMwmIndexGraph::GetTwins()):
1. из CrossRoutingContextReader получаем список mwm соседий для данной mwm;
2. загружаем в кеш переходные сегменты для соседних mwm;
3. по координате (о очень большим прямоугольником со стороной в 2 * 0.001 градус, как в OSRM) ищем близнецов в соседних mwm. Зачем такой большой "квадрат" поиска пока не знаю, но такой был в OSRM, потому и оставил.
=> CrossMwmIndexGraph::GetTwins() osrm implementation.

data/categories.txt, data/mapcss-mapping.csv
Марат попросил добавить `shop=coffee` и `shop=tea`: их большее двух тысяч каждых в планете.
Заодно сейчас Юра попросил поправить ситуацию с переводами `historic=memorial` и `historic=monument`. Там действительно [чехарда](https://wiki.openstreetmap.org/wiki/RU:Tag:historic%3Dmonument).
Стили не пересобирал, чтобы не мешать паралелльным пул-реквестам.
=> [types] Added coffee and tea shops, and switched some translations

routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/index_graph_loader.cpp, routing/index_graph_loader.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/applying_traffic_test.cpp, routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp, routing/segment.hpp, routing/single_mwm_router.cpp, routing/single_mwm_router.hpp, routing/traffic_stash.hpp, routing/world_graph.cpp, routing/world_graph.hpp, traffic/traffic_cache.cpp, traffic/traffic_cache.hpp
Cross mwm роутинг с помощью прыжков: ребер основанных на предрассчитанных маршрутах между входами и выходами внутри mwm.
Основано на использование функции CrossMwmGraph::GetEdgesList()
Подготовительный pull request, то есть функционал не подключен и не влияет на работу приложения.
=> [routing] Cross mwm leaps

3party/opening_hours/CMakeLists.txt, 3party/opening_hours/opening_hours.pro, 3party/opening_hours/opening_hours_parsers.hpp, 3party/opening_hours/parse_months.cpp, 3party/opening_hours/parse_opening_hours.cpp, 3party/opening_hours/parse_timespans.cpp, 3party/opening_hours/parse_weekdays.cpp, 3party/opening_hours/parse_weeks.cpp, 3party/opening_hours/parse_years.cpp, CMakeLists.txt, coding/simple_dense_coding.cpp, pyhelpers/vector_list_conversion.hpp, tracking/pytracking/CMakeLists.txt, traffic/pytraffic/CMakeLists.txt
=> [build] Use system-provided boost instead of 3party in cmake.

base/CMakeLists.txt, base/base.pro, base/random.cpp, base/random.hpp, routing/cross_mwm_road_graph.cpp, routing/cross_mwm_road_graph.hpp, routing/cross_routing_context.cpp, routing/cross_routing_context.hpp, routing/routing_integration_tests/cross_section_tests.cpp, search/pre_ranker.cpp, xcode/base/base.xcodeproj/project.pbxproj
1. Реализована обратная волна в классе CrossMwmGraph. Т.е. метод CrossMwmGraph::GetIngoingEdgesList() и методы необходимые для его реализации.
2. Написан тест (в routing_integration_test), который проходится по всем входам всех mwm всего мира. Для каждого входа ищет все доступные выходы в данной mwm. Для каждого найденного выхода - ищет все входы и проверяет, что среди них есть вход, с которого начали.
Замечания:
- Тест, указанный в (2) занимает 3 часа и должен выполняться над картой мира. Я пока не решил, что с ним делать. Вероятно, оставлю в routing_integration_test и закомментирую. Если есть идеи - пишите.
- Несложно заметить, что в коде есть срытый copy paste. Он связан с тем, что в сигнатурах многих функций используется …
=> Backward wave in CrossMwmGraph

coding/zlib.cpp
На линуксе не собирался проект, нашёл причину: старый zlib. Юра сказал, что этот кусок кода не обязательный, поэтому просто уточнил `#if`.
=> [zlib] Refine #if for zlib destructor

map/framework.cpp, routing/routing_session.cpp, routing/routing_session.hpp, tracking/reporter.cpp, tracking/reporter.hpp, tracking/tracking_tests/reporter_test.cpp
Протянул информацию о трафике из роутинга в tracking::Reporter
Дубликат https://github.com/mapsme/omim/pull/5526, только тот по ошибке был сделан в мастер, а этот в release-72
Откатывать https://github.com/mapsme/omim/pull/5526 не надо, его все равно потом бы пришлось переносить в master.
=> [release-72] [tracking] Add traffic info to tracking reporter

routing/directions_engine.cpp, routing/index_router.cpp, routing/index_router.hpp, routing/world_graph.cpp, routing/world_graph.hpp
При запуске меж-mwm-ного роутинга с прыжками ломался ReconstructRoute.
Проблема была в том, что граф при ReconstructRoute работал в режиме прыжков, а путь был уже полный, и не находились внутренние ребра mwm, через которую перепрыгнули.
Фикс этой поломки.
=> [routing] fix reconstruct route while cross mwm leaps

android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 225, size is 225
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at com.mapswithme.maps.downloader.DownloaderAdapter$HeaderViewHolder.bind(DownloaderAdapter.java:637)
at com.mapswithme.maps.downloader.DownloaderAdapter.onBindHeaderViewHolder(DownloaderAdapter.java:873)
at com.mapswithme.maps.downloader.DownloaderAdapter.onBindHeaderViewHolder(DownloaderAdapter.java:52)
at com.timehop.stickyheadersrecyclerview.caching.HeaderViewCache.getHeader(HeaderViewCache.java:35)
at com.timehop.stickyheadersrecyclerview.StickyRecyclerHeadersDecoration.getHeaderView(StickyRecyclerHeadersDecoration.java:148)
at …
```
=> [android] Attempted to fixed crash in download adapter

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/Utils.java
В Fabric есть подобные крэши:
```
Fatal Exception: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: my_ZG
at java.util.Currency.getInstance(Currency.java:84)
at com.mapswithme.maps.widget.placepage.PlacePageView.setMapObject(PlacePageView.java:887)
at com.mapswithme.maps.MwmActivity.onMapObjectActivated(MwmActivity.java:1161)
at com.mapswithme.maps.search.SearchEngine.nativeShowResult(SearchEngine.java)
at com.mapswithme.maps.search.SearchEngine.showResult(SearchEngine.java:148)
at com.mapswithme.maps.search.SearchFragment.showSingleResultOnMap(SearchFragment.java:480)
at com.mapswithme.maps.search.SearchAdapter$ResultViewHolder.processClick(SearchAdapter.java:222)
at com.mapswithme.maps.search.SearchAdapter$BaseResultViewHolder$1.onClick(SearchAda …
```
=> [android] Added hanlding of errors while getting a currency code

testing/testingmain.cpp
This PR allows to write
```./search_tests --filter=Smoke```
instead of current
```./search_tests --filter='.*Smoke.*'```
=> [testing] Relaxed the filters in regular expressions.

data/countries_meta.txt
MAPSME-4088
В Панаме государственный язык — испанский. Мы этого не знали.
=> [editor] Added default language for Panama

tools/unix/build_omim.sh
Without this patch, building barfs while trying to link OSRM because it
can't find librouting_common.a in the requested location.
Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>
=> Fix up "CONFIG=gtool build_omim.sh -cro"

tools/python/booking_hotels.py, tools/unix/build_omim.sh
Букинг начал возвращать ошибки в простой структуре с `code` и `message`, чего наш скрипт не ожидал.
Также поправил сборку с cmake. Увы, из-за разных неожиданных косяков её пока не сделать основным видом сборки.
=> [build] Fix cmake in build_omim and error detection in booking_hotels

routing/base/astar_algorithm.hpp, routing/car_router.cpp, routing/cross_mwm_index_graph.cpp, routing/cross_mwm_index_graph.hpp, routing/cross_mwm_road_graph.cpp, routing/cross_mwm_road_graph.hpp, routing/cross_routing_context.hpp, routing/index_router.cpp, routing/osrm2feature_map.hpp, routing/osrm_engine.hpp, routing/osrm_path_segment_factory.cpp, routing/osrm_path_segment_factory.hpp, routing/routing_integration_tests/cross_section_tests.cpp, routing/routing_tests/cross_routing_tests.cpp, routing/segment.hpp
* реализация метода для получения списка прескоков в cross mwm-ом роутинге на базе OSRM;
* реализовано кеширование MappingGuard при кросс mwm-ом роутинге;
* включен WorldGraph;
Данный PR тестировался на маршрутах:
Москва - Лиссабон, Москва - Париж, Москва - Берлин, Москва - Минск
=> CrossMwmIndexGraph::GetEdgeList(...) implementation.

indexer/map_style_reader.cpp, tools/python/generate_styles_override.py
- Добавлена возможность перезаписывать файлы стилей путем помещения их в специальную папку в директорию для записи. Это позволит дизайнерам тестировать новые стили на телефоне.
- Скрипт для генерации папки, которую нужно подкладывать в директорию для записи. Скрипт генерирует папку по данным, которые выдает дизайнер-тул.
=> Added styles overrides

drape_frontend/apply_feature_functors.cpp, drape_frontend/apply_feature_functors.hpp, drape_frontend/rule_drawer.cpp, drape_frontend/stylist.cpp, drape_frontend/stylist.hpp, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp
Do not render building feature if it is not a building part but has building parts.
=> has_parts type checking (for more accurate rendering of 3d buildings).

.gitmodules, tools/unix/build_designer.sh
Используем https://github.com/aurelien-rainone/macdeployqtfix , чтобы собранные пакеты использовали правильные модули Qt.
(NB: пул-реквест в ветку designer tool)
=> MacDeployQtFix until we use Qt 5.10

android/build.gradle, android/res/layout/place_page_banner.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/ads/AdTracker.java, android/src/com/mapswithme/maps/ads/BaseNativeAdLoader.java, android/src/com/mapswithme/maps/ads/DefaultAdTracker.java, android/src/com/mapswithme/maps/ads/FacebookAdError.java, android/src/com/mapswithme/maps/ads/FacebookAdsLoader.java, android/src/com/mapswithme/maps/ads/FacebookNativeAd.java, android/src/com/mapswithme/maps/ads/Factory.java, android/src/com/mapswithme/maps/ads/MwmNativeAd.java, android/src/com/mapswithme/maps/ads/NativeAdError.java, android/src/com/mapswithme/maps/ads/NativeAdListener.java, android/src/com/mapswithme/maps/ads/NativeAdLoader.java, android/src/com/mapswithme/maps/ads/OnAdCacheModifiedListener.java, android/src/com/mapswithme/maps/bookmarks/data/Banner.java, android/src/com/mapswithme/maps/widget/placepage/BannerController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageVisibilityProxy.java, android/src/com/mapswithme/util/statistics/Statistics.java
@goblinr @mpimenov PTAL
We always show cached banner for a placement_id if we have one. Otherwise we do 2.
Every time a banner is needed (pp opens, search opens and so on), despite of what we're showing in the banner slot, we will:
Check if this banner has been showed at least N (2) seconds on the screen (cumulatively) and there's at least M (30) seconds interval between the first time it was requested and the current moment.
If the previous check was successful, app must make a request to the FB API and try to get a new banner. If that request was a success app sets a new cached banner for a specified placement_id.
If there's any pending request for the same placement_id app must not start a new one.
=> [android] Mapsme 4114 fb banners cache

generator/feature_sorter.cpp, generator/gen_mwm_info.hpp, generator/generator_tests_support/routing_helpers.cpp, generator/osm_id.hpp, generator/routing_generator.cpp, generator/routing_helpers.cpp, omim.pro, tools/python/mwm/dump_mwm.py, tools/python/mwm/ft2osm.py, tools/python/mwm/mwm.py
Появилась задача искать osm id для произвольных объектов из mwm. Поэтому osm2ft боле не промежуточный файл, а важный элемент сгенерированных файлов, лол.
=> [osm2ft] Write osm ids for all features, not just for roads

generator/routing_index_generator.cpp, generator/routing_index_generator.hpp, geometry/region2d.hpp, routing/CMakeLists.txt, routing/coding.hpp, routing/cross_mwm_connector.hpp, routing/cross_mwm_connector_serialization.cpp, routing/cross_mwm_connector_serialization.hpp, routing/index_graph_serialization.hpp, routing/routing.pro, routing/routing_tests/CMakeLists.txt, routing/routing_tests/coding_test.cpp, routing/routing_tests/cross_mwm_connector_test.cpp, routing/routing_tests/routing_tests.pro, xcode/routing/routing.xcodeproj/project.pbxproj
Сжатие cross mwm секции.
Веса прыжковых дуг (leaps) хранятся с точностью до 4 секунд.
С этой точностью для Москвы секция занимает ~800 kb.
Каждое увеличение точности в два раза стоит 100 kb
То есть если хранить с точностью до 2 секунд будет занимать ~900 kb
Если до 1 секунды - то 1 mb
Алгоритм сжатия:
Сортируем переходы вдоль границы по часовой стрелке, далее пишем разницу delta кодером.
=> [routing] Cross mwm section compression

drape_frontend/apply_feature_functors.cpp, drape_frontend/apply_feature_functors.hpp, generator/intermediate_elements.hpp, generator/osm_translator.hpp, indexer/road_shields_parser.cpp, indexer/road_shields_parser.hpp
MAPSME-3758
В Европе, США и многих других странах номер дороги записывают не только в ref, но ещё и в отношение. Иногда — только в отношение. Самый явный пример — европейские маршруты с номерами Е. Этот реквест добавляет их поддержку: сначала генератор переносит теги `network/ref` с отношения на дорогу, затем рендерер обрабатывает такие пары.
Заметная проблема — вторые и последующие номера отображаются редко.
=> [shields] Process road networks on relations

coding/uri.cpp, map/map_tests/mwm_url_tests.cpp, xcode/map/map.xcodeproj/project.pbxproj
https://tools.ietf.org/html/rfc3986#page-11
6.2.2.1. Case Normalization
When a URI uses components of the generic syntax, the component syntax equivalence rules always apply; namely, that the scheme and host are case-insensitive and therefore should be normalized to lowercase. For example, the URI is equivalent to http://www.example.com/.
The other generic syntax components are assumed to be case-sensitive unless specifically defined otherwise by the scheme (see Section 6.2.3).
=> Fixed uri tests.

routing/CMakeLists.txt, routing/cross_mwm_connector.cpp, routing/cross_mwm_connector_serialization.hpp, routing/cross_mwm_graph.cpp, routing/cross_mwm_graph.hpp, routing/cross_mwm_index_graph.cpp, routing/cross_mwm_index_graph.hpp, routing/cross_mwm_osrm_graph.cpp, routing/cross_mwm_osrm_graph.hpp, routing/cross_mwm_road_graph.cpp, routing/cross_mwm_road_graph.hpp, routing/cross_mwm_router.cpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing.pro, routing/routing_integration_tests/cross_section_tests.cpp, routing/routing_tests/cross_mwm_connector_test.cpp, routing/transition_points.hpp, routing/world_graph.cpp, routing/world_graph.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Реализация методов по получению меж mwm-ой информации на базе новой (не OSRM) секции (cross_mwm). Поддержка получения меж mwm-ой информации для смеси mwm с OSRM и без.
Ограничения:
- сейчас не корректно работает метод: CrossMwmIndexGraph::GetEdgeList() на новых mwm. Онa возвращает переходы через mwm, но маршрут потом не прокладывается. Вероятно, не удается получить близнецы к этим переходам. Вероятно, сами переходы не корректны. Буду разбираться.
- если карта состоит из смеси mwm, не все переходы через смешанную границу (не osrm - osrm) возвращаются корректно. Похожий баг был и ранее переходом через границы osrm-osrm. Данный баг я не планирую лечить, поскольку ресурсы ограничены. Важно, чтоб на новых mwm все отрабатывало корректно.
=> [routing] Implementation of cross mwm methods (CrossMwmIndexGraph) for cross_mwm(non osrm) section.

generator/generator_tests/restriction_collector_test.cpp, generator/generator_tool/generator_tool.cpp, generator/restriction_collector.cpp, generator/restriction_collector.hpp, generator/road_access_generator.cpp, generator/routing_helpers.cpp, generator/routing_helpers.hpp, generator/routing_index_generator.cpp, generator/routing_index_generator.hpp, routing/cross_mwm_connector.cpp, routing/cross_mwm_connector.hpp, routing/cross_mwm_connector_serialization.cpp, routing/cross_mwm_connector_serialization.hpp, routing/routing_tests/cross_mwm_connector_test.cpp
Добавил в cross mwm секцию osm id для транзитных дорог.
Osm id нужны для более надёжного и оптимального связывания между mwm.
Без них это приходится делать приблизительно, по геометрии.
=> [routing] Add osm ids to cross mwm section

map/framework.cpp
Квадродерево, которое содержит bounding boxes всех mwm.
Нужно для того, чтобы понять какие mwm покрывают данную точку, чтобы попытаться найти в них близнеца при переходе между mwm.
Поскольку bounding box больше чем сама mwm, может выдавать ложные срабатывания, что для поиска близнецов приемлемо.
=> [routing] mwms tree4d for cross mwm router

generator/generator_tool/generator_tool.cpp, generator/routing_index_generator.cpp, generator/routing_index_generator.hpp
Добавил флаг для управления логами сборки cross mwm секции.
По умолчанию прогресс печатается в виде:
Building leaps: 10 / 239 waves passed
Building leaps: 20 / 239 waves passed
Building leaps: 30 / 239 waves passed
...
Можно выставить cross_mwm_progress_peroid=0, чтобы отключить эти логи, которые не нужны при автоматической сборке карт на сервере.
=> [routing] Flag for disabling cross mwm progress logs

routing/routing_session.cpp
При сборе статистики для роутингf информация о зеленых сегментах отбрасывалась и заменялась на Unknown.
=> [routing] Fix traffic statistics for SpeedGroup::G5

routing/base/astar_algorithm.hpp
Небольшая оптимизация AStar.
Ускоряет прокладку маршрута примерно на 12%
Измерял на маршруте метро Аэропорт - метро Царицыно
Время уменьшилось с 1.36 до 1.20 секунд (на ноутбуке)
=> [routing] Bidirectional Astar optimization

search/search_quality/assessment_tool/context.cpp, search/search_quality/assessment_tool/context.hpp, search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_model.hpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/assessment_tool/model.hpp, search/search_quality/assessment_tool/result_view.cpp, search/search_quality/assessment_tool/result_view.hpp, search/search_quality/assessment_tool/results_view.cpp, search/search_quality/assessment_tool/results_view.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/assessment_tool/view.hpp
Added a simple list view for results that are present in the search samples json, but weren't retrieved by the search engine. Relevances of these results may be modified by the user and these modifications will be saved.
@milchakov @bykoianko PTAL
=> [assessment-tool] Added view for non-found results.

routing/cross_mwm_graph.cpp, routing/cross_mwm_graph.hpp
Данный PR исправляет ситуации, когда были попытки проложить маршрут по одной mwm без cross_mwm секции. И маршрут были достаточно длинные, что волна подходила к краю mwm.
Причина, на наличие секции cross_mwmw проверялись только соседи, но не проверялась текущая mwm.
@dobriy-eeh @mpimenov @ygorshenin PTAL
=> [routing] Little number of mwm without cross_mwm section fix.

data/mapcss-dynamic.txt, indexer/drules_selector.cpp
Поддержка селектора для рейтинга гостиницы. Работает только для гостиничных типов. Позволяет написать такое:
```css
node|z16-[tourism=hotel],
node|z14-[tourism=hotel][rating>7] {
icon-image: hotel.svg;
}
```
=> [styles] Rating drules selector

routing/cross_mwm_graph.hpp, routing/cross_mwm_index_graph.hpp, routing/cross_mwm_osrm_graph.hpp, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/world_graph.cpp, routing/world_graph.hpp
Если mwm являются соседями или начало и конец лежат в одной mwm - то маршрут считается точно, но без оптимизаций. Под соседними понимается, что прямоугольник полностью содержащий стартовую mwm накрывает какую-то часть финишной mwm. Например, так считаются маршрут Москва-Москва, Москва-Область, Москва-Тверь.
Если mwm удалены друг от друга, то старт и финиш соединяются со всеми переходными точками mwm и затем считается кросс mwm-й маршрут. После чего считаются маршруты внутри mwm.
Данный PR дает значительное ускорение при прокладке длинных маршрутов (300 км и более), хотя может давать не точности в вычислениях. В то время как на коротких маршрута (мене 300 км) сохраняется точность и обеспечивается скорость.
Результаты измерений времени прокладки маршрута на iPhone 7:
Офис (м. Аэропорт) - …
=> [routing] Graph shortcut optimization for long routes.

map/framework.cpp
WTR:
1. Подложить Russia_Moscow.mw версии 161105 (до того, как появилась секция с index graph). Mwm с подмосковьем должны отсутствовать.
2. Проложить маршрут из Москвы в подмосковье.
Наблюдаемое поведение: maps.me предложит скачать подмосковье. После скачки получится несовместимое сочетание из Москвы старой версии и нового подмосковья, на котором роутинг работать не будет.
Ожидаемое поведение: maps.me должна предложить скачать подмосковье и Москву.
https://jira.mail.ru/browse/MAPSME-3905
=> [routing] Fix updating of mixed maps

routing/routing_settings.hpp
Притягивание направления движения по маршруту и для пешеходного роутинга.
@dobriy-eeh @ygorshenin PTAL
=> [routing] Using route bearing matching for pedestrian routing.

routing/index_router.cpp
В случае прокладки маршрута с эвристикой с достроением дуг от старта ко всем выходам из mwm и от всех входов к финишу используется прокладка маршрута по мировому графу.
=> [routing] Route calculation on world graph in case of start and finish leaps.

routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp
После того как поменяли скорости в car model, сломался один из тестов.
Починил.
=> [routing] Fix index_graph_test.cpp::RestrictionTest_LoopGraph

routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp
Исправление бага https://jira.mail.ru/browse/MAPSME-4172
Нарушался инвариант в AStar.
Причина была в том, что IndexGraphStarter был рассчитан на то, что стартовая и финишная точка лежат на стартовом и финишном сегменте соответственно.
Раньше это обеспечивала инфраструктура, которая располагалась выше по callstack. Теперь это не так, нужно делать проекцию непостредственно в starter.
=> [routing] fix crash near zoo

coding/transliteration.cpp
Transliteration of "МЭИ":
M·EI → MEI
=> Removed characters 'APOSTROPHE' and 'MIDDLE DOT'

map/framework.cpp
Гиперлокальная реклама должна инициироваться после storage, иначе на старте MwmId не находятся по имени.
=> Fixed local ads manager initialization

search/search_quality/assessment_tool/context.cpp, search/search_quality/assessment_tool/edits.cpp, search/search_quality/assessment_tool/edits.hpp, search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_model.hpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/assessment_tool/result_view.cpp, search/search_quality/assessment_tool/result_view.hpp, search/search_quality/assessment_tool/results_view.cpp, search/search_quality/assessment_tool/results_view.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/assessment_tool/view.hpp
@mpimenov @milchakov PTAL
Deletion is implemented in a lazy way - deleted items are actually marked as "deleted", and won't be saved or displayed to the user.
Pros of this approach:
* no dangling references/pointers, no deletions in vectors
* instead of changing visibility of "deleted" items we can, for example, set red background for such items, so this approach allows us to experiment with UX
Cons of this approach:
* need to handle "deleted" state for all samples in the model and in the view
=> [assessment-tool] Impemented deletion of non-found samples.

android/gradle.properties, android/src/com/mapswithme/maps/ads/MopubNativeAd.java, android/src/com/mapswithme/maps/ads/MopubNativeDownloader.java
https://jira.mail.ru/browse/MAPSME-4555
В общем наш листенер для нашей статистики (кликов и показов) перезатирал листенер Мопаба, и показы и клики в мопабе поэтому были равны нулю. В общем не тому объекту я листенер устанавливал (слишком низкоуровневому), исправил это в этом реквесте.
=> [android] Fixed mopub impression and clicks tracking

indexer/mwm_set.hpp, map/framework.cpp, map/traffic_manager.cpp, map/traffic_manager.hpp
Пофиксил случай, когда мы обновляем карту, а в трафик менеджере не обновляется список валидных mwm
=> traffic manager map deregistered fix

routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing_integration_tests/osrm_route_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_tests/index_graph_test.cpp, routing/world_graph.cpp, routing/world_graph.hpp
Данный PR исправляет ряд тонких багов в системе маршрутизации. 
В первом коммите (Routing issue fixes...):
1. Исправлено нарушение инварианта эвристики A*, если старт указан около переходного сегмента. Это было связано с тем, что в этой ситуации для переходного сегмента выдавалась одна координата, а для его близнеца другая. Главное исправление в IndexGraphStarter::GetPoint();
2. Возможность разворота не на joint, а на road point после склеивания маршрута из кусочков при cross mwm routing. Ранее разворот на road point, которая не является joint был возможен, при наличии разворота сразу после переходной точки;
3. Корректность сегментов маршрута после склеивания из кусочков. Ранее корректность нарушалась при наличии разворота сразу после переходной точки;
Во втором коммите ([routing] Route …
=> [release-73] Routing issue fixes.

data/categories.txt
«Велостоянка українською так и будет -"велостоянка". "Велозупинка" = "велоостановка". Общественного велотранспорта у нас, к превеликому сожалению, пока нет» — пишет нам участник из Украины.
=> [categories] Fixed bike parking Ukrainian translation

base/string_utils.cpp, base/string_utils.hpp, indexer/indexer_tests/search_string_utils_test.cpp, indexer/postcodes_matcher.cpp, indexer/search_string_utils.cpp, indexer/search_string_utils.hpp, indexer/string_set.hpp, search/search_integration_tests/processor_test.cpp
'#' and '№' before digits are considered as spaces now.
=> [search] Fixed numero signs in search queries and names.

generator/booking_dataset.cpp
А то default name слишком многозначен, иногда приложение начинало его транслитерировать.
=> [booking] Use English for default booking name instead of Default

android/jni/com/mapswithme/opengl/androidoglcontextfactory.cpp
Некоторые андроиды возвращают EGL_TRUE, для ситуации, когда count == 0
=> Fixed GL-context initialization for ES2-Android

base/logging.cpp, base/logging.hpp, qt/CMakeLists.txt, qt/main.cpp, qt/qt.pro
Sometimes debug build of desktop app crashes because of LERROR messages from HttpThread (as it tries to download local_ads). This flags makes it possible to modify severity of abort messages.
=> [qt] Implemented log-abort-level flag for Qt Desktop app.

map/framework.cpp, map/mwm_tree.hpp, routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/directions_engine.cpp, routing/index_router.cpp, routing/loaded_path_segment.hpp, routing/road_graph_router.cpp, routing/road_graph_router.hpp, routing/routing_benchmarks/bicycle_routing_tests.cpp, routing/routing_benchmarks/helpers.cpp, routing/routing_benchmarks/helpers.hpp, routing/routing_benchmarks/pedestrian_routing_tests.cpp, routing/routing_helpers.cpp, routing/routing_integration_tests/get_altitude_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/turns.cpp, routing/turns.hpp, routing/turns_generator.cpp
1. Правильная генерация маневров при авто (index_graph) и вело роутинге;
2. Удаление дублирующихся точке в маршруте;
3. Исправление срабатывающего ASSERT на не уникальность uniNodeId. (Они были не уникальны при фейковых фичах);
=> [routing] Turn generation fix. Removing segments duplicates.

map/mwm_tree.hpp, routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/directions_engine.cpp, routing/index_router.cpp, routing/loaded_path_segment.hpp, routing/road_graph_router.cpp, routing/road_graph_router.hpp, routing/routing_benchmarks/bicycle_routing_tests.cpp, routing/routing_benchmarks/helpers.cpp, routing/routing_benchmarks/helpers.hpp, routing/routing_benchmarks/pedestrian_routing_tests.cpp, routing/routing_helpers.cpp, routing/routing_integration_tests/get_altitude_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/turns.cpp, routing/turns.hpp, routing/turns_generator.cpp
cherry-pick https://github.com/mapsme/omim/pull/6198
Правильная генерация маневров при авто (index_graph) и вело роутинге;
Удаление дублирующихся точке в маршруте;
Исправление срабатывающего ASSERT на не уникальность uniNodeId. (Они были не уникальны при фейковых фичах);
=> [routing] Turn generation fix. Removing segments duplicates

generator/osm2type.cpp
MAPSME-4288
Из highway=abandoned + abandoned:highway=path мы собирали highway-path. Здесь я устраняю такие случаи.
(вместо #6029)
=> [generator]  Prevent merging different tags into one type

generator/metalines_builder.cpp
Рома передал:
/home/rootuser/workspace/GitHubWatchdog/BUILD_MODE/debug/label/Linux/omim/generator/metalines_builder.cpp: At global scope:
/home/rootuser/workspace/GitHubWatchdog/BUILD_MODE/debug/label/Linux/omim/generator/metalines_builder.cpp:44:46: error: declaration of ‘const Ways& {anonymous}::LineString::Ways() const’ [-fpermissive]
Ways const & Ways() const { return m_ways; }
^
/home/rootuser/workspace/GitHubWatchdog/BUILD_MODE/debug/label/Linux/omim/generator/metalines_builder.cpp:22:34: error: changes meaning of ‘Ways’ from ‘using Ways = class std::vector<int>’ [-fpermissive]
using Ways = std::vector<int32_t>;
=> [generator] Fix build on linux, deduplicating names

drape_frontend/stylist.cpp, indexer/displacement_manager.hpp, indexer/feature_visibility.cpp, indexer/feature_visibility.hpp
MAPSME-4407
Гостиницы с рейтингом 8 должны вытеснять гостиницы с рейтингом 7, но не вытесняли. Оказалось, статическое вытеснение учитывало только тип объекта, но не дополнительные свойства. Теоретически это должно было ускорить индексацию.
Я добавил фильтрацию правил по селекторам на основе полной информации об объекте. Это замедлило сборку Москвы меньше, чем на два процента. Теперь гостиницы вытесняются в правильном порядке.
Основное изменение в коде — что `FilterRulesByRuntimeSelector` вынес из `drape_frontend` в `indexer`.
=> [indexer] Check for runtime selectors for static displacement

indexer/road_shields_parser.cpp
Когда в теге `ref` дороги и в тегах `network` и `ref` на отношении трассы, которое содержит эту дорогу, одинаковые шилды, они схлопываются в один. Очевидно. Но иногда для семантически одинаковых значений генерируются разные виды шилдов.
Этот PR правит ситуацию в Штатах, когда `ref=US:CA 91` не равнялся значениям с отношения `network=US:CA` + `ref=91`. Теперь там и там будут одинаковые белые шилды.
=> [shields] Deduplicate US State Highways shields

data/countries.txt
Перезаписал секцию метаданных о регионе в украинских mwm, чтобы убрать из них русский язык как официальный. Теперь при включенной русской локали на телефоне в Украине будут выводиться украинские названия. Раньше не выводились, да.
Заодно по просьбе из #6104 перенёс Киото в соседний регион. Пул-реквест на соответствующее изменение файла иерархии сделаю завтра.
Дифф такой конский, потому что в реквесте #6263 забыл убрать пробелы с концов строк.
=> [planet] Update region_meta for Ukraine and Kyoto region

android/src/com/mapswithme/maps/routing/RoutingController.java
@milchakov @rokuz PTAL
Теперь когда удаляется либо старт, либо финиш (при отсутствии промежуточных точек) мы сбрасываем routing controller в дефолтное состоянии и завершаем прогресс.
=> [android] Fixed removing the start or finish point

routing/routing_tests/subway_test.cpp, routing/subway_graph.cpp, routing/subway_graph.hpp, routing/subway_router.cpp, routing/subway_router.hpp
Это реализация GetNearestStation() по ней осталось:
1. сделать кэш, в котором для распаршенных фич хранить SubwayVertex-ы. Этот кэш будет переиспользован в  GetOutgoingEdgesList()
2. доработать тест SubwayGraphTest, чтоб проверять результаты GetNearestStation()
3. дописать еще несколько тестов на создание тестовых mwm-ок и последующий тест GetNearestStation()/GetOutgoingEdgesList() используя инфраструктуры теста SubwayGraphTest.
@dobriy-eeh PTAL
=> [routing] GetNearestStation implementation.

routing/subway_estimator.cpp
Сделал три минуты пенальти за смену линии в одной точке, без линии `subway_meta=change`.
=> [subway] Fix line-to-line interchange weight

routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/loaded_path_segment.hpp, routing/pedestrian_directions.cpp, routing/pedestrian_directions.hpp, routing/routing_helpers.cpp, routing/routing_helpers.hpp, routing/turns_generator.cpp, routing/turns_generator.hpp
Продолжение рефакторинга класса Routing + доработки по ревью https://github.com/mapsme/omim/pull/6371
Тема PR - подготовка к генерации сегментов при пешеходном роутинге.
@dobriy-eeh @ygorshenin @rokuz PTAL
=> [routing] Preparing for segment generation at pedestrian mode.

routing/routing_integration_tests/routing_test_tools.cpp
/Users/vladimirbykoyanko/src_github/omim/routing/routing_integration_tests/routing_test_tools.cpp:135:23: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
, m_indexRouter(move(CreateCarRouter(m_featuresFetcher->GetIndex(), *m_infoGetter,
^
/Users/vladimirbykoyanko/src_github/omim/routing/routing_integration_tests/routing_test_tools.cpp:135:23: note: remove std::move call here
, m_indexRouter(move(CreateCarRouter(m_featuresFetcher->GetIndex(), *m_infoGetter,
@dobriy-eeh @ygorshenin PTAL
=> [routing integration tests] Warning fix.

routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/directions_engine.cpp, routing/directions_engine.hpp, routing/index_road_graph.cpp, routing/index_router.cpp, routing/pedestrian_directions.cpp, routing/pedestrian_directions.hpp, routing/road_graph_router.cpp, routing/routing_helpers.cpp, routing/routing_helpers.hpp, routing/turns_generator.cpp, routing/turns_generator.hpp
Идея этого PR в том, чтоб удалить дубли в вычислении ETA, так же сделать еще одну важную вещь.
Чтоб в одной точке (ReconstructRoute()) установить классу Route вектор с SegmentInfo к моменту вызова ReconstructRoute() (или в нем) нужно посчитать ETA в сегменты маршрута (в дальнюю точку сегментов). 
В случае IndexGraph ETA считается с учетом пробок при помощи EdgeEstimator. В случае велосипедного и пешего при помощи особой CalculateMaxSpeedTimes(). (См. коммент в ней. Там поясняется зачем нужно брать максимальную скорость у графа.)
В результате рефакторинга ETA считается перед вызовом ReconstructRoute() двумя разными способами для IndexGraph и RoadGraph. Все остальные "dummy" расчеты удалены.
Следующей шаг - создание вектора из SegmentInfo и установка его для Route в ReconstructRoute(). …
=> [routing] Removing duplication of routing ETA calculation.

indexer/road_shields_parser.cpp
1. Исправлен баг, когда US:I не обрабатывалась в FindNetworkShield, так как было строгое неравенство;
2. Исправлен баг, когда, например, строка "I 710;US:I/I 710" генерировала интерстейт с текстом I 710, а не просто 710, что приводило к дублированию роад-шилда.
=> Fixed roads shield parsing in US

drape_frontend/read_metaline_task.cpp
У мира нет osm2ft, поэтому металинии фейлились, и генератор выпадал с `LCRITICAL`.
=> [metalines] Do not read metalines for the entire world

android/src/com/mapswithme/util/log/LoggerFactory.java
Changed the logs tag from "Core" to "MapsmeCore" for messages coming from C++/JNI code to simplify the reading and filtering logs. Updated the wiki page https://github.com/mapsme/omim/wiki/%5BAndroid%5D-How-to-get-log-output 
@ygorshenin @milchakov PTAL
=> [android] Changed core logs tag

routing/directions_engine.cpp, routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/road_graph.cpp, routing/road_graph.hpp
История:
В https://github.com/mapsme/omim/pull/6420 ломался ReconstructRoute при попытке собрать routeEdges косвенным способом (см. цикл в IDirectionsEngine::ReconstructPath)
Проблема в том, что Junction как узел графа неоднозначен, и при самопересечении маршрутов (а при промежуточных точках такое часто происходит) всё плохо.
Была сделана попытка починить. ReconstructRoute ломаться перестал.
Однако изменения привели к тому, что сломалось два интеграционных теста:
RestrictionTestNearMetroShodnenskaya
SwedenBarlangeRoundaboutTurnTest
В этом PR:
* Откатил неудачную попытку починить из https://github.com/mapsme/omim/pull/6420
* Починил ReconstructRoute другим способом: чтобы routeEdges заполнялись напрямую из сегментов.
=> [routing] Fix integration tests 

partners_api/taxi_base.cpp, partners_api/taxi_engine.cpp, partners_api/uber_api.cpp, partners_api/uber_api.hpp
Пофиксил креш, который возникал в случае, когда сетевые запросы к уберу были неудачными. Убер для каждого неудачного внутреннего запроса вызывал коллбэк с ошибкой, из-за этого, в TaxiEngine, счетчик, который декрементится на каждый ответ от таксишных апи, уходил в значение меньше нуля и срабатывал CHECK.
Еще пофиксил потенциальную проблему с определением доступности сервисов такси - пустой список стран считался всегда доступным. Сделал чтоб наоборот считался недоступным.
=> Taxi engine crash fix

android/jni/com/mapswithme/maps/Framework.cpp, drape_frontend/overlays_tracker.cpp, drape_frontend/overlays_tracker.hpp, iphone/Maps/UI/PlacePage/MWMPlacePageData.mm, local_ads/event.hpp, local_ads/local_ads_tests/file_helpers_tests.cpp, local_ads/statistics.cpp, local_ads/statistics.hpp, map/local_ads_manager.cpp, map/local_ads_manager.hpp
steady_clock::now при вызове time_since_epoch не возвращает правильное число заданных единиц
int64_t const d = std::chrono::duration_cast<std::chrono::seconds>(std::steady_clock::now().time_since_epoch()).count();
Результат: 63259
int64_t const d = std::chrono::duration_cast<std::chrono::seconds>(std::system_clock::now().time_since_epoch()).count();
Результат: 1499425462
Замечание: графический движок и библиотека local_ads имеет собственные using для Timestamp и Clock, чтобы ни один не зависел от другого.
=> Substitute steady_clock for system_clock in local ads

editor/editor_tests/osm_feature_matcher_test.cpp, editor/osm_feature_matcher.cpp
Возобновление https://github.com/mapsme/omim/pull/5994
Не мержить пока Саша не протестит на сборке из этой ветки.
https://jira.mail.ru/browse/MAPSME-4322
У зданий из примера есть подъезды, они отмечены точками в геометрии. Получается, что количество точек здания = точки контура + точки подъездов + возможно еще какие-то точки. У нас в приложении геометрия упрощается и точки с подъездами из геометрии удаляются. В итоге на зданиях из примера у нас находились пары только для половины точек осма, потому что в осмовских фичах 8 точек (4 контур и 4 подъезды), а у нас всего 4. Для наших точек совпадение полное (4 из 4). При поиске пар такие объекты сразу отбрасывались из-за маленького количества соответствий с осмовскими точками.
Подкрутил настройки мэтчинга, ослабил правила. Теперь сразу …
=> [editor] building matching fix

routing/async_router.cpp, routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/directions_engine.hpp, routing/pedestrian_directions.cpp, routing/pedestrian_directions.hpp, routing/routing_helpers.cpp
https://jira.mail.ru/browse/MAPSME-4914
Если во время генерации тернов нажать на отмену прокладки маршрута наше приложение падало. Причина была в том, что CHECK на корректность результатов генерации стоял перед проверкой, что генерация была отменена. Данный PR исправляет это.
Кроме того, данный PR добавляет в метод IDirectionsEngine::Generate() возвращаемый результат, который явно сообщает о том, сгенерированны ли терны.
Кроме того, выкинут некоторый теперь не нужный код (emptyPathWorkaround)
@rokuz @ygorshenin PTAL
=> [routing] Crash fix while turn generation cancellation

map/routing_manager.cpp, map/routing_manager.hpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5969d40bbe077a4dcc96f174
OnLocationUpdate вызывался у фреймворка на Андроиде до создания графического движка
=> Fixed crash on location update before drape engine creation

data/categories.txt
Fixed some typos and several entries which were translations of the
wrong English homonym.
Also added "Cash machine" as a (Brittish) English alias for ATM.
=> Fix various errors in sv translations

geometry/polyline2d.hpp, routing/base/followed_polyline.cpp, routing/base/followed_polyline.hpp, routing/routing_tests/followed_polyline_test.cpp, routing/routing_tests/route_tests.cpp
Данный PR решает следующие проблемы:
1. Корректный matching, в случае самопересекающихся маршрутов:
https://jira.mail.ru/browse/MAPSME-4944
2. Корректный matching, когда когда маршрут дважды и более проходит через одни и те же сегменты. Это возможно, при добавлении пром точки (точек)
https://jira.mail.ru/browse/MAPSME-5002
Кроме того данный PR улучшит ситуацию в https://jira.mail.ru/browse/MAPSME-4919.
Идея данного PR проста. При route matching теперь мы сначала пробуем заметчить текущую позицию на ближайшие два сегмента оставшейся (после предыдущего мачинга) части маршрута. Если не получается - значит перескок или покинули маршрут. Пробуем замечить на всю оставшуюся часть с маршрута. Если не получается, значит покинули маршрут.
@mpimenov @rokuz PTAL
Я планирую добавить юнит тест на …
=> Routing matching hopping case fix.

geometry/polyline2d.hpp, routing/base/followed_polyline.cpp, routing/base/followed_polyline.hpp, routing/route.cpp, routing/routing_tests/followed_polyline_test.cpp, routing/routing_tests/route_tests.cpp
cherry-pick https://github.com/mapsme/omim/pull/6642 на master.
Данный PR решает следующие проблемы:
Корректный matching, в случае самопересекающихся маршрутов:
https://jira.mail.ru/browse/MAPSME-4944
Корректный matching, когда когда маршрут дважды и более проходит через одни и те же сегменты. Это возможно, при добавлении пром точки (точек)
https://jira.mail.ru/browse/MAPSME-5002
Кроме того данный PR улучшит ситуацию в https://jira.mail.ru/browse/MAPSME-4919.
Идея данного PR проста. При route matching теперь мы сначала пробуем заметчить текущую позицию на ближайшие два сегмента оставшейся (после предыдущего мачинга) части маршрута. Если не получается - значит перескок или покинули маршрут. Пробуем замечить на всю оставшуюся часть с маршрута. Если не получается, значит покинули маршрут. …
=> Master route matching fix

generator/osm_translator.hpp, indexer/road_shields_parser.cpp
Игорь тут тестировал стиль на Болгарии, и мне резанули глаз дублирующиеся шилды разных цветов. Проблема была в том, что сначала мы из `ref` брали номер и в отсутствие правил для Болгарии красили номер в цвет по умолчанию. А затем получали номер из отношения, где правило уже было, и поэтому мы красили его в синий. Что получается, можете посмотреть на релизной сборке в Болгарии.
Здесь я удаляю шилд с цветом по умолчанию, если из отношения пришёл он же, но раскрашенный. Фикс надеюсь впихнуть в багфикс после релиза. Пока не мёржите.
Осталась проблема с Латвией, которую нужно решить либо правкой кода, либо правкой Латвии. [Жду ответа](https://lists.openstreetmap.org/pipermail/talk-lv/2017-July/005989.html) от латышских мапперов.
=> [shields] Remove duplicate shields of default style

geometry/point2d.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/index_graph_test.cpp
Выбор стартового сегмента с учетом направления движения.
Для решения проблемы https://jira.mail.ru/browse/MAPSME-4919 необходимо было реализовать два тикета. Один из них (https://jira.mail.ru/browse/MAPSME-4945) реализован в этом PR. 
Теперь при выборе дуги для старта маршрута мы ищем ближайший сегмент среди тех, что почти параллельны вектору движения пользователя. А если таких не находится, то среди всех. Под почти параллельными понимаются сегменты, которые отличаются от вектора движения не более чем на 14 градусов.
@dobriy-eeh @mpimenov PTAL
=> [routing] Taking into account vector of user moving for choosing the best start edge.

android/UnitTests/jni/mock.cpp, android/jni/com/mapswithme/core/logging.cpp, base/assert.hpp, base/base.cpp, drape/drape_tests/pointers_tests.cpp, iphone/Maps/Common/Statistics/fabric_logging.hpp, iphone/Maps/Common/Statistics/fabric_logging_ios.mm, iphone/Maps/main.mm
Исправлены две проблемы в Сrashlytics:
1. Все CHECK группировались в одну кучу. Теперь каждый CHECK будет группироваться по той строчке, в которой он случился.
2. В ios версии терялся текст сообщения, указанный в CHECK.
=> [base] Fix CHECK in fabric сrashlytics 

map/framework.cpp, map/framework.hpp, map/place_page_info.hpp
https://jira.mail.ru/browse/MAPSME-5095
В рамках задачи посмотрел сколько фич перебирается при поиске объекта с тегом viator. На Нью-Йорке заметил максимальное количество перебираемых фич - около 5000, на остальных городах значительно меньше - в среднем около 500. Поэтому решил сразу добавлять тег виатора в рамках этой задачи.
=> viator injection into world mwm

android/UnitTests/jni/mock.cpp, android/jni/com/mapswithme/core/logging.cpp, base/assert.hpp, base/base.cpp, drape/drape_tests/pointers_tests.cpp, iphone/Maps/Common/Statistics/fabric_logging.hpp, iphone/Maps/Common/Statistics/fabric_logging_ios.mm, iphone/Maps/main.mm
Cherry pick https://github.com/mapsme/omim/pull/6720
Исправлены две проблемы в Сrashlytics:
Все CHECK группировались в одну кучу. Теперь каждый CHECK будет группироваться по той строчке, в которой он случился.
В ios версии терялся текст сообщения, указанный в CHECK.
=> [base] Fix CHECK in fabric сrashlytics

generator/routing_index_generator.cpp, routing/CMakeLists.txt, routing/base/astar_algorithm.hpp, routing/base/astar_weight.hpp, routing/cross_mwm_connector.cpp, routing/cross_mwm_connector.hpp, routing/cross_mwm_osrm_graph.cpp, routing/cross_mwm_road_graph.hpp, routing/cross_mwm_router.cpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/road_graph.hpp, routing/road_graph_router.cpp, routing/route_weight.cpp, routing/route_weight.hpp, routing/routing.pro, routing/routing_algorithm.cpp, routing/routing_algorithm.hpp, routing/routing_tests/astar_algorithm_test.cpp, routing/routing_tests/astar_router_test.cpp, routing/routing_tests/cross_mwm_connector_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/segment.hpp, routing/world_graph.cpp, routing/world_graph.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
A* принимает вес как шаблонный параметр (отвязала от double), сделала SegmentWeight, который сейчас просто обёртка над double -- заготовка, в которую можно добавить другие компоненты и переписать оператор сравнения (буду делать отдельным пул реквестом). 
Этот коммит не меняет способ построения маршрута и суть весов, только подготавливает почву для дальнейших изменений.
=> Astar weight template

routing_common/car_model.cpp
https://jira.mail.ru/browse/MAPSME-4974
Необходимо добавить в карты (авто index graph) дороги с тагом route=ferry.
Предупреждая вопросы отмечу, что этот таг уже задал в pedestrian_model.cpp и в bicycle_model.cpp.
Вот пример места, где это актуально: http://www.openstreetmap.org/way/28418329#map=12/45.8466/-62.7066
@Zverik @dobriy-eeh @tatiana-kondakova PTAL
=> Adding tags route-ferry to the map.

routing_common/car_model.cpp
https://jira.mail.ru/browse/MAPSME-4947
Необходимо добавить в карты (авто index graph) дороги с тагом man_made=pier.
Предупреждая вопросы отмечу, что этот таг уже задал в pedestrian_model.cpp и в bicycle_model.cpp.
Вот пример места, где это актуально: http://www.openstreetmap.org/way/226633687
@Zverik @dobriy-eeh @tatiana-kondakova PTAL
=> Adding tags man_made=pier to the map.

android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java
When PP is already in full screen mode we shouldn't try to return it to details state during the dragging up
=> [android] Fixed opening behaviour in PP

android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java, android/src/com/mapswithme/util/Config.java, android/src/com/mapswithme/util/SharedPropertiesUtils.java, android/src/com/mapswithme/util/statistics/Statistics.java
[android] Core reads the 'StatisticsEnabled' setting from the settings.ini. And problem was that the mentioned setting wasn't stored in settings.ini because of write permission migh not be granted at that moment. Now, the setting is set to setting.ini safely, i.e. when all needed permissions are granted.
=> [android] Fixed the sending gps tracks

android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java, android/src/com/mapswithme/util/Config.java, android/src/com/mapswithme/util/SharedPropertiesUtils.java, android/src/com/mapswithme/util/statistics/Statistics.java
[android] Core reads the 'StatisticsEnabled' setting from the settings.ini. And problem was that the mentioned setting wasn't stored in settings.ini because of write permission migh not be granted at that moment. Now, the setting is set to setting.ini safely, i.e. when all needed permissions are granted.
https://jira.mail.ru/browse/MAPSME-5264
=> [cherry-pick] [android] Fixed the sending gps tracks

map/routing_manager.cpp, openlr/router.cpp, routing/index_router.cpp, routing/index_router.hpp, routing/nearest_edge_finder.cpp, routing/nearest_edge_finder.hpp, routing/road_graph.cpp, routing/road_graph.hpp, routing/road_graph_router.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/nearest_edge_finder_tests.cpp
Ранее в PR https://github.com/mapsme/omim/pull/6726 подобная работа была проделана для односторонних дорог.
Теперь при выборе дуги для старта маршрута мы ищем ближайший сегмент среди тех, что почти параллельны вектору движения пользователя. А если таких не находится, то среди всех. Под почти параллельными понимаются сегменты, которые отличаются от вектора движения не более чем на 14 градусов.
Более того, если стартовый сегмент выбирается из-за близости угла gps heading и вектора движения клиента, то в стартовой FakeVertex устанавливается ранее предусмотренный флаг m_strictForward в true. Это означает, что стартовый сегмент не допустит не медленного разворота (без оплаты штрафа в 2 минуты)
@dobriy-eeh @mpimenov @ygorshenin PTAL
=> [routing] Taking into account user gps heading for chosing start segment in case of two way roads.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/routing/RoutingController.java
[android] If route was saved but then the configuration change was come we should delete previously saved route, because in the next onCreate method call the obsolete route will be restored but it's a not case when we actually need to restore route.
https://jira.mail.ru/browse/MAPSME-5268
=> [android] Fixed restoring the state during configuration change

map/routing_manager.cpp, map/routing_manager.hpp, routing/CMakeLists.txt, routing/checkpoint_predictor.cpp, routing/checkpoint_predictor.hpp, routing/routing.pro, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/CMakeLists.txt, routing/routing_tests/checkpoint_predictor_test.cpp, routing/routing_tests/routing_tests.pro, xcode/routing/routing.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-5059
Предсказатель, куда пользователь хочет добавить промежуточную точку маршрута и тесты на него.
При добавлении промежуточной точки маршрута нужно выбрать для нее изначально место (потом пользователь сможет подвинуть ее). Если промежуточная точка одна, то возможно только одно место между старом и финишем. При добавлении второй промежуточной точки надо понять, куда ее поставить. Между стартом и ранее добавленной пром точкой или между ранее добавленной промточкой и финишем. При добавлении третий ситуация повторяется. Относительный порядок ранее добавленных пром точек должен быть сохранен.
В данном PR реализован следующий алгоритм. Пусть у нас есть вектор точек: старт, ранее добавленные пром точки, финиш. А так же новая пром точка. Мы последовательно …
=> [routing] Intermediate route point predictor.

routing/routing_session.cpp, routing/routing_session.hpp
https://jira.mail.ru/browse/MAPSME-5226
При перестроении маршрута в RebuildRouteOnTrafficUpdate не всегда нужно использовать текущее местоположение в качестве старта, а только в случае следования по маршруту (OnRoute) и в случае, если было обнаружено, что пользователь отклонился и требуется перестроение (RouteNeedRebuild). В остальных случаях перестраивать надо с той же начальной точкой, которая есть на текущий момент (для состояния RouteRebuilding точка уже обновлена, если это требуется, для остальных пользователю вероятно не надо перепрыгивать на текущую позицию).
При работе над багом также обнаружила, что RebuildRouteOnTrafficUpdate вызывается и вызывает RebuildRoute в треде, отличном от треда RoutingManager и при этом не берёт мьютекс, в результате чего могут возникнуть гонки данных …
=> MAPSME-5226 Fix route rebuild on traffic update

generator/generator_tests/osm_type_test.cpp
В MAPSME-4974 @bykoianko добавил route=ferry в разрешенные типы дорог. Поправила в тестах.
=> MAPSME-5344 Fix test: route = ferry is road type since MAPSME-4974

drape_frontend/backend_renderer.cpp, drape_frontend/message_subclasses.hpp, drape_frontend/read_manager.cpp, drape_frontend/read_manager.hpp
Когда мы меняем стиль карты, мы останавливаем потоки вычитки на BR, а затем перезагружаем текстуры. Новая версия кода гарантирует, что потоки вычитки успеют завершиться до перезагрузки текстуры. Иначе возможно чтение из неинициализированной текстуры символов и крэш.
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/5972703dbe077a4dccee1669/sessions/latest?build=62182939
=> Fixed crash on switching map style

drape_frontend/shaders/area3d.vsh.glsl, drape_frontend/shaders/path_symbol.vsh.glsl, drape_frontend/shaders/position_accuracy3d.vsh.glsl, drape_frontend/shaders/route.vsh.glsl, drape_frontend/shaders/route_arrow.vsh.glsl, drape_frontend/shaders/shaders_lib.glsl, drape_frontend/shaders/traffic.vsh.glsl
На некоторых Андроидах нормализация нулевого вектора в шейдерах приводила к сильным артефактам. Здесь добавлена проверка на равенство нулю нормализуемых векторов во всех шейдерах, где это необходимо.
https://jira.mail.ru/browse/MAPSME-3341
https://jira.mail.ru/browse/MAPSME-5179
=> Fixed UB on normalization zero vectors on some Android devices

data/editor.config, editor/editor_config.cpp, generator/osm2meta.cpp, generator/osm2meta.hpp, indexer/editable_map_object.cpp, indexer/editable_map_object.hpp, indexer/feature_meta.cpp, indexer/feature_meta.hpp, indexer/map_object.cpp, indexer/map_object.hpp
Добавил поддержку атрибута level. Это этаж, на котором находится POI. Полезно в торговых центрах.
Их примерно 400 тысяч на планете, каждый имеет длину в среднем 2 символа, так что данные вырастут не заметно. Добавил методы для поддержки в редакторе, осталось только платформу поправить.
Тип поля — double: могут быть дробные этажи. Возможно, в редакторе мы не дадим возможность вводить дробные числа, но отображать их нужно.
=> [generator] Add level metadata field and methods for the editor

storage/diff_scheme/diff_scheme_checker.cpp
Проблема: при сборке gcc на linux получаем ошибку:
<tt>/home/ilya.zverev/omim/storage/diff_scheme/diff_scheme_checker.cpp:53:13: error: converting to ‘diff_scheme::NameFileInfoMap {aka std::unordered_map<std::basic_string<char>, diff_scheme::FileInfo>}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, Tp, Hash, Pred, Alloc>::unordered_map(std::unordered_map<_Key, Tp, Hash, Pred, Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with Key = std::basic_string<char>; Tp = diff_scheme::FileInfo; Hash = std::hash<std::basic_string<char> >; Pred = std::equal_to<std::basic_string<char> >; Alloc = std::allocator<std::pair<const std::basic_string<char>, diff_scheme::FileInfo> >; std::unordered_map<_Key, Tp, Hash, Pred, Alloc>::size_type = long …
=> [storage] Fix build on gcc

routing/base/followed_polyline.cpp, routing/base/followed_polyline.hpp, routing/route.hpp, routing/routing_session.cpp
Неправильно работало ведение по маршруту с промежуточными точками: FollowedPolyline не знал о промежуточных точках и при отклонении или самопересечениях маршрута матчил не на Subroute, ведущий к следующей промежуточной точке. Добавила в FollowedPolyline информацию о том, какая точка следующая и учёт этого в матчинге.
=> MAPSME-5233, MAPSME-5002, MAPSME-5234 fix following route with intermediate points

routing/route.hpp
MAPSME-5367
http://angola.mapsme.mail.msk:8080/job/GitHubWatchdog/BUILD_MODE=release,label=WD_Mac/lastCompletedBuild/testReport/(root)/routing_tests/route_tests_cpp_DistanceToCurrentTurnTest/
сломала, когда делала роутинг с промежуточными точками.
Суть поломки -- был добавлен ASSERT, который проверяет, что в Route `m_subrouteAttrs.size() > m_currentSubrouteIdx`.
Но сейчас объекты Route могут и не удовлетворять этому условию -- в сконструированном по умолчанию объекте `m_subrouteAttrs.size() ==0` и `m_currentSubrouteIdx == 0` и нет данных чтобы их корректно проинициализировать.
Сейчас методы, которые могут работать с саброутами, вызываются при не установленной информации о саброутах только в тестах. Но в целом интерфейс класса Route позволяет при отсутствии промежуточных точек не вызывать …
=> MAPSME-5367 fix route tests: allow empty m_subrouteAttrs for routes without intermediate points

drape_frontend/CMakeLists.txt, drape_frontend/drape_api.cpp, drape_frontend/drape_api.hpp, drape_frontend/drape_engine.hpp, drape_frontend/drape_engine_safe_ptr.hpp, drape_frontend/drape_frontend.pro, map/framework.cpp, map/local_ads_manager.cpp, map/local_ads_manager.hpp, map/routing_manager.cpp, map/routing_manager.hpp, map/traffic_manager.cpp, map/traffic_manager.hpp, xcode/drape_frontend/drape_frontend.xcodeproj/project.pbxproj
Добавлена потокобезопасная обертка над графическим движком, которую надо использовать, если указатель на движок хранится и используется вне фреймворка.
Должна также исправить эти крэши при выходе из приложения https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/5971a8cdbe077a4dcce512bb?time=last-seven-days
=> Added drape engine safe ptr

generator/routing_index_generator.cpp, routing/cross_mwm_graph.cpp, routing/cross_mwm_graph.hpp, routing/cross_mwm_index_graph.hpp, routing/index_router.cpp
Переделала реквест после информации от Тимура: план в том, чтобы для пешего и вело-роутинга не использовать leaps, т.к. пешие и вело маршруты, даже если они проходят через несколько mwm, не очень большие, а увеличивать размер cross-mwm секции и время генерации mwm не хочется.
=> MAPSME-5318 fix pedestrian and bicycle cross-mwm routing

android/jni/com/mapswithme/maps/Framework.cpp, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm, platform/location.hpp, routing/routing_session.cpp
Не отображаем название следующей улицы, пока мы далеко от поворота. Чтобы не путать смыслы ,сделала отдельное поле под название отображаемой улицы.
Поведение обсуждалось с Артёмом и Игорем -- начинаем отображать название следующей улицы тогда же когда информацию о полосах.
=> MAPSME-4897 Do not display the next street name when we are far from turn

indexer/altitude_loader.cpp, indexer/altitude_loader.hpp, routing/features_road_graph.cpp, routing/features_road_graph.hpp, routing/geometry.cpp
AltitudeLoader holds a FileReader of the altitudes section.
This reader, being a caching one, is not thread safe. However,
AltitudeLoader did not keep the MwmHandle from which it was
supposed to construct its reader, so the reader could be reused
(via MwmValue via MwmHandle) by another thread.
FeaturesRoadGraph tries to avoid this issue by keeping its
own cache of MwmHandles but it did not stop RoadGeometry
from bypassing this cache when creating its AltitudeLoader.
The question of whether we need to fix this other cache
and whether we need it at all is out of the scope of this CL.
https://jira.mail.ru/browse/MAPSME-5407
=> [routing] Fixed a data race in AltitudeLoader.

map/routing_manager.cpp, map/routing_manager.hpp, routing/index_graph_loader.cpp, routing/index_graph_loader.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing_integration_tests/routing_test_tools.cpp
Раньше грузим ли мы высоты определялось в IndexGraphLoaderImpl в зависимости от типа транспорта, в случае если не грузим всем точкам выставлялась дефолтная высота, если должны грузить, но потерпели неудачу -- kInvalidAltitude.
Это нормальное поведение, но оно не позволяет определить наличие загруженных высот на уровнях выше, чем IndexGraphLoaderImpl (либо надо дублировать условия выбора по типу транспорта, что плохо).
Поэтому перенесла определение необходимости загрузки высот выше -- на уровень RoutingManager, это минимальный предок для загрузки высот в роутинге и определения необходимости отображения графика.
=> MAPSME-5425: do not show altitudes for auto & taxi

data/categories.txt
Это часто используемая аббревиатура, как я понял. См. https://www.sendai-airport.co.jp/en/service/aed/
=> [types] Add AED as a synonym to defibrillator

generator/osm_translator.hpp
«ЦАО» на дороге в центре Москвы. 83124 на улицах немецких городов (это индекс). Автоматическое копирование тега `ref` с любых отношений на отрезки дорог в этих отношениях немного портит нам карту. Мы уже правильно копируем номера дорог с отношений `route=road`, теперь давайте запретим использование `ref` с других отношений.
=> [generator] Do not copy ref tags from boundaries and other relations

routing/index_road_graph.cpp, routing/routing_integration_tests/osrm_route_test.cpp
Исправление ASSERT в BicycleDirectionsEngine::GetUniNodeIdAndAdjacentEdges().
Проблема была в том, что при получении исходящих дуг из стартовой дуги маршрута координаты начала одной из исходящих дуг считались не верно. ASSERT стрелял в том случае, если старт попадал на двустороннюю фичу, и маршрут шел против точек это фичи.
При этом координата старта дуги исходящей из стартовой дуги и совпадающей с ней по геометрии, но противоположенная по направлению имела смещенную точку старта в начало маршрута (см. метод IndexRoadGraph::GetJunction). На этом и срабатывал ASSER на не совпадение точек. Аналогичная проблема была и при задании финиша.
@mpimenov @igrechuhin @rokuz @tatiana-kondakova PTAL
=> [routing] Bicycle turn generation ASSERT fix.

android/src/com/mapswithme/util/ThemeSwitcher.java
https://jira.mail.ru/browse/MAPSME-5327
При переключении темы на карте разрушения контекста OpenGL не происходит, так как isChangingConfigurations возвращает true. 
Кроме того, в классе ThemeSwitcher.java при смене темы карты ( if (!newTheme.equals(oldTheme)) ) зовется nativeMarkMapStyle.
Это в данной ситуации неправильно. Вероятно, надо звать код, похожий на этот
if (sRendererActive)
Framework.nativeSetMapStyle(style);
else
Framework.nativeMarkMapStyle(style);
=> [Android] Fixed theme switching on the map

android/src/com/mapswithme/maps/MapFragment.java
https://jira.mail.ru/browse/MAPSME-5508
Суть фикса в переносе подписки на колбэки серфейса в метод onStart из onResume. Так onResume это слишком поздно было и поэтому пропускался колбэк surfaceCreated в определенных кейсах.
=> [android] Fixed subscription on surface calbacks

routing/routing_integration_tests/bicycle_route_test.cpp
Исправил один из routing_integration_tests. 
По сути этот тест ранее проверял, что если ближайшая дорога имеет таг bicycle=no, то маршрут не прокладывается. Теперь он проверяет, что если ближайшая дорога имеет таг bicycle=no, то маршрут прокладывается от ближайшей дороги, которая подходит для велосипедов.
@mpimenov, @tatiana-kondakova PTAL
=> [routing] NetherlandsAmsterdamBicycleNo routing integration test fix.

android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
[android] Made storage callback detachable to handle update status/progress correctly, i.e. don't miss update status while app in background, and avoid memory leaks
[android] Fixed discarding the 'ToDoafterUpdate' status during screen rotation
https://jira.mail.ru/browse/MAPSME-5538
=> [android] Added 3g warning handling before doing update maps on 3g

routing/road_graph.cpp, routing/road_graph.hpp, routing/routing_integration_tests/CMakeLists.txt, routing/routing_integration_tests/road_graph_tests.cpp, routing/routing_integration_tests/routing_integration_tests.pro, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/routing_test_tools.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
После увеличения числа дуг кандидатов для начала и конца маршрута с 10 до 20 на одной точке произошел комбинаторный взрыв кол-ва файковых дуг (в IRoadGraph::m_fakeIngoingEdges и IRoadGraph::m_fakeOutgoingEdges). Это приводило к не приемлемому потреблению памяти при матчинге дуг.
Точка на которой воспроизвелась проблема: http://www.openstreetmap.org/#map=19/50.73197/-1.21295
Кроме, того данный PR включает не большой рефакторинг. Вектора в IRoadGraph::m_fakeIngoingEdges и IRoadGraph::m_fakeOutgoingEdges теперь сортированные.
@ygorshenin @mgsergio PTAL
=> [release-75] Memory consumption while jam matching fix

android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java, platform/http_request.cpp
https://jira.mail.ru/browse/MAPSME-5584
@VladiMihaylenko Просьба протестировать на ветке **MAPSME-5584-crash-in-downloader** (она есть в upstream) как работает IOs , кейсы о которых сегодня много раз говорили. Если там все ок, то потом замержем этот PR. (P.S. мы хотели сами, но не смогли добиться чтобы воцнью с update диалогом показался)
=> [android] Fixed crash while terminating any chunk during downloading mwm

routing/index_router.cpp, routing/routing_consistency_tests/routing_consistency_tests.cpp, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_integration_tests/get_altitude_test.cpp, routing/routing_integration_tests/online_cross_tests.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/routing_test_tools.hpp, routing/routing_integration_tests/street_names_test.cpp, routing/routing_integration_tests/turn_test.cpp
Данный PR исправляет ряд моментов упущенных после перевода пешей и вело навигации на IndexGraph.
- игнорируется направление односторонних дорог при пешей навигации;
- интеграционные тесты тесты на пешей и вело роутинг теперь работают по IndexGraph. (Они не были переведены);
- сделан тест и поправлен код, чтоб были допустимы маршруты, у которых старт и финиш совпадают;
- проведен рефакторинг в интеграционных тестах;
=> [routing] Routing integration tests and ignoring direction at pedestrian routing

routing/CMakeLists.txt, routing/bicycle_directions.cpp, routing/fake_edges_container.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing.pro, routing/routing_tests/applying_traffic_test.cpp, routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp, routing/routing_tests/road_access_test.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
Добавила в IndexGraphStarter структуры для хранения фейковых графов. В данный момент хранятся только фейковые старт/финиш, фейковые ребра от старта/финиша до ближайшего сегмента и фейковые куски реальных сегментов, но структуры позволяют в дальнейшем добавить туда проекции на несколько реальных сегментов (и использовать это в A* для поиска лучшего пути), а также более сложные конфигурации дуг для обхода препятствий.
Поскольку необходимо уметь собирать саброуты в единый маршрут, в котором будет информация обо всех фейковых дугах из саброутов, у IndexGraphStarter есть конструктор, принимающий на вход vector<IndexGraphStarter> и объединяющий их.
Также необходимо сохранять информацию о фейковых дугах (в том числе, достроенных для промежуточных точек) для последюущего использования в …
=> Add fake route endings to IndexGraphStarter

routing/index_router.cpp
cherry-pick коммита с мастера, который исправляет ошибку в переводе пешеходного роутинга на index graph. Сейчас в release-75 мы прокладываем пешеходные маршруты по направлению oneway featch. Без возможности ехать против их движения. Данный PR исправляет эту ошибку.
=> [release] Ignoring one way feature direction for pedestrian routing.

routing/fake_edges_container.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp
Значение, возвращаемое из GetNumFakeSegments, далее используется в конструкторе IndexGraphStarter как id следующего сегмента, оно не должно превышать `numeric_limits<uint32_t>::max()` -- это максимальное количество фейковых сегментов, т.к. id сегмента имеет тип uint32_t.
=> Fix implicit conversion warning

routing/routing_tests/index_graph_tools.cpp
При ожидаемом результате `Result::NoPath` не проверялось соответствие `resultCode`, возвращенного из `CalculateRoute`, ожидаемому результату (тест не фейлился, если ожидается `Result::NoPath`, а маршрут нашёлся).
=> fix TestRouteGeometry: check CalculateRoute return value even we expect Result::NoPath

routing/index_graph_starter.cpp
MAPSME-5630: направление сегмента учитывалось дважды: GetJunction уже учитывает IsForward.
=> Fix fake PartOfReal ends for backward segments

generator/routing_index_generator.cpp, routing/CMakeLists.txt, routing/base/astar_algorithm.hpp, routing/base/routing_result.hpp, routing/cross_mwm_connector.cpp, routing/cross_mwm_connector.hpp, routing/cross_mwm_osrm_graph.cpp, routing/cross_mwm_router.cpp, routing/geometry.hpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/road_graph_router.cpp, routing/route_weight.cpp, routing/route_weight.hpp, routing/routing.pro, routing/routing_algorithm.cpp, routing/routing_algorithm.hpp, routing/routing_tests/astar_algorithm_test.cpp, routing/routing_tests/astar_router_test.cpp, routing/routing_tests/cross_mwm_connector_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp, routing/world_graph.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
Добавила в многокомпонетнтный RouteWeight компонент, отвечающий за количество пересечений границы транзитной и нетранзитной зоны, добавила штраф за пересечение нетранзитной зоны в IndexRouter, добавила в IndexGraphStarter метод, проверяющий допустимость маршрута исходя из количества пересечений границы транзит/нетранзит и положения старта и финиша.
Cross-mwm вес был смесью RouteWeight и double, оставила double, так как этот вес не может иметь в себе никаких пересечений нетранзитных зон, шлагбаумов и т.п. (если были пересечения нетранзитных зон, то это CrossMwmConnector::kNoRoute).
=> Do not use non-transit features for transit

tools/autobuild/detect_qmake.sh
Brew installs qt with specific version in /usr/local/opt/qt@5.?/ 
This path is not specified in detect_qmake.sh, that causes problem with building project.
=> Fix qmake directory detection for brew package installer on MacOSX.

routing/index_graph_starter.cpp
https://github.com/mapsme/omim/pull/7125
=> Cherry-pick [Fix onesegment routes for case start segment is reverse of finish segment] from release-75

routing/CMakeLists.txt, routing/index_router.cpp, routing/index_router.hpp, routing/routing.pro, routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/world_graph.cpp, routing/world_graph.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
В рамках создания TransitWorldGraph с поддержкой общественного транспорта превращаю WorldGraph в абстрактный базовый класс, переношу текущую реализацию в SingleVehicleWorldGraph.
Также убрала из интерфейса метод GetIndexGraph, заменила на Mode::SingleMwm.
=> Convert WorldGraph into base class

coding/coding_tests/CMakeLists.txt, coding/coding_tests/coding_tests.pro
Without this change it's not possible to run csv reader tests, because they use platform, and platform is not properly initialized.
=> [coding] Init platform for coding tests.

routing/index_graph_starter.cpp, routing/routing_tests/index_graph_test.cpp
При поиске входящих/исходящих для фейкового сегмента типа PartOfReal добавляла к фейковым рёбрам входящие/исходящие для соответствующего реального сегмента.
Это было неправильно, поскольку в случае
```
a   b        c      d
*===>------->*----->*
```
где ac, cd -- реальные сегменты, ab -- сегмент типа PartOfReal при получении исходящих из ab в этот список добавлялся cd с весом cd (кусок bc получался как бы нулевым), что приводило к нарушению инварианта на некоторых маршрутах (в основном очень коротких, длиной меньше 20м).
Сейчас при поиске входящих/исходящих из фейкового сегмента добавляю входящие/исходящие для соответствующего реального только если `(isOutgoing && haveSameFront) || (!isOutgoing && haveSameBack)`.
Добавила тест, который ломался до фикса и не ломается теперь.
Надеюсь …
=> MAPSME-5690: Fix GetEdgeList for fake segments

routing/CMakeLists.txt, routing/routing.pro, routing/single_vehicle_world_graph.cpp, routing/transit_graph.hpp, routing/transit_graph_loader.cpp, routing/transit_graph_loader.hpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Заготовки для TransitWorldGraph.
TransitGraph -- граф общественного транспорта, будет содержать FakeGraph (сделаю, когда https://github.com/mapsme/omim/pull/7160 вольется в мастер) и мэпинг фейковых сегментов на информацию для отрисовки (id полилинии и т.п.)
TransitGraphLoader -- Loader для TransitGraph с кешем, для полной реализации нужен будет десериалайзер, будет сделан после добавления информации в генератор (@bykoianko сейчас работает над этим)
TransitWorldGraph -- совмещенный WorldGraph для пешеходов и общественного транспорта, будет использоваться из IndexRouter при типе транспорта Transit.
=> Add dummy TransitGraph, TransitGraphLoader, TransitWorldGraph classes.

generator/transit_generator.cpp, routing_common/transit_types.hpp
При сериализации/десериализции секции transit возникает ситуация, при которой поле одной из структур данных должно быть заполнено не из исходного json, а вычислено после десериализации из json, но перед сериализацией в mwm. Затем, при работе программы оно должно десериализоваться из mwm и использоваться.
@tatiana-kondakova @ygorshenin @mpimenov PTAL
=> Special handling for pedestrian feature ids.

data/categories.txt
Чтобы второй строчкой выводилось не `sponsored-thor`, а человеческое описание. Нам нужен только русский язык, т.к. точки только в Москве и Петербурге.
=> [types] Category translation for Thor items

routing/CMakeLists.txt, routing/fake_ending.cpp, routing/fake_ending.hpp, routing/fake_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/routing.pro, routing/routing_tests/applying_traffic_test.cpp, routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp, routing/transit_graph.cpp, routing/transit_graph.hpp, routing/transit_graph_loader.cpp, routing/transit_graph_loader.hpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
1. FakeEnding переехал в отдельный файл, в него добавилась дополнительная информация (координаты начала и конец сегмента, на который делается проекция, признак однонаправленности), чтобы можно было использовать для построения проекций там, где не доступен IndexGraph.
2. В FakeGraph добавлен метод AddConnection, который соединяет существующие вершины.
3. В TransitGraphLoader добавлены вызовы десериалайзера для чтения данных из секции transit. Чтобы соединить граф транспорта с пешеходными сегментами также понадобилось протащить туда IndexGraph для чтения геометрии.
4. В TransitGraph добавлен метод Fill, который заполняет граф на основании информации из секции transit и вспомогательные методы. Все основные изменения здесь.
Изменения в InexRouter и тестах -- только переезд FakeEnding из …
=> TransitGraphLoader implementation

generator/generator_tests/transit_test.cpp, routing/transit_graph.cpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp, tools/python/transit/transit_graph_generator.py
В класс Edge (массив json "edges") поля назывались не очень удачно: start_stop_id и finish_stop_id. В то время, как в классе Shape (массив json "edges") поля с похожим значением называются: stop1_id и stop2_id. Теперь, все приведено к единообразию и называется одинаково. Как в Shape. 
Документацию так же обновил: https://confluence.mail.ru/display/MAPSME/Subway+Data+Preparation
@rokuz @darina @tatiana-kondakova PTAL
=> Renaming start_stop_id to stop1_id and finish_stop_id to stop2_id at transit json.

routing/transit_graph.cpp
После того как в transit был смержен пул-реквест https://github.com/mapsme/omim/pull/7240 merge , включаю использование сохраненной в рамках него информации о ближайшем пешеходном сегменте в TransitGraph.
=> Use nearest pedestrian segment stored in mwm for transit to real mapping

routing/transit_graph.cpp
Договорились, что в дальнейшем у нас всегда будут веса для edges и gates в mwm.
=> Сheck edges and gates have valid weights while filling TransitGraph.

routing/transit_graph.cpp, routing/transit_graph.hpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
Мелкий рефакторинг: избавилась от TransitGraph::m_edgeToSegment и от transit::Edge::operator<, который был плох.
=> Getting rid of TransitGraph::m_edgeToSegment and transit::Edge::operator<

generator/transit_generator.cpp, routing/index_router.cpp, routing_common/CMakeLists.txt, routing_common/routing_common.pro, routing_common/transit_max_speed.hpp, routing_common/transit_speed_limits.hpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp, xcode/routing_common/routing_common.xcodeproj/project.pbxproj
Данный PR решает две задачи:
1. проверка на валидность структур для хранения общественного транспорта перед сериализацией;
2. временный код, по созданию корректных весов для transit::Edge. Позже, когда эти данные будут приходить json-ах описывающих граф общественного транспорта данный код будет заменен на чеки на валидность весов при генерации mwm.
@tatiana-kondakova @darina @ygorshenin PTAL
=> Transit data structure validity and calculation edge weights.

tools/python/transit/transit_graph_generator.py
Из-за сложностей с чтением uint64_t из json с @bykoianko было решено тип osm_id хранить в виде строки, а у id остановки зарезервировать старший бит (теперь под id обычной остановки отводится 62 бита, и для признака пересадочного узла используется 63-й).
=> Types of osm_id and stop_id updated in transit graph.

generator/feature_sorter.cpp
Для генерации площадных городов для геокодера нужно сопоставлять osm id и feature id. Не очень понял, почему на этапе сборки фич не скидывать сразу feature id, но ладно.
=> [generator] Create osm2ft files for the whole planet also

generator/generator_tests/transit_test.cpp, generator/generator_tool/generator_tool.cpp, generator/transit_generator.cpp, generator/transit_generator.hpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_serdes.hpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
Данный PR решает следующие задачи:
1. обработка osm id представленных в виде строк. Это было необходимо сделать, поскольку osm id требуют uint64_t, а json парсер поддерживает для целого типа только long long (не менее, чем int64_t);
2. конвертация из osm id в feature id. Это реализовано для фичь (обычно, но не всегда точечных), представляющих выходы и остановки;
@ygorshenin @darina @tatiana-kondakova PTAL
=> [transit] Conversion osm id to feature id.

routing/transit_info.hpp
Небольшие улучшения к https://github.com/mapsme/omim/pull/7323
в соответствии с комментариями от @darina которые то ли были сразу после мержа то ли при мерже не были замечены.
=> TransitInfo minor improvements: ASSERT for edge type

generator/generator_tests/transit_test.cpp, generator/transit_generator.cpp, generator/transit_generator.hpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
Идея PR в том, что shape id (локальный для mwm) заменяется на пару stop id начала - stop id конца. Данный новый id (пара) будет глобальный среди всех shape во всех mwm.
Гарантируется, что пара остановок (stops) может быть соединена не не более чем одним shape. Это означает, что пара stops однозначно идентифицирует shape.
Кроме того, после данного изменения мы получим все id в transit глобальными. Что будет удобно при разрезании графа общественного транспорта по mwm и при размещении разных графов в одной mwm.
@darina @tatiana-kondakova @ygorshenin PTAL
=> [transit] Getting rid of local shape id.

data/categories.txt
Чтобы люди не видели загадочное `sponsored-halloween` при нажатии на тыкву, указываем надписи в переводе типа. Целевая аудитория — англоговорящие люди, поэтому русскую надпись почти никто не увидит.
=> [types] Strings for the halloween type

generator/generator_tests/transit_test.cpp, generator/generator_tool/generator_tool.cpp, generator/transit_generator.cpp, generator/transit_generator.hpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_serdes.hpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
Подготовка к вырезанию графов общественного транспорта по границам mwm. 
Данный PR:
- изменяет способ передачи путей к данным в BuildTransit(), чтоб было проще потом получить доступ к data/border/*.poly файлам;
- обеспечивает сохранение в mwm для линии (lines) нескольких диапазонов остановок. Это может случится, в случае, если линия несколько раз пересекает границу mwm. Более подробно - см описание плана работ по вырезанию графа(ов) общественного транспорта по границам mwm: https://jira.mail.ru/browse/MAPSME-5858
@ygorshenin @darina PTAL
=> Cutting transit graphs according to mwms. Preparation.

generator/search_index_builder.cpp, indexer/search_string_utils.cpp, indexer/search_string_utils.hpp, iphone/Maps/UI/PlacePage/PlacePageLayout/Content/BookingCells/MWMPPReviewCell.mm, search/CMakeLists.txt, search/common.hpp, search/geocoder.hpp, search/highlighting.cpp, search/highlighting.hpp, search/intermediate_result.cpp, search/intermediate_result.hpp, search/pre_ranker.cpp, search/pre_ranker.hpp, search/processor.cpp, search/processor.hpp, search/ranker.cpp, search/ranker.hpp, search/result.hpp, search/search.pro, search/search_integration_tests/pre_ranker_test.cpp, search/search_quality/search_quality_tool/search_quality_tool.cpp, search/search_tests/CMakeLists.txt, search/search_tests/highlighting_tests.cpp, search/search_tests/search_tests.pro, search/suggest.cpp, search/suggest.hpp, search/utils.hpp, xcode/search/search.xcodeproj/project.pbxproj
- Factored out assigning the highlight ranges.
- Moved several Ranker's methods to the private section.
- Renamed PreResult1 to PreRankerResult and PreResult2 to RankerResult.
- Moved result comparators closer to their call sites (changing them to lambdas).
- Removed IndexedValue.
- Moved KeywordsScorer from Ranker to Processor.
- Added a type alias for query tokens.
=> [search] A refactoring of ranker.

generator/generator_tests/transit_test.cpp, generator/transit_generator.cpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_serdes.hpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
Идея данного PR в том, что необходимо хранить глобальные идентификаторы gates. Это связано с тем, что на границах mwm, иногда gates могут быть продублированны (подробнее https://jira.mail.ru/browse/MAPSME-5858). И чтоб при отрисовке не рисовать gates дважды нужно их идентифицировать.
У gates в json есть osm id и только один. Его и предполагается использовать, как глобальный id гейта.
В данном PR, в FeatureIdentifiers я сделал 2 режима. Сохранять только feature id (используется в Stops) и сохранять osm id и feature id (используется в Gates).
Как вариант, можно сделать еще один класс, похожий на FeatureIdentifiers, но который сохраняет не только feature id, но и osm id, но в таком варианте получается много copy paste.
Вариант, добавить в Gate поля в виде osm id и feature id и заполнять …
=> [transit] Keeping osm id with gates as gate id.

generator/generator_tests/transit_test.cpp, generator/transit_generator.cpp, generator/transit_generator.hpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
Идея данного PR:
1. Обход json-на с графом общественного транспорта определяется классами в transit_generator.hpp. Ранее, если требовалось распарсить json dictionary (как ShapeId или Colors), то в DeserializerFromJson добавлялся специальный operator() для того, чтоб распарсить соответствующий json dictionary. Теперь реализовано обобщенное решение. Если при обходе встречается класс, то проверяется, соответствует ли ему json dict и если да, то это учитывается и далее используется стандартный обход. (commint "
Any class from transit types may be present as json dictionary (object).")
2. EDITED. Добавлен цвет линий в Line. 
@darina @ygorshenin PTAL
=> [transit] Colors type. DeserializerFromJson refactoring.

generator/transit_generator.cpp, routing/transit_graph_loader.cpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_serdes.hpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
@tatiana-kondakova нашла баг при сохранении хедера секции transit. 
В начале секции place holder заголовока сохранялся сериалайзером с использованием varint, а затем он перезаписывался после создания секции.
Данный PR исправляет этот баг. Добавлен Serializer/Deserializer для хедера. Я так же добавил тест, на перезапись хедера.
@tatiana-kondakova @ygorshenin @darina PTAL
=> [transit] Serializing/deserializing header with fix number size.

routing/routing_tests/applying_traffic_test.cpp, routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp
Сделала функции, которые создают FakeEnding и IndexGraphStarter для тестов с популярными параметрами, чтобы уменьшить дублирование кода.
https://github.com/mapsme/omim/pull/7248#pullrequestreview-69002063
=> MAPSME-5761: Remove code duplication in routing_tests

routing/transit_graph.cpp, routing/transit_graph.hpp, routing/transit_graph_loader.cpp
Добавила штраф за пересадку на другой line, пока с заглушкой на месте, где появится line.GetTransferPenalty() после того как соответсвующее поле и метод будут добавлены transit::Line.
=> Add penalty for transit lines transfer

generator/generator_tests/transit_test.cpp, generator/transit_generator.cpp, generator/transit_generator.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing_exceptions.hpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
Данный PR обеспечивает при сборке mwm функциональность по перебору всех .transit.json с графами общественного транспорта, вырезанию их по границе обрабатываемой mwm согласно правилам из https://jira.mail.ru/browse/MAPSME-5858, и сохранению в mwm секцию.
PR уже прошу смотреть, однако в нем пока кое что не реализовано:
1. Сами правила по вырезанию графов обществного транспорта в методе GraphData::ClipGraphByMwm();
2. Использование visitors для ряда методов в GraphData;
3. Тесты на методы класса GraphData и на метод DeserializeFromJson;
Данные доработки будут добавлены в данный PR отдельными коммитами.
@ygorshenin @tatiana-kondakova PTAL
=> Cutting transit graphs according to mwm.

drape/oglcontextfactory.cpp, drape/oglcontextfactory.hpp, drape_frontend/backend_renderer.cpp, drape_frontend/frontend_renderer.cpp, iphone/Maps/Classes/iosOGLContextFactory.h, iphone/Maps/Classes/iosOGLContextFactory.mm
Есть 3 потока: **A**, **B**, **C**. **A** вызывает _setPresentAvailable_, **B** и **С** вызывают _waitForInitialization_. Задача: не позволить потокам **B** и **С** продолжиться, пока не завершится выполнение метода _setPresentAvailable_ на потоке **A**, а потоки **B** и **С** не окажутся в одной точке (внутри метода _waitForInitialization_).
=> [iOS] Fixed OGL context initiailization race

android/build.gradle
https://jira.mail.ru/browse/MAPSME-5921
Добавил возможность передачи следующих параметров:
1. arm или x86 , например, команда **gradlew rWD -Parm** - должна собрать (web debug) армовскую сборку. Аналогично, если указан параметр x86 - то x86. Если ни один параметр не указан, то сборка должна собраться под две платформы universal, но на ней этого написано не будет.
2. splitApk (будет нужен в основном @burivuh ), например, команда gradlew rWD **-PsplitApk** - должна собрать апк для x86 и arm + одну universal сборку.
=> [android] Added ability to build android apk for a specific arch

routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/pedestrian_directions.cpp, routing/road_graph.cpp, routing/road_graph.hpp, routing/transit_info.hpp
В реквесте два коммита, исправляющие две ошибки:
1. Исправление ошибки в инициализации TransitInfo -- для конструирования dummy Transfer передаем Edge с типом Transfer
2. Исправление ошибки в заполнении TransitInfo при постобработке маршрута.
Проблема была в том, что в PedestrianDirectionsEngine::Generate из RoadGraph из вектора сегментов, который в нём сохранен, получался вектор Edge, а потом по вектору Edge обратно восстанавливался вектор сегментов. При этом Edge внутри имеют FeatureID, который для фейковых сегментов не существует, и информация о транзитных сегментах терялась. Эта информация нужна далее чтобы корректно отрисовать маршрут, поэтому вместо восстановления вектора сегментов по вектору Edge берём вектор сегментов из RoadGraph.
=> [routing][transit] Fix set transit info

generator/transit_generator.cpp, routing/index_router.cpp, routing/index_router.hpp
Пару недель назад, при написании кода поиска ближайшего (лучшего) пешеходного сегмента к гейту мы спрятали создание WorldGraph в метод: IndexRouter::FindBestSegmentInSingleMwm(). Это оказалось не эффективно, поскольку для каждого Gate-та при создании секции transit создавался WorldGraph. Я передал код так, чтоб WorldGraph создавался один раз, на сборку секции transit.
=> [transit] Optimization. Creating world graph once for building mwm transit section.

routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/pedestrian_directions.cpp, routing/road_graph.cpp, routing/road_graph.hpp
Во вчерашнем PR было место, провоцирующее ворнинг, исправила.
=> Fix control reaches end of non-void function for NOTIMPLEMENTED RoadGraphBase::GetRouteSegments

routing/transit_graph.cpp
После появления в данных и в классе transit::Line информации об интервале следования меняю константу на `line.GetInterval() / 2` -- мат ожидание времени ожидания.
=> [routing][transit] Apply lines transfer penalty

routing/transit_world_graph.cpp
Исправила ошибку поиска фейковых сегментов, соответствующих реальным.
Если мы ищем исходящие сегменты, то back фейкового и соответствующего ему реального должен совпадать, если входящие то front. До этого тут по ошибки вместо соответствующего реального использовался исходный сегмент, для которого ищем входящие/исходящие.
Это условие можно переформулировать как
```C++
bool const frontConnectedToBack = GetJunction(segment, true /* front */) == GetJunction(s, false);
bool const backConnectedToFront = GetJunction(segment, false /* front */) == GetJunction(s, true);
if ((isOutgoing && frontConnectedToBack) || (!isOutgoing && backConnectedToFront))
{
...
}
```
но думаю haveSameFront, haveSameBack понятнее.
=> Fix transit to pedestrian connection

routing/transit_graph.cpp, routing/transit_graph.hpp, routing/transit_graph_loader.cpp, routing_common/transit_types.hpp
Два небольших рефакторинга TransitGraph:
1. Из интерфейса метода Fill убран Estimator и IndexGraph, которые использовались для поиска проекций gate на пешеходные сегменты, теперь эти действия происходят снаружи от TransitGraph.
2. m_stopToBack, m_stopToFront, которые используются только в ходе выполнения метода Fill переехали из полей в локальные переменные метода Fill
=> [routing][transit] TransitGraph refactoring

map/map_tests/CMakeLists.txt, map/map_tests/map_tests.pro, map/map_tests/search_api_tests.cpp, search/engine.cpp, search/pysearch/bindings.cpp, search/search_integration_tests/downloader_search_test.cpp, search/search_integration_tests/generate_tests.cpp, search/search_integration_tests/helpers.cpp, search/search_integration_tests/helpers.hpp, search/search_integration_tests/interactive_search_test.cpp, search/search_integration_tests/pre_ranker_test.cpp, search/search_integration_tests/processor_test.cpp, search/search_quality/features_collector_tool/features_collector_tool.cpp, search/search_quality/search_quality_tool/search_quality_tool.cpp, search/search_tests/CMakeLists.txt, search/search_tests/locality_finder_test.cpp, search/search_tests/search_tests.pro, search/search_tests_support/CMakeLists.txt, search/search_tests_support/search_tests_support.pro, search/search_tests_support/test_results_matching.cpp, search/search_tests_support/test_results_matching.hpp, search/search_tests_support/test_search_engine.cpp, search/search_tests_support/test_search_engine.hpp, search/search_tests_support/test_with_classificator.cpp, search/search_tests_support/test_with_classificator.hpp, search/search_tests_support/test_with_custom_mwms.cpp, search/search_tests_support/test_with_custom_mwms.hpp
TestSearchEngine is decoupled with Index, so it's possible to abstract out base test that allows to build custom mwms, and reuse it in search integration tests and in search API tests.
=> [search] SearchAPI tests.

data/replaced_tags.txt, generator/generator_tests/osm_type_test.cpp, indexer/feature_data.cpp
Fixes #7030 
Сейчас скамейки и банкоматы могут быть как самостоятельными объектами (`amenity=atm`), так и атрибутами других заведений (`atm=yes`). Сделал то же для туалетов. Тегов `toilets=yes` 18 тысяч на планете, полезная штука.
=> [generator] Add toilets type for toilets=yes

generator/generator_tests/CMakeLists.txt, generator/generator_tests/generator_tests.pro, generator/generator_tests/transit_graph_test.cpp, generator/generator_tests/transit_test.cpp, generator/generator_tests/transit_tools.hpp, generator/transit_generator.cpp, generator/transit_generator.hpp, routing_common/transit_types.hpp
Данный PR из всех .transit.json файлов выбирает те элементы, которые лежат в границах указанной mwm-ки.
Кроме того, добавлены тесты, на clipping графа.
Правила по которым выбираются элементы графа:
Генератор получает на вход ряд графов общественного транспорта в виде json (https://confluence.mail.ru/display/MAPSME/Subway+Data+Preparation)
Необходимо уложить в секцию transit в mwm только те вершины графов общественного транспорта, которые попадают в границы обрабатываемой mwm. При этом использовать следующие правила при попадании элементов графа общественного транспорта в mwm:
stops: попадают только те остановки, которые геометрически попадают в границы mwm согласно data/borders/*.poly + все остановки, которые соединены с ними при помощи edges. Если feature id получено быть не может, …
=> Clipping transit graph by mwm border.

.gitignore, qt/CMakeLists.txt, qt/res/Info.plist.in
Usage:
```
cmake {your_omim_path} -DBUILD_DESIGNER:bool=True -DAPP_VERSION={app_version}
sudo make package -j8
```
Necessity of sudo is explained by read-only permissions on qt library directories. There is also may be some problems with copying tools/shaders_compiler.
=> CMake Designer Tool Fix Final

indexer/categories_holder.cpp, indexer/categories_holder.hpp
=> [indexer] [search] Enabled the Persian language for categories.

generator/routing_index_generator.cpp, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/fake_ending.cpp, routing/fake_ending.hpp, routing/features_road_graph.cpp, routing/features_road_graph.hpp, routing/index_graph_starter.cpp, routing/index_router.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/transit_graph.cpp, routing/transit_graph.hpp, routing/transit_graph_loader.cpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, routing/world_graph.hpp, routing_common/bicycle_model.cpp, routing_common/bicycle_model.hpp, routing_common/car_model.cpp, routing_common/car_model.hpp, routing_common/pedestrian_model.cpp, routing_common/pedestrian_model.hpp, routing_common/routing_common_tests/vehicle_model_test.cpp, routing_common/vehicle_model.hpp, track_analyzing/track_analyzer/cmd_tracks.cpp, track_analyzing/track_matcher.cpp
В TransitGraph, TransitGraphLoader использовался estimator для оценки веса фейковых пешеходных дуг (part of real для подхода к гейту и дуги от проекции до гейта) и это было ошибкой, так как использовался "быстрый" estimator для общественного транспорта.
Заменила estimator на передачу средней скорости пешехода, так как единственное что нужно от estimator -- оценивать LeapWeight, ради этого тащить второй пешеходный эстиматор мне показалось излишним.
Кроме того, выпилила estimator из кода создания FakeEnding, там он на самом деле был не нужен -- нужно только сравнить расстояние, это можно сделать напрямую без estimator.
=> Getting rid of estimator in TransitGraph, TransitGraphLoader

routing/transit_graph.cpp
Договорились с @bykoianko для общности работы с cross-mwm использовать в cross-mwm для общественного транспорта те же фейковые сегменты, которые используются в TransitGraph.
Для этого необходимо чтобы идентификаторы transit::Edge в фейковом графе были стабильны в рамках версии данных и желательно привязаны к чему-то реальному.
Изменила порядок инициализации фейковых сегментов так, чтобы transit::Edge инициализировались первыми и их идентификаторы соответствовали порядку следования рёбер в mwm.
=> [routing][transit] Stable fake segment ids for transit edges

generator/road_access_generator.cpp, generator/road_access_generator.hpp, generator/routing_index_generator.cpp, routing/index_graph_loader.cpp, routing/index_graph_loader.hpp, track_analyzing/track_matcher.cpp
Исправила определение RoadAccess для ситуаций типа
```
access=no
foot=yes
```
PR содержит два коммита:
1. Доработка генератора, чтобы теги, имеющие отношение к конкретному типу транспорта учитывались с большим приоритетом чем просто тег access.
2. Независимо от типа транспорта считывался RoadAccess для VehicleType::Car, поменяла чтобы читался нужный тип.
=> [routing] Fix access tags combination

generator/generator_tests/transit_graph_test.cpp, generator/generator_tests/transit_test.cpp, generator/transit_generator.cpp, generator/transit_generator.hpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_serdes.hpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
В данном PR-те реализован ряд оптимизаций по уменьшению размера секции transit:
1. Реализовано дельта кодирование для хранения m_stopId в Stop и для m_stop1Id в Edge.
2. Все веса (в Gate, в Edge и в Line) теперь хранятся в виде целых чисел, в секундах. Это позволило их более оптимально хранить в varint.
3. Реализованы отдельные сериализаторы, десериализаторы для Edge. Это дало хороший эффект из-за того, что вектор m_shapeIds в Edge часто состоит из полей Edge::m_stop1Id и Edge::m_stop2id. Для этого в байт, в котором хранилось поле m_transfer так же положено: (1) пуст ли вектор m_shapeIds в Edge; (2) равен ли размер вектора m_shapeIds в Edge одному; (3) если 2 верно, то состоит ли единственный shape id в m_shapeIds из Edge::m_stop1Id и Edge::m_stop2id; () если 2 верно, то состоит ли …
=> Transit section optimization.

search/geocoder.cpp, search/geocoder.hpp, search/pre_ranker.cpp, search/pre_ranker.hpp, search/processor.cpp, search/ranker.cpp, search/ranker.hpp
Previously, Processor called Emitter directly to set
the end marker, but all other calls to Emitter were made
through the Geocoder-Preranker-Ranker pipeline.
Now all calls must be made through the pipeline, which
at least makes in easier to update the state in case
of cancellation (which is only done in PreRanker's m_currEmit currently).
Also, removed an unneeded call of UpdateResults in Processor:
all UpdateResults calls from Processor must now be made indirectly,
either via the normal search process in Geocoder, or via calling
Finish.
=> [search] Flattened the call graph of UpdateResults and Finish.

coding/coding_tests/csv_reader_test.cpp, editor/editor_tests/config_loader_test.cpp, editor/editor_tests/editor_notes_test.cpp, generator/generator_tests/altitude_test.cpp, generator/generator_tests/restriction_collector_test.cpp, generator/generator_tests/restriction_test.cpp, generator/generator_tests/road_access_test.cpp, indexer/indexer_tests/osm_editor_test.cpp, local_ads/local_ads_tests/file_helpers_tests.cpp, openlr/openlr_tests/decoded_path_test.cpp, platform/platform_tests/local_country_file_tests.cpp, platform/platform_tests_support/scoped_file.cpp, platform/platform_tests_support/scoped_file.hpp, platform/platform_tests_support/scoped_mwm.cpp, routing/routing_tests/routing_mapping_test.cpp, storage/storage_tests/storage_tests.cpp
The option allows one to push responsibility on the user
of the ScopedFile, that is, enables a scenario where
a ScopedFile does not try to create the file on disk
but only assures the cleanup.
=> [platform] [tests] Added an option to ScopedFile.

routing/base/astar_algorithm.hpp
Начиная с этого PR:
https://github.com/mapsme/omim/commit/e1ede4b1100a47b57e781d8bc9d77a9431f3bb18
думаю тут должен быть `+`:
```math
lr_i = l_i + h_i - h_(i-1)
SUM(lr) = SUM(l) + h_ff - h_sf
SUM(l) = SUM(lr) + h_sf 
```
где `lr_i` -- reduced length i-ого ребра, `l_i` -- длина i-ого ребра, `h_ff` -- эвристика от финиша до финиша равна 0, `h_sf` -- эвристика от старта до финиша. 
ну и под дебаггером посмотрела что сейчас возвращаемый вес не соответствует сумме весов рёбер, после исправления соответствует.
=> Fix distance calculation for unidirectional AStar

indexer/CMakeLists.txt, indexer/fake_feature_ids.cpp, indexer/fake_feature_ids.hpp, indexer/indexer.pro, indexer/osm_editor.cpp, routing/fake_feature_ids.cpp, routing/fake_feature_ids.hpp, routing/transit_graph.cpp, routing/transit_graph.hpp, xcode/indexer/indexer.xcodeproj/project.pbxproj
Перевела TransitGraph на использование разных FeatureId вместо kTransitFeatureId и разных SegmentIdx.
Для избежания конфликтов фейковых диапазонов в TransitGraph и в OsmEditor вынесла определение фейкового диапазона в OsmEditor из анонимного неймспейса в хедер.
=> [routing][transit] Use different featureIds for transit segments. 

routing/base/astar_algorithm.hpp, routing/cross_mwm_router.cpp, routing/fake_edges_container.hpp, routing/index_graph.cpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/route_weight.cpp, routing/route_weight.hpp, routing/routing_tests/astar_algorithm_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/transit_graph.cpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, routing/world_graph.hpp, track_analyzing/track_matcher.cpp
Ограничения времени хождения пешком для режима прокладки маршрута Transit.
Текущая реализация находит только самый коротки маршрут. Если есть маршрут на транспорте, удовлетворяющий ограничениям на пешее время, но который при этом не является самым коротким по общему времени, он не будет найден. Решение которое позволит искать такие маршруты требует дополнительной исследовательской работы для реализации.
+ Сделала в AStar коллбек для проверки допустимости веса.
+ Добавила компоненту transitTime в многокомпонентный вес -- время движения на транспорте. Сначала собиралась сделать pedestrianTime, но transitTime кажется более правильным т.к. TransitGraph знает какие ребра мы едем на транспорте, какие идём пешком и может всё правльно заполнить.
+ Перевела проверку допустимости …
=> [routing][transit] Transit pedestrian restrictions

generator/routing_index_generator.cpp
Очень часто бывает, что при генерации mwm нам нечего положить в секцию transit. И следовательно мы ее не создаем. Затем при попытке создать transit_cross_mwm мы падаем на CHECK о том, что не transit. Что не верно. Данный PR исправляет ошибку.
=> Stop crashing generator in case of absence transit section.

base/CMakeLists.txt, base/base.pro, base/base_tests/CMakeLists.txt, base/base_tests/base_tests.pro, base/base_tests/control_flow_tests.cpp, base/control_flow.hpp, coding/coding_tests/multilang_utf8_string_test.cpp, coding/multilang_utf8_string.cpp, coding/multilang_utf8_string.hpp, feature_list/feature_list.cpp, generator/dumper.cpp, generator/restaurants_info/restaurants_info.cpp, generator/search_index_builder.cpp, indexer/editable_map_object.cpp, indexer/feature.cpp, indexer/feature_utils.cpp, indexer/indexer_tests/editable_map_object_test.cpp, search/ranker.cpp, search/retrieval.cpp, search/search_quality/matcher.cpp, xcode/base/base.xcodeproj/project.pbxproj
The convention we used to break a ForEach loop prematurely
was to return false from the function object that was being
called by ForEach. Now the function object must return a special
enum, thus making the intention more readable.
=>  [base] ControlFlow.

generator/generator_tests/transit_graph_test.cpp, generator/transit_generator.cpp, routing_common/transit_types.hpp
Иногда возникают весьма странные ситуации, когда одна и та же линия соединяет два стопа более чем одни раз. Например, в Осло: https://en.wikipedia.org/wiki/Oslo_Metro#/media/File:Oslo_Metro_Map.svg линия 5.
Это означает, что два стопа будут соединены дугой в одном и том же направлении и line_id у этих дуг будет совпадать. В таких случаях маршрутизатор будет использовать ту дугу, которая легче. А если веса дуг одинаковы, то произвольную дугу.
Данный PR включает в себя реализацию и тесты.
@tatiana-kondakova @darina @Zverik PTAL
=> [transit] Removing equivalent edges.

generator/generator_tool/generator_tool.cpp, platform/platform.cpp, platform/platform.hpp, platform/platform_tests_support/writable_dir_changer.cpp, tools/unix/generate_planet.sh
Данный PR позволяет собирать секции transit и transit_cross_mwm для мира.
То что происходит с SetSettingDir - требует отдельного пояснения.
При сборке секции transit мы ищем и сохраняем ближайший пешеходный сегмент к каждому гейту. Для этого используется метод: `IndexRouter::FindBestSegment(...)`. Для инициализации `IndexRouter` нужно создать `CountyInfoGetter`, т.е. вызвать: `storage::CountryInfoReader::CreateCountryInfoReader(GetPlatform());`. Перовой строчке этой ф-ции мы проверяем, произошла ли миграция или нет.
```c++
unique_ptr<CountryInfoGetter> CountryInfoReader::CreateCountryInfoReader(Platform const & platform)
{
if (platform::migrate::NeedMigrate())
return CreateCountryInfoReaderTwoComponentMwms(platform);
return CreateCountryInfoReaderOneComponentMwms(platform);
}
```
Этот …
=> transit и transit_cross_mwm section generation.

indexer/indexer_tests/osm_editor_test.cpp, indexer/indexer_tests_support/helpers.cpp, indexer/indexer_tests_support/helpers.hpp, indexer/osm_editor.cpp, indexer/osm_editor.hpp, map/framework.cpp, search/search_tests_support/test_with_custom_mwms.hpp
Framework is instantiated in the map tests, and some tests may interfere with other tests. This PR fixes this.
=> [map] Fixed Framework shutdown + TearDownEditorForTesting.

indexer/osm_editor.cpp
This reverts commit c399af93fe96eb44c0a5c77faabda0497e133ce7.
From pr https://github.com/mapsme/omim/pull/7699
=> Revert "[editor] call LoadMapEdits before uploading changes"

routing_common/vehicle_model.cpp, routing_common/vehicle_model.hpp
Не был разрешен сквозной проезд через дороги с additional road type (пирсы, паромы, явно потеганные vehicle_type=yes), хотя должен быть.
Тестируется интеграционными тестами.
=> [routing] Fix pass through additional road types

generator/transit_generator.cpp
При генерации секции transit необходимо инициализировать IndexGraph. Для этого нужно создать CountyInfoGetter. А ему в свою очередь нужно знать использовать countries.txt или countries_obsolete.txt.
Если settings.ini нет или поля в "LastMigration" в settings.ini нет используется countries_obsolete.txt (крупная разбивка mwm). Т.о. чтоб генератор корректно работал ему необходимо подсунуть сейчас setting.ini со строчкой LastMigration=<достаточно большое число> (например, LastMigration=160302). Если этого не сделать - будет использован countries_obsolete.txt.
Учитывая, что:
- мы уже не поддерживаем миграцию с крупных mwm-ок и ни когда не используем countries_obsolete.txt в текущем коде; 
- у нас setting.ini не лежит в репозитории, и его надо поддерживать генератору;
Предлагаю по умолчанию …
=> Generator gits rid of settings.ini dependency.

generator/transit_generator.cpp
При сборке карты мира выяснилось, что очень редко (в одном случае: Osm id: relation 3791635) stop был представлен, как relation (2 платформы). Мы со @Zverik решили, что такое в принципе возможно. Вместе со stop передается osm id, которое при генерации конвертируется в feature id, и затем используется при подписывании остановок. Данный PR, в случае, если osm id отображается в несколько feature id не останавливает генератор, а берет одно из feature id (произвольное) и пишет warning на этапе генерации.
@Zverik @darina @ygorshenin PTAL
=> Taking into account cases when a stop is present as a relation.

routing/routing_consistency_tests/CMakeLists.txt, routing/routing_consistency_tests/routing_consistency_tests.pro, routing/routing_integration_tests/CMakeLists.txt, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/routing_integration_tests.pro, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/turn_test.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
Интеграционные тесты были заброшены, привожу в порядок.
Этот PR состоит из трёх коммитов:
- включение использования правильных VehicleModel для конкретной страны, для этого из storage подтягивается CountryParentGetter
- увеличение количества разрешенных файловых дескрипторов -- есть тесты, которые открыают все mwm-ки, а их уже больше 1024
- актуализация тестов.
Актуализация проведена как в части соответствия изменившимся картам, так и в части обновления функциональности, например тесты на то что дороги типа service в россии не проезжаются насквозь.
Там где карты изменились подобрала аналогичный тесткейс в другом месте.
Часть тестов остается сломанной, добавила к ним комментарии о том, что не работает. Большинство ошибок в генерации манёвров.
До изменений не проходило 67 тестов, сейчас с …
=> [routing] Fix routing integration tests

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-6204
Суть проблемы была в следующем. Если при запросе виатора возникала ошибка, то ядро возвращало пустой список продуктов и этот пустой список кладется в кэш по destId. Далее, когда снова тапаешь на объект виаторовский, срабатывало условие (!Viator.hasCache(id)) и галерея не переводилась в состояние loading.
Решение: удалил эту проверку, т.к. она лишняя и костыльная. Внутри класса Viaotor и перед тем как делать запрос есть проверка в кэше и + проверяется пустой список или нет, что правильно. Тем самым loading состояния всегда будет и его не должно не быть, да если в последующем данные возмуться из кэша.
=> [android] Fixed loading gallery state for vaitor in PP

routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/road_access_test.cpp
Избавилась от IndexGraphStarter в TestIndexGraphTopology, так как в TestIndexGraphTopology используется ZeroGeometry, а IndexGraphStarter-у нужна геометрия для построения фейковых рёбер.
До этого c FindPathBidirectional работало по чистой случайности, а c FindPath получали invariant violation из-за неправильно вычисленных фейковых дуг (MAPSME-6037).
Теперь в тестах топологии используется чистый WorldGraph без стартера.
=> [routing][MAPSME-5653][MAPSME-6037]Get rid of IndexGraphStarter in TestIndexGraphTopology.

routing/route_weight.hpp, routing/routing_tests/index_graph_tools.cpp
Добавила запуск одностороннего AStar в тесты, сравнение времени с двухсторонним, чтобы односторонний AStar тестировался и в случае нетривиальной эвристики.
Будет ловить ошибки типа https://github.com/mapsme/omim/pull/7609 .
=> [routing] Run both bidirectional and unidirectional AStar in routing tests.

routing/cross_mwm_connector.hpp, routing/cross_mwm_graph.hpp, routing/cross_mwm_index_graph.hpp, routing/cross_mwm_osrm_graph.hpp, routing/fake_edges_container.hpp, routing/fake_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, routing/world_graph.hpp
Рефакторинг создания фейковых leap от старта/финиша к выходам/входам из mwm.
Пока не исправляет ошибки, этот PR только про перенос создания фейковых дуг в стартер.
Теперь фейковая дуга начинается с фейкового стартового сегмента, а не с первого "реального", поэтому немного изменился код ProcessLeaps:
- убрано перекладывание фейковых сегментов в output в LeapsOnly
- маршрут для фековых Leap строится по стартеру в режиме NoLeaps, а не по WorldGraph.
=> [routing] Start and finish leaps creation refactoring

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/base/BaseActivityDelegate.java, android/src/com/mapswithme/maps/base/BaseMwmFragmentActivity.java
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5a34a4608cb3c2fa63fc1e1f?time=last-seven-days
В общем этот крэш - это все тот же крэш с removeMapObjectListener. Сейчас он выглядит более правильно, видимо после перехода на симейк. 
Суть проблемы в том, что метод `Framework.nativeRemoveMapObjectListener()` вызывается в каком-то случае два раза подряд. В каком это кейсе может произойти - пока не представляется возможным мне придумать (должен метод stop два раза подряд вызваться!). Зануление g_mapObjectListener'a улучшит нам статистику в Fabric'e, но корневая проблема останется. Чтобы ее решить, я вставил логирование в фабрик всех методов жизненного цикла всех экранов.
=> [android] Fixed crash during double-removing map object listener

routing/nearest_edge_finder.cpp
При поиске ближайших к точке сегментов мы исследуем фичи в окрестности точки. Ранее, если мы находили сегмент с нулевой длиной (старт и финиш совпадают) мы писали warning про это в лог. Хотя, это вполне штатная ситуация, которая корректно обрабатывается. Я удалил данный warning. 
На данный PR натолкнуло то, что при сборке секции transit мы вызываем данный метод FindClosestEdges()/finder.AddInformationSource многократно для каждого gate-та. И данный warning достаточно часто появлялся при сборке карт.
@tatiana-kondakova @Zverik PTAL
=> Removing a warning about segments with zero length.

openlr/decoded_path.cpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_mode.cpp, openlr/openlr_tests/decoded_path_test.cpp, routing/index_road_graph.cpp, routing/nearest_edge_finder.cpp, routing/road_graph.cpp, routing/road_graph.hpp, routing/routing_tests/nearest_edge_finder_tests.cpp, routing/routing_tests/road_graph_nearest_edges_test.cpp
Поддержка изменений в поведении IsFake в ReconstructPath:
раньше фейковость определялась по тому, содержит ли Edge реальный или пустой FeatureId, вызывающий код на это расчитывал.
заодно поправила 
`Edge Edge::MakeFake(Junction const & startJunction, Junction const & endJunction)`
этот метод производил ребро с типом Real, думаю это ошибка
=> [routing] Fix ReconstructPath with new routing::Edge::IsFake behaviour.

transit/transit_speed_limits.hpp
Удалил из проекта не используемую среднюю скорость на дуге общественного транспорта. Данный скорости должны поступать из графа в transit.json формате.
@tatiana-kondakova @Zverik PTAL
=> [transit] Removing unused kTransitAverageSpeedMPS.

map/framework.cpp, storage/country_info_getter.cpp, storage/country_info_getter.hpp, storage/storage_tests/helpers.cpp
В нашем проекте CountryInfoGetter создается при помощи CountryInfoReader::CreateCountryInfoReader() метода. Для работы данного метода необходимо обратиться к settings.ini, чтоб понять, произошла ли миграция. Не хорошо, что базовый метод требует наличия вспомогательного файла. Это не удобно, например, в генераторе.
В то время, как почти всегда (кроме как во framework) требуется создавать CountryInfoGetter на базе нового разбиения mwm.
Данный PR:
1. переименовывает методы: 
CreateCountryInfoReaderOneComponentMwms()->CreateCountryInfoReader()
CreateCountryInfoReaderTwoComponentMwms()->CreateCountryInfoReaderObsolete()
2. переносит выбор вызова правильного метода из методов выше во framework
3. Удаляет старый метод: CreateCountryInfoReader().
Данный PR сделан по следам обсуждения в: …
=> CreateCountyInfoReader() function refactoring and generator fix.

routing/base/astar_algorithm.hpp, routing/cross_mwm_connector.hpp, routing/cross_mwm_graph.cpp, routing/cross_mwm_graph.hpp, routing/cross_mwm_index_graph.hpp, routing/cross_mwm_router.cpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/routing_algorithm.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_tests/astar_algorithm_test.cpp, routing/routing_tests/cross_mwm_connector_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, routing/world_graph.cpp, routing/world_graph.hpp
Починка крешей в AStar при cross-mwm:
- в LeapsOnly используем только однонаправленный AStar;
- в GetTwins для LeapsOnly всё остается как было (нужны дублирующиеся сегменты -- и вход и выход из каждой mwm и при однонаправленном AStar проблем нет);
- в GetTwins для остальных режимов не добавляем дубликатов (иначе в обратной волне неоткуда будет брать вес на следующем за GetTwins шаге), вместо этого список входящих/исходящих для сегмента добавляем входящие/исходящие для его близнецов.
Прошлась по крешам из fabric, с теми что я посмотрела теперь всё ок. Добавила два случая в тесты:
- финиш на стыке mwm, который раньше падал на проверке эвристики в результате неправильной работы GetTwins в обратной волне;
- маршрут из Германии в Таллин, который падал на проверке эвристики из-за неправильной …
=> [routing][MAPSME-5953] Disable ingoing edges listing for LeapsOnly mode, remove LeapsIfPossible mode.

routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/loaded_path_segment.hpp, routing/road_graph.cpp, routing/routing_result_graph.hpp, routing/routing_tests/turns_generator_test.cpp, routing/turn_candidate.hpp, routing/turns.cpp, routing/turns.hpp, routing/turns_generator.cpp
Продолжаю удалять osrm поддержку. Сейчас приступил к библиотеке routing. Данный PR удаляет остатки osrm поддержки из генерации turn-ов.
=> Removing osrm from turn generation.

routing/base/astar_algorithm.hpp, routing/cross_mwm_router.cpp, routing/index_router.cpp, routing/routing_algorithm.cpp, routing/routing_tests/astar_algorithm_test.cpp, routing/routing_tests/index_graph_tools.cpp
Сломала в https://github.com/mapsme/omim/commit/86dc1ec066e30824ac9cdd76f8a037eaeec53b2c
Конструктор Params как и AStar::FindPath/AStar::FindPathBidirectional/AStar::AdjustRoute принимал большинство параметров по константным ссылкам. Но раньше когда в тестах мы инициализировали их временными переменными (default constructed my::Cancellable, значения для вершин типа unsigned и т.п.) это было ок, так как время жизни временной переменной расширялось до окончания выражения, в кором был вызов функции.
После создания params временная переменная стала жить до окончания конструктора. Исправляю это в этом PR.
=> [routing] Fix AStarAlgirithm::Params lifetime

routing/routing_settings.cpp
Настройка RoutingSettings для transit.
https://jira.mail.ru/browse/MAPSME-6426
Ранее навигация для общественного транспорта копировала настройки пешеходной. Причина скорее всего в том, что маршрут общественного транспорта состоит из двух типов маршрута: метро и пеший. Но имеет только одни настройки. Правильным (но вероятно, через чур сложным) решением было бы использовать отдельные настройки для пешей части, а отдельные для метро, а в будущем отдельные для автобуса.
Пока думаю оставить одни настройки для всех маршрутов входящих в transit, но немного их подрегулировать.
Я увеличил коридор матчинга для transit с 40 до 80 метров. (Было 20*2 стало 40*2).
Данный PR вместо такого поведения стрелки, отражающей текущую позицию, при движении по маршруту transit:
В ряде ситуаций сделает вот такое: …
=> Widening passage for transit routing.

drape_frontend/user_mark_shapes.cpp
Поскольку хранение меток специально отвязано от обновления групп меток, может быть ситуация, когда метка уже удалена, а индекс для группы еще не пересчитан. Такое возможно при одновременном удалении метки и вычитке карты. Это допустимо, правильный тайл с метками все равно будет перерисован после обновления группы.
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/59edad3661b02d480d0c8549
=> Fixed crash in user marks caching.

routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/routing_test_tools.hpp
У нас в интеграционных тестах количество точек в маршруте сравнивалось с ожидаемым или строго (TEST_EQUAL) или на больше/меньше без задания погрешности, это было не очень хорошо в условиях меняющихся карт. Сделала сравнение с погрешностью, похожее на то что используется для расстояния и для времени.
=> [routing] Improve points number testing in routing integration tests

routing/index_router.cpp
Удаление из проекта osrm привело к тому, что маршруты для автомобилей не будут прокладываться на картах без секций routing и cross_mwm. (Ранее, когда не было секции cross_mwm использовались секции osrm). Т.о. в ситуациях, когда карта старая (без секций указанных выше) CalculateRoute() должна заполнять, какие страны надо обновить (route.AddAbsentCountry(mwm)) и возвращать IRouter::ResultCode::FileTooOld;
Это и делает данный PR модифицирую метод: GetOutdatedMwms(m_index, outdatedMwms), который вызывает: GetOutdatedMwms()
Данный PR делает так, что мы будем прокладывать авто маршруты только по картам от 28 апреля 2017 и более поздним. В нем пока сохранена возможность прокладки пеших вело маршрутов по картам, более старым при помощи старого роутера.
@ygorshenin @mpimenov PTAL
=> Returns IRouter::ResultCode::FileTooOld for car routing if maps from 0317 and older.

drape_frontend/frontend_renderer.cpp
При кривом (не инициализированном, например) ScreenBase может теоретически формироваться некорректный scale. Воспроизвести данную ситуацию и понять ее причины на тестовом окружении не получается, исправление тривиально и, по идее, не должно аффектить ничего другого.
https://jira.mail.ru/browse/MAPSME-6448
=> Fixed crash in GetBgColor

search/search_quality/features_collector_tool/features_collector_tool.cpp
An alternative would be to start the numbering from zero in the assessment tool but I have no strong preference in this particular case.
=> [search] Fixed a discrepancy in the numeration of samples.

routing/index_graph.cpp, routing/index_graph_starter.cpp, routing/route_weight.cpp, routing/route_weight.hpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/road_access_test.cpp, routing/transit_graph.cpp
Добавила в многокомпонентный вес компонент для access.
Поскольку мы теперь обрубаем пути, нарушающие ограничение на вес, в процессе построения маршрута, уменьшила размер компонентов для nonPassThroughCross, accessCross -- они вполне влезут в int8_t, а растить размер RouteWeight нехорошо -- его много в очереди в AStar.
В данной реализации проезд через access = no запрещен, а через access = private, access=destination разрешен и при этом будет выбран маршрут с наименьшим возможным числом пересечений. Это сделано, потому что следующим шагом буду добавлять шлагбаумы, а их по пути в зону с ограниченным доступом может быть несколько и разрешать пересекать access=destination один раз будет неправильно (текущая версия не разрешает строить маршрут из/в access=destination, access=private). Хорошим …
=> [routing] Add access component to RouteWeight

routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/routing_result_graph.hpp, routing/turn_candidate.hpp, routing/turns.cpp, routing/turns.hpp, routing/turns_generator.cpp
Исправлен assert, который возникал при прокладке маршрута в debug режиме. Он проверял, что наборы сегментов (segment range) между joint уникальны в маршруте.
Данный assert возникал в двух случаях:
1. Проблема. После появления возможности прокладывать маршрут через промежуточные точки стало возможным прохождения маршрута несколько раз через одни и те же сегменты графа дорог.
Решение. Сейчас мы проверяем (в ASSERT), что если маршрут проходит через один и тот же segment range несколько раз, то соответствующие ему смежные дуги совпадают.
2. Проблема. В маршруте содержится несколько fake-вых дуг, которым соответствует SegmentRange, созданный конструктором по умолчанию. При для разных fake-вых дуг формируются отличные друг от друга |adjacentEdges| (См. …
=> Fixing assert for segment uniqueness in route.

indexer/ftypes_matcher.cpp, platform/local_country_file.hpp, routing/routing_integration_tests/get_altitude_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/turn_test.cpp
Поправлено 7 тестов в routing_integration_tests. Сейчас не проходят 16:
16  tests failed:
bicycle_turn_test.cpp::RussiaMoscowSalameiNerisPossibleTurnCorrectionBicycleWayTurnTest
bicycle_turn_test.cpp::RussiaMoscowSevTushinoParkBicycleOnePointTurnTest
pedestrian_route_test.cpp::BelarusMinskRenaissanceHotelUndergroundCross
pedestrian_route_test.cpp::RussiaMoscowTrubnikovPereulok30Ac1LiftGate
pedestrian_route_test.cpp::RussiaMoscowKhlebnyyLane15c1Gate
pedestrian_route_test.cpp::RussiaMoscowKhlebnyyLane19LiftGateAndGate
turn_test.cpp::RussiaMoscowSalameiNerisUturnTurnTest
turn_test.cpp::RussiaMoscowTrikotagniAndPohodniRoundaboutTurnTest
turn_test.cpp::RussiaMoscowNoTurnsOnMKADTurnTest
turn_test.cpp::RussiaMoscowTTKKashirskoeShosseOutTurnTest …
=> Fixing 7 tests from routing_integration_tests.

generator/generator_tests/road_access_test.cpp, generator/road_access_generator.cpp, generator/road_access_generator.hpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/road_access.cpp, routing/road_access.hpp, routing/road_access_serialization.hpp, routing/road_point.hpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/road_access_test.cpp
Добавила в генератор генерацию RoadAccess для точечных фичей.
При генерации пользуюсь тем, что в o5m nodes идут раньше чем ways -- предсохраняем информацию о nodes с заполненными тегами доступа, при сохранении информации для ways используем запомненные nodes, сохраняем их вместе, чтобы потом одинаково конвертить osm id в faeture id.
В RoadAccess вместо того чтобы хранить информацию о доступности сегментов храню информацию о доступности фичей и RoadPoints (т.к. именно RoadPoints имеют ограниченный доступ в случае точечных фичей, сегменты по обе стороны от запрещенной RoadPoint можно использовать), такой подход позволит не лепить в дальнейшем костылей для односегментных маршрутов и т.п.
Пока что в IndexGraph не используется информация о доступности RoadPoints, сделаю отдельно.
Для …
=> [routing][generator]Save road points access info

data/mapcss-mapping.csv, data/types.txt
Простой фикс, добавляющий на карту 3700 прибрежных гостиниц, отмеченных правильным тегом `leisure=resort`. У нас, почему-то, был неправильный `tourism=resort`.
=> [types] Add leisure=resort

configure.sh
Current version doesn't work when repository is placed on a secondary hdd, and symlinked from the original hdd. For example, on my laptop:
```bash
y@lambda:~/coding/omim$ pwd
/home/y/coding/omim
y@lambda:~/coding/omim$ pwd -P
/media/linux-secondary-hdd/y/coding/omim
```
I.e. pwd shows logical path, but we need physical path here (what git rev-parse returns).
=> [build] Fixed configure.sh.

generator/generator_tool/generator_tool.cpp, generator/search_index_builder.cpp
Сложная логика вычисления пути ко временным файлам начала обрушивать генератор вот с такой ошибкой:
```
LOG TID(1) INFO      45.3044 generator_tool/generator_tool.cpp:307 main() Generating search index for /opt/mapsme/mwm/180122/Belarus_Minsk Region.mwm
LOG TID(1) ERROR     45.3047 generator/search_index_builder.cpp:459 BuildSearchIndexFromDataFile() Error writing index file: /Belarus_Minsk Region.sdx.tmp; Write truncate; Permission denied
LOG TID(1) WARNING   45.3047 internal/file_data.cpp:232 CheckFileOperationResult() File operation error for file: /Belarus_Minsk Region.addr.tmp - No such file or directory
LOG TID(1) WARNING   45.3048 internal/file_data.cpp:232 CheckFileOperationResult() File operation error for file: /Belarus_Minsk Region.sdx.tmp - No such file or directory
LOG TID(1) …
```
=> [generator] Fix paths for search index builder

routing/routing_integration_tests/turn_test.cpp
Тест ниже должен быть изменен. 
Как видно из картинки, сообщения не об одном, а об двух маневрах в данном случае вполне корректно. Поскольку в обоих случаях есть выбор, куда ехать.
@tatiana-kondakova PTAL
=> Routing integration test RussiaMoscowLeningradskiyPrptToTheCenterUTurnTest fixing.

android/src/com/mapswithme/maps/routing/ResultCodesHelper.java, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm, routing/async_router.cpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/router.hpp
Добавлены 3 новых сообщения об ошибках при прокладке маршрута.
RouteNotFoundRedressRouteError - маршрут был проложен, но пост обработка не прошла. Его можно рассматривать в клиенте, как RouteNotFound.
TransitRouteNotFoundTooLongPedestrian - маршрут общественным транспортом не проложен, поскольку пешеходная часть слишком длинная.
TransitRouteNotFoundNoNetwork - маршрут общественным транспортом не проложен, поскольку в области старта, финиша или пром точки нет данных об общественном транспорте.
Идея в следующем. Если возникли проблемы пост обработки маршрута, то возвращается ошибка RouteNotFoundRedressRouteError в любом случае. Можно показать стандартное сообщение, что маршрут не проложен при любом типе маршрутизатора.
Если же мы прокладываем маршрут общественным транспортом, то могут …
=> Special messages for errors in transit routing.

routing/routing_integration_tests/turn_test.cpp
Тест на отсутствие генерации маневра. Проблема была в том, что отредактировали дорогу, которая использовалась в данном тесте: http://www.openstreetmap.org/way/483686777#map=18/7.90585/98.36788
Должно быть:
Ошибка была в этом:
Немого подвинул точку финиша.
@tatiana-kondakova PTAL
=> routing_integration_test ThailandPhuketNearPrabarameeRoad fix.

generator/osm2type.cpp
=> [generator] Skip keys like name:en:pronunciation

routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/turn_test.cpp
Данный тест был написан, как тест на генерацию маневра при съезде с обычной дороги на link. В этом плане сейчас все работает:
Проблема с тестом была в том, что сейчас маневр не генерируется, если сегмент, с которого маневер начинается это сегмент не полной (файковой) фичи. Мы не можем получить ее атрибуты, поскольку в место генерации маневра она приходит как Edge с координатами начала и конца. Так это было и в этом тесте:
Предлагаю сейчас подвинуть старт маршрута.
=> routing integration test RussiaMoscowMKADLeningradkaTest fix.

CMakeLists.txt, cmake/OmimHelpers.cmake
В главном CMakeLists.txt файле проекта накопилось 13 функций и 1 макрос. Для улучшения его читабельности предлагаю вынести все функции в отдельный файл ```cmake/OmimHelpers.cmake```, который подключается вот так:
```
include(OmimHelpers)
```
=> [cmake] Main CMakeLists.txt refactoring

routing_common/vehicle_model.hpp
Чинит сборку routing_common на centos 7, gcc 7.2
=> Add forgotten #include <functional>

coding/point_to_integer.hpp, indexer/cell_id.hpp, indexer/feature_covering.cpp, indexer/feature_covering.hpp, indexer/index.hpp, indexer/indexer_tests/scale_index_reading_tests.cpp, indexer/locality_index.hpp, indexer/locality_index_builder.hpp, indexer/scale_index_builder.hpp, search/mwm_context.cpp, search/street_vicinity_loader.cpp
Использование разной высоты дерева для обычного геоиндекса (всё остается как было -- 19) и для геокодера (увеличила до 24, чтобы ячейки были не слишком большими).
=> [geocoder] Change LocalityIndex depth

transit/transit_graph_data.cpp
Данный PR предназначен, чтоб исследовать вопрос со сборкой карт в случае если одна osm id отображается в несколько feature id.
=> Removing check in case of osm id is mapped to two or more features.

tools/unix/generate_planet.sh
Если прервать скрипт на этапе копирования границ и потом перезапустить, соберутся не все mwm. Здесь я безусловно очищаю и пересоздаю каталог с границами, чтобы таких косяков не было.
=> [generator] Backup old borders regardless of options

tools/python/transit/transit_color_palette.py, tools/python/transit/transit_graph_generator.py
Переиначил скрипт под питон3. Под вторым тоже будет работать, но чуть хуже. Кроме того, завернул matplotlib туда, где он реально используется, т.к. это не основная функциональность, а установить этот пакет не так просто.
Зачем? Потому что скрипт для подготовки метро тоже на питоне 3, ну и некомильфо уже как-то.
=> [transit] Update scripts to python 3

map/cloud.cpp, map/cloud.hpp, map/user.cpp
Храним имена (а не пути до) файлов в индексе облака, так как абсолютный путь до файлов букмарок может меняться от запуска к запуску
=> Store file names instead of file paths in the cloud index

3party/liboauthcpp/src/SHA1.h
Линковщик на некоторых системах (XCode) ищет не ту реализацию из-за эквивалентности ULONG_MAX и UINT_MAX. Ужесточил критерий выбора unsigned long.
=> Fixed SHA1 compilation

data/mixed_nodes.txt
Оказалось, что `banner_url` на фейковых объектах не только не нужен, но ещё и роняет приложение.
=> [partner] Remove banner_url from luggage hero points

generator/generator_tests/osm_type_test.cpp
Когда искал источник того, что в свежих картах Париж снова написан транскрипцией, написал тест для #7998. Оказалось, что всё работает, просто в сборку реквест не попал. Но тест пусть будет.
=> [generator] Add test for name:en:pronunciation

routing/bicycle_directions.cpp, routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_integration_tests/street_names_test.cpp, routing/routing_integration_tests/turn_test.cpp, routing/turn_candidate.hpp, routing/turns.cpp, routing/turns.hpp, routing/turns_generator.cpp
Добавлено ряд улучшений в систему генерации маневров и тесты на эти улучшения:
- не генерируется ошибочный маневр на двусторонней дороге. Ранее он иногда генерировался на двусторонних фичах, поскольку разворот на данной фиче рассматривался как путь, по которому водитель может ошибочно поехать
https://jira.mail.ru/browse/MAPSME-5455
https://jira.mail.ru/browse/MAPSME-6805
- на этапе ранней фильтрации не выкидываются плавные повороты, если все остальные кандидаты на повороты так же плавные;
https://jira.mail.ru/browse/MAPSME-6813
https://jira.mail.ru/browse/MAPSME-6803
- не генерируется (не нужны) маневр, если данный маневр является плавным поворотом или движением прямо с не link-дороги на не link-дорогу, и при этом все остальные кандидаты в маневры ведут y link;
- добавлены интеграционные …
=> Turn generation improvements

routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp
После обновления карт до 2018.02.09 поправил routing integration tests.
BelarusBobruisk50LetVlksmToArena - изменилась геометрия карты, но маршрут прокладывает корректный по прежнему:
MoscowToSVOAirport - в карте допущена ошибка. Не большой кусок двусторонней дороги сделан односторонним:
Карту я поправил: https://www.openstreetmap.org/changeset/56686302
А тест пока закомментировал и оставил TODO на раскомметирование после пересборки карт. Мне важно, чтоб интеграционные тесты проходили.
@rokuz @mpimenov PTAL
=> Fixing routing integration tests for 18.02.09

storage/storage.cpp
Solve bug in gcc-6. More info:
https://stackoverflow.com/questions/32097759/calling-this-member-function-from-generic-lambda-clang-vs-gcc/32098850#32098850
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67274
=> [gcc] Fix GCC-6 build bug

map/cloud.cpp, map/cloud.hpp
Если при загрузке в облако KMZ файл модифицировался, то на сервер мог уйти битый файл. Теперь перед отправкой мы считается контрольную сумму, делаем копию файла, считаем контрольную сумму скопированного файла и продолжаем только в случае, если суммы совпадают
=> Fixed uploading KMZ files to the cloud

routing/routing_integration_tests/turn_test.cpp, routing/turns_generator.cpp
Около 3 лет назад был написан фильтр под обработки маневров, который удалял все плавные маневры при условии, что названия улиц на сегментах маршрута вокруг данного маневра не сильно отличаются. Эта необходимость была связана прежде всего с тем, что при движении по МКАД генерировалось примерно один маневр на километр. 
Это был быстры фикс. Сейчас реализован правильный механизм: если угол маневра плавный, маршрут следует с не link дороги на не link дорогу, а остальные кандидаты link дороги, то маневр генерировать не надо.
Фильтр указанный выше нужно удалить, поскольку он приводит к ряду не правильных маневров:
https://jira.mail.ru/browse/MAPSME-6815
https://jira.mail.ru/browse/MAPSME-6890
Разумеется данное изменение влияет на интеграционные тесты. Но в лучшую сторону: …
=> Removing filtering turns if the route goes from one segment to another with almost the same name.

android/src/com/mapswithme/maps/routing/RoutingInfo.java, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm, routing/turns_tts_text.cpp
Пока не реализован UI по оповещению о выходах с магистрали, будут использованы оповещение о плавных поворотах.
Вместо выход направо - плавный поворот направо;
Вместо выход налево - плавный поворот налево;
@tatiana-kondakova @VladiMihaylenko @alexzatsepin PTAL
=> Using slight turn notification instead of exits from highway.

3party/jansson/myjansson.hpp, generator/CMakeLists.txt, generator/extract_addr/CMakeLists.txt, generator/extract_addr/extract_addr.cpp
Раз другой компонент геокодера использует промежуточные файлы `*.mwm.tmp` для вытаскивания геометрии, я переписал выгрузку адресных точек тоже на эти файлы.
Помимо самих адресов, скрипт выгружает POI без адресов. Некоторым из них повезёт оказаться внутри зданий и получить-таки адреса.
=> [geocoder] Extract addresses tool

coding/internal/xmlparser.hpp, map/api_mark_point.cpp, map/bookmark.cpp
Удалены/изменены ворнинги, которые лились в лог во всех режимах, что на больших файлах очень сильно замедляло парсинг KML
=> Removed warnings from KML parser

android/jni/com/mapswithme/core/jni_helper.cpp, android/jni/com/mapswithme/core/jni_helper.hpp, android/jni/com/mapswithme/util/NetworkPolicy.cpp, android/multidex-config.txt
Почему-то на Nexus 5 (девайсе @bykoianko )  jni::GetGlobalClassRef(env, "com/mapswithme/util/NetworkPolicy") стабильно возвращал null. Только после переноса инициализации класса в onLoad в jni-helper проблема ушла. Но почему она была пока выяснить не удалось. П
=> [android] Fixed network policy class initialization in JNI on nexus 5

tracking/reporter.cpp
исправила выделение циклического буфера -- resize делает не то что надо, он и размер и текущую позицию устанавливает в size, а нам нужно чтобы буфер был пустым, но с заданной capacity
=> [tracking] Fix circular buffer allocation

map/routing_manager.cpp, routing/base/followed_polyline.cpp, routing/base/followed_polyline.hpp, routing/route.cpp, routing/route.hpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/routing_session_test.cpp
В PR https://github.com/mapsme/omim/pull/8216 @tatiana-kondakova обратила внимание на то, что RoutingSession::m_route защищен не всегда при помощи RoutingSession::m_routingSessionMutex.
Действительно m_route защищен почти всегда в RoutingSession, но иногда это сразу не видно, поскольку защищены вызывающие методы. Например, RoutingManager вызывает RoutingSession::SetReadyCallbacks(..) для установки колбеков buildReadyCallback и rebuildReadyCallback. На время вызовов этих колбеков берется RoutingSession::m_routingSessionMutex.
Единственным местом, где защита нарушалось был вызов RoutingManager::InsertRoute() из RoutingManager::SetDrapeEngine(). Метод shared_ptr<Route> RoutingSession::GetRoute() обеспечивал потоко-небезопасный доступ к RoutingSession::m_route. Притом в данном случае …
=> m_route protection in RoutingSession.

routing/routing_integration_tests/turn_test.cpp
Поправил routing_integration_test: RussiaMoscowTTKToNMaslovkaTest
В данной ситуации второй маневр корректен, поскольку это развилка двух дорог соседних highway class-ов.
highway:unclassified и highway:service
@tatiana-kondakova PTAL
=> Routing integration test RussiaMoscowTTKToNMaslovkaTest fixing.

feature_list/feature_list.cpp, storage/storage.cpp, tools/python/local_ads/mwm_to_csv_4localads.py
Накопившиеся правки по двум скриптам, которые я давно использую в продакшене:
* Убрал вываливание бессмысленного эксепшна в `storage.cpp`.
* Досыпал типов в скрипт выгрузки маппингов для localads, файл на 5% больше.
* Четыре новых атрибута для фида тринета: wikipedia, floor, fee, atm.
* Новые идентификаторы для фида тринета основываются на osm id, а не на хэше из координат и названия.
=> Update feature_list and mwm_to_localads scripts

routing/routing_integration_tests/turn_test.cpp, routing/turns_generator.cpp
Не столь давно был починен интеграционный тест RussiaMoscowTTKToNMaslovkaTest в PR https://github.com/mapsme/omim/pull/8307. В действительности данный маневр (двигайтесь прямо) был бы не совсем уместен в данном случае, если взглянуть на панорамы.
В этом PR сделано следующее. Если HighwayClass дороги, по которой проходит маршрут, больше чем HighwayClass прочих возможных маневров. И маневр, который образует маршрут в данной точке бифуркации плавный, то удаляем данный маневр.
Это изменило 2 интеграционных теста в лучшую сторону:
@tatiana-kondakova @mpimenov PTAL
=> Removing more slight turns in case if other roads has less highway class.

indexer/ftypes_matcher.cpp, routing/routing_integration_tests/route_test.cpp
Корректная прокладка маршрутов вдоль пирсов. 
Ранее дороги с тегом "man_made", "pier" не были добавлены в классификатор HighwayClass, что приводило к срабатывание ASSERT в дебаг версии.
https://jira.mail.ru/browse/MAPSME-7142
@tatiana-kondakova @mpimenov PTAL
=> Routes along piers.

generator/transit_generator.cpp, transit/transit_graph_data.cpp, transit/transit_graph_data.hpp, transit/transit_tests/transit_graph_test.cpp, transit/transit_tests/transit_test.cpp, transit/transit_types.hpp
Ранее при генерации секций связанных с общественным транспортом использовался следующий подход:
- на вход подавался json с графом общественного транспорта;
- данный json загружался в GraphData;
- и если в нем оказывались не уникальные элементы, или не отсортированные таблицы, или не валидные элементы, то генератор прекращал свою работу и говорил, что граф не валиден.
- требовалось отдельное исследование, чтоб понять, что именно в графе не так.
Теперь, в случае проблем с графом, генератор остановится и выдаст достаточно информации, чтоб поправить ошибку:
- в какой таблице произошла проблема;
- какой элемент не уникален;
- какой элемент не валиден;
@Zverik @tatiana-yan @darina PTAL
=> Detailed diagnostic information for transit section building.

data/styles/clear/include/Basemap.mapcss, data/styles/clear/include/Basemap_label.mapcss, data/styles/clear/include/Icons.mapcss, data/styles/clear/include/Roads.mapcss, data/styles/clear/include/Roads_label.mapcss, data/styles/clear/include/defaults_new.mapcss, data/styles/vehicle/include/Basemap.mapcss, data/styles/vehicle/include/Basemap_label.mapcss, data/styles/vehicle/include/Icons.mapcss, data/styles/vehicle/include/Roads.mapcss, data/styles/vehicle/include/Roads_label.mapcss, data/styles/vehicle/include/defaults_new.mapcss
I'm currently implementing a map renderer / MapCSS parser, and had a few minor issues with parsing Maps.ME stylesheets. Rather than adding workarounds to the parser, I thought it might be a good idea to fix at least those stylesheet fragments that clearly deviate from [the specification](https://wiki.openstreetmap.org/wiki/MapCSS/0.2).
This includes:
* missing commas between selectors (`line[highway=track] line[highway=raceway]` → `line[highway=track], line[highway=raceway]`);
* duplicate semicolons in rules (`;;` → `;`);
* missing semicolons after the last rule (`{text-position: center}` → `{text-position: center;}`);
* abruptly terminating rules (`{icon-image: fuel-xl.svg;font-size: 14.5;text:}` → `{icon-image: fuel-xl.svg;font-size: 14.5;}`).
IMO these changes seem to improve …
=> Try to fix MapCSS syntax where appropriate

tools/python/mwm_downloader.py
Little python 3 script to download mwm files from `direct.mapswithme.com`.
Needed for my CI tasks. For example to prepare environment before `routing_integration_tests`.
**Usage:**
Download all latest maps in `data/{maps_version}`
```
tools/python/mwm_downloader.py 
Start downloading maps with 8 threads
[--------------------] 0% 4/1152
```
Download 180126 version of Armenia.mwm and Albania.mwm in directory `foo` with 2 threads.
```
tools/python/mwm_downloader.py -v 180126 -m Armenia Albania -f foo -t 2
Start downloading maps with 2 threads
[####################] 100% 2/2
Finished in 2 s.
```
=> [python] Mwm downloader script

editor/editor_config.cpp, editor/editor_tests/editor_config_test.cpp
Оказалось, у нас нельзя изменить название церкви, потому что большинство церквей в данных занесены под длинными типами вида `amenity-place_of_worship-christian` (с религией), а поля в редакторе указаны только для общего `amenity-place_of_worship`. Не было наследования. То же касается станций метро или туристических офисов, например. В этом пул-реквесте я добавляю наследование.
Fixes #7969.
=> [editor] Inherit editing properties for long types

data/categories.txt
У нас критикал в минорку: неправильно назвали категорию. MAPSME-7005.
=> [strings] Rename Luggage Hero to Luggage Storage → r8.1

routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/turn_test.cpp
После обновления карты до 16.03.18 сломались routing integration tests
http://angola.mapsme.mail.msk:8080/job/RoutingIntegration/100/testReport/
Данный PR чинит их.
=> Routing integration test fixing for map 18.03.16

routing/cross_mwm_connector.hpp, routing/index_graph_starter.cpp, routing/route_weight.cpp, routing/route_weight.hpp
Поля BidirectionalStepContext::bestDistance и BidirectionalStepContext::parent (Context::m_distanceMap и Context::m_parents) занимают около 30% памяти при прокладке маршрута. При прокладке пешего маршрута Москва-Великие Луки каждое из них содержит порядка 3 миллионов значений в пике. Т.е. структура BidirectionalStepContext занимает 
3*10^6*(12 + 24 + 12 + 12) = 180MB.
Размер Segment = 12 байт,
Размер Weight = 24 байта.
Данный PR уменьшает размер Weight до 16-ти байт. Т.е. при прокладке пешего маршрута Москва-Великие Луки экономится 24MB.
К сожалению, я не смог уменьшить размер RouteWeight в двое с 24 байт до 12-ти, поскольку, для это нужно так же сделать поле RouteWeight::m_weight типа float. А если это сделать, то на интеграционном тесте GermanyToTallinCrossMwmRoute нарушится инвариант в …
=> Reducing RoutingWeight size from 24 bytes to 16 bytes.

qt/CMakeLists.txt, qt/qt_common/CMakeLists.txt
Fix for cmake version 3.10 and higher. ([More info](https://cmake.org/cmake/help/git-stage/policy/CMP0071.html))
=> [cmake] Fix CMP0071 policy

storage/storage.cpp
We used to use the countryId which is stored in queuedCountry. But queuedCountry was stored by a reference and sometimes it could be removed from the queue so reference became dangling. Using a copy of the countryId must be more safety.
=> Using saved countryId instead of reference.

generator/generator_tool/generator_tool.cpp, generator/locality_sorter.cpp, generator/locality_sorter.hpp
Сейчас в индекс для серверного обратного геокодера добавляются только здания и POI, которые имеют адрес.
Но задача изменилась и нужно добавлять ещё ряд POI из списка. Этот PR содержит доработку, которая вычитывает список интересующих POI (имеет формат по одной записи на строку, первым идёт encoded osm id, а дальше что-то, что используется на serverside) и включает их индексирование.
=> [geocoder] Add option to index nodes without address.

base/base_tests/levenshtein_dfa_test.cpp, base/levenshtein_dfa.cpp, base/levenshtein_dfa.hpp, search/search_integration_tests/processor_test.cpp, search/utils.cpp
Данный PR разрешает опечатки в первых буквах.
Посмотрела на производительность при помощи `features_collector_tool`:
было:
```
real    9m30.546s
user    3m35.131s
sys     6m1.028s
```
стало на 5% медленнее:
```
real    10m3.026s
user    4m1.396s
sys     6m9.829s
```
посмотрела на запросы из выборки, которую мы сейчас размечаем, из 1000 запросов есть видимые улучшения на следующих:
```
иосква (москва)
юольшой (большой)
чолнечный (солнечный)
Жмариуполь (мариуполь)
AvOttekatu (avenue Ottekatu)
сгус (село гусаровское)
улваршавская (ул варшавская)
pgrunwaldzka (grunwaldzka)
```
и еще 3-5 потенциальных улучшений -- слова где есть опечатки в первых буквах, но дальше другие проблемы -- опечаток слишком много или на улице нет нужного номера дома, а неполный поиск пока не включен.
=> [search] Allow first letter misprint
