mapsme/omim

- android/gradle.properties
- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
https://jira.mail.ru/browse/MAPSME-9853
> Mapsme 9853 single tap on pp

- iphone/Maps/UI/Search/Tabs/SearchTabViewController.swift
https://jira.mail.ru/browse/MAPSME-9451
> [iOS] fix category search localization

- iphone/Maps/UI/Settings/MWMPowerManagmentViewController.mm
- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
- iphone/Maps/UI/Storyboard/Settings.storyboard
https://jira.mail.ru/browse/MAPSME-9858
> [iOS] fix power management settings localization

- android/src/com/mapswithme/maps/purchase/PurchaseUtils.java
https://jira.mail.ru/browse/MAPSME-9859
> [android] Fixed float price calculation

- android/src/com/mapswithme/maps/ugc/routes/EditCategoryNameFragment.java
https://jira.mail.ru/browse/MAPSME-9856
> [android] Change res ids

- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-9868
> [android] Added network policy checking for hotel views displaying

- android/src/com/mapswithme/maps/bookmarks/data/BookmarkCategory.java
https://jira.mail.ru/browse/MAPSME-9702
> [android] Change res id

- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
https://jira.mail.ru/browse/MAPSME-9865
> [iOS] minor localization fix

- android/assets/categories_brands.txt
https://jira.mail.ru/browse/MAPSME-9845
> [android] Added symlink to categories_brands.txt to fix crash in search

- android/src/com/mapswithme/maps/bookmarks/data/BookmarkCategory.java
- android/src/com/mapswithme/maps/ugc/routes/BaseEditUserBookmarkCategoryFragment.java
- android/src/com/mapswithme/maps/ugc/routes/EditCategoryDescriptionFragment.java
- android/src/com/mapswithme/maps/ugc/routes/EditCategoryNameFragment.java
https://jira.mail.ru/browse/MAPSME-9856
> Mapsme 9856

- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
https://jira.mail.ru/browse/MAPSME-9853
> [android] Fixed place page restoring screen rotation

- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
- iphone/Maps/Bookmarks/Categories/Sharing/UploadActionCell.swift
https://jira.mail.ru/browse/MAPSME-9871
> [iOS] change text in direct link cell if list in public

- android/src/com/mapswithme/maps/widget/WheelProgressView.java
https://jira.mail.ru/browse/MAPSME-9841
> [android] Changed making tint drawable way

- routing/CMakeLists.txt
- routing/route.hpp
- routing/routing_options.cpp
- routing/routing_options.hpp
- xcode/routing/routing.xcodeproj/project.pbxproj
нужен интерфейс для Даши, чтобы она могла делать UI
> [routing] add routing options for UI

- generator/feature_sorter.cpp
cherry-pick https://github.com/mapsme/omim/pull/10464 to master
https://jira.mail.ru/browse/MAPSME-9705
@maksimandrianov PTAL
> Removing speed cameras from geometry index for Turkey, Switzerland, Macedonia and Cyprus.

- generator/feature_sorter.cpp
Данный PR исправляет ошибку и увеличивает эффективность https://github.com/mapsme/omim/pull/10464/
@maksimandrianov @gmoryes PTAL
> Bugfix for Removing speed cameras from geometry index for Turkey, Switzerland, Macedonia and Cyprus.

- android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
https://jira.mail.ru/browse/MAPSME-9895
> [android] Added uploading immediately after update btn click

- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
https://jira.mail.ru/browse/MAPSME-9893
> [android] Added discarding of banner ration on place page hidding

- storage/storage.cpp
Consider the following scenario.
1. Diffs for A and B are downloaded but not applied.
Currently it is possible because we do not delete a
diff whose application process was cancelled.
2. The update button is clicked for both A and B, adding
them both to the queue.
3. The cancel button is clicked for both A and B.
The cancellation of A sends a signal to the diff
manager and kicks the downloader to start applying B.
The diff manager receives the signal to cancel A and
resets the m_latestDiffRequest. Then, the cancel request
to B clears the queue but never reaches the diff manager
(because of the m_latestDiffRequest mismatch), and, once
the diff to B has been successfully applied, Storage cannot
remove B from queue because it has already been removed.
> [storage] Fixed a crash.

- android/res/layout/fragment_bookmark_category_restriction.xml
- android/src/com/mapswithme/maps/ugc/routes/BaseEditUserBookmarkCategoryFragment.java
https://jira.mail.ru/browse/MAPSME-9856
> [android] Fixed doubled hint

- tools/python/openlr/quality.py
Добавил статистику по сегментам, помеченным, как ignore в merge опцию для quality.py
> Adding statistics about ignored openlr segments to quality.py.

- iphone/Maps/Core/InappPurchase/Impl/BillingPendingTransaction.swift
https://jira.mail.ru/browse/MAPSME-9921
> [iOS] ignore pending transactions in .purchasing state on enter to catalog

- iphone/Maps/UI/Search/Filters/MWMSearchHotelsFilterViewController.mm
https://jira.mail.ru/browse/MAPSME-9920
> [iOS] set default check in/out dates in hotel filter

- iphone/Maps/Maps.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-9936
> [iOS] add missing file to project

- geocoder/index.cpp
Фикс случая: находить 'Аэропортовская 1-я' для '1-я Аэропортовская' (в данных)
> [geocoder] Add shuffle match

- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/util/sharing/MapObjectShareable.java
https://jira.mail.ru/browse/MAPSME-9944
> [android] share my position crash fix

- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
https://jira.mail.ru/browse/MAPSME-9951
> [iOS] "call" method implementation from the MWMActionBarProtocol  to fix the "unrecognized selector" crash.

- track_generator/CMakeLists.txt
- track_generator/pytrack_generator/CMakeLists.txt
- track_generator/pytrack_generator/bindings.cpp
- track_generator/pytrack_generator/pytrack_generator_test.py
> Track generator bindings.

- iphone/Maps/Classes/Components/ExpandableReviewView/ExpandableReviewView.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/MWMPPPreviewLayoutHelper.mm
+ tweak for an empty review text
https://www.fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/5c86501ff8b88c2963b40210?time=last-seven-days
> [ios] This fix should reduce an amount of crashes for UITableView.update()

- docs/CONTRIBUTING.md
This pull request adds missing directory descriptions to [CONTRIBUTING.md](https://github.com/mapsme/omim/blob/master/docs/CONTRIBUTING.md). Also,  descriptions are removed of directories no longer existing in the root of the project.
While I tried to keep the descriptions descriptive and short, it could be that I missed the true purpose of some directories. Also, if I misplaced a directory in `Core` or `Other`, please let me know!
I think this will help new contributors to the project a great deal.
The CLA is signed.
> [docs] Update directories in CONTRIBUTING.md

- openlr/openlr_match_quality/openlr_assessment_tool/map_widget.cpp
- qt/draw_widget.cpp
- qt/draw_widget.hpp
- qt/qt_common/map_widget.cpp
- qt/qt_common/map_widget.hpp
Данный PR обеспечивает возможность осуществить новый тип разметки при помощи openlr_assessment_tool. Он позволяет понять какие хар-ки дорог openlr отображаются хар-ки дорог osm и сделать соответствующую разметку. Если раньше мы размечали преимущественно геометрию, то теперь размечаем и многочисленные св-ва.
Технически, он позволяет увидеть в openlr_assessment_tool osm таги.
> Displaying in openlr_assessment_tool features tags.

- android/src/com/mapswithme/maps/ugc/routes/SendLinkPlaceholderFragment.java
https://jira.mail.ru/browse/MAPSME-9899
> [android] Change dialog strings res

- map/user.cpp
- map/user.hpp
https://jira.mail.ru/browse/MAPSME-9786
> Fixed reset user-bound properties on authentication losing

- routing/geometry.cpp
- routing/geometry.hpp
- routing/index_graph.cpp
- routing/index_graph.hpp
- routing/index_graph_loader.cpp
- routing/index_graph_loader.hpp
- routing/index_graph_starter.cpp
- routing/index_graph_starter.hpp
- routing/index_graph_starter_joints.cpp
- routing/index_graph_starter_joints.hpp
- routing/index_router.cpp
- routing/online_absent_fetcher.hpp
- routing/route.hpp
- routing/routing_options.cpp
- routing/routing_options.hpp
- routing/routing_tests/CMakeLists.txt
- routing/routing_tests/routing_options_tests.cpp
- routing/single_vehicle_world_graph.cpp
- routing/single_vehicle_world_graph.hpp
- routing/turns_notification_manager.cpp
- routing/world_graph.cpp
- routing/world_graph.hpp
- xcode/routing/routing.xcodeproj/project.pbxproj
https://confluence.mail.ru/display/MAPSME/Routing+with+avoiding+different+types+of+roads
Here list of useful files, mostly without temporary changes
1) routing/geometry.cpp
2) routing/geometry.hpp
3) routing/index_graph.cpp
4) routing/index_graph.hpp
5) routing/index_graph_starter.cpp
6) routing/index_graph_starter.hpp
7) routing/index_graph_starter_joints.cpp
8) routing/index_graph_starter_joints.hpp
9) routing/index_router.cpp
> [routing] routing options, core implementation 

- android/src/com/mapswithme/maps/downloader/BottomPanel.java
Reduced the complexity of update() from 22 to 18. getAdapter is a function that returns a NonNull adapter. This means that the `!= null` check is not needed.
Also, one duplicate line was removed outside the if-else. The state does not seem to be affected by any other lines and thus could be reduced to one single assignment.
> [android] Refactored BottomPanel update

- android/src/com/mapswithme/maps/auth/Constants.java
https://jira.mail.ru/browse/MAPSME-9976
> [android] Deleted user_friends scope

- iphone/Maps/UI/Search/Tabs/HistoryTab/SearchHistoryViewController.xib
https://jira.mail.ru/browse/MAPSME-9946
> [iOS] I just turned off the userInteractionEnabled flag for the "No Results View"

- map/framework.cpp
Если фича - страна, то PP не во всех ситуациях был правильным (такой из которого можно скачать страну), так как проверка на то, что выделенный объект это страна проводилась в методе FillFeatureInfo(FeatureID const & fid, place_page::Info & info), а не в более глубинном FillInfoFromFeatureType.
Кроме того, исправлен баг при долгом тапе (или переходе к выделению через поиск), когда FillPointInfo геометрически не находила фичу (показывала "Неизвестное место"), хотя фича была явно выставлена через TapInfo
> Fixed country-features selection

- android/res/xml/prefs_main.xml
https://jira.mail.ru/browse/MAPSME-7395
> [android] Added summary for enable logging setting

- editor/editor_tests/osm_editor_test.cpp
- generator/generator_tests/descriptions_section_builder_tests.cpp
- generator/generator_tests_support/test_feature.cpp
- generator/generator_tests_support/test_feature.hpp
- search/reverse_geocoder.cpp
- search/reverse_geocoder.hpp
- search/search_integration_tests/processor_test.cpp
- search/search_integration_tests/ranker_test.cpp
- search/search_integration_tests/smoke_test.cpp
Черри-пик https://github.com/mapsme/omim/pull/10528 и тесты
>  [search] Fix streets matching for generator

- iphone/Maps/UI/Search/Tabs/CategoriesTab/SearchCategoriesViewController.swift
- iphone/Maps/UI/Search/Tabs/HistoryTab/SearchHistoryViewController.swift
https://jira.mail.ru/browse/MAPSME-9981
> [iOS] Added appropriate keyboardDismissMode for the search tabs

- drape/glyph_manager.cpp
https://jira.mail.ru/browse/MAPSME-976
https://jira.mail.ru/browse/MAPSME-3066
> [drape] Not render text if it contains symbols from unsupported unicode groups

- xcode/common.xcconfig
> [iOS] fix build architectures

- generator/world_map_generator.hpp
Фикс падения сборки world генератором, собранным в дебаге.
ASSERT FAILED
generator/feature_builder.cpp:406
CHECK(fb == *this)
> [generator] Fixed converting to point.

- iphone/Maps/UI/Search/Tabs/CategoriesTab/SearchCategoriesViewController.swift
- iphone/Maps/UI/Search/Tabs/HistoryTab/SearchHistoryViewController.swift
- iphone/Maps/UI/Search/Tabs/HistoryTab/SearchHistoryViewController.xib
- platform/http_session_manager.mm
- xcode/common.xcconfig
Cherry-pick iOS related commits to master
> Release90 to master

- search/search_integration_tests/utils_test.cpp
- search/utils.cpp
- search/utils.hpp
Дальше можно по желанию протащить как статический метод в SearchApi, не понимаю будет ли от этого вызывающему коду лучше.
> [search] Add IsCategorialRequestFuzzy method.

- indexer/road_shields_parser.cpp
https://jira.mail.ru/browse/MAPSME-4103
https://jira.mail.ru/browse/MAPSME-4107
> Added road shields special visualization for Malaysia and Mexico

- map/framework.cpp
- map/framework.hpp
> [map] no need to migrate UGC API

- routing/routing_tests/astar_router_test.cpp
- routing/routing_tests/routing_algorithm.cpp
- routing/routing_tests/routing_algorithm.hpp
Убрал лишний интерфейс из тестов
> [routing] Remove useless code from routing_tests

- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-9999
> [booking] the dates are injected into More and More reviews buttons.

- android/jni/com/mapswithme/maps/LightFramework.cpp
- iphone/Maps/Core/Notifications/LocalNotificationManager.mm
- map/CMakeLists.txt
- map/framework.cpp
- map/framework.hpp
- map/framework_light.cpp
- map/framework_light.hpp
- map/framework_light_delegate.hpp
- map/notifications/notification_manager.cpp
- map/notifications/notification_manager.hpp
https://jira.mail.ru/browse/MAPSME-9942
> [lightweight] Delegate is added into lightweight framework.

- android/build.gradle
https://jira.mail.ru/browse/MAPSME-10057
> [android] Change fb sdk version

- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-10031
> Redundant updating of visible viewport fixed.

- routing/transit_world_graph.cpp
- routing/transit_world_graph.hpp
- routing/world_graph.cpp
- routing/world_graph.hpp
Сделал некоторые методы non-pure virtual, чтобы у них была реализация по умолчанию и не приходилось в код вставлять заглушки
> [routing] make some methods non-pure virtual

- android/build.gradle
> Mapsme 10057 cherry pick

- android/jni/com/mapswithme/maps/LightFramework.cpp
- iphone/Maps/Core/Notifications/LocalNotificationManager.mm
- map/CMakeLists.txt
- map/framework.cpp
- map/framework.hpp
- map/framework_light.cpp
- map/framework_light.hpp
- map/framework_light_delegate.hpp
- map/notifications/notification_manager.cpp
- map/notifications/notification_manager.hpp
cp for https://github.com/mapsme/omim/pull/10572
> [cherry-pick][lightweight] Delegate is added into lightweight framework

- drape/overlay_tree.cpp
- drape_frontend/drape_frontend_tests/user_event_stream_tests.cpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/frontend_renderer.hpp
- drape_frontend/user_event_stream.cpp
- drape_frontend/user_event_stream.hpp
https://jira.mail.ru/browse/MAPSME-9819
> Scrolling of map after object selection fixed.

- iphone/Maps/UI/Search/MWMSearchManager.mm
https://jira.mail.ru/browse/MAPSME-10049
> [iOS] Show keyboard when user opens search

- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/main.mm
> [iOS] fix iOS release build

- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkPaymentDataParser.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadManager.java
- android/src/com/mapswithme/maps/bookmarks/DefaultBookmarkDownloadController.java
- android/src/com/mapswithme/maps/bookmarks/SystemDownloadCompletedService.java
- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bridging-Header.h
- map/bookmark_catalog.cpp
- map/bookmark_catalog.hpp
- map/bookmark_manager.cpp
https://jira.mail.ru/browse/MAPSME-10026
> [android][ios]statistic events are added for Guides

- drape_frontend/user_mark_shapes.cpp
https://jira.mail.ru/browse/MAPSME-9879
> [drape] Fixed search mark rendering

- map/bookmark_catalog.cpp
- map/bookmark_catalog.hpp
- map/bookmark_manager.cpp
- map/framework.cpp
- map/purchase.cpp
- map/purchase.hpp
2 наших сервиса при получении ошибки аутенфикации не разлогинивали всю систему. Теперь все сервисы, получив 403, будут разлогинивать пользователя
https://jira.mail.ru/browse/MAPSME-10076
> Fixed auth error processing

- map/booking_availability_filter.cpp
- map/booking_availability_filter.hpp
- map/booking_filter.hpp
- map/booking_filter_params.hpp
- map/booking_filter_processor.cpp
- map/booking_filter_processor.hpp
- map/map_tests/booking_filter_test.cpp
- partners_api/booking_api.hpp
часть https://jira.mail.ru/browse/MAPSME-9623
> [booking] booking filter is adapted to work with raw feature ids.

- generator/generator_tests/regions_tests.cpp
- generator/place_node.hpp
- generator/regions/node.cpp
- generator/regions/node.hpp
- generator/regions/regions.cpp
- generator/regions/regions_builder.cpp
- generator/regions/regions_builder.hpp
- generator/regions/to_string_policy.cpp
- generator/regions/to_string_policy.hpp
Экономия в памяти и скорости: построчная запись KV вместо формирования и запись всего списка строк.
Новый процесс формирования KV будет удобен и для сл. PR: для перегенерации mwm с новой геометрии для фич.
> [generator:regions] Optimize regions KV-file write

- qt/build_style/build_skins.cpp
> [qt] fix warning

- android/src/com/mapswithme/maps/MwmActivity.java
- iphone/Maps/Classes/MapsAppDelegate.mm
https://jira.mail.ru/browse/MAPSME-10177
> [deep links] fix for search on map deep link without cll parameter

- data/countries.txt
- data/external_resources.txt
Карты на архивной ноде. Будет работать все, кроме пробок. 
@bykoianko  упали тесты:
bicycle_route_test.cpp::RussiaKerchStraitFerryRoute
route_test.cpp::MoscowToSVOAirport                                                                          
route_test.cpp::RussiaFerryToCrimea 
turn_test.cpp::RussiaTiinskTest
> [data] Planet 190329 

- android/src/com/mapswithme/maps/MwmActivity.java
- iphone/Maps/Classes/MapsAppDelegate.mm
cp for https://github.com/mapsme/omim/pull/10644
> [cherry-pick][deep links] fix for search on map deep link without cll parameter

- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkPaymentDataParser.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadManager.java
- android/src/com/mapswithme/maps/bookmarks/DefaultBookmarkDownloadController.java
- android/src/com/mapswithme/maps/bookmarks/SystemDownloadCompletedService.java
- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bridging-Header.h
- map/bookmark_catalog.cpp
- map/bookmark_catalog.hpp
- map/bookmark_manager.cpp
cp for https://github.com/mapsme/omim/pull/10597
> [cherry-pick][android][ios]statistic events are added for Guides + review fixes

- android/src/com/mapswithme/maps/bookmarks/BookmarkPaymentDataParser.java
https://jira.mail.ru/browse/MAPSME-10022
> [android] Added log for empty billing parameters.

- drape_frontend/drape_engine.cpp
- drape_frontend/drape_engine.hpp
- drape_frontend/drape_hints.hpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/frontend_renderer.hpp
- drape_frontend/message.hpp
- drape_frontend/message_subclasses.hpp
- drape_frontend/my_position_controller.cpp
- map/framework.cpp
- map/framework.hpp
- openlr/openlr_match_quality/openlr_assessment_tool/map_widget.cpp
- qt/CMakeLists.txt
- qt/draw_widget.cpp
- qt/draw_widget.hpp
- qt/main.cpp
- qt/mainwindow.cpp
- qt/mainwindow.hpp
- qt/qt_common/map_widget.cpp
- qt/qt_common/map_widget.hpp
- qt/screenshoter.cpp
- qt/screenshoter.hpp
- search/search_quality/assessment_tool/main_view.cpp
https://jira.mail.ru/browse/MAPSME-10173
https://confluence.mail.ru/display/MAPSME/Admin#Admin-Генерациякартинок-карт
> New mode of Qt app to take screenshots of bookmarks.

- tools/python/booking_hotels.py
- tools/unix/generate_planet.sh
https://jira.mail.ru/browse/MAPSME-10166
> [generator] Supported new booking api.

- android/src/com/mapswithme/maps/MapFragment.java
- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/maps/SplashActivity.java
- android/src/com/mapswithme/maps/news/WelcomeDialogFragment.java
[android] Removed static field about first start and put it in application
https://jira.mail.ru/browse/MAPSME-10234
> [android] Moved welcome/policy screen at the start of onboarding

- partners_api/rutaxi_api.cpp
https://jira.mail.ru/browse/MAPSME-10256
https://confluence.mail.ru/pages/viewpage.action?pageId=158666430
> Fixed Taxi Vezet link

- indexer/feature_data.cpp
https://jira.mail.ru/browse/MAPSME-10276
> [indexer] Leave the most important types in FeatureParams::FinishAddingTypes()

- drape_frontend/drape_engine.cpp
- drape_frontend/drape_engine.hpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/user_event_stream.cpp
- drape_frontend/user_event_stream.hpp
- map/framework.cpp
- map/framework.hpp
- map/routing_manager.cpp
https://jira.mail.ru/browse/MAPSME-10226
> [drape] Added visible viewport usage in set-rect methods

- partners_api/rutaxi_api.cpp
https://jira.mail.ru/browse/MAPSME-10297
> Fixed Taxi Vezet URL scheme

- 3party/jansson/myjansson.cpp
- 3party/jansson/myjansson.hpp
- generator/CMakeLists.txt
- generator/geo_objects/geo_objects.cpp
- generator/geo_objects/geo_objects_filter.cpp
- generator/geo_objects/geo_objects_filter.hpp
- generator/geo_objects/region_info_getter.cpp
- generator/geo_objects/region_info_getter.hpp
- generator/geo_objects/streets_builder.cpp
- generator/geo_objects/streets_builder.hpp
- generator/osm_element.cpp
- generator/osm_element.hpp
- generator/translator_geo_objects.cpp
Добавляются улицы в geo_objects.jsonl из OSM. В след. PR будут добавляться улицы и из адресов зданий.
> [generator:geo_objects] Generate streets for KV

- tools/python/booking/download_hotels.py
- tools/python/mwm/decode_id.py
- tools/python/mwm/dump_mwm.py
- tools/python/mwm/find_feature.py
- tools/python/mwm/ft2osm.py
- tools/python/mwm/mwm.py
- tools/python/mwm/mwm_feature_compare.py
- tools/python/post_generation/hierarchy_to_countries.py
- tools/python/post_generation/localads_mwm_to_csv.py
- tools/python/post_generation/requirements.txt
- tools/unix/generate_planet.sh
Избавление от грязных хаков:
```
sys.path.append(
os.path.join(
os.path.dirname(__file__), '..', 'mwm'
)
)
```
> [generator] Python projects refactoring.

- 3party/jansson/myjansson.hpp
- generator/geo_objects/region_info_getter.cpp
- generator/geo_objects/region_info_getter.hpp
Фикс определения locality/subregion для строений и улиц: проверка границ.
> [generator:geo_objects] Fix region find: border check

- android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/intent/Factory.java
https://jira.mail.ru/browse/MAPSME-10235
> Mapsme 10235 handle first launch by two deeplinks case

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/routing/RoutingController.java
- android/src/com/mapswithme/maps/settings/DrivingOptionsFragment.java
- android/src/com/mapswithme/maps/settings/RoadType.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-10281
> Mapsme 10281 paid road stats

- map/place_page_info.cpp
https://jira.mail.ru/browse/MAPSME-10332
> [DNM][ads] the ads are disabled for route points.

- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogActivity.java
- android/src/com/mapswithme/maps/intent/Factory.java
- android/src/com/mapswithme/maps/news/IntroductionDialogFragment.java
- android/src/com/mapswithme/maps/news/IntroductionScreenFactory.java
- android/src/com/mapswithme/util/statistics/StatisticalNameProvider.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-10283
> Mapsme 10283 guides deeplink statistic

- android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-10324
> [android] Fixed switching of settings

- skin_generator/generator.cpp
- skin_generator/generator.hpp
- skin_generator/main.cpp
- tools/unix/generate_symbols.sh
Boost GIL больше не нужен, так как colorCorrection уже давно не актуально
> Get rid of boost/gil usage

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/news/IntroductionDialogFragment.java
- android/src/com/mapswithme/maps/news/IntroductionScreenFactory.java
- android/src/com/mapswithme/maps/tips/TipsApi.java
- android/src/com/mapswithme/maps/tips/TipsClickListener.java
- android/src/com/mapswithme/util/statistics/StatisticValueConverter.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-10220
> Mapsme 10220 tips tricks statistics

- partners_api/booking_api.cpp
https://jira.mail.ru/browse/MAPSME-10350
> [booking] link fix

- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMRoutePreview.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMiPadRoutePreview.xib
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMiPhoneRoutePreview.xib
https://jira.mail.ru/browse/MAPSME-10338
https://jira.mail.ru/browse/MAPSME-10339
> [iOS] Font and shadow fixes for the driving options

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/routing/RoutingController.java
https://jira.mail.ru/browse/MAPSME-10349
> [android] Restored intermediate points

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/routing/RoutingController.java
https://jira.mail.ru/browse/MAPSME-10321
> [android] Disabled DO view for bicycle route

- search/intermediate_result.hpp
- search/pre_ranker.cpp
- search/pre_ranking_info.cpp
- search/pre_ranking_info.hpp
- search/ranker.cpp
- search/ranking_info.cpp
- search/ranking_info.hpp
- search/search_quality/scoring_model.py
> [search] Heuristics for rating.

- android/src/com/mapswithme/maps/widget/menu/MainMenu.java
- android/src/com/mapswithme/util/Animations.java
https://jira.mail.ru/browse/MAPSME-10328
https://jira.mail.ru/browse/MAPSME-10094
Вернул обратно показ меню через Animations.java, который я удалил когда рефакторил PP. Когда показываешь меню без этой анимации, то вылезают вышеперечисленные баги. Почему так происходит - нет времени разбираться, пока просто откатил обратно.
> Mapsme 10328 ui bug in routing panel

- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
https://jira.mail.ru/browse/MAPSME-9130
> [android] Fixed stub catalog images

- generator/restriction_writer.cpp
забыли поддержать only_u_turn
было:
стало:
osm:
> [routing] Add new restriction

- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-10363
> [android] Fixed statistic values

- iphone/Maps/Categories/NSAttributedString+HTML.swift
- iphone/Maps/UI/PlacePage/PlacePageDescriptionViewController.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/DescriptionCell/MWMPlaceDescriptionCell.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/DescriptionCell/MWMPlaceDescriptionCell.xib
https://jira.mail.ru/browse/MAPSME-10097
> [iOS] attributes fixes for the place description

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
https://jira.mail.ru/browse/MAPSME-10192
> [iOS] Replaced close button for the Guides Catalogue

- generator/geo_objects/geo_objects.cpp
Рефакторинг FindHousePoi(), что бы проверял номер здания, как ожидается из имени метода.
> [generator:geo_objects] Refactor POI house searching

- android/res/layout/place_page_description_layout.xml
https://jira.mail.ru/browse/MAPSME-10096
> [android] Fixed wiki desc appearance

- android/res/values/arrays.xml
https://jira.mail.ru/browse/MAPSME-10383
> [android] Fixed whats new

- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.xib
https://jira.mail.ru/browse/MAPSME-10384
> [iOS] Replaced guide catalogue title

- iphone/Maps/UI/Welcome/WhatsNewController.swift
https://jira.mail.ru/browse/MAPSME-10382
> [iOS] Removed one of What's new 9.1 screens

- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
https://jira.mail.ru/browse/MAPSME-10221
https://jira.mail.ru/browse/MAPSME-10373
> [iOS] fixes for tips and tricks statistic

- data/countries.txt
- data/external_resources.txt
Карты на архивной ноде
Нужно запустить тесты
Если будет все ок, раскатим и карты и пробки на боевые
> [planet] New data from 19.04.2019(descriptions:22363, hotels:1842851)

- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- partners_api/booking_api.cpp
Сначала создал https://github.com/mapsme/omim/pull/10758 не в той ветке, заменил ветку, пришлось менять и pr.
Плюс закинул сюда фиксы 
https://jira.mail.ru/browse/MAPSME-10350
https://jira.mail.ru/browse/MAPSME-10370
@niakrise, fyi, ты заболела, а @burivuh срочно хочет регрессию, поэтому назначаю на @beloal
> [ios][booking] use single deep link when booking.com app is installed

- android/jni/com/mapswithme/maps/MapManager.cpp
- android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
- generator/mwm_diff/diff.cpp
- storage/diff_scheme/diff_manager.cpp
- storage/diff_scheme/diff_manager.hpp
- storage/diff_scheme/diff_types.hpp
- storage/storage.cpp
https://jira.mail.ru/browse/MAPSME-10217
@mpimenov FYI
> [storage][android] autoupdate displayed sizes fix

- data/countries.txt
- data/external_resources.txt
Карты на архивной ноде
Нужно запустить тесты
Если будет все ок, раскатим и карты и пробки на боевые
> [cherry-pick][planet] New data from 19.04.2019(descriptions:22363, hotels:1842851)

- android/AndroidManifest.xml
- android/res/layout/fragment_catalog_bookmark_categories.xml
- android/src/com/mapswithme/maps/bookmarks/BookmarksPageFactory.java
https://jira.mail.ru/browse/MAPSME-10386
> [android] Corrected string ids usage for guide's screens

- android/src/com/mapswithme/maps/routing/RoutingPlanController.java
https://jira.mail.ru/browse/MAPSME-10397
> [android] Restoring DO view

- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Core/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-10391
> [iOS] rebuild route after changing driving options

- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageProtocol.h
- iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.h
- iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMPlacePageActionBar.mm
https://jira.mail.ru/browse/MAPSME-10353
> [iOS] Localization fixes for the place page (tolls, ferries, etc.)

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Classes/DeepLinkHandler.swift
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- iphone/Maps/UI/Welcome/DeeplinkInfoViewController.swift
- iphone/Maps/UI/Welcome/WelcomePageController.swift
https://jira.mail.ru/browse/MAPSME-10406
https://jira.mail.ru/browse/MAPSME-10412
> [iOS] fix guides_page deeplink, fix some post-onboarding deeplinks

- iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-10410
> [iOS] fix crash when entering catalog

- drape_frontend/backend_renderer.cpp
- drape_frontend/drape_engine.cpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/message.cpp
- map/bookmark_helpers.cpp
- map/bookmark_helpers.hpp
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/framework.cpp
- qt/CMakeLists.txt
- qt/mainwindow.cpp
- qt/screenshoter.cpp
- qt/screenshoter.hpp
- tools/unix/build_omim.sh
* Wait graphics after user marks updating on BackendRenderer.
* Fix Qt dependencies for desktop app.
> [screenshots] Check viewport before taking a screenshot.

- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
https://jira.mail.ru/browse/MAPSME-9885
> [iOS] New flow for the public guide update

- iphone/Maps/Core/InappPurchase/Impl/BillingPendingTransaction.swift
https://jira.mail.ru/browse/MAPSME-9631
> [iOS] fix multiple pending transactions

- iphone/Maps/Classes/DeepLinkHandler.swift
https://jira.mail.ru/browse/MAPSME-10407
> [iOS] Do not show Tips and Tricks above the deeplink

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
https://jira.mail.ru/browse/MAPSME-10445
> [iOS] updated guides web view title

- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/intent/Factory.java
- iphone/Maps/Classes/DeepLinkHelper.mm
- iphone/Maps/Classes/MapViewController.mm
- map/framework.cpp
- map/framework.hpp
https://jira.mail.ru/browse/MAPSME-10227
> [deeplink][android][ios] fix for search in list deep link.

- iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.h
- iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm
- iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.h
- iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm
- iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.h
- iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm
- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
- iphone/Maps/Core/Framework/MWMFrameworkHelper.h
- iphone/Maps/Core/Framework/MWMFrameworkHelper.mm
- iphone/Maps/Core/Routing/MWMRouter.mm
- iphone/Maps/Core/Storage/MWMStorage.h
- iphone/Maps/Core/Storage/MWMStorage.mm
- iphone/Maps/UI/Autoupdate/MWMAutoupdateController.mm
- iphone/Maps/UI/Downloader/MWMBaseMapDownloaderViewController.mm
- iphone/Maps/UI/Migration/MWMMigrationViewController.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
https://jira.mail.ru/browse/MAPSME-10245
> [iOS] new onCancel callback for MWMStorage download/update actions

- android/res/values-fa/strings.xml
- data/categories.txt
- data/strings/types_strings.txt
- iphone/Maps/LocalizedStrings/fa.lproj/Localizable.strings
The original PR by the author (Sosha1996) is here:
https://github.com/mapsme/omim/pull/9639
The PR is rebased and the commits are squashed on the author's behalf.
Also, the corresponding translations are added to types_strings.txt too.
> [categories] Several Farsi translations.

- iphone/Maps/Core/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-10448
> [iOS] don't show "change driving options" on non-vehicle routes

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/routing/RoutingController.java
https://jira.mail.ru/browse/MAPSME-10444
> [android] Added vehicle route type checking during routing build error

- android/jni/com/mapswithme/vulkan/android_vulkan_context_factory.cpp
Судя по этому крэшу https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5cc965b2f8b88c2963baec16/sessions/latest и логу к нему возможен повторный вызов ResetSurface
> [vulkan] Fixed secondary surface reset

- android/jni/com/mapswithme/vulkan/android_vulkan_context_factory.cpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5ccb28e6f8b88c2963dc8100/sessions/latest
Оказалось, что это возможно на Android 7.0
> [vulkan] Added changing native window support

- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
https://jira.mail.ru/browse/MAPSME-10458
> [iOS] Night mode support for drivingOptionsCell

- android/src/com/mapswithme/maps/MapFragment.java
OnResume теперь не может вызываться до инициализации surface
> [android] Fixed onResume invocation in MapFragment

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
https://jira.mail.ru/browse/MAPSME-10465
> [iOS] nullify deeplink if the linlk has been processed

- generator/generator_tool/generator_tool.cpp
- generator/node_mixer.cpp
- generator/node_mixer.hpp
- generator/osm_source.cpp
- generator/translator_country.cpp
- generator/translator_country.hpp
- generator/translator_factory.hpp
osm only сборка - сборка без всех наших данных(партнерских и пользовательских) для "любителей модов"
> [generator] Preparing for generation 'osm only':  disable ads

- tools/python/post_generation/__main__.py
- tools/python/post_generation/hierarchy_to_countries.py
- tools/python/post_generation/localads_mwm_to_csv.py
- tools/unix/generate_planet.sh
Рефакторинг нужен для того что бы использовать код в других python проектах, а именно в https://github.com/mapsme/omim/pull/10699.
> [python] Refactored hierarchy_to_countries.py and localads_mwm_to_csv.py

- routing/index_graph_starter_joints.hpp
> [routing] add std::move in index_graph_starter_joints.hpp

- routing/index_graph_starter.cpp
> [routing] Adding a comment on multiplying by zero structure RouteWeight.

- drape/symbols_texture.cpp
- drape/symbols_texture.hpp
- drape/texture_manager.cpp
- drape/texture_manager.hpp
- drape/vulkan/vulkan_pipeline.cpp
- drape_frontend/backend_renderer.cpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/gui/compass.cpp
- drape_frontend/message.cpp
- drape_frontend/message.hpp
- drape_frontend/message_subclasses.hpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5cd278fdf8b88c2963569fd4?time=last-seven-days
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5cd407a7f8b88c296372d78c/sessions/5cd8f5b4026e00012a4d5efb3054ff17_DNE_0_v2?
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5cd52dbcf8b88c2963876673/sessions/latest
> Fixed rendering crashes

- routing/routing_consistency_tests/routing_consistency_tests.cpp
- routing/routing_integration_tests/bicycle_route_test.cpp
- routing/routing_integration_tests/bicycle_turn_test.cpp
- routing/routing_integration_tests/online_cross_tests.cpp
- routing/routing_integration_tests/pedestrian_route_test.cpp
- routing/routing_integration_tests/route_test.cpp
- routing/routing_integration_tests/routing_test_tools.cpp
- routing/routing_integration_tests/routing_test_tools.hpp
- routing/routing_integration_tests/speed_camera_notifications_tests.cpp
- routing/routing_integration_tests/street_names_test.cpp
- routing/routing_integration_tests/transit_route_test.cpp
- routing/routing_integration_tests/turn_test.cpp
мне нужно в другом PR передавать этот аргумент через функцию, соответственно нормально и просто я это сделать не могу, и непонятно зачем он вообще шаблонный
> [routing] Refact routing integr tests

- drape_frontend/frontend_renderer.cpp
- map/framework.cpp
- map/place_page_info.cpp
- map/place_page_info.hpp
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/5cd9237ff8b88c2963c805b2
> Fixed PP for road type mark in case of invalid featureId.

- iphone/Maps/Classes/DeepLinkHandler.swift
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/UI/Welcome/DeeplinkInfoViewController.swift
- iphone/Maps/UI/Welcome/WelcomePageController.swift
https://jira.mail.ru/browse/MAPSME-10480
https://jira.mail.ru/browse/MAPSME-10503
> [iOS] fix deeplink related errors

- routing/bicycle_directions.cpp
- routing/bicycle_directions.hpp
- routing/directions_engine.hpp
- routing/index_router.cpp
- routing/index_router.hpp
- routing/pedestrian_directions.hpp
После построения маршрута не удалялись карты в плоть до перезагрузки программы или вплоть до смены типа роутинга. Поправлено.
@darina @tatiana-yan PTAL
> [routing] Releasing map handles after route building.

- data/categories.txt
- indexer/categories_holder.cpp
- indexer/categories_holder.hpp
- indexer/indexer_tests/categories_test.cpp
Now that we have data/strings/types_strings.txt, there is
no need in the special syntax to mark the displayed name in categories.txt.
> [categories] Removed the '^' symbol.

- geocoder/geocoder.cpp
- geocoder/geocoder_tests/geocoder_tests.cpp
Фикс поиска улицы с числом в имени и с указанием синонима улицы в запросе поиска: "Россия, Москва, улица 1905 года". Если убрать одно из условий из запроса, то улица находится: "Россия, Москва, 1905 года"
> [geocoder] Fix search of street with number and street synonym together

- android/jni/com/mapswithme/maps/MapFragment.cpp
- android/src/com/mapswithme/maps/MapFragment.java
- android/src/com/mapswithme/maps/MapRenderingListener.java
- android/src/com/mapswithme/maps/MwmActivity.java
- drape_frontend/backend_renderer.cpp
- drape_frontend/backend_renderer.hpp
- drape_frontend/base_renderer.cpp
- drape_frontend/base_renderer.hpp
- drape_frontend/drape_engine.cpp
- drape_frontend/drape_engine.hpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/frontend_renderer.hpp
- map/framework.cpp
- map/framework.hpp
Сейчас Android оповещается после того, как рендеринг действительно закончил инициализацию и можно выполнять отложенные таски
> [drape] Fixed rendering initialization notification

- android/res/menu/menu_bookmark_catalog.xml
- android/res/menu/menu_top_bookmark_categories.xml
- android/src/com/mapswithme/maps/base/BaseToolbarActivity.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogActivity.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
https://jira.mail.ru/browse/MAPSME-10191
> [android] Changed behavior of catalog closing btn

- android/src/com/mapswithme/util/sharing/MapObjectShareable.java
https://jira.mail.ru/browse/MAPSME-10214
> [android] Removed 'sharing_call_action_look' usage

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/tips/TipsApi.java
- android/src/com/mapswithme/maps/tips/TipsClickListener.java
https://jira.mail.ru/browse/MAPSME-10500
> [android] Added validation of the first launch for Tips&Tricks

- routing/index_graph_starter_joints.hpp
- routing/restriction_loader.cpp
- routing/restriction_loader.hpp
- routing/routing_integration_tests/route_test.cpp
- routing/single_vehicle_world_graph.cpp
> [routing] fix restiction only convertation

- drape_frontend/drape_engine.cpp
- drape_frontend/drape_engine.hpp
- drape_frontend/drape_frontend_tests/user_event_stream_tests.cpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/scenario_manager.cpp
- drape_frontend/user_event_stream.cpp
- drape_frontend/user_event_stream.hpp
- map/framework.cpp
- map/framework.hpp
https://jira.mail.ru/browse/MAPSME-10547
> [drape] Rotate method added.

- openlr/decoded_path.hpp
- openlr/graph.cpp
- openlr/graph.hpp
- openlr/openlr_decoder.cpp
- openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.cpp
- openlr/router.cpp
- openlr/router.hpp
- openlr/score_types.hpp
- routing/bicycle_directions.cpp
- routing/bicycle_directions.hpp
- routing/index_graph_starter.cpp
- routing/index_graph_starter.hpp
- routing/index_road_graph.cpp
- routing/index_road_graph.hpp
- routing/index_router.cpp
- routing/road_graph.cpp
- routing/road_graph.hpp
- routing/route.hpp
- routing/routing_helpers.cpp
- routing/routing_tests/road_graph_nearest_edges_test.cpp
- routing/routing_tests/routing_algorithm.cpp
- routing/turns_generator.cpp
> [routing] push info about fake segments to routing manager

- iphone/Maps/UI/Search/Filters/MWMHotelParams.h
- iphone/Maps/UI/Search/Filters/MWMHotelParams.mm
- iphone/Maps/UI/Search/Filters/MWMSearchHotelsFilterViewController.mm
https://jira.mail.ru/browse/MAPSME-10453
> [iOS] Fixed the price filter for search hotel filters

- iphone/Maps/Classes/DeepLinkHandler.swift
https://jira.mail.ru/browse/MAPSME-10542
> [iOS] fix error when deffered deeplink flow launches before onboarding ends

- map/discovery/discovery_client_params.hpp
- map/discovery/discovery_manager.cpp
- map/discovery/discovery_manager.hpp
- partners_api/promo_api.cpp
- partners_api/promo_api.hpp
https://jira.mail.ru/browse/MAPSME-10613
fyi @alexzatsepin @niakrise
> [core] Inject promo api into discovery manager + do not show promo for same city after booking

- data/replaced_tags.txt
Замена неподдерживаемых тегов на близкие поддерживаемые.
> [generator] Add tag replacement rules.

- base/CMakeLists.txt
- base/base_tests/CMakeLists.txt
- base/base_tests/non_intersecting_intervals_tests.cpp
- base/non_intersecting_intervals.hpp
- routing/CMakeLists.txt
- routing/base/bfs.hpp
- routing/index_router.cpp
- routing/leaps_postprocessor.cpp
- routing/leaps_postprocessor.hpp
- routing/routing_quality/routing_quality_tests/CMakeLists.txt
- routing/routing_quality/routing_quality_tests/leaps_postprocessing_tests.cpp
- routing/routing_tests/CMakeLists.txt
- routing/routing_tests/astar_algorithm_test.cpp
- routing/routing_tests/bfs_tests.cpp
- routing/routing_tests/routing_algorithm.cpp
- routing/routing_tests/routing_algorithm.hpp
- xcode/base/base.xcodeproj/project.pbxproj
- xcode/routing/routing.xcodeproj/project.pbxproj
> [routing] Leaps postprocessing

- generator/statistics.cpp
- generator/statistics.hpp
Добавлен подсчет оюъектов с именами
> [generator] Added number of objects with name to statistics.

- data/countries.txt
- data/external_resources.txt
1  tests failed:
street_names_test.cpp::RussiaTulskayaToPaveletskayaStreetNamesTest
Some tests FAILED.
> [data] Planet 190517

- data/categories.txt
- search/model.cpp
тесты есть в ProcessorTest - TestCategories
для highway-ford нет стилей и он не попадает в данные и нет переводов в types-strings, но это тема отдельных реквестов
> [search] Add more types to TypesSkipper whitelist.

- geometry/latlon.hpp
- routing/bicycle_directions.cpp
- routing/index_graph_starter_joints.hpp
- routing/index_router.cpp
- routing/routing_integration_tests/CMakeLists.txt
- routing/routing_integration_tests/small_routes.cpp
- xcode/routing/routing.xcodeproj/project.pbxproj
на мастере сейчас 51 из 92 тестов в этом PR падают на CHECK в astar_algorithm.hpp
> [routing] Fix some crashes and bugs for small routes

- data/countries.txt
- data/countries_synonyms.csv
- data/external_resources.txt
черри-пик новых данных с release-91 с перегенерацией countries.txt  кодом из мастера
```
diff data/countries.txt ~/data/190517/countries.txt 
246,249d245
<    "country_name_synonyms": [
<     "Aruba",
<     "Curacao"
<    ],
366,368d361
<    "country_name_synonyms": [
<     "Sint Maarten"
<    ],
1008,1010d1000
<    "country_name_synonyms": [
<     "Belaru\u015b"
<    ],
2618,2620d2607
<    "country_name_synonyms": [
<     "Cabo Verde"
<    ],
2802,2804d2788
<    "country_name_synonyms": [
<     "Republic of the Congo"
<    ],
2810,2812d2793
<    "country_name_synonyms": [
<     "Democratic Republic of the Congo"
<    ],
2962,2964d2942
<    "country_name_synonyms": [
<     "Czechia"
<    ],
3170,3173d3147
<    "country_name_synonyms": [
<     "C\u00f4te d'Ivoire",
<     "Ivory Coast"
< …
```
> [planet] New data from 17.05.2019.

- tracking/connection.cpp
Записываем информацию о реконнекте сокета в алоху при записи трека. 
Детали: https://confluence.mail.ru/display/MAPSME/Traffic+jam
Для проверки поставил рядом запись в лог и посмотрел, как вызывается на Android при наличии и отсутствии интернета.
> [traffic] Writing to aloha information about reconnect fact in case of problems with writing to the track socket.

- map/booking_availability_filter.cpp
> Warning fix in release.

- iphone/Maps/LocalizedStrings/en-GB.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/en.lproj/Localizable.strings
- iphone/Maps/UI/Ads/AdBanner.swift
- iphone/Maps/UI/PlacePage/MWMPlacePageData.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.h
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMiPhonePlacePageLayoutImpl.mm
- iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.xib
https://jira.mail.ru/browse/MAPSME-10630
> [iOS] New place page state (preview plus)

- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-10760
> [android] Awesome fix uncompleted task

- generator/restriction_writer.cpp
Писали в файл перед проверкой на то, что такая точка существует
> [generator] fix RestrictionWriter

- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
https://jira.mail.ru/browse/MAPSME-10636
> [android] Implemented preview plus state for place page

- data/faq.html
> [FAQ] Update June 2019

- android/jni/CMakeLists.txt
- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/Framework.hpp
- android/jni/com/mapswithme/maps/discovery/DiscoveryManager.cpp
- android/jni/com/mapswithme/maps/promo/CityGallery.cpp
- android/jni/com/mapswithme/maps/promo/CityGallery.hpp
- android/src/com/mapswithme/maps/discovery/DiscoveryManager.java
- android/src/com/mapswithme/maps/promo/Promo.java
- android/src/com/mapswithme/maps/promo/PromoCityGallery.java
- map/discovery/discovery_manager.hpp
- partners_api/partners_api_tests/promo_tests.cpp
- partners_api/promo_api.cpp
- partners_api/promo_api.hpp
https://jira.mail.ru/browse/MAPSME-10777
https://jira.mail.ru/browse/MAPSME-10776
> [promo] jni + error callback int promo api

- routing/features_road_graph.cpp
- routing/features_road_graph.hpp
- routing/geometry.cpp
- routing/geometry.hpp
- routing/road_point.hpp
- routing/transit_world_graph.cpp
- routing_common/vehicle_model.cpp
- routing_common/vehicle_model.hpp
- track_analyzing/serialization.hpp
- track_analyzing/track_analyzer/CMakeLists.txt
- track_analyzing/track_analyzer/cmd_table.cpp
- track_analyzing/track_analyzer/crossroad_checker.cpp
- track_analyzing/track_analyzer/crossroad_checker.hpp
Хочу заметить, что функции из crossroads_classificator.hpp и функция GetCrossroadsFromSegment сейчас в track_analyzer'е, но, в будущем, видимо, будут в routing'е в текущем или ином виде.
> [routing] Crossroads in track_analyzer

- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/ads/LocalAdInfo.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- map/framework.cpp
- map/place_page_info.hpp
Для скрытых рекламных кампаний добавлена утерянная статистика по кликам в PP
https://jira.mail.ru/browse/MAPSME-10663
https://jira.mail.ru/browse/MAPSME-10662
> [partners] Fixed local ads stats for hidden campaigns

- routing/routing_integration_tests/routing_test_tools.cpp
- routing/routing_integration_tests/street_names_test.cpp
- routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp
- routing/routing_quality/utils.cpp
- storage/country_parent_getter.hpp
@mpimenov @tatiana-yan @gmoryes PTAL
> [routing] Fixing routing integration and quality tests after packed_polygons.bin update.

- drape/vulkan/vulkan_base_context.cpp
Cherry pick https://github.com/mapsme/omim/pull/11035
> [vulkan] Fixed crash after getting foreground

- android/build.gradle
- android/gradle.properties
https://jira.mail.ru/browse/MAPSME-10835
> Huawei build

- android/build.gradle
https://jira.mail.ru/browse/MAPSME-10835
> [android] Fixed huawei assets resources path

- base/deferred_task.hpp
- base/thread_pool_delayed.hpp
- generator/feature_builder.hpp
- generator/generator_tool/generator_tool.cpp
- generator/geo_objects/geo_objects.cpp
- generator/geo_objects/geo_objects.hpp
- generator/regions/region_info_getter.cpp
- generator/regions/region_info_getter.hpp
- generator/streets/streets_builder.hpp
Параллельная фильтрация building null по странам. Сейчас это занимает около 12 часов, с параллельной обработкой - около 20 минут.
> [generator:geo_objects] Parallel processing in addressless filter

- android/gradle.properties
- android/jni/com/mapswithme/maps/PrivateVariables.cpp
- android/src/com/mapswithme/maps/PrivateVariables.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/purchase/AbstractProductDetailsLoadingCallback.java
- android/src/com/mapswithme/maps/purchase/AbstractPurchaseController.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseController.java
- android/src/com/mapswithme/maps/purchase/FailedBookmarkPurchaseController.java
- android/src/com/mapswithme/maps/purchase/PlayStoreBillingCallback.java
- android/src/com/mapswithme/maps/purchase/PurchaseFactory.java
- android/src/com/mapswithme/maps/purchase/PurchaseUtils.java
- android/src/com/mapswithme/maps/purchase/QueryProductDetailsRequest.java
- android/src/com/mapswithme/util/HttpClient.java
https://jira.mail.ru/browse/MAPSME-10808
https://jira.mail.ru/browse/MAPSME-10809
> Mapsme 10808 inapp product details on web catalog

- android/build.gradle
https://jira.mail.ru/browse/MAPSME-10835
> [android] Made chinese build version codes bigger

- generator/generator_tool/generator_tool.cpp
- generator/streets/streets.cpp
- generator/streets/streets.hpp
- generator/streets/streets_builder.cpp
- generator/streets/streets_builder.hpp
Цифры ускорения я не помню, но где то на порядок
> [generator:streets] Parallel build streets jsonl

- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/purchase/AbstractProductDetailsLoadingCallback.java
- android/src/com/mapswithme/maps/purchase/AbstractPurchaseController.java
- android/src/com/mapswithme/maps/purchase/FailedBookmarkPurchaseController.java
- android/src/com/mapswithme/maps/purchase/PlayStoreBillingCallback.java
- android/src/com/mapswithme/maps/purchase/QueryProductDetailsRequest.java
https://jira.mail.ru/browse/MAPSME-10808
> [android] Added handling of bookmark inapp details loading failure

- generator/extract_addr/extract_addr.cpp
- generator/geo_objects/geo_objects.cpp
- generator/regions/regions.cpp
- generator/regions/to_string_policy.cpp
- generator/regions/to_string_policy.hpp
- generator/streets/streets_builder.cpp
Уменьшаем разрядность координат в jsonl
> [generator] real numbers precision MAPSB2B-41

- generator/generator_tests/regions_tests.cpp
- generator/regions/collector_region_info.cpp
- generator/regions/collector_region_info.hpp
- generator/regions/region.cpp
- generator/regions/regions_builder.cpp
- generator/regions/regions_builder.hpp
Добавлены административные place: "country", "state", "province", "district", "county", "municipality".
Удалена дефаулт эвристика конвертации в регион по admin_level=4,6. В след-их PR будет добавлена конвертация admin_level в регион для России и других стран.
> [generator:regions] Add administrative place

- generator/CMakeLists.txt
- generator/regions/country_specifier.cpp
- generator/regions/country_specifier.hpp
- generator/regions/regions.cpp
- generator/regions/regions_builder.cpp
- generator/regions/regions_builder.hpp
Рефакторинг для след PR с спецификой разметки регионов в странах.
RelateByWeight и GetLevel перенесены в CountrySpecifier
> [generator:regions] Add country specifier

- coding/coding_tests/string_utf8_multilang_tests.cpp
- coding/string_utf8_multilang.cpp
- coding/string_utf8_multilang.hpp
- generator/generator_tests/regions_tests.cpp
- generator/regions/region_base.cpp
MAPSB2B-83
Устанавливаем порядок языков, из которых мы будем транслитерировать имена региона и отбразываем сломанные транслитерации.
> [generator] Use reasonable order for transliteration of region names

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Common/WebViewController.h
- iphone/Maps/Common/WebViewController.mm
- iphone/Maps/Core/InappPurchase/InAppPurchase.swift
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.h
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.mm
https://jira.mail.ru/browse/MAPSME-10822
> [iOS] Show item price in catalog

- generator/generator_tests/region_info_collector_tests.cpp
- generator/regions/region_base.cpp
- generator/regions/region_base.hpp
- generator/regions/region_info.cpp
- generator/regions/region_info.hpp
- generator/regions/to_string_policy.cpp
Рефакторинг для след. PR: удобней работать с Region через optional, чем через Has + Get
> [generator:regions] Refactor class Region: Has*() -> *Optional()

- partners_api/partners_api_tests/promo_tests.cpp
- partners_api/promo_api.cpp
- partners_api/promo_api.hpp
- tools/python/ResponseProvider.py
- tools/python/jsons.py
fyi @yoksnod @alexzatsepin @niakrise
> [promo] signed ids are supported + GetMoreUrl method

- generator/geo_objects/geo_object_info_getter.cpp
- generator/geo_objects/geo_object_info_getter.hpp
- generator/geo_objects/geo_objects.cpp
- generator/key_value_storage.cpp
- generator/key_value_storage.hpp
Исключена стадия загрузки jsonl после её генерации
> [generator:geo_objects] Optimize geo objects generator: eliminate geo objects loading

- map/bookmark_manager.cpp
- map/cloud.cpp
- map/cloud.hpp
https://jira.mail.ru/browse/MAPSME-10857
> Forbidden cloud backup for paid bookmarks

- iphone/Maps/Categories/UIColor+MapsMeColor.h
- iphone/Maps/Categories/UIColor+MapsMeColor.mm
- iphone/Maps/Categories/UIKitCategories.h
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/Discovery/Collection Cells/DiscoveryGuideCell.swift
- iphone/Maps/UI/Discovery/Collection Cells/DiscoveryGuideCell.xib
- iphone/Maps/UI/Discovery/MWMDiscoveryCollectionView.h
- iphone/Maps/UI/Discovery/MWMDiscoveryCollectionView.mm
- iphone/Maps/UI/Discovery/MWMDiscoveryController.mm
- iphone/Maps/UI/Discovery/MWMDiscoveryController.xib
- iphone/Maps/UI/Discovery/MWMDiscoveryTableManager.mm
- iphone/Maps/UI/Discovery/Table Cells/Holders/DiscoveryBookingCollectionHolderCell.xib
- iphone/Maps/UI/Discovery/Table Cells/Holders/DiscoveryCollectionHolderCell.swift
- iphone/Maps/UI/Discovery/Table Cells/Holders/DiscoveryGuideCollectionHolderCell.xib
- iphone/Maps/UI/Discovery/Table Cells/Holders/DiscoverySearchCollectionHolderCell.xib
- iphone/Maps/UI/Discovery/View Models/MWMDiscoveryControllerViewModel.mm
- iphone/Maps/UI/Discovery/View Models/MWMDiscoveryGuideViewModel.h
- iphone/Maps/UI/Discovery/View Models/MWMDiscoveryGuideViewModel.m
- iphone/Maps/UI/PlacePage/MWMPlacePageButtonsProtocol.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-10628
Для корректной работы необходимо добавить получение id города и передачу его в api->GetCityGallery
> [iOS][Cross traffic] Guides in the place page

- generator/regions/collector_region_info.cpp
- generator/regions/country_specifier.cpp
- generator/regions/regions_builder.cpp
Фикс проблемы, когда столица в виде точки (нет границ) считается страной.
> [generator:regions] Fix for capital node

- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/Framework.hpp
- android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
- android/src/com/mapswithme/maps/discovery/DiscoveryManager.java
- android/src/com/mapswithme/maps/discovery/DiscoveryParams.java
- android/src/com/mapswithme/maps/discovery/DiscoveryResultReceiver.java
- android/src/com/mapswithme/maps/discovery/DiscoveryUserEvent.java
- android/src/com/mapswithme/maps/discovery/ItemType.java
- android/src/com/mapswithme/maps/promo/PromoCityGallery.java
- android/src/com/mapswithme/maps/promo/PromoEntity.java
- metrics/eye_info.hpp
https://jira.mail.ru/browse/MAPSME-10490
> Mapsme 10490 discovery

- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Core/Framework/MWMFrameworkHelper.h
- iphone/Maps/Core/Framework/MWMFrameworkHelper.mm
https://jira.mail.ru/browse/MAPSME-10906
> [iOS] validate subscription only if WiFi connection available

- map/purchase.cpp
https://jira.mail.ru/browse/MAPSME-10924
> [RELEASE ONLY] Added http request latency statistics

- android/res/layout/catalog_promo_container.xml
- android/res/layout/item_viator_more.xml
https://jira.mail.ru/browse/MAPSME-10926
> [android] Fixed https://jira.mail.ru/browse/MAPSME-10926

- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-10907
> [android] Added auth error in statistics during purchase validation

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- map/bookmark_catalog.cpp
- map/bookmark_catalog.hpp
https://jira.mail.ru/browse/MAPSME-10902
> Added bookmarks catalog pinger

- data/faq.html
> [FAQ] minor hotfix 

- routing/leaps_postprocessor.cpp
- routing/leaps_postprocessor.hpp
- routing/routing_quality/routing_quality_tests/leaps_postprocessing_tests.cpp
> [routing] Fix loops in route

- base/CMakeLists.txt
- base/base_tests/CMakeLists.txt
- base/base_tests/thread_safe_queue_tests.cpp
- base/file_name_utils.cpp
- base/file_name_utils.hpp
- base/queue.hpp
- base/string_utils.cpp
- base/string_utils.hpp
- base/thread_safe_queue.hpp
- generator/osm_element.cpp
- generator/osm_element.hpp
- indexer/feature_data.cpp
- indexer/feature_data.hpp
Изменений очень много, решил все же разбивать на отдельные реквесты.
Часть первая, здесь нет ничего серьезного,  здесь добавляются некоторые перегрузки методов и простая threadsafe очередь.
Можно смотреть по коммитам.
> [generator] Optimization step features: part 1

- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/MwmApplication.cpp
- android/src/com/mapswithme/maps/MwmApplication.java
https://jira.mail.ru/browse/MAPSME-10609
> [android] enter foreground/background is corrected

- drape_frontend/arrow3d.cpp
- drape_frontend/arrow3d.hpp
- drape_frontend/drape_engine.cpp
- drape_frontend/drape_engine.hpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/message.cpp
- drape_frontend/message.hpp
- drape_frontend/message_subclasses.hpp
- drape_frontend/my_position_controller.cpp
- drape_frontend/my_position_controller.hpp
- map/framework.cpp
- map/framework.hpp
https://jira.mail.ru/browse/MAPSME-10909
Смещение offsetY задает расстояние от нижней границы visibleViewport до нижней границы стрелки (движок масштабирует его под текущий visual scale).
> [drape] For CarPlay added method for updating arrow offset Y in routing.

- tools/python/maps_generator/maps_generator.py
> [generator][python] Fixed ttf copy.

- generator/regions/region_info_getter.cpp
- generator/regions/region_info_getter.hpp
> [generator] Pid->Dref fix

- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
https://jira.mail.ru/browse/MAPSME-10932
> [android] Added an interception of the "subscribe" url

- android/res/layout/bookmark_payment_layout.xml
- android/res/values/strings.xml
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentState.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseCallback.java
- android/src/com/mapswithme/maps/purchase/PurchaseFactory.java
- android/src/com/mapswithme/maps/purchase/SubsProductDetailsCallback.java
- data/strings/strings.txt
https://jira.mail.ru/browse/MAPSME-10940
> Mapsme 10940 subs btn

- routing/routing_benchmarks/CMakeLists.txt
- routing/routing_benchmarks/bicycle_routing_tests.cpp
- routing/routing_benchmarks/car_routing_tests.cpp
- routing/routing_benchmarks/helpers.cpp
- routing/routing_benchmarks/helpers.hpp
- routing/routing_benchmarks/pedestrian_routing_tests.cpp
Добавил benchmark-и, чтоб оценивать время поиска ближайших к старту и финишу маршрута сегментов.
> [routing] Adding benchmarks on finding best segments of the route.

- generator/locality_sorter.cpp
Фикс: не индексировать POI, которые не добавлены в jsonl (отсутствует адрес).
> [generator:geo_objects] No index addressless POI

- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/Framework.hpp
- android/jni/com/mapswithme/maps/promo/CityGallery.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/promo/Promo.java
- android/src/com/mapswithme/maps/promo/PromoAfterBooking.java
- android/src/com/mapswithme/maps/tips/TipsApi.java
- partners_api/promo_api.hpp
https://jira.mail.ru/browse/MAPSME-11062
https://jira.mail.ru/browse/MAPSME-11063
> Android promo after booking show logic + several tips fixes

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- map/bookmark_catalog.cpp
- map/bookmark_catalog.hpp
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/cloud.cpp
- map/purchase.cpp
- map/purchase.hpp
- platform/remote_file.cpp
- platform/remote_file.hpp
https://jira.mail.ru/browse/MAPSME-10860
> Added invalid bookmarks deleter

- indexer/map_style_reader.cpp
- qt/build_style/build_style.cpp
- qt/build_style/build_style.h
- qt/main.cpp
- qt/mainwindow.cpp
- Исправлена проблема с невозможностью показать открываемый стиль (показывался всегда встроенный);
- Добавлена автоматическая перегенерация открываемого стиля на старте (больше нет необходимости вручную нажимать кнопку Build Style после открытия приложения);
- Исправлен крэш, возникающий из-за неконсистентности local ads.
> Fixed designer tool

- generator/regions/locality_point_integrator.cpp
Проверки через `boost::geometry::intersection` недостаточно: может быть малый процент пресечения (см. `RegionsBuilder::InsertIntoSubtree`, вызов `RegionsBuilder::CompareAffiliation`). Заменено на проверку  через `RegionsBuilder::CompareAffiliation`.
> [generator:regions] Fix around place insertion

- android/res/layout/fragment_confirmation.xml
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesPagerFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadFragmentDelegate.java
- android/src/com/mapswithme/maps/bookmarks/InvalidSubscriptionAlertDialogCallback.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- android/src/com/mapswithme/maps/dialog/AlertDialog.java
Added invalid subscription dialog - Catalog Fragment, Categories Pager Fragment
> [android] https://jira.mail.ru/browse/MAPSME-10948

- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadManager.java
- android/src/com/mapswithme/util/HttpClient.java
DNM пока https://github.com/mapsme/omim/pull/11152 не залит
> [android] X-Mapsme-Device-Id header for BookmarksDownloadManager

- android/res/layout/fragment_confirmation.xml
- android/res/values/dimens.xml
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadFragmentDelegate.java
- android/src/com/mapswithme/maps/bookmarks/InvalidSubscriptionAlertDialogCallback.java
- android/src/com/mapswithme/maps/dialog/AlertDialog.java
- android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionActivity.java
- android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionFragment.java
- android/src/com/mapswithme/maps/purchase/PurchaseUtils.java
https://jira.mail.ru/browse/MAPSME-10931
https://jira.mail.ru/browse/MAPSME-10934
> Mapsme 10931 10934 woo hoo and catalog reload

- 3party/jansson/myjansson.cpp
- 3party/jansson/myjansson.hpp
- generator/region_meta.cpp
- geocoder/geocoder_tests/geocoder_tests.cpp
- geocoder/hierarchy.cpp
- geocoder/hierarchy_reader.cpp
- geocoder/hierarchy_reader.hpp
Чтение jsonl в новом формате:
1. id объекта в hex без 0x
2. поля в JSON: properties.name -> properties.locales.default.name, properties.address -> properties.locales.default.address
> [geocoder] Moving to new jsonl version: hex id, locales

- .gitignore
- tools/unix/build_omim.sh
До кучи переключим версию тулсета, 6-я не может собрать omim
> Compile Database by -j flag on build_omim.sh

- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/purchase/SubscriptionPurchaseController.java
https://jira.mail.ru/browse/MAPSME-10938
> Mapsme 10938 bookmark catalog header

- android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionFragment.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-10937
> [android] Added stats of the bookmark subscription

- android/res/layout/subscription_offer_sale.xml
- android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-11001
> Mapsme 11001 bmk subs validation

- android/jni/com/mapswithme/maps/metrics/UserActionsLogger.cpp
- metrics/eye.cpp
- metrics/eye.hpp
- metrics/eye_info.hpp
- metrics/metrics_tests/eye_tests.cpp
- partners_api/partners_api_tests/promo_tests.cpp
- partners_api/promo_api.cpp
- partners_api/promo_api.hpp
Переделал часть ока для промо, то, что было ранее - какой-то бред.
Среди прочего реквест фиксит тесты и https://jira.mail.ru/browse/MAPSME-11045
> [eye][promo] several fixes for promo

- android/build.gradle
https://jira.mail.ru/browse/MAPSME-10915
> [android] Updated Pushwoosh sdk

- android/res/layout/fragment_discovery.xml
- android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
https://jira.mail.ru/browse/MAPSME-11050
> Mapsme 11050 local experts

- 3party/jansson/myjansson.hpp
- generator/geo_objects/geo_objects.cpp
> Address buildings fix

- generator/feature_builder.hpp
Фикс игнорирования исключений в тредах
> [generator] Fix exception propagation form threads

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
- android/src/com/mapswithme/maps/downloader/DownloaderPromoBanner.java
- android/src/com/mapswithme/maps/downloader/DownloaderPromoBannerStats.java
- android/src/com/mapswithme/maps/downloader/OnmapDownloader.java
- android/src/com/mapswithme/maps/gallery/impl/Factory.java
- android/src/com/mapswithme/maps/gallery/impl/RegularCatalogPromoListener.java
- android/src/com/mapswithme/maps/promo/PromoBookingDialogFragment.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- android/src/com/mapswithme/util/statistics/Destination.java
- android/src/com/mapswithme/util/statistics/GalleryType.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-11034
> [android] Added more stats for dialog after booking

- map/promo_delegate.cpp
- map/promo_delegate.hpp
https://jira.mail.ru/browse/MAPSME-11051
> [promo] load cities section into delegate lazy

- android/src/com/mapswithme/util/UTM.java
- iphone/Maps/Bookmarks/Catalog/MWMUTM.h
- partners_api/promo_api.cpp
- partners_api/utm.hpp
- Исправлен забытый UTM для карточек в галерее
- Добавлен UTM для ссылки с промо-окна букинга
> Added UTM for booking promo popup

- android/res/layout/catalog_promo_placeholder_card.xml
- android/src/com/mapswithme/maps/gallery/Holders.java
- android/src/com/mapswithme/maps/gallery/impl/Factory.java
https://jira.mail.ru/browse/MAPSME-11130
> [android] Removed clicks on Progress view

- iphone/Maps/Classes/Widgets/MWMBookmarksBannerViewController.h
- iphone/Maps/Classes/Widgets/MWMBookmarksBannerViewController.m
- iphone/Maps/Classes/Widgets/MWMBookmarksBannerViewController.xib
- iphone/Maps/Classes/Widgets/MWMDownloadBannerViewController.h
- iphone/Maps/Classes/Widgets/MWMDownloadBannerViewController.m
- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.xib
- iphone/Maps/Classes/Widgets/MWMMegafonBannerViewController.h
- iphone/Maps/Classes/Widgets/MWMMegafonBannerViewController.m
- iphone/Maps/Classes/Widgets/MWMMegafonBannerViewController.xib
- iphone/Maps/Maps.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-10627
> [iOS] Bookmarks banner on map download popup

- android/jni/com/mapswithme/maps/LocationState.cpp
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/location/LocationHelper.java
- android/src/com/mapswithme/maps/location/LocationState.java
- android/src/com/mapswithme/maps/routing/ResultCodesHelper.java
- drape_frontend/drape_engine.cpp
- drape_frontend/drape_engine.hpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/frontend_renderer.hpp
- drape_frontend/my_position_controller.cpp
- drape_frontend/my_position_controller.hpp
- iphone/Maps/Classes/CarPlay/CarPlayService.swift
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Core/Framework/ProxyObjects/Location/MWMLocationModeListener.h
- iphone/Maps/Core/Location/MWMLocationManager.h
- iphone/Maps/Core/Location/MWMLocationManager.mm
- map/framework.cpp
- map/framework.hpp
See https://confluence.mail.ru/display/MAPSME/Geo+orientation+v2 "New in 9.2"
https://jira.mail.ru/browse/MAPSME-6624
https://jira.mail.ru/browse/MAPSME-6623
> Improved location mode

- base/thread_pool_computational.hpp
- generator/final_processor_intermediate_mwm.cpp
Спасибо @cc-engineering что заметил проблему с другим тредпулом.
добавил новый метод, который не возвращает future
> Thread pool new method

- search/search_integration_tests/processor_test.cpp
cherry-pick https://github.com/mapsme/omim/pull/11252
> [search] Ignore ranking for ProcessorTest_ExactMatchTest.

- generator/CMakeLists.txt
- generator/emitter_coastline.hpp
- generator/emitter_country.cpp
- generator/emitter_country.hpp
- generator/emitter_world.cpp
- generator/emitter_world.hpp
- generator/feature_processing_layers.cpp
- generator/feature_processing_layers.hpp
- generator/final_processor_intermediate_mwm.cpp
- generator/place_processor.cpp
- generator/place_processor.hpp
Возвращаю обратно:
https://github.com/mapsme/omim/pull/11187/commits/bc91ac1aa014dc6ce9b35f32bbe53ab2325a69b5#r301615372
На картинке видно что появлется куча лишних штук, например острова. Они все будут иметь подписи.
На счет равных стран и т.д. в коде есть кейсы см place.cpp
> [generator] Fixed final_processor_intermediate_mwm

- search/result.cpp
- search/result.hpp
добавление координат поискового результата в алохалитику в события searchShowResult и searchEmitResultsAndCoords
https://jira.mail.ru/browse/MAPSME-6699
формат согласован с Игнатом
> [search][Alohalytics] Add coords to search result.

- partners_api/taxi_engine.cpp
https://jira.mail.ru/browse/MAPSME-11222
> [uber] The Uber is disabled

- partners_api/rutaxi_api.cpp
https://jira.mail.ru/browse/MAPSME-10679
> [vezet] deeplink fix

- android/jni/com/mapswithme/util/statistics/PushwooshHelper.cpp
- android/src/com/mapswithme/maps/bookmarks/SystemDownloadCompletedService.java
- android/src/com/mapswithme/util/statistics/PushwooshHelper.java
- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Core/Notifications/MWMPushNotifications.h
- iphone/Maps/Core/Notifications/MWMPushNotifications.mm
- map/purchase.cpp
- platform/marketing_service.cpp
- platform/marketing_service.hpp
- storage/storage.cpp
https://jira.mail.ru/browse/MAPSME-10861
https://jira.mail.ru/browse/MAPSME-10783
> Added pw tags for bookmark catalog and purchases

- iphone/Maps/Classes/CarPlay/CarPlayService.swift
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Core/Framework/MWMFrameworkHelper.h
- iphone/Maps/Core/Framework/MWMFrameworkHelper.mm
https://jira.mail.ru/browse/MAPSME-11077
> [CarPlay][iOS] map rotation and arrow position fixes

- routing/routing_integration_tests/bicycle_route_test.cpp
- routing/routing_integration_tests/route_test.cpp
- routing/routing_quality/routing_quality_tests/passby_roads_tests.cpp
Поправил outing integration tests and routing quality tests. Пока не мержим. Ждем релизной карты.
> [routing] Fixing routing integration tests and routing quality tests for maps 19.07.2019.

- search/locality_scorer.cpp
cherry-pick фикса https://github.com/mapsme/omim/pull/11281 на релиз
> [search] Fix DF calculation in LocalityScorer.

- android/jni/com/mapswithme/maps/Framework.cpp
- map/framework.cpp
- partners_api/promo_api.cpp
часть https://jira.mail.ru/browse/MAPSME-11246
https://jira.mail.ru/browse/MAPSME-11243
https://jira.mail.ru/browse/MAPSME-11133
https://jira.mail.ru/browse/MAPSME-11260
> promo_api fixes

- generator/generator_tests/regions_tests.cpp
- generator/regions/node.cpp
Фикс проблемы записи несколько раз одного и того же региона в mvm при repack
> [generator:regions] Fix duplicate of regions in mvm-repack

- iphone/Maps/UI/Discovery/Table Cells/DiscoveryOnlineTemplateCell.swift
https://jira.mail.ru/browse/MAPSME-11255
> [iOS] Fixed guides loading/failure template

- iphone/Maps/UI/BottomMenu/MWMBottomMenuViewController.mm
https://jira.mail.ru/browse/MAPSME-10789
> [iOS] Fixed parameter for kStatToolbarMenuClick

- iphone/Maps/Bookmarks/MWMCategoryInfoCell.mm
- iphone/Maps/Categories/NSAttributedString+HTML.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/BookmarkCell/MWMBookmarkCell.mm
https://jira.mail.ru/browse/MAPSME-10341
> [iOS] Added image resize for bookmarks and guide descriptions

- partners_api/downloader_promo.cpp
- partners_api/promo_api.cpp
- partners_api/promo_api.hpp
> Fixed URL for downloader promo

- iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-11297
> [iOS] Fixed deadlock on iOS 10

- android/res/layout-land/onmap_downloader.xml
- android/res/layout/onmap_downloader.xml
https://jira.mail.ru/browse/MAPSME-11153
> [android] Fixed a promo block's appearance

- android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
- android/src/com/mapswithme/maps/gallery/impl/Factory.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-11296
> [android] Fixed stats of the sponsored galleries

- android/res/layout-w1020dp/menu_buttons_line.xml
https://jira.mail.ru/browse/MAPSME-10785
> [android] Added the "hotel_search" btn for the tablets' landscape mode

- android/src/com/mapswithme/maps/downloader/OnmapDownloader.java
https://jira.mail.ru/browse/MAPSME-11153
> [android] Removed the "if" condition if a promo is missing

- partners_api/ads_base.cpp
https://jira.mail.ru/browse/MAPSME-11312
> Remove banners from promo

- generator/generator_tests/regions_tests.cpp
- generator/regions/locality_point_integrator.cpp
Для подбора границы place-точки, не рассматривать слишком большие по площади регионы.
> [generator:regions] Add limit on admin region size for place node

- iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm
Cherry pick for https://github.com/mapsme/omim/pull/11317
> [iOS] Fixed crash when location restricted alert showed up

- iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-11328
> [iOS] Disabled location related dialogs for the welcome screen

- iphone/Maps/Classes/CarPlay/CarPlayService.swift
Cherry pick for https://github.com/mapsme/omim/pull/11328
> [iOS][CarPlay] fixed CPAlertTemplate crash. Only one template at the time can be presented

- map/bookmark.cpp
- map/bookmark.hpp
- map/bookmark_helpers.hpp
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/framework.cpp
- map/framework.hpp
- map/map_tests/bookmarks_test.cpp
- openlr/openlr_tests/CMakeLists.txt
- search/CMakeLists.txt
- search/region_address_getter.cpp
- search/region_address_getter.hpp
- search/region_info_getter.cpp
- search/region_info_getter.hpp
- search/reverse_geocoder.cpp
- search/reverse_geocoder.hpp
- storage/country_decl.hpp
- xcode/search/search.xcodeproj/project.pbxproj
Для букмарок добавлен адрес ближайшего топонима. Адрес потребуется для группировки сортированных по расстоянию букмарок и для поиска по топониму. 
Адрес RegionAddress состоит из:
* FeatureId ближайшего населенного пункта, если он найден;
* CountryId, если FeatureId принадлежит World.mwm или не найден. 
Чтобы отображать в UI заголовок группы букмарок в формате "Имя города + Имя mwm", необходимо хранить помимо FeatureId из World.mwm и CountryId.
> [bookmarks][geocoder] Region address for bookmarks.

- map/purchase.cpp
- platform/marketing_service.cpp
- platform/marketing_service.hpp
https://jira.mail.ru/browse/MAPSME-11183
> Added PW tags for remove ads

- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
https://jira.mail.ru/browse/MAPSME-11366
> [iOS] Fixed catalog url from the mwm download banner

- iphone/Maps/UI/Search/Filters/FilterCollectionHolderCell.swift
https://jira.mail.ru/browse/MAPSME-11266
> [iOS] Fixed search filter height

- iphone/Maps/UI/Discovery/MWMDiscoveryController.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
https://jira.mail.ru/browse/MAPSME-11367
> [iOS] Exclude bookmarks screen from the hierarchy when we are opening catalogs from the URL

- CMakeLists.txt
- qt/CMakeLists.txt
- shaders/CMakeLists.txt
https://github.com/mapsme/omim/issues/11330
У человека не ищется python, из-за того что в CMakeLists.txt написан просто
```sh
python ...
```
добавил поиск питона через CMake, скрипт отрабатывает как под питоном 3, так и под вторым
> [omim] Now python's search processed by cmake

- generator/regions/regions.cpp
- generator/translation.cpp
> Transliteration lazy initilation

- base/geo_object_id.hpp
- generator/feature_builder.hpp
- generator/generator_tests/CMakeLists.txt
- generator/generator_tests/common.cpp
- generator/generator_tests/common.hpp
- generator/generator_tests/geo_objects_tests.cpp
- generator/generator_tests/regions_tests.cpp
- generator/generator_tool/generator_tool.cpp
- generator/geo_objects/geo_object_info_getter.cpp
- generator/geo_objects/geo_object_info_getter.hpp
- generator/geo_objects/geo_objects.cpp
- generator/geo_objects/geo_objects.hpp
- generator/osm_source.hpp
- indexer/locality_index_builder.cpp
Для точек с адресами добавляем геометрию внешнего здания без адреса
> Null building addresses

- android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
- android/src/com/mapswithme/maps/gallery/Holders.java
- android/src/com/mapswithme/maps/gallery/impl/Factory.java
- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
- android/src/com/mapswithme/maps/widget/StackedButtonDialogFragment.java
- android/src/com/mapswithme/maps/widget/placepage/ErrorCatalogPromoListener.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- android/src/com/mapswithme/util/Config.java
- android/src/com/mapswithme/util/NetworkPolicy.java
https://jira.mail.ru/browse/MAPSME-11246
> Mapsme 11246 internet gallery

- coding/coding_tests/CMakeLists.txt
- coding/coding_tests/serdes_json_test.cpp
- coding/serdes_json.hpp
- kml/type_utils.cpp
- kml/type_utils.hpp
- map/bookmark_helpers.cpp
- map/bookmark_helpers.hpp
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/map_tests/bookmarks_test.cpp
- map/place_page_info.cpp
- xcode/coding/coding.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-11378
> [bookmarks] Sorting by type, distance and type.

- partners_api/rutaxi_api.cpp
https://jira.mail.ru/browse/MAPSME-11226
> [taxi] fix rutaxi for ios

- iphone/Maps/UI/Discovery/MWMDiscoveryTableManager.mm
https://jira.mail.ru/browse/MAPSME-11319
> [iOS] "turn on internet" fixes for discovery

- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMiPhoneRoutePreview.xib
- iphone/Maps/UI/BottomMenu/MWMBottomMenuViewController.mm
https://jira.mail.ru/browse/MAPSME-11227
https://jira.mail.ru/browse/MAPSME-11393
> [iOS] Fixed bottom view position for the landscape mode

- android/build.gradle
https://jira.mail.ru/browse/MAPSME-11420
> [android] Increased version code for splitted by abi arch builds

- android/res/layout/catalog_promo_item_card.xml
- android/res/values/dimens.xml
- android/src/com/mapswithme/maps/gallery/Holders.java
https://jira.mail.ru/browse/MAPSME-11363
> [android] Added elevation to 'PRO' label view in catalog promo gallery

- coding/internal/file_data.cpp
- coding/internal/file_data.hpp
- generator/collector_addresses.cpp
- generator/collector_addresses.hpp
- generator/collector_camera.cpp
- generator/collector_camera.hpp
- generator/collector_city_area.cpp
- generator/collector_city_area.hpp
- generator/collector_collection.cpp
- generator/collector_collection.hpp
- generator/collector_interface.hpp
- generator/collector_tag.cpp
- generator/collector_tag.hpp
- generator/maxspeeds_collector.cpp
- generator/maxspeeds_collector.hpp
- generator/regions/collector_region_info.hpp
- generator/restriction_writer.cpp
- generator/restriction_writer.hpp
- generator/road_access_generator.cpp
- generator/road_access_generator.hpp
- generator/translator.cpp
- generator/translator_country.cpp
Изменил коллекторы.
Проблема была в том, что не хватало памяти для сборки карт всего мира. Сейчас жирные данные пишутся во временные файлы.
Тесты есть, они чуть позже пойдут в другом реквесте.
> [generator] Collectors can work with files

- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
- android/src/com/mapswithme/maps/widget/StackedButtonDialogFragment.java
- android/src/com/mapswithme/util/NetworkPolicy.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-11377
> [android] Added stats for the "turn on internet" dialog

- generator/geo_objects/geo_objects.cpp
- generator/geo_objects/geo_objects.hpp
This is super important refactoring: we rename three variables
> Generator super important refactoring

- iphone/Maps/UI/PlacePage/MWMPlacePageData.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-11418
> [iOS] Fixed place page bookmarks crash

- iphone/Maps/Bookmarks/Categories/Sharing/Tags/TagsCollectionViewLayout.swift
- iphone/Maps/UI/Storyboard/SearchFilters.storyboard
https://jira.mail.ru/browse/MAPSME-11266
> [iOS] Fixed top gap for the type filter

- iphone/Maps/Classes/Widgets/MWMBookmarksBannerViewController.xib
https://jira.mail.ru/browse/MAPSME-11364
> [iOS] Fixed font for the guides promo banner

- android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
- android/src/com/mapswithme/maps/gallery/Holders.java
- android/src/com/mapswithme/maps/gallery/impl/Factory.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-11246
> Mapsme 11246 fix network error after 500/400 error recieved

- iphone/Maps/Categories/UIFont+MapsMeFonts.h
- iphone/Maps/Categories/UIFont+MapsMeFonts.mm
- iphone/Maps/UI/Discovery/Collection Cells/DiscoveryGuideCell.swift
- iphone/Maps/UI/Discovery/Collection Cells/DiscoveryGuideCell.xib
https://jira.mail.ru/browse/MAPSME-11365
> [iOS] Fixed font for the details button in promo collection

- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
https://jira.mail.ru/browse/MAPSME-11349
> [iOS] Fixed downloading banner show/hide behavior

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
- android/src/com/mapswithme/maps/metrics/UserActionsLogger.java
- android/src/com/mapswithme/maps/tips/AbstractClickInterceptor.java
- android/src/com/mapswithme/maps/tips/ClickInterceptorFactory.java
- android/src/com/mapswithme/maps/tips/TipsApi.java
- android/src/com/mapswithme/maps/tips/Tutorial.java
- android/src/com/mapswithme/maps/tips/TutorialAction.java
- android/src/com/mapswithme/maps/tips/TutorialClickListener.java
https://jira.mail.ru/browse/MAPSME-11069
> [android] Fixed tips screen duplication/overlaying

- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
https://jira.mail.ru/browse/MAPSME-11311
> [iOS] Fixed downloading progress

- android/res/layout/bookmark_subscription_fragment.xml
https://jira.mail.ru/browse/MAPSME-11432
> [android] Added gravity for subs' cards

- android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-11022
> [android] Fixed movements of the "Layers" btn

- iphone/Maps/Classes/Widgets/MWMBookmarksBannerViewController.xib
https://jira.mail.ru/browse/MAPSME-11364
При изменении шрифтов, не заметила что на рантайме шрифт сбрасывался на непонятно какой. Убрала лишний атрибут.
> [iOS] Fixed font for the guides promo banner (runtime)

- android/build.gradle
https://jira.mail.ru/browse/MAPSME-11455
> [android] Added x86_64 version

- generator/filter_world.cpp
- generator/filter_world.hpp
- generator/raw_generator.cpp
- generator/raw_generator.hpp
- generator/raw_generator_writer.cpp
- generator/raw_generator_writer.hpp
- generator/translators_pool.cpp
- generator/translators_pool.hpp
generator/filter_world - этот файл нужен для фильтрации World.mwm
generator/raw_generator - ядро, здесь все объединяется
generator/raw_generator_writer - писатель в отдельном потоке, помощник raw_generator
generator/translators_pool - заставляет работать трансляторы параллельно, помощник raw_generator
ВАЖНО: это сейчас не будет все компилироваться. Я разбил на несколько реквестов, что бы ревьюерам было проще ознакомиться с кодом. Следующие изменения залью скопом, потому что они рушат обратную совестимость и переключают на новую схему генерации фичей
> [generator] Added classes for features generation optimization.

- android/res/layout/bookmark_subscription_fragment.xml
https://jira.mail.ru/browse/MAPSME-11432
> [android] Added gravity for subs' cards and titles

- iphone/Maps/Bookmarks/Catalog/BookmarksSubscriptionViewController.swift
- iphone/Maps/Bookmarks/Catalog/PaidRouteViewController.swift
- iphone/Maps/Core/InappPurchase/Impl/PaidRouteStatistics.swift
- iphone/Maps/Core/Subscriptions/SubscriptionManager.swift
- iphone/Maps/UI/Ads/RemoveAdsViewController.swift
https://jira.mail.ru/browse/MAPSME-10946
> [iOS] Bookmarks subscription stats

- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMiPhonePlacePageLayoutImpl.mm
- iphone/Maps/UI/Storyboard/Main.storyboard
https://jira.mail.ru/browse/MAPSME-11461
> [iOS] Fixed pp offset for the preview state

- android/res/layout/bookmark_subscription_fragment.xml
https://jira.mail.ru/browse/MAPSME-11489
> [android] Fixed sale view gravity on bookmark subscription screen

- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-11483
> [android] Set the loading adapter to the recycler before long requests

- data/mixed_tags.txt
https://jira.mail.ru/browse/MAPSME-10799
> [data] Removed McArthurGlen Outlets.

- generator/features_processing_helpers.hpp
- generator/raw_generator.cpp
- generator/raw_generator_writer.cpp
- generator/translators_pool.cpp
Поправил по замечаниям @mpimenov 
https://github.com/mapsme/omim/pull/11378
> [generator] Review fixes.

- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesPagerFragment.java
https://jira.mail.ru/browse/MAPSME-11510
> [android] Added correct method's call

- map/bookmark_catalog.cpp
https://jira.mail.ru/browse/MAPSME-11520
> [bookmarks][catalog] Delete kml request fixed.

- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-11480
> [iOS] Guides gallery reload for the place page

- android/res/layout/fragment_promo_after_booking_dialog.xml
- android/res/values/styles.xml
https://jira.mail.ru/browse/MAPSME-11518
> [android] Fixed promo booking dialog look

- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMRoutePreview.mm
https://jira.mail.ru/browse/MAPSME-10537
> [iOS] fix route rebuild on fast switch of route type

- android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-11022
> [android] Added adjustment of the map layer btn after screen rotation

- iphone/Maps/Classes/Components/Modal/PromoBookingPresentationController.swift
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/Promo/PromoAfterBookingViewController.swift
- iphone/Maps/UI/Promo/PromoAfterBookingViewController.xib
https://jira.mail.ru/browse/MAPSME-11519
> [iOS] After Booking popup fixes

- iphone/Maps/Classes/MapsAppDelegate.mm
https://jira.mail.ru/browse/MAPSME-11532
> [CarPlay] Replaced nativeScale to scale for the visual scale update

- iphone/Maps/Classes/MapsAppDelegate.mm
https://jira.mail.ru/browse/MAPSME-10837
> [iOS] Fixed UIBarButtonItem appearance (We need it for navigation bar only)

- iphone/Maps/Bookmarks/Catalog/BookmarksSubscriptionCellViewController.swift
- iphone/Maps/Bookmarks/Catalog/BookmarksSubscriptionViewController.swift
- iphone/Maps/Bookmarks/Catalog/BookmarksSubscriptionViewController.xib
- iphone/Maps/Categories/UIColor+MapsMeColor.h
- iphone/Maps/Categories/UIColor+MapsMeColor.mm
https://jira.mail.ru/browse/MAPSME-11499
https://jira.mail.ru/browse/MAPSME-11507
https://jira.mail.ru/browse/MAPSME-11503
https://jira.mail.ru/browse/MAPSME-11505
> [iOS] fix bookmarks subscription screen layout

- data/categories.txt
(This one is taken from a recent commit by sb12.)
> [categories] Added a German synonym for dog_park.

- generator/regions/level_region.hpp
- geocoder/geocoder_tests/geocoder_tests.cpp
- geocoder/hierarchy.cpp
- geocoder/hierarchy.hpp
Фикс случая subregion в locality: индексируется по имени региона, а не по имени locality
> [geocoder] Fix indexing for subregion in locality

- iphone/Maps/Bookmarks/Catalog/BookmarksSubscriptionViewController.swift
when selecting monthly subscription
https://jira.mail.ru/browse/MAPSME-11537
> [iOS] fix crash on bookmarks subscription screen

- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
- iphone/Maps/Classes/MapViewController.h
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageProtocol.h
https://jira.mail.ru/browse/MAPSME-11234
> [iOS] Fixed the logic for displaying the tutorial

- iphone/Maps/Bookmarks/Catalog/BookmarksSubscriptionViewController.swift
- iphone/Maps/Bookmarks/Catalog/PaidRouteViewController.swift
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Common/Statistics/StatisticsStrings.h
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.h
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.mm
https://jira.mail.ru/browse/MAPSME-10946
> [iOS] add missing subscription stats

- iphone/Maps/Bookmarks/Catalog/BookmarksSubscriptionViewController.swift
- iphone/Maps/Bridging-Header.h
- iphone/Maps/Common/WebViewController.mm
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/Authorization/AuthorizationViewController.swift
- iphone/Maps/UI/Authorization/PhoneNumberAuthorizationViewController.swift
https://jira.mail.ru/browse/MAPSME-11571
> [iOS] show authorization dialog before subscription screen

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
https://jira.mail.ru/browse/MAPSME-11469
> [iOS] download guide after subscription from guide page

- android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
https://jira.mail.ru/browse/MAPSME-11556
> [android] Fixed text on buy subscription button

- tools/python/booking/__main__.py
- tools/python/booking/api/booking_api.py
- tools/python/booking/download_test_data.py
хотела сделать общий скрипт с download_hotels, но получается не очень красиво: в download_hotels не нужны дистрикты, зато нужна куча всего другого -- выходят сплошные ветвления, решила разделить
> [tools] Add script for booking test dataset download.

- iphone/Maps/Categories/UIViewController+Authorization.swift
- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
https://jira.mail.ru/browse/MAPSME-11572
> [iOS] restore all subsriptions from settings

- search/retrieval.cpp
- search/search_integration_tests/search_edited_features_test.cpp
не очень понятно почему мы делали MatchesByType внутри emo.GetNameMultilang().ForEach()
> [search] Fix search edited objects by type.

- CMakeLists.txt
Такой тип сборки полезен для профилировки при помощи perf
> [build] Add Release With Debug Info possibility

- drape/vulkan/vulkan_pipeline.cpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/a2aa6fd202395e5678b4e4afe0fc9708?time=last-ninety-days
> [vulkan] Workaround for vkCreatePipelineCache unspecified return codes

- map/bookmark.cpp
https://jira.mail.ru/browse/MAPSME-11514
> [bookmarks] sharing deeplink is changed

- indexer/feature_data.cpp
- indexer/feature_data.hpp
- map/framework.cpp
- map/framework.hpp
https://jira.mail.ru/browse/MAPSME-11423
> [DNM][core] fix for matching bookmarks on areas

- indexer/feature_data.cpp
- indexer/feature_data.hpp
- map/framework.cpp
- map/framework.hpp
> Revert "[DNM][core] fix for matching bookmarks on areas"

- indexer/feature_data.cpp
- indexer/feature_data.hpp
- map/framework.cpp
- map/framework.hpp
реинкарнация https://github.com/mapsme/omim/pull/11516
https://jira.mail.ru/browse/MAPSME-11423
> [core] fix for matching bookmarks on areas

- cmake/BuildVersion.cmake
Теперь варнинга нет, варнинг выскакивал потому что не получалось взять из гита тэг, точнее он возвращал пустую строку.
Теперь пустая строка это ок. Успех или не успех теперь проверяется через exit code
> [Cmake] Fixed warn

- android/jni/com/mapswithme/maps/Framework.cpp
- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.h
- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageProtocol.h
- map/framework.cpp
- map/framework.hpp
- qt/draw_widget.cpp
- search/search_quality/assessment_tool/main_view.cpp
https://jira.mail.ru/browse/MAPSME-11462
> [ios] Place page reopening fix

- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-11578
> [core] do not show preview plus when routing is active

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
https://jira.mail.ru/browse/MAPSME-11619
> [iOS] fix bug in which "no internet" error appears on backward navigation in catalog

- iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-11604
> [iOS] fix bug in which toast was displayed instead of dialog

- tools/python/maps_generator/__main__.py
- tools/python/maps_generator/generator/coastline.py
- tools/python/maps_generator/generator/gen_tool.py
- tools/python/maps_generator/generator/stages.py
Изменения в генераторе требуют некоторых изменений в пиновском проекте
> [generator][python] Fixed for python maps_generator.

- iphone/Maps/Bookmarks/BookmarksVC.mm
- iphone/Maps/Bookmarks/BookmarksVC.xib
- iphone/Maps/UI/Storyboard/Main.storyboard
https://jira.mail.ru/browse/MAPSME-11401
> [iOS] Show description section for all categories.

- android/src/com/mapswithme/maps/analytics/ExternalLibrariesMediator.java
https://jira.mail.ru/browse/MAPSME-11634
> [android] Reduced timeout for getting advertising id setting

- drape/support_manager.cpp
Cherry pick https://github.com/mapsme/omim/pull/11524
> [vulkan] GPU PowerVR GE8100 banned.

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- iphone/Maps/Bookmarks/BookmarksVC.mm
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/map_tests/bookmarks_test.cpp
https://jira.mail.ru/browse/MAPSME-11647
Отображение блока с треками в отсортированном списке.
> [bookmarks] Add tracks block to sorted results.

- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.h
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-11663
https://jira.mail.ru/browse/MAPSME-11676
> Update pp fix

- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/Framework.hpp
- android/jni/com/mapswithme/maps/promo/Promo.cpp
- android/src/com/mapswithme/maps/promo/Promo.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- android/src/com/mapswithme/maps/widget/placepage/Sponsored.java
- android/src/com/mapswithme/util/statistics/Statistics.java
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- map/CMakeLists.txt
- map/framework.cpp
- map/place_page_info.hpp
- map/promo_catalog_poi_checker.hpp
- partners_api/CMakeLists.txt
- partners_api/ads_base.cpp
- partners_api/promo_api.cpp
- partners_api/promo_api.hpp
- partners_api/promo_catalog_types.cpp
- partners_api/promo_catalog_types.hpp
- xcode/map/map.xcodeproj/project.pbxproj
- xcode/partners_api/partners_api.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-11644
> [promo][core][jni] promo for attractions is added

- iphone/Maps/Bookmarks/Catalog/BookmarksSubscriptionViewController.swift
- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bookmarks/Catalog/Dialogs/BookmarksSubscriptionExpiredViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
- iphone/Maps/Bookmarks/Catalog/PaidRouteViewController.swift
- iphone/Maps/Bookmarks/Catalog/UIViewController+Subscription.swift
- iphone/Maps/Classes/Components/Modal/CoverVerticalModalTransitioning.swift
- iphone/Maps/Classes/Components/Modal/DimmedModalPresentationController.swift
- iphone/Maps/Classes/Components/Modal/FadeTransitioning.swift
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.h
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- iphone/Maps/Core/InappPurchase/Impl/InAppBilling.swift
- iphone/Maps/Core/Subscriptions/SubscriptionManager.swift
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/Ads/RemoveAdsViewController.swift
https://jira.mail.ru/browse/MAPSME-11576
> [iOS] show "expired subscription dialog" when appropriate

- tools/python/descriptions/descriptions_downloader.py
- tools/python/maps_generator/maps_generator.py
С пометкой: нужно для запуска сборки сегодня
> [python] Added fr, de langs for descriptions.

- iphone/Maps/Bookmarks/BookmarksVC.mm
- iphone/Maps/Bookmarks/BookmarksVC.xib
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.h
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
https://jira.mail.ru/browse/MAPSME-11669
> [bookmarks][iOS] Enable sort and search for categories from the catalog.

- map/CMakeLists.txt
- map/crown.cpp
- map/crown.hpp
- metrics/eye.cpp
- metrics/eye.hpp
- metrics/eye_info.hpp
- omim_config.h
- xcode/map/map.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-11701
FYI @alexzatsepin @beloal
> [core] crown is added

- iphone/Maps/Bookmarks/Catalog/CatalogConnectionErrorView.xib
- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
https://jira.mail.ru/browse/MAPSME-11659
> [iOS] fix "no internet" popup in catalog

- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
- iphone/Maps/Bookmarks/Catalog/UIViewController+Subscription.swift
https://jira.mail.ru/browse/MAPSME-11707
> [iOS] reload category list when delete downloaded categories

- base/stl_helpers.hpp
- generator/final_processor_intermediate_mwm.cpp
- generator/generator_tests/CMakeLists.txt
- generator/generator_tests/cluster_finder_tests.cpp
- generator/generator_tests/place_processor_tests.cpp
- generator/place_processor.cpp
- generator/place_processor.hpp
С пометкой: нужно для запуска сборки сегодня
> [generator] Improved catalog matching 

- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMiPhonePlacePageLayoutImpl.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/MWMPPPreviewLayoutHelper.mm
https://jira.mail.ru/browse/MAPSME-11711
> [iOS] fix PP action bar when searching on map

- tools/python/post_generation/inject_promo_cities.py
На сервере countries.txt строился за 5ч16м, теперь за 17м
> [generator][python] Optimized inject_promo_cities.

- iphone/Maps/Bookmarks/Catalog/BookmarksSubscriptionViewController.swift
- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
https://jira.mail.ru/browse/MAPSME-10942
> [iOS] fix "successfull subscription" dialog

- routing/index_graph_starter_joints.hpp
В генераторе мы запускаем волну от `startSegment`, в то время как на `endSegment` нам все равно (потому что мы к нему никогда не обращаемся) и мы инициализировали его как `Segment()` и забивали. 
Но при инициализации IndexGraphStarterJoints были места вида:
```cpp
m_endPoint = m_graph.GetPoint(endSegment, ...);
```
а `endSegment` равен `Segment()`, а `Segment().GetFeatureId() == 0` и в итоге мы пытались вычитать highway тип у нулевой фичи. А так как она не была дорогой и тип хранится в boost::optional, то это приводило к крэшу
> [routing] Fix crash in debug in routing during map generation

- drape_frontend/drape_engine.cpp
- drape_frontend/drape_engine.hpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/message_subclasses.hpp
- map/framework.cpp
Геометрия улиц более не выделяется при кликах по карте. Выделение происходит только при наличии конкретной фичи (например, при переходе из поиска).
https://jira.mail.ru/browse/MAPSME-11673
> Fixed line selection

- routing/index_router.cpp
https://jira.mail.ru/browse/MAPSME-11739
> [routing][release-93] Fix crash about times at route points

- iphone/Maps/Bookmarks/BookmarksVC.xib
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/UI/Storyboard/Main.storyboard
https://jira.mail.ru/browse/MAPSME-11706
> [iOS] Fixed color of the search cursor.

- map/user_mark.hpp
cherry-pick of https://github.com/mapsme/omim/pull/11636
> [routing][map] Ferry placed upper than Tolls or Dirty icons

- routing/routing_integration_tests/route_test.cpp
- routing/routing_integration_tests/turn_test.cpp
cherry-pick https://github.com/mapsme/omim/pull/11631 to master.
@gmoryes PTAL
> [routing] Fixing routing integration tests after map update to 190830.

- android/jni/com/mapswithme/maps/PrivateVariables.cpp
- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- android/src/com/mapswithme/maps/PrivateVariables.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
- android/src/com/mapswithme/maps/bookmarks/CachedBookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionFragment.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- android/src/com/mapswithme/util/statistics/Statistics.java
- iphone/Maps/Common/Statistics/Statistics.mm
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-11699
> [android] Added realtime statistics for guides

- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.xib
- iphone/Maps/Images.xcassets/NavigationDashboard/ic_search_toast.imageset/Contents.json
https://jira.mail.ru/browse/MAPSME-11719
UIButton with "system" type and "word wrap" line break mode makes an app unresponsive when changing one multiline title to another multiline title. 
Fixed by changing type to "custom"
> [iOS] workaround for iOS 13.1 beta UIButton bug

- android/jni/com/mapswithme/maps/UserMarkHelper.cpp
- android/jni/com/mapswithme/maps/promo/Promo.cpp
- android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java
- android/src/com/mapswithme/maps/bookmarks/data/MapObject.java
- android/src/com/mapswithme/maps/promo/PromoCityGallery.java
https://jira.mail.ru/browse/MAPSME-11598
> Mapsme 11598 promo guides in pp

- iphone/Maps/Bookmarks/BookmarksVC.xib
- iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.xib
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Images.xcassets/NavigationDashboard/ic_search_toast.imageset/Contents.json
- iphone/Maps/UI/Storyboard/Main.storyboard
cherry picks https://github.com/mapsme/omim/pull/11632 https://github.com/mapsme/omim/pull/11619
> Release 93 fixes to master

- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesPagerFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadFragmentDelegate.java
- android/src/com/mapswithme/maps/bookmarks/InvalidSubscriptionAlertDialogCallback.java
https://jira.mail.ru/browse/MAPSME-11750
> Mapsme 11750 fix invalid subs dialog showing

- android/jni/com/mapswithme/maps/promo/Promo.cpp
- android/src/com/mapswithme/maps/promo/PromoCityGallery.java
- partners_api/partners_api_tests/promo_tests.cpp
- partners_api/promo_api.cpp
- partners_api/promo_api.hpp
- tools/python/ResponseProvider.py
- tools/python/jsons.py
https://jira.mail.ru/browse/MAPSME-11774
> [promo] client-server protocol is changed + test

- iphone/Maps/Bridging-Header.h
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/CatalogPromo/CatalogPromoItem+Core.h
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/CatalogPromo/CatalogPromoItem+Core.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/CatalogPromo/CatalogPromoItem.h
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/CatalogPromo/CatalogPromoItem.m
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/CatalogPromo/CatalogSingleItemCell.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/CatalogPromo/CatalogSingleItemCell.xib
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/CatalogPromo/EmptyTableViewCell.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/CatalogPromo/EmptyTableViewCell.xib
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-11835
> [iOS] add single item catalog promo to place page

- search/features_layer_matcher.cpp
- search/reverse_geocoder.cpp
cherry-pick
https://github.com/mapsme/omim/pull/11696
> [search] Fix CHECK, add more debug info.

- generator/routing_index_generator.cpp
- routing/cross_mwm_connector.hpp
- routing/cross_mwm_connector_serialization.hpp
- routing/routing_tests/cross_mwm_connector_test.cpp
Я рядом делаю PR, который связан с переходными сегментами и вот заметил следующее:
Сейчас в информацию о переходных сегментах пишутся координаты сегмента, при этом в коде они потом нигде не используются
При этом эта информация попадает в секцию, пока выпиливать из секции не стал, а просто поставил заглушки
это блокер для: https://github.com/mapsme/omim/pull/11628
> [routing] Rid from back front transition (cross mwm) points

- routing/edge_estimator.cpp
- routing/geometry.cpp
1. Поправил креш. Обработал случай, когда паром состоит из одной точки или из совпадающих точек https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/6d14578aa587a59018c6a091b217b77d?time=last-thirty-days
2. Добавил информации в чек на будущее
@gmoryes PTAL
> Release 94 info for crach fix

- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/cfd42363de839e48fb7f16e5111919c2?time=last-thirty-days
> [iOS] fix crash when city gallery promo loaded in PP

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/InvalidSubscriptionAlertDialogCallback.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionActivity.java
- android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionFragment.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-11794
> [android] Added crown stats

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/InvalidSubscriptionAlertDialogCallback.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionActivity.java
- android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionFragment.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://github.com/mapsme/omim/pull/11695/commits
cherry-pick
> Mapsme 11794 cherry pick

- iphone/Maps/Bookmarks/TracksSection.mm
https://jira.mail.ru/browse/MAPSME-11852
> [iOS] Fixed event Bookmarks_BookmarksList_Track_select

- map/routing_manager.cpp
https://jira.mail.ru/browse/MAPSME-11844
> Fixed rendering fake edges for transit routes

- routing/index_router.cpp
> [routing] Fix color of fake segments for non car routing

- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
https://jira.mail.ru/browse/MAPSME-11851
> [iOS] don't show crown when in routing mode

- android/src/com/mapswithme/maps/gallery/impl/CatalogPromoAdapterStrategy.java
https://jira.mail.ru/browse/MAPSME-11886
> [android] Changed max items count in catalog promo gallery

- android/src/com/mapswithme/maps/routing/NavigationController.java
https://jira.mail.ru/browse/MAPSME-111850
> [android] Moved search frame views lower than crown btn

- generator/translator_interface.hpp
Забыл удалить некоторый код оставшийся от b2b
> [generator] Removed unused code.

- generator/CMakeLists.txt
- generator/affiliation.cpp
- generator/affiliation.hpp
- generator/borders.hpp
- generator/cells_merger.cpp
- generator/cells_merger.hpp
- generator/final_processor_intermediate_mwm.cpp
- generator/generator_integration_tests/features_tests.cpp
- generator/generator_tests/CMakeLists.txt
- generator/generator_tests/cells_merger_tests.cpp
- generator/processor_country.cpp
- geometry/tree4d.hpp
Алгоритм для CellsMerger был взят с https://stackoverflow.com/a/31182327/8122949
Если где-то покажется что-то неочивидным, могу добавить комменты по запросу
> [generator] Added index for borders.

- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/CatalogPromo/CatalogSingleItemCell.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/CatalogPromo/CatalogSingleItemCell.xib
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-11872
https://jira.mail.ru/browse/MAPSME-11870
> [iOS] go to guide page on tap at "more" button in catalog promo

- map/framework.cpp
- map/framework.hpp
https://jira.mail.ru/browse/MAPSME-11673
> Fixed line selection rendering

- android/src/com/mapswithme/maps/gallery/impl/RegularCatalogPromoListener.java
- android/src/com/mapswithme/maps/promo/CatalogPromoController.java
- android/src/com/mapswithme/util/UTM.java
- iphone/Maps/Bookmarks/Catalog/MWMUTM.h
- partners_api/utm.hpp
[android] Fixed starting bookmark catalog activity by cta pressing in single item sightseen ui
https://jira.mail.ru/browse/MAPSME-11736
https://jira.mail.ru/browse/MAPSME-11889
> [android][ios] Added utm_content 'more' for more item in gallery

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-11895
https://jira.mail.ru/browse/MAPSME-11896
> [android] Added missed events for crown btn

- android/res/layout/fragment_confirmation.xml
- android/res/values/font_sizes.xml
- android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-11858
> [android] Redesigned alert confirmation dialog

- NOTICE
> Updated NOTICE

- map/crown.cpp
https://jira.mail.ru/browse/MAPSME-11860
> [core] Changed supported launguages list for crown showing

- iphone/Maps/Bookmarks/Catalog/BookmarksSubscriptionViewController.xib
- iphone/Maps/Bookmarks/Catalog/PaidRouteViewController.swift
https://jira.mail.ru/browse/MAPSME-11869
> [iOS] replace some subscription-related strings

- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-11875
> [iOS] fix empty catalog promo in PP

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
https://jira.mail.ru/browse/MAPSME-11840
> [iOS] reload catalog after subscription purchase

- drape/support_manager.cpp
https://jira.mail.ru/browse/MAPSME-11810
> Banned PowerVR Rogue GE8300 for Vulkan

- iphone/Maps/UI/Downloader/DataSources/MWMMapDownloaderExtendedDataSourceWithAds.mm
https://jira.mail.ru/browse/MAPSME-10599
> [iOS] don't show baneer on downloads screen when ads removal is active

- iphone/Maps/Core/Search/MWMSearch.mm
- map/framework.cpp
- map/framework.hpp
> [map] Got rid of the old style std/ includes in Framework.

- android/res/values/colors.xml
- android/src/com/mapswithme/maps/analytics/PushWooshEventLogger.java
- android/src/com/mapswithme/maps/background/Notifier.java
- android/src/com/mapswithme/util/UiUtils.java
https://jira.mail.ru/browse/MAPSME-9927
> [android] Changed notification icon and text color, blue->green

- storage/storage.cpp
> [storage] checking mwm directory creation result is added.

- android/src/com/mapswithme/maps/promo/CatalogPromoController.java
- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageButtonsListener.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-11877
@beloal FYI
> Mapsme 11877 fix bookmark behaviour in sightseen pp

- generator/cross_mwm_osm_ways_collector.cpp
- generator/generator_tests/cross_mwm_osm_ways_collector_tests.cpp
Если последняя точка фичи лежала ровно на границе, то не выполнялось условие, что:
```cpp
существует точка A и точка B, такие что, что A внутри/снаружи, B снаружи/внутри
```
потому что в таком случае обе точке будут внутри, но тем не менее сегмент будет переходным
> [generator] Fix cross mwm way collector

- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Common/Statistics/StatisticsStrings.h
https://jira.mail.ru/browse/MAPSME-11859
> [iOS] update stats for wiki description

- android/jni/com/mapswithme/maps/Framework.cpp
- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.h
- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm
- iphone/Maps/Core/Framework/ProxyObjects/Routing/MWMRoutingManager.mm
- iphone/Maps/Core/Routing/MWMRouter.mm
- map/map_tests/gps_track_collection_test.cpp
- map/routing_manager.hpp
- platform/location.hpp
- platform/settings.cpp
- qt/draw_widget.cpp
- routing/CMakeLists.txt
- routing/following_info.hpp
- routing/routing_session.hpp
- routing/turns_notification_manager.hpp
- xcode/routing/routing.xcodeproj/project.pbxproj
@tatiana-yan @gmoryes @LaGrunge
> Removing a dependency. Platform does not depend on routing anymore.

- iphone/Maps/Categories/NSAttributedString+HTML.swift
https://jira.mail.ru/browse/MAPSME-11910
> [iOS] fix font in HTML descriptions

- iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-11492
> [iOS] fix white screen on CarPlay

- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
https://jira.mail.ru/browse/MAPSME-11927
> [android] Changed pp preview plus ration on 45%

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.h
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
https://jira.mail.ru/browse/MAPSME-11971
> [iOS] send aloha id to catalog

- 3party/icu/CMakeLists.txt
Подавил warning в ` 3party/icu/`
Any C++ PTAL
> Suppressing warning in icu.

- iphone/Maps/Bookmarks/BookmarksVC.mm
due to usage of undocumented API
> [iOS] remove search progress spinner from bookmarks list

- generator/cross_mwm_osm_ways_collector.cpp
Should be fixed after: https://github.com/mapsme/omim/pull/10996
But until it is not merged...
> [generator] Fix cross mwm collector ways

- android/jni/com/mapswithme/maps/DownloadResourcesLegacyActivity.cpp
- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/MapManager.cpp
- android/jni/com/mapswithme/maps/SearchEngine.cpp
- android/jni/com/mapswithme/maps/Sponsored.cpp
- android/jni/com/mapswithme/maps/TrackRecorder.cpp
- android/jni/com/mapswithme/maps/UserMarkHelper.cpp
- android/jni/com/mapswithme/maps/editor/Editor.cpp
- android/jni/com/mapswithme/maps/editor/OpeningHours.cpp
- android/jni/com/mapswithme/maps/promo/Promo.cpp
- android/jni/com/mapswithme/maps/ugc/UGC.cpp
- android/jni/com/mapswithme/platform/HttpThread.cpp
- android/jni/com/mapswithme/util/HttpClient.cpp
- local_ads/campaign_serialization.cpp
- platform/network_policy.hpp
> [android] Fixed some warnings.

- generator/generator_integration_tests/features_tests.cpp
Поправлены тесты, после исправления популярити и добавления новых типов(парковочные места, лэндюзы)
> [generator] Fixed integration tests.

- android/res/layout/place_page_description_layout.xml
https://jira.mail.ru/browse/MAPSME-11981
> [android] Changed textview of pp desc according to Zeplin

- generator/generator_tool/generator_tool.cpp
- generator/processor_booking.hpp
- generator/processor_coastline.cpp
- generator/processor_country.cpp
- generator/processor_factory.hpp
- generator/processor_interface.hpp
- generator/processor_simple.cpp
- generator/processor_simple.hpp
- generator/processor_world.cpp
- generator/translator.cpp
- generator/translator.hpp
- generator/translator_coastline.cpp
- generator/translator_collection.cpp
- generator/translator_collection.hpp
- generator/translator_country.cpp
- generator/translator_country.hpp
- generator/translator_factory.hpp
- generator/translator_world.cpp
Сделал clang-format некоторых файлов в генераторе
> [generator] Clang-format

- iphone/Maps/UI/Discovery/MWMDiscoveryCityGalleryObjects.h
- iphone/Maps/UI/Discovery/MWMDiscoveryCityGalleryObjects.mm
- iphone/Maps/UI/Discovery/MWMDiscoveryTableManager.mm
- iphone/Maps/UI/Discovery/Table Cells/Holders/DiscoveryCollectionHolderCell.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-11977
> [iOS] fix PP gallery header

- indexer/data_source.cpp
- platform/mwm_version.cpp
- platform/mwm_version.hpp
cherry-pick https://github.com/mapsme/omim/pull/11822 на мастер
> [platform][indexer] Do not register old mwms with 0 version (from data root).

- map/bookmark_manager.cpp
https://jira.mail.ru/browse/MAPSME-12042
https://jira.mail.ru/browse/MAPSME-12043
> [bookmarks] Sorting fixes.

- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
После старта на Android букмарки не отображались на карте.
> [bookmarks] Changes tracking fixed.

- android/src/com/mapswithme/maps/settings/HelpFragment.java
- android/src/com/mapswithme/maps/settings/StoragePathFragment.java
- android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-11987
> [android] Added attaching the logs to user feedback letter

- base/stl_helpers.hpp
- generator/CMakeLists.txt
- generator/complex_generator/CMakeLists.txt
- generator/complex_generator/complex_generator.cpp
- generator/feature_sorter.cpp
- generator/filter_complex.cpp
- generator/filter_complex.hpp
- generator/final_processor_intermediate_mwm.cpp
- generator/final_processor_intermediate_mwm.hpp
- generator/gen_mwm_info.cpp
- generator/gen_mwm_info.hpp
- generator/generator_tool/generator_tool.cpp
- generator/hierarchy.cpp
- generator/hierarchy.hpp
- generator/place_node.hpp
- generator/processor_complex.cpp
- generator/processor_complex.hpp
- generator/processor_factory.hpp
- generator/processor_interface.hpp
- generator/translator_complex.cpp
- generator/translator_complex.hpp
- generator/translator_factory.hpp
- generator/translator_interface.hpp
- generator/utils.cpp
- generator/utils.hpp
- indexer/ftypes_matcher.cpp
- indexer/ftypes_matcher.hpp
Грепнем по id Московского кремля:
до
```
$ grep "13835058055283524353" popularity-src_coords.csv
13835058055283524411;13835058055283524353;55.7512149;37.6201355;leisure-park;Grand Kremlin Square
13835058055283524389;13835058055283524353;55.7500727;37.6187242;leisure-park;Tainitsky Garden
13835058055283524353;;55.7494424;37.6160136;tourism-attraction;Московский Кремль
```
после
```
$ grep "1360641" /home/andrianov/output.txt 
Osm Node 2368886170;Osm Relation 1360641;2;37.6164;67.454;tourism-museum;Tsarina's Golden Chamber
Osm Node 311999396;Osm Relation 1360641;2;37.6179;67.4554;tourism-attraction;Царь-пушка
Osm Node 2368886164;Osm Relation 1360641;2;37.6157;67.4539;tourism-museum;Terem Palace
Osm Node 311999397;Osm Relation 1360641;2;37.6185;67.4542;tourism-attraction;Tsar Bell
Osm …
```
> [generator] Added complex_generator

- android/src/com/mapswithme/maps/settings/HelpFragment.java
- android/src/com/mapswithme/maps/settings/StoragePathFragment.java
- android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-11987
> [android] Rolled back sd failure subject for feedback letter

- android/gradle.properties
https://jira.mail.ru/browse/MAPSME-11555
> [android] target sdk 28 support

- drape_frontend/my_position_controller.cpp
https://jira.mail.ru/browse/MAPSME-12050
> [drape] Fixed false my position snapping

- drape_frontend/my_position_controller.cpp
cherry-pick https://github.com/mapsme/omim/pull/11860
> [cherry-pick][drape] Fixed false my position snapping

- generator/osm2type.cpp
https://github.com/mapsme/omim/issues/11841
> [generator] Process chipseal as paved tag

- coding/coding_tests/csv_reader_test.cpp
- coding/csv_reader.cpp
- coding/csv_reader.hpp
- generator/popular_places_section_builder.cpp
- indexer/ftraits.hpp
https://jira.mail.ru/browse/MAPSME-11715
https://github.com/mapsme/omim/pull/11791 был закрыт
> [coding] Rewritten CSVReader.

- android/gradle.properties
This reverts commit ba5341f8fe40c88d6abf83184afa5b876e68b10b.
> Revert "[android] target sdk 28 support"

- map/notifications/notification_queue_storage.cpp
DNM до раската хотфикса
https://jira.mail.ru/browse/MAPSME-12144
> [notifications] empty file loading fix

- partners_api/promo_api.cpp
DNM пока не раскатан хотфикс
https://jira.mail.ru/browse/MAPSME-12135
> DNM [promo] city id is optional now.

- android/build.gradle
https://jira.mail.ru/browse/MAPSME-12126
DNM while @burivuh don't release 9.4 hotfix.
> [android] Updated Pushwoosh sdk to fix battery issue

- android/gradle.properties
https://jira.mail.ru/browse/MAPSME-11555
> [android] Updated target sdk to 28

- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
https://jira.mail.ru/browse/MAPSME-11606
> [iOS] show map download dialog below other controls

- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMiPhonePlacePageLayoutImpl.mm
https://jira.mail.ru/browse/MAPSME-11928
> [iOS] Change PP preview+ to 45%

- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
https://jira.mail.ru/browse/MAPSME-12116
> [iOS] show wiki description in PP while offline

- iphone/Maps/Bookmarks/Catalog/PaidRouteViewController.swift
- iphone/Maps/Bookmarks/Catalog/PaidRouteViewController.xib
https://jira.mail.ru/browse/MAPSME-11929
> [iOS] limit min header image height

- iphone/Maps/Maps.xcodeproj/project.pbxproj
> [iOS] update code signing settings for new profile

- data/strings/types_strings.txt
Some autocorrection from previous update
> Added and fixed Polish phrases

- android/res/layout/item_bookmark_category_choose.xml
https://jira.mail.ru/browse/MAPSME-12132
> [android] Reverted previous changes that produce this bug

- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
https://jira.mail.ru/browse/MAPSME-12192
> [iOS] fix map download dialog

- partners_api/promo_catalog_types.cpp
https://jira.mail.ru/browse/MAPSME-12148
> [promo] Added place_of_worship type

- indexer/classificator.cpp
> [indexer] Simplified Classificator::GetTypeByReadableObjectName

- base/string_utils.cpp
- base/string_utils.hpp
фнукция которой часто не хватало, решил поместить ее сюда
позже будет использоваться в комплексах
> [base] Added  bool to_size_t(std::string const & s, size_t & i).

- iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.swift
- iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.xib
- iphone/Maps/Bookmarks/Catalog/Subscription/BaseSubscriptionViewController.swift
- iphone/Maps/Bookmarks/Catalog/Subscription/BookmarksSubscriptionDiscountLabel.swift
- iphone/Maps/Bookmarks/Catalog/Subscription/BookmarksSubscriptionViewController.swift
- iphone/Maps/Bookmarks/Catalog/Subscription/BookmarksSubscriptionViewController.xib
- iphone/Maps/Maps.xcodeproj/project.pbxproj
All shared functionality for AllPassSubscriptionViewController and BookmarksSubscriptionViewController has been moved into BaseSubscriptionViewController (configure, loading, purchase, SubscriptionManagerListener, etc.)
> [iOS] Subscrition ViewControllers refactoring

- indexer/mwm_set.hpp
- routing/cross_mwm_graph.cpp
- routing/cross_mwm_index_graph.hpp
- search/house_to_street_table.cpp
- search/house_to_street_table.hpp
- search/lazy_centers_table.cpp
- search/lazy_centers_table.hpp
- search/mwm_context.hpp
- search/retrieval.cpp
меня смутил тот факт, что метод константный, а возвращает не константный указатель
пофиксил это
> [indexer] Add const to MwmValue *

- android/res/layout/subscription_button.xml
- android/res/values/attrs.xml
- android/src/com/mapswithme/maps/widget/SubscriptionButton.java
https://jira.mail.ru/browse/MAPSME-12207
> [android] Implemented subscription button layout and custom view

- geometry/area_on_earth.cpp
- geometry/distance_on_sphere.cpp
- geometry/distance_on_sphere.hpp
> [geometry] Fix area geometry tests

- android/build.gradle
- android/gradle.properties
https://jira.mail.ru/browse/MAPSME-12264
> Mapsme 12264 crash during update push token

- iphone/Maps/Bookmarks/BookmarksVC.mm
https://jira.mail.ru/browse/MAPSME-12120
> [iOS] Sharing Options пустой группы активна при тапе на More

- generator/hierarchy.cpp
- generator/hierarchy.hpp
- generator/hierarchy_entry.cpp
- generator/hierarchy_entry.hpp
- indexer/complex/tree_node.hpp
- indexer/indexer_tests/tree_node_tests.cpp
Функции пригодятся в следующих реквестах.
Примерное использование можно посмотреть в черновике: https://github.com/mapsme/omim/pull/11904
> [indexer] Added methods for tree node, added class Forest.

- android/src/com/mapswithme/maps/widget/placepage/Sponsored.java
- android/src/com/mapswithme/util/statistics/Statistics.java
- map/framework.cpp
- map/place_page_info.hpp
- map/promo_catalog_poi_checker.hpp
- partners_api/promo_catalog_types.cpp
- partners_api/promo_catalog_types.hpp
тип в PP для прогулок за городом по аналогии с достопримечательностями.
Прокинул сразу в Java, чтоб не крэшилось
https://jira.mail.ru/browse/MAPSME-12277
fyi @Polas
> [promo] new promo gallery type Outdoor is added

- partners_api/promo_api.cpp
- partners_api/promo_api.hpp
https://jira.mail.ru/browse/MAPSME-12213
> [promo] Timeout 5 sec for promo galleries

- iphone/Maps/Bookmarks/Catalog/CatalogCategoryCell.swift
- iphone/Maps/Bookmarks/Categories/Categories/BMCCategoryCell.swift
- iphone/Maps/Categories/MWMCategory+PlacesCountTitle.swift
- iphone/Maps/Classes/CarPlay/Template Builders/ListTemplateBuilder.swift
- iphone/Maps/Maps.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-12064
> [iOS] Fix tracks/objects count in bookmarks

- android/res/layout/fragment_sightseeing_subscription.xml
- android/res/layout/subscription_button.xml
- android/res/values/attrs.xml
- android/res/values/dimens.xml
- android/src/com/mapswithme/maps/widget/SubscriptionButton.java
https://jira.mail.ru/browse/MAPSME-12309
> [android] Added progress bar into subscription button layout

- geometry/CMakeLists.txt
- geometry/circle_on_earth.cpp
- geometry/circle_on_earth.hpp
- geometry/geometry_tests/CMakeLists.txt
- geometry/geometry_tests/circle_on_earth_tests.cpp
- geometry/geometry_tests/point3d_tests.cpp
- geometry/point3d.hpp
- xcode/geometry/geometry.xcodeproj/project.pbxproj
Этот PR нужен для составления круговых границ городов, посколько радиусы городов могут быть большими, нельзя просто нарисовать круг в меркаторе, получается большая погрешность
как это выглядит на всем мире (все круги одинакового радиуса, нарисованные с помощью этого PR)
> [geometry] Circle on earth

- indexer/feature.hpp
- mapshot/CMakeLists.txt
- mapshot/mapshot.cpp
- software_renderer/cpu_drawer.hpp
- software_renderer/feature_processor.cpp
- software_renderer/feature_processor.hpp
- software_renderer/feature_styler.cpp
- software_renderer/feature_styler.hpp
- software_renderer/frame_image.hpp
- software_renderer/geometry_processors.cpp
- software_renderer/geometry_processors.hpp
- software_renderer/glyph_cache.cpp
- software_renderer/glyph_cache_impl.cpp
- software_renderer/pen_info.hpp
- software_renderer/proto_to_styles.cpp
- software_renderer/software_renderer.cpp
- software_renderer/software_renderer.hpp
- software_renderer/text_engine.cpp
Fixed issue https://github.com/mapsme/omim/issues/11976
> [software_renderer] Fixed mapshot tool compilation and linking.

- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/purchase/AbstractBookmarkSubscriptionFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionPaymentState.java
- android/src/com/mapswithme/maps/purchase/PurchaseFactory.java
- android/src/com/mapswithme/maps/purchase/SubscriptionType.java
- android/src/com/mapswithme/maps/purchase/SubscriptionUiChangeListener.java
- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
https://jira.mail.ru/browse/MAPSME-12280
> Mapsme 12280 generalize subscription code

- iphone/Maps/Categories/NSAttributedString+HTML.swift
https://jira.mail.ru/browse/MAPSME-12001
> [iOS] PP: Bookmarks crash fix on unsupported image formats

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
https://jira.mail.ru/browse/MAPSME-12226
> [iOS] Add back button to catalog navigation bar

- docs/PR_GUIDE.md
Коллеги предлагаю всем разработчикам договориться о правилах составления PR-ов и проведения ревью. В данном PR предлагаю версию документа.
Прошу комментировать. Дополнять п-тами и т.п.
@all PTAL
> [docs] PR Guide.

- iphone/Maps/UI/Discovery/MWMDiscoveryController.mm
https://jira.mail.ru/browse/MAPSME-12201
> [iOS] Reordered blocks in Discovery View

- generator/osm2type.cpp
- generator/search_index_builder.cpp
- indexer/feature_data.cpp
- indexer/feature_data.hpp
- indexer/feature_meta.hpp
Place записывался, но никогда не читался.
Postcode сейчас тоже не читается, но дальше планирую удалять FMD_POSTCODE и использовать в AddrData.
> [indexer] AddressData minor refactoring, remove unused code.

- search/geocoder.cpp
- search/search_integration_tests/processor_test.cpp
https://github.com/mapsme/omim/issues/11599
> [search] Add relaxed search for cities.

- generator/city_roads_generator.cpp
- generator/city_roads_generator.hpp
- generator/collector_routing_city_boundaries.cpp
- generator/collector_routing_city_boundaries.hpp
- generator/final_processor_intermediate_mwm.cpp
- generator/final_processor_intermediate_mwm.hpp
- generator/generator_tests/city_roads_tests.cpp
- generator/generator_tests/collector_routing_city_boundaries_tests.cpp
- generator/generator_tool/generator_tool.cpp
- generator/raw_generator.cpp
- generator/routing_city_boundaries_processor.cpp
- generator/routing_city_boundaries_processor.hpp
- generator/translator_country.cpp
- routing/city_roads_serialization.hpp
- routing/routing_helpers.hpp
Результаты сравнения размера секции до и после на примере Франции: https://pastebin.com/SevgZjRF
Велики + машина:
https://pastebin.com/1LB8f2hS
Выбрал Францию, как страну с кучей деревень и плотной постановкой городов
https://confluence.mail.ru/pages/viewpage.action?pageId=287950469
> [generator] Improve city boundaries, serialize to section

- base/base_tests/cancellable_tests.cpp
- base/cancellable.cpp
- base/cancellable.hpp
- map/map_tests/search_api_tests.cpp
Review fixes for https://github.com/mapsme/omim/pull/11933.
> [base] Made the call to CancellationStatus update the status before return.

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bookmarks/Catalog/Dialogs/SubscriptionGoToCatalogViewController.swift
- iphone/Maps/Bookmarks/Catalog/Dialogs/SubscriptionSuccessViewController.swift
- iphone/Maps/Bookmarks/Catalog/PaidRouteViewController.swift
- iphone/Maps/Bookmarks/Catalog/Subscription/BaseSubscriptionViewController.swift
- iphone/Maps/Core/Subscriptions/SubscriptionGroup.swift
https://jira.mail.ru/browse/MAPSME-12424
> [iOS] CatalogWebView: new parameter  in urls for subscription groups

- generator/generator_integration_tests/features_tests.cpp
> [tests] Fixed generator integration tests.

- tools/python/maps_generator/README.md
Уточнение для сторонних разработчиков
https://github.com/mapsme/omim/issues/12078
> [doc] Minor documentation improvement.

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bookmarks/Catalog/Dialogs/SubscriptionGoToCatalogViewController.swift
- iphone/Maps/Bookmarks/Catalog/Dialogs/SubscriptionSuccessViewController.swift
- iphone/Maps/Bookmarks/Catalog/PaidRouteViewController.swift
- iphone/Maps/Bookmarks/Catalog/Subscription/BaseSubscriptionViewController.swift
- iphone/Maps/Bookmarks/Catalog/Subscription/SubscriptionViewBuilder.swift
- iphone/Maps/Bookmarks/Catalog/UIViewController+Subscription.swift
- iphone/Maps/Classes/CustomViews/MapViewControls/PromoButton/PromoButton.swift
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
- iphone/Maps/Core/DeepLink/Strategies/DeepLinkSubscriptionStrategy.swift
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.h
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.mm
- iphone/Maps/Core/Subscriptions/Subscription.swift
- iphone/Maps/Core/Subscriptions/SubscriptionManager.swift
- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
- iphone/Maps/UI/Welcome/PromoDiscovery/PromoDiscoveryRouter.swift
- map/purchase.hpp
https://jira.mail.ru/browse/MAPSME-12289
> [iOS] Business logic AllPass/Sightseeing

- android/src/com/mapswithme/util/UTM.java
- partners_api/utm.hpp
https://jira.mail.ru/browse/MAPSME-12307
> Added new values for Utm

- android/src/com/mapswithme/maps/downloader/BottomPanel.java
- android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java
- android/src/com/mapswithme/maps/downloader/DownloaderToolbarController.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-12286
> Added all-pass subscriptions stats

- android/src/com/mapswithme/maps/SplashActivity.java
- android/src/com/mapswithme/maps/news/OnboardingStep.java
- android/src/com/mapswithme/maps/onboarding/WelcomeDialogFragment.java
- android/src/com/mapswithme/util/Counters.java
https://jira.mail.ru/browse/MAPSME-12302
> [android] Implemented sliding of onboarding screens on splash activity

- routing/index_router.cpp
- routing/index_router.hpp
ф-ия CalculateSubroute  слишком длинная, вынес блок кода выбора типа роутинга в отдельную ф-ию
> [routing] Add SetupAlgorithmMode, move block of code to private method

- coding/coding_tests/zip_creator_test.cpp
- coding/zip_creator.cpp
- coding/zip_creator.hpp
This PR implements the wrapper function over minizip for archiving multiple files together. Compression level is an optional parameter.
This function is the optimal way of preparing tracks for platform-specific task manager in the [PR about the historical data.](https://github.com/mapsme/omim/pull/12024)
> [Coding] Zip multiple files in a single archive.

- data/strings/types_strings.txt
так как ждем ответа по pl у @strebski, строки пока не генерировал
> Translations

- android/src/com/mapswithme/maps/purchase/PurchaseFactory.java
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.mm
- map/crown.cpp
- map/purchase.cpp
- map/purchase.hpp
- platform/marketing_service.cpp
- platform/marketing_service.hpp
https://jira.mail.ru/browse/MAPSME-12473
> [core] subscription type is added

- android/src/com/mapswithme/maps/purchase/PurchaseFactory.java
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.mm
- map/crown.cpp
- map/purchase.cpp
- map/purchase.hpp
- platform/marketing_service.cpp
- platform/marketing_service.hpp
@Polas @alexzatsepin FYI
https://github.com/mapsme/omim/pull/12111
> [cherry-pick][core] subscription type is added

- android/src/com/mapswithme/maps/news/OnboardingStep.java
- android/src/com/mapswithme/maps/onboarding/BaseNewsFragment.java
- android/src/com/mapswithme/maps/onboarding/WelcomeDialogFragment.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-12306
> Added statistics for onboarding screens

- map/onboarding.cpp
https://jira.mail.ru/browse/MAPSME-12307
> [onboarding] correct way to inject utm

- android/res/layout/fragment_discovery.xml
https://jira.mail.ru/browse/MAPSME-12202
> [android] Changed discovery galleries order

- iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.xib
Fixed localization and description content size
> [iOS] Fixed description labels in AllPassSubscriptionView

- iphone/Maps/UI/PlacePage/MWMPlacePageData.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- map/framework.cpp
- map/framework.hpp
Partial reverse of the commit bffa6b4 (Refactored place page info), which leads to reloadData before performBatchUpdate on PlacePage's tableView
> [RELEASE_ONLY][iOS] Fixed crash in PlacePage on add/delete bookmark

- android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
- android/src/com/mapswithme/maps/intent/Factory.java
https://jira.mail.ru/browse/MAPSME-12507
> Mapsme 12507 subscription deeplink

- android/src/com/mapswithme/maps/intent/Factory.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentDataParser.java
- android/src/com/mapswithme/maps/purchase/PurchaseUtils.java
https://jira.mail.ru/browse/MAPSME-12507
> [android] Changed parameter name in subscription deeplink

- map/catalog_headers_provider.cpp
https://jira.mail.ru/browse/MAPSME-12508
> [catalog] catalog headers duplication is fixed

- iphone/Maps/UI/Welcome/PromoDiscovery/PromoDiscoveryPresenter.swift
- iphone/Maps/UI/Welcome/TermsOfUse/TermsOfUsePresenter.swift
- iphone/Maps/UI/Welcome/WelcomePageController.swift
- iphone/Maps/UI/Welcome/WelcomeView/WelcomeViewController.swift
Add modal presentation for iPad, fix missed localizations
> [iOS] Fixed layout and localization in Onboarding views

- iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkSubscriptionData.h
- iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkSubscriptionData.mm
- iphone/Maps/Core/DeepLink/Strategies/DeepLinkSubscriptionStrategy.swift
- map/mwm_url.cpp
- map/mwm_url.hpp
> [iOS] Changed parameter name in subscription deeplink

- defines.hpp
- generator/CMakeLists.txt
- generator/collector_boundary_postcode.cpp
- generator/collector_boundary_postcode.hpp
- generator/collector_interface.hpp
- generator/translator_country.cpp
В этом реквесте сохранение outer геометрии для релейшенов type=boundary + boundary=postal_code + postal_code=... в промежуточный файл, дальше будут два реквеста -- с тестами и с использованием.
Тесты хочу делать отдельным реквестом, т.к. реквест с тестами получился больше чем основной, думаю так будет проще смотреть.
> [generator] Collect relation boundary=postal_code to tmp file.

- .clang-format
https://releases.llvm.org/8.0.0/tools/clang/docs/ClangFormatStyleOptions.html
> [omim] Add param for clang-format for sorting each block separately

- android/code_style_sheme.xml
Выгрузил из android studio схему код стайла и добавил в папку андроид, чтобы сторонние разработчики могли импортировать ее в свою IDE и форматировать код согласно нашему код стайлу.
> [android] Exported android studio code style scheme in repo

- data/countries.txt
- data/external_resources.txt
Новая версия, для релиза со странами от Жени для countries.txt.
> [planet] New data from 24.11.2019

- iphone/Maps/Bookmarks/Catalog/Subscription/BaseSubscriptionViewController.swift
https://jira.mail.ru/browse/MAPSME-12547
> [iOS] Change discount label localization in Subscription views

- iphone/Maps/UI/Welcome/FirstLaunch/FirstLaunchPresenter.swift
- iphone/Maps/UI/Welcome/TermsOfUse/TermsOfUseViewController.swift
https://jira.mail.ru/browse/MAPSME-12546
> [iOS] Fixed missing statistics

- android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-12531
> [android] Added orientation changes check for  on boarding btn

- map/onboarding.cpp
https://jira.mail.ru/browse/MAPSME-12560
> [core] Added lang to the onboarding tip url

- geometry/geometry_tests/CMakeLists.txt
- geometry/geometry_tests/polyline_tests.cpp
- geometry/polyline2d.hpp
Рефакторинг. Добавил функциональности в ранее не используемый метод: Polyline ::CalcMinSquaredDistance()
Добавил тесты на Polyline в целом и особенно на метод: olyline ::CalcMinSquaredDistance()
P.S. В xcode не добавил специально. Сейчас тесты в xcode вообще не работают. Договорился с @beloal о варианте починки. Сделаю отдельным PR-ом, тогда и добавлю.
> [geometry] polyline refactoring and tests.

- android/src/com/mapswithme/maps/permissions/BasePermissionsDialogFragment.java
- android/src/com/mapswithme/maps/permissions/PermissionsDialogFragment.java
https://jira.mail.ru/browse/MAPSME-12541
> [android] Added stats for permission screen

- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.h
- iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
- iphone/Maps/UI/Settings/MWMAboutController.m
- iphone/Maps/UI/Settings/MWMAboutControllerHeader.xib
https://jira.mail.ru/browse/MAPSME-12569
> [iOS] fix data version format

- base/base.cpp
- base/logging.cpp
- base/logging.hpp
> [base] Add TID to message at CHECK/ASSERT

- iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.swift
- iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.xib
- iphone/Maps/Bookmarks/Catalog/Subscription/BaseSubscriptionViewController.swift
- iphone/Maps/Bookmarks/Catalog/Subscription/BookmarksSubscriptionViewController.swift
Fixed view controller orientation for iphone, discount label constraints, description stackView
> [iOS] Fixed layout in Subscription Views

- routing/base/astar_algorithm.hpp
синяя - новый вариант, желтая - старый
Согласно профайлеру
Среднее время построения меньше на 5%
> [routing] Save heuristic to State

- map/map_tests/countries_names_tests.cpp
cherry-pick https://github.com/mapsme/omim/pull/12161
так как вливание https://github.com/mapsme/omim/pull/12199  сломало тесты в мастере
> [map] CountriesNamesTest is fixed

- indexer/ftypes_matcher.cpp
- routing/bicycle_directions.cpp
- routing/routing_integration_tests/pedestrian_route_test.cpp
- routing/routing_integration_tests/route_test.cpp
- routing/routing_integration_tests/transit_route_test.cpp
cherry-pick https://github.com/mapsme/omim/pull/12183/ any C++
Поправил routing integration tests для 191124.
> [routing] Routing integration tests fixing.

- android/res/drawable/bookmarks_sightseeing_subs_central_content_bg.xml
- android/res/layout-w600dp/fragment_sightseeing_subscription.xml
- android/res/values/colors.xml
- android/res/values/dimens.xml
https://jira.mail.ru/browse/MAPSME-12402
> [android] Added tablet layout for SightSeeing Sub Fragment

- map/bookmark_catalog.cpp
- map/onboarding.cpp
- partners_api/promo_api.cpp
https://jira.mail.ru/browse/MAPSME-12583
> [core] Set new mobile front catalog api version

- pyhelpers/pair.hpp
- tracking/pytracking/bindings.cpp
- traffic/pytraffic/CMakeLists.txt
- traffic/pytraffic/bindings.cpp
Fixed building of python bindings:
pyhelpers
pytracking
pytraffic
> [Python bindings] Fixes for pyhelpers and other subprojects

- routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp
cherry-pick https://github.com/mapsme/omim/pull/12214
@mesozoic-drones or @gmoryes PTAL
> [routing] Fixing rqt RoutingQuality_IranSouth.

- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
https://jira.mail.ru/browse/MAPSME-12109
> [iOS] fix bug in which offline description not displayed for some points

- track_generator/pytrack_generator/bindings.cpp
Temporary workaround for building bindings. Will be fixed later:
https://jira.mail.ru/browse/MAPSME-12589
> [Python bindings] commented pytrack_generator bindings

- pyhelpers/pair.hpp
- search/pysearch/bindings.cpp
- track_generator/pytrack_generator/bindings.cpp
- tracking/pytracking/bindings.cpp
- traffic/pytraffic/CMakeLists.txt
- traffic/pytraffic/bindings.cpp
fixes building of all our python bindings
> Pybindings fixes cherry-pick to release 95

- android/res/layout/fragment_bookmarks_all_subscription.xml
- android/res/layout/pager_fragment_bookmarks_all_subscription.xml
- android/res/values-w600dp/dimens.xml
- android/res/values-w600dp/integer.xml
- android/res/values/dimens.xml
- android/res/values/font_sizes.xml
- android/res/values/integer.xml
https://jira.mail.ru/browse/MAPSME-12587
> Mapsme 12587 fix design for all pass screen

- generator/CMakeLists.txt
- generator/generator_tests_support/test_mwm_builder.cpp
- generator/generator_tool/generator_tool.cpp
- generator/postcode_points_builder.cpp
- generator/postcode_points_builder.hpp
- generator/search_index_builder.cpp
- generator/search_index_builder.hpp
Разделила файлы и переименовала функцию (чтобы не путать с BuldPostcodesSection).
XCode или сделаю в отдельном реквесте или если @bykoianko успеет сделать PR с починкой XCode отребейжусь на него.
> [generator][search] Move postcode_points section build to separate file.

- storage/storage_integration_tests/CMakeLists.txt
- storage/storage_integration_tests/download_calc_size_test.cpp
> [storage] Adding storage/storage_integration_tests/download_calc_size_test.cpp and fixing DownloadingTests_CalcOverallProgress().

- xcode/base/base.xcodeproj/project.pbxproj
- xcode/coding/coding.xcodeproj/project.pbxproj
- xcode/editor/editor.xcodeproj/project.pbxproj
- xcode/generator/generator.xcodeproj/project.pbxproj
- xcode/generator_tool/generator_tool.xcodeproj/project.pbxproj
- xcode/geometry/geometry.xcodeproj/project.pbxproj
- xcode/indexer/indexer.xcodeproj/project.pbxproj
- xcode/kml/kml.xcodeproj/project.pbxproj
- xcode/local_ads/local_ads.xcodeproj/project.pbxproj
- xcode/map/map.xcodeproj/project.pbxproj
- xcode/metrics/metrics.xcodeproj/project.pbxproj
- xcode/partners_api/partners_api.xcodeproj/project.pbxproj
- xcode/platform/platform.xcodeproj/project.pbxproj
- xcode/routing/routing.xcodeproj/project.pbxproj
- xcode/routing_common/routing_common.xcodeproj/project.pbxproj
- xcode/search/search.xcodeproj/project.pbxproj
- xcode/shaders/shaders.xcodeproj/project.pbxproj
- xcode/storage/storage.xcodeproj/project.pbxproj
- xcode/traffic/traffic.xcodeproj/project.pbxproj
- xcode/ugc/ugc.xcodeproj/project.pbxproj
Поправил все тесты и тулзы под xcode. 
- удалил plist из тестов
- добавил нужные файлы в проек и удалил не нужные файлы из xcode проекта
@beloal @Polas @any C++
> [xcode] Fixing all the tests and tools for MacOS.

- generator/collector_building_parts.cpp
- generator/collector_building_parts.hpp
- generator/generator_tests/CMakeLists.txt
- generator/generator_tests/collector_building_parts_tests.cpp
- generator/intermediate_data.hpp
В следующем реквесте вынесу код модификаций дерева из ComplexFinalProcessor в какое нибудь другое место, и напишу тесты для того кода
> [generator] Added CollectorBuildingParts tests.

- generator/generator_tests_support/test_mwm_builder.cpp
- generator/generator_tool/generator_tool.cpp
- generator/postcodes_section_builder.cpp
- generator/postcodes_section_builder.hpp
В этом реквесте посткоды сохраненные в BoundaryPostcodeCollector добавляются в секцию с посткодами. После этого они автоматически будут использоваться так же как если бы были сразу в фичах.
> [generator] Populate postcodes with data collected from boundary=postal_code.

- map/framework.cpp
Исправлена ошибка, когда при переходе к поисковому результату попадаем на рандомный PP.
https://jira.mail.ru/browse/MAPSME-12268
> Fixed filling of feature info in the place page.

- data/copyright.html
Ссылка на датасет: https://www.ordnancesurvey.co.uk/business-government/products/code-point-open
Лицензионные требования на странице датасета:
```
Our open data products are covered by the Open Government Licence (OGL), which allows you to:
- copy, distribute and transmit the data;
- adapt the data; and
- exploit the data commercially, whether by sub-licensing it, combining it with other data, or including it in your own product or application.
We simply ask that you acknowledge the copyright and the source of the data by including the following attribution statement:
- Contains OS data © Crown copyright and database right 2018
Where you use Code-Point Open data, you must also use the following attribution statements:
- Contains Royal Mail data © Royal Mail copyright and Database right …
```
> [data] Add copyright information for Code-Point Open dataset.

- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-12372
> [iOS] fix crash

- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
https://jira.mail.ru/browse/MAPSME-12570
> [iOS] dont show empty wiki description in place page

- iphone/Maps/UI/Search/MWMSearchManager.mm
https://jira.mail.ru/browse/MAPSME-12536
> [iOS] Show button 'View on map' in Search before complete

- generator/final_processor_intermediate_mwm.cpp
- generator/final_processor_intermediate_mwm.hpp
- generator/hierarchy.cpp
- generator/hierarchy.hpp
Перемещение нужно для написание тестов для функций, и для экономии строк в final_processor_intermediate_mwm
> [generator] Moved code to hierarchy.hpp|cpp

- android/src/com/mapswithme/maps/onboarding/WelcomeDialogFragment.java
- android/src/com/mapswithme/util/UiUtils.java
- android/src/com/mapswithme/util/sharing/BookmarkInfoShareable.java
https://jira.mail.ru/browse/MAPSME-12610
> [android] Changed strings for welcome screen (title, subtitle)

- map/bookmark_helpers.cpp
https://jira.mail.ru/browse/MAPSME-12586
> [bookmarks] Minor update of transport bookmark type mapping.

- generator/final_processor_intermediate_mwm.cpp
- generator/final_processor_intermediate_mwm.hpp
- generator/generator_tests/CMakeLists.txt
- generator/generator_tests/hierarchy_tests.cpp
- generator/hierarchy.cpp
- generator/hierarchy.hpp
- xcode/generator_tool/generator_tool.xcodeproj/project.pbxproj
Когда писал тест, то переписал немного кода, что бы конструктор HierarchyBuilder принимал фичи билдеры, а не путь к файлу
> [generator] Added some tests of hierarchy.

- iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.xib
- iphone/Maps/Categories/UIColor+MapsMeColor.h
- iphone/Maps/Categories/UIColor+MapsMeColor.m
- iphone/Maps/UI/Welcome/PromoDiscovery/PromoDiscoveryRouter.swift
Also added half-opacity background and change font for discount
https://jira.mail.ru/browse/MAPSME-12611
> [iOS] Fixed present/dismiss order of All Pass subscription view from promo screen

- iphone/Maps/UI/Storyboard/Welcome.storyboard
https://jira.mail.ru/browse/MAPSME-12613
> [iOS] Fixed landscape constraints in Welcome Screen

- search/processor.cpp
- search/ranker.cpp
cherry-pick https://github.com/mapsme/omim/pull/12255
> [search] Fix NormalizeRank.

- generator/generator_integration_tests/features_tests.cpp
Починка интеграционного теста после починки мини-раундэбаутов.
> [generator] Fixed integration test.

- generator/intermediate_data.cpp
- generator/intermediate_data.hpp
> [generator] Fix warning

- generator/generator_tests/mini_roundabout_tests.cpp
- generator/mini_roundabout_transformer.cpp
> [generator] Fixed mini-roundabouts to roads matching.

- routing/routing_quality/routing_quality_tool/benchmark_stat.cpp
- routing/routing_quality/routing_quality_tool/benchmark_stat.hpp
- routing/routing_quality/routing_quality_tool/routing_quality_tool.cpp
поскольку возможных вариантов запуска становится больше, я порефакторил немного подсказки запуска, выглядит это так:
> [routing] refact argv help for routing_quality_tool

- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
- iphone/Maps/Classes/CustomViews/MapViewControls/PromoButton/PromoButton.swift
- iphone/Maps/Core/PromoCampaign/PromoDiscoveryCampaign/PromoDiscoveryCampaign.swift
https://jira.mail.ru/browse/MAPSME-12642
https://jira.mail.ru/browse/MAPSME-12641
> [iOS] Fixed discovery button behaviour

- kml/type_utils.hpp
- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-12228
> [bookmarks] no need to show PreviewPlus state when description is empty

- generator/generator_tests/mini_roundabout_tests.cpp
- generator/mini_roundabout_transformer.cpp
> [generator] Removed invalid check from mini-roundabouts.

- android/build.gradle
https://jira.mail.ru/browse/MAPSME-12592
> [android] Updated Flurry sdk to support California Consumer Privacy Act

- android/src/com/mapswithme/maps/search/SearchFragment.java
https://jira.mail.ru/browse/MAPSME-12652
> [android] Added push token hidden command

- indexer/ftypes_matcher.cpp
- indexer/ftypes_matcher.hpp
- search/ranker.cpp
- search/ranking_info.cpp
перенос изменений, сделанных в релизе на мастер
https://github.com/mapsme/omim/pull/12265
https://github.com/mapsme/omim/pull/12256
> [search] Tweak NormalizeRank and ranking coeffs, separate coeffs for categorial search.

- generator/feature_sorter.cpp
- generator/final_processor_intermediate_mwm.cpp
1. Перенес код удаляющий камеры из стадии построения индекса геометрии в стадию построения фичей. Xочется что бы по возможности фильтровка фичей приосиходила на этой стадии, что бы логика не размазывалась
2. Поправил комменты; убрал некоторые, на мой взгляд странные
3. Поправил код возврата если возникло исключение
> [generator] Rework GenerateFinalFeatures

- partners_api/promo_api.cpp
https://jira.mail.ru/browse/MAPSME-12667
> [android] Updated catalog gallery version

- partners_api/promo_api.cpp
https://jira.mail.ru/browse/MAPSME-12667
> [android][chpick] Updated catalog gallery version

- android/res/layout/pager_fragment_bookmarks_all_subscription.xml
- android/res/values/colors.xml
https://jira.mail.ru/browse/MAPSME-12637
> [android] Added overlay for All pass screen

- iphone/Maps/Core/NetworkPolicy/MWMNetworkPolicy+UI.m
https://jira.mail.ru/browse/MAPSME-12653
> [iOS] fix mobile internet permission

- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-12683
> Fixed deselection after tapping on empty place.

- tools/python/ResponseProvider.py
cherry pick from https://github.com/mapsme/omim/pull/12289
> cherry pick [promo] tests fix for promo gallery v2

- generator/complex_generator/complex_generator.cpp
- generator/feature_processing_layers.cpp
- generator/feature_processing_layers.hpp
- generator/processor_booking.hpp
- generator/processor_coastline.cpp
- generator/processor_coastline.hpp
- generator/processor_complex.cpp
- generator/processor_complex.hpp
- generator/processor_country.cpp
- generator/processor_country.hpp
- generator/processor_interface.hpp
- generator/processor_noop.hpp
- generator/processor_simple.cpp
- generator/processor_simple.hpp
- generator/processor_world.cpp
- generator/processor_world.hpp
- generator/raw_generator.cpp
- generator/translator.hpp
Оказалось ненужным, убрал эту возможность
если возникнет нужда в логе лучше через обычный LOG
> [generator] Removed LogBuffer.

- android/src/com/mapswithme/maps/search/SearchAdapter.java
- android/src/com/mapswithme/maps/search/SearchFragment.java
https://jira.mail.ru/browse/MAPSME-12679
> [android] Made 'View on map' button visible consistently during search

- android/res/layout/bookmark_payment_layout.xml
https://jira.mail.ru/browse/MAPSME-12660
> [android] Added padding to subscription button on single purchase screen

- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMiPhonePlacePageLayoutImpl.mm
https://jira.mail.ru/browse/MAPSME-12691
> [iOS] Fixed crash in UGC Add review from notifications

- iphone/Maps/Core/NetworkPolicy/MWMNetworkPolicy+UI.m
https://jira.mail.ru/browse/MAPSME-12653
> [iOS] fix mobile internet "Today" permission

- android/src/com/mapswithme/maps/analytics/FlurryEventLogger.java
https://jira.mail.ru/browse/MAPSME-12592
> Mapsme 12592 flurry coppa support

- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/Gallery/Photos/PhotosOverlayView.swift
https://jira.mail.ru/browse/MAPSME-12754
> [iOS] Fixed topAnchor constraint in PhotosOverlayView

- partners_api/ads_base.cpp
https://jira.mail.ru/browse/MAPSME-12740
> [ads] do not show banners on objects with outdoor gallery

- partners_api/ads_base.cpp
cherry-pick for https://github.com/mapsme/omim/pull/12327
> cherry-pick [ads] do not show banners on objects with outdoor gallery

- routing/routing_integration_tests/CMakeLists.txt
- routing/routing_integration_tests/roundabouts_tests.cpp
Integration tests for routes with mini-roundabouts.
> [Routing] Integration test for mini-roundabouts.

- android/jni/com/mapswithme/maps/Framework.cpp
https://jira.mail.ru/browse/MAPSME-12736
> [android] Fixed bookmark deleting via PP.

- data/categories.txt
- indexer/ftypes_matcher.cpp
сейчас не матчим адреса на такие улицы как https://www.openstreetmap.org/way/26469317
> [search] Add cycleway to streets list.

- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-12775
> [bookmarks][android] Fixed finding nearest bookmark.

- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-10515
> [editor] Fix street duplicates.

- android/src/com/mapswithme/maps/location/BaseLocationListener.java
- android/src/com/mapswithme/maps/location/LocationHelper.java
- android/src/com/mapswithme/maps/location/SensorHelper.java
https://jira.mail.ru/browse/MAPSME-12782
Этот PR исправляет проблему сильной тряски стрелки, обозначающей направление и местоположение пользователя на карте. Стрелка дрожит, резко меняет направление. Особенно если девайс в состоянии покоя или на низких скоростях. На это поступали жалобы пользователей и это стабильно воспроизводится на Андроид-девайсах. На iOS проблемы нет.
Причина: для определения направления мы использовали показания магнетометра (TYPE_MAGNETIC_FIELD) и планировали уточнять их данными с акселерометра (TYPE_ACCELEROMETER), но после считывания они не обрабатывались.
В PR магнетометр заменен на fused-сенсор [TYPE_ROTATION_VECTOR](https://source.android.com/devices/sensors/sensor-types#rotation_vector), объединяющий и стабилизирующий показания магнетометра, акселерометра и …
> [Android] Remove jitter for user arrow indicating direction.

- android/src/com/mapswithme/util/FileUploadWorker.java
- android/src/com/mapswithme/util/HttpBackgroundUploader.java
- android/src/com/mapswithme/util/HttpPayload.java
- android/src/com/mapswithme/util/HttpUploader.java
- android/src/com/mapswithme/util/KeyValue.java
https://jira.mail.ru/browse/MAPSME-12453
> [android] Added android work manager call

- iphone/Maps/Core/PromoCampaign/PaidRoutesSubscriptionCampaign/PaidRoutesSubscriptionCampaign.swift
https://jira.mail.ru/browse/MAPSME-12830
> [iOS] Fixed random in PaidRouteSubscriptionCampaign

- map/bookmark_catalog.cpp
https://jira.mail.ru/browse/MAPSME-12829
> [catalog] Default headers are added into downloading guide request.

- map/routing_manager.cpp
- routing/routing_session.cpp
cherry-pick https://github.com/mapsme/omim/pull/12367 to release-96
> [routing] Route rebuilding fix.

- map/bookmark_catalog.cpp
cherry pick https://github.com/mapsme/omim/pull/12371
> cherry-pick [catalog] Default headers are added into downloading guide request.

- data/mapcss-mapping.csv
добавила более популярный вариант указания типа дороги. 
highway=path + sac_scale=* встречается 422 798 раз
https://taginfo.openstreetmap.org/tags/highway=path#combinations
highway=path + route=hiking 3 173 раза
https://taginfo.openstreetmap.org/tags/highway=path#combinations
> [mapcss] Add [highway=path][sac_scale=hiking] selector for highway|path|hiking.

- map/routing_manager.cpp
- map/routing_manager.hpp
Background uploader на стороне Андроид-платформы уже готов к тестированию:
https://jira.mail.ru/browse/MAPSME-12453
Чтобы проверить его работу, нужно раскомментировать archival reporter.
https://jira.mail.ru/browse/MAPSME-12431
> [tracking] Uncomment archival reporter.

- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-12854
> [core] user marks now are more preferred against "my position"

- map/framework.cpp
cp for https://github.com/mapsme/omim/pull/12400
> cherry-pick [core] user marks now are more preferred against "my position"

- android/res/values/strings.xml
- android/src/com/mapswithme/maps/routing/ResultCodesHelper.java
- data/strings/strings.txt
https://jira.mail.ru/browse/MAPSME-12747
> Mapsme 12747 new appearance

- storage/http_map_files_downloader.cpp
- storage/map_files_downloader.cpp
https://jira.mail.ru/browse/MAPSME-12892
> [storage] incorrect downloading type after failed download is fixed

- map/place_page_info.cpp
https://jira.mail.ru/browse/MAPSME-12797
> [iOS] display coodrdinates in PP in decimal format by default

- map/routing_manager.cpp
- map/routing_manager.hpp
- platform/CMakeLists.txt
- platform/http_uploader_background_dummy.cpp
- tracking/archival_manager.cpp
- tracking/archival_manager.hpp
- tracking/archival_reporter.cpp
- tracking/archival_reporter.hpp
- xcode/platform/platform.xcodeproj/project.pbxproj
> [Testing] Added setters for ArchivalReporter

- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/maps/maplayer/BottomSheetItem.java
- android/src/com/mapswithme/maps/maplayer/Mode.java
- android/src/com/mapswithme/maps/maplayer/OnIsoLinesLayerToggleListener.java
- android/src/com/mapswithme/maps/maplayer/OnIsolinesLayerToggleListener.java
- android/src/com/mapswithme/maps/maplayer/ToggleMapLayerDialog.java
- android/src/com/mapswithme/maps/maplayer/isolines/IsoLinesManager.java
- android/src/com/mapswithme/maps/maplayer/isolines/IsolinesManager.java
https://jira.mail.ru/browse/MAPSME-12783
> [android] Added isolines jni

- iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm
https://jira.mail.ru/browse/MAPSME-12748
> [iOS] update text in "subway route not found" alert

- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
https://jira.mail.ru/browse/MAPSME-12755
> [iOS] Fixed bookmark synchonization update for BMCViewController

- iphone/CoreApi/CoreApi.xcodeproj/project.pbxproj
- iphone/CoreApi/CoreApi/Promo/PromoAfterBookingCampaignAdapter.h
- iphone/CoreApi/CoreApi/Promo/PromoAfterBookingCampaignAdapter.mm
- iphone/CoreApi/CoreApi/Promo/PromoAfterBookingData+Core.h
- iphone/CoreApi/CoreApi/Promo/PromoAfterBookingData.h
- iphone/CoreApi/CoreApi/Promo/PromoAfterBookingData.mm
- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
- iphone/Maps/Core/PromoCampaign/PromoAfterBookingCampaign/PromoAfterBookingCampaign.swift
https://jira.mail.ru/browse/MAPSME-12749
> [iOS] Removed caching in Promo after booking campaign

- routing/routing_callbacks.hpp
- routing/routing_session.cpp
- routing/routing_session.hpp
- routing/routing_tests/routing_session_test.cpp
cherry-pick https://github.com/mapsme/omim/pull/12435
@gmoryes PTAL
> [release-96][routing] Continue navigating along a previous route in case of route rebuilding error.

- android/jni/com/mapswithme/maps/Framework.cpp
https://jira.mail.ru/browse/MAPSME-12783
> [android] Attach jni layer

- base/CMakeLists.txt
- base/base_tests/CMakeLists.txt
- coding/CMakeLists.txt
- coding/bwt.cpp
- coding/bwt.hpp
- coding/bwt_coder.hpp
- coding/coding_tests/CMakeLists.txt
- coding/coding_tests/bwt_tests.cpp
- coding/coding_tests/move_to_front_tests.cpp
- coding/move_to_front.cpp
- coding/move_to_front.hpp
- xcode/base/base.xcodeproj/project.pbxproj
- xcode/coding/coding.xcodeproj/project.pbxproj
Follow-up to https://github.com/mapsme/omim/pull/6462
> [base] [coding] Moved BWT and MTF from base/ to coding/.

- android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
- android/src/com/mapswithme/maps/tips/ClickInterceptorFactory.java
- android/src/com/mapswithme/maps/tips/Tutorial.java
- metrics/eye_info.hpp
https://jira.mail.ru/browse/MAPSME-12938
> [android] Separated tips for isolines and subways layers

- android/jni/com/mapswithme/maps/ugc/UGC.cpp
@alexzatsepin @milchakov @yoksnod PTAL
> [android] Warning fix.

- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/UI/Welcome/WelcomePageController.swift
https://jira.mail.ru/browse/MAPSME-11828
> [iOS] Fixed showing of 'what's new' screen on next start after handle deeplink

- android/src/com/mapswithme/maps/routing/ResultCodesHelper.java
- android/src/com/mapswithme/maps/routing/RoutingErrorDialogFragment.java
https://jira.mail.ru/browse/MAPSME-12747
> [android] Changed dialog btn text

- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
https://jira.mail.ru/browse/MAPSME-9039
> [iOS] display spinner when retrying map downloading

- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
Show catalog promo instead
https://jira.mail.ru/browse/MAPSME-12975
> [iOS] remove Megafon banner from download map dialog

- tools/python/maps_generator/var/etc/file_generation_order.txt
карта Египта выросла и сейчас приходится лишний час ждать пока она соберется
> [maps_generator] Fix order for Egypt.

- generator/road_access_generator.cpp
- routing/routing_quality/routing_quality_tests/barriers_tests.cpp
[MAPSME-12984](https://jira.mail.ru/browse/MAPSME-12984)
**Проблема:** добавление бродов привело к тому, что мы больше не можем прокладывать большую часть дорог, которые раньше прокладывали. Броды на этих дорогах могут быть сезонными, возникающими на несколько часов несколько дней в году, и т.д. Не вести по таким дорогам кажется слишком сильной мерой.
Этот PR решает проблему сильной разорванности графа. Он не является revert'ом для #11778.
Маршрут через брод до PR:
Маршрут через брод после PR:
Пешеходный маршрут через брод:
> [Routing] Build routes through fords.

- iphone/Maps/Classes/CustomViews/MapViewControls/Layers/LayersViewController.xib
https://jira.mail.ru/browse/MAPSME-12995
> [iOS] fix buttons order in map ovelays view

- partners_api/partners_api_tests/CMakeLists.txt
https://jira.mail.ru/browse/MAPSME-12976
> Mapsme 12976 remove megafon

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
https://jira.mail.ru/browse/MAPSME-12987
> [iOS] Fixed back button in CatalogWebView

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
https://jira.mail.ru/browse/MAPSME-12987
> [iOS] fix back button in catalog

- iphone/Maps/UI/Welcome/WelcomePageController.swift
https://jira.mail.ru/browse/MAPSME-13007
> [iOS] Fixed double show of What's New screen

- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
Added updating catalog webview when subscription is purhchased after launch subscription screen from catalog banner
https://jira.mail.ru/browse/MAPSME-12396
> [android] Fixed updating catalog webview after single bookmark payment

- data/categories.txt
- data/ugc_types.csv
- map/style_tests/classificator_tests.cpp
- partners_api/promo_catalog_types.cpp
- search/search_integration_tests/smoke_test.cpp
Не заметила сразу, т.к. тесты падают только в дебаге.
Кроме починки упавших тестом прошлась поиском по коду, больше нигде не осталось.
> [mapcss] Fix natural-wood removal: delete hardcoded type from categories, ugc, tests.

- generator/srtm_parser.cpp
- generator/srtm_parser.hpp
- topography_generator/generator.cpp
- topography_generator/generator.hpp
- topography_generator/isolines_utils.cpp
- topography_generator/isolines_utils.hpp
- topography_generator/main.cpp
- topography_generator/marching_squares/contours_builder.cpp
- topography_generator/marching_squares/contours_builder.hpp
- topography_generator/marching_squares/marching_squares.hpp
- topography_generator/marching_squares/square.hpp
Fixed several cases discovered after generating tiles for the planet.
> [topography_generator] Isolines tiles generating fixes.

- iphone/Maps/UI/Settings/Cells/SettingsTableViewLinkCell.swift
https://jira.mail.ru/browse/MAPSME-13024
> [iOS] fix crash when tap "About" in settings

- iphone/Maps/Core/Theme/Extensions/UINavigationItem+styleName.swift
- iphone/Maps/Core/Theme/Extensions/UIView+styleName.swift
- iphone/Maps/Core/Theme/Renderers/UITextFieldRenderer.swift
- iphone/Maps/Core/Theme/Swizzle/UINavigationItem+swizzle.h
- iphone/Maps/Core/Theme/Swizzle/UINavigationItem+swizzle.m
- iphone/Maps/Core/Theme/Swizzle/UIWindow+swizzle.h
- iphone/Maps/Core/Theme/Swizzle/UIWindow+swizzle.m
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/Search/MWMSearchView.xib
https://jira.mail.ru/browse/MAPSME-13027
> [iOS] fix style related errors

- map/bookmark_catalog.cpp
https://jira.mail.ru/browse/MAPSME-13017
> [iOS] add catalog headers to route download request

- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadManager.java
- android/src/com/mapswithme/util/HttpClient.java
- android/src/com/mapswithme/util/HttpUploader.java
- android/src/com/mapswithme/util/KeyValue.java
https://jira.mail.ru/browse/MAPSME-13018
> Mapsme 13018 geo headers for downlod request

- data/mixed_nodes.txt
- generator/search_index_builder.cpp
- search/types_skipper.cpp
- search/types_skipper.hpp
черри-пик 
https://github.com/mapsme/omim/pull/12359
> [search] Add SkipAlways to TypesSkipper.

- android/build.gradle
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-13030
> [android] Set fb sdk 5.15.0

- routing/route.cpp
- routing/routing_settings.cpp
- routing/routing_settings.hpp
- routing/routing_tests/route_tests.cpp
[MAPSME-12806](https://jira.mail.ru/browse/MAPSME-12806)
Нужно завершать маршрут заранее, при заданном расстоянии до финиша по маршруту. Например, для машин - 50м, для остальных видов роутинга - 20 м.
> [Routing] Complete the route in some distance to the finish point.

- android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
- android/src/com/mapswithme/maps/maplayer/ToggleMapLayerDialog.java
- android/src/com/mapswithme/maps/maplayer/isolines/IsolinesState.java
- android/src/com/mapswithme/maps/maplayer/isolines/OnIsolinesChangedListenerImpl.java
https://jira.mail.ru/browse/MAPSME-13071
> [DNM][android] Added IsoLines states

- iphone/CoreApi/CoreApi/Traffic/MWMMapOverlayManager.h
- iphone/CoreApi/CoreApi/Traffic/MWMMapOverlayManager.mm
- iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm
https://jira.mail.ru/browse/MAPSME-12928
https://jira.mail.ru/browse/MAPSME-13073
> [iOS] show isolines status

- iphone/Maps/Core/Theme/Renderers/UISearchBarRenderer.swift
- iphone/Maps/Core/Theme/Renderers/UITableViewRenderer.swift
https://jira.mail.ru/browse/MAPSME-12818
> [iOS] Fixed visual bugs

- routing/base/followed_polyline.cpp
> [Routing] Fix for followed_polyline.

- platform/platform_ios.mm
https://jira.mail.ru/browse/MAPSME-13092
> [iOS] implement ad id in platform

- iphone/Maps/Core/Theme/Core/ThemeManager.swift
https://jira.mail.ru/browse/MAPSME-13094
> [iOS] Disabled dark theme management by system

- map/isolines_manager.cpp
https://jira.mail.ru/browse/MAPSME-13072
> [android] Fixed multiple  toast appearance

- routing/routing_settings.cpp
- routing/routing_tests/route_tests.cpp
[MAPSME-12806](https://jira.mail.ru/browse/MAPSME-12806)
Изменения в связи с обновлением ТЗ:  договорились для машин сделать 20 метров, для остальных видов роутинга - 15 м. [В начальном PR](https://github.com/mapsme/omim/pull/12350) было 50 метров для машин и 20 - для остальных.
> [Routing] Change in RoutingSettings finishToleranceM values.

- map/isolines_manager.cpp
- map/isolines_manager.hpp
часть https://jira.mail.ru/browse/MAPSME-12785
> [eye][isolines] mark isolines layer as used

- android/jni/com/mapswithme/platform/Platform.cpp
- android/src/com/mapswithme/maps/analytics/ExternalLibrariesMediator.java
- android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-13091
> [android] Implemented obtaining the advertising id

- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/editor/Editor.cpp
- android/jni/com/mapswithme/maps/metrics/UserActionsLogger.cpp
- android/src/com/mapswithme/maps/downloader/CountryItem.java
- android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java
- android/src/com/mapswithme/maps/downloader/OnmapDownloader.java
https://jira.mail.ru/browse/MAPSME-13099
https://jira.mail.ru/browse/MAPSME-13100
https://jira.mail.ru/browse/MAPSME-13101
> Fix monkey crashes

- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-12382
> [android] Removed redundant poi catalog gallery request

- iphone/Maps/Core/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-13094
> [iOS] Turn on autoupdate for theme in routing mode

- android/res/layout-land/elevation_profile_bottom_sheet.xml
- android/res/layout/activity_map.xml
- android/res/layout/elevation_profile_bottom_sheet.xml
- android/res/values/dimens.xml
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/widget/placepage/BottomSheetChangedListener.java
- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/DefaultBottomSheetCallback.java
- android/src/com/mapswithme/maps/widget/placepage/ElevationProfileBottomSheetController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageControllerFactory.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageUtils.java
https://jira.mail.ru/browse/MAPSME-12947
> Mapsme 12947 bottom sheet controller refactoring

- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.h
- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Core/Routing/MWMRouter.mm
- iphone/Maps/UI/BottomMenu/MWMBottomMenuViewController.mm
- iphone/Maps/UI/PlacePage/PlacePageViewController.swift
- iphone/Maps/UI/Search/MWMSearchManager.mm
https://jira.mail.ru/browse/MAPSME-13074
> [iOS] Fixed missed 'Add stop' button in PP
