android/jni/com/mapswithme/maps/Framework.cpp
android/src/com/mapswithme/maps/Framework.java
android/src/com/mapswithme/maps/auth/PhoneAuthFragment.java
iphone/CoreApi/CoreApi.xcodeproj/project.pbxproj
iphone/CoreApi/CoreApi/CoreApi-swift.h
iphone/CoreApi/CoreApi/WebApi/WebApi.h
iphone/CoreApi/CoreApi/WebApi/WebApi.mm
iphone/Maps/UI/Authorization/PhoneNumberAuthorizationViewController.swift
map/user.cpp
web_api/request_headers.cpp
web_api/request_headers.hpp

https://jira.mail.ru/browse/MAPSME-13091
https://jira.mail.ru/browse/MAPSME-13092

[core][android][ios] default headers for auth requests

---

generator/feature_sorter.cpp

Сейчас в feature sorter создается один file container writer и в нём секции в режиме append.
Пока сериализаторы у секций примитивные это работает, но как только при сериализации начинает использоваться Seek получаем креш в дебаге тут: https://github.com/mapsme/omim/blob/5c537200ca85aca6fd3957a730d487e5851489c7/coding/internal/file_data.cpp#L162
Также возникают проблемы если в секциях используется выравнивание.

[generator] Feature sorter: do not write sections in append mode.

---

android/jni/com/mapswithme/maps/Framework.cpp

https://jira.mail.ru/browse/MAPSME-13117

[android] Ban Vulkan for Android 10.0.

---

data/countries.txt
data/external_resources.txt

Просьба запустит тесты роутинга, а так же все остальные автотесты.

[planet] New data from 09.02.2020

---

tools/python/maps_generator/README.md
tools/python/maps_generator/__main__.py
tools/python/maps_generator/generator/env.py
tools/python/maps_generator/generator/generation.py
tools/python/maps_generator/generator/stages.py
tools/python/maps_generator/generator/stages_declaration.py
tools/python/maps_generator/maps_generator.py
tools/python/maps_generator/utils/algo.py

[python][generator] Added helper_stage_for; Changed stages names.

---

data/replaced_tags.txt

[MAPSME-12024](https://jira.mail.ru/browse/MAPSME-12024)
Для точечных объектов [highway=turning_loop](https://taginfo.openstreetmap.org/tags/highway=turning_loop) строить круговые движения точно так же, как для мини-раундэбаутов.
Вид на замапленный turning loop со спутника:
До PR:
После PR:

[Data] Handle turning loops the same way as mini roundabouts.

---

generator/generator_tests/road_access_test.cpp
generator/road_access_generator.cpp
routing/index_graph.cpp
routing/index_graph.hpp
routing/road_access.cpp
routing/road_access.hpp
routing/road_access_serialization.hpp
routing/routing_tests/index_graph_tools.cpp
routing/routing_tests/road_access_test.cpp

порефакторил названия методов и членов класса, чтобы удобнее было использовать потом вместе с conditional

[routing] Refactor RoadAccess class

---

3party/minizip/minizip.hpp

cp for https://github.com/mapsme/omim/pull/12596

[cherry-pick][3party] lost include is added into minizip

---

routing/routing_quality/routing_quality_tests/barriers_tests.cpp

[Routing] Update for ford test.

---

iphone/Maps/Maps.xcodeproj/project.pbxproj
xcode/coding/coding.xcodeproj/project.pbxproj
xcode/generator_tool/generator_tool.xcodeproj/project.pbxproj
xcode/map/map.xcodeproj/project.pbxproj
xcode/mapshot/mapshot.xcodeproj/project.pbxproj
xcode/minizip/minizip.xcodeproj/project.pbxproj
xcode/minizip/minizip_framework/Info.plist
xcode/platform/platform.xcodeproj/project.pbxproj
xcode/qtMapsMe/qtMapsMe.xcodeproj/project.pbxproj
xcode/routing/routing.xcodeproj/project.pbxproj
xcode/search/search.xcodeproj/project.pbxproj
xcode/storage/storage.xcodeproj/project.pbxproj

It crashed minizip lib was missing. Looks like xcode cant link to custom dylibs, so I changed framework type from .dylib to .framework
https://jira.mail.ru/browse/MAPSME-13161

[iOS] fix a bug in which the app crashes on the device at startup.

---

android/res/values/themes-base.xml

https://jira.mail.ru/browse/MAPSME-13170

[android] Changed isoLines layers image

---

generator/generator_integration_tests/features_tests.cpp

Новые значения для интеграционных тестов генератора после добавления turning-loop #12585.

[Generator] Fix for generator integration tests.

---

tools/python/maps_generator/maps_generator.py

Испрпавлена функция generate_coasts, которая из планеты генерит только костлайн.

[python][generator] Added lost option for coastline generation.

---

iphone/Maps/UI/BottomMenu/MWMBottomMenuViewController.mm
iphone/Maps/UI/BottomMenu/MWMBottomMenuViewController.xib

https://jira.mail.ru/browse/MAPSME-13173

[iOS] Remove autoresizing in bottom menu

---

iphone/Maps/Core/Theme/GlobalStyleSheet.swift
iphone/Maps/Core/Theme/Renderers/RatingViewRenderer.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Content/UGC/UGCAddReview/UGCAddReviewRatingCell.xib
iphone/Maps/UI/PlacePage/PlacePageLayout/Content/UGC/UGCSummaryRatingStarsCell.xib

https://jira.mail.ru/browse/MAPSME-13180

[iOS] Fixed RatingView style in place page

---

iphone/Maps/Core/Theme/SearchStyleSheet.swift
iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.xib

https://jira.mail.ru/browse/MAPSME-13200

[iOS] Fixed cell style in Search

---

drape_frontend/apply_feature_functors.cpp
geometry/smoothing.cpp
map/framework.cpp
map/isolines_manager.cpp
platform/mwm_traits.cpp
platform/mwm_traits.hpp

https://jira.mail.ru/browse/MAPSME-13196

[isolines][core][geometry] Isolines fixes.

---

iphone/Maps/UI/Discovery/Collection Cells/DiscoveryBookingCell.xib

https://jira.mail.ru/browse/MAPSME-13215

[iOS] Fixed style in Discovery

---

iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/NavigationControlView.xib

https://jira.mail.ru/browse/MAPSME-13228

[iOS] Fixed 'Stop' button in navigation

---

iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift

https://jira.mail.ru/browse/MAPSME-13223

[iOS] fix route purchase screen orientation

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
android/src/com/mapswithme/maps/tips/TutorialClickListener.java

https://jira.mail.ru/browse/MAPSME-13205
https://jira.mail.ru/browse/MAPSME-13206
https://jira.mail.ru/browse/MAPSME-13207

[android] Fixed handling and showing the tutorial coming from the core

---

iphone/Maps/Core/Theme/GlobalStyleSheet.swift

https://jira.mail.ru/browse/MAPSME-13218

[iOS] Fixed 'MoreButton' background

---

iphone/CoreApi/CoreApi/Traffic/MWMMapOverlayManager.mm
iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm

https://jira.mail.ru/browse/MAPSME-13155

[iOS] fix layers button state on startup

---

iphone/Maps/Classes/CustomViews/MapViewControls/Layers/LayersViewController.swift

https://jira.mail.ru/browse/MAPSME-13212

[iOS] fix isolines stats

---

storage/http_map_files_downloader.cpp
storage/map_files_downloader.hpp
storage/storage.cpp
storage/storage.hpp

https://jira.mail.ru/browse/MAPSME-13229

[storage] notify subscribers on concrete events only

---

android/src/com/mapswithme/util/statistics/Statistics.java
iphone/Maps/Core/DeepLink/Strategies/DeepLinkHandlerStrategy.swift
map/framework.cpp
map/mwm_url.cpp
map/mwm_url.hpp
partners_api/booking_api.cpp
partners_api/booking_api.hpp

https://jira.mail.ru/browse/MAPSME-13031
жду https://github.com/mapsme/omim/pull/12534 , потом перевожу черновик в нормальный реквест

[deeplinks] affiliate_id parameter is supported

---

iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.h
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.mm
iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
iphone/Maps/UI/PlacePage/MWMPlacePageManagerHelper.h
iphone/Maps/UI/PlacePage/MWMPlacePageManagerHelper.mm
iphone/Maps/UI/PlacePage/PlacePageViewController.swift
iphone/Maps/UI/Search/Filters/MWMHotelParams.h
iphone/Maps/UI/Search/Filters/MWMHotelParams.mm

https://jira.mail.ru/browse/MAPSME-13124

[iOS] Fixed crash in hotel filters in search and pp

---

android/src/com/mapswithme/maps/geofence/GeofenceTransitionsIntentService.java

Cherry-pick of https://github.com/mapsme/omim/pull/12653

[android] [local_ads] Fix a data race.

---

iphone/Maps/UI/Discovery/View Models/MWMDiscoveryControllerViewModel.mm

https://jira.mail.ru/browse/MAPSME-13215

[iOS] Fixed hotel rating in Discovery

---

android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
android/src/com/mapswithme/maps/maplayer/subway/DefaultMapLayerController.java

https://jira.mail.ru/browse/MAPSME-13206
https://jira.mail.ru/browse/MAPSME-13207

Mapsme 13206 fix map layer controller

---

drape_frontend/user_mark_shapes.cpp

https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/d9f63425bcf9e1a26d75ccbf59c39d3d

[bookmarks] Fixed crash after track simplification.

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/PurchaseOperationObservable.java
android/src/com/mapswithme/maps/base/Initializable.java
android/src/com/mapswithme/maps/location/LocationHelper.java
android/src/com/mapswithme/maps/maplayer/isolines/IsolinesManager.java
android/src/com/mapswithme/maps/maplayer/subway/SubwayManager.java
android/src/com/mapswithme/maps/maplayer/traffic/TrafficManager.java
android/src/com/mapswithme/maps/purchase/AbstractPurchaseController.java
android/src/com/mapswithme/maps/purchase/FailedBookmarkPurchaseController.java
android/src/com/mapswithme/maps/purchase/PurchaseController.java
android/src/com/mapswithme/maps/routing/RoutingController.java
android/src/com/mapswithme/maps/search/SearchEngine.java
android/src/com/mapswithme/maps/sound/TtsPlayer.java
android/src/com/mapswithme/maps/widget/placepage/ElevationProfileViewRenderer.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageController.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageControllerComposite.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageFactory.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageViewRenderer.java
android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
android/src/com/mapswithme/maps/widget/placepage/SimplePlacePageController.java
android/src/com/mapswithme/util/sharing/SharingHelper.java

https://jira.mail.ru/browse/MAPSME-12953

Mapsme 12953 elevation data binder interface

---

3party/opening_hours/opening_hours.cpp
3party/opening_hours/opening_hours.hpp
defines.hpp
generator/feature_segments_checker/CMakeLists.txt
generator/generator_tests/road_access_test.cpp
generator/road_access_generator.cpp
generator/road_access_generator.hpp
generator/srtm_coverage_checker/CMakeLists.txt
routing/CMakeLists.txt
routing/road_access.cpp
routing/road_access.hpp
routing/road_access_serialization.cpp
routing/road_access_serialization.hpp
routing/routes_builder/routes_builder_tool/CMakeLists.txt
routing/routing_quality/routing_quality_tests/CMakeLists.txt
routing/routing_quality/routing_quality_tool/CMakeLists.txt
routing/routing_tests/opening_hours_serdes_tests.cpp
routing/routing_tests/road_access_test.cpp
track_analyzing/track_analyzer/CMakeLists.txt
track_generator/CMakeLists.txt
xcode/routing/routing.xcodeproj/project.pbxproj

1) [generator] Implement parsing access:conditional 
Тут происходит работа с коллектором (который generator::CollectorInterface), тут реализована поддержка тэга - access:conditional
2) [generator] collector stage + test
Тут реализована ф-ия `ProcessConditional` с учетом всех ф-ий helper'ов из предыдущего коммита
3) [routing][generator] ser des
Тут реализована сериализация/десирализация в mwm
4) [routing] ser des tests
Тут тест к предыдущему комиту

[routing][generator] Access conditional generator

---

routing/index_graph.cpp
routing/index_graph.hpp
routing/index_graph_loader.cpp
routing/road_access.cpp
routing/road_access.hpp

https://github.com/mapsme/omim/pull/12665
закрыл этот PR, потому что он не из моей ветки

[routing] add current time callback to RoadAccess from IndexGraphLoader

---

android/res/layout/elevation_profile_internal.xml
android/src/com/mapswithme/maps/widget/placepage/ElevationProfileViewRenderer.java
android/src/com/mapswithme/maps/widget/placepage/SimplePlacePageController.java

https://jira.mail.ru/browse/MAPSME-12953

[android] Filled the eleveation profile layout with stubs

---

tools/python/maps_generator/README.md
tools/python/maps_generator/__main__.py
tools/python/maps_generator/generator/coastline.py
tools/python/maps_generator/generator/env.py
tools/python/maps_generator/generator/generation.py
tools/python/maps_generator/generator/settings.py
tools/python/maps_generator/generator/stages_declaration.py
tools/python/maps_generator/generator/steps.py
tools/python/maps_generator/var/etc/map_generator.ini.default

Два коммита:
1. Добавляет опцию NEED_PLANET_UPDATE. Нужно для контроля обновления. Например: для произвольного участва планеты, для планеты для релизной сборки не нужно проводить апдейт, для osm only нужно 
2. Изменяет логику хранения планеты. Раньше была общая планета для всех сборок, теперь планета на сборку. Так будет легче восстановить сборку + можно запускать несколько задач без конкуренции за планету

[python][generator] Added NEED_PLANET_UPDATE option. Changed planet paths.

---

android/res/layout-land/elevation_profile_bottom_sheet.xml
android/res/layout/elevation_profile_bottom_sheet.xml
android/res/layout/floating_marker_view.xml
android/res/values/dimens.xml
android/src/com/mapswithme/maps/widget/placepage/PlacePageGestureListener.java
android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
android/src/com/mapswithme/maps/widget/placepage/SimplePlacePageController.java

https://jira.mail.ru/browse/MAPSME-12953

Mapsme 12953 handle single tap bottom sheet

---

generator/routing_index_generator.cpp
routing/CMakeLists.txt
routing/base/astar_algorithm.hpp
routing/base/astar_graph.hpp
routing/base/astar_vertex_data.hpp
routing/base/bfs.hpp
routing/index_graph.cpp
routing/index_graph.hpp
routing/index_graph_starter.cpp
routing/index_graph_starter.hpp
routing/index_graph_starter_joints.hpp
routing/index_road_graph.cpp
routing/leaps_graph.cpp
routing/leaps_graph.hpp
routing/routes_builder/routes_builder_tool/CMakeLists.txt
routing/routing_helpers.cpp
routing/routing_tests/index_graph_tools.hpp
routing/routing_tests/routing_algorithm.cpp
routing/routing_tests/routing_algorithm.hpp
routing/single_vehicle_world_graph.cpp
routing/single_vehicle_world_graph.hpp
routing/transit_world_graph.cpp
routing/transit_world_graph.hpp
routing/world_graph.cpp
routing/world_graph.hpp

закрыл PR: https://github.com/mapsme/omim/pull/12657
потому что ветку не там создал

[routing] Pass weight from astar

---

android/src/com/mapswithme/maps/bookmarks/SystemDownloadCompletedService.java
iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift

https://jira.mail.ru/browse/MAPSME-12452

[android][ios] pushwoosh timestamp for free guides

---

data/copyright.html

лицензия: https://creativecommons.org/licenses/by-sa/2.0/legalcode
оригинальный датасет: https://civicspacelabs.org/download/
пополняемый датасет: https://public.opendatasoft.com/explore/dataset/us-zip-code-latitude-and-longitude/information/

[data] Add copyright information for US Zip Code Latitude and Longitude dataset.

---

routing/routing_session.cpp

cherry-pick https://github.com/mapsme/omim/pull/12698 to master

[routing] Crashfix in case traffic jam has been downloaded while the first route building.

---

base/base_tests/CMakeLists.txt
base/base_tests/checked_cast_tests.cpp
base/base_tests/string_utils_test.cpp
base/checked_cast.hpp
base/string_utils.cpp
base/string_utils.hpp
map/CMakeLists.txt
map/bookmark_manager.cpp
map/bookmark_manager.hpp
map/elevation_info.cpp
map/elevation_info.hpp
map/framework.cpp
map/framework.hpp
map/place_page_info.hpp
transit/transit_graph_data.cpp
xcode/base/base.xcodeproj/project.pbxproj
xcode/map/map.xcodeproj/project.pbxproj

https://jira.mail.ru/browse/MAPSME-13270

Strings conversion refactoring + elevation info infrastructure

---

local_ads/statistics.cpp

Cherry-pick of https://github.com/mapsme/omim/pull/12708

[cherry-pick] [local_ads] A couple of changes related to the Framework-LightFramework race. 

---

iphone/Maps/Core/Theme/Renderers/UITableViewHeaderFooterViewRenderer.swift

Удален глобальный стиль для UITableViewHeaderFooterView, приводящий к визуальным багам в настройках

[iOS] Removed global style for UITableViewHeaderFooterView

---

iphone/Maps/UI/PlacePage/Components/PlacePagePreviewViewController.swift

https://jira.mail.ru/browse/MAPSME-13139

[iOS] Fixed hotel raiting in pp

---

.gitignore
routing/routing_quality/routing_quality_tool/utils.cpp
tools/python/routing/etc/comparison.ini.example
tools/python/routing/etc/heap_comparison_benchmark.ini.example
tools/python/routing/etc/paths.ini.example
tools/python/routing/requirements.txt
tools/python/routing/run_comparison.py
tools/python/routing/run_heap_comparison_benchmark.py
tools/python/routing/src/common_config.py
tools/python/routing/src/graph_scripts.py
tools/python/routing/src/logger.py
tools/python/routing/src/utils.py

https://confluence.mail.ru/display/MAPSME/Python+Tools

[routing] Routing tools python

---

iphone/CoreApi/CoreApi/Storage/MWMMapNodeAttributes.h
iphone/CoreApi/CoreApi/Storage/MWMMapNodeAttributes.mm
iphone/Maps/Bridging-Header.h
iphone/Maps/Core/Storage/MWMStorage+UI.m
iphone/Maps/UI/Autoupdate/MWMAutoupdateController.mm
iphone/Maps/UI/Downloader/AvailableMapsDataSource.swift
iphone/Maps/UI/Downloader/Cells/MWMMapDownloaderButtonTableViewCell.h
iphone/Maps/UI/Downloader/Cells/MWMMapDownloaderButtonTableViewCell.m
iphone/Maps/UI/Downloader/Cells/MWMMapDownloaderTableViewCell.m
iphone/Maps/UI/Downloader/DownloadMapsViewController.swift
iphone/Maps/UI/Storyboard/Main.storyboard

https://jira.mail.ru/browse/MAPSME-12871
https://jira.mail.ru/browse/MAPSME-12880
https://jira.mail.ru/browse/MAPSME-12883
https://jira.mail.ru/browse/MAPSME-12872
https://jira.mail.ru/browse/MAPSME-12885
https://jira.mail.ru/browse/MAPSME-12861
https://jira.mail.ru/browse/MAPSME-12863
https://jira.mail.ru/browse/MAPSME-12864

[DNM] Fixes after Downloader refactoring

---

routing_common/car_model_coefs_default.hpp

Две пропущенные запятые, из-за которых не собирался мастер.

[routing] Minor fix for car model for all the world.

---

iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift

https://jira.mail.ru/browse/MAPSME-13151

[iOS] don't show empty catalog promo gallery in PP

---

iphone/CoreApi/CoreApi/CoreApi-swift.h
iphone/CoreApi/CoreApi/PlacePageData/Common/IOpeningHoursLocalization.h
iphone/CoreApi/CoreApi/PlacePageData/Common/OpeningHours.h
iphone/CoreApi/CoreApi/PlacePageData/Common/OpeningHours.mm
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData+Core.h
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.h
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageInfoData.mm
iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.h
iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
iphone/Maps/Classes/MapViewController.mm
iphone/Maps/Maps.xcodeproj/project.pbxproj
iphone/Maps/UI/PlacePage/Components/OpeningHoursViewController.swift
iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard
iphone/Maps/UI/PlacePage/PlacePageBuilder.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Content/Controllers/FacilitiesController.swift
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm
iphone/Maps/UI/PlacePage/Util/OpeinigHoursLocalization.swift

https://jira.mail.ru/browse/MAPSME-12663

[iOS] fix display of working hours in PP

---

iphone/Maps/Core/Ads/Facebook/FacebookBanner.swift
iphone/Maps/Core/Ads/Mopub/MPNativeAd+MWM.h
iphone/Maps/Core/Ads/Mopub/MPNativeAd+MWM.m
iphone/Maps/Core/Ads/Mopub/MopubBanner.swift
iphone/Maps/Core/Theme/Renderers/UITableViewHeaderFooterViewRenderer.swift
iphone/Maps/UI/Ads/AdBanner.swift
iphone/Maps/UI/Ads/AdBanner.xib
partners_api/facebook_ads.cpp
partners_api/mopub_ads.cpp

bd616b2216 [iOS] Removed global style for UITableViewHeaderFooterView
5ea722d6f0 [iOS] Changed NativeAd to NativeBannerAd in Facebook SDK

[iOS] Cherry-pick from release-96 to master

---

iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.h
iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm

https://jira.mail.ru/browse/MAPSME-13004

[iOS] fix update of "edit bookmark" button in PP on add/remove bookmark

---

iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.h
iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
iphone/Maps/UI/PlacePage/Components/ActionBarViewController.swift

https://jira.mail.ru/browse/MAPSME-13334

[iOS] fix PP buttons for route points

---

android/jni/com/mapswithme/core/jni_helper.cpp
android/jni/com/mapswithme/core/jni_helper.hpp
android/jni/com/mapswithme/maps/Framework.cpp
android/jni/com/mapswithme/maps/UserMarkHelper.cpp
android/jni/com/mapswithme/maps/UserMarkHelper.hpp
android/src/com/mapswithme/maps/ChartController.java
android/src/com/mapswithme/maps/Framework.java
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/base/Supportable.java
android/src/com/mapswithme/maps/bookmarks/data/ElevationInfo.java
android/src/com/mapswithme/maps/bookmarks/data/MapObject.java
android/src/com/mapswithme/maps/widget/placepage/ElevationProfileViewRenderer.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageController.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageControllerComposite.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageData.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageFactory.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageUtils.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageViewRenderer.java
android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
android/src/com/mapswithme/maps/widget/placepage/SimplePlacePageController.java
android/src/com/mapswithme/maps/widget/placepage/UserMarkInterface.java

https://jira.mail.ru/browse/MAPSME-12952

Mapsme 12952 fill elevation profile info

---

search/ranker.cpp
search/ranking_info.cpp
search/ranking_info.hpp
search/search_integration_tests/ranker_test.cpp
search/search_quality/scoring_model.py

Пока коэффициент обучен на размеченной вручную выборке, на алохе тоже запущу посмотреть.
draft пока смотрю выборку с новыми коэффициентами.

[search] Add exactCountryOrCapital ranking parameter.

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/maplayer/isolines/IsolinesErrorDialogListener.java
android/src/com/mapswithme/maps/maplayer/isolines/IsolinesManager.java
android/src/com/mapswithme/maps/maplayer/isolines/IsolinesState.java
android/src/com/mapswithme/maps/maplayer/isolines/OnIsolinesChangedListenerImpl.java

https://jira.mail.ru/browse/MAPSME-13225

[android] Added isoLines error ui

---

android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
android/src/com/mapswithme/maps/ChartController.java
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java

https://jira.mail.ru/browse/MAPSME-12950

[android] Added setting and getting elevation active point in the chart

---

iphone/Maps/Core/Theme/Core/StyleManager.swift
iphone/Maps/Core/Theme/Swizzle/SwizzleStyle.h
iphone/Maps/Core/Theme/Swizzle/SwizzleStyle.m
iphone/Maps/Core/Theme/Swizzle/UISearchBar+swizzle.h
iphone/Maps/Core/Theme/Swizzle/UISearchBar+swizzle.m
iphone/Maps/Core/Theme/Swizzle/UITextField+swizzle.h
iphone/Maps/Core/Theme/Swizzle/UITextField+swizzle.m
iphone/Maps/Core/Theme/Swizzle/UIView+swizzle.h
iphone/Maps/Core/Theme/Swizzle/UIView+swizzle.m
iphone/Maps/Maps.xcodeproj/project.pbxproj

https://jira.mail.ru/browse/MAPSME-13124

[iOS] Reordered methods sizzling in style manager

---

iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.xib

https://jira.mail.ru/browse/MAPSME-13424

[iOS] Fixed loading view in outdoor subscription after redesign

---

iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.swift
iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.xib
iphone/Maps/Core/Theme/Components/IFonts.swift
iphone/Maps/Core/Theme/FontStyleSheet.swift
iphone/Maps/Core/Theme/Fonts.swift
iphone/Maps/Core/Theme/SubscriptionsStyleSheet.swift

https://jira.mail.ru/browse/MAPSME-13281

[iOS] Added dynamic layout for SE in outdoor subscription

---

iphone/Maps/Classes/CustomAlert/CreateBookmarkCategory/MWMBCCreateCategoryAlert.xib

https://jira.mail.ru/browse/MAPSME-13342

[iOS] Fixed style in 'create new group' alert in bookmarks

---

coding/files_container.cpp
coding/files_container.hpp
generator/CMakeLists.txt
generator/pygen/CMakeLists.txt
generator/pygen/example.py
generator/pygen/pygen.cpp
generator/utils.hpp
geometry/triangle2d.hpp
indexer/editable_map_object.cpp
indexer/feature_meta.cpp
indexer/feature_meta.hpp
platform/mwm_version.cpp
platform/mwm_version.hpp

Некоторые биндинги для генератора.
Пока это планируется использоваться только в maps_generator. 
Так как хочется сохранить старую реализацию, решил их сделать в другом реквесте, т.к изменения будут значительными.

[bindings] Added pygen.

---

iphone/Maps/Core/Subscriptions/SubscriptionManager.swift
iphone/Maps/UI/Settings/MWMSettingsViewController.mm

https://jira.mail.ru/browse/MAPSME-12252

[iOS] Added subscriptions activation in settings

---

iphone/Maps/UI/PlacePage/Components/ActionBarViewController.swift
iphone/Maps/UI/PlacePage/PlacePageInteractor.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/IPlacePageLayout.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageElevationLayout.swift
iphone/Maps/UI/PlacePage/PlacePageViewController.swift
iphone/Maps/UI/Storyboard/Main.storyboard

https://jira.mail.ru/browse/MAPSME-13134
https://jira.mail.ru/browse/MAPSME-13433
https://jira.mail.ru/browse/MAPSME-13437
https://jira.mail.ru/browse/MAPSME-13122

[iOS] fix scroll and popover issues in PP on iPad

---

android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
android/src/com/mapswithme/maps/ChartController.java
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
android/src/com/mapswithme/maps/bookmarks/data/OnElevationCurrentPositionChangedListener.java
android/src/com/mapswithme/maps/widget/placepage/FloatingMarkerView.java

https://jira.mail.ru/browse/MAPSME-13416

[android] Added chart current position

---

data/categories.txt

https://jira.mail.ru/browse/MAPSME-12986

[search] Fix the search filter for campings.

---

tools/python/booking/api/booking_api.py

Ломалось давно и почти каждый раз, но не удавалось сделать реквест.
Изменил логику обработки ошибок.
Запустил еще разок проверить, пока работает

[python] Fixed downloading of hotels.

---

data/categories.txt

Cherry-pick https://github.com/mapsme/omim/pull/12789

[cherry-pick] [search] Fix the search filter for campings.

---

android/src/com/mapswithme/maps/widget/placepage/FloatingMarkerView.java

https://jira.mail.ru/browse/MAPSME-13450

Mapsme 13450 chart fix

---

iphone/CoreApi/CoreApi/User/MWMUser.h
iphone/CoreApi/CoreApi/User/MWMUser.mm
iphone/Maps/Bridging-Header.h
iphone/Maps/Common/Statistics/StatisticsStrings.h
iphone/Maps/Maps.xcodeproj/project.pbxproj
iphone/Maps/UI/Authorization/AuthorizationViewController.swift
iphone/Maps/UI/Authorization/AuthorizationViewController.xib
iphone/Maps/maps.me dbg.entitlements
iphone/Maps/maps.me full.entitlements
iphone/Maps/maps.me rel.entitlements
map/user.cpp
map/user.hpp

https://jira.mail.ru/browse/MAPSME-13190

[iOS] add "Sign in with Apple" to login options

---

map/bookmark_manager.cpp
map/elevation_info.cpp
map/elevation_info.hpp
map/framework.cpp
map/track.cpp
map/track.hpp

https://jira.mail.ru/browse/MAPSME-13452

[bookmarks] Select tracks from catalog with valid altitudes.

---

android/res/drawable-v21/button_megafon.xml
android/res/drawable-v21/ripple_mask_big_corner_radius.xml
android/res/drawable/button_megafon.xml
android/res/drawable/button_megafon_internal.xml
android/res/drawable/button_megafon_normal.xml
android/res/drawable/button_megafon_pressed.xml
android/res/layout/onmap_downloader.xml
android/res/values/dimens.xml
android/src/com/mapswithme/maps/downloader/DownloaderBannerConfigStrategyPartner.java
android/src/com/mapswithme/maps/downloader/DownloaderBannerType.java
iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
map/download_on_map_ads_delegate.cpp

https://jira.mail.ru/browse/MAPSME-13468
https://jira.mail.ru/browse/MAPSME-13483
https://jira.mail.ru/browse/MAPSME-13486
https://jira.mail.ru/browse/MAPSME-13490
https://jira.mail.ru/browse/MAPSME-13489

Download on map fixes

---

search/geocoder.cpp

cherry-pick
https://github.com/mapsme/omim/pull/12799

[search] Remove assert which is not true anymore.

---

iphone/Maps/Bookmarks/Catalog/Subscription/BaseSubscriptionViewController.swift

https://jira.mail.ru/browse/MAPSME-13424

[iOS] Added loader in subscription view controllers

---

iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
iphone/Maps/Bookmarks/Categories/Notifications/BMCNotificationsCell.xib

https://jira.mail.ru/browse/MAPSME-13465

[iOS] Fix style and duplicates of notification cell  in BMC ViewController

---

android/src/com/mapswithme/maps/widget/placepage/ElevationProfileViewRenderer.java
map/elevation_info.cpp
map/elevation_info.hpp

https://jira.mail.ru/browse/MAPSME-13497

[elevation info] invalid difficulty is added.

---

android/src/com/mapswithme/maps/downloader/OnmapDownloader.java

https://jira.mail.ru/browse/MAPSME-11623

[android] Fixed multiple Banners_show event calls

---

partners_api/ads/ads_engine.cpp

https://jira.mail.ru/browse/MAPSME-13409

[partners] mts banner is disabled.

---

storage/http_map_files_downloader.cpp
storage/map_files_downloader.cpp
storage/map_files_downloader.hpp

https://jira.mail.ru/browse/MAPSME-13274

[downloader] first downloading queue is added instead of task posting

---

iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm

https://jira.mail.ru/browse/MAPSME-13458

[iOS] Fixed mobile internet alert freeze

---

android/res/layout/elevation_profile_internal.xml
android/src/com/mapswithme/maps/widget/placepage/ElevationProfileViewRenderer.java

https://jira.mail.ru/browse/MAPSME-13497

[android] Hid difficulty and time views

---

map/elevation_info.cpp
map/elevation_info.hpp

Так как теперь стали известны вне названия уровней сложности, то предлагаю сделать enum.
@alexzatsepin @beloal fyi

[elevation] enum for difficulty is added.

---

metrics/eye.cpp

https://jira.mail.ru/browse/MAPSME-12920

[notifications] missed notifications are fixed

---

coding/byte_stream.hpp
coding/coding_tests/var_record_reader_test.cpp
coding/coding_tests/varint_test.cpp
coding/var_record_reader.hpp
indexer/feature.cpp
indexer/feature.hpp
indexer/features_vector.hpp

поверх https://github.com/mapsme/omim/pull/12778

[coding][index] Replace char with uint8_t.

---

storage/http_map_files_downloader.cpp
storage/map_files_downloader.cpp
storage/map_files_downloader.hpp

cp of https://github.com/mapsme/omim/pull/12781

[downloader] quarantine queue is added instead of task posting

---

android/src/com/mapswithme/util/HttpPayload.java

https://jira.mail.ru/browse/MAPSME-13426

[android] Changed uploader params collection

---

iphone/Chart/Chart.xcodeproj/project.pbxproj
iphone/Chart/Chart/ChartData/ChartPresentationData.swift
iphone/Chart/Chart/Views/ChartInfo/ChartInfoView.swift
iphone/Chart/Chart/Views/ChartInfo/ChartMyPositionView.swift
iphone/Chart/Chart/Views/ChartInfo/ChartPointIntersectionView.swift
iphone/Chart/Chart/Views/ChartView.swift
iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h
iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData+Core.h
iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData.h
iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData.mm
iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfilePresenter.swift
iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfileViewController.swift

https://jira.mail.ru/browse/MAPSME-12958

Elevation chart improvements

---

map/download_on_map_ads_delegate.cpp

https://jira.mail.ru/browse/MAPSME-13483

[ads] link fix

---

android/res/layout/floating_marker_view.xml

https://jira.mail.ru/browse/MAPSME-13524

[android] Fixed elevation chart font size

---

data/taxi_places/freenow.json

https://jira.mail.ru/browse/MAPSME-13265

[taxi] freenow available territories are fixed

---

iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfilePresenter.swift

https://jira.mail.ru/browse/MAPSME-13544
https://jira.mail.ru/browse/MAPSME-13545

[iOS] Added units for attitude in elevation profile

---

iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData.h
iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData.mm
iphone/Maps/Core/Theme/GlobalStyleSheet.swift
iphone/Maps/UI/PlacePage/Components/ElevationDetails/ElevationDetailsViewController.swift
iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfilePresenter.swift
iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfileViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard
iphone/Maps/UI/PlacePage/Views/DifficultyView.swift

https://jira.mail.ru/browse/MAPSME-13496

[iOS] Disable difficulty and time view in Elevation profile depend on data

---

android/res/layout-land/altitude_chart_panel.xml
android/res/layout/altitude_chart_panel.xml

https://jira.mail.ru/browse/MAPSME-13040

[android] Fixed displaying the altitude chart in bottom routing panel

---

map/bookmark_manager.cpp
map/bookmark_manager.hpp
map/framework.cpp
map/track.cpp
map/track.hpp

https://jira.mail.ru/browse/MAPSME-13243
https://jira.mail.ru/browse/MAPSME-13542

[bookmarks] Show track markers only if the track is visible.

---

iphone/Maps/UI/Downloader/DownloadMapsViewController.swift

https://jira.mail.ru/browse/MAPSME-12861

[iOS] Added missing offset in downloader table view

---

iphone/Maps/UI/PlacePage/PlacePagePresenter.swift
iphone/Maps/UI/PlacePage/PlacePageViewController.swift

https://jira.mail.ru/browse/MAPSME-13519

[iOS] Fixed crash in PlacePage on zoom out

---

iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift

https://jira.mail.ru/browse/MAPSME-13556

[iOS] Added exit button in catalog

---

iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData+Core.h
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.mm
iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm

https://jira.mail.ru/browse/MAPSME-13559

[iOS] add header to PP of outdoor track

---

generator/pygen/example.py
generator/pygen/pygen.cpp

[generator] Refactored names of enums.

---

android/res/values/colors.xml
android/res/values/themes-attrs.xml
android/res/values/themes-base.xml
android/src/com/mapswithme/maps/ChartController.java

https://jira.mail.ru/browse/MAPSME-13578

[android] Changed chart dark theme bg

---

android/res/layout/elevation_profile_internal.xml
android/res/values/dimens.xml

https://jira.mail.ru/browse/MAPSME-13564

[android] Small ui fixes in elevation profile layout

---

android/res/layout/elevation_profile_internal.xml

https://jira.mail.ru/browse/MAPSME-13524

[android] Fixed big font chart

---

tracking/archival_manager.hpp

Set timeout 24 hours for m_uploadIntervalSeconds.

[tracking] Update for default settings.

---

iphone/Maps/UI/Search/MWMSearchManager.mm

https://jira.mail.ru/browse/MAPSME-13398

[iOS] Changed parent for search views

---

iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.swift
iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.xib

https://jira.mail.ru/browse/MAPSME-13591

[iOS] Changed order of localizations in outdoor subsctiption view

---

iphone/Maps/Core/Theme/Colors.swift
iphone/Maps/Core/Theme/Components/IColors.swift
iphone/Maps/Core/Theme/GlobalStyleSheet.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard

https://jira.mail.ru/browse/MAPSME-13116

[iOS] fix divider color in PP

---

iphone/Chart/Chart/Views/ChartPreviewView.swift
iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfilePresenter.swift

https://jira.mail.ru/browse/MAPSME-13527
https://jira.mail.ru/browse/MAPSME-13529

[iOS] Chart zoom improvements

---

tools/python/maps_generator/README.md
tools/python/maps_generator/__main__.py
tools/python/maps_generator/generator/env.py

[generator][python] Supported suffix the name of a build dir.

---

map/download_on_map_ads_delegate.cpp
map/download_on_map_ads_delegate.hpp
partners_api/ads/ads_base.cpp
partners_api/ads/ads_base.hpp
partners_api/ads/tinkoff_insurance_ads.cpp
partners_api/partners_api_tests/ads_engine_tests.cpp
partners_api/partners_api_tests/download_on_map_container_delegate.hpp
partners_api/partners_api_tests/mts_tests.cpp
partners_api/partners_api_tests/tinkoff_airlines_tests.cpp
partners_api/partners_api_tests/tinkoff_insurance_tests.cpp

https://jira.mail.ru/browse/MAPSME-13409

[ads] territories for download on map banners are fixed

---

android/src/com/mapswithme/maps/ChartController.java

https://jira.mail.ru/browse/MAPSME-13578

[android] Changed chart line color

---

iphone/Maps/Maps.xcodeproj/project.pbxproj
iphone/Maps/UI/PlacePage/PlacePageViewController.swift
iphone/Maps/UI/PlacePage/Views/TouchTransparentView.swift
iphone/Maps/UI/Storyboard/Main.storyboard

https://jira.mail.ru/browse/MAPSME-13520

[iOS] fix zoom buttons when PP open

---

iphone/Chart/Chart/Views/ChartInfo/ChartInfoView.swift
iphone/Chart/Chart/Views/ChartInfo/ChartMyPositionView.swift

https://jira.mail.ru/browse/MAPSME-13552

[iOS] fix user position tracking in Elevation Profile

---

iphone/Maps/Core/Theme/PlacePageStyleSheet.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/IPlacePageLayout.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageElevationLayout.swift
iphone/Maps/UI/PlacePage/PlacePagePresenter.swift
iphone/Maps/UI/PlacePage/PlacePageViewController.swift

https://jira.mail.ru/browse/MAPSME-13445

[iOS] change separator color in PP

---

iphone/Maps/UI/Authorization/AuthorizationViewController.swift

https://jira.mail.ru/browse/MAPSME-13590

[iOS] fix Sign in with Apple button color

---

android/res/layout/elevation_profile.xml
android/res/layout/floating_marker_view.xml
android/res/values/dimens.xml

https://jira.mail.ru/browse/MAPSME-13538

[android] Changed selected point view height

---

routing/CMakeLists.txt
routing/fake_edges_container.hpp
routing/fake_graph.cpp
routing/fake_graph.hpp
routing/index_graph_starter.hpp
routing/routing_tests/fake_graph_test.cpp
routing/transit_graph.hpp
xcode/routing/routing.xcodeproj/project.pbxproj

После #12661 стало понятно, что классу FakeGraph не нужна шаблонность. В соответствии с этим изменен тест для FakeGraph.

[routing] FakeGraph with no templates.

---

map/framework.cpp

https://jira.mail.ru/browse/MAPSME-13609

[drape] Fixed updating of a track selection shape.

---

android/src/com/mapswithme/maps/purchase/BookmarksAllSubscriptionPage.java

https://jira.mail.ru/browse/MAPSME-13592

[android] Fixed order views subs screen

---

tools/python/maps_generator/generator/stages_declaration.py

Видать после ребейза или после мержа потерялась строка

[generator][python] Fixed StageIsolinesInfo.

---

iphone/Maps/Classes/MapViewController.mm

https://jira.mail.ru/browse/MAPSME-13530
https://jira.mail.ru/browse/MAPSME-13553

[iOS] deselect map object when PP is hidden

---

android/jni/com/mapswithme/maps/Framework.cpp
android/jni/com/mapswithme/maps/UserMarkHelper.cpp
android/jni/com/mapswithme/maps/UserMarkHelper.hpp
android/src/com/mapswithme/maps/bookmarks/data/ElevationInfo.java
android/src/com/mapswithme/maps/widget/placepage/BannerController.java
android/src/com/mapswithme/maps/widget/placepage/ElevationProfileViewRenderer.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageControllerComposite.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageStateObserver.java
android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
android/src/com/mapswithme/maps/widget/placepage/SimplePlacePageController.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-13616

Mapsme 13616 statistic for elevation profile

---

iphone/Maps/UI/PlacePage/PlacePageLayout/Content/UGC/UGCAddReview/UGCAddReviewRatingCell.xib

https://jira.mail.ru/browse/MAPSME-13439

[iOS] Fixed label width in UGCAddReviewRatingCell

---

iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.h
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.mm
iphone/Maps/UI/Search/Filters/MWMHotelParams.mm

https://jira.mail.ru/browse/MAPSME-13629

[iOS] fix crash when tap on "Similar hotels" in PP

---

iphone/Maps/Core/Theme/GlobalStyleSheet.swift
iphone/Maps/UI/BottomMenu/MWMBottomMenuViewController.mm
iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfileViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/IPlacePageLayout.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageElevationLayout.swift
iphone/Maps/UI/PlacePage/PlacePagePresenter.swift
iphone/Maps/UI/PlacePage/PlacePageViewController.swift
iphone/Maps/UI/Storyboard/Main.storyboard

https://jira.mail.ru/browse/MAPSME-13562
https://jira.mail.ru/browse/MAPSME-13600
https://jira.mail.ru/browse/MAPSME-13474
https://jira.mail.ru/browse/MAPSME-13547

[iOS] PP scrolling improvements

---

iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.h
iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
iphone/Maps/UI/PlacePage/Components/PlacePageReviewsViewController.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Content/UGC/UGCAddReview/UGCAddReviewController.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Content/UGC/UGCAddReview/UGCReviewModel.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Content/UGC/UGCRating.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm

https://jira.mail.ru/browse/MAPSME-13637

[iOS] Refresh reviews section in PP after adding review

---

iphone/Maps/UI/PlacePage/PlacePage.storyboard

https://jira.mail.ru/browse/MAPSME-13636

[iOS] fix crash when user taps on hotel facility cell in PP

---

iphone/Maps/UI/PlacePage/PlacePage.storyboard

https://jira.mail.ru/browse/MAPSME-13642

[iOS] Changed hugging priority to open hours in PP

---

iphone/Maps/Categories/UIViewController+alternative.swift
iphone/Maps/Core/Theme/PlacePageStyleSheet.swift
iphone/Maps/Maps.xcodeproj/project.pbxproj
iphone/Maps/UI/PlacePage/Components/PlacePageHeader/PlacePageHeaderPresenter.swift
iphone/Maps/UI/PlacePage/Components/PlacePageHeader/PlacePageHeaderViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard
iphone/Maps/UI/PlacePage/PlacePagePresenter.swift
iphone/Maps/UI/PlacePage/PlacePageViewController.swift
iphone/Maps/UI/Storyboard/Main.storyboard

https://jira.mail.ru/browse/MAPSME-13480

[iOS] Added swipe gesture to close PP on ipad

---

iphone/Maps/UI/Downloader/Cells/MWMMapDownloaderTableViewCell.m

https://jira.mail.ru/browse/MAPSME-12872

[iOS] Fixed spinner progress animation in mapdownloader

---

android/res/layout/elevation_profile_internal.xml
android/src/com/mapswithme/maps/widget/placepage/ElevationProfileViewRenderer.java

https://jira.mail.ru/browse/MAPSME-13524

[android] Fixed bottom ellipsize chart

---

iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift

Падает на некоторых точках например: Индийский океан

[iOS] Fixed crash in pp

---

iphone/Maps/Core/Theme/Renderers/UISearchBarRenderer.swift

https://jira.mail.ru/browse/MAPSME-13653

[iOS] Changed search bar text field tintColor to fontColor

---

iphone/Chart/Chart.xcodeproj/project.pbxproj
iphone/Chart/Chart/Views/ChartInfo/ChartInfoView.swift
iphone/Chart/Chart/Views/ChartPreviewView.swift
iphone/Chart/Chart/Views/ChartView.swift
iphone/Chart/Chart/Views/ExpandedTouchView.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard

https://jira.mail.ru/browse/MAPSME-13529

[iOS] fix small tap area in Elevation Profile

---

iphone/CoreApi/CoreApi.xcodeproj/project.pbxproj
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageBookmarkData+Core.h
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePageBookmarkData.mm
iphone/Maps/UI/EditBookmark/MWMEditBookmarkController.h
iphone/Maps/UI/EditBookmark/MWMEditBookmarkController.mm
iphone/Maps/UI/PlacePage/Components/PlacePageBookmarkViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard
iphone/Maps/UI/PlacePage/PlacePageInteractor.swift
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManagerHelper.h
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManagerHelper.mm
iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift
iphone/Maps/UI/Storyboard/Main.storyboard

Fix bookmark section layout issues

[iOS] refresh bookmark section in PP after bookmark editing.

---

iphone/Maps/Classes/Widgets/PartnerBannerViewController.xib

https://jira.mail.ru/browse/MAPSME-13645

[iOS] Changed aspect ratio for icon in downloader banner

---

iphone/Maps/UI/PlacePage/PlacePageViewController.swift

1. Раскрывать рекламу при повороте устройства
2. Учитывать отрытую/закрытую рекламу при завершении скрола

[iOS] Place page scroll improvements for Ads

---

iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfilePresenter.swift

https://jira.mail.ru/browse/MAPSME-13635

[iOS] fix stats for elevation profile

---

iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData+Core.h
iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData.h
iphone/CoreApi/CoreApi/PlacePageData/ElevationProfile/ElevationProfileData.mm
iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfilePresenter.swift

https://jira.mail.ru/browse/MAPSME-13635

[iOS] pass serverID to elevation profile stats

---

iphone/Maps/UI/Authorization/AuthorizationViewController.swift

https://jira.mail.ru/browse/MAPSME-13590

[iOS] adjust colors of Sign in with Apple button

---

iphone/Maps/Classes/MapViewController.mm
iphone/Maps/UI/Storyboard/Main.storyboard

На маленьких устройствах увеличина ширина меню, добавлено авто-скрытие

[iOS] Changed menu width for wC/hC devices

---

iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift

https://jira.mail.ru/browse/MAPSME-13674

[iOS] Don't show routes gallery in PP of bookmark

---

editor/editor_config.cpp

https://jira.mail.ru/browse/MAPSME-13672

[editor] postcode editing is fixed

---

generator/affiliation.cpp
generator/affiliation.hpp
generator/coastlines_generator.cpp
generator/feature_builder.hpp
generator/feature_helpers.cpp
generator/generator_tests/CMakeLists.txt
generator/generator_tests/affiliation_tests.cpp

* Добавил тесты
* Добавил реализацию CountriesFilesIndexAffiliation::GetAffiliations(m2::PointD const &), для этого переписал код что бы не дублировать реализации, которые немного бы отличались

[generator] Added affiliation tests.

---

iphone/Chart/Chart/Views/ChartInfo/ChartPointIntersectionView.swift
iphone/Maps/Core/Theme/Colors.swift
iphone/Maps/Core/Theme/Components/IColors.swift
iphone/Maps/UI/PlacePage/Components/ElevationProfile/ElevationProfilePresenter.swift

https://jira.mail.ru/browse/MAPSME-13651

[iOS] fix elevation chart color in night mode

---

iphone/CoreApi/CoreApi/User/MWMUser.h
iphone/CoreApi/CoreApi/User/MWMUser.mm
iphone/Maps/Classes/MapsAppDelegate.mm
iphone/Maps/Maps.xcodeproj/project.pbxproj
iphone/Maps/UI/Authorization/AuthorizationViewController.swift
iphone/Maps/UI/Authorization/User+AppleId.swift
map/user.cpp
map/user.hpp

Also implement log out if Apple Id authorization revoked

[iOS] pass user name on Sign in with Apple

---

iphone/Maps/Classes/Widgets/PartnerBannerViewController.xib

https://jira.mail.ru/browse/MAPSME-13663

[iOS] Changed layout for downloader banner in landscape orientation

---

data/taxi_places/yandex.json

https://jira.mail.ru/browse/MAPSME-13265

[taxi] yandex places are fixed

---

map/CMakeLists.txt
map/framework.cpp
map/framework.hpp
map/guides_manager.cpp
map/guides_manager.hpp
map/place_page_info.hpp
xcode/map/map.xcodeproj/project.pbxproj

https://jira.mail.ru/browse/MAPSME-13678

[core] Guides manager added.

---

iphone/Maps/UI/PlacePage/PlacePageInteractor.swift
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManagerHelper.h
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManagerHelper.mm

https://jira.mail.ru/browse/MAPSME-13721

[iOS] open booking.com for non-booking.com hotels

---

routing/features_road_graph.cpp

cherry-pick https://github.com/mapsme/omim/pull/12972 to master.

[routing] Fix crash in FeaturesRoadGraph::FindClosestEdges().

---

search/locality_scorer.cpp
search/search_integration_tests/processor_test.cpp
search/search_tests/locality_scorer_test.cpp

поверх https://github.com/mapsme/omim/pull/12949

[search] LocalityScorer: Consider matched tokens number before rank.

---

iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm

https://jira.mail.ru/browse/MAPSME-13553

[iOS] Fixed deselection after deleting a bookmark on empty place.

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/widget/menu/BottomSheetMenuController.java
android/src/com/mapswithme/maps/widget/menu/MainMenuRenderer.java
android/src/com/mapswithme/maps/widget/menu/MenuRenderer.java

https://jira.mail.ru/browse/MAPSME-13348

Mapsme 13348 download maps counter

---

android/res/layout/item_bottomsheet_dialog.xml
android/src/com/mapswithme/maps/maplayer/DefaultClickListener.java
android/src/com/mapswithme/maps/maplayer/LayerHolder.java
android/src/com/mapswithme/maps/maplayer/LayersAdapter.java
android/src/com/mapswithme/maps/maplayer/Mode.java
android/src/com/mapswithme/maps/maplayer/ToggleMapLayerDialog.java
android/src/com/mapswithme/maps/widget/menu/MainMenu.java
android/src/com/mapswithme/maps/widget/menu/MainMenuRenderer.java
android/src/com/mapswithme/util/SharedPropertiesUtils.java

https://jira.mail.ru/browse/MAPSME-13349

Mapsme 13349 layer indicator

---

android/src/com/mapswithme/maps/widget/menu/MainMenuRenderer.java

https://jira.mail.ru/browse/MAPSME-13349

[android] Added method to show toast at the top after layer is enabled

---

generator/generator_tests/road_access_test.cpp
routing/index_graph_loader.cpp
routing/road_access_serialization.hpp
routing/routing_tests/road_access_test.cpp

cherry-pick to master https://github.com/mapsme/omim/pull/12983

[routing] Adding logs in case wrong version (wrong header) of access conditional section.

---

android/gradle.properties
android/multidex-config.txt

https://jira.mail.ru/browse/MAPSME-13753

[android] Fixed crash on start on Android 4.4

---

android/multidex-config.txt

https://jira.mail.ru/browse/MAPSME-13753

[chpick][android] Fixed crash on start on Android 4.4

---

routing/road_access_serialization.cpp
routing/road_access_serialization.hpp

cherry-pick https://github.com/mapsme/omim/pull/12992

[routing] Crash fix for reading zero version of section roadaccess.

---

android/code_style_scheme.xml
android/jni/CMakeLists.txt
android/jni/com/mapswithme/maps/Framework.cpp
android/jni/com/mapswithme/maps/guides/Guides.cpp
android/jni/com/mapswithme/maps/guides/Guides.hpp
android/src/com/mapswithme/maps/guides/GuidesGallery.java

https://jira.mail.ru/browse/MAPSME-13353

Mapsme 13353 implement guides gallery

---

iphone/Maps/UI/Downloader/DownloadMapsViewController.swift

https://jira.mail.ru/browse/MAPSME-13772

[iOS] Fixed download button updating in DownloadMapsViewController

---

iphone/Maps/Classes/MapViewController.mm
iphone/Maps/UI/BottomMenu/MWMBottomMenuView.m
iphone/Maps/UI/BottomMenu/MWMBottomMenuViewController.xib
iphone/Maps/UI/Storyboard/Main.storyboard

https://jira.mail.ru/browse/MAPSME-13736
https://jira.mail.ru/browse/MAPSME-13733

[RELEASE_ONLY][iOS] Size and animation fixes for menu

---

iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift

https://jira.mail.ru/browse/MAPSME-13745

[iOS] Added promo statistics after loading catalog in PP

---

iphone/Maps/UI/PlacePage/Components/ActionBarViewController.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.h
iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.m
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift

https://jira.mail.ru/browse/MAPSME-13770

[iOS] set correct button state when appears in 'more' popup in PP

---

android/res/drawable/bg_rounded_card.xml
android/res/drawable/bg_rounded_card_night.xml
android/res/layout/guides_discovery_item.xml
android/res/values/dimens.xml
android/res/values/themes-attrs.xml
android/res/values/themes-base.xml

https://jira.mail.ru/browse/MAPSME-13353

[android] Added elevation and round background for guides gallery item

---

map/CMakeLists.txt
map/framework.cpp
map/guides_manager.cpp
map/guides_manager.hpp
map/guides_manager_delegate.cpp
map/guides_manager_delegate.hpp
partners_api/guides_on_map_api.cpp
partners_api/guides_on_map_api.hpp
partners_api/utm.hpp
xcode/map/map.xcodeproj/project.pbxproj

https://jira.mail.ru/browse/MAPSME-13680

[guides on map] request guides is implemented.

---

generator/feature_builder.hpp
generator/final_processor_complex.cpp
generator/final_processor_country.cpp
generator/final_processor_country.hpp
generator/final_processor_utils.cpp
generator/final_processor_utils.hpp
generator/mini_roundabout_transformer.cpp
generator/mini_roundabout_transformer.hpp
generator/raw_generator.cpp

Уменьшил потребление памяти. Сборка влезла на машине с 64 Гб памяти и 16 ядрами.

[generator] Reduced memory usage of generator tool.

---

android/res/drawable/ic_claim.xml
android/res/layout/guides_discovery_item.xml

https://jira.mail.ru/browse/MAPSME-13352

[android] Added btn

---

indexer/feature_decl.hpp

Цель реквеста -- сокращение объема реквеста по созданию нескольких секций с фичами (если он всё-таки будет) или не потерять мелкие улучшения сделанные в процессе (если его не будет).

[indexer] FeatureID minor style fixes.

---

partners_api/guides_on_map_api.cpp
partners_api/partners_api_tests/guides_on_map_tests.cpp
tools/python/jsons.py

[guides on map] client-server protocol is changed

---

android/src/com/mapswithme/maps/purchase/AbstractBookmarkSubscriptionFragment.java
android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionFragment.java

https://jira.mail.ru/browse/MAPSME-13757

[cherry-pick][android] Removed network policy checking from subscription screen

---

generator/feature_sorter.cpp
indexer/feature_impl.hpp
search/cities_boundaries_table.hpp

Цель реквеста -- сокращение объема реквеста по созданию нескольких секций с фичами (если он всё-таки будет) или не потерять мелкие улучшения сделанные в процессе (если его не будет).

[indexer][generator][search] Minor fixes.

---

android/gradle.properties
android/src/com/mapswithme/maps/purchase/AbstractBookmarkSubscriptionFragment.java
android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionFragment.java

https://jira.mail.ru/browse/MAPSME-13757

Mapsme 13757 network dialog on subs screen

---

android/res/values/strings.xml
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/maplayer/guides/GuidesState.java
android/src/com/mapswithme/maps/widget/menu/MainMenuRenderer.java
android/src/com/mapswithme/util/SharedPropertiesUtils.java
android/src/com/mapswithme/util/UiUtils.java

https://jira.mail.ru/browse/MAPSME-13349

Mapsme 13349 layer toasts

---

map/framework.cpp
map/framework.hpp
map/guides_manager.cpp

https://jira.mail.ru/browse/MAPSME-13778

[guides on map] guides layer is disabled after 8 hours in background

---

map/guides_manager.cpp
map/guides_manager.hpp

https://jira.mail.ru/browse/MAPSME-13764

[guides on map] shown guides counting is added

---

android/jni/com/mapswithme/maps/guides/Guides.cpp
android/src/com/mapswithme/maps/guides/GuidesGallery.java
map/guides_manager.cpp
map/guides_manager.hpp
partners_api/guides_on_map_api.cpp

Guides fixes

---

drape_frontend/my_position_controller.cpp
drape_frontend/my_position_controller.hpp

[drape frontend] Cherry pick for Arrow fix.

---

iphone/Maps/Classes/MapViewController.mm

https://jira.mail.ru/browse/MAPSME-13831

[iOS] Bring to front place page container on opening pp

---

android/res/layout/city_content.xml
android/res/layout/guides_discovery_item.xml
android/res/values/colors.xml
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
android/src/com/mapswithme/maps/gallery/Holders.java
android/src/com/mapswithme/maps/guides/GuidesGallery.java
android/src/com/mapswithme/maps/routing/RoutingController.java

https://jira.mail.ru/browse/MAPSME-13798

Mapsme 13798

---

routing/routing_session.cpp

Баг, на который стали жаловаться с 10.3: стрелка рандомно дергается в стороны при движении в режиме навигации.
https://jira.mail.ru/browse/MAPSME-13797

[routing] Fix for chaotic arrow in navigation view.

---

routing/routing_session.cpp

Cherry-pick from release-100: #13051

[routing] Cherry-pick for "Fix for arrow in car navigation".

---

iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift

https://jira.mail.ru/browse/MAPSME-13845

[iOS] Disable editing in ExpandableLabel

---

map/guides_manager.cpp
map/guides_manager.hpp

[guides on map] dummies are removed

---

android/src/com/mapswithme/maps/maplayer/guides/GuidesState.java
android/src/com/mapswithme/util/SharedPropertiesUtils.java

https://jira.mail.ru/browse/MAPSME-13349

[android] Added showing guides tutorial toast only once

---

iphone/Maps/UI/BottomMenu/Menu/BottomMenuViewController.swift

https://jira.mail.ru/browse/MAPSME-13827
https://jira.mail.ru/browse/MAPSME-13821

[iOS] Fixed height and scroll in bottom menu

---

partners_api/ads/ads_engine.cpp
partners_api/ads/ads_engine.hpp

https://jira.mail.ru/browse/MAPSME-13857

[ads] promo banners are not removable by "Remove Ads" subscription now.

---

partners_api/ads/ads_engine.cpp
partners_api/ads/ads_engine.hpp

cp for https://github.com/mapsme/omim/pull/13093

cherry-pick [ads] promo banners are not removable by "Remove Ads" subscription now.

---

iphone/Maps/UI/PlacePage/PlacePageInteractor.swift

https://jira.mail.ru/browse/MAPSME-13856

[iOS] Fixed share view present in action bar

---

iphone/Maps/UI/BottomMenu/Menu/BottomMenuInteractor.swift
iphone/Maps/UI/BottomMenu/Menu/BottomMenuPresenter.swift

https://jira.mail.ru/browse/MAPSME-13828

[iOS] Removed booking button from menu

---

iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm
iphone/Maps/UI/BottomMenu/MWMBottomMenuState.h
iphone/Maps/UI/BottomMenu/Menu/BottomMenuBuilder.swift
iphone/Maps/UI/BottomMenu/Menu/BottomMenuPresenter.swift
iphone/Maps/UI/BottomMenu/Menu/BottomMenuViewController.swift

https://jira.mail.ru/browse/MAPSME-13835

[iOS] Restored bottom layers menu

---

iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarPresenter.swift

https://jira.mail.ru/browse/MAPSME-13816

[iOS] Fixed guides menu badge count

---

map/bookmark_helpers.cpp
map/bookmark_helpers.hpp
map/bookmark_manager.cpp
map/bookmark_manager.hpp
map/framework.cpp
qt/mainwindow.cpp
qt/screenshoter.cpp
qt/screenshoter.hpp

Bookmark manager получает размер букмарка, чтобы иметь возможность скорректировать размер вьюпорта, затем стартует screenshoter.
JTALL
https://jira.mail.ru/browse/MAPSME-13789

[bookmarks] Avoid cropping of bookmarks in screenshoter

---

map/bookmark_catalog.cpp
map/bookmark_catalog.hpp
map/catalog_headers_provider.cpp
map/catalog_headers_provider.hpp
map/framework.cpp
map/guides_on_map_delegate.cpp
platform/http_client.hpp
web_api/request_headers.cpp
web_api/request_headers.hpp

Изменения для гидов на карте + https://jira.mail.ru/browse/MAPSME-13791
Смотреть лучше по коммитам.

Headers for downloaded guides

---

iphone/Maps/Bookmarks/Catalog/Subscription/BaseSubscriptionViewController.swift

https://jira.mail.ru/browse/MAPSME-13867

[iOS] Moved subscriptions in BaseSubscriptionViewController

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-13625

[android] Added map layer click statistic event

---

routing/opening_hours_serdes.cpp
routing/routing_tests/opening_hours_serdes_tests.cpp

cherry-pick https://github.com/mapsme/omim/pull/13111 to master

[routing][map build fix] ShouldSkipYear(...) functions returns a wrong value.

---

routing/opening_hours_serdes.cpp

[routing] Refactoring.

---

android/src/com/mapswithme/maps/maplayer/subway/TransitSchemeState.java
android/src/com/mapswithme/maps/maplayer/traffic/TrafficState.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-13625

[android] Removed map layers activate event usage

---

android/src/com/mapswithme/maps/gallery/Holders.java

https://jira.mail.ru/browse/MAPSME-13910

[android] Added hide/show

---

android/res/layout/menu_content.xml
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/widget/menu/MainMenu.java
android/src/com/mapswithme/maps/widget/menu/MainMenuOptionListener.java
android/src/com/mapswithme/maps/widget/menu/MainMenuRenderer.java

https://jira.mail.ru/browse/MAPSME-13829

Mapsme 13829

---

map/guides_manager.cpp

@yoksnod @alexzatsepin @beloal FYI

[guides on map] switch to network error state when internet is absent.

---

android/src/com/mapswithme/util/LocationUtils.java

Cherry-pick from master to release-100: #13121

[Android] Cherry-pick Fix for arrow rotation in not-default screen orientation.

---

map/framework.cpp

Cherry-pick from master to release-100: #13122

[map] Cherry-pick Fix azimuth disappearance for PP.

---

android/src/com/mapswithme/maps/bookmarks/BaseBookmarkCategoriesFragment.java
android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
android/src/com/mapswithme/maps/gallery/Holders.java
android/src/com/mapswithme/maps/widget/placepage/GuidesGalleryViewRenderer.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-13625

[android] Added forgotten guides layer statitstics

---

iphone/CoreApi/CoreApi/Traffic/MWMMapOverlayManager.mm
iphone/Maps/UI/BottomMenu/TabBar/BottomTabBarViewController.xib

Добавлена проверка на опциональных методах MWMMapOverlayManagerObserver
Удалена лишняя разделительная полоса

[iOS] Fixes in bottom TabBar

---

software_renderer/point.h
software_renderer/rect.h

Missing std includes resulted in build problems on some systems
as reported here: https://github.com/mapsme/omim/issues/11976

[software_renderer] Fix build.

---

android/jni/com/mapswithme/maps/isolines/IsolinesManager.cpp
android/src/com/mapswithme/maps/maplayer/AbstractIsoLinesClickListener.java
android/src/com/mapswithme/maps/maplayer/ToggleMapLayerDialog.java
android/src/com/mapswithme/maps/maplayer/isolines/IsolinesManager.java
android/src/com/mapswithme/maps/widget/menu/MainMenuRenderer.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-13649
https://jira.mail.ru/browse/MAPSME-13712

[android] Added isoLines toast

---

android/res/layout/place_page_banner_content.xml
android/src/com/mapswithme/maps/widget/placepage/BannerController.java

https://jira.mail.ru/browse/MAPSME-13358

[android] Fix for new banner colors

---

tracking/protocol.cpp
tracking/tracking_tests/protocol_test.cpp

@mpimenov @vicpopov PTAL (Pls see a letter for the details.)

[tracking] Wrong packet case.

---

iphone/CoreApi/CoreApi/Traffic/MWMMapOverlayManager.h
iphone/CoreApi/CoreApi/Traffic/MWMMapOverlayManager.mm
iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm
iphone/Maps/Common/Statistics/StatisticsStrings.h

https://jira.mail.ru/browse/MAPSME-13648
https://jira.mail.ru/browse/MAPSME-13711

[iOS] add toast for isolines on low zoom levels

---

android/res/values/colors.xml

https://jira.mail.ru/browse/MAPSME-13358

[android] Changed color for buttons and bg in pp banner

---

map/CMakeLists.txt
map/framework.cpp
map/guides_manager.cpp
map/guides_manager.hpp
map/isolines_manager.cpp
map/isolines_manager.hpp
map/layers_statistics.cpp
map/layers_statistics.hpp
map/traffic_manager.cpp
map/traffic_manager.hpp
map/transit/transit_reader.cpp
map/transit/transit_reader.hpp

https://jira.mail.ru/browse/MAPSME-13625

[layers] statistics

---

data/countries.txt
data/external_resources.txt

Попросил Антона, что бы удалил прошлые карты с той же версией

[planet] New data from 14.05.2020

---

transit/world_feed/CMakeLists.txt
transit/world_feed/world_feed.hpp
transit/world_feed/world_feed_integration_tests/CMakeLists.txt
transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp

Интеграционные тесты по результатам добавления класса WorldFeed (#12946).

[transit] World feed integration tests.

---

map/framework.cpp

https://jira.mail.ru/browse/MAPSME-13944

[guides on map] Stop follow location when the guides gallery is open.

---

tools/python/airmaps/README.md
tools/python/airmaps/__init__.py
tools/python/airmaps/dags/build_coastline.py
tools/python/airmaps/dags/build_maps.py
tools/python/airmaps/dags/update_planet.py
tools/python/airmaps/instruments/settings.py
tools/python/airmaps/instruments/storage.py
tools/python/airmaps/instruments/utils.py
tools/python/airmaps/requirements.txt
tools/python/airmaps/sandbox/.dockerignore
tools/python/airmaps/sandbox/README.md
tools/python/airmaps/sandbox/airmaps/Dockerfile
tools/python/airmaps/sandbox/airmaps/airflow.cfg
tools/python/airmaps/sandbox/airmaps/airmaps.ini
tools/python/airmaps/sandbox/airmaps/run_airmaps_service.sh
tools/python/airmaps/sandbox/build.sh
tools/python/airmaps/sandbox/clean.sh
tools/python/airmaps/sandbox/create_storage.sh
tools/python/airmaps/sandbox/docker-compose.yml
tools/python/airmaps/var/etc/airmaps.ini.default
tools/python/descriptions/descriptions_downloader.py
tools/python/maps_generator/generator/env.py
tools/python/maps_generator/generator/generation.py
tools/python/maps_generator/generator/settings.py
tools/python/maps_generator/generator/stages.py
tools/python/maps_generator/generator/stages_declaration.py
tools/python/maps_generator/generator/status.py
tools/python/maps_generator/generator/steps.py
tools/python/maps_generator/maps_generator.py
tools/python/maps_generator/utils/file.py

Примерно так будет выглядеть главное окно(зеленые кружочки - статус успешного выполнения):
А вот кусочек графа для борки карт:
Как я понял пока не планируется использоваться на текущих машинах. Артем говорил что будет заводить это на других машинах(десктопных) попозже.

[generator][python] Added airmaps.

---

iphone/Maps/UI/Downloader/DownloadAllView/DownloadAllView.swift
iphone/Maps/UI/Downloader/DownloadAllView/DownloadAllView.xib
iphone/Maps/UI/Downloader/DownloadMapsViewController.swift

https://jira.mail.ru/browse/MAPSME-13588

[iOS] Downloader bottom panel: fixed style for night theme, added error state, removed ambiguous states

---

map/guides_manager.cpp
map/guides_manager.hpp
partners_api/guides_on_map_api.cpp
partners_api/guides_on_map_api.hpp

реквест на мастер апстрима, потому что переключить на нужную ветку в рамках https://github.com/milchakov/omim/pull/8 не удалось.

Guides cancel tasks

---

iphone/Maps/UI/PlacePage/PlacePage.storyboard
partners_api/guides_on_map_api.cpp

https://jira.mail.ru/browse/MAPSME-13917

Fix track duration parsing/display

---

tools/python/maps_generator/__main__.py
tools/python/maps_generator/check_logs.py
tools/python/maps_generator/check_maps.py
tools/python/maps_generator/checks/check.py
tools/python/maps_generator/checks/check_addresses.py
tools/python/maps_generator/checks/check_categories.py
tools/python/maps_generator/checks/check_log_levels.py
tools/python/maps_generator/checks/check_mwm_types.py
tools/python/maps_generator/checks/check_sections.py
tools/python/maps_generator/checks/check_size.py
tools/python/maps_generator/checks/default_check_set.py
tools/python/maps_generator/checks/logs/logs_reader.py
tools/python/maps_generator/generator/env.py
tools/python/maps_generator/generator/stages.py
tools/python/maps_generator/tests/test_logs_reader.py
tools/python/maps_generator/update_generation_order.py
tools/python/maps_generator/utils/algo.py
tools/python/maps_generator/utils/log.py
tools/python/mwm/mwm_python.py

Пример можно глянуть здесь
https://t.bk.ru/I00Wl/200402-200514.checks.txt

[python][generator] Added logs and maps checks

---

iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.h
iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
iphone/Maps/Categories/URL+Query.swift
iphone/Maps/Maps.xcodeproj/project.pbxproj

https://jira.mail.ru/browse/MAPSME-13813

[iOS] open route on map from catalog

---

search/cbv.cpp
search/cbv.hpp
search/features_layer_matcher.hpp
search/geocoder.cpp
search/geocoder.hpp
search/search_integration_tests/processor_test.cpp

Чинит и поиск poi внутри и просто поиск сабурбов: мы раньше не эмитили ничего если все токены использованы и predictions для улиц внутри сабурба пустые. https://jira.mail.ru/browse/MAPSME-13808

[search] Fix suburbs search. Match pois with suburbs.

---

iphone/Maps/Classes/MapViewController.mm
iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
iphone/Maps/MAPSME.plist

I'm one of the developers of the WunderLINQ. The WunderLINQ enables you to use your motorcycle's handlebar controls to control your smartphone. Essentially the device acts as a Bluetooth keyboard.
Here is a video of the integration in action: https://youtu.be/2QHUiheVF5c
Support was recently committed to the Android App, this PR is for the iOS App.

[iOS]Initial WunderLINQ Support

---

tools/python/maps_generator/generator/env.py
tools/python/maps_generator/generator/exceptions.py
tools/python/maps_generator/generator/stages.py
tools/python/maps_generator/generator/stages_declaration.py
tools/python/maps_generator/generator/stages_tests.py

Добавалено тестирование стадий: добавлено тестирования свежести данных букинга.

[python][generator] Added @test_stage; added booking data test.

---

iphone/Maps/UI/BottomMenu/Menu/BottomMenuBuilder.swift
iphone/Maps/UI/BottomMenu/Menu/BottomMenuPresenter.swift
iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuLayersCell.swift
iphone/Maps/UI/PlacePage/Components/GuidesGallery/GuidesGalleryPresenter.swift

https://jira.mail.ru/browse/MAPSME-13960
Исправлены пункты 1 и 4. Остально в ядре

[iOS] fix stats

---

iphone/Maps/Classes/MapViewController.mm
iphone/Maps/UI/PlacePage/Components/GuidesGallery/GuidesGalleryViewController.swift
iphone/Maps/UI/Storyboard/Main.storyboard

https://jira.mail.ru/browse/MAPSME-13922

[iOS] hide gudes gallery on swipe. Fix selection on map issues

---

routing/routing_integration_tests/route_test.cpp
routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp

cherry-pick первых 2 коммитов из https://github.com/mapsme/omim/pull/13197

[routing] Fixing rit and rqt for the map 200514.

---

drape_frontend/frontend_renderer.cpp
drape_frontend/frontend_renderer.hpp
drape_frontend/message.cpp
map/guides_manager.cpp
map/guides_manager.hpp
map/guides_marks.cpp
map/guides_marks.hpp

Черновое отключение вытеснения иконок в слое гидов. В дальнейшем планируется замена иконок на версию без теней.

[guides on map] Disabled icons displacement.

---

android/src/com/mapswithme/maps/MwmActivity.java

https://jira.mail.ru/browse/MAPSME-13824

[android] Added closing the main bottom menu on touch outside

---

tools/python/maps_generator/generator/env.py

Cherry-pick from master: #13215

[python][generator] Fix for transit_path_experimental. Cherry-pick to release-101.

---

iphone/Maps/Classes/Components/VerticallyAlignedButton.swift
iphone/Maps/Core/Theme/GlobalStyleSheet.swift
iphone/Maps/UI/BottomMenu/Menu/BottomMenuViewController.swift
iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuItemCell.xib
iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuLayerButton.swift
iphone/Maps/UI/BottomMenu/Menu/Cells/BottomMenuLayersCell.xib

https://jira.mail.ru/browse/MAPSME-13988

[iOS] Bottom menu visual fixes

---

iphone/Maps/UI/Storyboard/Settings.storyboard

https://jira.mail.ru/browse/MAPSME-13776

[iOS] Fixed constraints in settings

---

tools/python/booking/__main__.py
tools/python/booking/api/booking_api.py
tools/python/booking/download_hotels.py
tools/python/booking/download_test_data.py
tools/python/descriptions/__main__.py
tools/python/descriptions/descriptions_downloader.py
tools/python/post_generation/__main__.py
tools/python/post_generation/hierarchy_to_countries.py
tools/python/post_generation/inject_promo_ids.py
tools/python/post_generation/localads_mwm_to_csv.py

Изменил форматирование на то, которое исопльзуется в maps_generator и airmaps

[python] Refactoring: Changed formatting.

---

iphone/Maps/Categories/NSAttributedString+HTML.swift
iphone/Maps/UI/PlacePage/Components/PlacePageBookmarkViewController.swift

https://jira.mail.ru/browse/MAPSME-13740

[iOS] resize images in html description of object to fit PP width

---

map/guides_manager.cpp
map/guides_manager.hpp

https://jira.mail.ru/browse/MAPSME-13924

[guides on map] network errors frequency is reduced (5 sec timeout)

---

android/jni/com/mapswithme/maps/Framework.cpp

https://jira.mail.ru/browse/MAPSME-13946

[android] Changed order of settings saving

---

android/src/com/mapswithme/maps/gallery/Holders.java

https://jira.mail.ru/browse/MAPSME-14020

Mapsme 14020 new strs

---

android/res/layout/menu_content.xml

https://jira.mail.ru/browse/MAPSME-14021

[android] Fixed paddings in layers header in main menu

---

transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp

@bykoianko PTAL
Интеграционный тест на корректность разбивки фида на несколько mwm. Следует за #13178. Специально для теста в архив gtfs-feeds-for-tests.zip добавлен фид, состоящий из одного маршрута через 4 mwm, по одной остановке на каждую.

[transit] Integration tests for splitting feed into regions.

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/routing/NavigationController.java
android/src/com/mapswithme/maps/widget/menu/BaseMenu.java
android/src/com/mapswithme/maps/widget/menu/MainMenu.java

https://jira.mail.ru/browse/MAPSME-13823

[android] Added new marker update when menu is closed

---

android/res/drawable/ic_claim_city.xml
android/src/com/mapswithme/maps/gallery/Holders.java

https://jira.mail.ru/browse/MAPSME-13915

[android] Changed city image

---

android/src/com/mapswithme/maps/widget/placepage/GuidesGalleryViewRenderer.java

https://jira.mail.ru/browse/MAPSME-13961

[android] Added missed statistic event for guides gallery item click

---

drape/drape_tests/testing_graphics_context.hpp
drape/graphics_context.hpp
drape/metal/metal_base_context.hpp
drape/oglcontext.hpp
drape/vulkan/vulkan_base_context.cpp
drape/vulkan/vulkan_base_context.hpp
drape_frontend/frontend_renderer.cpp
drape_frontend/postprocess_renderer.cpp

Cherry-pick for #13207 from master to release-101.

[drape] [android] [vulkan] Cherry-pick. Sporadic crash on layer switching MAPSME-13706

---

search/features_layer_matcher.hpp
search/geocoder.cpp
search/geocoder_context.cpp
search/geocoder_context.hpp
search/intersection_result.cpp
search/intersection_result.hpp
search/model.cpp
search/model.hpp
search/ranker.cpp
search/ranking_info.cpp
search/ranking_info.hpp
search/search_integration_tests/pre_ranker_test.cpp
search/search_integration_tests/processor_test.cpp
search/search_integration_tests/tracer_tests.cpp
search/search_quality/scoring_model.py
search/search_tests/ranking_tests.cpp

Теперь работают запросы типа "Макдональдс Авиапарк", "Шереметьево терминал D" и т.п.

[search] Support POI-POI parse.

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/auth/Authorizer.java
android/src/com/mapswithme/maps/auth/PassportAuthDialogFragment.java
android/src/com/mapswithme/maps/auth/SocialAuthDialogFragment.java
android/src/com/mapswithme/maps/base/BaseAuthFragment.java
android/src/com/mapswithme/maps/base/BaseToolbarAuthFragment.java
android/src/com/mapswithme/maps/bookmarks/AuthBundleFactory.java
android/src/com/mapswithme/maps/bookmarks/BookmarkBackupController.java
android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogActivity.java
android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadFragmentDelegate.java
android/src/com/mapswithme/maps/editor/AuthDialogFragment.java
android/src/com/mapswithme/maps/editor/EditorHostFragment.java
android/src/com/mapswithme/maps/editor/OsmAuthFragmentDelegate.java
android/src/com/mapswithme/maps/intent/Factory.java
android/src/com/mapswithme/maps/purchase/AbstractBookmarkSubscriptionFragment.java
android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
android/src/com/mapswithme/maps/ugc/routes/SendLinkPlaceholderFragment.java
android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
android/src/com/mapswithme/util/KeyValue.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-13632

[android] Added some new auth stats

---

coding/coding_tests/string_utf8_multilang_tests.cpp
coding/string_utf8_multilang.cpp
coding/string_utf8_multilang.hpp
generator/feature_builder.cpp
generator/generator_tests/feature_builder_test.cpp

драфт поверх https://github.com/mapsme/omim/pull/13229

[generator] Do not add alt name which is almost equal to default name.

---

shaders/Metal/gui.metal
shaders/metal_program_pool.mm

https://jira.mail.ru/browse/MAPSME-13322

[drape] [iOS] [Metal] Fix vertex layout for GUI static outlined text

---

coding/string_utf8_multilang.cpp
coding/string_utf8_multilang.hpp

ревью фиксы к реквесту https://github.com/mapsme/omim/pull/13260

[coding] StringUtf8Multilang minor refactoring.

---

shaders/Metal/gui.metal
shaders/metal_program_pool.mm

Cherry-pick for #13273 from master.

[drape] [iOS] [Metal] Cherry-pick. Fix vertex layout for GUI static outlined text MAPSME-13322

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/base/NoConnectionListener.java
android/src/com/mapswithme/maps/maplayer/DefaultClickListener.java
android/src/com/mapswithme/maps/maplayer/ToggleMapLayerDialog.java
android/src/com/mapswithme/maps/maplayer/guides/AbstractGuidesClickListener.java
android/src/com/mapswithme/maps/widget/menu/MainMenuRenderer.java
android/src/com/mapswithme/maps/widget/menu/MenuControllerFactory.java

https://jira.mail.ru/browse/MAPSME-13946

Mapsme 13946 v2

---

android/res/drawable/ic_claim_city_night.xml
android/res/drawable/ic_claim_night.xml
android/res/values/colors.xml
android/res/values/themes-attrs.xml
android/res/values/themes-base.xml
android/src/com/mapswithme/maps/gallery/Holders.java

https://jira.mail.ru/browse/MAPSME-14098

[android] Changeg night resources for guides gallery item ui

---

data/countries.txt
data/external_resources.txt
routing/routing_integration_tests/speed_camera_notifications_tests.cpp

https://t.bk.ru/b7Fi1/200514-200607.checks.txt

[planet] New data from 07.06.2020

---

generator/generator_integration_tests/features_tests.cpp
generator/place_processor.cpp

Провела несколько экспериментов с разными эвристиками. В текущей версия по крайней мере World строго лучше чем при сборке из master.

[generator] PlaceProcessor: tune IsWorsePlace coeffs.

---

base/base_tests/bidirectional_map_tests.cpp
base/bidirectional_map.hpp
base/thread_pool_delayed.cpp
base/thread_pool_delayed.hpp

Хотел сделать отдельный класс для очереди отложенных задач, но очень сильно пересекался бы с существующим bidirectional map, поэтому все же решил немного модифицировать существующий шаблон. Методы GetFirstKey/GetFirstValue не совсем ложатся в логику bidirectional map, поэтому была мысль сделать m_kToV и m_vToK защищенными членами и приватно занаследоваться и в наследнике уже реализовать GetFirstKey/GetFirstValue. Но решил пока сделать так и получить ваши отзывы.
https://jira.mail.ru/browse/MAPSME-14033

[base] Tasks cancelling improvements

---

iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm

https://jira.mail.ru/browse/MAPSME-14095

[iOS] fix zoom buttons layout on RTL layout

---

tools/python/maps_generator/check_logs.py
tools/python/maps_generator/check_mwms.py
tools/python/maps_generator/checks/check_mwm_types.py
tools/python/maps_generator/checks/default_check_set.py

Изменил значения фильтров на около дженкинсовские:)
Добавлена опция checks для удобства

[python][generator] Added the option '--checks'; Changed filters.

---

iphone/Maps/Classes/MapViewController.h
iphone/Maps/Classes/MapViewController.mm
iphone/Maps/UI/PlacePage/PlacePageBuilder.swift
iphone/Maps/UI/PlacePage/PlacePageInteractor.swift
iphone/Maps/UI/PlacePage/PlacePagePresenter.swift
iphone/Maps/UI/PlacePage/PlacePageViewController.swift

https://jira.mail.ru/browse/MAPSME-14016

[iOS] Restored map buttons offset

---

iphone/Maps/UI/PlacePage/Components/PlacePageInfoViewController.swift

https://jira.mail.ru/browse/MAPSME-13974

[iOS] display coordinates in decimal style in PP by default

---

iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift

https://jira.mail.ru/browse/MAPSME-6182

[iOS] fix expandable label bg color (especially in night mode)

---

iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingFlow.storyboard

https://jira.mail.ru/browse/MAPSME-13718

[iOS] fix description input style on bookmarks share screen

---

iphone/Maps/Bookmarks/Catalog/Dialogs/SubscriptionExpiredViewController.xib
iphone/Maps/Bookmarks/Catalog/Dialogs/SubscriptionFailViewController.xib
iphone/Maps/Bookmarks/Catalog/Dialogs/SubscriptionGoToCatalogViewController.xib

https://jira.mail.ru/browse/MAPSME-12843

[iOS] fix catalog dialogs' styles

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java

https://jira.mail.ru/browse/MAPSME-13846

[android] Added guides 8 hour processing

---

iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift

https://jira.mail.ru/browse/MAPSME-14132

[iOS] Fixed PP height for empty bookmark description

---

iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
iphone/Maps/UI/PlacePage/Components/PlacePagePreviewViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift

https://jira.mail.ru/browse/MAPSME-13674

[iOS] update bookmark related section in PP on bookmark add/remove

---

iphone/Maps/UI/Authorization/AuthorizationViewController.swift

https://jira.mail.ru/browse/MAPSME-14119

[iOS] Fixed some authoriztion statistics parameters

---

3party/opening_hours/opening_hours.cpp
3party/opening_hours/opening_hours.hpp
editor/editor_tests/ui2oh_test.cpp
generator/routing_index_generator.cpp
generator/transit_generator_experimental.cpp
generator/transit_generator_experimental.hpp
tools/python/maps_generator/generator/stages.py
tools/python/maps_generator/generator/stages_declaration.py
transit/experimental/transit_data.cpp
transit/experimental/transit_data.hpp
transit/experimental/transit_types_experimental.cpp
transit/experimental/transit_types_experimental.hpp
transit/transit_entities.hpp
transit/transit_serdes.hpp
transit/world_feed/date_time_helpers.cpp
transit/world_feed/date_time_helpers.hpp

Сериализация и десериализация новой транзитной секции. 
Реквест следует за #13187. 
Для транзитных классов [готовы юнит-тесты](https://github.com/mesozoic-drones/omim/pull/2) чтения из json, в которые добавлены тесты на сериализацию/десериализацию секции mwm. **Эти тесты проходят.** Они будут мержиться на мастер после мержа этого реквеста.

[generator][transit][routing] Ser/des new version of transit mwm section.

---

generator/transit_generator_experimental.cpp
transit/CMakeLists.txt
transit/experimental/transit_data.cpp
transit/experimental/transit_data.hpp
transit/experimental/transit_types_experimental.cpp
transit/experimental/transit_types_experimental.hpp
transit/transit_entities.hpp
transit/transit_experimental_tests/CMakeLists.txt
transit/transit_experimental_tests/parse_transit_from_json_tests.cpp
transit/transit_experimental_tests/transit_serdes_tests.cpp
transit/transit_tests/transit_json_parsing_test.cpp
transit/transit_tests/transit_tools.hpp

[transit][tests] Unit tests for experimental transit entities.

---

iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
iphone/Maps/Bookmarks/Catalog/Subscription/AllPassSubscriptionViewController.swift
iphone/Maps/Bookmarks/Catalog/Subscription/BaseSubscriptionViewController.swift
iphone/Maps/Core/InappPurchase/Impl/PaidRouteStatistics.swift
iphone/Maps/Core/InappPurchase/InAppPurchase.swift

https://jira.mail.ru/browse/MAPSME-14118

[iOS] Fixes in subscription statistic

---

generator/generator_tests/feature_builder_test.cpp

из-за того что нет типа amenity=shop в дебаге срабатывал ассерт

[generator_tests] Fix non-existent type.

---

iphone/Maps/UI/PlacePage/PlacePage.storyboard

https://jira.mail.ru/browse/MAPSME-14149

[iOS] Fixed 'more' button localization in PP

---

drape_frontend/frontend_renderer.cpp

https://jira.mail.ru/browse/MAPSME-13276

[drape] Improve conditions to mark RenderGroups as CanBeDeleted 

---

iphone/Maps/UI/Downloader/DownloadMapsViewController.swift

https://jira.mail.ru/browse/MAPSME-14142

[iOS] Added datasource to available maps when opening from child folder

---

data/mapcss-mapping.csv

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling
https://taginfo.openstreetmap.org/keys/recycling:batteries

[mapcss] Fix rule for recycling=toxic.

---

tools/python/mwm/mwm_pygen.py
tools/python/mwm/mwm_python.py

Значительное ускорение сборки: не вычитываем фичу полностью, вычитываем только то что нужно

[generator][python] Mwm reading speed-up

---

iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift

https://jira.mail.ru/browse/MAPSME-13674

[iOS] fix show/hide bookmark related section on add/remove bookmark

---

iphone/Maps/UI/Settings/MWMSettingsViewController.mm

https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/handling_subscriptions_billing?language=objc

[iOS] update link to manage subscriptions page

---

data/categories.txt

в синонимах уже есть то же самое на katakana: バス

[categories] Add hirigana for bus_stop/bus_station.

---

map/guides_manager.cpp

https://jira.mail.ru/browse/MAPSME-14196

[guides on map] stop location follow when cluster is clicked

---

routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp

cherry-pick https://github.com/mapsme/omim/pull/13204 to release-101

[routing] Fixing rqt for the map 200514.

---

routing/routing_integration_tests/speed_camera_notifications_tests.cpp

cherry-pick https://github.com/mapsme/omim/pull/13325 to master with fixing conflicts.

[routing] Fixing routing integration tests for map 200607.

---

drape_frontend/frontend_renderer.cpp
drape_frontend/frontend_renderer.hpp
map/bookmark_manager.cpp
map/bookmark_manager.hpp
map/framework.cpp
map/guides_manager.cpp
map/guides_manager.hpp

1) Увеличена область тапа для иконок гидов и кластеров.
2) Снятие выделения с гидов https://jira.mail.ru/browse/MAPSME-13913
3) Мгновенное обновление иконки загруженных гидов https://jira.mail.ru/browse/MAPSME-13956

[guides on map] Render layer background. Fixes.

---

iphone/Maps/Classes/MapViewController.mm

https://jira.mail.ru/browse/MAPSME-14194

[iOS] fix "show on map" after downloading guide from gallery

---

map/bookmark_manager.cpp
map/bookmark_manager.hpp

https://jira.mail.ru/browse/MAPSME-14257

[bookmarks][android] Fixed crash after deleting a just created category.

---

android/src/com/mapswithme/maps/MwmActivity.java
map/framework.cpp
map/framework.hpp

https://jira.mail.ru/browse/MAPSME-13913

[guides on map] Deselect guide on gallery closing by swipe down.

---

indexer/feature_utils.cpp
indexer/feature_utils.hpp
search/processor.cpp
search/search_integration_tests/processor_test.cpp

обычно дополнительные (или в случае с be исходный) языки не слишком "жирные", поэтому не должно стать слишком медленно

[search] Use languages similar to device and query languages.

---

iphone/Maps/Classes/MapViewController.mm

https://jira.mail.ru/browse/MAPSME-14174

[iOS] Fallback to old search in navigation

---

map/purchase.cpp
map/purchase.hpp

[purchase] trial subscription dummies.

---

map/transit/transit_display.cpp

Из cpp убран `using namespace routing`. Это нужно для того, чтобы в последующих реквестах сюда можно было подключить классы, ответственные за работу с экспериментальным транзитом (не только метро, а общественный транспорт вообще). Эти новые классы находятся в неймспейсе `::transit::experimental`, и при подключенном юзинге роутинга конфликтуют с `routing::transit`. Аналогичные выкидывания юзинга уже проделаны в генераторе и некоторых файлах роутинга.

[map] Remove using routing namespace from transit display.

---

android/jni/com/mapswithme/maps/Framework.cpp
iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
partners_api/ads/ads_base.cpp
partners_api/ads/ads_base.hpp
partners_api/ads/ads_engine.cpp
partners_api/ads/ads_engine.hpp
partners_api/ads/bookmark_catalog_ads.cpp
partners_api/ads/bookmark_catalog_ads.hpp

https://jira.mail.ru/browse/MAPSME-14247

[ads] showing bookmark catalog promo during map downloading is fixed

---

android/jni/com/mapswithme/maps/SearchEngine.cpp
android/src/com/mapswithme/maps/search/BookingFilterParams.java
iphone/Maps/UI/Search/Filters/MWMHotelParams.mm
partners_api/booking_availability_params.cpp
partners_api/booking_availability_params.hpp
partners_api/partners_api_tests/booking_tests.cpp

[booking] age of children is array now.

---

tools/python/transit/gtfs/download_gtfs.py

[tools][transit] Updated gtfs crawler log message.

---

iphone/Maps/UI/PlacePage/Components/PlacePageBookmarkViewController.swift
iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift

https://jira.mail.ru/browse/MAPSME-14299

[iOS] fix a bug in which "more" button below bookmark description in PP is not available

---

base/base_tests/exception_tests.cpp
base/exception.hpp

Обработка случая для перехватчика всех исключений (добавлен в https://github.com/mapsme/omim/pull/13385), когда функция возвращает void.

[base] Returns void case for all kinds of exceptions catcher.

---

android/gradle.properties
android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
android/src/com/mapswithme/maps/bookmarks/InvalidSubscriptionAlertDialogCallback.java
android/src/com/mapswithme/maps/purchase/BookmarkSubscriptionFragment.java
android/src/com/mapswithme/maps/purchase/PurchaseUtils.java

https://jira.mail.ru/browse/MAPSME-13812
https://jira.mail.ru/browse/MAPSME-14286

Mapsme 13812 already downloaded guide

---

.gitignore
android/.gitignore
android/AndroidManifest.xml
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
android/jni/com/mapswithme/core/logging.cpp
android/multidex-config.txt
android/src/com/mapswithme/maps/analytics/ExternalLibrariesMediator.java
android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
android/src/com/mapswithme/util/CrashlyticsUtils.java
android/src/com/mapswithme/util/log/LoggerFactory.java
configure.sh

https://jira.mail.ru/browse/MAPSME-14125

[android] Firebase SDK integration

---

.gitignore
android/.gitignore
android/AndroidManifest.xml
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
android/jni/com/mapswithme/core/logging.cpp
android/multidex-config.txt
android/src/com/mapswithme/maps/analytics/ExternalLibrariesMediator.java
android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
android/src/com/mapswithme/util/CrashlyticsUtils.java
android/src/com/mapswithme/util/log/LoggerFactory.java
configure.sh

https://jira.mail.ru/browse/MAPSME-14125
cp for https://github.com/mapsme/omim/pull/13398

[cherry-pick][android] Firebase SDK integration

---

android/jni/com/mapswithme/maps/Framework.cpp
iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
partners_api/ads/ads_base.cpp
partners_api/ads/ads_base.hpp
partners_api/ads/ads_engine.cpp
partners_api/ads/ads_engine.hpp
partners_api/ads/bookmark_catalog_ads.cpp
partners_api/ads/bookmark_catalog_ads.hpp

cherry pick for https://github.com/mapsme/omim/pull/13360

cherry-pick [ads] showing bookmark catalog promo during map downloading is fixed

---

data/categories.txt

черри-пик https://github.com/mapsme/omim/pull/13410 в минорку

[search][categories] Create metacategory for recycling.

---

android/jni/com/mapswithme/platform/Language.cpp
android/src/com/mapswithme/util/Utils.java
platform/CMakeLists.txt
platform/locale.hpp
platform/locale.mm
platform/locale_linux.cpp

это нужно для новой версии апи букинга

[platform] locales are provided into core.

---

iphone/Maps/UI/PlacePage/Components/CatalogGalleryViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard

https://jira.mail.ru/browse/MAPSME-14276

[iOS] Changed style for CatalogGalleryView in PP

---

iphone/Maps/Maps.xcodeproj/project.pbxproj

https://jira.mail.ru/browse/MAPSME-14162

[iOS] Fixed dsym path for Beta build

---

map/search_mark.cpp
map/search_mark.hpp

price - это текст справа от colored symbol сёрчмарки. Не имеет смысла до завершения MAPSME-14322
https://jira.mail.ru/browse/MAPSME-14321

[booking] Add possibility to specify additional textual price value for searchmarks

---

kml/pykmlib/bindings.cpp

Добавление в исключения больше информации, в случае его возникновения.
https://github.com/mapsme/omim/pull/13409 не только перехватывал std исключения. Он более подробно логировал причину их возникновения. Поскольку мы его закрыли из-за того, что Boost.Python корректно обрабатывает std исключения, я добавил отдельным PR добавление информацию в исключения.
@vicpopov @milchakov PTAL

[pykmlib] Adding more about language info to log in case of exceptions.

---

android/jni/com/mapswithme/maps/Framework.cpp
android/src/com/mapswithme/maps/Framework.java
android/src/com/mapswithme/maps/PurchaseOperationObservable.java
android/src/com/mapswithme/maps/purchase/CoreValidationObserver.java
android/src/com/mapswithme/maps/purchase/DefaultPurchaseValidator.java
iphone/Maps/Core/InappPurchase/Impl/MWMPurchaseValidation.mm
map/purchase.cpp
map/purchase.hpp

Для заглушки сделал якобы всегда триал

[purchase] trial flag for validation callback dummy.

---

data/faq.html

Fixed a broken link to online help

[FAQ] Fixed broken link

---

data/faq.html

cherry-pick https://github.com/mapsme/omim/pull/13420

Fixed broken link

---

map/CMakeLists.txt
map/booking_availability_filter.cpp
map/booking_availability_filter.hpp
map/booking_filter.hpp
map/booking_filter_cache.cpp
map/booking_filter_cache.hpp
map/booking_filter_params.hpp
map/booking_filter_processor.cpp
map/booking_filter_processor.hpp
map/booking_utils.cpp
map/booking_utils.hpp
map/framework.cpp
map/map_tests/booking_availability_cache_test.cpp
map/map_tests/booking_filter_test.cpp
map/search_api.cpp
partners_api/booking_api.cpp
partners_api/booking_api.hpp
partners_api/partners_api_tests/booking_tests.cpp
platform/locale.mm
xcode/map/map.xcodeproj/project.pbxproj
xcode/platform/platform.xcodeproj/project.pbxproj

https://jira.mail.ru/browse/MAPSME-14327
+
часть https://jira.mail.ru/browse/MAPSME-14329

Booking v26

---

partners_api/partners_api_tests/mts_tests.cpp
partners_api/partners_api_tests/skyeng_tests.cpp
partners_api/partners_api_tests/tinkoff_airlines_tests.cpp
partners_api/partners_api_tests/tinkoff_insurance_tests.cpp

черри-пик https://github.com/mapsme/omim/pull/13415

[ads] tests fixes

---

data/categories.txt

https://jira.mail.ru/browse/MAPSME-11117 – добавил только синоним для отеля
https://jira.mail.ru/browse/MAPSME-11159 – исправил перевод

[Categories] fixed translations

---

map/booking_utils.cpp
map/booking_utils.hpp
map/framework.cpp
map/place_page_info.hpp
map/search_mark.cpp
map/search_mark.hpp

https://jira.mail.ru/browse/MAPSME-14329
и заглушки для остальных взаимодействий с дрэйпом

[search_marks] dummies for booking improvements

---

map/purchase.cpp
map/purchase.hpp

https://jira.mail.ru/browse/MAPSME-14335
https://jira.mail.ru/browse/MAPSME-14334
@Polas @alexzatsepin @beloal fyi

[purchase] Trial implementation

---

map/booking_utils.cpp

[booking] review fixes for booking filters

---

data/countries.txt
data/external_resources.txt

Mwm ки можно увидеть тут: http://mapsme4.devmail.ru/mwm/
Логи тут: http://mapsme4.devmail.ru/mwm/logs/
Тесты запускал на серверах, результаты вот:
https://t.bk.ru/eWhPd/200607-200714.checks.txt
https://t.bk.ru/YKDCy/200607-200714-logs.checks.txt
Обзор показал что все отклонения в пределах нормы.

[planet] New data from 14.07.2020

---

android/build.gradle
android/gradle.properties
android/jni/CMakeLists.txt

https://jira.mail.ru/browse/MAPSME-14125

Mapsme 14125 firebase crashlytics fix

---

android/jni/com/mapswithme/maps/Framework.cpp
android/src/com/mapswithme/maps/Framework.java
android/src/com/mapswithme/maps/purchase/AbstractBookmarkSubscriptionFragment.java
android/src/com/mapswithme/maps/purchase/AbstractBookmarkValidationCallback.java
android/src/com/mapswithme/maps/purchase/DefaultPurchaseValidator.java
android/src/com/mapswithme/maps/purchase/SubscriptionPurchaseController.java
android/src/com/mapswithme/maps/purchase/TwoButtonsSubscriptionFragmentDelegate.java
android/src/com/mapswithme/maps/purchase/ValidationCallback.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-14208

[android] Added statistic for subscription trial

---

android/res/layout/fragment_search_filter.xml
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/search/FilterActivity.java
android/src/com/mapswithme/maps/search/FilterFragment.java

https://jira.mail.ru/browse/MAPSME-14180

[android] Removed checkin/checkout controls from the filter screen

---

android/jni/com/mapswithme/maps/Framework.cpp
android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadFragmentDelegate.java
android/src/com/mapswithme/maps/bookmarks/InvalidSubscriptionAlertDialogCallback.java
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.h
iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
iphone/Maps/Bookmarks/Catalog/PaidRouteViewController.swift
iphone/Maps/Bookmarks/Catalog/UIViewController+Subscription.swift
iphone/Maps/Core/Subscriptions/MWMPurchaseManager.mm
iphone/Maps/UI/Subscription/SubscriptionInteractor.swift
map/bookmark_manager.cpp
map/bookmark_manager.hpp
map/purchase.cpp
map/purchase.hpp
platform/marketing_service.cpp
platform/marketing_service.hpp

"invalid" categories are "expired" now
https://jira.mail.ru/browse/MAPSME-14428

Trial statistics + renaming

---

android/jni/com/mapswithme/platform/Localization.cpp
android/src/com/mapswithme/util/Utils.java
map/booking_utils.cpp
map/booking_utils.hpp
map/framework.cpp
map/map_tests/booking_filter_test.cpp
platform/localization.hpp
platform/localization.mm
platform/localization_dummy.cpp

https://jira.mail.ru/browse/MAPSME-14332

Booking price formatting

---

map/booking_availability_filter.cpp
map/booking_availability_filter.hpp
map/booking_filter.hpp
map/booking_filter_params.hpp
map/booking_filter_processor.cpp
map/booking_filter_processor.hpp
map/booking_utils.cpp
map/booking_utils.hpp
map/framework.cpp
map/framework.hpp
map/map_tests/booking_filter_test.cpp
map/search_mark.cpp
map/search_mark.hpp

https://jira.mail.ru/browse/MAPSME-14331
https://jira.mail.ru/browse/MAPSME-14333
https://jira.mail.ru/browse/MAPSME-14381
https://jira.mail.ru/browse/MAPSME-14427

[booking] processing for unavailable and visited hotels.

---

map/booking_availability_filter.cpp
map/search_api.cpp

https://jira.mail.ru/browse/MAPSME-14380

[booking] crash fixes

---

iphone/CoreApi/CoreApi/InappPurchase/IMWMPurchaseValidation.h
iphone/CoreApi/CoreApi/InappPurchase/Impl/MWMPurchaseValidation.mm
iphone/Maps/Bookmarks/Catalog/PaidRouteViewController.swift
iphone/Maps/Classes/MapsAppDelegate.mm
iphone/Maps/Common/Statistics/StatisticsStrings.h
iphone/Maps/Core/InappPurchase/Impl/PaidRoutePurchase.swift
iphone/Maps/Core/InappPurchase/Impl/PaidRouteStatistics.swift
iphone/Maps/Core/InappPurchase/Impl/PendingTransactionsHandler.swift
iphone/Maps/Core/Subscriptions/MWMPurchaseManager.h
iphone/Maps/Core/Subscriptions/MWMPurchaseManager.mm
iphone/Maps/Core/Subscriptions/SubscriptionManager.swift
iphone/Maps/UI/Ads/RemoveAdsViewController.swift
iphone/Maps/UI/Settings/MWMSettingsViewController.mm
iphone/Maps/UI/Subscription/SubscriptionInteractor.swift
iphone/Maps/UI/Subscription/SubscriptionPresenter.swift

https://jira.mail.ru/browse/MAPSME-14209

[iOS] Subscription trial statistics

---

routing/CMakeLists.txt
routing/index_graph_starter.cpp
routing/index_router.cpp
routing/index_router.hpp
routing/leaps_graph.cpp
routing/leaps_graph.hpp
routing/mwm_hierarchy_handler.cpp
routing/mwm_hierarchy_handler.hpp
routing/routing_integration_tests/CMakeLists.txt
routing/routing_integration_tests/cross_country_routing_tests.cpp
routing/routing_tests/index_graph_tools.cpp
routing/segment.hpp
routing/single_vehicle_world_graph.cpp
routing/single_vehicle_world_graph.hpp
routing/world_graph.hpp
routing_common/num_mwm_id.hpp
xcode/routing/routing.xcodeproj/project.pbxproj

Реквест реализует добавление weight-пенальти (не eta) при пересечении границ государств. Это нужно, чтобы реже вести пользователя без острой необходимости через границы. Логика такая:
- При пересечении границ между странами Шенгена или ЕАЭС пенальти не добавляется.
- В других случаях пенальти - это +2 часа на пересечение каждой границы.
- При пересечении границы спорной территории пенальти налагается в любом случае.
| Было  | Стало | Комментарий |
| ------------- | ------------- | ------------- |
| <img width="400" alt="Screenshot 2020-07-15 at 17 13 17" src="https://user-images.githubusercontent.com/54934129/87556758-b242d900-c6bf-11ea-91ae-f1b7b2ea06a8.png"> | <img width="400" alt="Screenshot 2020-07-15 at 17 09 18" src="https://user-images.githubusercontent.com/54934129/87556834-cedf110 …

[routing] Cross-country penalty.

---

generator/generator_tests/osm_type_test.cpp
generator/osm2type.cpp
generator/relation_tags.cpp

Основной фикс во втором коммите (сейчас он работает и без первого).

[generator] Store pure alt/old name only.

---

iphone/Maps/UI/Welcome/WhatsNew/WhatsNewBuilder.swift

Добавлен еще один шаг, для того чтобы корректно отработало автообновление.

[iOS] What's new 10.2 - added second step for autoupdate

---

iphone/Maps/UI/Editor/Cells/MWMEditorCategoryCell.m
iphone/Maps/UI/Editor/Cells/MWMEditorSelectTableViewCell.m
iphone/Maps/UI/Editor/MWMEditorCommon.h

https://jira.mail.ru/browse/MAPSME-14458

[iOS] Fixed crash in editor

---

iphone/Maps/Core/InappPurchase/Impl/PaidRouteStatistics.swift

https://jira.mail.ru/browse/MAPSME-14118

[iOS] Added 'from' to innap show event in paid route statistics

---

map/catalog_headers_provider.cpp
map/download_on_map_ads_delegate.cpp
storage/country_tree.cpp
storage/storage.cpp
storage/storage.hpp
storage/storage_defines.hpp
tools/python/post_generation/inject_promo_ids.py

https://jira.mail.ru/browse/MAPSME-14384

Headers for catalog

---

iphone/Maps/Classes/MapViewController.mm
iphone/Maps/UI/Search/MWMSearchManager.mm
iphone/Maps/UI/Search/SearchBar.swift

https://jira.mail.ru/browse/MAPSME-14448

[iOS] Search on map fixes and improvements

---

editor/editor_tests/xml_feature_test.cpp

https://github.com/mapsme/omim/pull/13486
код поправила, а тест не поправила

[editor] Fix test.

---

tracking/protocol.cpp
tracking/protocol.hpp
tracking/pytracking/bindings.cpp
tracking/tracking_tests/protocol_test.cpp

[tracking] Crash fix in case of Protocol::DecodeHeader({}).

---

tracking/tracking_tests/reporter_test.cpp

[tracking] Warning fix.

---

iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm

https://jira.mail.ru/browse/MAPSME-14486

[iOS] Added currency to booking description

---

iphone/CoreApi/CoreApi/InappPurchase/Impl/MWMTrialEligibility.mm
iphone/Maps/Core/Subscriptions/MWMPurchaseManager.mm

https://jira.mail.ru/browse/MAPSME-14452

[iOS] Fixed trial eligibility check

---

map/booking_availability_filter.cpp
map/booking_utils.cpp
map/booking_utils.hpp
map/framework.cpp
map/search_mark.cpp
map/search_mark.hpp

https://jira.mail.ru/browse/MAPSME-14489
https://jira.mail.ru/browse/MAPSME-14477

Booking search marks fixes

---

data/taxi_places/yandex.json
partners_api/partners_api_tests/taxi_engine_tests.cpp
partners_api/taxi_engine.cpp

https://jira.mail.ru/browse/MAPSME-14304

[taxi] vezet taxi is disabled, list of cities for yandex taxi is updated

---

android/res/layout/fragment_search.xml
android/res/layout/toolbar_filter_controls.xml
android/res/layout/toolbar_with_search.xml
android/res/layout/toolbar_with_search_no_elevation.xml
android/res/values/donottranslate.xml
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/search/BookingFilterParams.java
android/src/com/mapswithme/maps/search/SearchFilterController.java
android/src/com/mapswithme/maps/search/SearchFragment.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java

https://jira.mail.ru/browse/MAPSME-14185
В данном PR имплементация логики выбора дат через новые компоненты, расположенные в верхнем тулбаре на экране поиска и карте. Также использован новый контрол из материал дизайна для выбора дат.

Mapsme 14185 checkin buttons in toolbar

---

iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm

https://jira.mail.ru/browse/MAPSME-14486

[iOS] Check for 'XXX' currency code

---

CMakeLists.txt
cmake/OmimHelpers.cmake
tracking/CMakeLists.txt
tracking/protocol.cpp
tracking/tracking_fuzz_tests/CMakeLists.txt
tracking/tracking_fuzz_tests/tracking_fuzz_tests.cpp

Добавлен первый fuzz тест для pytracking. Это первое использование LibFuzzer в нашем проекте. Я внес все общее для LibFuzzer в cmake/LibFuzzerHelpers.cmake, чтоб при добавлении новых LibFuzzer тестов, не дублировать одинаковый код.

[tracking] Adding fuzz test.

---

iphone/Maps/Bookmarks/MWMCategoryInfoCell.mm

https://jira.mail.ru/browse/MAPSME-13309

[iOS] Show short and long description in guides

---

iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift

https://jira.mail.ru/browse/MAPSME-14512

[iOS] Open subscription screen on empty tier

---

iphone/Maps/Common/WebViewController.m

https://jira.mail.ru/browse/MAPSME-14513

[iOS] Resend headers in webcatalog on reload

---

tracking/tracking_fuzz_tests/tracking_fuzz_tests.cpp

Покрыл fuzz тестами pytracking полностью.

[tracking] Covering with fuzz tests Protocol::CreateDataPacket() and Protocol::CreateDataPacket().Protocol::CreateDataPacket().

---

data/countries.txt
data/external_resources.txt

Результаты тестов:
https://t.bk.ru/annTl/200714-200804.checks.txt
https://t.bk.ru/6tqWr/200714-200804-logs.checks.txt
значимых отклонений не наблюдаю

[planet] New data from 04.08.2020

---

data/taxi_places/yandex.json

https://jira.mail.ru/browse/MAPSME-14519

[taxi] yandex cities are updated

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/search/SearchFilterController.java
android/src/com/mapswithme/maps/search/SearchFragment.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java

https://jira.mail.ru/browse/MAPSME-14293

[android] Fixed passing the chosen dates across map and search screen

---

editor/editor_tests/editor_config_test.cpp
editor/xml_feature.cpp

Исправила ASSERT -- как вариант можно сравнивать при помощи strcmp и будет быстрее, но т.к. это внутри ASSERT то кажется лучше выбирать вариант который лучше читается.
Поправила тест конфига, который сломала при выпиливании редактирования операторов.

[editor] Minor fixes.

---

search/ranker.cpp

Технический реквест, чтобы не смешивать рефакторинг с изменением кода.
Тут только перестановка кода и приведение в соответствие порядка полей и аргументов конструктора.

[search] RankerResultMaker minor refactoring.

---

generator/generator_tests/metadata_parser_test.cpp
generator/osm2meta.cpp
indexer/ftypes_matcher.cpp
indexer/ftypes_matcher.hpp

Список типов для которых планируется сохранять показывала Лёше в реквесте про выпиливание лишних операторов из редактора, он ок.

[generator] Save operator for payment terminal, money exchange, post office, car sharing, car rental, bicycle rental.

---

android/build.gradle
android/src/com/mapswithme/maps/search/FilterUtils.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java
android/src/com/mapswithme/util/Utils.java

https://jira.mail.ru/browse/MAPSME-14293
Восстановил ограничения для выбора дат, которые были до этого (длительность проживания в отеле не более 30 дней, чекин должен быть внутри 365 дней), для новых контроллов выбора дат в верхнем поисковом тулбаре.

Mapsme 14293 date picker constraints

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/bookmarks/BookmarkBackupController.java
android/src/com/mapswithme/maps/search/FilterUtils.java
android/src/com/mapswithme/maps/search/SearchActivity.java
android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java
android/src/com/mapswithme/maps/widget/placepage/ErrorCatalogPromoListener.java
android/src/com/mapswithme/util/Utils.java

https://jira.mail.ru/browse/MAPSME-14293
В первом коммите добавил проверку интернета и если его нет, то будет показан наш привычный диалог. Во втором коммите модифицировал метод открытия настроек так, чтобы он сначала попытался открыть именно сетевые настройки, если по каким-то причинам (их много) не получится то пользователь увидеть главный экран настроек.

Mapsme 14293 datepicker connection check

---

android/res/values-ru/strings.xml
data/categories.txt
data/strings/types_strings.txt
iphone/Maps/LocalizedStrings/ru.lproj/Localizable.strings

[strings][categories] Fix nursing home translation.

---

iphone/Maps/UI/Search/Filters/MWMHotelParams.mm

https://jira.mail.ru/browse/MAPSME-14456

[iOS] fix wrong dates passed to booking api

---

android/build.gradle

copy of https://github.com/mapsme/omim/pull/13468

[cherry-pick][android] Fixed crash in androidx(WorkManager)

---

iphone/Maps/UI/Search/DatePickerViewController.swift
iphone/Maps/UI/Search/GuestsPickerViewController.swift
iphone/Maps/UI/Search/MWMSearchManager.mm

Also adjust guests picker available values
https://jira.mail.ru/browse/MAPSME-14446
https://jira.mail.ru/browse/MAPSME-14453

[iOS] fix state preservation in search hotels params

---

iphone/Maps/UI/Storyboard/Main.storyboard

https://jira.mail.ru/browse/MAPSME-14462

[iOS] Changed Search ViewController width in landscape

---

iphone/Maps/Core/Ads/Mopub/MPNativeAd+MWM.m

https://jira.mail.ru/browse/MAPSME-14420
Удалил проверку на флаг hasAttachedToView, который управляется самим мопабом

[iOS] Removed unnecessary check from ad banner

---

android/jni/com/mapswithme/maps/SearchEngine.cpp
android/src/com/mapswithme/maps/search/BookingFilterParams.java
android/src/com/mapswithme/maps/search/FilterUtils.java

https://jira.mail.ru/browse/MAPSME-14187

[android] Implemented toRooms method

---

iphone/Maps/Core/Location/MWMLocationHelpers.h

https://jira.mail.ru/browse/MAPSME-14534

[iOS] fix bug with distance units on bookmarks screen

---

iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.h
iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm
iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm

https://jira.mail.ru/browse/MAPSME-13295
https://jira.mail.ru/browse/MAPSME-13459

[iOS] Disable isolines on error

---

iphone/Maps/Classes/MapViewController.mm
iphone/Maps/UI/Downloader/DownloadMapsViewController.swift

Also pause map rendering when map screen is not active
https://jira.mail.ru/browse/MAPSME-14563

[iOS] improve performance on map donloader screen

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/base/FinishActivityToolbarController.java
android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
android/src/com/mapswithme/maps/downloader/DownloaderToolbarController.java
android/src/com/mapswithme/maps/editor/AuthFragment.java
android/src/com/mapswithme/maps/editor/EditorHostFragment.java
android/src/com/mapswithme/maps/routing/RoutingPlanController.java
android/src/com/mapswithme/maps/search/SearchFragment.java
android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
android/src/com/mapswithme/maps/widget/InteractiveCounterView.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java
android/src/com/mapswithme/maps/widget/ToolbarController.java
android/src/com/mapswithme/maps/widget/menu/GuestsRoomsMenuRenderer.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-14206
В этом PR заимплементил два эвента для booking improvements:
Search_QuickFilter_Open (aloha & flurry) и Search_QuickFilter_Click (aloha & flurry):

Mapsme 14206 booking improvements stats

---

drape_frontend/user_mark_shapes.cpp
map/search_mark.cpp

https://jira.mail.ru/browse/MAPSME-14628

[drape] [Booking] Correct calculations of text metrics for better badge width adjustment

---

iphone/DatePicker/DatePicker/DatePickerView.swift
iphone/Maps/UI/Search/Filters/MWMHotelParams.mm

https://jira.mail.ru/browse/MAPSME-14456

[iOS] fix time zone issues in date picker

---

iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift

https://jira.mail.ru/browse/MAPSME-14652

[iOS] impement accurate path check in catalog links

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/search/FilterFragment.java
android/src/com/mapswithme/maps/search/FilterUtils.java
android/src/com/mapswithme/maps/search/SearchFragment.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-14206
Добавил трекание:
Search_QuickFilter_Apply
Search_QuickFilter_Click_error
Search_Filter_Open (модификация старого эвента)
Search_Filter_Apply(модификация старого эвента)

[android] Added tracking the quick filters applying

---

android/res/layout-land/onmap_downloader.xml
android/res/layout-land/onmap_downloader_banner.xml
android/res/layout-land/onmap_downloader_banner_big_logo.xml
android/res/layout-land/onmap_downloader_catalog_banner.xml
android/res/layout/onmap_downloader.xml
android/res/layout/onmap_downloader_banner.xml
android/res/layout/onmap_downloader_banner_big_logo.xml
android/res/layout/onmap_downloader_catalog_banner.xml
android/src/com/mapswithme/maps/downloader/DownloaderBannerConfigStrategyPartner.java
android/src/com/mapswithme/maps/downloader/DownloaderBannerType.java
android/src/com/mapswithme/maps/downloader/OnmapDownloader.java

https://jira.mail.ru/browse/MAPSME-14555

[android] Ad button fix

---

map/isolines_manager.cpp

https://jira.mail.ru/browse/MAPSME-14449

[core] Moved statistics traking bebore change state in isolines

---

android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java

https://jira.mail.ru/browse/MAPSME-14629
https://jira.mail.ru/browse/MAPSME-14674

Mapsme 14629 crash in map downloader

---

tools/python/maps_generator/checks/default_check_set.py

Из-за это ошибки в прошлый раз не запустились тесты адресов.

[generator][python] Fixed logic error.

---

map/map_tests/booking_filter_test.cpp

cp for https://github.com/mapsme/omim/pull/13617

cherry-pick [booking] filter tests are fixed

---

iphone/Maps/Core/Location/MWMLocationManager.mm

https://jira.mail.ru/browse/MAPSME-14665

[iOS] Background location update activates in route planning mode

---

data/countries.txt
data/external_resources.txt

https://t.bk.ru/8nJTu/200804-200822.checks.txt
https://t.bk.ru/a4JV1/200804-200822-logs.checks.txt

[planet] New data from 22.08.2020

---

iphone/Maps/UI/Downloader/DownloadMapsViewController.swift

https://jira.mail.ru/browse/MAPSME-14683

[iOS] update "no maps" state when user returns to Donloaded Maps screen

---

android/src/com/mapswithme/maps/downloader/OnmapDownloader.java

https://jira.mail.ru/browse/MAPSME-14703

[android] double banner is fixed

---

data/taxi_places/yandex.json

https://jira.mail.ru/browse/MAPSME-14519

[taxi] another one cities fix

---

partners_api/ads/ads_base.cpp
partners_api/ads/ads_base.hpp
partners_api/partners_api_tests/mastercard_sberbank_tests.cpp
partners_api/partners_api_tests/skyeng_tests.cpp
partners_api/partners_api_tests/tinkoff_airlines_tests.cpp
partners_api/partners_api_tests/tinkoff_insurance_tests.cpp

https://jira.mail.ru/browse/MAPSME-14556

[ads] banner absence is fixed when user position is not found

---

generator/generator_tests/metadata_parser_test.cpp

cherry pick https://github.com/mapsme/omim/pull/13632

[generator tests] Fix misprint.

---

data/countries-strings/ar.json/localize.json
data/countries-strings/cs.json/localize.json
data/countries-strings/da.json/localize.json
data/countries-strings/de.json/localize.json
data/countries-strings/el.json/localize.json
data/countries-strings/en.json/localize.json
data/countries-strings/es.json/localize.json
data/countries-strings/fi.json/localize.json
data/countries-strings/fr.json/localize.json
data/countries-strings/he.json/localize.json
data/countries-strings/hu.json/localize.json
data/countries-strings/id.json/localize.json
data/countries-strings/it.json/localize.json
data/countries-strings/ja.json/localize.json
data/countries-strings/ko.json/localize.json
data/countries-strings/nb.json/localize.json
data/countries-strings/nl.json/localize.json
data/countries-strings/pl.json/localize.json
data/countries-strings/pt.json/localize.json
data/countries-strings/ro.json/localize.json
data/countries-strings/ru.json/localize.json
data/countries-strings/sk.json/localize.json
data/countries-strings/sv.json/localize.json
data/countries-strings/th.json/localize.json
data/countries-strings/tr.json/localize.json
data/countries-strings/uk.json/localize.json
data/countries-strings/vi.json/localize.json
data/countries-strings/zh-Hans.json/localize.json
data/countries-strings/zh-Hant.json/localize.json
data/countries_names.txt

черри-пик https://github.com/mapsme/omim/pull/13637 на релиз

[strings] Remove duplicates for Bolivia_North, Bolivia_South

---

editor/editor_tests/config_loader_test.cpp

cp for https://github.com/mapsme/omim/pull/13630

cherry-pick [editor] remote config loader tests are disabled

---

drape/vulkan/vulkan_base_context.cpp

cherry-pick [drape] [Vulkan] Make rendering and presentation conditions the same

---

indexer/altitude_loader.cpp
indexer/feature.cpp
indexer/feature_meta.hpp

Format::v7 это не single mwm, мы его больше не поддерживаем.

[indexer] Remove unused code.

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/search/BookingFilterParams.java
android/src/com/mapswithme/maps/search/FilterActivity.java
android/src/com/mapswithme/maps/search/FilterUtils.java
android/src/com/mapswithme/maps/search/SearchActivity.java
android/src/com/mapswithme/maps/search/SearchFragment.java

https://jira.mail.ru/browse/MAPSME-14718

Mapsme 14718 fix search filter from discovery

---

iphone/Maps/Bookmarks/BookmarksCoordinator.swift
iphone/Maps/Classes/MapViewController.mm

https://jira.mail.ru/browse/MAPSME-14669

[iOS] Hide bookmarks back button in navigation

---

iphone/Maps/Bookmarks/BookmarksTabViewController.swift
iphone/Maps/Classes/MapViewController.mm

https://jira.mail.ru/browse/MAPSME-14712

[iOS] Fixed crash in BookmarksCoordinator

---

iphone/Maps/UI/PlacePage/PlacePageViewController.swift

https://jira.mail.ru/browse/MAPSME-14708

[iOS] Fixed parents of viewcontrollers in PP

---

iphone/Maps/UI/Downloader/AvailableMapsDataSource.swift
iphone/Maps/UI/Downloader/DownloadMapsViewController.swift
iphone/Maps/UI/Downloader/DownloadedMapsDataSource.swift

https://jira.mail.ru/browse/MAPSME-14707
https://jira.mail.ru/browse/MAPSME-14693
https://jira.mail.ru/browse/MAPSME-14694

[iOS] fix bugs on Download Maps screen

---

generator/generator_integration_tests/features_tests.cpp

черри-пик https://github.com/mapsme/omim/pull/13619 на мастер

[tests] Fixed after pr 13557.

---

iphone/Maps/Classes/Components/TabView/TabView.swift

https://jira.mail.ru/browse/MAPSME-14291

[iOS] fix layout issue in TabView, remove obsolete code

---

iphone/Maps/Bookmarks/BookmarksVC.mm

https://jira.mail.ru/browse/MAPSME-14681

[iOS] refresh bookmarks list on viewWillAppear

---

iphone/Maps/Bookmarks/Categories/Category settings/CategorySettingsViewController.swift
iphone/Maps/UI/EditBookmark/EditBookmarkViewController.swift
iphone/Maps/UI/Editor/Cells/MWMButtonCell.h
iphone/Maps/UI/Editor/Cells/MWMButtonCell.m
iphone/Maps/UI/Editor/Cells/MWMButtonCell.xib
iphone/Maps/UI/Editor/MWMEditorViewController.mm

https://jira.mail.ru/browse/MAPSME-14728

[iOS] disable delete button on list settings screen for last bookmarks group

---

iphone/Maps/Bookmarks/Categories/Sharing/GuideNameViewController.swift

https://jira.mail.ru/browse/MAPSME-14729

[iOS] localize "Next" button on guide sharing screen

---

iphone/Maps/UI/Search/Filters/MWMHotelParams.mm
iphone/Maps/UI/Search/MWMSearchManager.mm

https://jira.mail.ru/browse/MAPSME-14713

[iOS] don't set guests in hotel fiter by default

---

iphone/Maps/Core/Ads/Mopub/MopubBanner.swift
iphone/Maps/Core/Location/MWMLocationManager+SpeedAndAltitude.swift
iphone/Maps/Core/Location/MWMLocationManager.h
iphone/Maps/Core/Theme/Core/ThemeManager.swift
iphone/Maps/UI/BottomMenu/Menu/BottomMenuInteractor.swift
iphone/Maps/UI/Downloader/DownloadMapsViewController.swift
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift
iphone/Maps/UI/Welcome/FirstLaunch/FirstLaunchPresenter.swift
iphone/Maps/UI/Welcome/WelcomePageController.swift

https://jira.mail.ru/browse/MAPSME-14726

[iOS] don't show taxi component in pp when offline or no location

---

drape_frontend/rule_drawer.cpp
drape_frontend/rule_drawer.hpp
indexer/ftypes_matcher.cpp
indexer/ftypes_matcher.hpp

Partial rollback of pr #13159 https://jira.mail.ru/browse/MAPSME-13687.

[guides on map] Do not filter POI when guides layer is enabled

---

iphone/Maps/UI/PlacePage/Components/PlacePagePreviewViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard

Пришлось отказаться от стиля для лэйбла потому что если установить цвет текста после установки attributedText, все цвета из attributedText пропадают

[iOS] fix popular label color in PP

---

drape/batcher_helpers.cpp
drape/cpu_buffer.cpp
drape/vertex_array_buffer.cpp
drape_frontend/area_shape.cpp

https://jira.mail.ru/browse/MAPSME-12898

[drape] [iOS] Changes to catch a source of crash at dp::CPUBuffer::UploadData 

---

map/framework.cpp
map/search_mark.cpp
map/search_mark.hpp

https://jira.mail.ru/browse/MAPSME-14691

[drape] [Booking] Add SearchMarkType::Hotel for SearchMarkType to distinct OSM hotels in search results

---

map/framework.cpp

https://jira.mail.ru/browse/MAPSME-14721
Помимо бага, в ShowViewportSearchResults срабатывал ассерт на то, что m_activeFilters должны быть не пустыми.

[map] search mark selection is fixed

---

iphone/Maps/UI/EditBookmark/legacy_bookmark_colors.h

https://jira.mail.ru/browse/MAPSME-12897

[bookmarks] Fix crash caused by 'None' predefined bookmark color value

---

iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift

https://jira.mail.ru/browse/MAPSME-14756

[iOS] Added reload in catalog web view after single purchase

---

iphone/Maps/UI/Subscription/SubscriptionRouter.swift

https://jira.mail.ru/browse/MAPSME-14692

[iOS] Fixed success dialog in subscriptions

---

android/res/layout/toolbar_with_search.xml
android/src/com/mapswithme/maps/downloader/DownloaderToolbarController.java
android/src/com/mapswithme/maps/editor/EditorHostFragment.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java
android/src/com/mapswithme/maps/widget/ToolbarController.java
android/src/com/mapswithme/util/UiUtils.java

https://jira.mail.ru/browse/MAPSME-14715

Mapsme 14715 fix toolbar in map downloader

---

android/res/drawable/ic_logo_yango.xml
android/src/com/mapswithme/maps/taxi/TaxiType.java
data/taxi_places/yango.json
iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.h
iphone/CoreApi/CoreApi/PlacePageData/PlacePageData.mm
iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMRoutePreviewTaxiCellType.h
iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMTaxiPreviewDataSource.mm
iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RoutePreviewTaxiCell.swift
iphone/Maps/Common/Statistics/StatisticsStrings.h
iphone/Maps/Core/Routing/MWMRouter.mm
iphone/Maps/Images.xcassets/ic_taxi_logo_yango.imageset/Contents.json
iphone/Maps/Images.xcassets/ic_taxi_logo_yango.imageset/ic_taxi_logo_yango.pdf
iphone/Maps/UI/PlacePage/Components/TaxiViewController.swift
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm
partners_api/CMakeLists.txt
partners_api/taxi_engine.cpp
partners_api/taxi_places_loader.cpp
partners_api/taxi_provider.hpp
partners_api/yandex_api.cpp
partners_api/yango_api.cpp
partners_api/yango_api.hpp
tools/python/jsons.py
xcode/partners_api/partners_api.xcodeproj/project.pbxproj

https://jira.mail.ru/browse/MAPSME-14251

Yango taxi

---

iphone/Maps/Core/Search/MWMSearch.mm

https://jira.mail.ru/browse/MAPSME-14720

[RELEASE_ONLY][iOS] Do not clear previous results in search on map

---

map/search_mark.cpp

https://jira.mail.ru/browse/MAPSME-14778

[drape] [Booking] Use star icon for advertised non-Booking hotels

---

.gitignore
pyhelpers/setup.py

- Возможность собирать не только версию, соответствующую версии omim, но и более точную, определяемую коммитом (или чем угодно, что поставим в окружение)
- Использование пакетов omim-data-basic как зависимостей, вместо собственных data_files

Python modules customizable version and dependencies

---

android/gradle.properties
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/discovery/DiscoveryActivity.java
android/src/com/mapswithme/maps/search/FilterUtils.java
android/src/com/mapswithme/maps/tips/ClickInterceptorFactory.java

https://jira.mail.ru/browse/MAPSME-14788

Mapsme 14788 filter panel showing fix

---

drape_frontend/visual_params.cpp

Revert eb7c804883
https://jira.mail.ru/browse/MAPSME-14796

[drape] Fix infinite zoom in MAPSME-14796

---

iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift

https://jira.mail.ru/browse/MAPSME-14762

[iOS] Added bookmarks error statistics event

---

iphone/Maps/Bookmarks/Categories/Sharing/GuideDescriptionViewController.swift

https://jira.mail.ru/browse/MAPSME-14729

[iOS] localize "Next" button title on bookmarks sharing screen

---

iphone/Maps/UI/Search/Filters/MWMSearchHotelsFilterViewController.mm

https://jira.mail.ru/browse/MAPSME-14814

[iOS] keep previous filter on hotels filter screen

---

iphone/Maps/UI/Subscription/City/CitySubscriptionViewController.swift

https://jira.mail.ru/browse/MAPSME-14816

[iOS] fix city subscription screen presentation on iPad

---

data/copyright.html

[expat] Copyright update.

---

generator/final_processor_country.cpp
generator/final_processor_country.hpp
generator/raw_generator.cpp

[dnm][generator] Added booking-matching.log.

---

drape/overlay_handle.cpp
drape/overlay_handle.hpp
drape/overlay_tree.cpp
drape_frontend/apply_feature_functors.cpp
drape_frontend/circles_pack_shape.cpp
drape_frontend/colored_symbol_shape.cpp
drape_frontend/drape_engine.cpp
drape_frontend/frontend_renderer.cpp
drape_frontend/frontend_renderer.hpp
drape_frontend/gui/shape.cpp
drape_frontend/path_text_shape.cpp
drape_frontend/poi_symbol_shape.cpp
drape_frontend/poi_symbol_shape.hpp
drape_frontend/render_group.hpp
drape_frontend/shape_view_params.hpp
drape_frontend/text_handle.cpp
drape_frontend/text_shape.cpp
drape_frontend/transit_scheme_builder.cpp
drape_frontend/user_mark_shapes.cpp
drape_frontend/user_mark_shapes.hpp
drape_frontend/user_marks_provider.hpp
map/bookmark_manager.hpp
map/framework.cpp
map/framework.hpp
map/place_page_info.cpp
map/place_page_info.hpp
map/search_mark.cpp
map/search_mark.hpp
map/user_mark.hpp

Тап по тексту подписи POI или бэйджу с ценой, рейтингом и скидкой приводит к выделению отеля.
https://jira.mail.ru/browse/MAPSME-14544

[drape] [Booking] Make badge selectable

---

drape_frontend/user_mark_shapes.cpp

https://jira.mail.ru/browse/MAPSME-12900

[drape] [tracks] Allow to render tracks for 20 zoomLevel MAPSME-12900

---

android/gradle.properties
android/jni/com/mapswithme/maps/SearchEngine.cpp
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/search/NativeSearchListener.java
android/src/com/mapswithme/maps/search/SearchEngine.java
android/src/com/mapswithme/maps/search/SearchFragment.java

https://jira.mail.ru/browse/MAPSME-14817

Mapsme 14817 fix filter displaying

---

iphone/Maps/UI/PlacePage/Views/ExpandableLabel.swift

https://jira.mail.ru/browse/MAPSME-14866

[iOS] Added data detection to bookmarks description

---

android/res/layout/fragment_bookmark_list.xml

Update fragment_bookmark_list.xml

MAPSME-14856-bug-fix

---

android/jni/com/mapswithme/maps/guides/Guides.cpp
android/jni/com/mapswithme/maps/guides/Guides.hpp
android/multidex-config.txt
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
android/src/com/mapswithme/util/SharedPropertiesUtils.java
map/framework.cpp
map/framework.hpp
map/guides_manager.cpp
map/guides_manager.hpp
map/layers_statistics.cpp
map/layers_statistics.hpp
platform/CMakeLists.txt
platform/utils.cpp
platform/utils.hpp
platform/utils.mm
xcode/platform/platform.xcodeproj/project.pbxproj

https://jira.mail.ru/browse/MAPSME-14865

[guides on map] layer is enabled automatically on startup once.

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/intent/Factory.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-14907
Кейс не воспроизводится после исправлений.
Дополнительно файлы отформатировались по кодстайлу.

[android] MAPSME-14907 Crush-fix. Added bundle "from" notification.

---

iphone/Maps/UI/Search/DatePickerViewController.swift
iphone/Maps/UI/Search/DatePickerViewController.xib
iphone/Maps/UI/Search/GuestsPickerViewController.swift
iphone/Maps/UI/Search/GuestsPickerViewController.xib

https://jira.mail.ru/browse/MAPSME-14840

[iOS] Fixed date picker and guest picker in horizontal orientation

---

xcode/transit/transit.xcodeproj/project.pbxproj

[ios] build fix

---

map/booking_availability_filter.cpp
map/catalog_headers_provider.cpp
map/discovery/discovery_search.cpp
search/ranking_info.cpp

Кроме копирования в цикле заменил тип константного массива с `vector<string>`  на `array<string, 3>`,
думаю нет смысла аллоцировать в куче для такого маленького массива.

[map] [search] removing extra copy in loop

---

android/jni/CMakeLists.txt
android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
drape_frontend/transit_scheme_builder.cpp
map/bookmark_manager.cpp

+ build fix @mesozoic-drones  fyi

[android][bookmarks] methods for retrieving children collections and categories are provided

---

routing/route.cpp
routing/route.hpp
routing/routing_callbacks.hpp
routing/routing_session.cpp
routing/routing_session.hpp
routing/routing_tests/routing_session_test.cpp
routing/routing_tests/tools.hpp

Добавил возможность задавать колбек на смену маневра в режиме навигации. И тесты на этот колбек.
Этот колбек нужен, чтоб поправил баг (Обозначения маневров мерцают и быстро сменяются на CarPlay на 10.2.1): https://jira.mail.ru/browse/MAPSME-14919 
@mesozoic-drones @beloal PTAL

[routing] Adding callback on turn changed.

---

data/countries.txt
data/external_resources.txt

https://t.bk.ru/7N8FK/200822-200920-logs.checks.txt
https://t.bk.ru/11pokd/200822-200920.checks.txt

[planet] New data from 20.09.2020

---

iphone/Maps/Classes/CarPlay/CarPlayRouter.swift
iphone/Maps/Classes/CarPlay/CarPlayService.swift
iphone/Maps/Core/Framework/ProxyObjects/Routing/MWMRoutingManager.h
iphone/Maps/Core/Framework/ProxyObjects/Routing/MWMRoutingManager.mm
iphone/Maps/Images.xcassets/CarPlay/Maneuvers/Symbols/ic_cp_uturn_right_then.imageset/Contents.json

https://jira.mail.ru/browse/MAPSME-14919

[iOS] fix flashing maneuvers on carplay

---

search/pre_ranker.cpp
search/pre_ranker.hpp
search/search_integration_tests/pre_ranker_test.cpp

Черри-пики на релиз коммитов из 
https://github.com/mapsme/omim/pull/13756

[search] Make search results more stable. 

---

iphone/Maps/UI/Subscription/AllPass/AllPassSubscriptionViewController.swift

https://jira.mail.ru/browse/MAPSME-14934

[iOS] Fixed crash when open AllPass Subscription from richmedia

---

iphone/Maps/Core/Theme/Extensions/UIView+styleName.swift
iphone/Maps/Core/Theme/Renderers/UISearchBarRenderer.swift
iphone/Maps/Core/Theme/Renderers/UITextFieldRenderer.swift

https://jira.mail.ru/browse/MAPSME-13460

[iOS] Fixed styles on deeplinks from richmedia

---

coding/serdes_json.hpp
iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm
map/bookmark_catalog.cpp

https://jira.mail.ru/browse/MAPSME-14990
https://jira.mail.ru/browse/MAPSME-14976
и реверт этого
https://jira.mail.ru/browse/MAPSME-14964

Release 102 fixes

---

kml/kml_tests/serdes_tests.cpp
kml/pykmlib/bindings.cpp
kml/pykmlib/bindings_test.py
kml/serdes.cpp
kml/serdes_binary.hpp
kml/types.hpp

https://jira.mail.ru/browse/MAPSME-14912

[pykmlib] compilations are added

---

iphone/Maps/UI/CarPlay/CarPlayMapViewController.swift

https://jira.mail.ru/browse/MAPSME-14643

[iOS] Fixed mapview in carplay

---

transit/world_feed/color_picker.cpp
transit/world_feed/color_picker.hpp

Формула для вычисления близости двух цветов заменена с обычного евклидова расстояния на Colour metric.
https://www.compuphase.com/cmetric.htm

[transit] cmetric for measuring of colors distance.

---

map/tips_api.cpp

@alexzatsepin fyi
https://jira.mail.ru/browse/MAPSME-15008

[RELEASE ONLY][android] Tips for layers are disabled.

---

map/bookmark_manager.cpp

@beloal @Polas @velichkomarija @alexzatsepin fyi

[bookmarks] additional mock's

---

map/bookmark.cpp
map/bookmark.hpp
map/framework.cpp
map/place_page_info.cpp
map/place_page_info.hpp

https://jira.mail.ru/browse/MAPSME-14914

[bookmarks] [lonely planet] Pass metadata from bookmark props to show on place page

---

android/src/com/mapswithme/maps/bookmarks/BookmarkCollectionAdapter.java
android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
android/src/com/mapswithme/maps/bookmarks/Holders.java
android/src/com/mapswithme/maps/bookmarks/data/AbstractCategoriesSnapshot.java
android/src/com/mapswithme/maps/bookmarks/data/CategoryDataSource.java

https://jira.mail.ru/browse/MAPSME-14902

[android] MAPSME-14902 Added click listener on collection items.

---

android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java

https://jira.mail.ru/browse/MAPSME-14902

[android] MAPSME-14857 Hided description layout in users bookmarks.

---

tools/python/data/all/setup.py
tools/python/data/base.py
tools/python/data/borders/__init__.py
tools/python/data/borders/setup.py
tools/python/data/essential/setup.py
tools/python/data/fonts/setup.py
tools/python/data/styles/setup.py
tools/python/data_files/__init__.py
tools/python/data_files/setup.py
tools/python/maps_generator/generator/settings.py
tools/python/maps_generator/requirements.txt
tools/python/mwm/__init__.py
tools/python/mwm/requirements.txt

Опечатался и удалил ветку :(
Поправил замечания по https://github.com/mapsme/omim/pull/13771

[python][packaging] Borders package contains borders.tar.xz archive.

---

iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
iphone/Maps/Bookmarks/Categories/Sharing/EditOnWebViewController.swift
iphone/Maps/Categories/UIViewController+Authorization.swift
iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.h
iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm
iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.h
iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm
iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.h
iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm
iphone/Maps/UI/Settings/MWMSettingsViewController.mm
iphone/Maps/UI/Subscription/SubscriptionInteractor.swift

https://jira.mail.ru/browse/MAPSME-15033

[iOS] Added error message on failed authorization

---

iphone/Maps/UI/Search/MWMSearchManager.mm

https://jira.mail.ru/browse/MAPSME-14994

[iOS] fix dates in date picker stats

---

kml/types.hpp
map/bookmark.cpp
map/bookmark.hpp
map/bookmark_helpers.cpp
map/bookmark_manager.cpp
map/bookmark_manager.hpp
map/user_mark_id_storage.cpp

https://jira.mail.ru/browse/MAPSME-14913

[bookmarks] compilations are supported into bookmark manager

---

android/AndroidManifest.xml
android/res/layout/fragment_bookmark_list.xml
android/res/layout/fragment_bookmarks_description.xml
android/res/layout/item_guide_info.xml
android/src/com/mapswithme/maps/bookmarks/BookmarkHeaderView.java
android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
android/src/com/mapswithme/maps/bookmarks/description/BookmarksDescriptionActivity.java
android/src/com/mapswithme/maps/bookmarks/description/BookmarksDescriptionFragment.java

- Вынес общий заголовок в отдельную view
- Создал фрагмент и активность для экрана описания
https://jira.mail.ru/browse/MAPSME-14900
требования:
https://confluence.mail.ru/display/MAPSME/Guides+list+usability+improvements
https://www.figma.com/file/oVkjD6pja8fXLA6ihXrDY8/Android-design?node-id=0%3A3395

[android] new bookmarks description screen is added

---

iphone/Maps/Classes/CarPlay/CarPlayService.swift
iphone/Maps/Classes/MapsAppDelegate.mm
iphone/Maps/Core/Theme/Core/ThemeManager.swift
iphone/Maps/MAPSME.plist

Фикс автопереключения темы на CarPlay
Так же потенциальный фикс https://jira.mail.ru/browse/MAPSME-14988

[iOS] CarPlay fixes

---

android/build.gradle

https://jira.mail.ru/browse/MAPSME-14920
В исходниках библиотеки добавили локализацию в новой версии.
Подняла версию используемой библиотеки материальных компонентов до новейшей 1.3.0.

[adnroid] Fixed an issue with date picker localization.

---

android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
map/bookmark_manager.cpp
map/bookmark_manager.hpp

[bookmarks] helper methods for compilations

---

android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
map/bookmark.cpp
map/bookmark.hpp
map/bookmark_manager.cpp
map/bookmark_manager.hpp

https://jira.mail.ru/browse/MAPSME-14915

[bookmarks] Track visibility of bookmarks, that belong to any number of compilations

---

routing/base/astar_algorithm.hpp
routing/index_router.cpp
routing/index_router.hpp

Нашел 2 места, где забыли спецификатор const.

[routing] Const correctness.

---

coding/file_reader.cpp

make_shared() instead of new.

---

drape/batcher.cpp
drape/batcher_helpers.cpp

В продолжение #13609.
https://jira.mail.ru/browse/MAPSME-12898

[drape] [iOS] Changes to catch a source of crash at CHECK(IsEnoughMemory) in LineRawBatch::BatchData

---

iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.h
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.mm
iphone/Maps/Classes/CustomViews/MapViewControls/GuidesNavigationBar/GuidesNavigationBarViewController.swift
iphone/Maps/Maps.xcodeproj/project.pbxproj
iphone/Maps/UI/PlacePage/Components/PlacePageDividerViewController.swift
iphone/Maps/UI/PlacePage/Components/PlacePagePreviewViewController.swift
iphone/Maps/UI/PlacePage/PlacePage.storyboard
iphone/Maps/UI/PlacePage/PlacePageLayout/Layouts/PlacePageCommonLayout.swift

https://jira.mail.ru/browse/MAPSME-14894

[iOS] Added logo and dividers in PP

---

android/res/values/arrays.xml
android/src/com/mapswithme/maps/bookmarks/data/BookmarkCategory.java

https://jira.mail.ru/browse/MAPSME-15082

[android] Fix string in whats new.

---

android/src/com/mapswithme/maps/bookmarks/BookmarkCollectionAdapter.java
android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
android/src/com/mapswithme/maps/bookmarks/Holders.java
android/src/com/mapswithme/maps/bookmarks/data/BookmarkCategory.java

https://jira.mail.ru/browse/MAPSME-14902
https://jira.mail.ru/browse/MAPSME-14857
Проверить можно на гиде loonely planet.

[android] Click listeners for items witch must be hidden from the map

---

android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
map/bookmark_manager.cpp
map/bookmark_manager.hpp

https://jira.mail.ru/browse/MAPSME-15104

[android] [bookmarks] Add predicates to check compilations visibility

---

data/taxi_places/yango.json

https://jira.mail.ru/browse/MAPSME-14251

[taxi] yango cities fix

---

android/src/com/mapswithme/maps/bookmarks/BookmarkCollectionAdapter.java
android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
android/src/com/mapswithme/maps/bookmarks/Holders.java
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-14903

[android] Added some statistic function.

---

cmake/BundledBoost.cmake
pyhelpers/setup.py

We don't need to find them since we don't link to them anymore (since #13695)

[pybindings] do not search for python libraries

---

map/guides_manager.cpp

cherry-pick for https://github.com/mapsme/omim/pull/13852

[guides on map] zoom-out from incorrect place is fixed.

---

iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMiPhoneRoutePreview.m
iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMiPhoneRoutePreview.xib

В 14 iOS высота статус бара изменилась, этот фикс убирает хардкод.

[iOS] Changed top anchor in p2p navbar

---

android/src/com/mapswithme/maps/bookmarks/BookmarkCollectionAdapter.java

https://jira.mail.ru/browse/MAPSME-14897
Убрала метод проверки видимости компиляций на карте из платформы, теперь используется проверка из ядра.

[android] Using the method of checking visibility on the map from the core.

---

android/res/layout/fragment_bookmark_list.xml
android/src/com/mapswithme/maps/bookmarks/BookmarkCollectionAdapter.java
android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java

https://jira.mail.ru/browse/MAPSME-14897
Убрана анимация дивайдера при нажатии на чекбокс.
Предложено решение смены состояния кнопки скрыть/показать по нажатию на чекбокс спискаю

[android] Fixed collection recycler animation.

---

android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
android/src/com/mapswithme/util/HttpClient.java

https://jira.mail.ru/browse/MAPSME-14398

[android] night theme is added for guides catalog

---

android/jni/com/mapswithme/maps/UserMarkHelper.cpp
android/res/layout/place_page_description_header.xml
android/res/layout/place_page_details.xml
android/res/layout/place_page_preview.xml
android/res/values/dimens.xml
android/src/com/mapswithme/maps/bookmarks/BookmarkHeaderView.java
android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java
android/src/com/mapswithme/maps/bookmarks/data/MapObject.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

https://jira.mail.ru/browse/MAPSME-14904
Добавил флаг isTopChoice в объект MapObject
Согласно флагу меняется цвет первого лейбла в блоке МастСи
сделал небольшие доработки UI согласно макетам
основные изменения в файлах place_page_description_layout.xml и PlacePageView.java
протестировал пока только на фейковых данных

[android] place description logo is added + related ui changes

---

map/bookmark_manager.cpp

https://jira.mail.ru/browse/MAPSME-15129

[bookmarks] Bookmarks that belongs to compilations attached to compilation id instead of category id

---

indexer/data_source.cpp
indexer/indexer_tests/test_mwm_set.hpp
indexer/rank_table.cpp

Using make_unique instead of new for indexer.

---

android/src/com/mapswithme/maps/widget/InteractiveCounterView.java

https://jira.mail.ru/browse/MAPSME-15128
Проблема была в том, что после вызова setCurrentValue() не обновлялись кнопки плюса и минуса, и можно было проскочить условие когда value != mMinValue.

[android] update counter view after value setting

---

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

https://jira.mail.ru/browse/MAPSME-15018

[android] hotel rating string for PP

---

android/res/values-es/strings.xml
android/res/values-pt/strings.xml
data/strings/strings.txt
iphone/Maps/LocalizedStrings/es.lproj/Localizable.strings
iphone/Maps/LocalizedStrings/pt.lproj/Localizable.strings

Исправил локализацию к задаче https://jira.mail.ru/browse/MAPSME-15038
по ошибке она уехала в pt вместо es

[strings] Changed strings

---

map/bookmark_manager.cpp

Букмарки с пустым списком compilationIds должны наследовать логическую видимость от родительской категории.
https://jira.mail.ru/browse/MAPSME-15129

[bookmarks] Make bookmarks that don't belong to any collection visible

---

android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java

часть https://jira.mail.ru/browse/MAPSME-15142

[jni] GetCategoryData method is provided into java

---

android/src/com/mapswithme/maps/ugc/Impress.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

https://jira.mail.ru/browse/MAPSME-15018
предыдущий ПР неполностью исправлял проблему, тут дополнение в виде текстового представления оценки

[android] hotel textual impression for PP

---

android/src/com/mapswithme/maps/bookmarks/BookmarkHeaderView.java

https://jira.mail.ru/browse/MAPSME-15147
Было неверно задано условие использования.

[android] Fixed description button visibility.

---

partners_api/citymobil_api.cpp

https://jira.mail.ru/browse/MAPSME-15138

[taxi] citymobil credentials are changed.

---

routing/routing_integration_tests/bicycle_turn_test.cpp
routing/routing_integration_tests/pedestrian_route_test.cpp

Интеграционные тесты из примеров в дескрипшене #13821 + 2 дополнительных на пешиков.

[routing] New integration tests for turns.

---

android/src/com/mapswithme/maps/widget/menu/BottomSheetMenuController.java

https://jira.mail.ru/browse/MAPSME-14952
Поискал в сети, некоторые люди с подобной проблемой тоже столкнулись для 10 андроида, эта штука фиксит такое поведение. Выглядит как workaround, но расковыривать лэйаут или писать кастомный бехейвиор будет сложнее и скорее всего приведет к регрессии, на мой взгляд

[android] set hidden state for bottom sheet behavior on initialization

---

data/categories.txt

https://github.com/mapsme/omim/pull/13832#discussion_r511954799

[search][categories] Add '飲食店' Japanese synonym for 'where to eat' category.

---

data/categories_cuisines.txt

https://github.com/mapsme/omim/pull/13832#discussion_r512002445
https://github.com/mapsme/omim/pull/13832#discussion_r512011320
https://github.com/mapsme/omim/pull/13832#discussion_r512011754

[search][categories_cuisines] Fix Japanese synonyms for cuisines.

---

android/res/layout-land/news_page.xml

Отцентрован текст.
https://jira.mail.ru/browse/MAPSME-15141

[android] Update news_page.xml

---

map/search_mark.cpp

https://jira.mail.ru/browse/MAPSME-14844

[searchmarks] Do not mark as visited searchmarks that tapped twice

---

android/src/com/mapswithme/maps/taxi/TaxiType.java

https://jira.mail.ru/browse/MAPSME-15065

[android][taxi] citymobil currency fix

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/search/FloatingSearchToolbarController.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java

https://jira.mail.ru/browse/MAPSME-15120
Теперь ПП скрывается, если открыть фильтры. Заметил такое поведение: если менять фильтры прямо на карте, прогресс бар не показывается. Не уверен, так надо или нет, поэтому пока трогать не стал

[android] MAPSME-15120: hide PP in case of opening filters

---

generator/generator_tool/generator_tool.cpp
map/transit/transit_display.cpp
map/transit/transit_reader.cpp
transit/world_feed/world_feed.cpp

Фиксы для корректного отображения маршрута транзита:

[transit][map] Fixes for transit route rendering.

---

android/res/layout/pager_fragment_bookmarks_all_subscription.xml

https://jira.mail.ru/browse/MAPSME-15085

[android] Fixed new subscription header string

---

android/src/com/mapswithme/maps/maplayer/traffic/widget/TrafficButtonController.java
android/src/com/mapswithme/maps/settings/HelpFragment.java

https://jira.mail.ru/browse/MAPSME-15182
Использовалась старая библиотека AlertDialog. 
Изменила в 2-х местах, где использовалась.

[android] Fix alert dialogs night mode.

---

android/res/layout/fragment_auth_passport_dialog.xml

https://jira.mail.ru/browse/MAPSME-15173

[android] Fixed night theme in social auth fragment.

---

android/src/com/mapswithme/maps/ugc/routes/UgcRouteEditSettingsFragment.java

https://jira.mail.ru/browse/MAPSME-15196

 [android] Added limit for name of category in edit mode.

---

android/jni/com/mapswithme/maps/Framework.cpp
android/jni/com/mapswithme/maps/SearchEngine.cpp
android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
android/jni/com/mapswithme/util/StringUtils.cpp
android/src/com/mapswithme/maps/routing/NavigationController.java
android/src/com/mapswithme/util/StringUtils.java
iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardEntity.mm
iphone/Maps/Core/Framework/ProxyObjects/Routing/MWMRoutingManager.mm
iphone/Maps/Core/Location/MWMLocationHelpers.h
iphone/Maps/Core/Routing/MWMRouter.mm
iphone/Maps/UI/Discovery/View Models/MWMDiscoveryControllerViewModel.mm
iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
map/framework.cpp
map/routing_manager.cpp
platform/CMakeLists.txt
platform/localization.cpp
platform/localization.hpp
platform/measurement_utils.cpp
platform/measurement_utils.hpp
platform/platform_tests/measurement_tests.cpp
routing/routing_session.cpp
xcode/platform/platform.xcodeproj/project.pbxproj

https://jira.mail.ru/browse/MAPSME-14203
Хотел сделать мелкую задачу с локализацией, там оказалась куча проблем накрученных вместе. Все проблемы решить не удалось, но, кажется, получилось сделать лучше.
В ios заменил все методы форматирования расстояния, высоты и скорости на локализованные.
В андроид, из-за затрат на вызов jni, не рискнул заменять, думаю там нужно отдельно получать единицы измерения, их где-то сохраниять, а при надобности проставлять в методы форматирования без доп jni вызова. методы для таких действий предоставил.

Measurement utils localization

---

android/jni/com/mapswithme/maps/UserMarkHelper.cpp
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.h
iphone/CoreApi/CoreApi/PlacePageData/Common/PlacePagePreviewData.mm
iphone/Maps/UI/PlacePage/Components/PlacePagePreviewViewController.swift
map/place_page_info.cpp
map/place_page_info.hpp

Виктор обратил внимание на эту ошибку. Главная проблема - это "is_top_choise" property name.

Obsolete "choise" renamed to "choice".

---

iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkData.h
iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkData.m
iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkSearchData.h
iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkSearchData.mm
iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkSubscriptionData.h
iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkSubscriptionData.mm
iphone/CoreApi/CoreApi/DeepLink/DeepLinkParser.mm
iphone/Maps/Core/DeepLink/DeepLinkStrategyFactory.swift
iphone/Maps/Core/DeepLink/Strategies/DeepLinkIncorrectStrategy.swift

https://jira.mail.ru/browse/MAPSME-13291

[iOS] Added correct handler to deeplink missed stat

---

iphone/Maps/UI/Settings/MWMSettingsViewController.mm

https://jira.mail.ru/browse/MAPSME-15038

[iOS] fixed localization key in settings

---

.gitignore

К PR про добавление GoogleService-Info.plist

[iOS] Updated gitignore

---

.gitignore

cherry_pick для https://github.com/mapsme/omim/pull/13892

[iOS] Updated gitignore - cherry-pick from releasle-103

---

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.h
iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager+Entity.mm
iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationInfoView.mm
iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/NavigationControlView.swift
iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/NavigationControlView.xib
iphone/Maps/Core/Routing/MWMRouter.mm

https://jira.mail.ru/browse/MAPSME-15067

[iOS] Added directions to pedestrian navigation

---

iphone/CoreApi/CoreApi/Search/MWMSearchFrameworkHelper.h
iphone/CoreApi/CoreApi/Search/MWMSearchFrameworkHelper.mm
iphone/Maps/UI/PlacePage/Components/TaxiViewController.swift
iphone/Maps/UI/PlacePage/PlacePageInteractor.swift
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManager.mm
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManagerHelper.h
iphone/Maps/UI/PlacePage/PlacePageManager/MWMPlacePageManagerHelper.mm
iphone/Maps/UI/Search/Tabs/CategoriesTab/SearchBannerCell.swift
iphone/Maps/UI/Search/Tabs/CategoriesTab/SearchBannerCell.xib
iphone/Maps/UI/Search/Tabs/CategoriesTab/SearchCategoriesViewController.swift

https://jira.mail.ru/browse/MAPSME-15135

[ios] Statistics + search banner category unification

---

data/categories_brands.txt

https://github.com/mapsme/omim/pull/13832
часть из синонимов из реквеста уже была у нас в categories_brands.txt

[categories_brands] Add categories_brands Japanese synonyms.

---

map/bookmark_manager.cpp

https://jira.mail.ru/browse/MAPSME-15206

[bookmarks] Compilation inherit author and access rules from parent category.

---

platform/platform.cpp
platform/platform.hpp
track_analyzing/CMakeLists.txt
track_analyzing/temporary_file.cpp
track_analyzing/temporary_file.hpp
track_analyzing/track_analyzing_tests/CMakeLists.txt
track_analyzing/track_analyzing_tests/track_archive_reader_tests.cpp
track_analyzing/track_archive_reader.cpp
track_analyzing/track_archive_reader.hpp
tracking/archive.hpp

Класс для чтения архивов с оффлайн треками пользователей.

[track_analyzing]Add track archive reader

---

map/search_mark.cpp

Rebase #13879 onto release-103.
https://jira.mail.ru/browse/MAPSME-14844

[searchmarks] Do not mark as visible searchmarks that clicked twice.

---

data/countries.txt
data/external_resources.txt

https://t.bk.ru/9pd5y/200920-201101.checks.txt
https://t.bk.ru/Mazrh/200920-201101-logs.checks.txt

[planet] New data from 01.11.2020

---

partners_api/ads/arsenal_ads.cpp

https://jira.mail.ru/browse/MAPSME-15227

[ads] arsenal countries are changed

---

android/res/values/themes-base.xml

https://jira.mail.ru/browse/MAPSME-15028

[android] ignore system dark theme

---

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

https://jira.mail.ru/browse/MAPSME-15103
При повторном вызове метода setMapObject не вызывался код, ответственный за установку страны и видимости кнопки загрузки.

[android] set country for existing map object

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/search/SearchFilterController.java
android/src/com/mapswithme/maps/search/SearchFragment.java

https://jira.mail.ru/browse/MAPSME-14011

[android] Show "view on map" in p2p mode search.

---

android/src/com/mapswithme/maps/bookmarks/Holders.java

https://jira.mail.ru/browse/MAPSME-15145
Условие отображение кнопки more задала.
Верхнее меню настроено верно, эффект должен починиться с помощью при проставлении айди автора в самой kml.
После проверки верхнего меню на другой kml выведу из драфта.

[android] Fix more button visibility on bookmark item.

---

android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java

https://jira.mail.ru/browse/MAPSME-15145
Теперь у компиляции в диалоговом меню нет опции удалить.

[android] Hided button ''delete" in compilation's option menu.

---

android/res/layout/fragment_auth_editor.xml

https://jira.mail.ru/browse/MAPSME-14525
Обрезанный вид встречался бы везде вне зависимости от разрешения экрана. Исправлено.

[android] Fixed font size in osm rating string.

---

android/res/drawable/bg_search_category_ad_action_night.xml
android/res/drawable/bg_search_category_banner_night.xml
android/res/layout/item_search_promo_category.xml
android/res/values/colors.xml
android/res/values/themes-attrs.xml
android/res/values/themes-base.xml
android/src/com/mapswithme/util/Utils.java

https://jira.mail.ru/browse/MAPSME-15232
https://jira.mail.ru/browse/MAPSME-15252

Android search category changes + currency formatting changes

---

android/res/layout/fragment_bookmark_list.xml
android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java

2 комита:
1. При выполнении задачи https://jira.mail.ru/browse/MAPSME-15123 добавила вызов, в котором был  Objects.requireNonNull, который приводил к крешу. Тем самым исправлен таск https://jira.mail.ru/browse/MAPSME-15220 .
2. Исправила поведение скрола при поиске, вопрос который поднял @tomilov. https://jira.mail.ru/browse/MAPSME-15256

[android] Search fixes.

---

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

https://jira.mail.ru/browse/MAPSME-15253
Для кейса, описанного в тикете, страна устанавливалась дважды, что приводило к крэшу. Регрессия от https://jira.mail.ru/browse/MAPSME-15103, его тоже проверил после фикса, работает ок

[android] reset country only in case if it's null

---

android/res/layout/fragment_web_view_with_progress.xml

https://jira.mail.ru/browse/MAPSME-7662

[android]: fix for language picker on signin webview

---

android/src/com/mapswithme/util/LocationUtils.java

https://jira.mail.ru/browse/MAPSME-14906 - работает верно, единственно дропнула проверку на версию андройда.

[android] Removed useless condition.

---

tools/python/maps_generator/generator/diffs.py
tools/python/maps_generator/generator/settings.py
tools/python/maps_generator/generator/stages_declaration.py
tools/python/maps_generator/var/etc/map_generator.ini.default

Added a new mwm stage for the diff generation.
Working with the pybindings from the pymwm_diff.
Configured by DATA_ARCHIVE_DIR and DIFF_VERSION_DEPTH from the settings/config.

[generator]Added a new mwm stage for the diff generation

---

android/build.gradle
android/src/com/mapswithme/maps/bookmarks/ChooseBookmarkCategoryFragment.java
android/src/com/mapswithme/maps/editor/EditorFragment.java

https://jira.mail.ru/browse/MAPSME-8499 
Встречалась в 2-х местах. Заменила на сдкашную, проверила все работает в разных ориентациях.

[android] Remove org.solovyev.android.views:linear-layout-manager lib from project.

---

generator/feature_builder.cpp
generator/generator_integration_tests/features_tests.cpp
indexer/ftypes_matcher.cpp
indexer/ftypes_matcher.hpp

https://jira.mail.ru/browse/MAPSME-15118
Статистика по типам для которых записывали ref в name: https://t.bk.ru/2H9PY/types.txt

[generator] Fixed default name replacing.

---

android/res/layout/edit_bookmark_common.xml
android/res/layout/fragment_auth_editor_dialog.xml
android/res/layout/fragment_edit_bookmark.xml
android/res/layout/fragment_google_play_dialog.xml
android/res/layout/fragment_google_plus_dialog.xml

Конкретно по задаче https://jira.mail.ru/browse/MAPSME-15244 не воспроизвелось у меня на телефоне на сборке release-103, выглядит так ![](https://sun9-37.userapi.com/k7PXfKpTMvdtoKLYyxjMwyWePhjDrhz_MHBsMg/SaXYkuI-AI0.jpg)
Добавила фон в некоторых диалогах.
Исправила фон в редактировании метки, стр:
1. заходим в свои метки, выбираем непустую категорию.
2. у метки нажимаем more - выбираем редактировать.
Было ![](https://sun9-60.userapi.com/RrgJziz-KEhtT4rJhGlzScFRl7_QbzCCw82eKw/dydY3iglCYM.jpg)
Стало(по аналогии с редактированием категории) ![](https://sun9-8.userapi.com/xd0-QW-7hXe3YCtsAkTV72ZIJJEwS3SopNV0yw/LHu2ay6plMc.jpg)

[android] Added background in some layouts.

---

generator/routing_index_generator.cpp
routing/geometry.cpp
routing/geometry.hpp
routing/index_graph_loader.cpp
routing/index_graph_loader.hpp
routing/index_graph_serialization.hpp

Выбор размера кэша геометрии дорожной сети на этапе генерации MWM для сохранения всех данных. По оценке должно ускорить построение  кросс MWM секции на 30%.

[routing][generator] Adaptive roads cache size

---

iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
iphone/Maps/UI/Storyboard/Main.storyboard

https://jira.mail.ru/browse/MAPSME-14749
Исправлены констрейнты для ControlsView в Main.storyboard + небольшие фиксы анимации

[iOS] Side buttons landscape fix

---

iphone/Maps/UI/PlacePage/Components/HotelReviewsViewController.swift

https://jira.mail.ru/browse/MAPSME-15019

[iOS] Formatted rating string in PP

---

iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
iphone/Maps/Classes/MapViewController.mm
iphone/Maps/UI/BottomMenu/Menu/BottomMenuInteractor.swift

https://jira.mail.ru/browse/MAPSME-15131

[iOS] Fixed bottom tabbar state on guide navigation bar

---

android/res/layout/fragment_confirmation.xml

https://jira.mail.ru/browse/MAPSME-15292

[android] Fixed background in night mode in confirmation dialogs.

---

iphone/Maps/Bookmarks/BookmarksList/BookmarksListPresenter.swift

https://jira.mail.ru/browse/MAPSME-15124

[iOS] Disable sharing on empty bookmark group

---

android/res/layout/fragment_bookmark_categories.xml
android/res/layout/fragment_bookmark_list.xml
android/res/layout/fragment_catalog_bookmark_categories.xml
android/res/layout/placeholder_with_progressbar_layout.xml
android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java

https://jira.mail.ru/browse/MAPSME-15274

[android] Added progress bar in bookmarks layout.

---

android/AndroidManifest.xml

https://jira.mail.ru/browse/MAPSME-15279

[android] Delete myTracker service in Manifest.xml

---

iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkSearchData.h
iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkSearchData.mm
iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkSubscriptionData.h
iphone/CoreApi/CoreApi/DeepLink/Data/DeepLinkSubscriptionData.mm

https://jira.mail.ru/browse/MAPSME-15038

[iOS] Renamed urlType in deeplink data

---

storage/storage.cpp
storage/storage.hpp

https://jira.mail.ru/browse/MAPSME-15275

[storage] diffs aborting processing is corrected

---

android/src/com/mapswithme/maps/taxi/TaxiManager.java
android/src/com/mapswithme/util/statistics/Statistics.java

https://jira.mail.ru/browse/MAPSME-15258

[android] statistical event Routing_Build_Taxi is fixed

---

android/res/layout/item_category_description.xml
android/src/com/mapswithme/maps/bookmarks/BookmarkListAdapter.java
android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
android/src/com/mapswithme/maps/bookmarks/Holders.java

https://jira.mail.ru/browse/MAPSME-15314

[android] Return old description block in users bookmarks.

---

android/res/layout/fragment_show_on_map_catalog_category.xml

https://jira.mail.ru/browse/MAPSME-15293

[android] Fix night mode in show on map dialog.

---

android/src/com/mapswithme/maps/routing/RoutingController.java
android/src/com/mapswithme/maps/taxi/TaxiInfoError.java
android/src/com/mapswithme/util/statistics/Statistics.java

еще раз)
https://jira.mail.ru/browse/MAPSME-15258

[android] taxi error tracking unification

---

platform/background_downloader_ios.h
platform/background_downloader_ios.mm
storage/background_downloading/downloader_adapter_ios.mm

https://jira.mail.ru/browse/MAPSME-15261

[ios] background downloader finish callback is fixed

---

generator/routing_index_generator.cpp
routing/geometry.cpp
routing/geometry.hpp
routing/index_graph_loader.cpp
routing/index_graph_loader.hpp
routing/index_graph_serialization.hpp

Cherry-pick of [#13593](https://github.com/mapsme/omim/pull/13593) to master.

cherry-pick [routing][generator] Adaptive roads cache size

---

android/src/com/mapswithme/maps/bookmarks/BookmarkCollectionAdapter.java
android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java

https://jira.mail.ru/browse/MAPSME-15335 
Исправлен пока только второй кейс. На счет первого есть ограничения по ядру.

[android] Fixed statistic visibility compilation method.

---

android/jni/com/mapswithme/maps/UserMarkHelper.cpp
map/place_page_info.cpp
map/place_page_info.hpp

https://jira.mail.ru/browse/MAPSME-14904

[Android][LP][bookmarks] Add predicate for LP bookmarks to fill PP the same way as for map features

---

android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java

https://jira.mail.ru/browse/MAPSME-14516

[android] Send headers after auth in catalog.

---

android/src/com/mapswithme/maps/bookmarks/BookmarkCollectionAdapter.java

https://jira.mail.ru/browse/MAPSME-15337

[android] Fixed update collection and categories when hide all/show all button was pressed.

---

generator/CMakeLists.txt
generator/generator_tool/generator_tool.cpp
generator/routing_world_roads_generator.cpp
generator/routing_world_roads_generator.hpp
tools/python/maps_generator/generator/env.py
tools/python/maps_generator/generator/gen_tool.py
tools/python/maps_generator/generator/settings.py
tools/python/maps_generator/generator/stages_declaration.py
tools/python/maps_generator/generator/steps.py
tools/python/maps_generator/var/etc/map_generator.ini.default

В map_generator.ini добавлен новый параметр WORLDROADS_URL - путь к файлу, в котором в текстовом виде хранится информация для графа CrossBorderGraph из #13958 
В генератор добавлен новый stage, состоящий из одного step, для запуска generator_tool с параметром - путем к этому файлу.
В generator_tool  добавлена сериализация данных из файла в новую секцию в World.

[generator] Fill section with main roads for routing in World.mwm.

---

android/res/layout/dialog_sorting_types.xml

https://jira.mail.ru/browse/MAPSME-15330

[android] Fixed night mode in sorting dialog.

---

iphone/Maps/Bookmarks/BookmarksList/BookmarksListViewController.swift

https://jira.mail.ru/browse/MAPSME-15166

[iOS] Added bottom keyboard inset in Bookmark List

---

iphone/Maps/UI/BottomMenu/Menu/BottomMenuInteractor.swift

https://jira.mail.ru/browse/MAPSME-15321

[iOS] Fixed tabbar visibility in menu

---

iphone/Maps/Bookmarks/BookmarksList/BookmarksListInterfaces.swift
iphone/Maps/Bookmarks/BookmarksList/BookmarksListPresenter.swift

https://jira.mail.ru/browse/MAPSME-15334

[iOS] Fixed collections show/hide statistics

---

android/jni/com/mapswithme/maps/Framework.cpp
android/jni/com/mapswithme/util/StringUtils.cpp

https://jira.mail.ru/browse/MAPSME-14203

[jni] Added localization in measurement.

---

android/src/com/mapswithme/maps/SplashActivity.java
android/src/com/mapswithme/maps/background/NotificationService.java
android/src/com/mapswithme/maps/editor/EditorHostFragment.java
android/src/com/mapswithme/maps/editor/ViralFragment.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

Remove prefs() from NotificationService, EditorHostfragment, ViralFragment, SplashActivity, PlacePageView.

[android] Refactoring  MwmApplication.prefs().

---

android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java
android/src/com/mapswithme/util/statistics/MytargetHelper.java

[android] Remove MwmApplication.prefs() from MyTargetHelper.

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/background/WorkerService.java
android/src/com/mapswithme/maps/editor/Editor.java
android/src/com/mapswithme/maps/editor/EditorHostFragment.java
android/src/com/mapswithme/maps/editor/OsmAuthFragmentDelegate.java
android/src/com/mapswithme/maps/editor/OsmOAuth.java
android/src/com/mapswithme/maps/editor/ProfileFragment.java
android/src/com/mapswithme/util/statistics/Statistics.java

[android] Remove MwmApplication.prefs from OsmOAuth.

---

android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/SplashActivity.java
android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
android/src/com/mapswithme/util/Config.java
android/src/com/mapswithme/util/SharedPropertiesUtils.java
android/src/com/mapswithme/util/statistics/Statistics.java

Refactoring MwmApplication, Statistic, SharedPropertiesUtils.

[android] Refactoring MwmApplication.prefs().

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/SplashActivity.java
android/src/com/mapswithme/maps/ads/LikesManager.java
android/src/com/mapswithme/maps/ads/RateStoreDialogFragment.java
android/src/com/mapswithme/maps/background/UpgradeReceiver.java
android/src/com/mapswithme/maps/onboarding/NewsFragment.java
android/src/com/mapswithme/maps/onboarding/WelcomeDialogFragment.java
android/src/com/mapswithme/util/Counters.java
android/src/com/mapswithme/util/statistics/Statistics.java

[android]Remove usage of MwmApplication.prefs from Counters.

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/search/SearchFragment.java

https://jira.mail.ru/browse/MAPSME-13189
В итоге оказалось достаточно засетить поисковый запрос сразу после вызова showResult, таким образом тулбар автоматически отображается вместе с ПП и работает аналогично с экраном "View on map"
https://confluence.mail.ru/display/MAPSME/Search#Search-BackfromPPofthesearchresulttothelist
проверил, переходы соответствуют требованиям

toolbar with back button for single search result

---

android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/location/TrackRecorder.java
android/src/com/mapswithme/maps/location/TrackRecorderWakeReceiver.java
android/src/com/mapswithme/maps/location/TrackRecorderWakeService.java
android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java

ttps://jira.mail.ru/browse/MAPSME-15354

[android] Refactoring TrackRecorder class.

---

android/res/layout/fragment_promo_after_booking_dialog.xml

https://jira.mail.ru/browse/MAPSME-15373

[Android] Change background in fragment_promo_after_booking_dialog.xml

---

android/src/com/mapswithme/maps/background/AbstractLogBroadcastReceiver.java
android/src/com/mapswithme/maps/background/UpgradeReceiver.java
android/src/com/mapswithme/maps/background/WorkerService.java
android/src/com/mapswithme/maps/editor/Editor.java
android/src/com/mapswithme/maps/location/GPSCheck.java
android/src/com/mapswithme/maps/location/TrackRecorderWakeReceiver.java
android/src/com/mapswithme/util/MultipleTrackerReferrerReceiver.java

https://jira.mail.ru/browse/MAPSME-15367
Remove usage from AbstractLogBroadcastReceiver, BroadcastReceiver, WorkerService, Editor, GPSCheck, LocationHelper, TrackRecorderWakeReceiver, MultipleTrackerReferrerReceiver.

[android] Remove usage of MwmApplication.backgroundTracker

---

android/res/layout/place_page_details.xml
android/res/layout/place_page_key_info_header.xml
android/src/com/mapswithme/maps/bookmarks/data/MapObject.java
android/src/com/mapswithme/maps/bookmarks/data/Metadata.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

https://jira.mail.ru/browse/MAPSME-15362

[android] fix for lost header label 'key information' on PP

---

android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/location/TrackRecorder.java

Заключительный коммит по https://jira.mail.ru/browse/MAPSME-15354

[Android] Remove MwmApplication.prefs

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/PanelAnimator.java
android/src/com/mapswithme/maps/ads/RateStoreDialogFragment.java
android/src/com/mapswithme/maps/background/NotificationService.java
android/src/com/mapswithme/maps/routing/ResultCodesHelper.java
android/src/com/mapswithme/maps/routing/RoutingController.java
android/src/com/mapswithme/maps/routing/RoutingErrorDialogFragment.java
android/src/com/mapswithme/maps/routing/RoutingMapsDownloadFragment.java
android/src/com/mapswithme/maps/routing/RoutingPlanController.java
android/src/com/mapswithme/maps/routing/RoutingPlanInplaceController.java
android/src/com/mapswithme/maps/widget/RotateDrawable.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java

Remove from classes: NotificationService, PanelAnimator, PlacePageButtons.Item, RateStoreDialogFragment, ResultCodesHelper, RotateDrawable, RoutingController, RoutingErrorDialogFragment, RoutingMapsDownloadFragment, RoutingPlanController.

[android] Remove usage of MwmApplication.get.

---

iphone/Maps/UI/BottomMenu/Menu/BottomMenuInteractor.swift

https://jira.mail.ru/browse/MAPSME-15321

[iOS] Added restore state on bottom tabbar

---

android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/location/CompassData.java
android/src/com/mapswithme/maps/location/LocationHelper.java
android/src/com/mapswithme/maps/location/TrackRecorder.java
android/src/com/mapswithme/maps/location/TrackRecorderWakeReceiver.java
android/src/com/mapswithme/maps/location/TrackRecorderWakeService.java
android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
android/src/com/mapswithme/util/ThemeSwitcher.java

https://jira.mail.ru/browse/MAPSME-15367

[android] Remove usage of MwmApplication.backgroundTracker.

---

android/src/com/mapswithme/maps/MapFragment.java
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/PanelAnimator.java
android/src/com/mapswithme/maps/bookmarks/BookmarkBackupController.java
android/src/com/mapswithme/maps/editor/EditorFragment.java
android/src/com/mapswithme/maps/editor/SimpleTimetableAdapter.java
android/src/com/mapswithme/maps/editor/data/TimeFormatUtils.java
android/src/com/mapswithme/maps/location/LocationHelper.java
android/src/com/mapswithme/maps/location/SensorHelper.java
android/src/com/mapswithme/maps/location/TrackRecorder.java
android/src/com/mapswithme/maps/onboarding/BaseNewsFragment.java
android/src/com/mapswithme/maps/onboarding/NewsFragment.java
android/src/com/mapswithme/maps/routing/BaseRoutingErrorDialogFragment.java
android/src/com/mapswithme/maps/search/SearchFragment.java
android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
android/src/com/mapswithme/maps/sound/TtsPlayer.java
android/src/com/mapswithme/maps/widget/menu/MenuToggle.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
android/src/com/mapswithme/util/PermissionsUtils.java
android/src/com/mapswithme/util/SharedPropertiesUtils.java
android/src/com/mapswithme/util/UiUtils.java

Remove from classes: PermissionsUtils, SensorHelper, SharedPropertiesUtils, TimeFormatUtils, TrackRecorder, TtsPlayer, UiUtils

[Android] Remove usage of MwmApplication.get()

---

android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/analytics/ExternalLibrariesMediator.java
android/src/com/mapswithme/maps/background/AbstractLogBroadcastReceiver.java
android/src/com/mapswithme/maps/background/UpgradeReceiver.java
android/src/com/mapswithme/maps/background/WorkerService.java
android/src/com/mapswithme/maps/base/BaseActivityDelegate.java
android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
android/src/com/mapswithme/maps/intent/Factory.java
android/src/com/mapswithme/maps/location/TrackRecorderWakeReceiver.java
android/src/com/mapswithme/maps/location/TrackRecorderWakeService.java
android/src/com/mapswithme/maps/purchase/BookmarkPaymentDataParser.java
android/src/com/mapswithme/maps/purchase/PurchaseUtils.java
android/src/com/mapswithme/maps/scheduling/ConnectivityJobScheduler.java
android/src/com/mapswithme/util/CrashlyticsUtils.java
android/src/com/mapswithme/util/MultipleTrackerReferrerReceiver.java
android/src/com/mapswithme/util/StorageUtils.java
android/src/com/mapswithme/util/Utils.java
android/src/com/mapswithme/util/log/LoggerFactory.java
android/src/com/mapswithme/util/statistics/Statistics.java

[adnroid] remove MwmApplication.get method part 2

---

android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java

https://jira.mail.ru/browse/MAPSME-14516

[android] Updated method onAuthorizationRequired in BookmarksCatalogFragment

---

android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java
android/src/com/mapswithme/maps/editor/HoursMinutesPickerFragment.java
android/src/com/mapswithme/maps/editor/data/HoursMinutes.java
android/src/com/mapswithme/maps/gallery/Holders.java
android/src/com/mapswithme/maps/gallery/Items.java
android/src/com/mapswithme/maps/gallery/RegularAdapterStrategy.java
android/src/com/mapswithme/maps/location/GPSCheck.java
android/src/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
android/src/com/mapswithme/maps/location/LocationHelper.java
android/src/com/mapswithme/maps/search/FilterFragment.java
android/src/com/mapswithme/maps/search/HotelsTypeAdapter.java
android/src/com/mapswithme/maps/widget/FadeView.java
android/src/com/mapswithme/maps/widget/HeightLimitedFrameLayout.java
android/src/com/mapswithme/util/DateUtils.java

DownloaderAdapter
FadeView
FilterFragment
GoogleFusedLocationProvider
GPSCheck
HeightLimitedFrameLayout
HotelsTypeAdapter
HoursMinutes
Items.LocalExpertMoreItem

[android] remove MwmApplication.get part 3

---

android/jni/com/mapswithme/platform/Platform.cpp
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/downloader/DownloaderFragment.java
android/src/com/mapswithme/maps/location/LocationHelper.java
android/src/com/mapswithme/maps/routing/SearchWheel.java
android/src/com/mapswithme/maps/search/SearchEngine.java
android/src/com/mapswithme/maps/search/SearchFragment.java
android/src/com/mapswithme/maps/search/SearchRecents.java
android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
android/src/com/mapswithme/util/Language.java
android/src/com/mapswithme/util/LocationUtils.java
android/src/com/mapswithme/util/log/MemLogging.java

Items.MoreSearchItem
Language
LocationHelper
LocationUtils
MemLogging
MwmActivity

[android] remove MwmApplication get

---

android/src/com/mapswithme/maps/ugc/routes/TagsResFactory.java

https://jira.mail.ru/browse/MAPSME-15385

[android] Fixed night mode tags items.

---

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

https://jira.mail.ru/browse/MAPSME-15398

[android] fix for hidden description label on PP

---

android/jni/com/mapswithme/platform/Platform.cpp
android/src/com/mapswithme/util/Language.java

fixes for comments from review

[android] remove unused imports and reformat code

---

android/src/com/mapswithme/maps/ugc/routes/UgcRouteEditSettingsFragment.java

https://jira.mail.ru/browse/MAPSME-15388
Добавлена проверка на пустоту имени и на повторение с уже существующими. При неудачной попытке - отображается диалоговое окно.

[android] Added check into edittext category name.

---

android/src/com/mapswithme/maps/bookmarks/BaseBookmarkCategoriesFragment.java
android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java

https://jira.mail.ru/browse/MAPSME-8919

[android] Fixed doubling sharing category dialog.

---

android/src/com/mapswithme/maps/MwmApplication.java
android/src/com/mapswithme/maps/SplashActivity.java
android/src/com/mapswithme/maps/background/NotificationService.java
android/src/com/mapswithme/maps/base/BaseMwmFragmentActivity.java
android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
android/src/com/mapswithme/maps/gallery/Items.java
android/src/com/mapswithme/maps/gallery/impl/Factory.java
android/src/com/mapswithme/maps/gallery/impl/HotelAdapterStrategy.java
android/src/com/mapswithme/util/PermissionsUtils.java
android/src/com/mapswithme/util/StorageUtils.java

https://jira.mail.ru/browse/MAPSME-15405

[android] Remove sSelf and get() from MwmApplication

---

android/jni/com/mapswithme/maps/editor/OpeningHours.cpp

https://jira.mail.ru/browse/MAPSME-15404

[android] fix for crash on search

---

android/src/com/mapswithme/maps/bookmarks/description/BookmarksDescriptionFragment.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
android/src/com/mapswithme/util/Utils.java

https://jira.mail.ru/browse/MAPSME-15358
Воспроизводилось только на Самсунге. Проблема появилась сразу после смены targetSdkVersion 29 (с версией апи 28 не воспроизводится). Решение по типу workaround https://stackoverflow.com/questions/58061708/webview-targeting-29-not-showing-content

[android] fix for broken content in webview on PP

---

android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadFragmentDelegate.java

https://jira.mail.ru/browse/MAPSME-14516

[android] Added loadCatalog in BookmarksDownloadFragmentDelegate.

---

generator/world_roads_builder/world_roads_builder.cpp
generator/world_roads_builder/world_roads_builder.hpp
generator/world_roads_builder/world_roads_builder_tool/world_roads_builder_tool.cpp
map/routing_manager.hpp
routing/absent_regions_finder.cpp
routing/absent_regions_finder.hpp
routing/async_router.cpp
routing/dummy_world_graph.hpp
routing/index_graph_starter.cpp
routing/regions_router.cpp
routing/regions_router.hpp
routing/regions_sparse_graph.cpp
routing/regions_sparse_graph.hpp
routing/routing_integration_tests/CMakeLists.txt
routing/routing_integration_tests/absent_regions_finder_tests.cpp

Исправлены ошибки роутинга по World-графу.
Добавлены интеграционные тесты.
@ldo2 @bykoianko Удобнее всего смотреть по комитам.

[routing] World roads fixes & tests.

---

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

https://jira.mail.ru/browse/MAPSME-15398

[android] fix for lost LP logo

---

indexer/data_header.cpp
indexer/data_header.hpp

мы уже давно не поддерживаем такие старые mwm

[indexer] DataHeader: remove 2011 format support.

---

android/res/layout-land/activity_download_resources.xml
android/res/layout/activity_download_resources.xml

https://jira.mail.ru/browse/MAPSME-15422
Проблемы с отображением векторов на 5-6 андроиде в ImageView. Заменил на AppComapt, с ним работает прекрасно

[android] fix for crash on startup on android os ver 5-6

---

iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm

https://jira.mail.ru/browse/MAPSME-15224

[iOS] Fixed duplicate banner creation in downloader screen

---

data/categories.txt

список переводов от переводчиков:
https://docs.google.com/spreadsheets/d/1Tn1qy-OhIN2TLjd_OarEQZ1lTC-M0nHJ0S2QoUCnXOI/edit?usp=sharing
во втором столбце оригинальный перевод, в третьем то что в итоге вошло в реквест
красным помечены строки, в которых оригинальный перевод был отредактирован (удалены или изменены все или часть синонимов)
зеленым помечены строки которые были дополнены синонимами (в осносном из categories)
белые строки вошли в реквест без изменений

[categories] Fix korean search categories.

---

partners_api/ads/ads_engine.cpp

https://jira.mail.ru/browse/MAPSME-15444

[ads] arsenal ads are removed

---

drape_frontend/transit_scheme_builder.cpp

Исправлен небольшой косяк отрисовки остановок метро на схеме метро (новая версия секции транзит).
На скрине остановка "Улица 1905 года" отрендерена правильно. До реквеста она обводилась черным цветом, как пересадка (на скрине это Краснопресненская).

[drape_frontend] Handle corner case in new subway map rendering.

---

generator/generator_tests/speed_cameras_test.cpp

В тестах на то куда внутри сегмента попадает камера скорости не было учтено что это зависит от размера сегмента (если сегмент маленький, например 2.5 метра как в данном тесте, +/- метр с которым кодируется положение камеры вносит существенный разброс). Вместо этого было просто захардкожено куда при текущем сохранении геометрии попадёт камера.

[generator_tests] Fix coefficient epsilon for speed cameras test.

---

generator/generator_integration_tests/features_tests.cpp
routing/routing_benchmarks/car_routing_tests.cpp

По ошибке были закомментированы тесты в https://github.com/mapsme/omim/pull/14018/files

Uncommented tests.

---

generator/generator_tool/generator_tool.cpp
tools/python/maps_generator/__main__.py
tools/python/maps_generator/generator/env.py
tools/python/maps_generator/generator/gen_tool.py
tools/python/maps_generator/generator/settings.py
tools/python/maps_generator/generator/stages_declaration.py
tools/python/maps_generator/generator/steps.py
tools/python/maps_generator/var/etc/map_generator.ini.default

Добавлен промежуточный этап в генератор для подготовки worldroads.txt. worldroads.txt затем подкладывается generator_tool для сборки специальной роутинг-секции в World.mwm.

[generator] Step for world roads creation.

---

android/build.gradle
android/src/com/mapswithme/maps/tips/Tutorial.java

https://jira.mail.ru/browse/MAPSME-15291

[android] fix for status bar when prompt is shown

---

iphone/Maps/Classes/MapViewController.mm
iphone/Maps/Maps.xcodeproj/project.pbxproj
iphone/Maps/UI/Welcome/TermsUpdate/TermsUpdateViewController.swift
iphone/Maps/UI/Welcome/TermsUpdate/TermsUpdateViewController.xib
iphone/Maps/UI/Welcome/WelcomeView/WelcomeStorage.swift

[iOS] Added terms update view

---

android/gradle.properties
android/res/layout/fragment_new_terms.xml
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/onboarding/WelcomeDialogFragment.java
android/src/com/mapswithme/maps/promo/NewTermsDialogFragment.java
android/src/com/mapswithme/util/SharedPropertiesUtils.java
android/src/com/mapswithme/util/UiUtils.java

No issue new terms dialog

---

openlr/router.cpp
routing/routing_tests/followed_polyline_test.cpp
search/geocoder.cpp

FTBFS with `lcc` compiler fixed.
Compiler version: lcc:1.25.10:Nov--7-2020:e2k-v4-linux.

[elbrus] Porting to e2k-v4 arch.

---

tools/python/transit/gtfs/download_gtfs.py

1. Добавлена обработка двух типов исключений, которые словила Таня: 
https://github.com/mapsme/omim/pull/14089#discussion_r550903081
https://github.com/mapsme/omim/pull/14089#discussion_r550979631
2. Убран ворнинг про "неожиданный тип фида": теперь у агрегаторов кроме рил-тайм GTFS появился еще и [GBFS,](https://github.com/NABSA/gbfs/blob/master/gbfs.md) а в скором времени появятся и другие типы, поэтому ворнинг теряет смысл.
3. Переформулирована пара сообщений в лог - сделаны более понятными.

[tools][transit] Handle exceptions while crawling Transitland & refactor log messages.

---

android/src/com/mapswithme/maps/routing/NavigationController.java
android/src/com/mapswithme/maps/routing/RoutingInfo.java

https://jira.mail.ru/browse/MAPSME-14614
При дебаге выяснилось, что описанные в задаче проблемы возникают, если с ядра не приходит дистанция. Добавила проверку на пустоту дистанции, тем самым ушла ситуация показа пиктограммы "ехать прямо" пока не рассчитан следующий маневр.

[android] Fixed empty distance when user go straight.

---

generator/osm_source.cpp
generator/osm_source.hpp
generator/raw_generator.cpp
generator/translators_pool.cpp
generator/translators_pool.hpp

https://github.com/mapsme/omim/pull/11988 по частям
Тут переработаны старые 
* ce3feeb56b418d50890b4c2eb263117b0e921c1d [generator] Added log messages. (generator/osm_source.cpp, generator/osm_source.hpp, generator/raw_generator.cpp)
Добавлены вывод некоторых сообщений, что бы понимать, что и где тормозит на стадии Features. И как те или иные изменения будут улучшать генерацию.
* 2ef311d4c9c67cd00d380ed272ad1355c8680494 [generator] Added call Clear(). (generator/osm_source.cpp, generator/raw_generator.cpp, generator/translators_pool.cpp, generator/translators_pool.hpp)
Добавлен вызов Clear по аналогии a9d73c038e419ecd902a727ac5d446579e887a3a для OsmElement'ов.
* 68a56057099eceb39dc49667f7b8476e7354f000 [generator] Moved logging logic to class Stats. (generator/raw_generator.cpp)
Теперь …

[generator] Some optimizations part 2

---

android/AndroidManifest.xml

https://jira.mail.ru/browse/MAPSME-15426
Исправила, ориентираясь на статью https://ru.stackoverflow.com/questions/950834

[android] Fixed landscape orientation in download map screen.

---

android/res/values/styles.xml
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java

Продолжение https://jira.mail.ru/browse/MAPSME-15395 
2) Если в приложении темная тема включена, а в настройках девайса выключена, при копировании данных в РР появляется белое поле без текста вместо слова "копировать" 
STR
1. Включить светлую тему в настройках телефона 
2. Открыть приложение 
3. Зайти в настройки 
4. Включить ночной режим 
5. Зайти в РР объекта 
6. Долгим тапом копировать элемент описания объекта (например телефон)
7. Обратить внимание, что вместо слова копировать появляется белое поле без текста
ОР: Отображается окно с текстом (копировать)
ФР: Отображается белое окно без текста
3) При включении ночного режима приложения в разделах "Справка", "Копирайт", "вики описание места" (например: 55.733085, 37.623565) не изменяется фон соответствующий режиму 
STR
1. Открыть …

[android] Fixed background color PopupMenu in PlacePage.

---

transit/world_feed/world_feed.cpp

братик реквеста https://github.com/mapsme/omim/pull/14120
тесты world_feed_integration_tests, world_feed_tests у меня проходят

[transit] Improve get stop times for trip speed.

---

android/res/layout-land/activity_download_resources.xml
android/res/layout/activity_download_resources.xml
android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/bookmarks/BookmarkBackupController.java
android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadFragmentDelegate.java
android/src/com/mapswithme/maps/gallery/FullScreenGalleryFragment.java
android/src/com/mapswithme/maps/maplayer/AbstractIsoLinesClickListener.java
android/src/com/mapswithme/maps/maplayer/guides/GuidesManager.java
android/src/com/mapswithme/maps/maplayer/guides/GuidesState.java
android/src/com/mapswithme/maps/maplayer/isolines/IsolinesState.java
android/src/com/mapswithme/maps/maplayer/isolines/OnIsolinesChangedListenerImpl.java
android/src/com/mapswithme/maps/maplayer/traffic/widget/TrafficButtonController.java
android/src/com/mapswithme/maps/purchase/AbstractBookmarkSubscriptionFragment.java
android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
android/src/com/mapswithme/maps/widget/SearchToolbarController.java
android/src/com/mapswithme/maps/widget/placepage/FacilitiesAdapter.java
android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
android/src/com/mapswithme/util/Utils.java

https://jira.mail.ru/browse/MAPSME-9500 
Замена тостов на снекбары. В тех местах, где есть нижнее меню - снекбары отображаются выше меню (гайдлайны материала).

[android] Toasts are replaced with snackbars.

---

android/AndroidManifest.xml
android/res/layout/navigation_notification.xml
android/src/com/mapswithme/maps/MwmActivity.java
android/src/com/mapswithme/maps/location/LocationHelper.java
android/src/com/mapswithme/maps/routing/NavigationController.java
android/src/com/mapswithme/maps/routing/NavigationService.java
android/src/com/mapswithme/maps/routing/RoutingInfo.java
android/src/com/mapswithme/maps/sound/TtsPlayer.java
android/src/com/mapswithme/util/Utils.java

https://jira.mail.ru/browse/MAPSME-15417
Пока сделано открытие и закрытие сервиса навигации с обновлением локации во время работы сервиса. 
Проблемы обозначены TODO в коде.

[android] Added NavigationService.

---

transit/world_feed/world_feed.cpp

отдельными реквестами хочу добавить интеграционные тесты

[transit][world_feed] Choose stop index based on previous stop index for multiple shape projections.

---

transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp

не понимаю надо ли что-то поправить на дженкинсе кажется он уже скорее мертв

[transit][world_feed] Use repo for integration tests data.

---

transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp

тесты для https://github.com/mapsme/omim/pull/14130

[transit][world_feed] Add integration tests.

---

generator/collector_camera.cpp

Файл с дорогами в том месте упорядочивать не нужно, мы его потом удаляем

[generator] Fixed ordering.

---

transit/transit_schedule.cpp
transit/world_feed/world_feed.cpp

Думаю что gtfs_converter должен игнорировать некорректные данные, а не крешиться

[transit][world_feed] Fix crashes.
