android/AndroidManifest.xml, android/src/com/mapswithme/maps/MwmApplication.java
This reverts commit 44b2aef2e07884e7cbaf786d17755e133b23cd97.
=> Revert "[android][pushwoosh] Switching off pushwoosh geozones."

editor/user_stats.cpp, generator/booking_dataset.cpp, generator/booking_dataset.hpp, generator/booking_quality_check/booking_addr_match.cpp, generator/generate_info.hpp, generator/generator_tests/booking_test.cpp, generator/generator_tests/generator_tests.pro, generator/generator_tool/generator_tool.cpp, generator/generator_tool/generator_tool.pro, generator/osm_source.cpp, generator/search_index_builder.cpp, indexer/indexer_tests/feature_xml_test.cpp, search/search_quality/search_quality_tool/search_quality_tool.cpp, xcode/coding/coding.xcodeproj/project.pbxproj, xcode/generator/generator.xcodeproj/project.pbxproj, xcode/generator_tool/generator_tool.xcodeproj/project.pbxproj, xcode/indexer/indexer.xcodeproj/project.pbxproj, xcode/map/map.xcodeproj/project.pbxproj, xcode/search/search.xcodeproj/project.pbxproj
Добавлена возможность использовать данные от нашего геокодера
=> Booking addresses

drape/overlay_handle.cpp, drape/overlay_handle.hpp, drape_frontend/apply_feature_functors.cpp, drape_frontend/circle_shape.cpp, drape_frontend/poi_symbol_shape.cpp, drape_frontend/poi_symbol_shape.hpp, generator/booking_dataset.cpp, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, map/framework.cpp, map/place_page_info.cpp, map/place_page_info.hpp
https://jira.mail.ru/browse/MAPSME-1704
=> Added displaying of hotel info if any hotel is selected

generator/osm2type.cpp
Велодорожка иногда только с одной стороны дороги — всё равно по ней ведём, пусть и без учёта стороны.
Will fix  #3678.
=> [bicycle] Process cycleway:left/:right

editor/changeset_wrapper.cpp, editor/user_stats.cpp, generator/osm2type.cpp
Несколько PR с release-62x на мастер: #3677, #3679, #3704.
=> My pull requests to the master branch

editor/xml_feature.cpp, editor/xml_feature.hpp, indexer/editable_map_object.cpp, indexer/editable_map_object.hpp
=> [editor] Trim name

base/base_tests/string_utils_test.cpp, base/string_utils.cpp, base/string_utils.hpp, generator/booking_dataset.cpp, generator/booking_dataset.hpp, tools/python/booking_hotels.py
=> [booking] Save all translations we've got (→release-62x)

data/countries.txt, data/external_resources.txt
Ну потому что почему бы и нет.
=> [planet] New data from 1.07.2016

indexer/osm_editor.cpp, indexer/osm_editor.hpp
https://jira.mail.ru/browse/MAPSME-1303
@mgsergio 
@mpimenov
=> [editor] Remove edits when remove the map

indexer/editable_map_object.cpp, indexer/indexer_tests/editable_map_object_test.cpp
https://jira.mail.ru/browse/MAPSME-1660
@mgsergio 
@Zverik
=> [editor] incorrect website validation

search/geocoder.cpp, search/geocoder.hpp, search/search_integration_tests/smoke_test.cpp
https://jira.mail.ru/browse/MAPSME-1854
=> [search] Fixed affiliation-name loading.

generator/generator_tests/osm_type_test.cpp
Ну раз есть wheelchair, то уже не один тип.
=> [tests] Fix subway test (why add wheelchair)

drape_frontend/my_position_controller.cpp, drape_frontend/navigator.cpp
https://jira.mail.ru/browse/MAPSME-1862
=> Zoom on two touches fixed.

android/src/com/mapswithme/maps/editor/HoursMinutesPickerFragment.java
=> [android] Save opening hours properly. Fixed bug with unsaved finish.

indexer/feature_visibility.cpp
Поспешил с прибиванием типа wheelchair=* и не заметил ошибки, из-за которой данные не собирались. Не очень понял, правда, почему во время тестов месяц назад всё отлично отработало.
Этот PR исправляет сборку данных.
=> [generator] Fix wheelchair type

drape/overlay_handle.cpp, drape/overlay_handle.hpp, drape_frontend/apply_feature_functors.cpp, drape_frontend/poi_symbol_shape.cpp, drape_frontend/poi_symbol_shape.hpp, drape_frontend/text_shape.cpp, drape_frontend/text_shape.hpp
https://jira.mail.ru/browse/MAPSME-1782
=> Improved hotels displacement

generator/intermediate_data.hpp
=> [generator] Fix big node ids issue (→master)

base/bits.hpp, coding/bit_streams.hpp, coding/coding.pro, coding/coding_tests/bit_streams_test.cpp, coding/coding_tests/coding_tests.pro, coding/coding_tests/elias_coder_test.cpp, coding/elias_coder.hpp
=> [coding] Elias gamma and delta coder.

android/3rd_party/BottomSheet/build.gradle, android/UnitTests/build.gradle, android/build.gradle, generator/booking_dataset.cpp, generator/booking_dataset.hpp, generator/booking_quality_check/booking_quality_check.cpp, generator/booking_scoring.cpp, generator/booking_scoring.hpp, generator/osm_element.cpp, generator/osm_element.hpp, tools/python/booking_hotels.py, tools/python/booking_hotels_quality.py, xcode/generator/generator.xcodeproj/project.pbxproj, xcode/generator_tool/generator_tool.xcodeproj/project.pbxproj
@ygorshenin 
@burivuh 
@mpimenov
=> [booking] Booking name matching

search/intermediate_result.cpp, search/result.hpp
=> [search] Added hotel rating and hotel pricing to result metadata.

indexer/osm_editor.cpp, iphone/Maps/Classes/Editor/MWMEditorViewController.mm, iphone/Maps/Classes/MWMBasePlacePageView.mm
=> [ios] Fixed bugs

map/framework.cpp, search/params.cpp
=> [search] Honor original onResults callback.

iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.h, iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.h, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm, iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.h, iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm, iphone/Maps/Classes/Editor/MWMEditorViewController.mm
=> [ios] Personal info warning alert.

iphone/Maps/Categories/TimeUtils.h, iphone/Maps/Categories/TimeUtils.mm, iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMRoutePreview.mm
https://jira.mail.ru/browse/MAPSME-1879
=> [ios] Fixed eta formatter.

android/jni/com/mapswithme/maps/SearchEngine.cpp, android/res/layout/item_search_result.xml, android/src/com/mapswithme/maps/search/SearchAdapter.java, android/src/com/mapswithme/maps/search/SearchResult.java
@yunikkk 
@trashkalmar 
@VladiMihaylenko
=> [android] Add hotel rating and price category.

iphone/Maps/Classes/Search/MWMSearch.mm
https://jira.mail.ru/browse/MAPSME-1915
=> [ios] Workaround for current search interface implementation.

android/res/values-ru/strings.xml, iphone/Maps/ru.lproj/Localizable.strings, strings.txt
Cherry pick from td_locs_160718
=> Td locs 160718 m

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.mm, iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.xib
https://jira.mail.ru/browse/MAPSME-1883
=> [ios] Fixed sound button coloring in navigation.

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.mm
https://jira.mail.ru/browse/MAPSME-1887
=> [ios] Added diminish routing state on timer.

android/jni/com/mapswithme/maps/Framework.cpp, android/res/values/donottranslate.xml, android/res/xml-v21/prefs_route.xml, android/res/xml/prefs_route.xml, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/settings/RoutePrefsFragment.java
https://jira.mail.ru/browse/MAPSME-1904
=> [Android] Added auto zoom to settings

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationInfoView.mm
https://jira.mail.ru/browse/MAPSME-1878
=> [ios] Fixed distance to next turn label text size.

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.mm
https://jira.mail.ru/browse/MAPSME-1880
=> [ios] Fixed speed display for zero values.

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationInfoView.xib
https://jira.mail.ru/browse/MAPSME-1876
=> [ios] Added shadows to navigation UI components.

search/geocoder.cpp, search/pre_ranker.cpp, search/pre_ranker.hpp, search/processor.cpp, search/processor.hpp, search/ranker.cpp, search/ranker.hpp
=> [search] Implemented batching of search results.

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuView.mm, iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.xib, iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.h, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationInfoView.h, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationInfoView.mm
https://jira.mail.ru/browse/MAPSME-1886
=> [ios] Fixed PP position on iPad during navigation.

iphone/Maps/Classes/CustomViews/MapViewControls/Welcome/MWMFirstLaunchController.mm, iphone/Maps/Classes/Location/MWMLocationManager.mm, iphone/Maps/Classes/MapsAppDelegate.h, iphone/Maps/Classes/MapsAppDelegate.mm
https://jira.mail.ru/browse/MAPSME-1934
=> [ios] Fixed permissions request on app launch.

search/geocoder.cpp, search/mwm_context.hpp, search/retrieval.cpp, search/retrieval.hpp, search/search_integration_tests/processor_test.cpp
=> [search] MwmContext is used in Retrieval now.

drape_frontend/screen_animations.cpp, drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp
https://jira.mail.ru/browse/MAPSME-1893
=> Pretty follow animation fixed on max zoom level.

indexer/osm_editor.cpp, indexer/osm_editor.hpp
=> [editor] Fix crash in created feature editing.

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.mm, iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.xib
https://jira.mail.ru/browse/MAPSME-1882
=> [ios] Fixed settings button behavior in route mode.

iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtons.mm
https://jira.mail.ru/browse/MAPSME-1877
=> [ios] Hide location button in follow&rotate state on routing.

drape_frontend/frontend_renderer.cpp, drape_frontend/text_shape.cpp, geometry/screenbase.cpp, geometry/screenbase.hpp
https://jira.mail.ru/browse/MAPSME-1894
=> Fixed house numbers selection in perspective mode.

iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtons.mm
https://jira.mail.ru/browse/MAPSME-1747
https://jira.mail.ru/browse/MAPSME-1810
=> [ios] Hide zoo buttons on restart if disabled in settings.

iphone/Maps/Classes/CustomViews/MapViewControls/Search/TabbedView/MWMSearchTabbedViewController.mm
https://jira.mail.ru/browse/MAPSME-1811
=> Mapsme 1811

docs/MAPS.md, skin_generator/main.cpp, tools/unix/generate_symbols.sh
Пара мелких фиксов по мотивам #3777 и #3778.
=> [styles] Fix small issues in skin generator and docs

data/countries.txt, data/external_resources.txt
=> [planet] Data from 15.07.2016, with Rio 2016 points

iphone/Maps/Settings/SettingsViewController.mm
=> [ios] Exchanged autozoom and tts in settings.

drape_frontend/animation/interpolators.cpp, drape_frontend/my_position_controller.cpp, map/framework.cpp
https://jira.mail.ru/browse/MAPSME-1945
=> Autozoom is enabled by default. Autozoom parameters are tuned.

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/Sound/MWMTextToSpeech.h, iphone/Maps/Classes/CustomViews/NavigationDashboard/Sound/MWMTextToSpeech.mm, iphone/Maps/Images.xcassets/NavigationDashboard/Then Turn/finish_point_then.imageset/Contents.json, iphone/Maps/Images.xcassets/NavigationDashboard/Then Turn/round_then.imageset/Contents.json, iphone/Maps/Images.xcassets/NavigationDashboard/Then Turn/sharp_left_then.imageset/Contents.json, iphone/Maps/Images.xcassets/NavigationDashboard/Then Turn/sharp_right_then.imageset/Contents.json, iphone/Maps/Images.xcassets/NavigationDashboard/Then Turn/simple_left_then.imageset/Contents.json, iphone/Maps/Images.xcassets/NavigationDashboard/Then Turn/simple_right_then.imageset/Contents.json, iphone/Maps/Images.xcassets/NavigationDashboard/Then Turn/slight_left_then.imageset/Contents.json, iphone/Maps/Images.xcassets/NavigationDashboard/Then Turn/slight_right_then.imageset/Contents.json, iphone/Maps/Images.xcassets/NavigationDashboard/Then Turn/straight_then.imageset/Contents.json, iphone/Maps/Images.xcassets/NavigationDashboard/Then Turn/uturn_left_right.imageset/Contents.json, iphone/Maps/Images.xcassets/NavigationDashboard/Then Turn/uturn_left_then.imageset/Contents.json
https://jira.mail.ru/browse/MAPSME-1951
=> [ios] Fixed tts.

iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.h, iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.h, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm, iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.h, iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm, iphone/Maps/Classes/MapsAppDelegate.mm
=> [ios] Track warning alert.

coding/coding.pro, coding/memory_region.hpp, coding/reader.hpp, coding/succinct_mapper.hpp, indexer/centers_table.cpp, indexer/centers_table.hpp, indexer/indexer.pro, indexer/indexer_tests/centers_table_test.cpp, indexer/indexer_tests/indexer_tests.pro, indexer/rank_table.cpp
=> [indexer] Implemented CentersTable.

indexer/indexer_tests/editable_map_object_test.cpp, map/mwm_tests/mwm_foreach_test.cpp
=> [all] Fixed warnings.

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationInfoView.mm, iphone/Maps/UIFont+MapsMeFonts.h, iphone/Maps/UIFont+MapsMeFonts.mm
https://jira.mail.ru/browse/MAPSME-1982
=> [ios] Changed distance to next turn font to bold 28.

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuCollectionViewLandscapeCell.xib
https://jira.mail.ru/browse/MAPSME-1135
=> [ios] Fixed multiline label in landscape menu.

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationInfoView.xib
https://jira.mail.ru/browse/MAPSME-1989
=> [ios] Fixed gas search from routing.

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
https://jira.mail.ru/browse/MAPSME-1998
=> [ios] Fixed compass location inavlid positioning on color scheme change.

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.mm
https://jira.mail.ru/browse/MAPSME-1994
=> [ios] Fixed search stop on stop routing.

iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-982
=> [ios] Disabled fullscreen during navigation.

android/res/layout/fragment_auth_editor.xml, android/src/com/mapswithme/maps/editor/ProfileFragment.java
Удалил айтем, отображающий количество локальных правок (в айосе тоже удалили)
=> [android] count of local edits item removed

iphone/Maps/Classes/CustomViews/MapViewControls/PlacePage/Cells/OpeningHours/MWMPlacePageOpeningHoursCell.mm, iphone/Maps/Classes/CustomViews/MapViewControls/PlacePage/Cells/OpeningHours/MWMPlacePageOpeningHoursCell.xib
https://jira.mail.ru/browse/MAPSME-1519
=> [ios] Fixed opening hours layout issue in 12h mode.

defines.hpp, generator/centers_table_builder.cpp, generator/centers_table_builder.hpp, generator/generator.pro, generator/generator_tests_support/test_mwm_builder.cpp, generator/generator_tool/generator_tool.cpp, indexer/centers_table.cpp, indexer/centers_table.hpp, indexer/indexer_tests/centers_table_test.cpp, platform/mwm_traits.cpp, platform/mwm_traits.hpp, search/lazy_centers_table.cpp, search/lazy_centers_table.hpp, search/mwm_context.cpp, search/mwm_context.hpp, search/pre_ranker.cpp, search/pre_ranker.hpp, search/ranker.hpp, search/search.pro, search/search_integration_tests/pre_ranker_test.cpp, search/search_integration_tests/processor_test.cpp, search/search_integration_tests/search_integration_tests.pro, tools/unix/generate_mwm.sh, tools/unix/generate_planet.sh
=> [search] Added centers table usage.

iphone/Maps/Classes/CustomViews/MapViewControls/Search/MWMSearchView.xib
https://jira.mail.ru/browse/MAPSME-1076
=> [ios] Fixed search bar layout.

iphone/Maps/Classes/PlacePageView.xib
https://jira.mail.ru/browse/MAPSME-1542
=> [ios] Fixed PP background.

generator/generator_tests/altitude_test.cpp, indexer/altitude_loader.cpp, indexer/altitude_loader.hpp
Багфиск. Прокладка маршрута над картами без секции с высотой.
@ygorshenin @mpimenov @trashkalmar PTAL
=> Bugfix. Building pedestrian and bicycle routes with maps without altitude section.

iphone/Maps/Classes/Share/MWMShareActivityItem.mm
https://jira.mail.ru/browse/MAPSME-1062
=> [ios] Fixed sharing url.

iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
https://jira.mail.ru/browse/MAPSME-1509
=> [ios] Fixed navigation p2p button state.

drape_frontend/my_position_controller.cpp
https://jira.mail.ru/browse/MAPSME-1936
=> Changed follow-and-rotate returning constant

iphone/Maps/Classes/MWMPlacePageActionBar.mm
https://jira.mail.ru/browse/MAPSME-1960
=> [ios] Fixed action bar bookmark button state update.

android/src/com/mapswithme/maps/editor/EditorHostFragment.java
Отключение отображения кнопки сохранения при выборе языка имени в редакторе.
=> [editor] save button hiding

data/faq.html
=> FAQ_Updated_links

iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-1832
=> [ios] Fixed viral alert display behavior.

tools/python/booking_hotels.py, tools/unix/generate_planet.sh
Появились три новых ключа: `SRTM_PATH`, `BOOKING_USER` и `BOOKING_PASS`. Первый включит сборку srtm, вторые два запустят фоновый процесс по скачиванию гостиниц из букинга.
Также поправил несколько мелочей с путями и отсутствовавшим osmconvert.
=> [generator] Update generate_planet script for booking and srtm

iphone/Maps/Classes/Common.h, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TabbedView/MWMSearchTabbedViewController.mm, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TabbedView/MWMSearchTabbedViewLayout.mm
https://jira.mail.ru/browse/MAPSME-1051
=> [ios] Fixed rigthtoleft orientation support to search tabs.

iphone/Maps/Classes/UIViewController+Navigation.mm
https://jira.mail.ru/browse/MAPSME-1048
=> [ios] Fixed back button orientation for Arabic language.

iphone/Maps/Classes/CustomViews/MapViewControls/Search/TabbedView/BookmarksTab/MWMSearchBookmarksCell.xib, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TabbedView/CategoriesTab/MWMSearchCategoryCell.xib, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TabbedView/HistoryTab/MWMSearchHistoryClearCell.xib, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TabbedView/HistoryTab/MWMSearchHistoryRequestCell.xib
https://jira.mail.ru/browse/MAPSME-1052
=> [ios] Fixed text alignment for Arabic language in search.

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardEntity.mm
https://jira.mail.ru/browse/MAPSME-2062
=> [ios] Fixed pedestrian navigation maneuver direction.

iphone/Maps/Classes/CustomViews/MapViewControls/PlacePage/Cells/OpeningHours/MWMPlacePageOpeningHoursCell.mm, iphone/Maps/Classes/Editor/MWMEditorSelectTableViewCell.mm, iphone/Maps/Classes/Editor/MWMEditorSelectTableViewCell.xib
https://jira.mail.ru/browse/MAPSME-1056
=> [ios] Fixed arrows direction for Arabic language.

iphone/Maps/Classes/Editor/MWMEditorTextTableViewCell.xib
https://jira.mail.ru/browse/MAPSME-1053
=> [ios] Fixed text alignment in editor for Arabic language.

iphone/Maps/Classes/CustomViews/MapViewControls/Search/TableView/MWMSearchCommonCell.xib
https://jira.mail.ru/browse/MAPSME-1055
=> [ios] Fixed text alignment in search results for Arabic language.

map/displacement_mode_manager.cpp, map/displacement_mode_manager.hpp, map/framework.cpp, map/framework.hpp, map/map.pro, qt/search_panel.cpp, search/hotels_classifier.cpp, search/hotels_classifier.hpp, search/interactive_search_callback.cpp, search/interactive_search_callback.hpp, search/intermediate_result.cpp, search/result.hpp, search/search.pro, search/search_integration_tests/interactive_search_test.cpp, search/search_integration_tests/search_integration_tests.pro, search/search_tests_support/test_search_request.cpp, search/search_tests_support/test_search_request.hpp
https://jira.mail.ru/browse/MAPSME-1771
=> [search][ui] Implemented hotels classifier.

iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
https://jira.mail.ru/browse/MAPSME-2056
=> [ios] Fixed routing planning on iPad.

iphone/Maps/Classes/MapsAppDelegate.mm, iphone/Maps/MWMRecentTrackSettingsController.mm
https://jira.mail.ru/browse/MAPSME-1999
=> [ios] Fixed duplicate warning on active gps tracker.

iphone/Maps/Categories/UIKitCategories.mm, iphone/Maps/UIButton+RuntimeAttributes.h, iphone/Maps/UIButton+RuntimeAttributes.mm
https://jira.mail.ru/browse/MAPSME-1507
=> [ios] Added button background color name support to coloring.

iphone/Common/RichTextVC.mm, iphone/Maps/Classes/CustomAlert/RoutingDisclaimerAlert/MWMRoutingDisclaimerAlert.mm, iphone/Maps/Classes/Editor/MWMNoteCell.mm, iphone/Maps/Classes/Editor/OpeningHours/MWMOpeningHoursEditorViewController.mm, iphone/Maps/Classes/MWMPlacePageBookmarkCell.mm, iphone/Maps/Classes/MWMPlacePageInfoCell.h, iphone/Maps/Classes/MWMPlacePageInfoCell.mm
https://jira.mail.ru/browse/MAPSME-1314
=> [ios] Fixed UITextView keyboard coloring.

drape_frontend/frontend_renderer.cpp, drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp
https://jira.mail.ru/browse/MAPSME-2072
=> Less detailed autozoom levels in 2d navigation.

generator/booking_dataset.cpp, generator/booking_dataset.hpp, generator/booking_quality_check/booking_quality_check.cpp, generator/booking_quality_check/booking_quality_check.pro, generator/booking_scoring.cpp, generator/booking_scoring.hpp, generator/feature_builder.cpp, generator/feature_builder.hpp, generator/generate_info.hpp, generator/generator_tests/feature_builder_test.cpp, generator/osm2type.cpp, generator/osm_id.cpp, generator/osm_id.hpp, generator/osm_source.cpp, generator/osm_source.hpp, generator/osm_translator.hpp, indexer/classificator_loader.cpp, indexer/feature_data.cpp, indexer/feature_data.hpp, omim.pro
=> [booking] area hotels

iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm, iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtons.mm, iphone/Maps/Classes/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-2083
=> [ios] Fixed zoom buttons visibility during routing.

drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp, map/framework.cpp
https://jira.mail.ru/browse/MAPSME-2082
=> Autozoom initialization after drape engine reinitialization.

tools/python_tests/permissions_test.py
Writes the result in the same format as the C++ unit tests so that we could write its results to the same log and parse it with the Jenkins scripts.
I did think about using unittest, but it is impossible to pass parameters to such tests.
=> Simple script for checking permissions.

drape_frontend/animation/animation.hpp, drape_frontend/animation/follow_animation.cpp, drape_frontend/animation_system.cpp, drape_frontend/user_event_stream.cpp
https://jira.mail.ru/browse/MAPSME-1869
=> Fixed follow-and-rotate animation jittering

drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp
https://jira.mail.ru/browse/MAPSME-1798
=> Fixed tapping in follow-and-rotate mode

android/res/values-cs/strings.xml, data/categories.txt, iphone/Maps/cs.lproj/Localizable.strings, strings.txt
Fixed some strings on Marat's request (due to complaints from users)
=> Td locs 160804

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/api/ParsedRoutingData.java, android/src/com/mapswithme/maps/api/ParsedUrlMwmRequest.java, android/src/com/mapswithme/maps/api/RoutePoint.java, android/src/com/mapswithme/maps/routing/RoutingController.java, coding/coding_tests/uri_test.cpp, coding/uri.cpp, coding/uri.hpp, iphone/Maps/Classes/MapsAppDelegate.mm, iphone/Maps/Classes/Routing/MWMRouter.h, iphone/Maps/Classes/Routing/MWMRouter.mm, map/framework.cpp, map/framework.hpp, map/geourl_process.cpp, map/map_tests/mwm_url_tests.cpp, map/mwm_url.cpp, map/mwm_url.hpp, routing/router.cpp, routing/router.hpp, xcode/map/map.xcodeproj/project.pbxproj
Now we can use string with following format:
mapswithme://route?sll=lat0,lon0&saddr=name0&dll=lat1lon1&daddr=name1&type=vehicle%20or%20pedestrian
for example: 
"mapsme://route?sll=37.3313365,-122.0319378&saddr=name0&dll=37.3326894,-122.0319452&daddr=name1&type=bicycle"
=> [api] [omim] Build rote from API: first try.

generator/booking_quality_check/booking_quality_check.cpp
=> Fix gtool build.

data/countries.txt, data/external_resources.txt
К пятнице собирал данные с новыми высотами, но как-то забыл, что хорошо бы эти данные расшарить :)
Не для релиза: тут нет выделенных олимпийских объектов в Рио.
=> [planet] New data from 4.08.2016

editor/editor.pro, editor/editor_storage.cpp, editor/editor_storage.hpp, indexer/index_helpers.cpp, indexer/index_helpers.hpp, indexer/indexer.pro, indexer/indexer_tests/indexer_tests.pro, indexer/indexer_tests/osm_editor_test.cpp, indexer/indexer_tests/osm_editor_test.hpp, indexer/osm_editor.cpp, indexer/osm_editor.hpp, map/framework.cpp, map/framework.hpp, omim.pro, xcode/editor/editor.xcodeproj/project.pbxproj, xcode/indexer/indexer.xcodeproj/project.pbxproj
Первая часть тестов для редактора
@ygorshenin 
@mgsergio
=> [editor] first group of tests for editor

iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm, iphone/Maps/Classes/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-2092
=> [ios] Fixed p2p route building.

data/countries.txt, data/external_resources.txt
=> [planet] New data from 8.08.2016 for release-63

iphone/Maps/Classes/CustomViews/NavigationDashboard/Sound/MWMTextToSpeech.mm
https://jira.mail.ru/browse/MAPSME-2108
=> [ios] Changed volume buttons to control notifications volume.

data/categories.txt
https://jira.mail.ru/browse/MAPSME-2008
Добавил зоопарки, чтобы искались и нормально подписывались.
Переводы взял с google translate. Нужно уточнить.
=> [types] Add zoo category with draft translations

data/categories.txt
Черри-пик замёрженного реквеста #3986.
=> [types] Add zoo category with draft translations (→release-63)

data/categories.txt
Случайно прошла опечатка, которая роняет приложение по CHECK.
=> [types] Fix language typo (release-63)

data/categories.txt
Случайно прошла опечатка, которая роняет приложение по CHECK.
=> [types] Fix language typo (master)

android/src/com/mapswithme/maps/widget/menu/NavMenu.java
@yunikkk or @trashkalmar PTAL
Not sure that this is a good fix.
=> [android] Hide enable/disable tts button in pedestrian routing mode.

data/categories.txt, data/editor.config
* Милиция → полиция
* добавление водопадов, по просьбе Алекса https://jira.mail.ru/browse/MAPSME-2017
* редактирование адресных точек
=> [editor] Allow adding waterfalls and editing addresses

android/res/values-fr/strings.xml, android/res/values-it/strings.xml, android/res/values-nb/strings.xml, android/res/values-uk/strings.xml, android/res/values-zh-rTW/strings.xml, android/res/values-zh/strings.xml, android/res/values/strings.xml, data/categories.txt, iphone/Maps/en.lproj/Localizable.strings, iphone/Maps/fr.lproj/Localizable.strings, iphone/Maps/it.lproj/Localizable.strings, iphone/Maps/nb.lproj/Localizable.strings, iphone/Maps/uk.lproj/Localizable.strings, iphone/Maps/zh-Hans.lproj/Localizable.strings, iphone/Maps/zh-Hant.lproj/Localizable.strings, strings.txt
Fixed some inconsistencies in strings.txt;
Used the proposed modifications for the danish strings in categories.txt
=> Td locs 160809

android/src/com/mapswithme/maps/widget/menu/NavMenu.java
Cherry pick on the release branch.
=> [android][release-63] Hide enable/disable tts button in pedestrian routing mode.

android/res/values-fr/strings.xml, android/res/values-it/strings.xml, android/res/values-nb/strings.xml, android/res/values-uk/strings.xml, android/res/values-zh-rTW/strings.xml, android/res/values-zh/strings.xml, android/res/values/strings.xml, data/categories.txt, iphone/Maps/en.lproj/Localizable.strings, iphone/Maps/fr.lproj/Localizable.strings, iphone/Maps/it.lproj/Localizable.strings, iphone/Maps/nb.lproj/Localizable.strings, iphone/Maps/uk.lproj/Localizable.strings, iphone/Maps/zh-Hans.lproj/Localizable.strings, iphone/Maps/zh-Hant.lproj/Localizable.strings, strings.txt
=> Td locs 160809 cp to rel

data/faq.html
=> FAQ hotfix 

android/src/com/mapswithme/maps/MwmApplication.java
=> Switching off pushwoosh GeoPushes.

android/src/com/mapswithme/maps/editor/EditorHostFragment.java, android/src/com/mapswithme/maps/editor/data/LocalizedName.java, iphone/Maps/Classes/Editor/AdditionalNames/MWMEditorAdditionalNamesTableViewController.mm
=> [ios][android] Exclude Default name from "Add language" window

data/categories.txt
Swapped the first and the second sinonyms for shop-alcohol in the Danish language.
=> Fixed indexer_tests on Master

3party/opening_hours/opening_hours.cpp, iphone/Maps/Classes/Common.h
=> Compilation fix.

data/categories.txt
Swapped the first and the second sinonyms for shop-alcohol in the Danish language.
=> [Cherry-pick] Fixed indexer_tests on rel

indexer/editable_map_object.cpp, indexer/indexer_tests/editable_map_object_test.cpp
Создан вместо реквеста на релизную ветку https://github.com/mapsme/omim/pull/4031
=> [editor] Engilsh name added to mandatory names

tools/python_tests/permissions_test.py
Added a more sophisticated and robust method of finding the AAPT on the machine.
=> Better AAPT search

routing/routing_session.cpp
MAPSME-2152
@igrechuhin PTAL
Для более детального разбирательства поставил: https://jira.mail.ru/browse/MAPSME-2156
=> Bugfix. Crash on zero length routes.

iphone/Maps/Classes/Common.h, iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/MWMNavigationView.mm
https://jira.mail.ru/browse/MAPSME-2057
=> [ios] Fixed status bar height estimation for iOS7.

drape_frontend/user_event_stream.cpp
https://jira.mail.ru/browse/MAPSME-2144
=> Fixed long tap

docs/MAPS.md, tools/unix/generate_planet.sh, tools/unix/test_planet.sh
=> [generator] Update docs, add OSC parameter, new test

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationInfoView.mm
https://jira.mail.ru/browse/MAPSME-2165
=> [ios] Fixed direction arrow rotation in navigation.

android/src/com/mapswithme/maps/location/LocationHelper.java
=> [android] Added some logging for crash-hunting.

tools/python_tests/permissions_test.py
The names of some permissions differ depending on the build type, such as beta, release or debug, plus we have some permissions in some build types that are not present in the others.
=> Build type fix.

android/src/com/mapswithme/maps/location/LocationHelper.java
=> [android] Fixed crash in with null framework.

android/src/com/mapswithme/maps/location/LocationHelper.java
@mgsergio or @bykoianko or @yunikkk or @trashkalmar PTAL
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/57b33942ffcdc04250c0aec0
=> [android] Yet another LocationHelper fix fix.

3party/jansson/myjansson.hpp, indexer/indexer_tests/osm_editor_test.cpp, indexer/indexer_tests/osm_editor_test.hpp, indexer/osm_editor.cpp, indexer/osm_editor.hpp, map/framework.cpp, xcode/generator/generator.xcodeproj/project.pbxproj, xcode/indexer/indexer.xcodeproj/project.pbxproj
=> additional tests for editor

indexer/editable_map_object.cpp, indexer/indexer_tests/editable_map_object_test.cpp
https://jira.mail.ru/browse/MAPSME-1650
@mgsergio 
@ygorshenin
=> [editor] website validation corrections

drape_frontend/backend_renderer.cpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/message.hpp, drape_frontend/message_subclasses.hpp, map/framework.cpp, map/framework.hpp, map/user_mark.hpp
https://jira.mail.ru/browse/MAPSME-2193
=> Added retrieving size of search marks in mercator

iphone/Maps/Classes/CustomViews/MapViewControls/Welcome/PageController/MWMPageController.mm
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/5703dc3effcdc042507243d7
=> [ios] Crash fix.

tools/python/booking_hotels.py, tools/python/eviltransform.py, tools/unix/generate_mwm.sh
MAPSME-1872
Вытащил гостиницы из воды с помощью открытого кода.
=> [booking] Fix chinese coordinates

search/search_integration_tests/helpers.cpp, search/search_integration_tests/interactive_search_test.cpp, search/search_integration_tests/processor_test.cpp, search/search_integration_tests/smoke_test.cpp, search/search_quality/features_collector_tool/features_collector_tool.cpp, search/search_tests_support/test_search_request.cpp, search/search_tests_support/test_search_request.hpp
=> [search] Disabled launching in the constructor of TestSearchRequest.

search/search_quality/search_quality_tool/search_quality_tool.cpp, search/search_tests_support/test_search_request.cpp, search/search_tests_support/test_search_request.hpp
=> [search] Followup fixes to TestSearchRequest.

tools/python/booking_hotels.py, tools/python/eviltransform.py, tools/unix/generate_mwm.sh
=> [booking] Fix chinese coordinates (→ release-63)

docs/MAPS.md, tools/unix/generate_mwm.sh
I keep the Steps part of MAPS.md unchanged, as I not sure of current steps order (step 6).
=> [doc] Update routing and non routing index on MAPS.md

base/base_tests/string_utils_test.cpp, base/stl_add.hpp, base/string_utils.hpp, generator/booking_dataset.cpp, generator/booking_dataset.hpp, generator/booking_quality_check/booking_quality_check.cpp, generator/osm_id.hpp, generator/osm_source.cpp
@ygorshenin 
@mpimenov 
@milchakov
=> [booking] Booking workflow

indexer/editable_map_object.cpp, indexer/feature.cpp, indexer/feature_data.cpp, indexer/feature_data.hpp, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, indexer/indexer_tests/checker_test.cpp, indexer/indexer_tests/editable_map_object_test.cpp, indexer/map_object.cpp, map/style_tests/classificator_tests.cpp, routing/routing_tests/vehicle_model_test.cpp
https://jira.mail.ru/browse/MAPSME-1091
@mgsergio 
@Zverik 
@VladiMihaylenko
=> [editor] populate FMD_INTERNET from type for MapObjects

base/base_tests/string_utils_test.cpp, base/string_utils.hpp, drape_frontend/animation_system.hpp, map/displacement_mode_manager.hpp
=> [build] Build fix for libstdc++.

base/base.pro, base/base_tests/base_tests.pro, base/base_tests/newtype_test.cpp, base/newtype.hpp, std/type_traits.hpp
=> Add NewType class to have strong typedefs for primitive types.

iphone/Maps/Classes/CustomViews/MapViewControls/Welcome/MWMWelcomeController.mm
https://jira.mail.ru/browse/MAPSME-1353
=> [ios] Fixed incorrect welcome screen size on iPad.

base/internal/message.hpp, map/framework.cpp, search/nearby_points_sweeper.cpp, search/nearby_points_sweeper.hpp, search/pre_ranker.cpp, search/pre_ranker.hpp, search/pre_ranking_info.hpp, search/processor.cpp, search/processor.hpp, search/search.pro, search/search_integration_tests/pre_ranker_test.cpp, search/search_params.cpp, search/search_params.hpp, search/search_tests/nearby_points_sweeper_test.cpp, search/search_tests/search_tests.pro
=> [search] Implemented viewport search results filtering.

base/base_tests/newtype_test.cpp, base/newtype.hpp
=> Add simple output.

iphone/Maps/Classes/MapViewController.mm, iphone/Maps/Classes/MapsAppDelegate.h, iphone/Maps/Classes/MapsAppDelegate.mm, map/framework.cpp
=> [api] Fixed bugs.

android/src/com/mapswithme/maps/location/GoogleFusedLocationProvider.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/settings/MiscPrefsFragment.java
Применение тумблера Google Services в программе сразу после переключения.
@trashkalmar @yunikkk PTAL
=> Android. Switching on or off using location sevices immediately on changing check state.

data/countries.txt, data/external_resources.txt
Планета 22.08.2016 на релизную ветку.
=> [planet] New data from 22.08.2016 for release-63

android/src/com/mapswithme/maps/location/GoogleFusedLocationProvider.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/settings/MiscPrefsFragment.java
cherry-pick на мастер https://github.com/mapsme/omim/pull/4120
=> Android. Switching on or off using location sevices immediately on changing check state. 

android/jni/com/mapswithme/maps/Framework.cpp, drape_frontend/animation/parallel_animation.cpp, drape_frontend/animation/parallel_animation.hpp, drape_frontend/animation/sequence_animation.cpp, drape_frontend/animation/sequence_animation.hpp, drape_frontend/animation_system.cpp, drape_frontend/animation_system.hpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/drape_frontend_tests/user_event_stream_tests.cpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp, drape_frontend/screen_animations.cpp, drape_frontend/screen_animations.hpp, drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp, iphone/Maps/Classes/MapViewController.mm, qt/draw_widget.cpp
https://jira.mail.ru/browse/MAPSME-1971
=> Parallel arrow animation.

android/jni/Android.mk, android/jni/com/mapswithme/maps/DisplayedCategories.cpp, android/res/values/arrays.xml, android/src/com/mapswithme/maps/search/CategoriesAdapter.java, android/src/com/mapswithme/maps/search/DisplayedCategories.java, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TabbedView/CategoriesTab/MWMSearchCategoriesManager.mm, search/displayed_categories.cpp, search/displayed_categories.hpp, search/search.pro, xcode/search/search.xcodeproj/project.pbxproj
@yunikkk @igrechuhin @mpimenov PTAL
=> [android, ios, core] Add a single entity for search categories.

drape/shaders/masked_texturing_billboard_vertex_shader.vsh, drape/shaders/text_billboard_vertex_shader.vsh, drape/shaders/text_outlined_billboard_vertex_shader.vsh, drape/shaders/texturing_billboard_vertex_shader.vsh, drape/shaders/user_mark_billboard.vsh
https://jira.mail.ru/browse/MAPSME-2088
=> Fixed false displaying of billboards on the latest Samsung OGL-driver

android/res/values-ru/strings.xml, iphone/Maps/ru.lproj/Localizable.strings, strings.txt
Three Russian translations replaced.
=> Td locs 160826

indexer/indexer_tests/indexer_tests.pro, indexer/indexer_tests/osm_editor_test.cpp, indexer/indexer_tests_support/helpers.cpp, indexer/indexer_tests_support/helpers.hpp, indexer/indexer_tests_support/indexer_tests_support.pro, indexer/osm_editor.cpp, indexer/osm_editor.hpp, omim.pro, search/categories_set.hpp, search/geocoder.cpp, search/geocoder.hpp, search/processor.cpp, search/query_params.cpp, search/query_params.hpp, search/retrieval.cpp, search/search.pro, search/search_integration_tests/helpers.cpp, search/search_integration_tests/helpers.hpp, search/search_integration_tests/search_edited_features_test.cpp, search/search_integration_tests/search_integration_tests.pro, search/token_slice.cpp
https://jira.mail.ru/browse/MAPSME-2223
@milchakov @mpimenov PTAL
=> [search] Added matching of edited features by type.

android/jni/com/mapswithme/maps/SearchEngine.cpp
Get rid of sync in Android - as all calls to core comes from the UI thread, and as all callbacks from SearchEngine are posted to the UI thread.
=> [android, search] Removed unnecessary synchronization.

drape_frontend/stylist.cpp, indexer/feature_utils.cpp, indexer/indexer_tests/feature_names_test.cpp, indexer/indexer_tests/indexer_tests.pro
=> [drape][indexer] names optimization and fix

drape_frontend/drape_engine.cpp, drape_frontend/frontend_renderer.cpp, drape_frontend/message_subclasses.hpp, drape_frontend/route_renderer.cpp, drape_frontend/route_renderer.hpp
https://jira.mail.ru/browse/MAPSME-2283
=> Fixed crash in navigation on switch to night style.

data/editor.config, editor/config_loader.cpp, editor/config_loader.hpp, editor/editor.pro, editor/editor_config.cpp, editor/editor_config.hpp, editor/editor_tests/config_loader_test.cpp, editor/editor_tests/editor_config_test.cpp, editor/editor_tests/editor_tests.pro, indexer/osm_editor.cpp, indexer/osm_editor.hpp, std/iterator.hpp, xcode/editor/editor.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-882
@ygorshenin 
@mgsergio
=> [editor] Mapsme 882 web config

editor/editor_config.hpp, indexer/indexer_tests/osm_editor_test.cpp, indexer/indexer_tests_support/helpers.cpp, indexer/indexer_tests_support/helpers.hpp, indexer/osm_editor.cpp, indexer/osm_editor.hpp, map/framework.cpp, search/editor_delegate.cpp, search/editor_delegate.hpp, search/search.pro, search/search_integration_tests/helpers.cpp
=> [indexer] Removed indexer dependency on search.

android/src/com/mapswithme/maps/MwmApplication.java
Фикс креша на старте.
@ygorshenin 
@yunikkk
=> [android] initializing alohalytics on startup

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationInfoView.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationInfoView.xib, xcode/search/search.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-2302
=> [ios] Added vibration on route finish.

iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm
https://jira.mail.ru/browse/MAPSME-2184
=> [ios] Fixed alerts layout.

omim.pro, search/run_search_engine.py, search/search_engine_pylib/README.txt, search/search_engine_pylib/api.cpp, search/search_engine_pylib/run_search_engine.py, search/search_engine_pylib/search_engine_pylib.pro
@mpimenov @syershov @burivuh PTAL
=> [search] Search engine pylib

drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp
https://jira.mail.ru/browse/MAPSME-2309
=> Auto rotation to North.

android/jni/com/mapswithme/maps/DisplayedCategories.cpp, android/src/com/mapswithme/maps/search/CategoriesAdapter.java, android/src/com/mapswithme/maps/search/DisplayedCategories.java, indexer/categories_holder.cpp, indexer/categories_holder.hpp, indexer/indexer_tests/categories_test.cpp, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TabbedView/CategoriesTab/MWMSearchCategoriesManager.mm, map/framework.cpp, map/framework.hpp, search/displayed_categories.cpp, search/displayed_categories.hpp
@igrechuhin @mpimenov @alexzatsepin PTAL
=> [search][android][ios] Exposed categories synonyms.

android/jni/com/mapswithme/maps/editor/Editor.cpp, android/src/com/mapswithme/maps/editor/Editor.java, android/src/com/mapswithme/maps/editor/EditorHostFragment.java, android/src/com/mapswithme/maps/editor/LanguagesFragment.java, android/src/com/mapswithme/maps/editor/data/Language.java, android/src/com/mapswithme/maps/editor/data/LocalizedName.java, indexer/editable_map_object.cpp, indexer/editable_map_object.hpp, indexer/indexer_tests/editable_map_object_test.cpp, iphone/Maps/Classes/Editor/AdditionalNames/MWMEditorAdditionalNamesTableViewController.mm, iphone/Maps/Classes/Editor/MWMEditorViewController.mm, map/framework.cpp
Продолжение эпопеи с именами в редакторе.
Тикет https://jira.mail.ru/browse/MAPSME-2292
Спека https://confluence.mail.ru/display/MAPSME/Meta+Info+Editor+v1.2#MetaInfoEditorv1.2-Name
@ygorshenin 
@igrechuhin 
@alexzatsepin
=> [editor][ios][android] localized names part 3

editor/config_loader.cpp, editor/config_loader.hpp
Do not throw exception if editor config can not be loaded
@ygorshenin
=> config loader fix

editor/config_loader.cpp
Отключить онлайн конфиг в этом релизе
@ygorshenin
=> disable online config

data/faq.html
=> FAQ hotfix

iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm
@VladiMihaylenko : it appears that all the alerts are used, so I didn't remove any of them.
=> Changed where we turn a key into the localised string

data/countries.txt, data/external_resources.txt
=> [planet] New data from 11.09.2016

search/emitter.hpp, search/processor.cpp, search/processor.hpp, search/ranker.cpp, search/ranker.hpp, search/search.pro, search/search_integration_tests/pre_ranker_test.cpp, search/search_integration_tests/processor_test.cpp
https://jira.mail.ru/browse/MAPSME-2339
@mpimenov PTAL
=> [search] Fixed (and accelerated) coords search.

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, map/chart_generator.cpp, map/chart_generator.hpp, map/framework.hpp, map/map_tests/chart_generator_tests.cpp
JNI слой для получения Bitmap с диаграммой высот маршрута из ядра.
@yunikkk @trashkalmar @alexzatsepin @ygorshenin @rokuz PTAL
https://jira.mail.ru/browse/MAPSME-2366
https://jira.mail.ru/browse/MAPSME-2346
https://jira.mail.ru/browse/MAPSME-2368
=> [altitude chart] JNI Layer.

indexer/editable_map_object.cpp
=> localized names minor fix

android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-1800
@alexzatsepin 
@ygorshenin
=> add installation id to report

3party/minizip/CMakeLists.txt, 3party/succinct/CMakeLists.txt, 3party/tomcrypt/CMakeLists.txt, CMakeLists.txt, base/CMakeLists.txt, coding/CMakeLists.txt, coding/coding_tests/CMakeLists.txt, editor/CMakeLists.txt, geometry/geometry_tests/CMakeLists.txt, storage/CMakeLists.txt
Added three libs (without tests for now).
=> Cmake libs

iphone/Maps/Classes/Search/MWMSearch.mm
https://jira.mail.ru/browse/MAPSME-2332
=> [ios] Fixed clear previous search results on new search.

iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
https://jira.mail.ru/browse/MAPSME-2354
=> [ios] Fixed status bar style on navigation state ready.

iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
https://jira.mail.ru/browse/MAPSME-2320
=> [ios] Fixed side buttons scroll area.

android/src/com/mapswithme/maps/MwmApplication.java
=> Alohalytics installation id was added into crashlytics

map/chart_generator.cpp, map/chart_generator.hpp, map/map_tests/chart_generator_tests.cpp
Диаграмма рельефа маршрута центрована по высоте.
@ygorshenin @igrechuhin @mpimenov PTAL
https://jira.mail.ru/browse/MAPSME-2364
=> Moving altitude chart diagram to the middle of the canvas.

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-2371
@alexzatsepin
=> disable editing of place during routing planning

xcode/routing/routing.xcodeproj/project.pbxproj
=> Adding routing_benchmarks target to xcode project.

android/src/com/mapswithme/maps/editor/data/HoursMinutes.java
https://jira.mail.ru/browse/MAPSME-1015
@alexzatsepin 
@ygorshenin
=> [android] 1-12 hours format supported in editor

android/jni/com/mapswithme/platform/Platform.cpp, iphone/Maps/main.mm, platform/platform.hpp, platform/platform_android.cpp, platform/platform_ios.mm, platform/platform_mac.mm, platform/platform_qt.cpp
https://jira.mail.ru/browse/MAPSME-2394
=> [ios] Added marketing events sender to platform.

CMakeLists.txt
@mgsergio @therearesomewhocallmetim PTAL
=> [cmake] Fixed Boost inclusion.

routing/routing_integration_tests/osrm_route_test.cpp
https://jira.mail.ru/browse/MAPSME-2351
Пока только добавил тест: @ygorshenin PTAL
=> Test on negative route time.

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, iphone/Maps/Classes/Routing/MWMRouter.mm, map/framework.cpp, map/framework.hpp, std/algorithm.hpp
Передача клиенту минимальной и максимальной высоты по проложенному маршруту.
@ygorshenin @igrechuhin @alexzatsepin PTAL
https://jira.mail.ru/browse/MAPSME-2387
=> Passing min and max route altitude. 

indexer/categories_holder.cpp, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp
https://jira.mail.ru/browse/MAPSME-2392
@mpimenov 
@ygorshenin
=> [RELEASE ONLY] categories fix

map/booking_api.cpp, map/booking_api.hpp, map/map_tests/booking_tests.cpp
=> [Booking] Booking GetHotelInfo dummy method.

map/booking_api.cpp, map/booking_api.hpp
=> Fix facility datatype.

iphone/Maps/Classes/CustomViews/MapViewControls/Search/MWMSearchManager.mm, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TabbedView/CategoriesTab/MWMSearchCategoriesManager.mm, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TabbedView/MWMSearchTabbedViewProtocol.h
https://jira.mail.ru/browse/MAPSME-2406
=> [ios] Remove keyboard on category search.

routing/routing_benchmarks/bicycle_routing_tests.cpp
Добавил тест на вело маршрут, который сейчас не прокладывается.
Притом, я отдельно проверил, что маршрут не прокладывается ни при помощи AStarBidirectionalRoutingAlgorithm, ни при помощи AStarRoutingAlgorithm.
@ygorshenin @mpimenov PTAL
=> Adding BicycleTest on a route from mail.ru office to ul. simanova5k2 which does not pass now.

xcode/routing/routing.xcodeproj/project.pbxproj
Корректная сборка routing под iOS.
@VladiMihaylenko PTAL
=> Building routing static lib for ios with new xcode.

xcode/routing/routing.xcodeproj/project.pbxproj
Починка xcode proj.
@igrechuhin PTAL
=> Adding file to xcode project.

xcode/routing/routing.xcodeproj/project.pbxproj
cherry-pick на релиз: https://github.com/mapsme/omim/pull/4310
=> [release-64] Adding file to xcode project.

android/src/com/mapswithme/maps/editor/EditorFragment.java
https://jira.mail.ru/browse/MAPSME-2425
=> [android] Disable editing of continent names

routing/road_graph_router.cpp
https://jira.mail.ru/browse/MAPSME-2423
@mpimenov PTAL
=> [routing] Fixed connectivity checking code.

iphone/Maps/MWMAboutController.mm, iphone/Maps/Mapsme.storyboard
https://jira.mail.ru/browse/MAPSME-2408
=> [ios] Fixed about screen name & data version.

iphone/Maps/Maps.xcodeproj/project.pbxproj
Required for replacing the values in the project on the build server.
=> Enabled "Automatically manage signing"

android/src/com/mapswithme/maps/location/TrackRecorder.java
This path was hard coded, i changed.
=> Removing the hard coded path for gps-tracker.log file.

map/framework.cpp, map/framework.hpp
https://jira.mail.ru/browse/MAPSME-2422
@darina 
@mpimenov 
PTAL
=> [core] Fixed tap restore.

indexer/features_vector.cpp, indexer/features_vector.hpp, indexer/index.cpp, indexer/index.hpp
=> [indexer] Extensions to FeaturesVector.

iphone/Maps/Classes/MapsAppDelegate.mm
https://jira.mail.ru/browse/MAPSME-2458
=> [ios] Fixed Spotlight search.

drape_frontend/backend_renderer.cpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/message_subclasses.hpp, drape_frontend/route_builder.cpp, drape_frontend/route_builder.hpp, drape_frontend/route_shape.hpp
https://jira.mail.ru/browse/MAPSME-2412
=> Route recaching fixed.

data/countries.txt, data/external_resources.txt
=> [planet] New data from 19.09.2016

iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm
https://jira.mail.ru/browse/MAPSME-2464
=> [ios] Attempt to fix iOS 7 crash.

coding/multilang_utf8_string.hpp, generator/restaurants_info/restaurants_info.cpp, generator/restaurants_info/restaurants_info.pro, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, omim.pro
=> Add restaurants_info utility.

iphone/Maps/Classes/MapDownloader/MWMBaseMapDownloaderViewController.mm
https://jira.mail.ru/browse/MAPSME-2411
=> Fixed return to map after migration

android/src/com/mapswithme/maps/editor/EditorHostFragment.java
https://jira.mail.ru/browse/MAPSME-1793
Я там еще слегка код поформатировал, убрал скобочки на весь метод
@alexzatsepin 
@syershov
=> [android] Added newcomers message

map/booking_api.cpp, map/booking_api.hpp
=> Add neutral review. And some more dummy comments.

map/framework.cpp
https://jira.mail.ru/browse/MAPSME-2421
=> Fixed crash in activating of map selection.

android/res/layout-land/layout_nav_bottom_numbers.xml, android/res/layout/layout_nav_bottom_numbers.xml, android/res/values/styles-text.xml
=> [android] Fixed font sizes and margins in the navigation panel

drape_frontend/gps_track_renderer.cpp
https://jira.mail.ru/browse/MAPSME-2500
=> Fixed GPS track recovering.

android/res/layout/edit_bookmark_common.xml
=> Made the bookmark editing field as multiline

android/3rd_party/BottomSheet/build.gradle, android/UnitTests/build.gradle, android/build.gradle
Откатил апдейт грэдл плагина до выяснения обстоятельств:"Почему в студии собирается, а из консоли нет"
=> [android] Reverted the updated gradle plugin

android/gradle.properties
=> [android] Increased app version to 6.4.2

iphone/Maps/MWMHelpController.mm, iphone/Maps/Mapsme.storyboard, iphone/Maps/Statistics/StatisticsStrings.h
https://jira.mail.ru/browse/MAPSME-2493
=> [ios] Updated feedback emails.

map/map_tests/booking_tests.cpp
=> Fix booking_api tests.

iphone/Maps/Classes/MapDownloader/MWMBaseMapDownloaderViewController.mm
https://jira.mail.ru/browse/MAPSME-2411
=> [ios] Fixed return to map after migration.

map/framework.cpp, search/engine.cpp, search/intermediate_result.cpp, search/intermediate_result.hpp, search/pre_ranker.cpp, search/pre_ranker.hpp, search/processor.cpp, search/ranker.cpp, search/ranker.hpp, search/search_engine_pylib/api.cpp, search/search_integration_tests/downloader_search_test.cpp, search/search_integration_tests/interactive_search_test.cpp, search/search_integration_tests/processor_test.cpp, search/search_params.cpp, search/search_params.hpp, search/search_quality/features_collector_tool/features_collector_tool.cpp, search/search_tests_support/test_search_request.cpp
https://jira.mail.ru/browse/MAPSME-2446
@mpimenov PTAL
=> [search] Fixed search in viewport filtering.

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/editor/EditorFragment.java, generator/generator_tests_support/test_feature.cpp, generator/generator_tests_support/test_feature.hpp, indexer/editable_map_object.cpp, indexer/editable_map_object.hpp, indexer/indexer_tests/osm_editor_test.cpp, indexer/osm_editor.cpp, iphone/Maps/Classes/Editor/MWMEditorViewController.mm, search/processor.cpp, search/retrieval.cpp, search/search_integration_tests/search_edited_features_test.cpp, search/search_tests_support/test_results_matching.cpp, search/search_tests_support/test_results_matching.hpp
https://jira.mail.ru/browse/MAPSME-2457
https://jira.mail.ru/browse/MAPSME-2459
@ygorshenin PTAL
=> [editor] [search] Fixed a crash.

base/base_tests/stl_helpers_test.cpp, base/internal/message.hpp, base/stl_helpers.hpp, std/auto_ptr.hpp
@ygorshenin @rokuz @mpimenov PTAL
=> Refactoring SortUnique and EraseIf. Now they can work with deque as well

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, drape/overlay_tree.cpp, drape/overlay_tree.hpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/drape_frontend_tests/user_event_stream_tests.cpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/message.hpp, drape_frontend/message_subclasses.hpp, drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp, drape_frontend/selection_shape.cpp, drape_frontend/selection_shape.hpp, drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp, iphone/Maps/Classes/EAGLView.mm, map/framework.cpp, map/framework.hpp
Центрирование видимой области на карте
https://jira.mail.ru/browse/MAPSME-616
https://jira.mail.ru/browse/MAPSME-656
=> Visible viewport

drape_frontend/drape_engine.cpp
https://jira.mail.ru/browse/MAPSME-2543
=> Fixed cross disappearing

drape_frontend/frontend_renderer.cpp, drape_frontend/render_group.cpp, drape_frontend/render_group.hpp
https://jira.mail.ru/browse/MAPSME-2544
=> Fixed displaying of lines from KML

common.pri
@ygorshenin @syershov @mpimenov
=> Set minimum macosx version to 10.8.

base/base.pro, base/time_samples.cpp, base/time_samples.hpp, base/timer.hpp, indexer/index.hpp, search/categories_cache.cpp, search/categories_cache.hpp, search/geocoder.cpp, search/geocoder.hpp, search/locality_finder.cpp, search/locality_finder.hpp, search/processor.cpp, search/processor.hpp, search/ranker.cpp, search/ranker.hpp, search/search.pro, search/search_integration_tests/pre_ranker_test.cpp, search/search_tests/locality_finder_test.cpp, search/search_tests/locality_selector_test.cpp, search/search_tests/search_tests.pro
https://jira.mail.ru/browse/MAPSME-2200
@mpimenov PTAL
=> [search] Fixed locality matching code.

android/build.gradle
=> [android] Added a new build flavor for Nine store

android/jni/Android.mk, android/jni/com/mapswithme/core/ScopedEnv.hpp, android/jni/com/mapswithme/core/jni_helper.cpp, android/jni/com/mapswithme/core/jni_helper.hpp, android/jni/com/mapswithme/util/HttpClient.cpp, android/src/com/mapswithme/util/HttpClient.java, editor/config_loader.cpp, editor/osm_auth.cpp, editor/user_stats.cpp, platform/apple_location_service.mm, platform/http_client.cpp, platform/http_client.hpp, platform/http_client_apple.mm, platform/http_client_curl.cpp, platform/http_thread_apple.mm, platform/ios_video_timer.mm, platform/platform.pro, platform/platform_ios.mm, platform/platform_mac.mm, routing/online_cross_fetcher.cpp, routing/online_cross_fetcher.hpp, xcode/platform/platform.xcodeproj/project.pbxproj
Http client was copied from alohalytics to our code with small changes
@syershov 
@alexzatsepin 
@VladiMihaylenko
=> [platform] http client

android/build.gradle, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/routing/RoutingPlanController.java
Перенес два коммита из release-64:
[android] Fixed the NPE exception in RoutingPlanController while retreiving the cached routing info	[android] Added a new build flavor for Nine store
=> Cherry-pick from the release-64

3party/opening_hours/CMakeLists.txt, 3party/opening_hours/opening_hours_tests/CMakeLists.txt, CMakeLists.txt, base/CMakeLists.txt, coding/CMakeLists.txt, geometry/CMakeLists.txt, platform/CMakeLists.txt, platform/platform_tests_support/CMakeLists.txt, storage/CMakeLists.txt
Use 
```CC=clang CXX=clang++ cmake ../omim``` to compile on Linux
=> [cmake] Opening hours lib and tests

data/categories.txt, indexer/categories_holder.cpp, indexer/categories_holder.hpp, indexer/indexer_tests/categories_test.cpp
В categories.txt добавлено дополнительное обозначение имен, которые должны быть использованы в пользовательском интерфейсе.
@mpimenov 
@ygorshenin
=> [indexer] added mark for readable names into categories.txt

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuView.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMRoutePreview.mm, iphone/Maps/UIImage+RGBAData.mm
=> [ios] Attempt to fix crush with using OpenGL in background.

docs/CPP_STYLE.md
Current reference to google coding style gives 404.
=> CPP_STYLE: fix reference to google code style guide

android/3rd_party/BottomSheet/build.gradle, android/UnitTests/build.gradle, android/build.gradle
=> [android] Updated Gradle plugin to 2.2.0

editor/changeset_wrapper.cpp
=> [editor] Plural of bench is benches

strings.txt
Строчки, вычитанные Алконостом. 
Прежде чем мы закажем переводы для нового языка, мы должны принять или отклонить английские строки, вычитанные ими.
=> Strings after proof reading in Alconost

search/locality_finder.cpp, search/locality_finder.hpp, search/search_tests/locality_selector_test.cpp
=> [search] Accelerated locality finder.

strings.txt
=> Added string stubs.

drape_frontend/my_position_controller.cpp
https://jira.mail.ru/browse/MAPSME-2668
+Поправлены коэффициенты автомасштабирования.
=> Do not auto scale if speed is unknown.

data/hardcoded_categories.txt, tools/python/clean_strings_txt.py, tools/python/find_untranslated_strings.py
And modifications to find_untranslated_strings to work with it.
To use it (or to check it) go to tools/python and run `python clean_strings_txt.py -s`
=> Strings cleaner

search/locality_finder.cpp, search/locality_finder.hpp
=> [search] LocalityFinder speedup.

data/countries.txt, data/external_resources.txt
Новая планета. По ошибке собрана мастером, но на момент сборки ломающих изменений в генераторе и данных не было, должна подойти к версии 6.4.
На всякий случай, запущена сборка от 10 октября, если релиз задержится. Но это помёржите и проверьте всё равно.
=> [planet] Data from 7.10.2016

base/string_utils.hpp, feature_list/feature_list.cpp
Для одного из фидов нам понадобится адрес сайта для POI.
=> [feature_list] Add website column

data/countries.txt, data/external_resources.txt
На этот раз собрано из этой ветки.
=> [planet] Very fresh data for the release-64 branch

drape/glstate.cpp, drape/glstate.hpp, drape/gpu_program.cpp, drape/gpu_program.hpp, drape/gpu_program_manager.cpp, tools/autobuild/shader_preprocessor.py
https://jira.mail.ru/browse/MAPSME-2676
=> Fixed using of texture slots in shaders

tools/python/find_untranslated_strings.py, tools/python/po_parser.py
This is the format in which we get translated strings from our partners.
The script imports the strings from those files (in a folder specified as a command line argument) into a strings.txt file specified as another command line argument.
=> Added the parser for .po format.

partners_api/partners_api_tests/uber_tests.cpp, partners_api/uber_api.cpp, partners_api/uber_api.hpp
Изменил тип идентификатора реквеста с size_t на uint64_t, также заметил и пофиксил потенциальную проблему при уничтожении объекта уберапи. Немного подправил тест чтобы проверить корректность уничтожения.
@ygorshenin 
@syershov
=> [core] uber additional changes

base/string_utils.cpp, base/string_utils.hpp, generator/feature_builder.cpp, generator/feature_builder.hpp, generator/generator_tests_support/test_feature.cpp, indexer/ftypes_matcher.hpp, map/framework.cpp, search/categories_cache.cpp, search/categories_cache.hpp, search/everywhere_search_params.hpp, search/geocoder.cpp, search/geocoder.hpp, search/geocoder_context.hpp, search/hotels_filter.cpp, search/hotels_filter.hpp, search/processor.cpp, search/processor.hpp, search/search.pro, search/search_integration_tests/processor_test.cpp, search/search_integration_tests/smoke_test.cpp, search/search_params.hpp, search/viewport_search_params.hpp
=> [search] Implemented hotels filter.

data/countries.txt, data/external_resources.txt
Временно скопируем планету в мастер, чтобы было удобно переключаться между версиями в тестировании.
=> [planet] Data from 10.10.2016 built with release-64 for the master br.

.clang-format, android/jni/com/mapswithme/maps/SearchEngine.cpp, android/src/com/mapswithme/maps/routing/SearchWheel.java, android/src/com/mapswithme/maps/search/HotelsFilter.java, android/src/com/mapswithme/maps/search/SearchEngine.java, android/src/com/mapswithme/maps/search/SearchFragment.java, map/framework.cpp, search/hotels_filter.cpp, search/hotels_filter.hpp, search/search_tests/hotels_filter_test.cpp, search/search_tests/search_tests.pro
=> [search] JNI layer for HotelsFilter.

drape_frontend/user_mark_shapes.cpp
https://jira.mail.ru/browse/MAPSME-2674
=> Fixed bookmark displaying

drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/text_layout.cpp, drape_frontend/visual_params.cpp, drape_frontend/visual_params.hpp, map/framework.cpp, map/framework.hpp
https://jira.mail.ru/browse/MAPSME-2730
=> Fonts scaling.

.gitignore, data/categories.txt, tools/python/categories_converter.py, tools/python/po_parser.py
1) to strings txt, so that we can send it to our translation partners.
2) for sorting categories.txt so that it is easier to work with, esp with future additions to it (if any)
3) for merging new strings from po files into a given categories.txt file
=> A script for converting categories.txt:

android/jni/com/mapswithme/maps/SearchEngine.cpp, iphone/Maps/Classes/Search/MWMSearch.mm, map/framework.cpp, search/emitter.hpp, search/engine.cpp, search/hotels_classifier.cpp, search/hotels_classifier.hpp, search/result.cpp, search/result.hpp, search/viewport_search_callback.cpp, search/viewport_search_callback.hpp, search/viewport_search_params.hpp
@mpimenov @alexzatsepin @igrechuhin PTAL
=> [search] HotelsClassifier can be used on the UI side now.

partners_api/uber_api.cpp
=> uber fix coordinates adjustment

android/src/com/mapswithme/maps/routing/RoutingController.java
https://jira.mail.ru/browse/MAPSME-2721
=> [android] Fixed passing the coordinates into core to build deep link

tools/python/opentable_restaurants.py, tools/unix/generate_planet.sh
Маленький косяк с параметрами запуска opentable.py.
=> [generator] Fix parameter name

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Fabric crash link - https://www.fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/57e4d0270aeb16625ba3828c
=> [android] Fixed NPE in PlacePageView.togglelsBookmark method

android/src/com/mapswithme/maps/editor/data/HoursMinutes.java
=> [android] Fix am/pm

partners_api/partners_api_tests/booking_tests.cpp
Сломались тесты, потому что в гостинице закончились номера. Заменил в тесте гостиницу на «Измайлово Гамма», в котором тысяча номеров.
=> [tests] Replace hotel id for tests

android/res/layout/menu_buttons_line.xml
https://jira.mail.ru/browse/MAPSME-2291
=> [android] Added id to menu button

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/routing/RoutingController.java
=> [android] Added saving the Uber panel during rotation

android/src/com/mapswithme/maps/routing/NavigationController.java, android/src/com/mapswithme/maps/routing/RoutingController.java
@milchakov @mpimenov @bykoianko
=> [android] Localized time units in routing/uber panel

partners_api/booking_api.cpp, partners_api/booking_api.hpp, partners_api/partners_api_tests/booking_tests.cpp
https://jira.mail.ru/browse/MAPSME-2748
И тест не починил («Измайлово Гамма» сегодня под завязку), и сборку сломал. Ну как так.
=> [tests] Fix booking tests again

editor/editor_config.cpp
=> [editor] Fix type priority in editor config

android/res/layout-land/place_page_details.xml, android/res/layout/fragment_fullscreen_image.xml, android/res/layout/item_bookmark_category_create.xml, android/res/layout/place_page.xml, android/res/layout/place_page_details.xml, android/res/layout/toolbar_elevated.xml, android/res/values/styles.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java, android/src/com/mapswithme/maps/gallery/FullScreenGalleryFragment.java, android/src/com/mapswithme/maps/widget/ObservableScrollView.java, android/src/com/mapswithme/maps/widget/placepage/BasePlacePageAnimationController.java, android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java, android/src/com/mapswithme/maps/widget/placepage/EditBookmarkFragment.java, android/src/com/mapswithme/maps/widget/placepage/LeftPlacePageAnimationController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, map/booking_api.cpp
Added a new state of the Place Page Card - FULLSCREEN.
DETAILS state - 70% of screen height
In FULLSCREEN card condition - 100% of screen height
When scrolling in FULLSCREEN mode appears Toolbar.
Fixed some minor bugs.
=> [android] New Place Page opening and scrolling behavior

tracking/reporter.cpp, tracking/tracking_tests/reporter_test.cpp
@alexzatsepin @igrechuhin PTAL
=> add required accuracy for gps reporter

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm, iphone/Maps/Classes/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-2762
=> [ios] Spinner for taxi.

iphone/Maps/Classes/MWMOpeningHoursCell.h, iphone/Maps/Classes/MWMOpeningHoursCell.mm
https://jira.mail.ru/browse/MAPSME-2770
=> [ios] Fixed crash with opening hours.

android/jni/com/mapswithme/maps/Framework.cpp, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMTaxiPreviewDataSource.mm, partners_api/partners_api_tests/uber_tests.cpp, partners_api/uber_api.cpp, partners_api/uber_api.hpp
Доп коллбэк на случай недоступности убера
@mpimenov 
@syershov
=> [core] Error callback for uber api

android/jni/com/mapswithme/core/jni_helper.cpp, android/jni/com/mapswithme/core/jni_helper.hpp, android/jni/com/mapswithme/platform/Platform.cpp, android/src/com/mapswithme/maps/location/SocketWrapper.java
- Added insecure implementation of ssl socket to make debugging process work with self-signed certificates
- Replaced the unique id with installation(aloha) id 
@syershov @dobriy-eeh @mpimenov PTAL
=> [android] Added self-signed cert support

android/src/com/mapswithme/util/Utils.java
=> [android] Added FLAG_NEW_TASK to uber launch

android/3rd_party/BottomSheet/build.gradle, android/UnitTests/build.gradle, android/build.gradle
=> [android] Updated gradle plugin to 2.2.2

android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/routing/RoutingPlanController.java
=> [android] Bound the toolbar progress bar to uber info request

drape_frontend/apply_feature_functors.cpp, drape_frontend/backend_renderer.cpp, drape_frontend/backend_renderer.hpp, drape_frontend/circle_shape.cpp, drape_frontend/circle_shape.hpp, drape_frontend/drape_api.cpp, drape_frontend/drape_api.hpp, drape_frontend/drape_api_builder.cpp, drape_frontend/drape_api_builder.hpp, drape_frontend/drape_api_renderer.cpp, drape_frontend/drape_api_renderer.hpp, drape_frontend/drape_engine.hpp, drape_frontend/drape_frontend.pro, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/message.hpp, drape_frontend/message_subclasses.hpp, map/framework.cpp, map/framework.hpp
https://jira.mail.ru/browse/MAPSME-2791
=> Added Drape API

iphone/Maps/Classes/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-2795
=> [ios] Atempt to fix crash in GL background.

android/src/com/mapswithme/util/HttpClient.java
=> [android] Fix authorization error

iphone/Maps/Classes/MapDownloader/DataSources/MWMMapDownloaderExtendedDataSource.mm, iphone/Maps/Classes/MapDownloader/DataSources/MWMMapDownloaderExtendedDataSourceWithAds.mm
https://jira.mail.ru/browse/MAPSME-2802
=> [ios] Fixed extra section duplication.

iphone/Maps/Classes/Share/MWMShareActivityItem.mm
https://jira.mail.ru/browse/MAPSME-2705
=> [ios] Fixed my location sharing from PPP.

iphone/Maps/Classes/MWMEditBookmarkController.mm
https://jira.mail.ru/browse/MAPSME-2818
=> [ios] Fixed crash while editing bookmark's category.

iphone/Maps/Classes/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-2595
https://jira.mail.ru/browse/MAPSME-2718
=> [ios] Fixed «route to» with no current location.

iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.h, iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.h, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm, iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm, iphone/Maps/Classes/CustomAlert/DownloadTransitMapsAlert/MWMDownloadTransitMapAlert.mm, iphone/Maps/Classes/CustomAlert/FacebookAlert/MWMFacebookAlert.mm, iphone/Maps/Classes/CustomAlert/LocationAlert/MWMLocationAlert.mm, iphone/Maps/Classes/CustomAlert/MWMEditorViralAlert.mm, iphone/Maps/Classes/CustomAlert/MWMOsmAuthAlert.mm, iphone/Maps/Classes/CustomAlert/MWMPlaceDoesntExistAlert.mm, iphone/Maps/Classes/CustomAlert/RateAlert/MWMRateAlert.mm, iphone/Maps/Classes/CustomAlert/RoutingDisclaimerAlert/MWMRoutingDisclaimerAlert.mm
https://jira.mail.ru/browse/MAPSME-2663
=> [ios] Fixed duplicate alerts display issue.

iphone/Maps/Classes/MWMBookmarkCell.mm
https://jira.mail.ru/browse/MAPSME-2805
https://jira.mail.ru/browse/MAPSME-2792
=> [ios] Fixed recursion in MWMBookmarkCell.

iphone/Maps/MWMAboutController.mm, iphone/Maps/MWMAboutControllerHeader.xib, iphone/Maps/Maps.xcodeproj/project.pbxproj, iphone/Maps/Mapsme.storyboard
https://jira.mail.ru/browse/MAPSME-2513
https://jira.mail.ru/browse/MAPSME-2620
=> [ios] Fixed settings «about» section layout.

data/countries.txt, data/external_resources.txt
=> [planet] New data from 26.10.2016

routing/routing_benchmarks/bicycle_routing_tests.cpp
=> Renaming a test.

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Hide rating if price is empty.
@alexzatsepin 
@mpimenov
=> [android] Hide rating if price is empty.

android/res/layout/fragment_auth_editor.xml
Fix profile verified changes text color.
@alexzatsepin 
@mpimenov
=> [android] Fix profile verified changes text color.

android/src/com/mapswithme/maps/location/SocketWrapper.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
=> [DNM] [android] Enabled ssl cert checking. Disabled the rich page for Booking.

android/res/layout-land/activity_map.xml, android/res/layout-land/layout_nav_search.xml, android/res/layout-w1020dp/activity_map.xml, android/res/layout/activity_map.xml, android/res/layout/layout_nav.xml, android/res/layout/layout_nav_search.xml, android/src/com/mapswithme/maps/routing/NavigationController.java, android/src/com/mapswithme/maps/routing/SearchWheel.java
Fixed: search button in navigation mode moved under the fade view.
@alexzatsepin 
@mpimenov
=> [android] Move navigation search button under the fade view.

android/src/com/mapswithme/maps/routing/NavigationController.java, android/src/com/mapswithme/maps/routing/SearchWheel.java
Closing the interactive search when the navigation menu is hidden.
@alexzatsepin 
@mpimenov
=> [android] clearing search results when the navigation session is closed.

iphone/Maps/Classes/MWMBookmarkTitleCell.xib
https://jira.mail.ru/browse/MAPSME-2183
=> [ios] Fixed capitalization.

data/categories.txt
=> categories.txt: hu:amenity=hunting_stand Vadászles

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.mm
https://jira.mail.ru/browse/MAPSME-2334
=> [ios] Fixed p2p button selected state.

iphone/Maps/Classes/MWMPlacePageButtonCell.mm, iphone/Maps/Classes/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-2093
=> [ios] Fixed place page buttons.

search/search_tests/locality_finder_test.cpp
Replaced one with the other to fix the search tests (and make Master green again)
=> Changed Rome to Vatican City

iphone/Maps/Classes/Share/MWMShareActivityItem.mm
https://jira.mail.ru/browse/MAPSME-2702
=> [ios] Returned ge0 sharing links format.

iphone/Maps/Classes/CustomViews/MapViewControls/Welcome/Welcome.storyboard
https://jira.mail.ru/browse/MAPSME-2853
=> [ios] Increased max image height to 280.

android/src/com/mapswithme/maps/editor/ProfileFragment.java
Added alert dialog on user logout.
@alexzatsepin 
@mpimenov
=> [android] Alert dialog on user logout

iphone/Maps/Classes/CustomViews/NavigationDashboard/Sound/MWMTextToSpeech.mm
https://jira.mail.ru/browse/MAPSME-2622
=> [ios] Fixed tts enabled & active statuses handling.

android/src/com/mapswithme/maps/editor/ProfileFragment.java
=> [android][cherry-pick] Added alert dialog on user logout

partners_api/partners_api_tests/uber_tests.cpp
=> Uber tests fix

iphone/Maps/Classes/MapsAppDelegate.mm, iphone/Maps/Statistics/Statistics.mm
https://jira.mail.ru/browse/MAPSME-2866
=> [ios] Fixed statistics initialization.

partners_api/partners_api_tests/uber_tests.cpp
=> [RELEASE ONLY] Uber tests fix

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/location/GPSCheck.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/routing/NavigationController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, platform/measurement_utils.cpp, platform/measurement_utils.hpp
Fixed bottom menu visibility after geo uri processing(https://jira.mail.ru/browse/MAPSME-2583).
Fixed PP my position altitude and speed display(http://jira.65apps.com/browse/MAP-52).
PP lat lng copy with semicolon(http://jira.65apps.com/browse/MAP-54).
Fixed on map search results(https://jira.mail.ru/browse/MAPSME-2860).
Force restart location update when user activate GPS(https://jira.mail.ru/browse/MAPSME-2244).
@alexzatsepin
@mpimenov
=> [android] [cherry-pick] bug fixes

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.xib, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMTaxiPreviewCell.xib, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMiPadRoutePreview.xib
https://jira.mail.ru/browse/MAPSME-2869
=> [ios] Fixed taxi view coloring in night mode.

iphone/Maps/Classes/Location/MWMLocationManager.mm
https://jira.mail.ru/browse/MAPSME-2822
=> Fixed false positioning in case of location turning off

platform/platform.pro
=> [build] Fixed linux build.

CMakeLists.txt, tracking/pytracking/CMakeLists.txt
@therearesomewhocallmetim PTAL
=> Fix cmake build

search/hotels_classifier.cpp
=> [search] Decreased threshold for hotels.

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.xib
https://jira.mail.ru/browse/MAPSME-2884
=> [ios] Fixed layout of go button.

android/res/values/themes-base.xml, android/res/values/themes.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/base/BaseMwmExtraTitleActivity.java, android/src/com/mapswithme/maps/base/BaseMwmFragmentActivity.java, android/src/com/mapswithme/maps/base/BaseToolbarActivity.java, android/src/com/mapswithme/maps/gallery/FullScreenGalleryActivity.java, android/src/com/mapswithme/maps/routing/NavigationController.java, android/src/com/mapswithme/maps/routing/RoutingPlanInplaceController.java, android/src/com/mapswithme/maps/settings/SettingsActivity.java, android/src/com/mapswithme/maps/widget/ToolbarController.java, android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java, android/src/com/mapswithme/maps/widget/placepage/EditBookmarkFragment.java, android/src/com/mapswithme/maps/widget/placepage/EditDescriptionFragment.java, android/src/com/mapswithme/maps/widget/placepage/LeftPlacePageAnimationController.java, android/src/com/mapswithme/util/UiUtils.java
Transparent statusbar(http://jira.65apps.com/browse/MAP-69).
@alexzatsepin 
@mpimenov
=> [android] Transparent statusbar.

data/countries.txt, data/external_resources.txt
Шар земной. Данные пока не разлиты по серверам.
=> [planet] Fresh data from 5.11.2016

iphone/Maps/Classes/CustomAlert/DownloadTransitMapsAlert/MWMDownloadTransitMapAlert.mm, iphone/Maps/Classes/CustomAlert/DownloadTransitMapsAlert/MWMDownloaderDialogHeader.h, iphone/Maps/Classes/CustomAlert/DownloadTransitMapsAlert/MWMDownloaderDialogHeader.mm
https://jira.mail.ru/browse/MAPSME-2865
=> [ios] Fixed transit alert storage observing.

iphone/Maps/Classes/Migration/MWMMigrationView.mm, iphone/Maps/Mapsme.storyboard
https://jira.mail.ru/browse/MAPSME-2879
=> [ios] Fixed migration layout.

iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm
https://jira.mail.ru/browse/MAPSME-2878
=> [ios] Fixed multiple alerts display.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/widget/menu/MainMenu.java
Fixed main menu restore state(https://jira.mail.ru/browse/MAPSME-2538).
@alexzatsepin 
@mpimenov
=> [android] Fixed main menu restore state.

drape/shaders/path_symbol_vertex_shader.vsh, drape_frontend/path_symbol_shape.cpp
https://jira.mail.ru/browse/MAPSME-2891
=> Fixed directional arrows rendering

editor/editor_tests/opening_hours_ui_test.cpp, editor/opening_hours_ui.cpp
https://jira.mail.ru/browse/MAPSME-2856
@mgsergio 
@mpimenov
=> [editor] Opening hours by default were changed

base/base.pro, base/base_tests/base_tests.pro, base/base_tests/levenshtein_dfa_test.cpp, base/levenshtein_dfa.cpp, base/levenshtein_dfa.hpp
=> [base] Levenshtein DFA.

android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java
Fixed Place Page opening behavior(https://jira.mail.ru/browse/MAPSME-2843).
@alexzatsepin 
@mpimenov
=> [android] Fixed Place Page opening behavior

iphone/Maps/Classes/CustomViews/MapViewControls/Search/MWMSearchChangeModeView.mm, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TableView/MWMSearchCommonCell.h, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TableView/MWMSearchCommonCell.mm, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TableView/MWMSearchCommonCell.xib, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TableView/MWMSearchShowOnMapCell.xib, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TableView/MWMSearchSuggestionCell.h, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TableView/MWMSearchSuggestionCell.mm, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TableView/MWMSearchSuggestionCell.xib, iphone/Maps/Classes/CustomViews/MapViewControls/Search/TableView/MWMSearchTableViewController.mm
https://jira.mail.ru/browse/MAPSME-2790
=> [ios] Updated search cells layout.

iphone/Maps/MWMAboutControllerHeader.xib
https://jira.mail.ru/browse/MAPSME-2922
=> [ios] Fixed layout issue.

android/res/layout/fragment_search.xml, android/res/layout/toolbar_with_search_no_elevation.xml, android/res/values/styles.xml
Removed elevation from toolbar(http://jira.65apps.com/browse/MAP-74).
@alexzatsepin 
@mpimenov
=> [android] Removed elevation from toolbar

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Fixed "Hotel More" button visibility(http://jira.65apps.com/browse/MAP-77).
@alexzatsepin 
@mpimenov
=> [android] Fixed "Hotel More" button visibility.

android/res/layout/downloader_item_header.xml, android/res/layout/fragment_downloader.xml, android/res/layout/fragment_migrate.xml, android/res/values/themes.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/base/BaseActivity.java, android/src/com/mapswithme/maps/base/BaseMwmFragmentActivity.java, android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesActivity.java, android/src/com/mapswithme/maps/bookmarks/BookmarkListActivity.java, android/src/com/mapswithme/maps/gallery/FullScreenGalleryActivity.java, android/src/com/mapswithme/maps/search/SearchActivity.java, android/src/com/mapswithme/maps/settings/SettingsActivity.java, android/src/com/mapswithme/util/ThemeUtils.java
Background color fix(http://jira.65apps.com/browse/MAP-76).
@alexzatsepin 
@mpimenov
=> [android] Background color fix.

iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm, iphone/Maps/Classes/Location/MWMLocationManager.mm, iphone/Maps/Classes/MapViewController.h, iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-2903
=> [ios] Fixed location alert display logic.

android/res/layout/place_page_bookmark_details.xml, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
@milchakov @mpimenov PTAL please
=> Mapsme 2137 Added HTML bookmark support

android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
https://jira.mail.ru/browse/MAPSME-2939
=> Setting bookmark fixed.

iphone/Maps/Classes/MWMEditBookmarkController.mm
https://jira.mail.ru/browse/MAPSME-2932
=> [ios] Fixed crush due bookmark's category changing.

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
https://jira.mail.ru/browse/MAPSME-2896
=> [ios] Fixed taxi view on iPad.

android/src/com/mapswithme/util/sharing/MapObjectShareable.java
=> [android] Added http link while sharing the bookmark

android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java
Extend Place Page view with status bar. Fixed click detection in FULLSCREEN state(https://jira.mail.ru/browse/MAPSME-2955).
@alexzatsepin 
@mpimenov
=> [android] Extend Place Page view with status bar.

iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.h, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm, iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.h, iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm, iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert_Protected.h, iphone/Maps/Classes/CustomAlert/LocationNotFoundAlert/MWMLocationNotFoundAlert.h, iphone/Maps/Classes/CustomAlert/LocationNotFoundAlert/MWMLocationNotFoundAlert.mm, iphone/Maps/Classes/MapViewController.mm, iphone/Maps/Maps.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-2350
=> [MAPSME-2350] [ios] Fixed no location dialog.

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationInfoView.mm, iphone/Maps/Classes/Widgets/MWMMapWidgets.h, iphone/Maps/Classes/Widgets/MWMMapWidgets.mm
https://jira.mail.ru/browse/MAPSME-2327
https://jira.mail.ru/browse/MAPSME-2381
=> [MAPSME-2327,MAPSME-2381] [ios] Fixed compass location.

android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java
Fixed Place Page gesture detection(https://jira.mail.ru/browse/MAPSME-2970).
@alexzatsepin 
@mpimenov
=> [android] Fixed Place Page bookmark delete.

iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm, iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert_Protected.h, iphone/Maps/Classes/MWMBasePlacePageView.mm, iphone/Maps/Classes/MWMPlacePageManager.mm, iphone/Maps/Classes/MapDownloader/MWMBaseMapDownloaderViewController.mm, iphone/Maps/Classes/Storage/MWMStorage.h, iphone/Maps/Classes/Storage/MWMStorage.mm, iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
https://jira.mail.ru/browse/MAPSME-1200
=> [MAPSME-1200] [ios] Fixed retry download.

base/CMakeLists.txt, base/base.pro, base/base_tests/CMakeLists.txt, base/base_tests/base_tests.pro, base/base_tests/levenshtein_dfa_test.cpp, base/base_tests/uni_string_dfa_test.cpp, base/dfa_helpers.hpp, base/levenshtein_dfa.hpp, base/string_utils.hpp, base/uni_string_dfa.cpp, base/uni_string_dfa.hpp, search/feature_offset_match.hpp, search/retrieval.cpp
=> [search] Switch to DFAs in search index retrieval

base/base_tests/levenshtein_dfa_test.cpp, base/levenshtein_dfa.cpp, base/levenshtein_dfa.hpp, search/categories_cache.cpp, search/categories_cache.hpp, search/categories_set.hpp, search/feature_offset_match.hpp, search/geocoder.cpp, search/geocoder.hpp, search/processor.cpp, search/query_params.cpp, search/query_params.hpp, search/retrieval.cpp, search/retrieval.hpp, search/search_integration_tests/processor_test.cpp
=> [search] Added fuzzy search (up to 2 errors).

search/geocoder.cpp
=> [search] Fixed UB in search query cleanup.

map/framework.cpp, map/traffic_manager.cpp, map/traffic_manager.hpp, storage/country_info_getter.cpp, storage/country_info_getter.hpp, storage/storage_tests/country_info_getter_test.cpp
1) Добавлена реализация пересечения вьюпорта и границ mwm-ок. 
Алгоритм следующий:
- Тест bounding box'ов
- Тест пересечения границ ректа и границ многоугольника
- Тест попадания центра ректа внутрь многоугольника.
Сложность соизмерима с GetRegionCountryId
2) Добавлен запрос пробок по таймеру
3) Исключены повторные запросы пробок раньше времени.
P.S. Очистка всех кэшей - следующая задача, не входящая в данный PR
=> Added getting mwms by rect

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Fixed download button visibility in Place Page when the navigation session active(https://jira.mail.ru/browse/MAPSME-2658).
@alexzatsepin 
@mpimenov
=> [android] Place Page download button visibility

android/src/com/mapswithme/maps/widget/RotateDrawable.java
Fixed RotateDrawable onBoundsChange behavior(https://jira.mail.ru/browse/MAPSME-2852).
@alexzatsepin 
@mpimenov
=> [android] Fixed RotateDrawable onBoundsChange behavior.

android/res/layout/routing_plan.xml
Added elevation to the routing plan menu(https://jira.mail.ru/browse/MAPSME-2355).
@alexzatsepin 
@mpimenov
=> [android] Added elevation to the routing plan menu.

iphone/Maps/Classes/MWMPlacePageEntity.mm, map/framework.cpp, map/place_page_info.cpp, map/place_page_info.hpp
@alexzatsepin 
@VladiMihaylenko 
@Zverik
=> [core] Banners dummy implementation

android/res/values-w1020dp/dimens.xml, android/res/values/dimens.xml, android/src/com/mapswithme/maps/MapFragment.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/PanelAnimator.java, android/src/com/mapswithme/util/UiUtils.java
Added compass y offset in landscape navigation mode(https://jira.mail.ru/browse/MAPSME-2476).
@alexzatsepin 
@mpimenov
=> [android] Added compass y offset in landscape navigation mode

android/src/com/mapswithme/maps/location/PlatformSocket.java
=> [android] Fixed the PlatformSocket time measurement

android/assets/resources-ldpi_clear, android/assets/resources-ldpi_dark, android/assets/resources-ldpi_legacy, android/src/com/mapswithme/util/sharing/SharingHelper.java
Fixed shared bookmark category name(https://jira.mail.ru/browse/MAPSME-1422).
@alexzatsepin 
@mpimenov
=> [android] Fixed shared bookmark category name

drape/overlay_tree.cpp
https://jira.mail.ru/browse/MAPSME-3033
=> Do not select streets on tap.

android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java, android/src/com/mapswithme/maps/downloader/DownloaderFragment.java, android/src/com/mapswithme/util/statistics/MytargetHelper.java
В данном PR:
1. Небольшое изменение в DownloaderAdapter'e (загрузчике) относительно крэша https://www.fabric.io/mapsme/android/apps/com.mapswithme.maps.pro.debug/issues/5834396a0aeb16625b27254d/sessions/583440EA02560001500620FEBD333B61_4a7e37e1b9124b1e84e131a104a94ce8_0_v1 . Крэш воспроизвести не получается, поэтому изменения в коде сделанные ни факт, что решают проблему. Поэтому я добавил еще логирование дополнительное в фабрик, на случай если крэш все таки не залечился. https://jira.mail.ru/browse/MAPSME-3023
2. Добавил подсчет статистике показов myTarget banneroв - https://jira.mail.ru/browse/MAPSME-2964
@mpimenov @milchakov
=> Mapsme 3023 dowloader crash

android/res/values/themes-base.xml, android/res/values/themes.xml, android/src/com/mapswithme/maps/base/BaseMwmFragmentActivity.java, android/src/com/mapswithme/maps/downloader/DownloaderAdapter.java, android/src/com/mapswithme/maps/downloader/DownloaderFragment.java, android/src/com/mapswithme/maps/location/PlatformSocket.java, android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java, iphone/Maps/Categories/UIKitCategories.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMTaxiPreviewDataSource.mm, iphone/Maps/Classes/Editor/MWMEditorViewController.mm, iphone/Maps/Classes/MWMPlacePageManager.mm, iphone/Maps/Classes/MWMPlacePageViewManager.mm, iphone/Maps/Classes/Routing/MWMRouter.mm, iphone/Maps/Maps.xcodeproj/project.pbxproj, iphone/Maps/Statistics/Statistics.mm, iphone/Maps/Statistics/StatisticsStrings.h, xcode/common.xcconfig
@igrechuhin @alexzatsepin PTAL
=> Unique release-65 commit to master.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/NavigationButtonsAnimationController.java, android/src/com/mapswithme/maps/routing/RoutingPlanController.java, android/src/com/mapswithme/maps/search/FloatingSearchToolbarController.java, android/src/com/mapswithme/maps/widget/menu/MyPositionButton.java, android/src/com/mapswithme/maps/widget/placepage/BasePlacePageAnimationController.java, android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/Animations.java
Place Page affects navigation buttons.
Hides "My Position" button in follow and rotate mode when the navigation session active.
In landscape orientation if not placed 3 buttons only remains my position button.
@alexzatsepin 
@mpimenov
=> [android] Navigation buttons animations.

iphone/Maps/Classes/MapDownloader/MWMBaseMapDownloaderViewController.mm
https://jira.mail.ru/browse/MAPSME-3043
=> [MAPSME-3043] [ios] Changed «update all» button display logic.

data/sound-strings/ro.json/localize.json, sound/tts/sound.txt
В #4402 приняли поправки для румынского языка, но забыли пересобрать файлы.
=> [tts] Rebuilt Romanian TTS

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
https://jira.mail.ru/browse/MAPSME-3072
=> [MAPSME-3072] [ios] Fixed search close bug on iPad.

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/editor/Editor.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java, android/src/com/mapswithme/maps/editor/Editor.java, android/src/com/mapswithme/maps/editor/EditorActivity.java, android/src/com/mapswithme/maps/editor/EditorHostFragment.java, map/framework.cpp, map/framework.hpp
[android] Fixed editor restore state(https://jira.mail.ru/browse/MAPSME-2972).
@alexzatsepin 
@mpimenov
=> [android] Fixed editor restore state.

tools/python/booking_hotels.py
Валимся на пустых координатах. Непонятно, откуда они там.
=> [booking] Fix processing of empty coordinates in China

tools/unix/generate_planet.sh
Последние несколько сборок ломались из-за проблем со скачиванием букинга или из-за забытого файла дорог. Я добавил ключ для указания пути к промежуточным файлам предыдущей сборки, чтобы сломанные файлы брать оттуда.
Также скрипт теперь ожидает 400 гигов свободного места, а не 250: уже пару раз за осень сборка вываливалась по нехватке места. Ну и оказалось, что проверка на свободное место не работала вообще.
=> [generator] A failsafe for missing files

drape_frontend/apply_feature_functors.cpp, drape_frontend/apply_feature_functors.hpp, drape_frontend/area_shape.cpp, drape_frontend/area_shape.hpp, drape_frontend/rule_drawer.cpp
https://jira.mail.ru/browse/MAPSME-2985
=> Added outline min zoom level

drape_frontend/gui/ruler.cpp, drape_frontend/gui/ruler_helper.cpp, drape_frontend/gui/ruler_helper.hpp
https://jira.mail.ru/browse/MAPSME-3093
=> Show the ruler only during scaling.

data/countries.txt, data/external_resources.txt
Свежачок (на самом деле, нет).
=> [planet] Relatively fresh planet data from 23.11.2016

routing/CMakeLists.txt
Which had broken by someone who added files to a *.pro file, but not to the corresponding CMakeLists.txt
=> Fixed cmake compilation

android/jni/com/mapswithme/maps/Framework.cpp, iphone/Maps/Classes/MWMPlacePageData.mm, iphone/Maps/Classes/MWMPlacePageEntity.mm, map/framework.cpp, map/framework.hpp, platform/network_policy.hpp, platform/platform.pro, xcode/platform/platform.xcodeproj/project.pbxproj
Сделал заглушечную реализацию с решателем. 
Мне не нравится.
@alexzatsepin 
@igrechuhin 
@mgsergio 
@ygorshenin
=> [core] Remote call solver dummy

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.mm, iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm, iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtons.mm, iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.h, iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm, iphone/Maps/Classes/MapViewController.mm, iphone/Maps/Classes/Routing/MWMRouter.h, iphone/Maps/Classes/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-3077
=> [MAPSME-3077] [ios] Updated traffic & location buttons layout & visibility.

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.h, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm, iphone/Maps/Classes/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-3035
=> [MAPSME-3035] [ios] Fixed taxi datasource cleanup.

iphone/Maps/Maps.xcodeproj/project.pbxproj, iphone/Maps/Maps.xcodeproj/xcshareddata/xcschemes/scheme_cmMAPS.ME.xcscheme, tools/autobuild/ios_cmake.sh
Modifications needed for building betas and debugs on the CI server.
=> Cmake ios autobuild

iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm, iphone/Maps/Classes/LocalNotificationManager.mm, iphone/Maps/Classes/MWMPPView.h, iphone/Maps/Classes/MWMPPView.mm, iphone/Maps/Classes/MWMPlacePageLayout.mm, iphone/Maps/Classes/MWMPlacePageLayoutImpl.h, iphone/Maps/Classes/MWMPlacePageManager.mm, iphone/Maps/Classes/MWMiPadPlacePageLayoutImpl.mm, iphone/Maps/Classes/MWMiPhonePlacePageLayoutImpl.mm, iphone/Maps/Classes/MapDownloader/MWMBaseMapDownloaderViewController.mm, iphone/Maps/Classes/MapsAppDelegate.mm, iphone/Maps/Classes/Migration/MWMMigrationViewController.mm, iphone/Maps/Classes/Routing/MWMRouter.mm, iphone/Maps/Classes/Storage/MWMStorage.h, iphone/Maps/Classes/Storage/MWMStorage.mm, iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
https://jira.mail.ru/browse/MAPSME-3126
=> [MAPSME-3126] [ios] Fixed PP opening bug.

android/assets/banners.txt, android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/script/replace_links.bat, indexer/banners.cpp, map/place_page_info.cpp
Добавил файл `banners.txt` в сборку андроида, также проверяю на его наличие и убрал название значка по умолчанию.
=> [banners] Fix android build, remove default icon

map/traffic_manager.hpp
=> [android] Fixed the thread in traffic manager

indexer/banners.cpp, indexer/indexer_tests/banners_test.cpp
My bad, после рефакторинга не проверил тесты.
=> [banners] Fix banners tests

drape_frontend/frontend_renderer.cpp, drape_frontend/gui/layer_render.cpp, drape_frontend/gui/layer_render.hpp, drape_frontend/my_position_controller.cpp
https://jira.mail.ru/browse/MAPSME-3139
=> Changed my-position button behaviour in routing, hid compass and ruler in routing

android/res/values-da/strings.xml, android/res/values-fi/strings.xml, iphone/Maps/da.lproj/Localizable.strings, iphone/Maps/fi.lproj/Localizable.strings, strings.txt
A rebase of https://github.com/mapsme/omim/pull/4205 by https://github.com/jleh
=> Str finnish

android/src/com/mapswithme/maps/bookmarks/data/Banner.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
=> [android] Added the link following to the banners

android/jni/Android.mk, map/framework.cpp, map/map_tests/map_tests.pro, map/traffic_manager.cpp, map/traffic_manager.hpp, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/index_graph.cpp, routing/index_graph_starter.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/routing_test_tools.hpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/applying_traffic_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/routing_tests.pro, routing/single_mwm_router.cpp, routing/single_mwm_router.hpp, traffic/traffic.pro, traffic/traffic_cache.cpp, traffic/traffic_cache.hpp, traffic/traffic_info.cpp, traffic/traffic_info.hpp, traffic/traffic_info_getter.cpp, traffic/traffic_info_getter.hpp
Учет пробок при прокладке маршрута по index graph и тесты.
Пока просто утяжеляю сегменты обратно пропорционально kSpeedGroupThresholdPercentage.
@rokuz Раскраску маршрута я лучше сделаю отдельным PR. А то этот и так довольно разросся.
@rokuz @ygorshenin @dobriy-eeh @mpimenov PTAL
=> [routing] Applying traffic jam on index graph

routing/routing_integration_tests/CMakeLists.txt, routing/routing_tests/CMakeLists.txt, traffic/CMakeLists.txt
@therearesomewhocallmetim PTAL
=> CMake build fix.

partners_api/partners_api_tests/uber_tests.cpp, partners_api/uber_api.cpp, partners_api/uber_api.hpp
Свел тест к проверке того, что все поля в загруженных продуктах заполнены
@ygorshenin
=> Uber tests

coding/CMakeLists.txt, coding/coding.pro, coding/coding_tests/CMakeLists.txt, coding/coding_tests/coding_tests.pro, coding/coding_tests/zlib_test.cpp, coding/zlib.cpp, coding/zlib.hpp
=> [coding] ZLib wrappers.

defines.hpp, generator/generate_info.hpp, generator/generator_tool/generator_tool.cpp, generator/osm_source.cpp, tools/unix/generate_planet.sh, tools/unix/generate_planet_routing.sh
Для сборки роутинга указывать названия промежуточных файлов излишне. Сократил список параметров до одного ключа: `--make_routing_index`. Старый роутинг собирается по `--make_routing`.
=> [generator] User only --make_new_routing for the new routing

iphone/Maps/Classes/CustomViews/MapViewControls/Search/TableView/MWMSearchTableView.mm
https://jira.mail.ru/browse/MAPSME-3178
=> [MAPSME-3178] [ios] Added title to to MWMSearchNoResults screen.

iphone/Maps/Classes/CustomViews/MapViewControls/Search/MWMSearchManager.mm
https://jira.mail.ru/browse/MAPSME-3174
=> [MAPSME-3174] [ios] Fixed search manager states handling.

generator/routing_generator.cpp, tools/python/booking_hotels.py, tools/python/mwm/find_feature.py, tools/unix/test_planet.sh
Мелкие правки скриптов, чтобы сборка шла лучше:
* Сократил отчёт о тестах за счёт routing_consistency_test (его всё равно никто не смотрит) и лишних предупреждений от генератора.
* Убрал выпадение скачивалки гостиниц, когда в какой-то стране нет переводов.
* В find_features ключи сортируются, чтобы можно было сравнивать данные от разных сборок.
=> [scripts] Fix scripts and warnings for generating planet

iphone/Maps/Classes/CustomAlert/MobileInternetAlert/MWMMobileInternetAlert.xib, iphone/Maps/MWMMobileInternetViewController.mm, iphone/Maps/Settings.storyboard, iphone/Maps/Settings/MWMSettingsViewController.mm
https://jira.mail.ru/browse/MAPSME-3163
=> [MAPSME-3163] [ios] Updated mobile internet strings keys.

iphone/Maps/Classes/CustomAlert/DownloadTransitMapsAlert/MWMDownloadTransitMapAlert.mm, iphone/Maps/Classes/CustomAlert/DownloadTransitMapsAlert/MWMDownloadTransitMapAlert.xib, xcode/coding/coding.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-3161
=> [MAPSME-3161] [ios] Fixed blinking artefacts.

android/src/com/mapswithme/maps/traffic/widget/TrafficButtonController.java
=> [android] Added the translated strings for traffic

base/macros.hpp, indexer/ftypes_matcher.cpp, map/CMakeLists.txt, map/map.pro, map/place_page_info.cpp, map/place_page_info.hpp, map/reachable_by_taxi_checker.cpp, map/reachable_by_taxi_checker.hpp
Добавил метод для провеерки убера в плейс пейдже
@VladiMihaylenko 
@alexzatsepin
=> [core] uber into place page

base/base_tests/levenshtein_dfa_test.cpp, base/levenshtein_dfa.cpp, base/levenshtein_dfa.hpp, search/search_integration_tests/processor_test.cpp
=> [base] Support transpositions in LevenshteinDFA.

map/framework.cpp, map/traffic_manager.cpp, map/traffic_manager.hpp, routing/routing_session.cpp, routing/routing_session.hpp, traffic/traffic_info.hpp
- Update traffic state after downloading or deleting mwm.
- Logic of traffic manager fixed.
=> Update traffic state after downloading or deleting mwm.

android/src/com/mapswithme/maps/traffic/widget/TrafficButton.java, android/src/com/mapswithme/maps/traffic/widget/TrafficButtonController.java
=> [android] Fixed the traffic animation on Jelly Bean

tools/unix/generate_planet.sh
Короче, предупреждения просто большими буквами не работают. Перекрасил их в красный цвет, чтобы точно выделялись. Работаю ещё над передачей в телеграм, но не в этом реквесте.
=> [generator] Red warnings in generate_planet.sh

map/traffic_manager.cpp, map/traffic_manager.hpp, platform/marketing_service.cpp, platform/marketing_service.hpp, traffic/traffic_info.cpp
Добавлены интересующие нас события в Алохалитику и таг в PushWoosh
=> Added statistics for traffic

iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.mm, iphone/Maps/Classes/CustomViews/MapViewControls/BottomMenu/MWMBottomMenuViewController.xib, iphone/Maps/Classes/CustomViews/MapViewControls/TrafficButton/MWMTrafficButtonViewController.mm
https://jira.mail.ru/browse/MAPSME-3143
=> [MAPSME-3143] [ios] Fixed traffic states handling.

search/result.hpp
http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1397
=> [build] C++ core issue workaround.

data/countries.txt
Тот же мир.
Те же костлайны.
Те же данные.
Новый роутинг.
Пробки.
=> [planet] Smaller files in the new planet

android/jni/com/mapswithme/util/HttpClient.cpp
Пофиксил утечки в JNI
@alexzatsepin
=> [android] http client leaks fix

search/search_tests/string_intersection_test.cpp
=> [search] Fixed UB in search_tests.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/routing/NavigationController.java, android/src/com/mapswithme/maps/routing/RoutingController.java
=> [android] Fixed fadingIn/fadingOut in routing mode

data/countries.txt
При переделке роутинга забыл четыре файла, в которых роутинга нет.
=> [planet] Missing files from 6.12.2016 planet

drape_frontend/backend_renderer.cpp
https://jira.mail.ru/browse/MAPSME-3207
=> Fixed cache clearing in the traffic generator.

iphone/Maps/Classes/CustomAlert/Toast/MWMToast.mm, iphone/Maps/Classes/CustomAlert/Toast/MWMToast.xib, iphone/Maps/UIColor+MapsMeColor.mm
https://jira.mail.ru/browse/MAPSME-3206
=> [MAPSME-3206] [ios] Removed blur from toast background.

map/traffic_manager.cpp, map/traffic_manager.hpp
@rokuz @darina и кому интересно PTAL
=> Requesting traffic info for routing mwm.

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/editor/Editor.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java, android/src/com/mapswithme/maps/editor/Editor.java, android/src/com/mapswithme/maps/editor/EditorActivity.java, android/src/com/mapswithme/maps/editor/EditorHostFragment.java, map/framework.cpp, map/framework.hpp
Откат изменений по причине невозможности создавать новые объекты в редакторе
=> [android] revert for merge-commit dd75999

map/framework.cpp, routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/car_router.cpp, routing/directions_engine.hpp, routing/loaded_path_segment.hpp, routing/pedestrian_directions.cpp, routing/pedestrian_directions.hpp, routing/road_graph_router.cpp, routing/road_point.hpp, routing/route.cpp, routing/route.hpp, routing/routing_helpers.cpp, routing/routing_helpers.hpp, routing/single_mwm_router.cpp, routing/single_mwm_router.hpp, routing/turns_generator.cpp, routing/turns_generator.hpp
Сохранение в классе Route информации о трафике.
@rokuz @darina @ygorshenin @mpimenov PTAL
=> Route traffic information.

android/src/com/mapswithme/maps/widget/placepage/BannerController.java
Place Page banner icon animations(http://jira.65apps.com/browse/MAP-92).
@alexzatsepin 
@mpimenov
=> [android] Place Page banner icon animations.

android/res/values-fi/strings.xml, android/res/values-hu/strings.xml, android/res/values-tr/strings.xml, android/res/values-zh/strings.xml, iphone/Maps/fi.lproj/Localizable.strings, iphone/Maps/hu.lproj/Localizable.strings, iphone/Maps/tr.lproj/Localizable.strings, iphone/Maps/zh-Hans.lproj/Localizable.strings, strings.txt
=> Str fix wn

android/src/com/mapswithme/util/HttpClient.java
=>  [android] Fixed expired app error showing

data/categories.txt, search/search_integration_tests/processor_test.cpp
https://jira.mail.ru/browse/MAPSME-3229
=> [search] More synonyms.

iphone/Maps/Classes/NetworkPolicy/MWMNetworkPolicy.mm
https://jira.mail.ru/browse/MAPSME-3246
=> [MAPSME-3246] [ios] Disabled network policy check on wifi connection.

android/src/com/mapswithme/util/HttpClient.java, platform/http_client_apple.mm, platform/http_client_curl.cpp, traffic/traffic_info.cpp
@syershov @milchakov @igrechuhin PTAL
https://jira.mail.ru/browse/MAPSME-3250
=> [android][ios][traffic] Fixed 'etag' header processing

generator/generator_tests/restriction_collector_test.cpp, generator/restriction_collector.hpp, generator/restriction_writer.cpp, generator/routing_index_generator.cpp, routing/CMakeLists.txt, routing/geometry.cpp, routing/geometry.hpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/joint_index.cpp, routing/joint_index.hpp, routing/restriction_loader.cpp, routing/restriction_loader.hpp, routing/restrictions_serialization.cpp, routing/restrictions_serialization.hpp, routing/road_index.cpp, routing/road_index.hpp, routing/road_point.hpp, routing/routing.pro, routing/routing_tests/CMakeLists.txt, routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp, routing/routing_tests/routing_tests.pro, routing/single_mwm_router.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
cherry-pick PR на мастре https://github.com/mapsme/omim/pull/4817, который пока не ревью.
=> [RELEASE ONLY] Applying restrictions line-point-line at runtime on index graph.

routing/CMakeLists.txt, routing/edge_estimator.cpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/route_point.hpp, routing/routing.pro, routing/routing_tests/index_graph_tools.cpp, routing/single_mwm_router.cpp, routing/single_mwm_router.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Корректировка оценки времени маршрута, грубая подгонка под более реалистичные значения.
PTAL @bykoianko
=> [routing] fix route times

routing/CMakeLists.txt, routing/edge_estimator.cpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/route_point.hpp, routing/routing.pro, routing/routing_tests/index_graph_tools.cpp, routing/single_mwm_router.cpp, routing/single_mwm_router.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Корректировка оценки времени маршрута, грубая подгонка под более реалистичные значения.
PTAL @bykoianko
=> [release] [routing] fix route times

android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/src/com/mapswithme/maps/bookmarks/data/Banner.java, android/src/com/mapswithme/maps/widget/placepage/BannerController.java, android/src/com/mapswithme/util/statistics/Statistics.java
=> [android] statistic events for banners

routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/single_mwm_router.cpp
=> [Release crash fix] Correct processing fake feature of IndexGraphStarter.

routing/car_router.cpp
=> Preventing cyclical calling of building route in case of some errors.

android/src/com/mapswithme/maps/routing/NavigationController.java, android/src/com/mapswithme/maps/routing/SearchWheel.java
=> [android] Added saving/restoring the nav search bar state

data/countries.txt, data/external_resources.txt
=> [planet] Fresh data from 14.12.2016

iphone/Maps/Classes/CustomAlert/SearchAlert/MWMSearchNoResultsAlert.xib, iphone/Maps/Classes/Search/MWMSearch.mm
https://jira.mail.ru/browse/MAPSME-3096
=> Fixed No Results Alert display logic on iPad.

map/framework.cpp, map/framework.hpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/routing_session_test.cpp
Автоматическое обновление маршрута при изменении данных пробок.
По задаче https://jira.mail.ru/browse/MAPSME-3251
PTAL @bykoianko and other volunteers.
=> [release] [routing] Rebuild route on traffic updates

routing/base/astar_algorithm.hpp, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/restriction_test.cpp, routing/single_mwm_router.cpp
@bykoianko @mpimenov @dobriy-eeh PTAL
=> [routing] Added UTurns.

android/3rd_party/BottomSheet/build.gradle, android/UnitTests/build.gradle, android/build.gradle
=> [android] Updated Gradle plugin to 2.2.3

routing/edge_estimator.cpp, routing/routing_tests/applying_traffic_test.cpp, traffic/speed_groups.hpp
Учет временно заблокированных дорог при прокладке маршрута.
https://jira.mail.ru/browse/MAPSME-3274
@mpimenov @dobriy-eeh @ygorshenin PTAL
=> Support temporary blocked streets.

android/src/com/mapswithme/maps/bookmarks/data/Banner.java, android/src/com/mapswithme/maps/widget/placepage/BannerController.java
@Zverik @mpimenov @ygorshenin  PTAL
Добавил обработку ситуации, когда к нам прилетает неизвестный айдишник строки для баннера . 
Для того чтобы определить в каком случае он прилетает дополнительно добавил логирования "плохо" баннера в Fabric
=> Mapsme 3304 crash in banner controller

tools/unix/generate_planet_routing.sh
Добавил ключик для сборки пробочного индекса.
=> [generator] Generate traffic for the planet

routing/car_model.cpp
@ygorshenin or @dobriy-eeh  PTAL
=> Reducing speed for highway pedestrian

map/framework.cpp
https://jira.mail.ru/browse/MAPSME-3300
=> [omim] Filling feature's countryId in single place.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/NavigationButtonsAnimationController.java
Fixed zoom buttons visibility settings(http://jira.65apps.com/browse/MAP-95).
@alexzatsepin 
@mpimenov
=> [android] fixed zoom buttons visibility settings

android/src/com/mapswithme/maps/search/SearchFragment.java, android/src/com/mapswithme/maps/search/TabAdapter.java, android/src/com/mapswithme/util/statistics/Statistics.java
=> [android] Added search tab selected statistic event

android/res/layout/place_page.xml, android/src/com/mapswithme/maps/widget/placepage/BannerController.java, android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Fixed Place Page close animation(http://jira.65apps.com/browse/MAP-94).
@alexzatsepin 
@mpimenov
=> [android] Fixed Place Page close animation

coding/huffman.hpp, coding/zlib.cpp, platform/http_client_apple.mm, platform/http_thread_apple.mm
=> Fix warnings

android/gradle.properties
=> [android] Updated version to 7.0.4

3party/libtess2/CMakeLists.txt, CMakeLists.txt, generator/CMakeLists.txt, generator/generator_tests_support/CMakeLists.txt, indexer/CMakeLists.txt, indexer/indexer_tests_support/CMakeLists.txt
@syershov @therearesomewhocallmetim PTAL
=> [cmake] Added CMakeLists for generator_tests_support and libtess2.

CMakeLists.txt, generator/CMakeLists.txt
@syershov @therearesomewhocallmetim PTAL
=> [cmake] Added CMakeLists for generator.

search/CMakeLists.txt, search/search_integration_tests/CMakeLists.txt
@therearesomewhocallmetim @syershov PTAL
=> [search] CMakeLists for search_integration_tests.

CMakeLists.txt, qt/CMakeLists.txt
@therearesomewhocallmetim @syershov PTAL
=> [cmake] Fixed desktop app build on Linux.

android/gradle.properties
=> [android] Updated version to 7.0.5

routing/vehicle_model.cpp
@Zverik @ygorshenin @dobriy-eeh @mpimenov PTAL
Фикс для релиза. Рассмотрение всех roundabout, как односторонние дороги, выровненные по порядку точек.
@Zverik @ygorshenin @dobriy-eeh @mpimenov PTAL
Заранее спасибо за оперативное ревью :)
=> [RELEASE ONLY] Considering all roundabout as one way roads.

generator/osm2type.cpp, omim.pro
Ставим для `junction=roundabout` атрибут односторонней дороги, если явно не указано обратное.
Также поправил зависимости для `generator_tool`.
=> [generator] Make roundabouts oneways

drape_frontend/frontend_renderer.cpp
https://jira.mail.ru/browse/MAPSME-3356
=> Fixed route arrows recaching

routing/index_graph_starter.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp
=> [routing][release-70] Preventing interpretation loop features self intersection as uturn

iphone/Maps/UI/Settings/MWMHelpController.mm
https://jira.mail.ru/browse/MAPSME-3384
=> [MAPSME-3384] [ios] Fixed bundle vesrion in bug report.

iphone/Maps/UI/Settings/MWMHelpController.mm
https://jira.mail.ru/browse/MAPSME-3385
=> [MAPSME-3385] [ios] Fixed bug report email subject.

iphone/Maps/UI/Settings/MWMHelpController.mm
https://jira.mail.ru/browse/MAPSME-3383
=> [MAPSME-3383] [ios] Fixed feedback crash on iOS 8.

android/src/com/mapswithme/maps/bookmarks/data/MapObject.java, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/Utils.java
Place Page Action Bar buttons(http://jira.65apps.com/browse/MAP-84).
@alexzatsepin 
@mpimenov
=> [android] Place Page Action Bar buttons.

android/jni/com/mapswithme/maps/SearchEngine.cpp, android/src/com/mapswithme/maps/downloader/DownloaderFragment.java, search/downloader_search_callback.cpp, search/downloader_search_callback.hpp, search/search_integration_tests/downloader_search_test.cpp
Fixed downloader callback behavior - for consistency with other search callbacks results are accumulated in the results vector.
@alexzatsepin @igrechuhin PTAL
=> [search][android] Fixed downloader callback behavior.

search/engine.cpp, search/processor.cpp, search/search_integration_tests/processor_test.cpp
=> [search] Allow empty strings in search.

iphone/Maps/Bridging-Header.h, iphone/Maps/Common/Common.swift, iphone/Maps/Maps.xcodeproj/project.pbxproj, iphone/Maps/UI/Downloader/DataSources/MWMMapDownloaderSearchDataSource.h, iphone/Maps/UI/Downloader/DataSources/MWMMapDownloaderSearchDataSource.mm, iphone/Maps/UI/Downloader/MWMMapDownloaderViewController.mm, iphone/Maps/UI/Downloader/NoMaps/DownloaderNoResultsEmbedViewController.swift, iphone/Maps/UI/Downloader/NoMaps/MWMNoMapsViewController.h, iphone/Maps/UI/Mapsme.storyboard, iphone/Maps/UI/Search/SearchNoResultsViewController.swift
https://jira.mail.ru/browse/MAPSME-3388
=> [MAPSME-3388] [ios] Added no results screen to search in downloader.

drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp
Do not rewind follow animations when reseting them by another follow animation.
https://jira.mail.ru/browse/MAPSME-2623
=> Do not rewind follow animations.

drape_frontend/apply_feature_functors.cpp
https://jira.mail.ru/browse/MAPSME-3129
=> Fixed zero-rating hotels displaying

drape_frontend/animation/animation.cpp, drape_frontend/animation/animation.hpp, drape_frontend/animation/arrow_animation.cpp, drape_frontend/animation/arrow_animation.hpp, drape_frontend/animation/follow_animation.cpp, drape_frontend/animation/follow_animation.hpp, drape_frontend/animation/linear_animation.cpp, drape_frontend/animation/linear_animation.hpp, drape_frontend/animation/parallel_animation.cpp, drape_frontend/animation/parallel_animation.hpp, drape_frontend/animation/scale_animation.cpp, drape_frontend/animation/scale_animation.hpp, drape_frontend/animation/sequence_animation.cpp, drape_frontend/animation/sequence_animation.hpp, drape_frontend/animation_system.cpp, drape_frontend/animation_system.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/kinetic_scroller.cpp, drape_frontend/my_position_controller.cpp, drape_frontend/screen_animations.cpp, drape_frontend/user_event_stream.cpp, geometry/screenbase.cpp, geometry/screenbase.hpp
- Инициализация анимаций перед отложенным стартом.
- Отдаление до 2д при переходе в режим Follow во время навигации.
https://jira.mail.ru/browse/MAPSME-2073
Повторение https://github.com/mapsme/omim/pull/5085 на мастер
=> Animations initialization before delayed start.

drape_frontend/gui/ruler.cpp, drape_frontend/gui/ruler_helper.cpp, drape_frontend/gui/ruler_helper.hpp
This reverts commit 12a05922687cddcef06ed84e15ad43683fba5b7f.
https://jira.mail.ru/browse/MAPSME-3454
=> Do not hide the ruler.

android/res/values-w320dp/dimens.xml, android/res/values-w360dp/dimens.xml
http://jira.65apps.com/browse/MAP-100
@alexzatsepin 
@mpimenov
=> [android] Navigation buttons margings on small screens

iphone/Maps/Categories/UIKitCategories.mm, iphone/Maps/Common/Statistics/StatisticsStrings.h, iphone/Maps/Core/Settings/MWMSettings.h, iphone/Maps/Core/Settings/MWMSettings.mm, iphone/Maps/UI/Settings/MWMSettingsViewController.mm, iphone/Maps/UI/Settings/Settings.storyboard
https://jira.mail.ru/browse/MAPSME-3452
=> [ios] Added large fonts scale support.

iphone/Maps/Categories/UIColor+MapsMeColor.h, iphone/Maps/Categories/UIColor+MapsMeColor.mm, iphone/Maps/Classes/Components/MWMMailViewController.mm, iphone/Maps/Classes/Components/MWMNavigationController.mm, iphone/Maps/Classes/CustomAlert/Toast/MWMToast.mm, iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm, iphone/Maps/Common/MWMCommon.h, iphone/Maps/UI/Downloader/MWMBaseMapDownloaderViewController.mm, iphone/Maps/UI/Editor/Cuisine/MWMCuisineEditorViewController.mm, iphone/Maps/UI/Editor/MWMObjectsCategorySelectorController.mm
https://jira.mail.ru/browse/MAPSME-3287
=> [MAPSME-3287] [ios] Updated status bar style.

map/framework.cpp
https://jira.mail.ru/browse/MAPSME-3477
=> Disable traffic on starting of pedestrian or bicycle navigation.

drape_frontend/frontend_renderer.cpp, drape_frontend/route_shape.cpp
https://jira.mail.ru/browse/MAPSME-3491
=> Fixed route clipping

iphone/Maps/Classes/CustomViews/NavigationDashboard/Sound/MWMTextToSpeech.mm
https://jira.mail.ru/browse/MAPSME-3493
=> [MAPSME-3493] [ios] Fixed audio session mode.

android/src/com/mapswithme/maps/search/HotelsFilterView.java, android/src/com/mapswithme/maps/search/PriceFilterView.java, android/src/com/mapswithme/maps/search/RatingFilterView.java, android/src/com/mapswithme/maps/widget/PlaceholderView.java
Fix crash on pre lollipop devices
@alexzatsepin 
@mpimenov
=> [android] Fix crash on pre lollipop devices.

iphone/Maps/UI/Mapsme.storyboard
https://jira.mail.ru/browse/MAPSME-3501
=> [MAPSME-3501] [ios] Fixed layout bug.

map/framework.cpp, xcode/storage/storage.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-3513
=> Correct retrieval countryId for place page

.gitignore
При запуске приложения из QT автоматически создается файл gps_track.dat и висит в diff
Добавил его в ignore.
=> ignore data/gps_track.dat

android/jni/com/mapswithme/maps/LocationState.cpp, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/NavigationButtonsAnimationController.java, android/src/com/mapswithme/maps/location/GoogleFusedLocationProvider.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/location/LocationPredictor.java, android/src/com/mapswithme/maps/location/LocationState.java, android/src/com/mapswithme/maps/routing/ResultCodesHelper.java, android/src/com/mapswithme/maps/widget/menu/MyPositionButton.java
[android] Fixed the handling of my position click when it do nothing (fake)
@mpimenov @goblinr PTAL
https://jira.mail.ru/browse/MAPSME-2870
http://jira.65apps.com/browse/MAP-71
=> [android] Reduced shows of annoying Location Error dialog

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java, android/src/com/mapswithme/maps/bookmarks/ChooseBookmarkCategoryFragment.java, android/src/com/mapswithme/maps/widget/placepage/EditBookmarkFragment.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Modify bookmark only when user pressed "save" button.
@alexzatsepin 
@mpimenov
=> [android] Bookmark edit refactoring

data/banners.txt
=> [banners] Prolong banners till 1.03.2017 and add a default url to viator

iphone/Maps/Classes/CustomAlert/MWMEditorViralAlert.mm, iphone/Maps/Classes/CustomAlert/MWMEditorViralAlert.xib
https://jira.mail.ru/browse/MAPSME-3541
=> [ios] Removed fake message from viral alert.

iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMRoutePreview.mm, iphone/Maps/Classes/EAGLView.mm, iphone/Maps/Classes/MapViewController.h, iphone/Maps/Classes/MapViewController.mm, iphone/Maps/Core/Framework/MWMFrameworkHelper.h, iphone/Maps/Core/Framework/MWMFrameworkHelper.mm, iphone/Maps/Maps.xcodeproj/project.pbxproj, iphone/Maps/UI/Mapsme.storyboard, iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm, iphone/Maps/UI/PlacePage/PlacePageLayout/MWMiPhonePlacePageLayoutImpl.mm, iphone/Maps/UI/PlacePage/PlacePageLayout/PlacePageView/MWMPPView.mm, iphone/Maps/UI/Search/MWMSearchView.xib, iphone/Maps/UI/Search/SearchBar.swift, iphone/Maps/UI/VisibleArea/VisibleArea.swift
https://jira.mail.ru/browse/MAPSME-657
=> [MAPSME-657] [ios] Added visible area support.

iphone/Maps/UI/Downloader/DataSources/MWMMapDownloaderDefaultDataSource.mm
https://jira.mail.ru/browse/MAPSME-3389
=> [MAPSME-3389] [ios] Fixed downloader condition to show delete button.

iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
https://jira.mail.ru/browse/MAPSME-3524
=> [MAPSME-3524] [ios] Fixed map download dialog coloring.

generator/booking_quality_check/booking_quality_check.cpp, generator/booking_quality_check/booking_quality_check.pro, generator/booking_scoring.cpp, generator/restaurants_info/restaurants_info.pro, generator/sponsored_dataset.hpp, tools/python/opentable_restaurants.py
=> Fix build, add comments.

iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
https://jira.mail.ru/browse/MAPSME-3507
=> [ios] Removed booking's url from place page.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/base/BaseActivityDelegate.java, android/src/com/mapswithme/maps/base/BaseMwmFragmentActivity.java, android/src/com/mapswithme/maps/location/AndroidNativeProvider.java, android/src/com/mapswithme/maps/location/BaseLocationListener.java, android/src/com/mapswithme/maps/location/BaseLocationProvider.java, android/src/com/mapswithme/maps/location/DefaultLocationFixChecker.java, android/src/com/mapswithme/maps/location/FusedLocationFixChecker.java, android/src/com/mapswithme/maps/location/GPSCheck.java, android/src/com/mapswithme/maps/location/GoogleFusedLocationProvider.java, android/src/com/mapswithme/maps/location/LocationFixChecker.java, android/src/com/mapswithme/maps/location/LocationHelper.java
1. Вернул проверку mLocationFixChecker.isLocationBetterThanLast(location) в BaseLocationListener.onLocationChanged(location) метод, которую неосторожно удалил во время последнего рефакоринга этих классов + вынес логику про проверку координа в отдельный интерфейс LocationFixChecker
2. Добавил проверку на предмет включения/отключения location сервисов и еще немного рефакторинга
https://jira.mail.ru/browse/MAPSME-2688 (Приложение не определяет местоположение при включенном после запуска GPS) 
https://jira.mail.ru/browse/MAPSME-3553 (Местоположение "скачет" при движении по пешему маршруту)
https://jira.mail.ru/browse/MAPSME-2555 (Определяет местоположение, хотя, не должен)
=> [android] Added the location fix check to onLocationChanged method

drape_frontend/text_layout.cpp
https://jira.mail.ru/browse/MAPSME-3525
=> Large non-sdf text rendering fixed.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/NavigationButtonsAnimationController.java, android/src/com/mapswithme/maps/widget/menu/MyPositionButton.java
Fix navigation buttons restore visibility state(http://jira.65apps.com/browse/MAP-106).
@alexzatsepin 
@mpimenov
=> [android] Fix navigation buttons restore visibility state.

android/res/layout/hotels_filter.xml, android/src/com/mapswithme/maps/search/HotelsFilterView.java
New hotels filter dialog design(http://jira.65apps.com/browse/MAP-118).
@alexzatsepin 
@mpimenov
=> [android] New hotels filter dialog design

android/jni/com/mapswithme/util/Config.cpp, android/res/values/donottranslate.xml, android/res/xml-v21/prefs_misc.xml, android/res/xml/prefs_misc.xml, android/src/com/mapswithme/maps/settings/MiscPrefsFragment.java, android/src/com/mapswithme/util/Config.java
Added large fonts size settings(http://jira.65apps.com/browse/MAP-119).
@alexzatsepin 
@mpimenov
=> [android] Added large fonts size settings

android/src/com/mapswithme/maps/location/AndroidNativeProvider.java
=> Mapsme 3562 geo location with wi fi

android/res/layout-land/activity_map.xml, android/res/layout/activity_map.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/search/HotelsFilterView.java, android/src/com/mapswithme/maps/search/SearchFilterController.java, android/src/com/mapswithme/maps/search/SearchFragment.java
Fixed hotels filter restore state(https://jira.mail.ru/browse/MAPSME-3536).
Hide MainMenu when filter panel opened(https://jira.mail.ru/browse/MAPSME-3538).
@alexzatsepin 
@mpimenov
=> [android] Fixed hotels filter restore state.

android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/res/layout-land/place_page_preview.xml, android/res/layout/place_page_preview.xml, android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java
Added object title to the bookmark subtitle(https://jira.mail.ru/browse/MAPSME-3343).
@alexzatsepin 
@mpimenov
=> [android] Added object title to the bookmark subtitle.

android/gradle.properties
=> [android] Updated version to 7.0.6

geometry/spline.cpp, xcode/drape/drape.xcodeproj/project.pbxproj, xcode/drape_frontend/drape_frontend.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-3561
создал таск
=> [xcode] Attempt to optimize debug configuration.

iphone/Maps/UI/Welcome/WelcomePageController.swift
https://github.com/hons82/THSegmentedPager/issues/17
http://stackoverflow.com/questions/25740245/assertion-failure-in-uipageviewcontroller
=> [welcome] [ios] Fixed welcome controller crash.

iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/_MWMPPPAddress.xib, iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/_MWMPPPExternalTitle.xib, iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/_MWMPPPSchedule.xib, iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/_MWMPPPSpace.xib, iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/_MWMPPPSubtitle.xib, iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/_MWMPPPTitle.xib
https://jira.mail.ru/browse/MAPSME-2868
=> [ios] Fixed place page's direction layout.

generator/generator_tests/restriction_collector_test.cpp, generator/generator_tests/restriction_test.cpp, generator/restriction_collector.hpp, generator/restriction_generator.cpp, generator/restriction_writer.cpp, routing/CMakeLists.txt, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/geometry.hpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_road_graph.cpp, routing/restriction_loader.cpp, routing/restriction_loader.hpp, routing/restrictions_serialization.cpp, routing/restrictions_serialization.hpp, routing/road_index.hpp, routing/routing.pro, routing/routing_tests/CMakeLists.txt, routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp, routing/routing_tests/routing_tests.pro, routing/single_mwm_router.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
It's a cherry-pick of https://github.com/mapsme/omim/pull/5167
@dobriy-eeh PTAL
=> [Release only] Dynimic restrictions and uturns.

android/res/drawable-v21/bg_active_icon.xml, android/res/drawable-v21/bg_active_icon_night.xml, android/res/drawable-v21/bg_steady_icon_night.xml, android/res/drawable/bg_active_icon.xml, android/res/drawable/bg_active_icon_night.xml, android/res/drawable/bg_steady_icon_night.xml, android/res/values/themes-attrs.xml, android/res/values/themes-base.xml, android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
Fixed drawable resources for pre lollipop devices(https://jira.mail.ru/browse/MAPSME-3403).
@alexzatsepin 
@mpimenov
=> [android] Fixed drawable resources for pre lollipop devices

android/src/com/mapswithme/maps/search/HotelsFilterView.java, android/src/com/mapswithme/maps/search/PriceFilterView.java
Fixed hotels filter dialog cancel behavior(https://jira.mail.ru/browse/MAPSME-3539).
@alexzatsepin 
@mpimenov
=> [android] Fixed hotels filter dialog cancel behavior

android/res/layout/fragment_search.xml, android/src/com/mapswithme/maps/search/SearchFragment.java
Added fake elevation in the filter panel for pre lollipop devices(https://jira.mail.ru/browse/MAPSME-3557).
@alexzatsepin 
@mpimenov
=> [android] Added fake elevation in the filter panel

iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm, iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.xib
https://jira.mail.ru/browse/MAPSME-3594
=> [MAPSME-3594] [ios] Fixed layout bug.

iphone/Maps/UI/Settings/Settings.storyboard
https://jira.mail.ru/browse/MAPSME-3582
=> [MAPSME-3582] [ios] Fixed About screen coloring.

iphone/Maps/Categories/UIKitCategories.mm
https://jira.mail.ru/browse/MAPSME-3573
=> [MAPSME-3573] [ios] Fixed links openning.

map/place_page_info.cpp
https://jira.mail.ru/browse/MAPSME-2163
=> Added comma to place page coordinate.

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationInfoView.mm
https://jira.mail.ru/browse/MAPSME-3602
=> [MAPSME-3602] [ios] Fixed search layout during routing.

iphone/Maps/UI/Settings/MWMMobileInternetViewController.mm, iphone/Maps/UI/Settings/MWMNightModeController.mm, iphone/Maps/UI/Settings/MWMRecentTrackSettingsController.mm, iphone/Maps/UI/Settings/MWMTTSSettingsViewController.mm, iphone/Maps/UI/Settings/MWMUnitsController.mm
https://jira.mail.ru/browse/MAPSME-3628
=> [MAPSME-3628] [ios] Added cells deselection in settings.

android/res/layout-land/activity_map.xml, android/res/layout/activity_map.xml
Fixed hotels filter panel z-order(https://jira.mail.ru/browse/MAPSME-3621).
@alexzatsepin 
@mpimenov
=> [android] Fixed hotels filter panel z-order

android/res/anim/search_fade_in.xml, android/res/anim/search_fade_out.xml, android/res/values/integer.xml, android/src/com/mapswithme/maps/search/SearchActivity.java
Tune search transition animation speed(http://jira.65apps.com/browse/MAP-124).
@alexzatsepin 
@mpimenov
=> [android] Tune search transition animation speed

editor/editor_notes.cpp, editor/editor_notes.hpp, editor/editor_tests/editor_notes_test.cpp
Сделал для начала простой вариант фикса тикета
https://jira.mail.ru/browse/MAPSME-3228.
Плюс пофиксил состояние гонки на переменной size и итераторе it.
@mgsergio 
@syershov
=> [editor] Notes duplication fix

iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
https://jira.mail.ru/browse/MAPSME-3648
=> [MAPSME-3648] [ios] Fixed status bar style for iPad.

android/res/xml-v21/prefs_map.xml, android/res/xml-v21/prefs_misc.xml, android/res/xml/prefs_map.xml, android/res/xml/prefs_misc.xml, android/src/com/mapswithme/maps/settings/MapPrefsFragment.java, android/src/com/mapswithme/maps/settings/MiscPrefsFragment.java
Move "large font" setting from misc to map settings(https://jira.mail.ru/browse/MAPSME-3453).
@alexzatsepin 
@mpimenov
=> [android] Move "large font" setting from misc to map settings

data/countries.txt, data/external_resources.txt
I for one welcome our map overlords
=> [planet] New data from 19.01.2017

base/base_tests/mem_trie_test.cpp, base/mem_trie.hpp, base/stl_add.hpp
=> [base] MemTrie is switched to unique_ptrs.

android/res/layout/layout_nav_bottom_numbers.xml, android/src/com/mapswithme/maps/widget/menu/MyPositionButton.java
layout_nav_bottom fixes.
Added padding shift for the my position button in follow mode.
http://jira.65apps.com/browse/MAP-126
@alexzatsepin 
@mpimenov
=> [android] layout_nav_bottom fixes.

android/src/com/mapswithme/maps/routing/BaseRoutingErrorDialogFragment.java, android/src/com/mapswithme/maps/routing/ResultCodesHelper.java, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/routing/RoutingErrorDialogFragment.java
Don’t cancel routing when building status code NEED_MORE_MAPS(https://jira.mail.ru/browse/MAPSME-3670)
@alexzatsepin 
@mpimenov
=> [android] Don’t cancel routing when building status code NEED_MORE_MAPS

android/src/com/mapswithme/maps/location/AndroidNativeProvider.java
[android] Fix ConcurrentModificationException(http://jira.65apps.com/browse/MAP-128).
=> [android] Fix ConcurrentModificationException

android/jni/com/mapswithme/maps/editor/Editor.cpp, android/src/com/mapswithme/maps/editor/Editor.java, android/src/com/mapswithme/maps/editor/EditorHostFragment.java, indexer/editable_map_object.cpp, indexer/editable_map_object.hpp, iphone/Maps/UI/Editor/MWMEditorViewController.mm
https://jira.mail.ru/browse/MAPSME-3565
Сделал правки в ядре, поменял поведение в андройде, в айосе оставил старое поведение потому как с ходу не понятно как фиксить.
=> [core][android][ios] native name fix

indexer/osm_editor.cpp
https://jira.mail.ru/browse/MAPSME-2804
@ygorshenin
=> Too detailed exception info (during upload) was visible for users

search/feature_offset_match.hpp, search/geocoder.cpp, search/geocoder.hpp, search/locality_scorer.hpp, search/processor.cpp, search/processor.hpp, search/query_params.cpp, search/query_params.hpp, search/ranker.cpp, search/ranking_utils.cpp, search/ranking_utils.hpp, search/retrieval.cpp, search/search_integration_tests/processor_test.cpp, search/search_tests/locality_scorer_test.cpp, search/search_tests/ranking_tests.cpp, search/streets_matcher.cpp, search/streets_matcher.hpp, search/token_slice.cpp, search/token_slice.hpp, search/utils.hpp
=> [search] Fixed QueryParams.

iphone/Maps/Categories/UIView+Hierarchy.swift, iphone/Maps/Classes/Components/MWMAddPlaceNavigationBar.mm, iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm, iphone/Maps/Maps.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-3680
=> [MAPSME-3680] [ios] Fixed status bar style in add place mode.

generator/search_index_builder.cpp, indexer/feature_visibility.cpp, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp
MAPSME-3739
Есть у нас два типа, которые не отображаются на карте, но по ним хорошо бы искать. Это wifi и wheelchair. Последний пока не используется, но может.
=> [search] Fix wifi test and internet_access=wlan visibility

generator/generator_tests/restriction_collector_test.cpp, generator/generator_tests/restriction_test.cpp, generator/restriction_collector.hpp, generator/restriction_generator.cpp, generator/restriction_writer.cpp, routing/CMakeLists.txt, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/geometry.hpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_road_graph.cpp, routing/restriction_loader.cpp, routing/restriction_loader.hpp, routing/restrictions_serialization.cpp, routing/restrictions_serialization.hpp, routing/road_index.hpp, routing/routing.pro, routing/routing_tests/CMakeLists.txt, routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp, routing/routing_tests/routing_tests.pro, routing/single_mwm_router.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
@ygorshenin @dobriy-eeh @mpimenov PTAL
Пока PR на ревью, буду профилировать этот код. Например, очень похоже что профилировщик может указать на метод IsRestricted().
=> [routing] Dynamic restrictions and UTurns on invert graph.

generator/search_index_builder.cpp
=> [generator] Fixed SearchIndexBuilder.

drape_frontend/animation/animation.cpp, drape_frontend/animation/animation.hpp, drape_frontend/animation/arrow_animation.cpp, drape_frontend/animation/arrow_animation.hpp, drape_frontend/animation/follow_animation.cpp, drape_frontend/animation/follow_animation.hpp, drape_frontend/animation/interpolators.cpp, drape_frontend/animation/interpolators.hpp, drape_frontend/animation/linear_animation.cpp, drape_frontend/animation/linear_animation.hpp, drape_frontend/animation/parallel_animation.cpp, drape_frontend/animation/parallel_animation.hpp, drape_frontend/animation/scale_animation.cpp, drape_frontend/animation/scale_animation.hpp, drape_frontend/animation/sequence_animation.cpp, drape_frontend/animation/sequence_animation.hpp, drape_frontend/kinetic_scroller.cpp, drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp, drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp
https://jira.mail.ru/browse/MAPSME-3504
=> Save duration restrictions of animation during its initialization.

coding/zlib.cpp
=> [coding] Fixed Android ZLib build.

drape_frontend/frontend_renderer.cpp, drape_frontend/message_subclasses.hpp
https://jira.mail.ru/browse/MAPSME-3738
=> Fixed crash inside the handler of new visible viewport event.

iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
https://jira.mail.ru/browse/MAPSME-3676
=> [MAPSME-3676] [ios] Fixed traffic button hidden state changes.

iphone/Maps/UI/Search/MWMSearchManager.mm
https://jira.mail.ru/browse/MAPSME-3752
=> [MAPSME-3752] [ios] Fixed search layout bug.

indexer/osm_editor.cpp, indexer/osm_editor.hpp
У нас не работало удаление для фич, которые были созданы пользователем, а правки уже улетели.
https://jira.mail.ru/browse/MAPSME-3458
=> [editor] added possibility to remove previously created and uploaded feature

drape/batcher.cpp, drape/batcher.hpp, drape_frontend/batchers_pool.hpp, drape_frontend/message_subclasses.hpp
https://jira.mail.ru/browse/MAPSME-3755
=> Fixed traffic recovering after receiving a response in background.

iphone/Maps/UI/PlacePage/PlacePageLayout/Content/OpeningHoursCell/MWMOpeningHoursLayoutHelper.mm
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/588f2fbc0aeb16625bb0a28d
=> [ios] Attempt to fix crash with place page opening hours layout.

base/mem_trie.hpp, search/geocoder.cpp, search/geocoder.hpp, search/locality_scorer.cpp, search/locality_scorer.hpp, search/ranking_utils.hpp, search/search_tests/CMakeLists.txt, search/search_tests/locality_scorer_test.cpp
=> [search] Pre-localities selection is moved to LocalityScorer.

android/src/com/mapswithme/maps/routing/RoutingController.java
Change text of routing alert dialog buttons(https://jira.mail.ru/browse/MAPSME-2286).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] change text of routing alert dialog buttons

android/src/com/mapswithme/maps/location/BaseLocationListener.java, android/src/com/mapswithme/maps/location/DefaultLocationFixChecker.java, android/src/com/mapswithme/maps/location/LocationFixChecker.java
https://jira.mail.ru/browse/MAPSME-3789
=> [android] Added accuracy ignoring for a gps location

android/jni/Android.mk, android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/jni/com/mapswithme/maps/Sponsored.cpp, android/jni/com/mapswithme/maps/uber/Uber.cpp, android/jni/com/mapswithme/util/NetworkPolicy.cpp, android/jni/com/mapswithme/util/NetworkPolicy.hpp, android/res/layout/dialog_stacked_buttons.xml, android/res/values/dimens.xml, android/res/values/donottranslate.xml, android/res/values/string-arrays.xml, android/res/values/styles.xml, android/res/values/themes-attrs.xml, android/res/values/themes-base.xml, android/res/xml-v21/prefs_misc.xml, android/res/xml/prefs_misc.xml, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/settings/MiscPrefsFragment.java, android/src/com/mapswithme/maps/uber/Uber.java, android/src/com/mapswithme/maps/widget/StackedButtonsDialog.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/placepage/Sponsored.java, android/src/com/mapswithme/util/Config.java, android/src/com/mapswithme/util/ConnectionState.java, android/src/com/mapswithme/util/NetworkPolicy.java, platform/network_policy.hpp
Added network policy android implementation(https://jira.mail.ru/browse/MAPSME-2990).
@alexzatsepin 
@mpimenov 
@milchakov 
PTAL
=> [android]Network policy android implementation

iphone/Maps/UI/Downloader/Cells/MWMMapDownloaderTableViewCell.mm
https://jira.mail.ru/browse/MAPSME-3753
=> Fixed calculation of size in downloader

android/res/layout/hotels_filter.xml, android/src/com/mapswithme/maps/search/HotelsFilterView.java
Adaptive height for hotels filter dialog(https://jira.mail.ru/browse/MAPSME-3701).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] adaptive height for hotels filter dialog

android/src/com/mapswithme/maps/location/BaseLocationListener.java, android/src/com/mapswithme/maps/location/DefaultLocationFixChecker.java, android/src/com/mapswithme/maps/location/LocationFixChecker.java
Cherry-pick этого PR https://github.com/mapsme/omim/pull/5341 на release-71
=> [android] [cherry-pick] Added accuracy ignoring for a gps location

android/res/layout/hotels_filter.xml, android/src/com/mapswithme/maps/search/HotelsFilterView.java
cherry-pick #5324 
Adaptive height for hotels filter dialog(https://jira.mail.ru/browse/MAPSME-3701).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] [cherry-pick] adaptive height for hotels filter dialog

android/src/com/mapswithme/maps/MwmActivity.java
update search bar status after routing/planing canceled(https://jira.mail.ru/browse/MAPSME-2982).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] update search bar status after routing/planing canceled.

android/res/drawable/ic_altitude_difference.xml, android/res/layout-land/altitude_chart_panel.xml, android/res/layout-land/routing_details.xml, android/res/layout-w1020dp-land/routing_details.xml, android/res/layout/routing_details.xml, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/routing/RoutingPlanController.java, android/src/com/mapswithme/maps/routing/RoutingPlanInplaceController.java
Added altitude difference indicator(https://jira.mail.ru/browse/MAPSME-3346).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] Added altitude difference indicator

geometry/covering_utils.hpp
Old bug. Better cells fitting into geometry. May increase index file size a little bit.
=> [geo-index][covering] Fixed cells covering. Use more predictive criteria.

search/CMakeLists.txt, search/features_layer.cpp, search/features_layer.hpp, search/geocoder.cpp, search/geocoder.hpp, search/geocoder_context.cpp, search/geocoder_context.hpp, search/intersection_result.hpp, search/locality_scorer.cpp, search/pre_ranker.cpp, search/pre_ranking_info.cpp, search/pre_ranking_info.hpp, search/query_params.cpp, search/query_params.hpp, search/ranker.cpp, search/search.pro, search/search_integration_tests/pre_ranker_test.cpp, search/search_integration_tests/processor_test.cpp, search/search_tests/ranking_tests.cpp, search/streets_matcher.cpp, search/streets_matcher.hpp, search/token_range.hpp, search/token_slice.cpp, search/token_slice.hpp
=> [search] Pair (start-token, end-token) is replaced by TokenRange.

android/src/com/mapswithme/maps/MwmActivity.java
cherry-peak from #5348
update search bar status after routing/planing canceled(https://jira.mail.ru/browse/MAPSME-2982).
@alexzatsepin
@mpimenov
PTAL
=> [android][cherry-peak] update search bar status after routing/planing canceled.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java, map/framework.cpp
Fixed multiple bookmark selection in one place(https://jira.mail.ru/browse/MAPSME-3195).
@alexzatsepin 
@mpimenov
=> [android] Fixed multiple bookmark selection in one place.

search/geocoder.cpp, search/geocoder_context.cpp, search/geocoder_context.hpp, search/pre_ranker.cpp, search/query_params.cpp, search/query_params.hpp, search/streets_matcher.cpp, search/token_range.hpp, search/token_slice.cpp
=> [search] Implicit TokenRange.

android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/background/AppBackgroundTracker.java, android/src/com/mapswithme/maps/search/SearchFragment.java, android/src/com/mapswithme/maps/settings/MiscPrefsFragment.java, android/src/com/mapswithme/util/HttpClient.java, android/src/com/mapswithme/util/Utils.java, android/src/com/mapswithme/util/log/FileLoggerStrategy.java, android/src/com/mapswithme/util/log/LoggerFactory.java, android/src/com/mapswithme/util/log/ZipLogsTask.java
?enableLogging and ?disableLogging commands close the search;
moved the 'logcat.log' file to the logs folder.
1. logcat.txt переместил в папку logs и переименовал его в logcat.log
2. Сделал закрытие поиска по командам ?enable/DisableLogging
3. Включил логирование по дефолту для бета сборок
@goblinr @milchakov @mpimenov PTAL
=> [android] Enabled file logging by default for beta builds;

android/res/layout/item_search_clear_history.xml, android/src/com/mapswithme/maps/search/SearchHistoryFragment.java
Added bottom margin for clear history button(https://jira.mail.ru/browse/MAPSME-2533).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] Search clear history button fix.

search/geocoder.cpp, search/pre_ranker.cpp, search/pre_ranking_info.cpp, search/pre_ranking_info.hpp, search/ranker.cpp, search/search_integration_tests/pre_ranker_test.cpp, search/token_range.hpp
@mpimenov PTAL
These token ranges are unused now, planning to use them in the next PR.
=> [search] Multiple TokenRanges in PreRankingInfo.

android/src/com/mapswithme/maps/MwmActivity.java
Fix start navigation in the tablet landscape mode(https://jira.mail.ru/browse/MAPSME-3700).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] Fix start navigation in the tablet landscape mode

search/geocoder.cpp, search/processor.cpp, search/ranker.cpp, search/ranking_utils.cpp, search/ranking_utils.hpp, search/search_integration_tests/processor_test.cpp
=> [search] Fixed discrepancy in tokens between geocoder and ranker.

qt/CMakeLists.txt
@therearesomewhocallmetim @syershov PTAL
=> [desktop] Fixed app running when cmake is used

drape_frontend/frontend_renderer.cpp
https://jira.mail.ru/browse/MAPSME-3667
https://jira.mail.ru/browse/MAPSME-3681
=> Fixed depth test for traffic and route

drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp
After deactivation of routing on devices without a compass fixed shape of my position.
https://jira.mail.ru/browse/MAPSME-3684
=> My position shape after deactivation of routing fixed.

base/CMakeLists.txt, base/base.pro, base/base_tests/CMakeLists.txt, base/base_tests/base_tests.pro, base/base_tests/bits_test.cpp, base/base_tests/small_set_test.cpp, base/bits.hpp, base/small_set.hpp, coding/compressed_bit_vector.cpp, coding/elias_coder.hpp, search/feature_offset_match.hpp, search/processor.cpp, search/query_params.cpp, search/query_params.hpp
=> [search] SmallSet for languages.

android/src/com/mapswithme/maps/settings/MiscPrefsFragment.java, android/src/com/mapswithme/util/log/LoggerFactory.java
=> [android] Enabled logging for beta build by default

android/build.gradle, android/jni/com/mapswithme/maps/PrivateVariables.cpp, android/proguard-mwm.txt, android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/PrivateVariables.java, data/copyright.html
Remove hockeyapp sdk(https://jira.mail.ru/browse/MAPSME-3767).
=> [android] remove hockeyapp sdk

base/base_tests/stl_helpers_test.cpp, base/mem_trie.hpp, base/stl_helpers.hpp, indexer/categories_holder.cpp, indexer/categories_holder.hpp, indexer/indexer_tests/categories_test.cpp
Also, minor style refactorings.
=> [indexer] Changed a map to a trie in CategoriesHolder.

android/src/com/mapswithme/util/log/FileLoggerStrategy.java
https://jira.mail.ru/browse/MAPSME-3831
@mpimenov PTAL
=> [android] Added milliseconds to log record

data/faq.html
Various corrections and improvements
=> FAQ Update February

android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java, android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
fix bookmarks empty message overlapping(https://jira.mail.ru/browse/MAPSME-3724).
=> [android] fix bookmarks empty message overlapping

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/src/com/mapswithme/maps/MapFragment.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/NavigationButtonsAnimationController.java, android/src/com/mapswithme/maps/location/AndroidNativeProvider.java, android/src/com/mapswithme/maps/location/BaseLocationProvider.java, android/src/com/mapswithme/maps/location/GPSCheck.java, android/src/com/mapswithme/maps/location/GoogleFusedLocationProvider.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/location/LocationPredictor.java, android/src/com/mapswithme/maps/location/LocationState.java, android/src/com/mapswithme/maps/location/TransitionListener.java, android/src/com/mapswithme/maps/news/BaseNewsFragment.java, android/src/com/mapswithme/maps/news/FirstStartFragment.java, android/src/com/mapswithme/maps/routing/ResultCodesHelper.java, android/src/com/mapswithme/maps/settings/MiscPrefsFragment.java, android/src/com/mapswithme/util/LocationUtils.java, android/src/com/mapswithme/util/statistics/Statistics.java, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp, map/framework.cpp
Суть этого PR:
1. Исправления бага в ядре связанного с тем, что платформа не получала состояния **PENDING_POSITION** для кнопки **My Positio**n при холодном старте. А также, были вытащены костыли из слоя JNI. Этим занимался @rokuz 
2. Отрефакторил класс **LocationHelper**, который был затыкан безбожно костылями + отрефакторил код, связанный с первым стартом.
@rokuz @mpimenov @goblinr PTAL
=> Android my pos fix

indexer/CMakeLists.txt, indexer/indexer_tests/CMakeLists.txt, indexer/road_shields_parser.cpp, qt/CMakeLists.txt
=> [build] CMake build fix.

indexer/categories_holder.cpp, indexer/categories_holder.hpp
https://jira.mail.ru/browse/MAPSME-3836
=> Use en category name if there is no translation for current locale

android/res/layout-land/dialog_stacked_buttons.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/widget/StackedButtonDialogFragment.java, android/src/com/mapswithme/maps/widget/placepage/BannerController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/placepage/Sponsored.java, android/src/com/mapswithme/util/Config.java, android/src/com/mapswithme/util/CrashlyticsUtils.java, android/src/com/mapswithme/util/NetworkPolicy.java
Show online-aware dialog before Place Page is shown(http://jira.65apps.com/browse/MAP-148).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] Show online-aware dialog before Place Page is shown

android/res/layout/layout_nav_bottom_numbers.xml, android/res/values-sw720dp/dimens.xml, android/res/values/dimens.xml
fix routing time info layout for tablet devices(https://jira.mail.ru/browse/MAPSME-3121).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] fix routing time info layout for tablet devices

android/jni/Android.mk, android/jni/com/mapswithme/core/jni_helper.cpp, android/jni/com/mapswithme/core/jni_helper.hpp, android/jni/com/mapswithme/core/logging.cpp, android/jni/com/mapswithme/core/logging.hpp, android/jni/com/mapswithme/util/LoggerFactory.cpp, android/src/com/mapswithme/util/log/FileLoggerStrategy.java, android/src/com/mapswithme/util/log/LogCatStrategy.java, android/src/com/mapswithme/util/log/LoggerFactory.java
Продолжение этого https://github.com/mapsme/omim/pull/5432
@syershov @milchakov @goblinr PTAL
=> [android] Bound core debug logs to 'Enable logging' setting

search/geocoder.cpp, search/geocoder.hpp, search/intersection_result.cpp, search/intersection_result.hpp, search/pre_ranking_info.hpp, search/ranker.cpp, search/ranker.hpp, search/search_integration_tests/CMakeLists.txt, search/search_integration_tests/helpers.cpp, search/search_integration_tests/helpers.hpp, search/search_integration_tests/processor_test.cpp, search/search_integration_tests/ranker_test.cpp
=> [search] Ranker takes into account possible errors in the street part.

search/ranking_info.cpp, search/search_quality/download-maps.sh
=> [search] Re-evaluated search model.

android/src/com/mapswithme/maps/widget/StackedButtonDialogFragment.java
showing network policy dialog with allow state loss(http://jira.65apps.com/browse/MAP-152).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] showing network policy dialog with allow state loss

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, drape/support_manager.hpp, drape_frontend/backend_renderer.cpp, drape_frontend/backend_renderer.hpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/message.hpp, drape_frontend/message_subclasses.hpp, drape_frontend/traffic_generator.cpp, drape_frontend/traffic_generator.hpp, map/framework.cpp, map/framework.hpp, map/traffic_manager.cpp, map/traffic_manager.hpp, qt/search_panel.cpp, qt/search_panel.hpp
https://jira.mail.ru/browse/MAPSME-3899
=> Added simplified traffic colors

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
don’t show banner on my position(https://jira.mail.ru/browse/MAPSME-3903).
@alexzatsepin 
@mpimenov
=> [android] don’t show banner on my position

data/countries.txt, data/external_resources.txt
Планетку вам в ветку. Данные почти разлились, можно мёржить.
=> [planet] New planet data from 15.02.2017

3party/jansson/myjansson.cpp, 3party/jansson/myjansson.hpp, android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/jni/com/mapswithme/maps/Sponsored.cpp, android/src/com/mapswithme/maps/review/Review.java, android/src/com/mapswithme/maps/review/ReviewAdapter.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/placepage/ReviewAdapter.java, android/src/com/mapswithme/util/HttpClient.java, iphone/Maps/UI/PlacePage/Deprecated/MWMPlacePageEntity.mm, iphone/Maps/UI/PlacePage/MWMPlacePageData.mm, map/framework.cpp, map/framework.hpp, partners_api/booking_api.cpp, partners_api/booking_api.hpp, partners_api/partners_api_tests/booking_tests.cpp, platform/http_client.cpp, platform/http_client.hpp, xcode/search/search.xcodeproj/project.pbxproj
Добавил загрузку расширенной информации по отелю.
Переписывал букинг на использование другого класса загрузки данных из сети, в итоге переписал почти полностью.
Удалил поле "нейтральный отзыв" потому что в дизайне его нету и в информации от букинга тоже нету. От букинга приходит поле headline, которое можно было бы использовать у нас, если будет подходящий дизайн.
Также удалил поле "аватар автора" потому, что от букинга тоже нету этой инфы.
Не мержить пока на сервер не загружены данные по отелям (тесты не будут проходить).
@syershov 
@ygorshenin 
Потребуется изменение на стороне андройда чтобы корректно протаскивать рейтинг отеля / ревьюхи и количество голосовавших.
@alexzatsepin
=> Booking extended info

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
prevent showing gallery if it has only 5 images(https://jira.mail.ru/browse/MAPSME-3906).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] prevent showing gallery if it has only 5 images

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
clear gallery adapter when place page start update(https://jira.mail.ru/browse/MAPSME-3909).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] clear gallery adapter when place page start update

android/res/layout/item_facility.xml, android/src/com/mapswithme/maps/widget/placepage/FacilitiesAdapter.java
text of facility is limited to 2 lines(https://jira.mail.ru/browse/MAPSME-3907).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] text of facility is limited to 2 lines

indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, search/hotels_filter.cpp, search/hotels_filter.hpp, search/search_integration_tests/helpers.cpp, search/search_integration_tests/helpers.hpp, search/search_integration_tests/processor_test.cpp
=> [search] Added filtering by hotel type.

android/build.gradle, android/res/layout/fragment_osm_login.xml, android/res/layout/place_page_hotel_rating.xml, android/src/com/mapswithme/maps/routing/SearchWheel.java, android/src/com/mapswithme/maps/widget/ObservableScrollView.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/placepage/ReviewAdapter.java, android/src/com/mapswithme/util/ThemeUtils.java
fix booking reviews in Place Page(https://jira.mail.ru/browse/MAPSME-3925).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] fix booking reviews in Place Page

android/src/com/mapswithme/maps/widget/placepage/BannerController.java
=> [android] Enabled facebook test banners for beta build

android/res/layout/place_page_banner.xml, android/src/com/mapswithme/maps/widget/placepage/BannerController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Added progress bar and error message for place page banner.
Fixed banner open/close behavior.
http://jira.65apps.com/browse/MAP-161
@alexzatsepin 
@mpimenov 
PTAL
=> [android] Added progress bar and error message for place page banner

routing/routing_integration_tests/routing_test_tools.cpp, routing/single_mwm_router.cpp, routing/single_mwm_router.hpp
=> routing integration test fix.

platform/mwm_traits.cpp, platform/mwm_traits.hpp
Забытая доработка из https://github.com/mapsme/omim/pull/5468
=> small refactoring mwm traits

data/copyright.html
=> [android] Added Glide and JCIP libraries in copyright list

android/AndroidManifest.xml, android/jni/com/mapswithme/maps/Sponsored.cpp, android/res/layout-land/place_page_details.xml, android/res/layout-w600dp-port/place_page_details.xml, android/res/layout/item_facility.xml, android/res/layout/place_page_details.xml, android/res/layout/place_page_hotel_description.xml, android/res/layout/place_page_hotel_rating.xml, android/res/layout/place_page_more.xml, android/res/values/dimens.xml, android/src/com/mapswithme/maps/widget/placepage/FacilitiesAdapter.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/placepage/Sponsored.java, android/src/com/mapswithme/util/HttpClient.java
=> Mapsme 3960 fix booking gallery pp

search/pysearch/bindings.cpp, search/pysearch/run_search_engine.py, search/pysearch/run_search_server.py
=> [search] Added simple search http server.

android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
fixed null pointer exception(http://jira.65apps.com/browse/MAP-166).
@alexzatsepin 
PTAL
=> [android] fixed null pointer exception

android/res/layout/fragment_search.xml, android/res/layout/tab.xml, android/res/values/styles-text.xml, android/res/values/styles.xml, android/src/com/mapswithme/maps/search/TabAdapter.java
=> [android] Fixed tabs in search

android/res/layout/place_page_hotel_facilities.xml, android/src/com/mapswithme/maps/widget/placepage/FacilitiesAdapter.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
fix PP hotel facilities view.
@alexzatsepin 
PTAL
=> [android] fix PP hotel facilities view

android/jni/com/mapswithme/maps/Sponsored.cpp
=> [android] Fixed booking reviews count

android/res/layout/fragment_search.xml, android/res/layout/item_search_clear_history.xml, android/src/com/mapswithme/maps/search/SearchFragment.java, android/src/com/mapswithme/util/Animations.java
fix search scrolling behavior(https://jira.mail.ru/browse/MAPSME-3970).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] fix search scrolling behavior

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
fix PP hotel gallery restore state(https://jira.mail.ru/browse/MAPSME-3984).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] fix PP hotel gallery restore state

map/framework.cpp, routing/routing_session.cpp, routing/routing_session.hpp, tracking/reporter.cpp, tracking/reporter.hpp, tracking/tracking_tests/reporter_test.cpp
Протянул информацию о трафике из роутинга в tracking::Reporter
=> [release-72] [tracking] Add traffic info to tracking reporter

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
@goblinr @mpimenov PTAL
Суть реквеста:
Объявил поле mMapObject Nullable и добавил проверку на null во всех местах использования этого объекта + логирование ошибки, если mMapObject is null
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5887791c0aeb16625b79886e?time=last-ninety-days
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/57e6aa200aeb16625bb247c0?time=last-ninety-days
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/588a34880aeb16625b8eb298?time=last-ninety-days
=> [android] Fixed nullability issues for mMapObject in PP

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Clear hotel info views before requesting new info(https://jira.mail.ru/browse/MAPSME-3988).
@alexzatsepin 
@mpimenov 
PTAL
=> [android] clear hotel info views before requesting new info

android/src/com/mapswithme/maps/widget/placepage/BannerController.java
=> [android] Added test hash device

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Translate booking based on reviews.
@alexzatsepin 
PTAL
=> [android]Translate booking based on reviews

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
fix PP animation behavior when country has downloaded.
@alexzatsepin 
PTAL
=> [android] fix PP animation behavior when country has downloaded

routing/directions_engine.cpp, routing/index_router.cpp, routing/index_router.hpp, routing/world_graph.cpp, routing/world_graph.hpp
@dobriy-eeh @syershov @Zverik PTAL
=> [release 72] Routing integration test fix.

data/faq.html
Edit FAQ - add <wbr> tags to paths for no horizontall scroll
=> Edit FAQ - add <wbr> tags to paths for no horizontall scroll

iphone/Maps/Core/Search/MWMSearch.mm
https://jira.mail.ru/browse/MAPSME-3971
=> [RELEASE ONLY] Fixed cancelling of searching on map.

data/countries.txt, data/external_resources.txt
=> [planet] Fresh data from 6.03.2017

android/gradle.properties
@therearesomewhocallmetim PTAL
=> [android] Updated version to 7.2.0

qt/qt_common/map_widget.hpp, qt/qt_common/proxy_style.cpp, qt/qt_common/proxy_style.hpp, qt/qt_common/qtoglcontext.cpp, qt/qt_common/qtoglcontext.hpp, qt/qt_common/qtoglcontextfactory.cpp, qt/qt_common/qtoglcontextfactory.hpp
=> [qt] Fixed style of qt_common/*.(cpp|hpp).

android/src/com/mapswithme/maps/widget/placepage/BannerController.java
fix PP animation after background resume(https://jira.mail.ru/browse/MAPSME-4052).
=> [android] fix PP animation after background resume

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/placepage/Sponsored.java, android/src/com/mapswithme/util/statistics/Statistics.java
=> Mapsme 4042 statistics for rich page

data/categories.txt
=> Fix categories duplication

android/src/com/mapswithme/maps/widget/placepage/FacilitiesAdapter.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
fix PP size changed behavior when hotel facilities updated(https://jira.mail.ru/browse/MAPSME-3996).
=> [android] fix PP size changed behavior when hotel facilities updated

map/gps_track.cpp, map/gps_track.hpp
@alexzatsepin @ygorshenin PTAL
https://jira.mail.ru/browse/MAPSME-4057
=> [release-72] Track recorder crash fix.

iphone/Maps/Core/Search/MWMSearch.mm
https://jira.mail.ru/browse/MAPSME-4061
=> [RELEASE ONLY] Fixed showing of a single search result on iPad.

android/res/layout/place_page_banner.xml
@goblinr PTAL
"Отцентрировать по высоте название кнопки в рекламном блоке"
=> [android] Fixed small action text gravity

android/src/com/mapswithme/maps/widget/placepage/BannerController.java, android/src/com/mapswithme/util/statistics/Statistics.java
=> [android] Added statistic for FB banner

android/src/com/mapswithme/maps/widget/placepage/BannerController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Added bottom padding when fb banner has error occurred(https://jira.mail.ru/browse/MAPSME-4058).
@alexzatsepin
=> [android] Added bottom padding when fb banner has error occurred

android/res/layout/place_page_banner.xml, android/res/values-v21/donottranslate.xml, android/res/values/donottranslate.xml
RobotoMedium font on pre lollipop devices fix(https://jira.mail.ru/browse/MAPSME-4050).
=> [android] RobotoMedium font on pre lollipop devices fix

android/gradle.properties
=> [android] Increased build tools version

android/src/com/mapswithme/maps/widget/placepage/BannerController.java
=> [android] Removed test banners code

iphone/Maps/Classes/MapsAppDelegate.mm
https://jira.mail.ru/browse/MAPSME-4077
=> [ios] Don't show rate alert while routing.
