mapsme/omim

android/src/com/mapswithme/maps/routing/RoutingController.java
=> [android] Fixed NPE in RoutingController

android/jni/com/mapswithme/core/logging.cpp
https://github.com/mapsme/omim/pull/5603
=> Logging fix

android/src/com/mapswithme/maps/ads/LikesManager.java, android/src/com/mapswithme/maps/search/HotelsFilterView.java
[android] Don’t show rateapp dialog when routing session is active(https://jira.mail.ru/browse/MAPSME-4076).
=> [android] Don’t show rateapp dialog when routing session is active

android/gradle.properties
=> [android] Updated version to 7.2.1

data/categories.txt
https://jira.mail.ru/browse/MAPSME-4099
=> Categories fix

generator/routing_index_generator.cpp
=> [routing] Починка ужасного бага в роутинге

android/src/com/mapswithme/maps/routing/NavigationController.java
Fixed 24/12 hour time format in routing information(https://jira.mail.ru/browse/MAPSME-3975).
=> [android] Fixed 24/12 hour time format in routing information

.gitignore, drape_frontend/CMakeLists.txt, drape_frontend/apply_feature_functors.cpp, drape_frontend/apply_feature_functors.hpp, drape_frontend/backend_renderer.cpp, drape_frontend/custom_symbol.hpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/drape_frontend.pro, drape_frontend/frontend_renderer.cpp, drape_frontend/message.hpp, drape_frontend/message_subclasses.hpp, drape_frontend/poi_symbol_shape.cpp, drape_frontend/read_manager.cpp, drape_frontend/read_manager.hpp, drape_frontend/rule_drawer.cpp, drape_frontend/rule_drawer.hpp, drape_frontend/shape_view_params.hpp, drape_frontend/tile_info.cpp, drape_frontend/tile_info.hpp, drape_frontend/visual_params.cpp, drape_frontend/visual_params.hpp, xcode/drape_frontend/drape_frontend.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-4092
=> Added support of custom symbols for specific POI

iphone/Maps/Core/NetworkPolicy/MWMNetworkPolicy.mm, iphone/Maps/UI/PlacePage/MWMPlacePageData.mm, iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/58cbb79a0aeb16625b7ffbcf
=> [ios] Attempt to fix crash with online pp part.

iphone/Maps/Classes/Components/MWMTableViewController.mm, iphone/Maps/UI/Editor/Street/MWMStreetEditorViewController.mm
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/58cbd0af0aeb16625b809ed8
=> [ios] Fixed crash in street editor.

drape/hw_texture.cpp, platform/platform.hpp, platform/platform_ios.mm, platform/platform_unix_impl.cpp
=> Attempt to fix strange GL behaviour on iOS8

drape_frontend/apply_feature_functors.cpp, indexer/road_shields_parser.cpp
https://jira.mail.ru/browse/MAPSME-4102
=> Improved default road shields

generator/routing_index_generator.cpp
При запуске генерации всего мира падало с исключением.
=> [routing] fix cross mwm section generator

search/search_quality/assessment_tool/CMakeLists.txt, search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_model.hpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/assessment_tool/result_view.cpp, search/search_quality/assessment_tool/result_view.hpp, search/search_quality/assessment_tool/results_view.cpp, search/search_quality/assessment_tool/results_view.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/assessment_tool/view.hpp, search/search_quality/features_collector_tool/features_collector_tool.cpp, search/search_quality/matcher.cpp, search/search_quality/matcher.hpp, search/search_quality/sample.cpp, search/search_quality/sample.hpp
=> [assessment-tool] Implemented radio-buttons for relevances.

drape_frontend/read_manager.cpp, drape_frontend/read_manager.hpp
=> [drape] Surrogate atomic exchange on Linux.

strings.txt
Fix romanian translations for share
=> Fix romanian translations for share

feature_list/feature_list.cpp, omim.pro
Немного изменений в feature_list, которые давно использовал, но не доходили руки сделать PR.
=> [feature_list] Update feature_list for new feeds

indexer/road_shields_parser.cpp
Cherry peak https://github.com/mapsme/omim/pull/5676
=> [RELEASE-72] Fixed state road shields in US

indexer/road_shields_parser.cpp
Cherry pick https://github.com/mapsme/omim/pull/5628
=> [RELEASE-72-ONLY] Improved default road shields

indexer/road_shields_parser.cpp
https://jira.mail.ru/browse/MAPSME-4117
=> Fixed state road shields in US

search/search_quality/assessment_tool/CMakeLists.txt, search/search_quality/assessment_tool/edits.cpp, search/search_quality/assessment_tool/edits.hpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/result_view.cpp, search/search_quality/assessment_tool/result_view.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp
=> [assessment-tool] Editing support for relevances.

drape/overlay_tree.hpp, drape_frontend/CMakeLists.txt, drape_frontend/backend_renderer.cpp, drape_frontend/backend_renderer.hpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/drape_frontend.pro, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/message.hpp, drape_frontend/message_subclasses.hpp, drape_frontend/overlays_tracker.cpp, drape_frontend/overlays_tracker.hpp, map/framework.cpp, platform/platform_mac.mm
https://jira.mail.ru/browse/MAPSME-4128
=> Added overlay appearance tracking

search/search_quality/assessment_tool/CMakeLists.txt, search/search_quality/assessment_tool/Info.plist, search/search_quality/assessment_tool/assessment_tool.cpp, search/search_quality/assessment_tool/main_view.cpp
=> [assessment-tool] Fixed look and feel on MacOSX.

generator/routing_index_generator.cpp, routing/base/astar_algorithm.hpp, routing/cross_mwm_connector.cpp, routing/cross_mwm_connector.hpp, routing/geometry.cpp, routing/geometry.hpp, routing/index_graph_loader.cpp, routing/index_graph_loader.hpp, routing/vehicle_mask.hpp
Рассчёт весов для leap маршрутов между входами и выходами mwm.
Сохранение этих весов в cross mwm секцию.
Для Москвы рассчет занимает 30 минут.
=> [routing] Cross mwm leaps calculations

search/pysearch/CMakeLists.txt
=> Fix search pybinding build.

iphone/Maps/Classes/MapsAppDelegate.mm, iphone/Maps/Maps.xcodeproj/project.pbxproj, iphone/Maps/UI/PlacePage/BannersCache.swift, iphone/Maps/UI/PlacePage/CacheableFacebookBanner.swift, iphone/Maps/UI/PlacePage/MWMPlacePageData.mm, iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
https://confluence.mail.ru/display/MAPSME/Facebook+Native+Ads#FacebookNativeAds-Statistics (Architecture paragraph)
=> [ios] Added caching to banners.

data/copyright.html
Exactly what it says on the tin.
=> [icu] Copyright for libICU

android/src/com/mapswithme/maps/editor/EditorHostFragment.java
https://jira.mail.ru/browse/MAPSME-4166
=> Change logic for newcomers message

android/src/com/mapswithme/maps/editor/EditorHostFragment.java
=> [android] Change logic for newcomers message

map/city_finder.hpp, map/framework.cpp, map/framework.hpp, map/map.pro, map/place_page_info.cpp, map/place_page_info.hpp, partners_api/booking_api.cpp, partners_api/booking_api.hpp
Cherry pick for https://github.com/mapsme/omim/pull/5706
=> Search on booking cherry pick

search/search_quality/assessment_tool/CMakeLists.txt, search/search_quality/assessment_tool/context.cpp, search/search_quality/assessment_tool/context.hpp, search/search_quality/assessment_tool/edits.cpp, search/search_quality/assessment_tool/edits.hpp, search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_model.hpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/assessment_tool/result_view.cpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/assessment_tool/samples_view.cpp, search/search_quality/assessment_tool/samples_view.hpp, search/search_quality/assessment_tool/view.hpp
=> [assessment-tool] Store edits on the model side.

docs/CONTRIBUTING.md, docs/INSTALL.md
Сергей Е. помог обновить инструкции по сборке приложения в XCode.
=> [docs] Updated iOS building instructions

CMakeLists.txt, drape/drape_tests/CMakeLists.txt, generator/generator_tool/CMakeLists.txt, openlr/openlr_stat/CMakeLists.txt, qt/CMakeLists.txt, routing/routing_consistency_tests/CMakeLists.txt, search/search_quality/assessment_tool/CMakeLists.txt, search/search_quality/features_collector_tool/CMakeLists.txt, search/search_quality/search_quality_tool/CMakeLists.txt
=> [build] Added option for Address Sanitizer.

3party/jansson/myjansson.cpp, 3party/jansson/myjansson.hpp, generator/region_meta.cpp, partners_api/booking_api.cpp, partners_api/partners_api_tests/uber_tests.cpp, partners_api/uber_api.cpp, search/search_quality/helpers.cpp, search/search_quality/helpers.hpp, search/search_quality/sample.cpp, search/search_quality/sample.hpp, search/search_quality/search_quality_tests/sample_test.cpp, storage/country.cpp
=> [search] Added search samples json serialization.

android/src/com/mapswithme/util/log/LogCatStrategy.java
…collect it in Fabric
@darina @goblinr PTAL
Made writing INFO/WARNING/ERROR logs to Logcat for release builds to collect all these logs in Fabric system.
=> Mapsme 4188 return logging for crashlytics

map/place_page_info.cpp, partners_api/ads_base.cpp, partners_api/ads_base.hpp, partners_api/ads_engine.cpp, partners_api/ads_engine.hpp, partners_api/partners_api_tests/ads_engine_tests.cpp, partners_api/partners_api_tests/facebook_tests.cpp, partners_api/partners_api_tests/rb_tests.cpp, partners_api/rb_ads.cpp
https://jira.mail.ru/browse/MAPSME-4199
=> Restrictions for banners

.gitignore, coding/file_container.cpp, coding/file_container.hpp, drape_frontend/backend_renderer.cpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/message.hpp, drape_frontend/message_subclasses.hpp, drape_frontend/read_manager.cpp, drape_frontend/read_manager.hpp, drape_frontend/requested_tiles.cpp, drape_frontend/requested_tiles.hpp, map/CMakeLists.txt, map/framework.cpp, map/framework.hpp, map/hla_manager.cpp, map/hla_manager.hpp, map/local_ads_manager.cpp, map/local_ads_manager.hpp, map/map.pro
https://jira.mail.ru/browse/MAPSME-4189
=> Added Hyper Local Ads (HLA) manager

search/search_quality/search_quality_tool/CMakeLists.txt, search/search_quality/search_quality_tool/search_quality_tool.pro
=> [search] search quality tool fix

data/countries.txt, data/external_resources.txt
=> [planet] New data from 28.03.2017

xcode/map/map.xcodeproj/project.pbxproj
=> xcode compilation fix

android/gradle.properties
@therearesomewhocallmetim PTAL
=> [android] Update version to 7.2.2

feature_list/feature_list.cpp
А то в сайте не хватает разных стадионов и адвокатов.
=> [feature_list] Add sport and office categories to POI

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/statistics/Statistics.java
http://jira.65apps.com/browse/MAP-187
=> [android] Added statistic event for search booking button click.

map/framework.cpp, map/framework.hpp, map/local_ads_manager.cpp, map/local_ads_manager.hpp, search/search_quality/assessment_tool/assessment_tool.cpp
=> [framework] Framework flag to disable ads.

search/CMakeLists.txt, search/feature_loader.cpp, search/feature_loader.hpp, search/house_detector.cpp, search/house_detector.hpp, search/search.pro, search/search_quality/assessment_tool/CMakeLists.txt, search/search_quality/assessment_tool/context.cpp, search/search_quality/assessment_tool/context.hpp, search/search_quality/assessment_tool/edits.cpp, search/search_quality/assessment_tool/edits.hpp, search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_model.hpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/assessment_tool/model.hpp, search/search_quality/assessment_tool/result_view.cpp, search/search_quality/assessment_tool/result_view.hpp, search/search_quality/assessment_tool/results_view.cpp, search/search_quality/assessment_tool/results_view.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/assessment_tool/samples_view.cpp, search/search_quality/assessment_tool/samples_view.hpp, search/search_quality/assessment_tool/view.hpp, search/search_quality/features_collector_tool/features_collector_tool.cpp, search/search_quality/matcher.cpp, search/search_quality/matcher.hpp, search/search_quality/sample.cpp, search/search_quality/sample.hpp
=> [assessment-tool] Save/SaveAs

generator/generator_tests/restriction_collector_test.cpp, generator/restriction_collector.hpp
=> Generator test fix.

search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_model.hpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/assessment_tool/model.hpp, search/search_quality/assessment_tool/results_view.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/assessment_tool/samples_view.hpp, search/search_quality/assessment_tool/view.hpp
* implemented save dialog on open/quit
* re-used viewport move to the search result
=> [assessment-tool] Several improvements

android/jni/com/mapswithme/maps/Framework.cpp, drape_frontend/CMakeLists.txt, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/drape_frontend.pro, drape_frontend/drape_hints.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp, iphone/Maps/Classes/EAGLView.mm, map/framework.cpp, map/framework.hpp, xcode/drape_frontend/drape_frontend.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-4205
=> Don't follow to my position in case of launch by deep link.

android/jni/Android.mk, coding/file_reader.cpp, coding/file_reader.hpp, coding/multilang_utf8_string.hpp, iphone/Maps/Maps.xcodeproj/project.pbxproj, local_ads/CMakeLists.txt, local_ads/local_ads.pro, local_ads/local_ads_helpers.cpp, local_ads/local_ads_helpers.hpp, local_ads/local_ads_tests/CMakeLists.txt, local_ads/local_ads_tests/local_ads_helpers_tests.cpp, local_ads/local_ads_tests/local_ads_tests.pro, map/framework.cpp, map/local_ads_manager.cpp, map/local_ads_manager.hpp, map/map_tests/CMakeLists.txt, map/map_tests/map_tests.pro, mapshot/mapshot.pro, omim.pro, qt/CMakeLists.txt, qt/qt.pro, search/search_quality/assessment_tool/CMakeLists.txt, storage/storage_integration_tests/CMakeLists.txt, storage/storage_integration_tests/storage_integration_tests.pro, xcode/base/base.xcodeproj/project.pbxproj, xcode/local_ads/local_ads.xcodeproj/project.pbxproj, xcode/map/map.xcodeproj/project.pbxproj, xcode/omim.xcworkspace/contents.xcworkspacedata
- Переделано персистентное хранение
- Добавлена интеграция с библиотекой local_ads
- Библиотека local_ads добавлена в сборку под qmake, xcode и android studio
=> Refactored local ads manager

android/src/com/mapswithme/maps/bookmarks/data/MapObject.java
@milchakov PTAL
https://jira.mail.ru/browse/MAPSME-4234
=> [android] Fixed marshaling/unmarshaling for MapObject class

android/gradle.properties
=> [android] Updated version to 7.2.3

iphone/Maps/UI/Editor/MWMEditorViewController.mm
=> [ios] Fixed 4167

editor/osm_auth.cpp, editor/osm_auth_tests/osm_auth_tests.cpp
Поднял сервер http://test.osmz.ru и обновил ключи. Теперь тесты работают. Убрал тестирование google/facebook, потому что механизм входа нынче иной.
=> [tests] Fix osm auth tests

partners_api/facebook_ads.cpp, partners_api/facebook_ads.hpp, partners_api/partners_api_tests/ads_engine_tests.cpp, partners_api/partners_api_tests/facebook_tests.cpp, partners_api/partners_api_tests/rb_tests.cpp, partners_api/rb_ads.cpp
https://jira.mail.ru/browse/MAPSME-4254
https://jira.mail.ru/browse/MAPSME-4272
=> Ads hot fix

android/gradle.properties
=> [android] Update version to 7.2.4

tools/python/local_ads/features_db_updater.py, tools/python/mwm/ft2osm.py, tools/python/mwm/mwm.py
=> Add a script to generate mappings in csv.

map/framework.cpp, map/framework.hpp, search/search_quality/assessment_tool/context.cpp, search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_model.hpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/assessment_tool/model.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/assessment_tool/view.hpp
https://jira.mail.ru/browse/MAPSME-4261
=> [assessment-tool] Added buttons that display user position and viewport.

partners_api/facebook_ads.cpp, partners_api/facebook_ads.hpp, partners_api/partners_api_tests/ads_engine_tests.cpp, partners_api/partners_api_tests/facebook_tests.cpp, partners_api/partners_api_tests/rb_tests.cpp, partners_api/rb_ads.cpp
cherry pick from 75e81076420a364807039a19b0f19ebf91e0a69c
=> Ads hot fix master

CMakeLists.txt, base/CMakeLists.txt, base/base.pro, base/pprof.cpp, base/pprof.hpp, search/geocoder.cpp
=> [base] Implemented a wrapper around pprof.

iphone/Maps/UI/Migration/MWMMigrationView.mm, iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm, iphone/Maps/UI/PlacePage/MWMPlacePageProtocol.h, map/framework.cpp, map/framework.hpp
https://confluence.mail.ru/display/MAPSME/Auto+update+maps
=> Added after update logic.

pyhelpers/vector_uint8.hpp
=> Fix vector_uint8t_to_str to work woth both python 2 and 3.

android/gradle.properties, android/src/com/mapswithme/maps/ads/FacebookNativeAd.java, android/src/com/mapswithme/maps/ads/MwmNativeAd.java, android/src/com/mapswithme/maps/ads/MyTargetNativeAd.java, android/src/com/mapswithme/maps/widget/placepage/BannerController.java
=> Cherry-picks on master

iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/58cbeab30aeb16625b81317b
=> [crash-fix] [ios] Crash fix.

partners_api/ads_engine.cpp, partners_api/banner.hpp, partners_api/mopub_ads.cpp, partners_api/mopub_ads.hpp, partners_api/partners_api.pro, partners_api/partners_api_tests/ads_engine_tests.cpp, partners_api/partners_api_tests/mopub_tests.cpp, partners_api/partners_api_tests/partners_api_tests.pro
Mopub вместо фэйсбука
https://jira.mail.ru/browse/MAPSME-4281
=> Mopub core

map/framework.cpp, map/framework.hpp, partners_api/ads_base.cpp, partners_api/ads_base.hpp, partners_api/ads_engine.cpp, partners_api/ads_engine.hpp, partners_api/facebook_ads.hpp, partners_api/mopub_ads.cpp, partners_api/mopub_ads.hpp, partners_api/partners_api_tests/ads_engine_tests.cpp
https://jira.mail.ru/browse/MAPSME-4295
=> Banners for search

android/3rd_party/BottomSheet/build.gradle, android/UnitTests/build.gradle, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties
=> [android] Updated gradle to 3.3

android/AndroidManifest.xml, android/build.gradle, android/src/com/mapswithme/maps/ads/Banner.java, android/src/com/mapswithme/maps/ads/BaseMwmNativeAd.java, android/src/com/mapswithme/maps/ads/CachingNativeAdLoader.java, android/src/com/mapswithme/maps/ads/CompoundNativeAdLoader.java, android/src/com/mapswithme/maps/ads/FacebookAdsLoader.java, android/src/com/mapswithme/maps/ads/FacebookNativeAd.java, android/src/com/mapswithme/maps/ads/Factory.java, android/src/com/mapswithme/maps/ads/MopubAdError.java, android/src/com/mapswithme/maps/ads/MopubNativeAd.java, android/src/com/mapswithme/maps/ads/MopubNativeDownloader.java, android/src/com/mapswithme/maps/ads/MwmNativeAd.java, android/src/com/mapswithme/maps/ads/MyTargetAdsLoader.java, android/src/com/mapswithme/maps/ads/MyTargetNativeAd.java, android/src/com/mapswithme/maps/ads/NativeAdListener.java, android/src/com/mapswithme/maps/ads/Providers.java, android/src/com/mapswithme/maps/widget/placepage/BannerController.java, android/src/com/mapswithme/util/statistics/Statistics.java, android/src/com/mopub/nativeads/FacebookNative.java
https://jira.mail.ru/browse/MAPSME-4284
=> [android] Added Mopub ad network

map/place_page_info.cpp, map/place_page_info.hpp
https://jira.mail.ru/browse/MAPSME-4298
=> Into PP info added a wrapper for secondary feature name.

drape_frontend/traffic_generator.cpp, drape_frontend/traffic_renderer.cpp
https://jira.mail.ru/browse/MAPSME-3703
=> Added arrows to green traffic segments

android/src/com/mapswithme/maps/ads/FacebookNativeAd.java, android/src/com/mapswithme/maps/ads/MopubNativeAd.java, android/src/com/mapswithme/maps/ads/MwmNativeAd.java, android/src/com/mapswithme/maps/ads/MyTargetNativeAd.java, android/src/com/mapswithme/maps/widget/placepage/BannerController.java, android/src/com/mapswithme/util/UiUtils.java, android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-4307
=> Mapsme 4307 mopub privacy notice

indexer/feature_utils.cpp, indexer/feature_utils.hpp, indexer/indexer_tests/feature_names_test.cpp, map/framework.cpp, partners_api/booking_api.cpp, partners_api/booking_api.hpp
https://jira.mail.ru/browse/MAPSME-4290
=>  Booking search changes

iphone/Maps/Classes/CustomAlert/DownloadTransitMapsAlert/MWMDownloadTransitMapAlert.mm, platform/mwm_traits.cpp, platform/mwm_traits.hpp, platform/mwm_version.hpp, routing/car_router.cpp, routing/car_router.hpp, storage/storage.cpp, storage/storage.hpp
Обработка смеси mwm разных версий.
Подробнее тут:
https://jira.mail.ru/browse/MAPSME-3905
[DNM] - мержить надо, но в четко выбранный момент, когда будет готовиться соответствующая версия.
=> [routing] Cross mwm mix handling

android/jni/com/mapswithme/maps/SearchEngine.cpp, android/res/drawable-v21/search_la_customer_result.xml, android/res/drawable-v21/search_la_customer_result_night.xml, android/res/drawable/search_la_customer_result.xml, android/res/drawable/search_la_customer_result_night.xml, android/res/values/colors.xml, android/res/values/themes-attrs.xml, android/res/values/themes-base.xml, android/src/com/mapswithme/maps/search/SearchAdapter.java, android/src/com/mapswithme/maps/search/SearchResult.java, iphone/Maps/Core/Search/MWMSearch.mm, iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm, iphone/Maps/UI/Search/TableView/MWMSearchTableViewController.mm, map/framework.cpp, map/framework.hpp, map/local_ads_manager.cpp, map/local_ads_manager.hpp, search/everywhere_search_callback.cpp, search/everywhere_search_callback.hpp, search/hotels_classifier.cpp, search/hotels_classifier.hpp, search/processor.cpp, search/result.cpp, search/result.hpp, search/search.pro, xcode/search/search.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-4258
=> [core][android][ios] tint local ads customers in search results

local_ads/local_ads_tests/CMakeLists.txt, search/search_quality/search_quality_tests/CMakeLists.txt
=> [build] Fixed linux cmake build.

android/src/com/mapswithme/maps/location/AndroidNativeProvider.java, android/src/com/mapswithme/maps/location/LocationHelper.java
https://jira.mail.ru/browse/MAPSME-4289
https://jira.mail.ru/browse/MAPSME-4286
=> [android] fix SecurityException and my position button mode

3party/jansson/myjansson.cpp, 3party/jansson/myjansson.hpp, map/local_ads_manager.cpp, partners_api/booking_api.cpp, partners_api/partners_api_tests/uber_tests.cpp, partners_api/uber_api.cpp, search/search_quality/assessment_tool/context.cpp, search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/assessment_tool/view.hpp, storage/country.cpp
@rokuz @milchakov @bykoianko PTAL
=> [build] Various fixes to master build.

search/search_quality/assessment_tool/main_model.cpp, search/search_quality/features_collector_tool/features_collector_tool.cpp, search/search_quality/gen-samples.lisp, search/search_quality/sample.cpp, search/search_quality/sample.hpp, search/search_quality/search_quality_tests/sample_test.cpp
=> [search] Single json array is replaced by lines of json objects.

base/CMakeLists.txt, base/base.pro, base/get_time.hpp, base/timer.cpp, partners_api/booking_api.cpp, std/iomanip.hpp
=> [build] Fixed get_time/put_time on Linux.

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/settings/MapPrefsFragment.java, android/src/com/mapswithme/util/Config.java, android/src/com/mapswithme/util/ThemeSwitcher.java
@goblinr @rokuz PTAL
https://jira.mail.ru/browse/MAPSME-4208
=> [android] Added support for vehicle map styles

android/src/com/mapswithme/maps/ads/CachingNativeAdLoader.java
@goblinr PTAL
https://jira.mail.ru/browse/MAPSME-4330
=> [android] Reduced request time for native ads

android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/res/layout-land/place_page_preview.xml, android/res/layout/place_page_preview.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java, android/src/com/mapswithme/maps/bookmarks/data/MapObject.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/search/SearchFragment.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
@goblinr @darina PTAL
https://jira.mail.ru/browse/MAPSME-4328
=> [android] Added transliteration in PP

search/search_quality/search_quality_tests/sample_test.cpp
=> [search] Fixed search quality tests.

indexer/drules_selector.cpp
=> [style] Fix error with IsHotelChecker

std/iomanip.hpp
=> [std] Removed target_os inclusion.

map/map_tests/transliteration_test.cpp
Исправление тестов после https://github.com/mapsme/omim/pull/5887
=> Fixed transliteration tests

map/place_page_info.cpp, partners_api/ads_base.cpp, partners_api/ads_base.hpp, partners_api/ads_engine.cpp, partners_api/ads_engine.hpp, partners_api/partners_api_tests/ads_engine_tests.cpp, partners_api/partners_api_tests/facebook_tests.cpp, partners_api/partners_api_tests/mopub_tests.cpp, partners_api/partners_api_tests/rb_tests.cpp, partners_api/rb_ads.cpp
https://jira.mail.ru/browse/MAPSME-4303
=> Added user language check in RB banners appearing logic

android/jni/com/mapswithme/core/jni_helper.cpp, android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/jni/com/mapswithme/maps/UserMarkHelper.hpp, android/res/layout-land/place_page_details.xml, android/res/layout/place_page_add.xml, android/res/layout/place_page_add_business.xml, android/res/layout/place_page_details.xml, android/res/layout/place_page_local_ad.xml, android/res/values/strings.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/ads/LocalAdInfo.java, android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java, android/src/com/mapswithme/maps/bookmarks/data/MapObject.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/search/SearchFragment.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/Utils.java, strings.txt
=> Mapsme 4311 create ad local button

3party/jansson/myjansson.cpp, 3party/jansson/myjansson.hpp, search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/assessment_tool/view.hpp, search/search_quality/features_collector_tool/features_collector_tool.cpp, search/search_quality/helpers.cpp, search/search_quality/helpers.hpp, search/search_quality/sample.cpp, search/search_quality/sample.hpp, search/search_quality/search_quality_tests/CMakeLists.txt, search/search_quality/search_quality_tests/sample_test.cpp, search/search_quality/search_quality_tests/search_quality_tests.pro
=> [assessment-tool] Allow null values in positions.

iphone/Maps/Core/Ads/Facebook/FacebookBanner.swift, iphone/Maps/Core/Ads/Mopub/MopubBanner.swift, iphone/Maps/Core/Ads/RB/RBBanner.swift
=> [MAPSME-4331] [ios] Reduced min banner time on screen.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/routing/RoutingPlanController.java, android/src/com/mapswithme/maps/routing/RoutingPlanFragment.java
@goblinr PTAL
https://jira.mail.ru/browse/MAPSME-4152
=> [android] Fixed the crash while tapping on start button in Uber case

android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/routing/RoutingPlanController.java
https://jira.mail.ru/browse/MAPSME-4313
=> [android] Disabled mobile data check for a taxi

map/framework.cpp, map/framework.hpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp
=> [assessment-tool] Added marks for found results.

configure.sh, local_ads/config.hpp, map/framework.cpp, map/local_ads_manager.cpp, map/local_ads_manager.hpp
Дубликат на мастер https://github.com/mapsme/omim/pull/5914
=> Added usage of stage server

indexer/feature_utils.cpp, indexer/feature_utils.hpp, indexer/indexer_tests/feature_names_test.cpp
https://jira.mail.ru/browse/MAPSME-4337
=> Extended languages for device language

android/res/layout-land/place_page_details.xml, android/res/layout/place_page_details.xml, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
@goblinr PTAL
https://jira.mail.ru/browse/MAPSME-4353
=> [android] Added dividers for last section buttons in PP

android/src/com/mapswithme/maps/settings/MiscPrefsFragment.java, android/src/com/mapswithme/util/Config.java, android/src/com/mapswithme/util/NetworkPolicy.java
https://jira.mail.ru/browse/MAPSME-4101
=> [android] Added NONE state for 3g aware settings

android/src/com/mapswithme/maps/ads/BaseNativeAdLoader.java, android/src/com/mapswithme/maps/ads/CachingNativeAdLoader.java, android/src/com/mapswithme/maps/ads/CompoundNativeAdLoader.java, android/src/com/mapswithme/maps/ads/NativeAdLoader.java
https://jira.mail.ru/browse/MAPSME-4326
=> [android] Empty banner fix

indexer/feature_utils.cpp, indexer/feature_utils.hpp, indexer/indexer_tests/feature_names_test.cpp
Описание текущей логики в хедере https://github.com/mapsme/omim/pull/5933/files#diff-630930479162287273c11cc92bb96079
=> Poi naming fix

local_ads/pylocal_ads/CMakeLists.txt
=> Fix pylocal_ads.so build for linux.

pyhelpers/specs/python35-mapsme-modules.spec
=> Add rpmspeck for python3 bindings.

iphone/Maps/UI/PlacePage/MWMPlacePageData.h, iphone/Maps/UI/PlacePage/MWMPlacePageData.mm, iphone/Maps/UI/PlacePage/PlacePageLayout/Content/ButtonCell/MWMPlacePageButtonCell.h, iphone/Maps/UI/PlacePage/PlacePageLayout/Content/ButtonCell/MWMPlacePageButtonCell.mm, iphone/Maps/UI/PlacePage/PlacePageLayout/Content/RegularCell/MWMPlacePageRegularCell.mm, iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-4372
=> [ios] Changed pp buttons position.

android/src/com/mapswithme/maps/ads/CachingNativeAdLoader.java, android/src/com/mapswithme/maps/ads/MopubNativeAd.java, android/src/com/mapswithme/maps/ads/MopubNativeDownloader.java
https://jira.mail.ru/browse/MAPSME-4381
=> [android] Added click tracking for mopub ads

generator/generator_tests/road_access_test.cpp, generator/generator_tests_support/test_feature.cpp, generator/generator_tests_support/test_feature.hpp, generator/osm_translator.hpp, generator/road_access_generator.cpp, generator/road_access_generator.hpp, generator/routing_helpers.cpp, map/framework.cpp, routing/CMakeLists.txt, routing/road_access.cpp, routing/road_access.hpp, routing/road_access_serialization.hpp, routing/router.cpp, routing/router.hpp, routing/routing.pro, routing/routing_tests/road_access_test.cpp, routing/vehicle_mask.cpp, routing/vehicle_mask.hpp
1. Структура для хранения информации о проходимости для каждого сегмента для всех поддерживаемых роутеров.
2. Её сериализация и поддержка в генераторе.
3. Использование будет отдельным PR.
=> [routing] [generator] Better road access.

generator/generator_tests/road_access_test.cpp, generator/generator_tests_support/test_feature.cpp, generator/generator_tests_support/test_feature.hpp, generator/osm_translator.hpp, generator/road_access_generator.cpp, generator/road_access_generator.hpp, generator/routing_helpers.cpp, map/framework.cpp, routing/CMakeLists.txt, routing/road_access.cpp, routing/road_access.hpp, routing/road_access_serialization.hpp, routing/router.cpp, routing/router.hpp, routing/routing.pro, routing/routing_tests/road_access_test.cpp, routing/vehicle_mask.cpp, routing/vehicle_mask.hpp
https://github.com/mapsme/omim/pull/5919
=> Cherry-pick of PR #5919

iphone/Maps/Core/Routing/MWMCoreRouterType.h
@igrechuhin @VladiMihaylenko PTAL
=> iOS build fix.

android/res/values/colors.xml
https://jira.mail.ru/browse/MAPSME-4165
=> [android] Button pressed accent color for night theme.

routing/cross_mwm_graph.hpp, routing/cross_mwm_index_graph.hpp, routing/cross_mwm_osrm_graph.hpp, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/world_graph.cpp, routing/world_graph.hpp
git cherry-pick [routing] Graph shortcut optimization for long routes.
Оригинальный PR: https://github.com/mapsme/omim/pull/5894
Исследование замены константы 2.0 для leap дуг: https://jira.mail.ru/browse/MAPSME-4414
=> [release-73] [routing] Graph shortcut optimization for long routes.

android/res/layout-land/place_page_details.xml, android/res/layout/place_page_button_frame.xml, android/res/layout/place_page_details.xml, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-4373
=> [android] redesign create ad campaign button

android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java, android/src/com/mapswithme/maps/bookmarks/data/MapObject.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/search/SearchFragment.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-4369
=> [android] Hyper local ads common statistics

android/gradle.properties
=> [android] Updated version to 7.3.0

android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
https://jira.mail.ru/browse/MAPSME-4408
=> [android] fix update maps indicator after autoupdate dialog

coding/coding_tests/zlib_test.cpp, coding/zlib.cpp, coding/zlib.hpp, map/local_ads_manager.cpp, platform/http_client_curl.cpp, traffic/traffic_info.cpp
@mpimenov @milchakov @rokuz PTAL
=> [coding] Added GZip support.

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
@goblinr @rokuz @milchakov  PTAL
https://jira.mail.ru/browse/MAPSME-4370
=> Mapsme 4370 add local ads statistic

routing/index_router.cpp, routing/road_graph_router.cpp, routing/routing_helpers.cpp, routing/routing_helpers.hpp
Отключение диаграммы высот маршрута при авто роутинге.
@VladiMihaylenko @dobriy-eeh @ygorshenin PTAL
https://jira.mail.ru/browse/MAPSME-4387
=> [routing] Stop altitude chart showing in car routing.

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-4428
=> [android] Added hiding of Booking views for other sponsored objects

android/src/com/mapswithme/maps/editor/EditorHostFragment.java
https://jira.mail.ru/browse/MAPSME-4422
=> [android] notes fix

iphone/Maps/Bookmarks/AddSetVC.mm, iphone/Maps/Bookmarks/BookmarksVC.mm
https://jira.mail.ru/browse/MAPSME-4421
=> [ios] Fixed crash with umlaut in bookmark's category name.

routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_loader.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/road_access_test.cpp
Cherry-pick of https://github.com/mapsme/omim/pull/5961
=> [routing] Road access cherry-pick to release.

routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/road_graph.hpp, routing/road_graph_router.cpp, routing/routing_helpers.hpp, routing/routing_tests/index_graph_test.cpp, routing/world_graph.hpp
Обобщение метода для проверки, является ли дуга "тупиковой"
Откидывание тупиковых дуг при поиске ближайших дуг к старту/финишу в index graph.
https://jira.mail.ru/browse/MAPSME-4341
=> [routing] Checking segment for acceptability

routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/road_graph.hpp, routing/road_graph_router.cpp, routing/routing_helpers.hpp, routing/routing_tests/index_graph_test.cpp, routing/world_graph.hpp
cherry-pick https://github.com/mapsme/omim/pull/5968
@dobriy-eeh PTAL
=> [release 73] [routing] Checking phantom nodes for acceptability by trying go with BFS.

routing/index_router.cpp
https://jira.mail.ru/browse/MAPSME-4323
@dobriy-eeh @ygorshenin PTAL
=> [routing] Loading maps in case of an attempt of route creation to the place where maps are absent.

xcode/routing/routing.xcodeproj/project.pbxproj
=> xcode build fix.

data/countries.txt, data/external_resources.txt
=> [planet] New data from 28.04.2017

android/src/com/mapswithme/maps/routing/RoutingPlanController.java, android/src/com/mapswithme/maps/uber/UberAdapter.java, android/src/com/mapswithme/maps/uber/UberInfo.java
[android] Replaced array with list
https://jira.mail.ru/browse/MAPSME-4417
=> [android] Fixed the crash while deserialization of uber info array

openlr/openlr_simple_decoder.cpp, openlr/openlr_stat/openlr_stat.cpp
=> [openlr] More warning messages from matching tool.

tools/python/local_ads/features_db_updater.py
=> Improve features_db_updater.py.

map/framework.cpp, map/framework.hpp
https://jira.mail.ru/browse/MAPSME-4431
https://jira.mail.ru/browse/MAPSME-4438
=> [routing] Fixed spontaneous setting of the pedestrian router.

android/jni/com/mapswithme/maps/editor/Editor.cpp, android/src/com/mapswithme/maps/editor/Editor.java, android/src/com/mapswithme/maps/editor/EditorFragment.java, iphone/Maps/UI/Editor/MWMEditorViewController.mm
https://jira.mail.ru/browse/MAPSME-4334
=> [editor] Hide 'levels' field for buildings which were added as point.

android/src/com/mapswithme/maps/routing/BaseRoutingErrorDialogFragment.java, android/src/com/mapswithme/maps/routing/RoutingErrorDialogFragment.java
https://jira.mail.ru/browse/MAPSME-4433
=> [android] fix wrong download size calculation

map/bookmark_manager.cpp, map/framework.cpp, map/gps_track_filter.cpp, map/gps_tracker.cpp, platform/settings.hpp
Cherry-pick of https://github.com/mapsme/omim/pull/6006
=> [platform] Check the result of Settings::Get.

local_ads/config.hpp
Не мержить без разрешения Артема!
=> [RELEASE ONLY] Local ads switched to prod servers

routing/index_router.cpp
Починка бага https://jira.mail.ru/browse/MAPSME-3778
Суть бага: при следованию по маршруту оставшееся время уменьшалось до 1 минуты в середине маршрута, после чего остаток пути так и показывало 1 минуту.
=> [release-73][routing] Fix remaining route time

strings.txt
=> remove-ad-translate

iphone/Maps/Core/Search/MWMSearch.mm
Дублирование https://github.com/mapsme/omim/pull/5583 на release-73
https://jira.mail.ru/browse/MAPSME-4061
=> Fixed showing of a single search result on iPad.

routing/edge_estimator.cpp, routing_common/car_model.cpp
Скорости для car model из последнего письма @ygorshenin.
Экспериментальный PR, чтобы собрать версию и протестировать что выйдет.
Магический фактор 1.8 применяется только к сегментам, на которых есть пробки.
=> [routing] Car model speeds

android/src/com/mapswithme/maps/widget/placepage/BannerController.java, android/src/com/mapswithme/util/statistics/Statistics.java
@milchakov PTAL
https://jira.mail.ru/browse/MAPSME-4449
=> [android] Added mytracker events for banners

CMakeLists.txt
Я бы ещё передвинул это сообщение в самое начало лога, но сейчас при повторном запуске оно и так второе. WDYT?
=> [cmake] Show build type.

android/jni/com/mapswithme/maps/MapManager.cpp, iphone/Maps/Core/Storage/MWMStorage.mm, map/framework.cpp, storage/storage.cpp, storage/storage.hpp, storage/storage_helpers.cpp, storage/storage_helpers.hpp
IsEnoughSpaceForDownload() поправлена для случая, когда размер mwm уменьшается.
@VladiMihaylenko @syershov PTAL
=> [release-73] IsEnoughSpaceForDownload() fix. Case when mwm size becomes smaller.

storage/storage_helpers.cpp, storage/storage_helpers.hpp
Учет комментариев в https://github.com/mapsme/omim/pull/6018 после мержа.
@ygorshenin @dobriy-eeh PTAL
=> IsEnoughSpaceForDownload() refactoring.

iphone/Maps/Bookmarks/BookmarksRootVC.mm, iphone/Maps/Bookmarks/BookmarksVC.mm, iphone/Maps/Common/MWMConsts.h, iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
https://jira.mail.ru/browse/MAPSME-3866
=> [ios] Fixed crash while deleting bookmark.

iphone/Maps/Classes/Components/BorderedButton.swift
https://jira.mail.ru/browse/MAPSME-4459
=> [ios] Fixed wrong border color of button.

android/jni/com/mapswithme/maps/editor/Editor.cpp, indexer/indexer_tests/osm_editor_test.cpp, indexer/osm_editor.cpp, indexer/osm_editor.hpp, iphone/Maps/UI/Editor/MWMEditorViewController.mm, map/framework.cpp, map/framework.hpp
https://jira.mail.ru/browse/MAPSME-4468
Теперь текст будет выглядеть примерно так:
```
User's comment: Парка нету; 
Poi name: Тайницкий Сад; 
Poi types: leisure-park ; 
OSM data version: 2017-04-28T19:09:51Z; 
The place has gone or never existed. This is an auto-generated note from MAPS.ME application: a user reports a POI that is visible on a map (which can be outdated), but cannot be found on the ground. 
#mapsme
```
```
User's comment: - ; 
Poi name: - ; 
Poi types: amenity-bar ; 
OSM data version: 2017-04-28T19:09:51Z; 
#mapsme
```
=> [editor] Notes reformatting

drape/shaders/route_dash_fragment_shader.fsh, drape_frontend/route_shape.cpp
https://jira.mail.ru/browse/MAPSME-4480
=> Fixed false optimization on Mali-G71

3party/jansson/myjansson.cpp, 3party/jansson/myjansson.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/sample.cpp, search/search_quality/sample.hpp, search/search_quality/search_quality_tests/sample_test.cpp
=> [assessment-tool] Added support for related queries.

routing/index_router.cpp
=> Revert https://github.com/mapsme/omim/pull/6043

drape_frontend/frontend_renderer.cpp
https://jira.mail.ru/browse/MAPSME-4204
=> Pull to bound area after a new visible viewport received.

drape_frontend/stylist.cpp
https://jira.mail.ru/browse/MAPSME-4492
=> Fixed style switch in stylist

data/countries.txt, data/external_resources.txt
=> [planet] Very fresh data from 11.05.2017

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/api/ParsedUrlMwmRequest.java, defines.hpp, iphone/Maps/Classes/MapsAppDelegate.mm, map/local_ads_manager.cpp, map/map_tests/mwm_url_tests.cpp, map/mwm_url.cpp, map/mwm_url.hpp, platform/CMakeLists.txt, platform/marketing_service.cpp, platform/marketing_service.hpp, platform/platform.pro, platform/settings.cpp, platform/settings.hpp, platform/string_storage_base.cpp, platform/string_storage_base.hpp, xcode/platform/platform.xcodeproj/project.pbxproj
@goblinr ptal
https://jira.mail.ru/browse/MAPSME-4484
=> Marketing api request.

drape_frontend/my_position_controller.cpp
https://jira.mail.ru/browse/MAPSME-4278
=> On devices without compass start routing in follow-and-rotate mode.

android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-4499
=> [android] Hide search controls when navigation session start

android/AndroidManifest.xml, android/src/com/mapswithme/maps/DownloadResourcesActivity.java
https://jira.mail.ru/browse/MAPSME-4488
=> [android] Added intent processor for lead url

openlr/router.hpp
=> [openlr] Small improvements.

3party/opening_hours/opening_hours.cpp, 3party/opening_hours/opening_hours.hpp, 3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp, editor/ui2oh.cpp
https://jira.mail.ru/browse/MAPSME-4173
=> Opening hours twenty four hours fix

drape/gpu_program_manager.cpp, drape/gpu_program_manager.hpp, tools/autobuild/shader_preprocessor.py
https://jira.mail.ru/browse/MAPSME-4487
=> Don't count texture inside Samsung Google Nexus workaround.

android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-4474
=> [android] Fix navigation buttons bottom limit calculation

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java, android/src/com/mapswithme/maps/news/BaseNewsFragment.java, android/src/com/mapswithme/maps/news/NewsFragment.java
=> [android] Fix map updater dialog behaviour.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/SplashActivity.java, android/src/com/mapswithme/maps/ads/LikesManager.java, android/src/com/mapswithme/maps/news/NewsFragment.java, android/src/com/mapswithme/util/Config.java, android/src/com/mapswithme/util/Counters.java
https://jira.mail.ru/browse/MAPSME-4085
=> [android] Review request improvement

android/src/com/mapswithme/maps/ads/CompoundNativeAdLoader.java, android/src/com/mapswithme/maps/ads/MopubNativeDownloader.java, android/src/com/mapswithme/maps/widget/placepage/BannerController.java
https://jira.mail.ru/browse/MAPSME-4555
=> [android] Fixed Mopub ad's shows tracking

android/src/com/mapswithme/maps/ads/CompoundNativeAdLoader.java, android/src/com/mapswithme/maps/ads/MopubNativeDownloader.java, android/src/com/mapswithme/maps/widget/placepage/BannerController.java
=> [cherry-pick] [android] Fixed Mopub ad's shows tracking

android/src/com/mapswithme/maps/MwmActivity.java
=> [cherry-pick][android] Fix navigation buttons bottom limit calculation

android/gradle.properties
=> [android] Updated version to 7.3.4

drape_frontend/shaders/shader_index.txt
https://jira.mail.ru/browse/MAPSME-4498
=> Fixed lines disappearing under hatching area

android/src/com/mapswithme/maps/editor/data/TimeFormatUtils.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-4174
https://jira.mail.ru/browse/MAPSME-2708
Плюс сделал названия дней недели с большой буквы. Согласовал с @igortomko .
=> [android] Opening hours fixes

search/intermediate_result.cpp, search/locality_scorer.cpp, search/ranking_info.cpp, search/ranking_utils.cpp, search/ranking_utils.hpp, search/search_quality/scoring_model.py, search/search_tests/ranking_tests.cpp
https://jira.mail.ru/browse/MAPSME-4452
Полностью не исправляет, т.к. первые 6 результатов полностью совпадают с запросом по имени, но по крайней мере упрощает код.
Current NDCG: 0.7311376267701065, std: 0.37243721556328185
NDCG mean: 0.7132874268236522, std: 0.3706336659832005
Accuracy: 0.7590711175616836
***** Linear model weights *****
DistanceToPivot: -0.37897824370302247
Rank: 1.0
FalseCats: -0.05775625793967508
Zero: -0.11436302557264734
Substring: 0.014295634567960331
Prefix: 0.046219090910780115
Full Match: 0.05384830009390816
POI: -0.09164609318265761
Building: -0.09164609318265761
Street: -0.0805969548653964
Unclassified: -0.030493728520630793
Village: -0.19242203325862917
City: -0.10945592241057521
State: 0.19250143015921584
Country: 0.31211330207867427
=> [search] Changed the name scoring scheme.

coding/transliteration.cpp, coding/transliteration.hpp, map/framework.cpp, map/framework.hpp, platform/settings.cpp
Дубликат https://github.com/mapsme/omim/pull/6128 на мастер
=> Translit setting master

android/gradle.properties, android/src/com/mapswithme/maps/ads/MopubNativeAd.java, android/src/com/mapswithme/maps/ads/MopubNativeDownloader.java
@milchakov PTAL
https://jira.mail.ru/browse/MAPSME-4555
=> [android][cherry-pick] Fixed mopub impression and clicks tracking

routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing_integration_tests/osrm_route_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_tests/index_graph_test.cpp, routing/world_graph.cpp, routing/world_graph.hpp
cherry-pick of https://github.com/mapsme/omim/pull/6091 to master
=> [master] Routing issue fixes.

data/categories.txt, strings.txt
Rebase of #5138 which was a rebase of #3846.
Again, just strings, no support in the code yet. All contributors have signed the CLA.
=> [strings] pt_BR translation + adjustments in pt_PT

data/categories.txt
=> [categories] Fixed bike parking Ukrainian translation

strings.txt
Edit russian translation for "Add place"
=> edit russian translation

drape/overlay_tree.cpp, drape/overlay_tree.hpp, drape_frontend/frontend_renderer.cpp
https://jira.mail.ru/browse/MAPSME-4591
=> Clear overlay tree on context destruction.

android/AndroidManifest.xml, android/build.gradle
https://jira.mail.ru/browse/MAPSME-4588
=> [android] Update pushwoosh to 4.12.2

drape_frontend/route_shape.cpp, drape_frontend/route_shape.hpp, drape_frontend/traffic_generator.cpp, drape_frontend/traffic_generator.hpp
https://jira.mail.ru/browse/MAPSME-4170
=> Fixed simplified traffic color scheme

android/src/com/mapswithme/maps/background/AppBackgroundTracker.java
=> [android] fixed bug with mVisibleAppLaunchListeners.

android/jni/com/mapswithme/util/Config.cpp, android/res/values/donottranslate.xml, android/res/xml/prefs_main.xml, android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java, android/src/com/mapswithme/util/Config.java
=> [cherry-pick][android] transliteration settings

generator/road_access_generator.cpp, tools/python/local_ads/mwm_to_csv_4localads.py, tools/unix/generate_mwm.sh, tools/unix/generate_planet.sh
Выпилил всё, связанное с генерацией роутинга на OSRM (отдельный скрипт пока не менял). Добавил задержку, чтобы ждать скачивания букинга, из-за отсутствия которой сломалась последняя сборка.
Также правит проблему в генераторе запретов поворотов, из-за которой он ругался на проблемы в данных OSM.
=> [generator] Replace OSRM routing in generate_planet.sh

qt/search_panel.cpp, qt/search_panel.hpp
=> [qt] Fixed freezing UI during search.

android/jni/com/mapswithme/platform/Platform.cpp, android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/util/BatteryState.java, android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-4643
=> [android] implemented Platform::GetChargingStatus() method.

android/jni/com/mapswithme/platform/Platform.cpp, android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/util/BatteryState.java, android/src/com/mapswithme/util/statistics/Statistics.java
=> [cherry-pick][android] implemented Platform::GetChargingStatus() method.

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/jni/com/mapswithme/maps/sound/tts.cpp, iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm, iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtons.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardEntity.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/Sound/MWMTextToSpeech.mm, iphone/Maps/Classes/MapsAppDelegate.mm, iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm, iphone/Maps/Core/Framework/MWMFrameworkListener.mm, iphone/Maps/Core/Location/MWMLocationManager.mm, iphone/Maps/Core/Routing/MWMRouter.mm, iphone/Maps/Core/Routing/MWMRouterSavedState.mm, iphone/Maps/Core/Storage/MWMStorage.mm, iphone/Maps/UI/BottomMenu/MWMBottomMenuViewController.mm, map/CMakeLists.txt, map/framework.cpp, map/framework.hpp, map/map.pro, map/routing_manager.cpp, map/routing_manager.hpp, platform/marketing_service.cpp, platform/marketing_service.hpp, qt/draw_widget.cpp, xcode/map/map.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-4599
=> Routing manager

indexer/CMakeLists.txt, indexer/indexer.pro, indexer/indexer_tests/CMakeLists.txt, indexer/indexer_tests/indexer_tests.pro, indexer/indexer_tests/wheelchair_tests.cpp, indexer/map_object.cpp, indexer/map_object.hpp, indexer/wheelchair.hpp, xcode/indexer/indexer.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-4607
=> [indexer] Wheelchair type info added into MapObject class

data/categories.txt
Для сборки версии для Танзании нужно перевести две строчки. Я её собираю из релизной ветки, поэтому реквест в неё.
=> [categories] Two Swahili translations

android/build.gradle
=> [android] Updated myTarget SDK to 4.6.14

android/src/com/mapswithme/maps/ads/MyTargetAdsLoader.java
=> [android] Fixed myTarget build

android/jni/com/mapswithme/maps/Framework.cpp, drape_frontend/user_mark_shapes.cpp, drape_frontend/user_marks_provider.hpp, iphone/Maps/Core/Routing/MWMRouter.mm, iphone/Maps/UI/PlacePage/MWMPlacePageData.h, iphone/Maps/UI/PlacePage/MWMPlacePageData.mm, iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm, iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMPlacePageActionBar.mm, map/CMakeLists.txt, map/bookmark_manager.cpp, map/framework.cpp, map/framework.hpp, map/map.pro, map/place_page_info.cpp, map/place_page_info.hpp, map/routing_manager.cpp, map/routing_manager.hpp, map/routing_mark.cpp, map/routing_mark.hpp, map/user_mark.cpp, map/user_mark.hpp, map/user_mark_container.hpp, xcode/map/map.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-4600
=> Route points based on UserMark.

android/3rd_party/BottomSheet/build.gradle, android/UnitTests/build.gradle, android/build.gradle
=> [android] Updated Gradle to 2.3.2

android/build.gradle, android/src/com/mapswithme/maps/ads/MyTargetAdsLoader.java
=> Mytarget update cherry pick

android/AndroidManifest.xml, android/src/com/mapswithme/maps/DownloadResourcesActivity.java, android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-4663
=> [android] Added SHOW_ON_MAP and BUILD_ROUTE intent actions.

search/locality_scorer.cpp
https://jira.mail.ru/browse/MAPSME-4715
=> [search] Fixed locality sorting.

generator/metalines_builder.cpp
Вчера писал читалку секции металиний, нашёл три ошибки в генераторе.
=> [generator] Fix metalines builder

android/AndroidManifest.xml, android/proguard-mwm.txt
=> [android] Fixed proguard mytarget build

map/framework.cpp, routing/turns.cpp
cherry pick https://github.com/mapsme/omim/pull/6245
=> Warning fix.

tracking/reporter.cpp, tracking/reporter.hpp
Не отправлять трек с неподключенных к зарядке устройств.
https://jira.mail.ru/browse/MAPSME-4644
=> [Release-73][tracking] Don't track if device is not charging

tracking/reporter.cpp, tracking/reporter.hpp
Cherry pick https://github.com/mapsme/omim/pull/6247
=> [tracking] Don't track if device is not charging

data/countries.txt, data/external_resources.txt
Планетка! Уже разливается, можно мёржить.
=> [planet] Fresh data from 9.06.2017

routing/route.cpp, routing/route.hpp, routing/routing_integration_tests/osrm_route_test.cpp, routing/routing_session.cpp, routing/routing_tests/route_tests.cpp
Интерфейс поддержки под маршрутов.
@dobriy-eeh @rokuz PTAL
=> [routing] Subroute interface.

openlr/openlr_tests/CMakeLists.txt, search/search_quality/search_quality_tests/CMakeLists.txt, traffic/traffic_tests/CMakeLists.txt
=> Fix cmake build.

iphone/Maps/Bookmarks/BookmarksVC.mm
=> [MAPSME-4545] [ios] Fixed bookmarks export.

data/countries_meta.txt
=> [data] Remove Russian language from Ukraine official langs

indexer/road_shields_parser.cpp
=> [generator] Deduplicate US State Highways shields

indexer/road_shields_parser.cpp
Откатываем #6281, потому что вдруг что.
=> [shields] Revert US shields fix

routing/CMakeLists.txt, routing/edge.hpp, routing/routing.pro, routing/subway_edge.hpp, routing/subway_graph.cpp, routing/subway_graph.hpp, routing/world_road_point.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Интерфейс графа метро, без реализации.
=> [routing] Subway graph

base/CMakeLists.txt, base/base.pro, base/base_tests/CMakeLists.txt, base/base_tests/base_tests.pro, base/base_tests/worker_thread_tests.cpp, base/worker_thread.cpp, base/worker_thread.hpp
=> [base] WorkerThread.

routing/CMakeLists.txt, routing/routing.pro, routing/subway_graph.hpp, routing/subway_router.cpp, routing/subway_router.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Реализация IRouter на базе SubwayGraph
=> [routing] Subway router

map/routing_manager.cpp, routing/router.hpp, routing/routing_settings.hpp
Протянул subway router наверх.
=> [routing] Support subway router in routing manager

generator/generator_tests_support/test_feature.cpp, generator/generator_tests_support/test_feature.hpp, routing/routing_tests/CMakeLists.txt, routing/routing_tests/routing_tests.pro, routing/routing_tests/subway_test.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
Создание mwm с картой метро для тестов на SubwayGraph.
=> [routing] SubwayGraph test with creation mwm.

routing/CMakeLists.txt, routing/routing.pro, routing/subway_edge.hpp, routing/subway_graph.cpp, routing/subway_graph.hpp, routing/subway_router.cpp, routing/subway_router.hpp, routing/subway_vertex.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Переименовал WorldRoadPoint в SubwayVertex
=> [routing] Subway vertex

ugc/CMakeLists.txt, ugc/api.cpp, ugc/api.hpp, ugc/types.hpp
=> Add ugc datatypes.

generator/generator_tests_support/test_feature.cpp, generator/generator_tests_support/test_feature.hpp, routing/subway_vertex.hpp
Добавил в SubwayVertex тип перехода.
=> [routing] Subway type enum

map/routing_manager.cpp, routing/route.hpp, routing/subway_router.cpp, routing/subway_router.hpp
=> [routing] Subway colors

android/src/com/mapswithme/maps/widget/menu/BaseMenu.java
https://jira.mail.ru/browse/MAPSME-4759
=> Removed unnecessary closing navigation menu

routing/CMakeLists.txt, routing/routing.pro, routing/subway_cache.cpp, routing/subway_cache.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Реализация кеша загруженных фичей.
Использование кеша будет отдельным PR.
=> [routing] Subway cache

routing/routing_tests/subway_test.cpp, routing/subway_cache.cpp, routing/subway_cache.hpp, routing/subway_graph.cpp, routing/subway_graph.hpp, routing/subway_router.cpp, routing/subway_router.hpp
=> [routing] Use subway cache

qt/draw_widget.cpp
Поправил падение при переносе стартовой точки на проложенном маршруте.
=> [routing] Fix subway alt+mouse click

coding/reader.hpp, ugc/CMakeLists.txt, ugc/serdes.hpp, ugc/types.hpp, ugc/ugc_tests/CMakeLists.txt, ugc/ugc_tests/serdes_tests.cpp
=> [ugc] Basic SerDes.

3party/jansson/myjansson.cpp, 3party/jansson/myjansson.hpp
=> MyJansson small refactoring.

generator/region_meta.cpp
=> Fix build.

ugc/api.cpp, ugc/api.hpp, ugc/ugc_tests/CMakeLists.txt, ugc/ugc_tests/serdes_tests.cpp
@VladiMihaylenko @alexzatsepin PTAL
=> [ugc] Fake UGC are generated in API now.

android/res/layout/fragment_ugc_editor.xml, android/res/layout/item_ugc_rating.xml, android/src/com/mapswithme/maps/ugc/UGCEditorActivity.java, android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java, android/src/com/mapswithme/maps/ugc/UGCRatingAdapter.java, android/src/com/mapswithme/maps/ugc/UgcAverageRatingController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
=> [android] Added UGCEditor fragment UI

android/jni/com/mapswithme/maps/Framework.cpp, generator/generator_tests/CMakeLists.txt, generator/generator_tests/generator_tests.pro, map/framework.cpp, map/framework.hpp, ugc/CMakeLists.txt, ugc/api.cpp, ugc/api.hpp, ugc/types.hpp, ugc/ugc.pro
@ygorshenin @VladiMihaylenko @alexzatsepin 
Тесты добавлю следом
=> Add dynamic ugc storage.

android/res/layout/fragment_ugc_editor.xml, android/src/com/mapswithme/maps/ugc/UGC.java, android/src/com/mapswithme/maps/ugc/UGCEditorActivity.java, android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, ugc/api.cpp
=> Ugc android display core data

android/src/com/mapswithme/maps/ugc/UGC.java, android/src/com/mapswithme/maps/ugc/UGCEditorActivity.java, android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
=> [android] Implemented passing ratings to editor

generator/feature_builder.cpp
Оставляем номера линий на линиях метро.
=> Keep refs for subway lines

tools/python_tests/permissions_test.py
=> [android] Fixed permission tests

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/routing/NavigationController.java, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/routing/SearchWheel.java
@goblinr @rokuz PTAL
https://jira.mail.ru/browse/MAPSME-4782
=> [android] Added search on viewport in P2P

routing/bicycle_directions.hpp, routing/pedestrian_directions.cpp, routing/pedestrian_directions.hpp, routing/road_graph_router.cpp, routing/road_graph_router.hpp, routing/routing_benchmarks/pedestrian_routing_tests.cpp, routing/routing_helpers.cpp
Продолжение рефакторинга по роутингу.
Следующий шаг - для класса Route при любой прокладке будет заполняться вектор vector<SegmentInfo>.
@dobriy-eeh @ygorshenin PTAL
=> Generating segments in case of pedestrian routing.

routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/directions_engine.hpp, routing/pedestrian_directions.cpp, routing/pedestrian_directions.hpp, routing/routing_helpers.cpp
=> [routing] Passing vector with streets name from IDirectionsEngine::Generate().

drape/drape_tests/CMakeLists.txt, drape/drape_tests/drape_tests.pro, drape/drape_tests/object_pool_tests.cpp, drape/object_pool.hpp, drape_frontend/backend_renderer.cpp, drape_frontend/backend_renderer.hpp, drape_frontend/base_renderer.cpp, drape_frontend/batchers_pool.hpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_frontend_tests/CMakeLists.txt, drape_frontend/drape_frontend_tests/drape_frontend_tests.pro, drape_frontend/frontend_renderer.cpp, drape_frontend/metaline_manager.hpp, drape_frontend/read_manager.cpp, drape_frontend/read_manager.hpp, drape_frontend/tile_info.cpp, drape_frontend/tile_key.cpp, drape_frontend/tile_key.hpp, drape_frontend/traffic_generator.cpp
https://jira.mail.ru/browse/MAPSME-4665
https://jira.mail.ru/browse/MAPSME-4666
=> Fixed crashes on enter background in drape

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/routing/RoutingBottomMenuController.java, android/src/com/mapswithme/maps/routing/RoutingController.java
@rokuz @goblinr PTAL
https://jira.mail.ru/browse/MAPSME-4787
=> [android] Added hiding the USE button if location is not determined

android/src/com/mapswithme/maps/routing/RoutingBottomMenuController.java, android/src/com/mapswithme/maps/routing/RoutingController.java
[android] Fixed overlapping add start/finish panel with uber panel
https://jira.mail.ru/browse/MAPSME-4783
https://jira.mail.ru/browse/MAPSME-4788
=> [andorid] Disabled intermediate points in taxi routing

data/countries.txt
Данные свежие, есть металинии, нет пробок и localads.
World.mwm и WorldCoasts.mwm не собрались из-за проблемы в металиниях (нужно их отключать для планеты), но можно использовать старые.
=> [planet] Temporary data from 22.06.2017 without world mwms

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/jni/com/mapswithme/maps/uber/Uber.cpp, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/uber/Uber.java, configure.sh, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMTaxiPreviewCell.h, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMTaxiPreviewCell.mm, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/MWMTaxiPreviewDataSource.mm, map/framework.cpp, map/framework.hpp, partners_api/CMakeLists.txt, partners_api/partners_api.pro, partners_api/partners_api_tests/CMakeLists.txt, partners_api/partners_api_tests/partners_api_tests.pro, partners_api/partners_api_tests/taxi_engine_tests.cpp, partners_api/partners_api_tests/uber_tests.cpp, partners_api/partners_api_tests/yandex_tests.cpp, partners_api/taxi_base.hpp, partners_api/taxi_engine.cpp, partners_api/taxi_engine.hpp, partners_api/taxi_provider.hpp, partners_api/uber_api.cpp, partners_api/uber_api.hpp, partners_api/yandex_api.cpp, partners_api/yandex_api.hpp, tools/python/ResponseProvider.py, tools/python/jsons.py, traffic/traffic_info.cpp, xcode/partners_api/partners_api.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-4613
Код на платформах заглушечный, должен быть изменен.
=> [partners_api] yandex + taxi engine + dummy for platforms

generator/routing_index_generator.cpp, map/routing_manager.cpp, routing/CMakeLists.txt, routing/async_router.cpp, routing/async_router.hpp, routing/base/astar_algorithm.hpp, routing/edge_estimator.cpp, routing/index_router.cpp, routing/index_router.hpp, routing/road_graph_router.cpp, routing/road_graph_router.hpp, routing/router.hpp, routing/routing.pro, routing/routing_algorithm.cpp, routing/routing_helpers.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/astar_algorithm_test.cpp, routing/routing_tests/async_router_test.cpp, routing/routing_tests/routing_session_test.cpp, routing/segmented_route.cpp, routing/segmented_route.hpp, routing/traffic_stash.cpp, routing/traffic_stash.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Быстрая перепрокладка маршрута.
При уходе с маршрута он не пересчитывается с нуля, а ищет возврат на проложенный.
https://jira.mail.ru/browse/MAPSME-4535
=> [routing] Fast rebuild route

map/routing_manager.cpp
https://jira.mail.ru/browse/MAPSME-4790
=> Fixed route preview duplication on switch router type

partners_api/partners_api_tests/viator_tests.cpp, partners_api/viator_api.cpp
Добавил поддерживаемые валюты и пофиксил баг https://jira.mail.ru/browse/MAPSME-4785
=> [partners_api] supported currencies + web url fix

map/routing_manager.cpp, routing/CMakeLists.txt, routing/async_router.cpp, routing/async_router.hpp, routing/checkpoints.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/road_graph_router.cpp, routing/road_graph_router.hpp, routing/router.hpp, routing/routing.pro, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/async_router_test.cpp, routing/routing_tests/routing_session_test.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
Прокидывание checkpoints (старт, промежуточные точки, финиш) из routing manager в роутер.
Сами промежуточные точки пока не используется, маршрут как и раньше прокладывается от старта к финишу.
=> [routing] Сheckpoints parameter for CalculateRoute

data/faq.html
=> FAQ Update June

drape_frontend/shaders/colored_symbol.fsh.glsl, drape_frontend/shaders/discarded_texturing.fsh.glsl, drape_frontend/shaders/shaders_lib.glsl, drape_frontend/shaders/smaa_edges.fsh.glsl
=> Revert "Optimized discarding in fragment shaders on ES3"

drape_frontend/apply_feature_functors.cpp, drape_frontend/apply_feature_functors.hpp, indexer/road_shields_parser.hpp
https://jira.mail.ru/browse/MAPSME-4808
=> Fixed shields rendering on roads without name

base/CMakeLists.txt, base/base.pro, base/base_tests/CMakeLists.txt, base/base_tests/base_tests.pro, base/base_tests/suffix_array_tests.cpp, base/suffix_array.cpp, base/suffix_array.hpp
=> [base] Added Skew|DC3 algorithm for suffix array construction.

iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm, routing/CMakeLists.txt, routing/async_router.cpp, routing/checkpoints.cpp, routing/checkpoints.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/router.hpp, routing/routing.pro, routing/world_graph.cpp, routing/world_graph.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Прокладка маршрута по промежуточным точкам.
Реализован простейший алгоритм прокладки: каждый подмаршрут прокладывается независимо, затем подмаршруты объединяются в общий маршрут.
=> [routing] Calculate route by checkpoints

map/routing_manager.cpp, routing/routing_session.cpp, routing/routing_session.hpp
Callback для изменения пройденного checkpoint.
Только интерфейс, реализация будет отдельным PR.
Пока умеет только дергать callback при прибытии на финиш.
=> [routing] Pass checkpoint callback

generator/generator_tool/generator_tool.cpp
Поправил читалку, а генератор забыл.
=> [generator] Do not build metalines for World*.mwm

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/jni/com/mapswithme/maps/MapFragment.cpp, android/src/com/mapswithme/maps/DownloadResourcesActivity.java, android/src/com/mapswithme/maps/MapFragment.java, android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-4237
=> [android] CreateDrapeEngine with m_isLaunchByDeepLink flag

android/res/values/strings.xml, android/src/com/mapswithme/maps/routing/ResultCodesHelper.java
https://jira.mail.ru/browse/MAPSME-4821
=> Mapsme 4821 intermediate point not found dialog

android/src/com/mapswithme/maps/viator/Viator.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-4812
=> [android] Added viator products cache.

android/res/values-pt/strings.xml, android/res/values/strings.xml, iphone/Maps/LocalizedStrings/pt.lproj/Localizable.strings, strings.txt
=> Fixed pt and pt-BR translations (rebase)

android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/routing/RoutingPlanController.java, android/src/com/mapswithme/maps/taxi/TaxiManager.java, android/src/com/mapswithme/util/statistics/Statistics.java
@milchakov @rokuz PTAL
https://jira.mail.ru/browse/MAPSME-4846
=> [android] Added handling the No_Providers case in taxi

android/src/com/mapswithme/maps/routing/RoutingBottomMenuController.java, android/src/com/mapswithme/maps/routing/RoutingController.java
=> [android] Added checking of start/end points before requesting taxi info

routing/index_router.cpp
@dobriy-eeh @alexzatsepin PTAL
=> [routing] Crash fix in rare cases when checkpoints are put between mwms.

android/gradle.properties
=> Android update version

map/bookmark_manager.cpp, map/framework.cpp
https://jira.mail.ru/browse/MAPSME-4849
=> Increased priority of route marks selection by tap.

routing/index_router.cpp, routing/routing_algorithm.cpp
=> [routing] Progress adjusting.

android/jni/com/mapswithme/opengl/androidoglcontextfactory.cpp
Из-за странных падений на некоторых 4 андроидах в драйвере OpenGL в режиме OpenGL ES 3, отключили режим для всех 4 Андроидов.
=> Disabled OpenGL ES3 for Android 4

android/jni/com/mapswithme/opengl/androidoglcontextfactory.cpp
Случайно разблочил ES 3 на старых девайсах с 5 Андроидом
=> Fixed disabling es3 on Android

android/src/com/mapswithme/maps/routing/RoutingBottomMenuController.java
https://jira.mail.ru/browse/MAPSME-4801
=> [android] hide routing action frame when error occurred

android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/background/ConnectivityChangedReceiver.java, android/src/com/mapswithme/maps/background/WorkerService.java
https://jira.mail.ru/browse/MAPSME-4804
=> [android] xiaomi dynamic permissions fix

drape/glstate.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/line_shape.cpp, drape_frontend/user_mark_shapes.cpp
https://jira.mail.ru/browse/MAPSME-4864
=> Render user lines in separate layer above 2d geometry.

map/routing_manager.cpp, routing/checkpoints.cpp, routing/checkpoints.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/road_graph_router.cpp, routing/route.cpp, routing/route.hpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/route_tests.cpp, routing/routing_tests/routing_session_test.cpp, routing/segmented_route.cpp, routing/segmented_route.hpp
Ведение по маршруту с учетом подмаршрутов.
=> [release-74][routing] Support checkpoints for the route following.

data/faq.html
minor changes and improvements for release 7.4
=> FAQ Hotfix June

data/faq.html
Rebase FAQ Hotfix June to release-74
=> Rebase FAQ Hotfix June to release-74

android/res/values/arrays.xml
https://jira.mail.ru/browse/MAPSME-4871
=> [Android] Fixed strings ids in what’s new

map/bookmark_manager.cpp, map/framework.cpp, map/user_mark_container.cpp
* Ускорение возврата из фона на android.
* Ускорение времени загрузки карты на старте при выключенных категориях букмарок.
=> Optimization of user marks invalidation.

partners_api/partners_api_tests/uber_tests.cpp, partners_api/partners_api_tests/yandex_tests.cpp, partners_api/taxi_base.cpp, partners_api/taxi_base.hpp, partners_api/uber_api.cpp, partners_api/yandex_api.cpp, tools/python/jsons.py
https://jira.mail.ru/browse/MAPSME-4883
=> added max supported distance for taxi

android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-4884
@rokuz @goblinr PTAL
=> [android] Changed add start/finish panel logic

map/bookmark_manager.cpp, map/framework.cpp
https://jira.mail.ru/browse/MAPSME-4849
=> Route point selection fix.

android/src/com/mapswithme/maps/taxi/TaxiAdapter.java
https://jira.mail.ru/browse/MAPSME-4889
Пробел в английской локали не стал добавлять, т.к. его отсутствие - это нормально, пример:
RUB100.0 -> $100.0
@rokuz @alexzatsepin PTAL
=> [android] added '~' symbol to taxi price

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java, android/src/com/mapswithme/maps/widget/placepage/LeftPlacePageAnimationController.java, android/src/com/mapswithme/util/statistics/PlacePageTracker.java, android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-4838
=> Mapsme 4838 place page taxi show

routing/async_router.cpp, routing/online_absent_fetcher.cpp, routing/online_absent_fetcher.hpp, routing/online_cross_fetcher.cpp, routing/online_cross_fetcher.hpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_tests/async_router_test.cpp, routing/routing_tests/online_cross_fetcher_test.cpp
Починка https://jira.mail.ru/browse/MAPSME-4835
При запросе отсутствующих mwm через сервер не учитывались промежуточные точки.
=> [release-74][routing] Fetch required mwms from online server for all checkpoints

android/src/com/mapswithme/maps/routing/RoutingController.java, iphone/Maps/Core/Routing/MWMRouter.mm, map/routing_manager.cpp
https://jira.mail.ru/browse/MAPSME-4909
https://jira.mail.ru/browse/MAPSME-4910
https://jira.mail.ru/browse/MAPSME-4911
=> Removing intermediate points in not-vehicle routing mode

android/src/com/mapswithme/maps/routing/RoutingController.java
https://jira.mail.ru/browse/MAPSME-4910
Удалил хранение mStartPoint, mEndPoint  в RoutingController. Так как при модификации маршрута (удалении/добавлении промежуточных/стартовой/финишной точке) возникла необходимость обновлять два эти поля и следить за их когерентностью с ядром.
=> [android] Removed storing the start and end points in routing controller

data/countries.txt, data/external_resources.txt
=> [planet] Fresh data from 3.07.2017

drape_frontend/read_manager.cpp, drape_frontend/read_metaline_task.cpp, drape_frontend/read_mwm_task.cpp
https://jira.mail.ru/browse/MAPSME-4898
=> Active tasks tracking fixed. Fixed tasks resetting.

iphone/Maps/UI/PlacePage/MWMPlacePageData.mm, iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm, iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.h, iphone/Maps/UI/PlacePage/PlacePageLayout/MWMiPhonePlacePageLayoutImpl.mm
Removed banner if Viator is available.
Changed logic to open place page expanded if Viator is available.
=> [MAPSME-4923] [ios] Update Viator support in place page.

partners_api/CMakeLists.txt, partners_api/cian_api.cpp, partners_api/cian_api.hpp, partners_api/partners_api.pro, partners_api/partners_api_tests/CMakeLists.txt, partners_api/partners_api_tests/cian_tests.cpp, partners_api/partners_api_tests/partners_api_tests.pro, partners_api/uber_api.cpp, partners_api/uber_api.hpp, partners_api/utils.hpp, partners_api/yandex_api.cpp, partners_api/yandex_api.hpp, tools/python/ResponseProvider.py, tools/python/jsons.py, xcode/partners_api/partners_api.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-4925
=> [partners_api] cian api

tools/python/local_ads/mwm_to_csv_4localads.py
Наконец-то дошли руки локалэдсы запустить для букинговских гостиниц. В этом PR по совету Сергея делаю единый формат. Разница только в последнем столбце, где 0 для осмовских данных и 1 для букинговских.
Также для каждой mwm добавляется запись с левым идентификатором, чтобы тестировать данные после загрузки в базу.
=> [DNM][localads] Change file format to unify osm and booking data

android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java
https://jira.mail.ru/browse/MAPSME-4920
=> [android] "Route to" & "Route from" order priority fix.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/viator/ViatorAdapter.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/placepage/Sponsored.java, android/src/com/mapswithme/util/statistics/PlacePageTracker.java, android/src/com/mapswithme/util/statistics/Statistics.java
@goblinr @rokuz PTAL
 Пока только сделал трекание viatora в горизонтальной и портретной ориентации. Так как блок виатора намного больше блока такси, то оставил в портретной ориентации трекание как и было - "пока элемент полностью не отобразиться на экране", а в лэндскейпе - хотя бы граница верхняя или нижняя.
=> [android] Added viator view to PlacePageTracker

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/routing/NavigationController.java, android/src/com/mapswithme/maps/routing/RoutePointInfo.java, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/routing/SearchWheel.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-4938
=> [android] routing point statistics

android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-4885
=> [android] fix PP hide in P2P mode when my position is null

search/search_quality/assessment_tool/result_view.cpp
https://jira.mail.ru/browse/MAPSME-4709
=> [assessment-tool] 0|+1|+2 are replaced by human-readable names.

android/src/com/mapswithme/util/HttpClient.java, android/src/com/mapswithme/util/PreLollipopSSLSocketFactory.java
@milchakov @rokuz PTAL
https://jira.mail.ru/browse/MAPSME-4597
=> [android] Fixed TLS problem on PreLollipop devices (Viator)

android/src/com/mapswithme/maps/search/SearchFragment.java
@rokuz PTAL
https://jira.mail.ru/browse/MAPSME-3942
=> [android] Fixed back button on tablet

android/src/com/mapswithme/maps/routing/RoutingController.java
=> [android] Fixed starting from my position

platform/location.hpp, qt/draw_widget.cpp, qt/qt_common/helpers.cpp, qt/qt_common/helpers.hpp, search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp, search/search_quality/assessment_tool/view.hpp
https://jira.mail.ru/browse/MAPSME-4709
=> [assessment-tool] Show user position on map, when available.

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-4992
=> [android] hide Viator.com view for other sponsored PP types

indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, map/framework.cpp, map/framework.hpp, map/place_page_info.cpp, map/place_page_info.hpp, partners_api/cian_api.cpp, partners_api/cian_api.hpp, partners_api/partners_api_tests/cian_tests.cpp
https://jira.mail.ru/browse/MAPSME-4960
=> [partners_api] cian pp

search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/results_view.cpp, search/search_quality/assessment_tool/results_view.hpp, search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp
https://jira.mail.ru/browse/MAPSME-4709
=> [assessment-tool] Added possibility to view position with top results.

data/countries.txt, data/external_resources.txt
После #6594 пересобрал геометрические индексы. Данные уже разливаются.
=> [planet] Updated geometric indices

drape/debug_rect_renderer.cpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5969d8b3be077a4dcc971c0d
=> Fixed crash in debug renderer initialization

android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/SplashActivity.java, android/src/com/mapswithme/maps/background/ConnectivityChangedReceiver.java, android/src/com/mapswithme/maps/background/UpgradeReceiver.java, android/src/com/mapswithme/maps/background/WorkerService.java, android/src/com/mapswithme/maps/base/BaseMwmFragmentActivity.java, android/src/com/mapswithme/maps/location/GPSCheck.java, android/src/com/mapswithme/maps/location/SensorHelper.java, android/src/com/mapswithme/maps/location/TrackRecorderWakeReceiver.java, android/src/com/mapswithme/maps/location/TrackRecorderWakeService.java, android/src/com/mapswithme/util/MultipleTrackerReferrerReceiver.java, android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-5008
=> Mapmsme 5008 framework initialization check

android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/background/ConnectivityChangedReceiver.java, android/src/com/mapswithme/maps/background/UpgradeReceiver.java, android/src/com/mapswithme/maps/background/WorkerService.java, android/src/com/mapswithme/maps/location/TrackRecorderWakeReceiver.java, android/src/com/mapswithme/maps/location/TrackRecorderWakeService.java, android/src/com/mapswithme/util/CrashlyticsUtils.java, android/src/com/mapswithme/util/MultipleTrackerReferrerReceiver.java
@goblinr Проверь, пожалуйста, перестало ли у тебя крэшится на этой ветке.
=> [android] Added lazy initializtion for Crashlytics library

data/editor.config
Мы планировали к релизу не только добавить категорий, но и включить добавление для некоторых, которые уже есть. Это:
* office-company (просто офис);
* колледж;
* <s>университет;</s>
* водонапорная башня;
* офис риэлтора.
Переводы я проверил, они есть.
=> [editor] Enable creation for several categories

search/search_quality/assessment_tool/context.cpp, search/search_quality/assessment_tool/edits.cpp, search/search_quality/assessment_tool/edits.hpp, search/search_quality/assessment_tool/main_model.cpp, search/search_quality/assessment_tool/main_model.hpp, search/search_quality/assessment_tool/result_view.cpp
https://jira.mail.ru/browse/MAPSME-4709
=> [assessment-tool] Save irrelevant results too.

android/src/com/mapswithme/maps/cian/RentOffer.java, android/src/com/mapswithme/maps/cian/RentPlace.java
=> [android] cian models

partners_api/cian_api.cpp, partners_api/cian_api.hpp, partners_api/partners_api_tests/cian_tests.cpp, partners_api/uber_api.cpp, partners_api/utils.hpp
https://jira.mail.ru/browse/MAPSME-4975
=> [partners_api] cian error callback

partners_api/partners_api_tests/uber_tests.cpp, partners_api/uber_api.cpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/58cab62a0aeb16625b782e18/sessions/596DC09702D200016C85BA6DD1699CC3_59d0faf26b9011e79b0256847afe9799_0_v2?build=60932702
=> [cherry-pick][partners_api] taxi engine crash fix

partners_api/partners_api_tests/uber_tests.cpp, partners_api/uber_api.cpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/58cab62a0aeb16625b782e18/sessions/596DC09702D200016C85BA6DD1699CC3_59d0faf26b9011e79b0256847afe9799_0_v2?build=60932702
=> [partners_api] taxi engine crash fix

android/jni/com/mapswithme/maps/Framework.cpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5703f3c6ffcdc0425072e4f2?time=last-seven-days
=> [android] Jni crash fix

android/jni/com/mapswithme/maps/Framework.cpp
cherry pick for https://github.com/mapsme/omim/pull/6639
=> [cherry-pick][android] jni crash fix

android/gradle.properties
=> [android] Updated version to 7.4.2

android/src/com/mapswithme/maps/SplashActivity.java
https://jira.mail.ru/browse/MAPSME-5096
=> [android] Added handling of updating the maps after recovery of app

android/gradle.properties, android/src/com/mapswithme/maps/SplashActivity.java
=> Cherry picks

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
=> [android] viator view initialization fix

android/src/com/mapswithme/maps/SplashActivity.java, android/src/com/mapswithme/maps/editor/ViralFragment.java
Fixed https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/59700726be077a4dccd3afb7?time=last-seven-days
=> [android] custom onDismissListener for ViralFragment dialog

android/src/com/mapswithme/maps/SplashActivity.java, android/src/com/mapswithme/maps/editor/ViralFragment.java
=> [cherry-pick][android] custom onDismissListener for ViralFragment dialog

android/gradle.properties
=> [android] Updated version to 7.4.3

android/gradle.properties
=> [android] [cherry-pick] Updated version to 7.4.3

geometry/mercator.hpp, partners_api/cian_api.cpp, partners_api/cian_api.hpp, partners_api/partners_api_tests/cian_tests.cpp
Изменения:
- добавил города;
- уменьшил радиус поиска объектов циана;
- изменил способ генерации прямоугольника для поиска;
- добавил обработку null значений в результатах поиска;
- сделал сохранение только полностью заполненных объектов.
https://jira.mail.ru/browse/MAPSME-5100
https://jira.mail.ru/browse/MAPSME-5104
=> [partners_api] cian changes

android/gradle.properties
=> [android] Updated version to 7.4.4

android/jni/Android.mk, android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/jni/com/mapswithme/maps/cian/Cian.cpp, android/src/com/mapswithme/maps/cian/Cian.java, android/src/com/mapswithme/maps/widget/placepage/Sponsored.java, partners_api/cian_api.cpp, partners_api/cian_api.hpp
https://jira.mail.ru/browse/MAPSME-4961
Пока протестить не получается, потому что приложение крешится при тапе на плейс пейдже.
Хотелось бы чтоб сделали ревью сейчас, а потом, когда мастер заработает - я протестирую и сразу зальем.
=> [android] cian jni

partners_api/cian_api.cpp, partners_api/cian_api.hpp, partners_api/partners_api_tests/cian_tests.cpp, tools/python/jsons.py
Думал что прайс приходит интом, а он приходит даблом.
=> [partners_api] cian price fix

routing/route.cpp
=> [routing] Wrong check fix.

drape_frontend/backend_renderer.cpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/message.hpp, drape_frontend/message_subclasses.hpp, map/framework.cpp
Удалил устаревшие методы и подправил приоритеты сообщений
=> Fixed messages priority

3party/opening_hours/rules_evaluation.cpp
https://jira.mail.ru/browse/MAPSME-5114
=> opening hours fix

android/jni/com/mapswithme/opengl/androidoglcontextfactory.cpp, android/jni/com/mapswithme/platform/Platform.cpp, android/jni/com/mapswithme/platform/Platform.hpp, drape/framebuffer.cpp, drape/support_manager.cpp, drape/support_manager.hpp, drape_frontend/frontend_renderer.cpp
https://jira.mail.ru/browse/MAPSME-5139
=> Disabled transparent 3d buildings on Android 4.2 and less

drape_frontend/rule_drawer.cpp, drape_frontend/user_mark_generator.cpp, drape_frontend/user_mark_shapes.cpp, geometry/spline.hpp
Cherry pick https://github.com/mapsme/omim/pull/6690
=> [release only] User lines indexing optimization.

drape_frontend/rule_drawer.cpp, drape_frontend/user_mark_generator.cpp, drape_frontend/user_mark_shapes.cpp, geometry/spline.hpp
https://jira.mail.ru/browse/MAPSME-5137
=> User lines indexing optimization.

routing/index_router.cpp, routing/route.cpp
Починка https://jira.mail.ru/browse/MAPSME-5053
После проезда промежуточной точки маршрут не перестраивался.
=> [routing] Fix route rebuilding after pass checkpoint

android/jni/com/mapswithme/platform/Platform.cpp, drape/framebuffer.cpp, drape/support_manager.cpp, drape/support_manager.hpp, drape_frontend/frontend_renderer.cpp
Нашел девайс, где воспроизводился баг с темным экраном и нашел вокрэраунд
=> Fixed retrieving Android API level and workaround for framebuffer clearing on Android 4.1-4.2

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/routing/RoutingController.java, iphone/Maps/Core/Routing/MWMRouter.h, iphone/Maps/Core/Routing/MWMRouter.mm, map/routing_manager.cpp, map/routing_manager.hpp
- Добавлены транзакции для точек маршрута;
- При помощи транзакций реализовано сохранение точек маршрута при переключении в режим такси.
https://jira.mail.ru/browse/MAPSME-5040
https://jira.mail.ru/browse/MAPSME-5042
=> Added route points transactions

map/bookmark.cpp, search/search_quality/assessment_tool/sample_view.cpp
https://jira.mail.ru/browse/MAPSME-5141
=> Fixed bookmark color updating. Fixed cmake compilation.

map/framework.cpp, partners_api/cian_api.cpp, partners_api/cian_api.hpp
https://jira.mail.ru/browse/MAPSME-5142
=> [partners_api] sponsored url for cian

openlr/openlr_tests/decoded_path_test.cpp
@therearesomewhocallmetim @mpimenov
=> Fix decoded_path_test.

routing/route.cpp
Починил crash, который иногда возникал при следовании по маршруту с промежуточными точками.
=> [release-74][routing] Fix crash on pass checkpoint after rebuilding

map/framework.cpp
https://jira.mail.ru/browse/MAPSME-5071
=> Changed the logic of an autoupdate after the whats new screen

routing/route.cpp
cherry pick https://github.com/mapsme/omim/pull/6707
=> [routing] Fix crash on passing checkpoint after rebuilding

data/categories.txt
Джанет попросила добавить типов в сборку для Танзании, и для них не было переводов. Здесь я их добавляю.
=> [strings] Add Swahili translations for some types

generator/osm_translator.hpp, indexer/road_shields_parser.cpp
Rebase of #6568 to the master branch.
=> [shields] Remove duplicate shields of default style

data/categories.txt
=> [strings] Add a synonim for butcher shop in Polish

map/routing_manager.cpp, map/routing_manager.hpp, map/routing_mark.cpp, map/routing_mark.hpp
Добавлено сокрытие подписей к точкам маршрута в режиме следование
=> Added hiding route marks titles in following mode

data/styles/clear/include/Basemap.mapcss
Rebase of #6569 to the master branch.
=> [styles] Restore piers

indexer/drawing_rules.cpp
Поломал после перехода на 3 протобуф
=> Fixed black background reading from styles

data/categories.txt, search/model.cpp, search/search_integration_tests/processor_test.cpp
https://jira.mail.ru/browse/MAPSME-4958
=> [search] Defibrillators and fire hydrants.

map/routing_manager.cpp, map/routing_manager.hpp, map/routing_mark.cpp
@bykoianko Добавил интерфейс для определения порядка промежуточных точек. На вход получает массив координат, на выход массив индексов пром. точек. Тебя устроит такой?
=> Unblocked 3 intermediate points

drape_frontend/user_mark_generator.cpp
Cherry pick https://github.com/mapsme/omim/pull/6711
=> Spline segment length corrected in user line indexing.

.gitignore, android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, map/routing_manager.cpp, map/routing_manager.hpp, map/routing_mark.hpp, qt/draw_widget.cpp
https://jira.mail.ru/browse/MAPSME-4794
=> Added route points persistence storing and loading

android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java, android/src/com/mapswithme/maps/bookmarks/data/MapObject.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/search/SearchFragment.java, android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-4968
https://jira.mail.ru/browse/MAPSME-4963
@rokuz @milchakov PTAL
=> Mapsme 4968 pp opening for sponsored

android/res/xml/prefs_main.xml, android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
https://jira.mail.ru/browse/MAPSME-5090
Don't forget to create cherry-pick on master after review!
=> [android] Fixed removing the preference when it's needed

android/res/xml/prefs_main.xml, android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
https://github.com/mapsme/omim/pull/6744
=> [cherry-pick] [android] Fixed removing the preference when it's needed

android/src/com/mapswithme/maps/base/BaseSponsoredAdapter.java
https://jira.mail.ru/browse/MAPSME-4970
=> [android] Fixed 'Details' button for error banner

android/res/layout/fragment_auth_editor.xml, android/src/com/mapswithme/maps/editor/OsmAuthFragmentDelegate.java, android/src/com/mapswithme/util/HttpClient.java
https://jira.mail.ru/browse/MAPSME-5067
=> Maspme 5067 remove google auth button

android/res/layout/fragment_auth_editor.xml, android/src/com/mapswithme/maps/editor/OsmAuthFragmentDelegate.java, android/src/com/mapswithme/util/HttpClient.java
=> [cherry-pick] Remove google btn

local_ads/campaign.hpp, local_ads/campaign_serialization.cpp, local_ads/campaign_serialization.hpp, local_ads/local_ads_tests/campaign_serialization_test.cpp, local_ads/pylocal_ads/bindings.cpp, local_ads/pylocal_ads/bindings_test.py, map/local_ads_manager.cpp
https://jira.mail.ru/browse/MAPSME-5094
=> MAPSME-5094 localads serialization

android/res/layout/card_loading.xml, android/src/com/mapswithme/maps/base/BaseSponsoredAdapter.java, android/src/com/mapswithme/maps/cian/CianAdapter.java
=> [android] Fixed android build after string merge

data/countries.txt, data/external_resources.txt
=> [planet] New data from 28.07.2017

drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, map/bookmark_manager.cpp, map/bookmark_manager.hpp, map/framework.cpp, map/framework.hpp
https://jira.mail.ru/browse/MAPSME-2328
=> TapInfo uses mercator coords instead of pixel ones

android/src/com/mapswithme/maps/routing/RoutingController.java
https://jira.mail.ru/browse/MAPSME-5201
=> Mapsme 5201 pass name for intermediate points

android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java, android/src/com/mapswithme/maps/bookmarks/data/MapObject.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/search/SearchFragment.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-5159
=> Mapsme 5159 disable ugc

map/framework.cpp, map/framework.hpp
https://jira.mail.ru/browse/MAPSME-5095
Сделал сначала на мастер, а надо на релиз
=> [RELEASE ONLY] viator for any z level

routing/routing_tests/route_tests.cpp
=> [routing] Routing test fix

generator/routing_index_generator.cpp, map/routing_manager.cpp, map/routing_manager.hpp, routing/CMakeLists.txt, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/index_graph_loader.cpp, routing/index_graph_loader.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/route.cpp, routing/route.hpp, routing/routing.pro, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_settings.cpp, routing/routing_settings.hpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/traffic_stash.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Перевод пешеходного и велороутинга на index graph.
Первая часть.
НЕ сделано:
- Учет высоты в весе ребра
- Удаление старого кода
=> [routing] Transfer pedestrian and bicycle to index router

generator/CMakeLists.txt, generator/mwm_diff/CMakeLists.txt, generator/mwm_diff/diff.cpp, generator/mwm_diff/diff.hpp, generator/mwm_diff/mwm_diff.pro, generator/mwm_diff/mwm_diff_tests/CMakeLists.txt, generator/mwm_diff/mwm_diff_tests/diff_test.cpp, generator/mwm_diff/mwm_diff_tests/mwm_diff_tests.pro, generator/mwm_diff/pymwm_diff/CMakeLists.txt, generator/mwm_diff/pymwm_diff/bindings.cpp, omim.pro
Для сборки на серверах:
```
$ cmake3 ../omim \
-DPYBINDINGS=on \
-DPYTHON_VERSION=3.5.1 \
-DBOOST_INCLUDEDIR=/usr/local/boost_1.54.0/include \
-DPYTHON_LIBRARY=/usr/local/python35/lib/libpython3.so \
-DPYTHON_INCLUDE_DIRS=/usr/local/python35/include
```
=> [generator] Stubs for incremental updates.

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/recycler/SingleChangeItemAnimator.java
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro.beta/issues/597f24ccbe077a4dcc625580?time=last-seven-days
https://jira.mail.ru/browse/MAPSME-5160
=> Mapsme 5160 crash cian

indexer/editable_map_object.cpp, indexer/editable_map_object.hpp, indexer/indexer_tests/editable_map_object_test.cpp
https://jira.mail.ru/browse/MAPSME-4888
FYI @Zverik
=> [editor] remove default name duplications on save

local_ads/pylocal_ads/bindings.cpp, local_ads/pylocal_ads/bindings_test.py
Нужно разрешить серверу отправлять данные запакованные в разных версиях
=> [local ads] py bindings for searelization in any version

routing_common/bicycle_model.cpp, routing_common/bicycle_model.hpp, routing_common/car_model.cpp, routing_common/car_model.hpp, routing_common/pedestrian_model.cpp, routing_common/pedestrian_model.hpp
Add country specific road usage restrictions to CarModel, update restrictions in BicycleModel and PedestrianModel
It'll not work properly untill MAPSME-5212 fix
=> Add country specific road usage restrictions to CarModel

CMakeLists.txt
проверил, собирается с параметрами -DPYBINDINGS=ON -DSKIP_DESKTOP=ON
=> [cmake] do not use qt for pybindings

android/AndroidManifest.xml, android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/search/SearchActivity.java, android/src/com/mapswithme/maps/search/SearchEngine.java, android/src/com/mapswithme/maps/search/SearchFragment.java
https://jira.mail.ru/browse/MAPSME-5069
=> [android] Supported search deeplink

android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/widget/recycler/SingleChangeItemAnimator.java
https://jira.mail.ru/browse/MAPSME-5208
=> Mapsme 5208 routing deeplink

map/framework.cpp, map/place_page_info.cpp, map/place_page_info.hpp
https://jira.mail.ru/browse/MAPSME-5239
=> Added coordinates as subtitle to unknown place

map/routing_manager.cpp
https://jira.mail.ru/browse/MAPSME-5039
=> Unblocked intermediate points for bikes and pedestrians

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
When user builds a route from the map his current position can be used as start point. But if use
r is in P2P mode we shouldn't do any assumptions about the start point, i.e. he should do it by himself.
https://jira.mail.ru/browse/MAPSME-5240
=> [android] Added 'canUseMyPositionAsStart' parameter

drape/overlay_handle.hpp, drape/overlay_tree.cpp, drape/render_bucket.cpp, drape/render_bucket.hpp, drape_frontend/CMakeLists.txt, drape_frontend/apply_feature_functors.cpp, drape_frontend/drape_frontend.pro, drape_frontend/path_text_handle.cpp, drape_frontend/path_text_handle.hpp, drape_frontend/path_text_shape.cpp, drape_frontend/path_text_shape.hpp, drape_frontend/text_layout.cpp, drape_frontend/text_layout.hpp, geometry/spline.cpp, geometry/spline.hpp, xcode/drape_frontend/drape_frontend.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-5021
=> Stabilization of path text placing.

drape_frontend/apply_feature_functors.cpp
Потерялась черная обводка на шилдах
=> Fixed default road shields outline

map/routing_manager.cpp
https://jira.mail.ru/browse/MAPSME-5266
=> Fixed route arrows rendering in route with intermediate points

map/routing_manager.cpp
Cherry pick https://github.com/mapsme/omim/pull/6801 на релизную ветку
=> [CHERRY PICK] Fixed route arrows rendering in route with intermediate points

geometry/point2d.hpp, indexer/altitude_loader.hpp, indexer/index.hpp, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/geometry.cpp, routing/geometry.hpp, routing/index_graph_loader.cpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/route.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/world_graph.cpp, routing/world_graph.hpp
Учёт высот для пешеходов и велосипедистов.
Для автомобилей в целях экономии производительности высоты не загружаются и не учитываются.
=> [routing] Estimate altitudes in index router

android/gradle.properties
=> [android] Updated version to 7.4.5

android/gradle.properties
=> [cherry-pick] [android] Updated version to 7.4.5

android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-4963
=> [android] Fixed cian provider name

android/src/com/mapswithme/maps/search/CategoriesAdapter.java, android/src/com/mapswithme/maps/search/SearchFragment.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-5285
https://jira.mail.ru/browse/MAPSME-5283
=> Mapsme 5283 1link statistics

map/routing_manager.cpp
https://jira.mail.ru/browse/MAPSME-5297
@dobriy-eeh @alexzatsepin PTAL
=> If StatisticsEnabled is not set at settings.ini the statistics is sent.

map/routing_manager.cpp
https://jira.mail.ru/browse/MAPSME-5297
cherry-pick от https://github.com/mapsme/omim/pull/6825
@dobriy-eeh PTAL
=> If StatisticsEnabled is not set in settings.ini the statistics is sent.

routing/index_router.cpp
Поддержка обратной совместимости со старыми картами для пешего и вело роутинга.
Без этой поддержки потребовались бы карты начиная с апреля 2017, когда появилась cross mwm секция для index graph.
=> [routing] Backward compatibility with outdated mwm versions for pedestrian and bicycle routing.

drape/overlay_tree.cpp
=> Drape warning fix.

drape/hw_texture_ios.mm, drape_frontend/tile_info.cpp, drape_frontend/user_mark_generator.cpp, drape_frontend/user_mark_generator.hpp, drape_frontend/user_mark_shapes.cpp, drape_frontend/user_mark_shapes.hpp
https://jira.mail.ru/browse/MAPSME-5183
=> User lines indexing is limited to several zoom levels.

3party/pugixml/pugixml.pro, 3party/pugixml/src/utils.hpp, geometry/CMakeLists.txt, geometry/geometry.pro, geometry/geometry_tests/CMakeLists.txt, geometry/geometry_tests/geometry_tests.pro, geometry/geometry_tests/nearby_points_sweeper_test.cpp, geometry/nearby_points_sweeper.cpp, geometry/nearby_points_sweeper.hpp, openlr/decoded_path.cpp, openlr/openlr_match_quality/openlr_assessment_tool/CMakeLists.txt, openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.cpp, openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.hpp, openlr/openlr_match_quality/openlr_assessment_tool/map_widget.cpp, openlr/openlr_match_quality/openlr_assessment_tool/map_widget.hpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_mode.cpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_mode.hpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_panel.cpp, openlr/openlr_match_quality/openlr_assessment_tool/trafficmodeinitdlg.cpp, openlr/openlr_stat/openlr_stat.cpp, search/CMakeLists.txt, search/pre_ranker.cpp, search/search.pro, search/search_tests/CMakeLists.txt, search/search_tests/search_tests.pro
=> Openlr tool

base/bits.hpp, search/CMakeLists.txt, search/features_layer_matcher.hpp, search/point_rect_matcher.hpp, search/search.pro, search/search_tests/CMakeLists.txt, search/search_tests/point_rect_matcher_tests.cpp, search/search_tests/search_tests.pro, search/search_tests/segment_tree_tests.cpp, search/segment_tree.cpp, search/segment_tree.hpp
https://jira.mail.ru/browse/MAPSME-5277
=> [search] O(n * n) -> O(n * log(n)) for poi-building intersection.

map/framework.cpp
https://jira.mail.ru/browse/MAPSME-5313
=> show cian for unnamed buildings only

drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/message_subclasses.hpp, drape_frontend/route_builder.cpp, drape_frontend/route_builder.hpp, drape_frontend/route_renderer.cpp, drape_frontend/route_renderer.hpp, drape_frontend/route_shape.hpp, map/routing_manager.cpp
https://jira.mail.ru/browse/MAPSME-5265
=> Fixed route disappearing on map style switch

drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/message.hpp, drape_frontend/message_subclasses.hpp
https://jira.mail.ru/browse/MAPSME-5308
=> Centering on bookmark fixed.

android/src/com/mapswithme/maps/MapFragment.java
[android] In case when app them is chaning via settings the drape was created twice. It happened because MapFragment had to be recreated to apply new theme. During recreation the surface was created two times which caused double creation of drape
https://jira.mail.ru/browse/MAPSME-5319
=> [android] Fixed doble drape creation while coming back from the settings

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/routing/RoutingController.java, map/routing_manager.cpp, map/routing_manager.hpp, qt/draw_widget.cpp, qt/draw_widget.hpp
Проблема:
При восстановлении маршрута гео-позиция может прийти слегка позже, чем маршрут загрузится из файла. В результате маршрут будет построен не от текущего положения пользователя, и при нажатии на кнопку "Начать" будет показан диалог о необходимости перестроения маршрута от текущего местоположения.
Решение:
Только после загрузки точек из файла ждем какой-то короткий временной интервал (2 секунды сейчас). Если в течение этого интервала гео-позиция приходит, то мы рекомендуем платформам перестроить маршрут от текущего местоположения.
=> Load route points recommendation

map/framework.cpp
Иконка с гиперлокалкой должна быть самой крутой
=> Fixed priority of search icons

data/mixed_tags.txt
Отмечаем полторы сотни зданий и стройплощадок значком ЦИАН-а и добавляем ссылки на соответствующие страницы их сайта.
=> [sponsored] Add CIAN branding

android/jni/com/mapswithme/maps/Sponsored.cpp, android/jni/com/mapswithme/maps/taxi/TaxiManager.cpp, android/jni/com/mapswithme/maps/viator/Viator.cpp, base/base.pro, base/waiter.hpp, partners_api/booking_api.cpp, partners_api/booking_api.hpp, partners_api/cian_api.cpp, partners_api/cian_api.hpp, partners_api/partners_api.pro, partners_api/partners_api_tests/async_gui_thread.hpp, partners_api/partners_api_tests/booking_tests.cpp, partners_api/partners_api_tests/cian_tests.cpp, partners_api/partners_api_tests/partners_api_tests.pro, partners_api/partners_api_tests/taxi_engine_tests.cpp, partners_api/partners_api_tests/uber_tests.cpp, partners_api/partners_api_tests/viator_tests.cpp, partners_api/partners_api_tests/yandex_tests.cpp, partners_api/taxi_engine.hpp, partners_api/viator_api.hpp, platform/platform.pro, platform/safe_callback.hpp, testing/testing.hpp, testing/testingmain.cpp, xcode/base/base.xcodeproj/project.pbxproj, xcode/partners_api/partners_api.xcodeproj/project.pbxproj, xcode/platform/platform.xcodeproj/project.pbxproj
Safe callbacks for partners apis + tests
=> [platform][partners_api] safe callbacks

drape_frontend/stylist.cpp
https://jira.mail.ru/browse/MAPSME-3658
=> Fixed crash by VB/IB overflow in text rendering

android/jni/com/mapswithme/maps/Framework.cpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/scenario_manager.cpp, drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp, map/framework.cpp
https://jira.mail.ru/browse/MAPSME-5324
=> Fixed centering on search result or bookmark on iOS.

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp, iphone/Maps/UI/PlacePage/MWMPlacePageData.mm, map/bookmark.hpp, map/framework.cpp, map/framework.hpp, map/place_page_info.cpp
https://jira.mail.ru/browse/MAPSME-5235
=> Fixed crash after place page refactoring

android/jni/com/mapswithme/maps/Framework.cpp, map/routing_manager.cpp, map/routing_manager.hpp, map/routing_mark.cpp, map/routing_mark.hpp
cherry-pick https://github.com/mapsme/omim/pull/6893
=> Refactoring of route point's intermediate index type.

drape_frontend/route_renderer.cpp, iphone/Maps/Classes/CustomViews/NavigationDashboard/Views/RoutePreview/RouteManager/RouteManagerViewModel.swift, iphone/Maps/Core/Routing/MWMRouter+RouteManager.mm, iphone/Maps/Core/Routing/MWMRouter.h
https://jira.mail.ru/browse/MAPSME-5357
=> Fixed route preview on points deletion

editor/editor_tests/editor_config_test.cpp
cherry-pick https://github.com/mapsme/omim/pull/6905
=> Fixed editor test

android/src/com/mapswithme/maps/bookmarks/data/Metadata.java
cherry-pick https://github.com/mapsme/omim/pull/6909
=> Added FMD_LEVEL for Android

coding/write_to_sink.hpp, local_ads/campaign_serialization.cpp, local_ads/local_ads_tests/campaign_serialization_test.cpp, std/type_traits.hpp
https://jira.mail.ru/browse/MAPSME-5350
https://jira.mail.ru/browse/MAPSME-5355
=> [local_ads] campaign ser/des fixes + tests

openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.cpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_mode.cpp, openlr/openlr_stat/openlr_stat.cpp
=> Save empty paths to openlr_stat assessment output.

base/base_tests/observer_list_test.cpp, base/observer_list.hpp, feature_list/feature_list.pro, indexer/mwm_set.hpp, map/framework.cpp, map/framework.hpp, map/map_tests/map_tests.pro, qt/CMakeLists.txt, qt/qt.pro, qt/update_dialog.cpp, search/search_integration_tests/search_integration_tests.pro, search/search_quality/features_collector_tool/features_collector_tool.pro, search/search_quality/search_quality_tool/search_quality_tool.pro, storage/CMakeLists.txt, storage/diff_scheme/diff_manager.cpp, storage/diff_scheme/diff_manager.hpp, storage/diff_scheme/diff_scheme_checker.cpp, storage/diff_scheme/diff_scheme_checker.hpp, storage/diff_scheme/diff_types.hpp, storage/index.hpp, storage/storage.cpp, storage/storage.hpp, storage/storage.pro, storage/storage_integration_tests/storage_downloading_tests.cpp, storage/storage_integration_tests/storage_group_download_tests.cpp, storage/storage_integration_tests/storage_http_tests.cpp, storage/storage_integration_tests/storage_integration_tests.pro, storage/storage_tests/storage_tests.pro
продолжение пуллреквеста от @VladiMihaylenko https://github.com/VladiMihaylenko/omim/pull/12
=> Download diffs

storage/diff_scheme/diff_manager.cpp, storage/diff_scheme/diff_manager.hpp, storage/diff_scheme/diff_scheme_checker.cpp
(+) дополнительное логирование, если сервак обосрется
=> [DIFFS] Fixed deadlock on start

routing/index_router.cpp
https://jira.mail.ru/browse/MAPSME-5397
Исправлено отображение прогресса при построении маршрута.
=> Fix routing progress

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, android/src/com/mapswithme/maps/ads/GoogleSearchAd.java
Передача данных о баннерах в поиске из ядра в платформенный код через JNI
=> [Android] Extracted search banner info from JNI

android/jni/com/mapswithme/maps/MapManager.cpp, android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java, iphone/Maps/Common/MWMConsts.h, iphone/Maps/UI/Autoupdate/MWMAutoupdateController.mm, iphone/Maps/UI/Downloader/Cells/MWMMapDownloaderTableViewCell.mm, storage/diff_scheme/diff_manager.cpp, storage/storage.cpp, storage/storage.hpp, storage/storage_tests/queued_country_tests.cpp
- Возвращение корректных размеров при обновлении карт (с учетом наличия диффов);
- Исправление прогресс-баров и окна автообновления карт для обеих платформ.
=> Correct update sizes and progress for interface

data/countries.txt, data/external_resources.txt
Данные нужны для тестирования diff-ов
=> [RELEASE ONLY] New data from 28.07.2017

platform/local_country_file_utils.cpp, platform/local_country_file_utils.hpp, platform/marketing_service.cpp, platform/marketing_service.hpp, storage/diff_scheme/diff_manager.cpp, storage/diff_scheme/diff_manager.hpp, storage/diff_scheme/diff_scheme_checker.cpp, storage/storage.cpp, storage/storage.hpp
https://jira.mail.ru/browse/MAPSME-5321
https://jira.mail.ru/browse/MAPSME-5323
=> Apply diffs on startup

drape_frontend/drape_frontend_tests/CMakeLists.txt, drape_frontend/drape_frontend_tests/drape_frontend_tests.pro, drape_frontend/drape_frontend_tests/path_text_test.cpp, drape_frontend/path_text_handle.cpp, drape_frontend/path_text_handle.hpp, drape_frontend/text_layout.cpp
https://jira.mail.ru/browse/MAPSME-4997
=> Rounding of spline corners for path text.

iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/MWMPPPreviewLayoutHelper.mm
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/58cbeab30aeb16625b81317b
=> [fix] [ios] Added logging for crash.

iphone/Maps/Classes/CustomViews/CircularProgress/MWMCircularProgress.h, iphone/Maps/Classes/CustomViews/CircularProgress/MWMCircularProgress.mm, iphone/Maps/Classes/CustomViews/CircularProgress/MWMCircularProgressView.h, iphone/Maps/Classes/CustomViews/CircularProgress/MWMCircularProgressView.mm, iphone/Maps/UI/Autoupdate/MWMAutoupdateController.mm
Dialog for cancelling maps auto-update download.
=> [MAPSME-5447] [ios] Added confirmation dialog.

data/countries.txt, data/external_resources.txt
=> [planet] New planet data from 17.08.2017

map/framework.cpp
https://jira.mail.ru/browse/MAPSME-5434
=> viator sponsored url fix

map/framework.cpp, map/framework.hpp, map/map_tests/bookmarks_test.cpp, map/map_tests/feature_getters_tests.cpp, map/map_tests/kmz_unarchive_test.cpp, map/map_tests/mwm_url_tests.cpp, mapshot/mapshot.cpp, openlr/openlr_match_quality/openlr_assessment_tool/main.cpp, platform/http_request.cpp, search/search_quality/assessment_tool/assessment_tool.cpp, storage/storage.cpp, storage/storage.hpp, storage/storage_integration_tests/migrate_tests.cpp, storage/storage_integration_tests/storage_3levels_tests.cpp, storage/storage_integration_tests/storage_update_tests.cpp
https://jira.mail.ru/browse/MAPSME-5449
=> Fixed download failure notification

qt/editor_dialog.cpp, qt/place_page_dialog.cpp, storage/diff_scheme/diff_scheme_checker.cpp
Поправил предупреждение при сборке приложения qt, и ошибку при сборке diff_checker под linux.
=> [fix] Add switch clauses for Level in qt, and fix compilation error

android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java
https://jira.mail.ru/browse/MAPSME-5466
=> Mapsme 5466 fix sponsored pp behaviour

map/framework.cpp, map/framework.hpp, map/place_page_info.hpp, partners_api/CMakeLists.txt, partners_api/locals_api.cpp, partners_api/locals_api.hpp, partners_api/partners_api.pro, xcode/partners_api/partners_api.xcodeproj/project.pbxproj
https://confluence.mail.ru/display/MAPSME/Locals.Maps.Me+integration
=> Locals API. First iteration.

map/routing_mark.hpp, map/user_mark.hpp, map/user_mark_container.cpp
https://jira.mail.ru/browse/MAPSME-5302
=> Do not select passed route mark.

android/res/layout/fragment_auth_editor_dialog.xml
https://jira.mail.ru/browse/MAPSME-5442
=> [android] Removed google button from profile dialog

android/src/com/mapswithme/maps/routing/RoutingController.java
https://jira.mail.ru/browse/MAPSME-5379
=> [android] Fixed routing statistics

android/AndroidManifest.xml, android/res/layout/fragment_editor.xml
[android] Made 'Details' field multiline
https://jira.mail.ru/browse/MAPSME-3771
=> [android] Fixed keyboard hidding of the details field in editor

android/src/com/mapswithme/maps/routing/RoutingController.java
https://jira.mail.ru/browse/MAPSME-5503
=> [android] Added deleting saved routing points when routing is cancelled

platform/country_defines.cpp, platform/country_defines.hpp, storage/queued_country.cpp, storage/storage.cpp, storage/storage.hpp
=> Fixed canceling of diff downloading.

android/src/com/mapswithme/maps/widget/menu/BaseMenu.java
https://jira.mail.ru/browse/MAPSME-2904
=> [android] Fixed fade effect problem caused by bottom menu

map/routing_manager.cpp, map/routing_mark.cpp, map/routing_mark.hpp
=> Remove the "my position" route mark before inserting of another one.

data/faq.html
=> FAQ Hotfix for release 7.5

data/categories.txt
=> [categories] Remove 'pomnik historyczny'

defines.hpp, platform/local_country_file_utils.cpp, storage/diff_scheme/diff_manager.cpp, storage/queued_country.hpp, storage/storage.cpp
=> Fixed canceling when diff is applying.

storage/storage.cpp
=> Check if there is a diff before downloading.

base/levenshtein_dfa.hpp, search/geocoder.cpp, search/ranker.cpp, search/ranking_info.cpp, search/ranking_info.hpp, search/ranking_utils.cpp, search/ranking_utils.hpp, search/search_integration_tests/helpers.cpp, search/search_integration_tests/helpers.hpp, search/search_integration_tests/processor_test.cpp, search/utils.cpp, search/utils.hpp
=> [search] Expose num typos to ranking info.

track_analyzing/track_analyzer/CMakeLists.txt
=> [track_analyzing] Linux build fix.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/routing/RoutingPlanInplaceController.java
https://jira.mail.ru/browse/MAPSME-5514
=> [android] Fixed compass visibility

openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.cpp
@mpimenov @tatiana-kondakova PTAL
=> [openlr] Fix to OpenLR assessment tool CarModelFactory creation.

android/src/com/mapswithme/util/sharing/MapObjectShareable.java
https://jira.mail.ru/browse/MAPSME-5515
=> [andorid] Fixed sharing text message

android/src/com/mapswithme/maps/routing/NavigationController.java
@darina @VladiMihaylenko PTAL 
https://jira.mail.ru/browse/MAPSME-5560
=> [android] Added closing navigation menu on stopping navigation

search/categories_cache.cpp, search/geocoder.cpp, search/geometry_cache.cpp, search/retrieval.cpp, search/retrieval.hpp, search/search_integration_tests/processor_test.cpp
@mpimenov @tatiana-kondakova PTAL
=> [search] Stateful retrieval.

routing/routing_consistency_tests/routing_consistency_tests.cpp
=> Routing integration tests build fix

3party/glm/glm/detail/func_common.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
В процессе ребеза обнаружилось ряд не значительных ошибок, которые у нас уже продолжительное время. Поправил.
@syershov @igrechuhin PTAL
=> Old minor issues are fixed.

routing_common/car_model.cpp
Reverting mistakenly merged commit PR https://github.com/mapsme/omim/pull/7080
@VladiMihaylenko @tatiana-kondakova PTAL
=> Reverting mistakenly merged commit PR https://github.com/mapsme/omim/pull/7080

xcode/generator_tool/generator_tool.xcodeproj/project.pbxproj
@syershov @VladiMihaylenko PTAL
=> xcode generator_tool build fix.

routing/index_router.cpp
MAPSME-5612
при переносе создания стартера из CalculateSubroute в DoCalculateRoute не разобралась, что при поиске лучшего сегмента надо учитывать направление только для первой стартовой точки, а не для стартовой точки каждого саброута. Поправила.
=> Fix finding best segment for intermediate points

routing/CMakeLists.txt, routing/bicycle_directions.cpp, routing/fake_edges_container.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_road_graph.cpp, routing/index_road_graph.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing.pro, routing/routing_tests/applying_traffic_test.cpp, routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp, routing/routing_tests/road_access_test.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
Cherry-pick коммитов из двух реквестов:
https://github.com/mapsme/omim/pull/7046
https://github.com/mapsme/omim/pull/7099
=> Cherry-pick fake endings to release-75

drape/support_manager.cpp, drape_frontend/drape_engine.cpp
=> Turn off AA by energy saving issues

routing/index_router.cpp, routing/index_router.hpp
После переноса создание starter из CalculateSubroute на уровень выше этот код стал не нужен.
=> Remove unused code

drape_frontend/path_text_handle.cpp, geometry/spline.cpp, geometry/spline.hpp
Временный фикс падения https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/59b7d9d5be077a4dcc816d18?time=last-seven-days
=> In path text handle added check on projection result.

routing/index_graph_starter.cpp
https://github.com/mapsme/omim/pull/7123
=> Cherry-pick [Fix fake PartOfReal ends for backward segments] to master

android/jni/Android.mk, android/jni/com/mapswithme/platform/Platform.cpp, android/jni/com/mapswithme/platform/Platform.hpp, android/jni/com/mapswithme/platform/SecureStorage.cpp, android/src/com/mapswithme/util/SecureStorage.java, platform/CMakeLists.txt, platform/platform.hpp, platform/platform.pro, platform/secure_storage.hpp, platform/secure_storage_dummy.cpp, platform/secure_storage_ios.mm, platform/secure_storage_qt.cpp, xcode/platform/platform.xcodeproj/project.pbxproj
Добавлен интерфейс для безопасного системного хранилища, в котором будут содержаться токены доступа к нашим сервисам. Реализация хранилища - на стороне платформ.
=> Added secure storage interface

routing/routing_tests/index_graph_test.cpp
Добавила тесты для https://github.com/mapsme/omim/pull/7125 и https://github.com/mapsme/omim/pull/7123
Тесты про работу с backward сегментами:
1) при построении маршрута из одного сегмента (старт и финиш проецируются на один сегмент) проверяем корректность построения маршрута вне зависимости от того, проекция на forward или backward сегмент (тестируем все комбинации forward/backward для старта и финиша) -- расширила существующий тест для маршрута из одного сегмента.
2) добавила тест корректности координат фейковых сегментов, тестируется корректность при любом сочетании forward/backward для старта и финиша -- в https://github.com/mapsme/omim/pull/7123 была исправлена ошибка при вычислении координат для backward сегментов.
=> Add IndexGraphStarter tests

android/res/drawable/list_divider.xml, android/res/layout/item_ugc_comment.xml, android/res/layout/item_ugc_rating.xml, android/res/layout/place_page_rating_records.xml, android/res/layout/place_page_ugc.xml, android/res/values/attrs.xml, android/res/values/dimens.xml, android/res/values/styles.xml, android/res/values/themes-base.xml, android/src/com/mapswithme/maps/ugc/UGC.java, android/src/com/mapswithme/maps/ugc/UGCReviewAdapter.java, android/src/com/mapswithme/maps/widget/RatingView.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/recycler/ItemDecoratorFactory.java
https://jira.mail.ru/browse/MAPSME-5520
Пока только UI + заглушки на стороне Java
=> Mapsme 5520 ugc reviews ui

data/countries.txt, data/external_resources.txt
=> [DNM][planet] Fresh data from 17.09.2017

android/gradle.properties
=> [android] Updated version to 7.5.3

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/Framework.java, configure.sh, map/CMakeLists.txt, map/framework.hpp, map/map.pro, map/user.cpp, map/user.hpp, xcode/map/map.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-5500
=> Added authentication system

data/categories.txt
Updated some translations and added translations for railway-level_crossing (OSM equivalent: railway=level_crossing).
=> [categories] Updated translations

routing/index_router.cpp, routing/index_router.hpp
https://github.com/mapsme/omim/pull/7126
=> Cherry-pick [Remove unused code] from release-75

routing/routing_tests/index_graph_test.cpp
https://github.com/mapsme/omim/pull/7131
=> Cherry-pick IndexGraphStarter tests from release-75 to master

android/AndroidManifest.xml, android/res/layout/fragment_ugc_editor.xml, android/res/layout/item_ugc_rating.xml, android/res/values/dimens.xml, android/src/com/mapswithme/maps/ugc/UGCEditorActivity.java, android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
https://jira.mail.ru/browse/MAPSME-5521
Пока только UI-ые доработки того, что было сделано на хаккатоне
=> [android] Implemented writing UGC review UI

drape_frontend/kinetic_scroller.cpp, drape_frontend/kinetic_scroller.hpp, drape_frontend/user_event_stream.cpp
Добавлено измерение мгновенной скорости, чтобы избегать ложных срабатываний
https://jira.mail.ru/browse/MAPSME-4751
=> Improved kinetic scroll

CMakeLists.txt, base/base_tests/worker_thread_tests.cpp, base/worker_thread.cpp, base/worker_thread.hpp
Also, thread-sanitizer is enabled. I'm planning to move PushDelayed() to TaskLoop and override it in the GuiThread in the next PR.
=> [base] WorkerThread supports delayed tasks now.

android/AndroidManifest.xml, android/build.gradle, android/res/layout/fragment_auth_passport_dialog.xml, android/res/layout/fragment_ugc_editor.xml, android/res/values/dimens.xml, android/res/values/donottranslate.xml, android/src/com/mapswithme/maps/auth/BaseMwmAuthorizationFragment.java, android/src/com/mapswithme/maps/auth/Constants.java, android/src/com/mapswithme/maps/auth/SocialAuthDialogFragment.java, android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/HttpClient.java, android/src/com/mapswithme/util/SecureStorage.java
[android] Implemented obtaining Facebook oauth token and passing it to the core
https://jira.mail.ru/browse/MAPSME-5587
Получение facebook токена и соотвествующий UI для этого. Также передача это токена в метод authenticate ядра. 
Осталось добавить пермишины к запросу необходимые (информацию о пользователи, почте и т.д.) + реализовать SecureStorage, но прежде надо отладить ядро и сервер авторизации, чтобы они отдавали mapsme токен.
=> [android] Added native facebook authentication

android/res/values/donottranslate.xml, map/user.cpp
Вливать только после того как будет замержен https://github.com/mapsme/omim-private/pull/57
=> [android] Temporary added test facebook credentials

CMakeLists.txt, openlr/decoded_path.cpp, openlr/openlr_match_quality/openlr_assessment_tool/CMakeLists.txt, openlr/openlr_match_quality/openlr_assessment_tool/main.cpp, openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.cpp, openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.hpp, openlr/openlr_match_quality/openlr_assessment_tool/map_widget.cpp, openlr/openlr_match_quality/openlr_assessment_tool/map_widget.hpp, openlr/openlr_match_quality/openlr_assessment_tool/points_controller_delegate_base.hpp, openlr/openlr_match_quality/openlr_assessment_tool/segment_correspondence.cpp, openlr/openlr_match_quality/openlr_assessment_tool/segment_correspondence.hpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_drawer_delegate_base.hpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_mode.cpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_mode.hpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_panel.cpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_panel.hpp, openlr/openlr_match_quality/openlr_assessment_tool/trafficmodeinitdlg.cpp, openlr/openlr_match_quality/openlr_assessment_tool/trafficmodeinitdlg.h, openlr/openlr_match_quality/openlr_assessment_tool/web_view.cpp, openlr/openlr_match_quality/openlr_assessment_tool/web_view.hpp
=> Openlr tool.  Partner's map on the side.

routing/CMakeLists.txt, routing/fake_edges_container.hpp, routing/fake_graph.hpp, routing/fake_vertex.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/routing.pro, routing/routing_tests/CMakeLists.txt, routing/routing_tests/fake_graph_test.cpp, routing/routing_tests/routing_tests.pro, ugc/types.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Вынесла FakeGraph и FakeVertex из IndexGraphStarter, добавила тесты на FakeGraph
=> Move FakeVertex and FakeGraph to separate files

android/AndroidManifest.xml, android/build.gradle, android/src/com/mapswithme/maps/ads/FacebookAdsLoader.java, android/src/com/mopub/nativeads/FacebookNative.java
https://jira.mail.ru/browse/MAPSME-5695
=> [android] Update Facebook native ads sdk and MopUb sdk

base/CMakeLists.txt, base/base.pro, base/base_tests/CMakeLists.txt, base/base_tests/base_tests.pro, base/base_tests/clustering_map_tests.cpp, base/clustering_map.hpp
I'm going to use this map in generator, to collect cities boundaries. The reason is that there is a lot of features corresponding to a city in OSM (city center, boundary, etc.), and exactly one of them will be transformed to a feature, but it would be nice to collect boundary info from others.
=> [base] ClusteringMap.

generator/generator_tests/transit_test.cpp, generator/transit_generator.cpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_serdes.hpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
cherry-pick PR https://github.com/mapsme/omim/pull/7205 на ветку transit.
@tatiana-kondakova PTAL&merge
=> Data structures for transit.

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/jni/com/mapswithme/maps/ugc/UGC.cpp, android/src/com/mapswithme/maps/ugc/UGC.java, android/src/com/mapswithme/maps/ugc/UGCController.java, android/src/com/mapswithme/maps/ugc/UGCEditorActivity.java, android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java, android/src/com/mapswithme/maps/ugc/UGCUpdate.java, android/src/com/mapswithme/maps/widget/placepage/BottomPlacePageAnimationController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
Добавил реализацию jNI для UGCUpdate. Особое внимание, пожалуйста, на сишный код.
=> Mapsme 5518 ppp ugc create button

android/src/com/mapswithme/maps/widget/placepage/Sponsored.java, android/src/com/mapswithme/util/statistics/Statistics.java, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, iphone/Maps/Common/Statistics/StatisticsStrings.h, iphone/Maps/UI/PlacePage/MWMPlacePageData.h, iphone/Maps/UI/PlacePage/MWMPlacePageData.mm, iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm, map/framework.cpp, map/place_page_info.hpp, platform/marketing_service.cpp, platform/marketing_service.hpp
https://jira.mail.ru/browse/MAPSME-5719
=> Added a sponsored project Thor

configure.sh, map/user.cpp, map/user.hpp
https://jira.mail.ru/browse/MAPSME-5716
=> Added user review ids

routing/CMakeLists.txt, routing/fake_feature_ids.cpp, routing/fake_feature_ids.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/routing.pro, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/transit_graph.hpp, routing/transit_graph_loader.cpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, routing/world_graph.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Частичная реализация TransitGraph, доработка TransitWorldGraph.
Не сделано:
- TransitGraphLoader
- использование TransitWorldGraph в IndexRouter
- cross-mwm для транспорта
=> TransitGraph implementation

android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/jni/com/mapswithme/maps/ugc/UGC.cpp, android/res/values/attrs.xml, android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java, android/src/com/mapswithme/maps/bookmarks/data/MapObject.java, android/src/com/mapswithme/maps/ugc/UGC.java, android/src/com/mapswithme/maps/ugc/UGCController.java, android/src/com/mapswithme/maps/ugc/UGCEditorActivity.java, android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java, android/src/com/mapswithme/maps/ugc/UGCRatingAdapter.java, android/src/com/mapswithme/maps/ugc/UGCUpdate.java, android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-5521
=> Mapsme 5521 connect ugc editor ui with logic

android/res/values/donottranslate.xml, map/user.cpp
https://jira.mail.ru/browse/MAPSME-5685
=> [core] [android] Enabled prod passport and facebook credentials

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/jni/com/mapswithme/maps/ugc/UGC.cpp, android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/background/WorkerService.java, android/src/com/mapswithme/maps/ugc/UGC.java, iphone/Maps/Classes/MapsAppDelegate.h, iphone/Maps/Classes/MapsAppDelegate.mm, map/framework.cpp, map/framework.hpp, map/user.cpp, map/user.hpp, qt/mainwindow.cpp
https://jira.mail.ru/browse/MAPSME-5498
=> Added UGC uploading

data/countries.txt, data/external_resources.txt
=> [planet] Fresh data from 6.10.2017

3party/jansson/myjansson.hpp, indexer/index.cpp, indexer/index.hpp, map/framework.cpp, search/editor_delegate.cpp, ugc/CMakeLists.txt, ugc/api.cpp, ugc/api.hpp, ugc/serdes_json.hpp, ugc/storage.cpp, ugc/storage.hpp, ugc/types.hpp, ugc/ugc.pro, ugc/ugc_tests/CMakeLists.txt, ugc/ugc_tests/storage_tests.cpp, ugc/ugc_tests/ugc_tests.pro
Don't merge until unit tests will be ready
=> UGCUpdate storage

android/src/com/mapswithme/maps/auth/SocialAuthDialogFragment.java, android/src/com/mapswithme/maps/ugc/UGCController.java, android/src/com/mapswithme/maps/ugc/UGCEditorActivity.java, android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java, android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-5717
=> [android] Added ugc statistics

coding/multilang_utf8_string.hpp, indexer/feature.cpp, search/city_finder.hpp, search/locality_finder.cpp, search/locality_finder.hpp, search/processor.cpp, search/ranker.cpp, search/ranker.hpp, search/search_tests/locality_finder_test.cpp, search/search_tests/locality_selector_test.cpp
@mpimenov @milchakov PTAL
Get rid of cache invalidations on LocalityFinder::SetLanguage.
=> [search] Reduced number of cache invalidations in LocalityFinder.

data/categories.txt
Поправил ошибку, которую Макс нашёл в #7254.
=> [types] Fix typo in categories

partners_api/mopub_ads.cpp, partners_api/partners_api_tests/ads_engine_tests.cpp, partners_api/rb_ads.cpp
=> [halloween] banner ids + tests

feature_list/feature_list.cpp, tools/unix/generate_planet.sh
Правки в feature_list и скрипт сборки планеты со сборочного сервера mapsme4. В FL учитываю оператора, беру ближайший адрес вместо точного и позволяю запустить скрипт для одного файла. В generate_planet поправил сборку таблиц для localads и исправил синтаксическую ошибку в разделе про UGC.
=> [scripts] Update feature_list and generate_planet

android/jni/com/mapswithme/core/jni_helper.cpp, android/jni/com/mapswithme/core/jni_helper.hpp, android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/jni/com/mapswithme/maps/UserMarkHelper.hpp, android/jni/com/mapswithme/maps/ugc/UGC.cpp, android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java, android/src/com/mapswithme/maps/bookmarks/data/MapObject.java, android/src/com/mapswithme/maps/ugc/UGC.java, android/src/com/mapswithme/maps/ugc/UGCController.java, android/src/com/mapswithme/maps/ugc/UGCEditorActivity.java, android/src/com/mapswithme/maps/ugc/UGCUpdate.java
https://jira.mail.ru/browse/MAPSME-5521
=> Mapsme 5521 getting rating records

android/res/layout/place_page_ugc.xml, android/src/com/mapswithme/maps/ugc/UGCController.java, data/ugc_types.csv
https://jira.mail.ru/browse/MAPSME-5519
=> [android] Connected UGC summary ui with logic

data/categories.txt
Fixed some incorrect Finnish translations in categories.
=> [categories] Updated Finnish translations.

android/AndroidManifest.xml, android/build.gradle, android/jni/com/mapswithme/maps/PrivateVariables.cpp, android/src/com/mapswithme/maps/MwmApplication.java, android/src/com/mapswithme/maps/PrivateVariables.java, configure.sh
https://jira.mail.ru/browse/MAPSME-5579
=> Mapsme 5579 apps flyer sdk

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/maps/widget/placepage/Sponsored.java, android/src/com/mapswithme/util/statistics/Statistics.java, indexer/ftypes_sponsored.hpp, iphone/Maps/Common/Statistics/StatisticsStrings.h, iphone/Maps/UI/PlacePage/MWMPlacePageData.h, iphone/Maps/UI/PlacePage/MWMPlacePageData.mm, iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm, map/framework.cpp, map/place_page_info.hpp
https://jira.mail.ru/browse/MAPSME-5769
=> Added Halloween sponsored objects

routing/index_road_graph.cpp, routing/index_router.cpp
Включаю создание графа с общественным транспортом в IndexRouter
=> Create transit world graph for transit vehicle type

generator/generator_tool/generator_tool.cpp, tools/unix/generate_planet.sh
Допилил изменение файла планеты перед сборкой и поправил загрузку классификатора для секции UGC.
=> [generator] Fix two issues in generator

generator/generator_tests/transit_test.cpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_serdes.hpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
cherry-pick https://github.com/mapsme/omim/pull/7295 to master
@ygorshenin  @mpimenov PTAL
=> [cherry-pick] Saving title anchors at transit section. 

drape_frontend/text_shape.cpp
https://jira.mail.ru/browse/MAPSME-5792
=> Fixed overlay rank for primary and secondary text.

android/res/layout/divider_horizontal.xml, android/res/layout/place_page_bookmark_details.xml, android/res/layout/place_page_details.xml, android/res/layout/place_page_fat_shadow.xml, android/res/layout/place_page_local_ad.xml, android/res/layout/place_page_more.xml, android/res/layout/place_page_ugc.xml, android/src/com/mapswithme/maps/ugc/UGCController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-5774
=> [android] Fixed place page dividers and shadows

android/src/com/mapswithme/maps/ugc/UGCController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-5782
https://jira.mail.ru/browse/MAPSME-5791
=> [andorid] Fixed rules for showing ugc view for different POI

iphone/Maps/Maps.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-5799
=> [ios] Added xib into xcode project.

tools/python/openlr/quality.py
=> Add comparison feature to the evaluation tool. Fix lcs.

android/res/values/themes-base.xml, android/src/com/mapswithme/maps/MapFragment.java
https://jira.mail.ru/browse/MAPSME-5608
=> Mapsme 5608 black screen

search/pysearch/CMakeLists.txt, search/pysearch/bindings.cpp, storage/country.cpp, storage/country.hpp, storage/storage.cpp
@bykoianko @tatiana-kondakova PTAL
=> [pysearch] Get rid of Storage.

android/src/com/mapswithme/maps/widget/RatingView.java
https://jira.mail.ru/browse/MAPSME-5771
=> [android] Centered '-' in rating view

iphone/Maps/Bookmarks/SelectSetVC.h, iphone/Maps/Bookmarks/SelectSetVC.mm, iphone/Maps/UI/EditBookmark/MWMEditBookmarkController.mm
https://jira.mail.ru/browse/MAPSME-5741
=> [ios] Fixed crash after changing bookmark's category.

android/src/com/mapswithme/maps/bookmarks/data/MapObject.java
https://jira.mail.ru/browse/MAPSME-5805
=> Mapsme 5805 crash during unmarshaling mapobject

android/jni/com/mapswithme/maps/ugc/UGC.cpp, android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java, android/src/com/mapswithme/maps/ugc/UGCUpdate.java
https://jira.mail.ru/browse/MAPSME-5808
=> Mapsme 5808 keyboard locale

android/jni/com/mapswithme/maps/Framework.cpp, iphone/Maps/Classes/CustomViews/MapViewControls/APIBar/MWMAPIBar.mm, map/CMakeLists.txt, map/bookmark.cpp, map/bookmark_manager.cpp, map/bookmark_manager.hpp, map/framework.cpp, map/framework.hpp, map/local_ads_manager.cpp, map/local_ads_mark.cpp, map/local_ads_mark.hpp, map/map.pro, map/map_tests/bookmarks_test.cpp, map/map_tests/mwm_url_tests.cpp, map/mwm_url.cpp, map/routing_manager.cpp, map/routing_mark.cpp, map/routing_mark.hpp, map/search_mark.cpp, map/search_mark.hpp, map/user_mark.cpp, map/user_mark.hpp, map/user_mark_container.cpp, map/user_mark_container.hpp, openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.cpp, search/search_quality/assessment_tool/sample_view.cpp, xcode/map/map.xcodeproj/project.pbxproj, xcode/search/search.xcodeproj/project.pbxproj
Доработана визуальное представление для результатов поиска. Теперь можно визуализировать фильтр booking.com по датам
=> Search result improvements

base/CMakeLists.txt, base/base.pro, base/url_helpers.cpp, base/url_helpers.hpp, coding/coding.pro, map/local_ads_manager.cpp, partners_api/CMakeLists.txt, partners_api/booking_api.cpp, partners_api/booking_api.hpp, partners_api/booking_http.cpp, partners_api/booking_http.hpp, partners_api/partners_api.pro, partners_api/partners_api_tests/booking_tests.cpp, platform/http_client.cpp, platform/http_client.hpp, tools/python/ResponseProvider.py, tools/python/jsons.py, xcode/base/base.xcodeproj/project.pbxproj, xcode/partners_api/partners_api.xcodeproj/project.pbxproj
Добавил еще один метод в букинг апи, после этого его пришлось зарефакторить, потому что файлики разрослись
=> [partners_api] Booking availability part1

data/countries.txt, data/external_resources.txt
=> [planet] Fresh data from 20.10.2017

android/src/com/mapswithme/maps/ugc/UGCRatingRecordsAdapter.java
https://jira.mail.ru/browse/MAPSME-5837
=> [android] Added localizaton retreiving for rating records in PP

ugc/api.cpp, ugc/api.hpp, ugc/storage.cpp, ugc/storage.hpp, ugc/types.hpp, ugc/ugc_tests/storage_tests.cpp
https://jira.mail.ru/browse/MAPSME-5760
=> Added callback to SetUGCUpdate.

routing/transit_info.hpp
=> Transit warning fix.

android/res/layout/fragment_editor.xml
https://jira.mail.ru/browse/MAPSME-5688
=> [android] Fixed recycler view behaviour in 'add language' part in editor

map/framework.cpp, search/downloader_search_callback.hpp, search/emitter.hpp, search/everywhere_search_params.hpp, search/processor.hpp, search/search_params.cpp, search/search_params.hpp, search/search_quality/sample.cpp, search/search_quality/sample.hpp, search/search_tests_support/test_search_engine.hpp, search/search_tests_support/test_search_request.cpp, search/search_tests_support/test_search_request.hpp, search/viewport_search_callback.cpp, search/viewport_search_callback.hpp, search/viewport_search_params.hpp, storage/downloader_search_params.hpp
=> [search] Simplified SearchParams.

android/src/com/mapswithme/maps/search/SearchFragment.java
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/59eb2d4261b02d480df31029/sessions/59F0B1C5000A000124B39796F9B1D2E6_fe3b7c32b99b11e7a5d056847afe9799_0_v2
=> [android] Fixed crash in search add view

android/src/com/mapswithme/util/Utils.java
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/59ef604f61b02d480d2035af/sessions/59F0C92800AD000109AE0EF35DCAD540_d846a7fcb9a911e7bdd156847afe9799_0_v2
=> [andorid] Fixed NPE while navigating to parent activity

android/gradle.properties, android/res/layout/fragment_ugc_editor.xml
https://jira.mail.ru/browse/MAPSME-5879
=> Mapsme 5879 multiline for ugc review

android/res/layout/fragment_ugc_editor.xml
capitalization of the first character of every sentence.
=> [android] Added textCapSentences mode for ugc review field

storage/storage_tests/storage_tests.cpp
@VladiMihaylenko @bykoianko PTAL
=> [storage] One more test on failing network policy.

map/framework.cpp, map/place_page_info.cpp, map/place_page_info.hpp
https://jira.mail.ru/browse/MAPSME-5888
=> Refused adding ugc for created or deleted objects.

search/processor.cpp, search/processor.hpp, search/search_integration_tests/helpers.cpp
=> [search] Removed multiple viewports.

search/keyword_lang_matcher.cpp, search/keyword_lang_matcher.hpp, search/keyword_matcher.cpp, search/keyword_matcher.hpp, search/processor.cpp, search/processor.hpp, search/ranker.cpp, search/search_integration_tests/pre_ranker_test.cpp, search/search_tests/keyword_lang_matcher_test.cpp, search/search_tests/keyword_matcher_test.cpp
The efficiency should drop a little because now new vectors
are created all the time but, taking into account how small
a part of processing a query this is, I think that introducing
additional lighter methods is not justified.
=> [search] Refactored the lang indexes in the KeywordLangMatcher.

platform/local_country_file_utils.cpp, storage/storage.cpp, storage/storage.hpp
Фикс креша
https://jira.mail.ru/browse/MAPSME-5889
И удаление диффов в устаревших папках
=> Storage fix

android/src/com/mapswithme/maps/auth/BaseMwmAuthorizationFragment.java
https://jira.mail.ru/browse/MAPSME-5846
=> [android] Added connection check for auth dialog showing

android/src/com/mapswithme/maps/ugc/EditParams.java, android/src/com/mapswithme/maps/ugc/UGCController.java, android/src/com/mapswithme/maps/ugc/UGCEditorActivity.java, android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
https://jira.mail.ru/browse/MAPSME-5884
Добавил к крэшу доп инфо (адрес, заголовок и координаты) , выглядит так https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro.debug/issues/59fb14ab61b02d480da37622?time=last-hour
=> Mapsme 5884 null feature id for ugc

generator/generator_tests/transit_test.cpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_types.cpp, routing_common/transit_types.hpp
Добавлено обязательно поле время пересадок в Line.
@tatiana-kondakova @darina @Zverik PTAL
=> [transit] Adding interval field to Line.

routing/transit_graph.cpp
https://github.com/mapsme/omim/pull/7458#issuecomment-342496802
=> Add comment about assumed type of transit arrival time distribution

routing/transit_graph.cpp
Дополнительный штраф на основе интервала следования транспорта применяется только если у нас есть разные line, соединенные между собой без transfer (например одна и та же остановка автобуса, на которой останавливаются много автобусов, одна и та же платформа, на которой останавливаются поезда разных веток).
Если line соединяются через ребро типа transfer (пересадка с ветки на ветку в метро), то, по договоренности с @bykoianko и @Zverik о формате, вес этого ребра является временем пересадки (включает в себя всё -- вход, выход, переход, ожидание).
=> No extra penalty for transfer edges

android/jni/com/mapswithme/maps/ugc/UGC.cpp, android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java, android/src/com/mapswithme/maps/ugc/UGCUpdate.java
https://jira.mail.ru/browse/MAPSME-5898
=> [android] Added passing the keyboard locale for UGCUpdate

tools/python/stylesheet/cat_stat.py
Использовал этот скрипт, чтобы подготовить #5921. Выводит кучу информации в csv: какие типы отображаются иконками или областями, какие можно редактировать, сколько объектов в OSM по типам, какие из популярных забыли.
=> [python] A script to use tag usage stats for suggesting new categories

search/CMakeLists.txt, search/geocoder.cpp, search/geocoder.hpp, search/geocoder_context.cpp, search/geocoder_context.hpp, search/processor.cpp, search/search.pro, search/search_integration_tests/CMakeLists.txt, search/search_integration_tests/helpers.hpp, search/search_integration_tests/interactive_search_test.cpp, search/search_integration_tests/search_integration_tests.pro, search/search_integration_tests/tracer_tests.cpp, search/search_params.hpp, search/search_tests/locality_scorer_test.cpp, search/streets_matcher.cpp, search/tracer.cpp, search/tracer.hpp
Tracer for search, collects all valid parses of the search query.
=> [search] Tracer.

android/res/layout/item_ugc_rating.xml, android/res/layout/item_ugc_rating_record.xml, android/res/values/styles.xml, android/src/com/mapswithme/maps/ugc/UGCReviewAdapter.java
https://jira.mail.ru/browse/MAPSME-5943
https://jira.mail.ru/browse/MAPSME-5948
=> Mapsme 5943 float start rating for pp

CMakeLists.txt, qt/CMakeLists.txt
Original pull request https://github.com/mapsme/omim/pull/7504
=> Qt version check added, and some styling remarks fixed

android/jni/com/mapswithme/maps/Framework.cpp, android/src/com/mapswithme/maps/routing/TransitRouteInfo.java, android/src/com/mapswithme/maps/routing/TransitStepInfo.java, android/src/com/mapswithme/maps/routing/TransitStepType.java, map/routing_manager.cpp, map/routing_manager.hpp, routing/routing_session.cpp, routing/routing_session.hpp
Added formatted transit distance, collecting information about intermediate route points.
=> Formatted transit distance strings.

routing/index_router.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/transit_graph.cpp, routing/transit_graph.hpp, routing/transit_graph_loader.cpp, routing/transit_graph_loader.hpp
Сделала TestTransitGraphLoader аналогично TesIndexGraphLoader и функцию для создания TransitWorldGraph  в тестах
=> [routing][transit] Create TestTransitGraphLoader

android/res/layout/fragment_bookmark_categories.xml, android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java, map/bookmark.cpp, map/bookmark_manager.cpp, map/bookmark_manager.hpp
https://jira.mail.ru/browse/MAPSME-5994
=> [Android] Added bookmarks async loading in bookmark activity

search/ranker.cpp
https://jira.mail.ru/browse/MAPSME-6018
=> [search] Fixed an uncaught CancelException.

android/res/drawable/dot_divider_night.xml, android/res/layout/routing_bottom_panel_transit.xml, android/res/values/themes-attrs.xml, android/res/values/themes-base.xml, android/src/com/mapswithme/maps/routing/RoutingBottomMenuController.java, android/src/com/mapswithme/maps/routing/TransitStepView.java
https://jira.mail.ru/browse/MAPSME-5824
=> Mapsme 5824 transit crash on prelolipop

map/search_api.cpp, map/search_api.hpp, search/search_integration_tests/interactive_search_test.cpp, search/viewport_search_callback.cpp
https://jira.mail.ru/browse/MAPSME-6029
=> [search] Fixed search in viewport.

data/categories.txt
I have checked the Spanish translation of categories and have found some minor mistakes plus mixture of Latin American and Castilian Spanish. I have corrected them. 
Please note that "es" is now 100% Castilian Spanish.
Greetings!
=> [categories] Translation improvements for es

openlr/openlr_model_xml.cpp
=> [OpenLR] Skip segments with no <locationReference>.

data/countries.txt, data/external_resources.txt
Свежая планета, уже раскачена.
=> [planet] Fresh data from 17.11.2017

android/jni/com/mapswithme/maps/editor/Editor.cpp, indexer/editable_map_object.cpp, indexer/editable_map_object.hpp, indexer/indexer_tests/editable_map_object_test.cpp, iphone/Maps/UI/Editor/MWMEditorViewController.mm
https://github.com/mapsme/omim/pull/7582 with BNF
пришлось пересоздать, потому что предыдущий не переоткрыть
=> [editor] added possibility to save several phone numbers

android/jni/com/mapswithme/maps/locals/Locals.cpp, android/src/com/mapswithme/maps/discovery/DiscoveryManager.java, android/src/com/mapswithme/maps/discovery/LocalExpert.java, android/src/com/mapswithme/maps/discovery/Locals.java, android/src/com/mapswithme/maps/discovery/LocalsError.java
https://jira.mail.ru/browse/MAPSME-5970
=> Mapsme 5970 java structures for discovery

data/countries.txt
Файлы планеты не изменились, только размеры секции ugc в большинстве mwm.
=> [planet] Update data with new reviews

data/countries.txt, data/external_resources.txt
=> [planet] Fresh planet data from 17.11.2017 to master branch

map/booking_filter_availability_params.hpp, map/framework.cpp
https://jira.mail.ru/browse/MAPSME-6064
Не мержить пока не прояснили как все-таки надо делать
=> [booking] availability filter - return sorted vector of features

generator/routing_index_generator.cpp, generator/routing_index_generator.hpp, generator/transit_generator.cpp, routing/vehicle_mask.hpp, routing_common/routing_common_tests/transit_test.cpp, routing_common/transit_types.hpp
Реализован метод для заполнения секции transit_cross_mwm информацией о переходах.
=> [transit] Implementation CalcCrossMwmTransitions()

indexer/editable_map_object.cpp
https://jira.mail.ru/browse/MAPSME-6093
=> [editor] validate name crash fix

routing/transit_graph_loader.cpp
Добавила вызов IsValidSortedUnique для десериализованных данных.
=> Check deserialized data is valid in TransitGraphLoaderImpl::CreateTransitGraph

map/framework.cpp, storage/storage.cpp, storage/storage.hpp
https://jira.mail.ru/browse/MAPSME-1816
=> [editor] disable editing during download maps

generator/transit_generator.cpp
=> Adding log for building transit section.

generator/generator_tests/transit_graph_test.cpp, generator/transit_generator.cpp, generator/transit_generator.hpp, geometry/region2d.hpp
Данный тест проверяет сериализацию и десериализацию всей секции transit. Для этого в класс GraphData добавлен метод: DeserializeForTesting(). Файл transit_graph_test.cpp модифицирован так, что сериализация и десериализция проверяется на 3 графах.
=> Whole transit section test on serialization and deserialization.

android/jni/com/mapswithme/maps/SearchEngine.cpp, android/jni/com/mapswithme/maps/UserMarkHelper.cpp, android/jni/com/mapswithme/maps/UserMarkHelper.hpp, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/search/NativeBookingFilterListener.java, android/src/com/mapswithme/maps/search/SearchEngine.java, android/src/com/mapswithme/maps/search/SearchFilterController.java, android/src/com/mapswithme/maps/search/SearchFragment.java, android/src/com/mapswithme/maps/search/SearchResult.java
- Доработано JNI;
- Сделан интерфейс в Java для приема результатов фильтра;
- Проброшен FeatureId в результат поиска на Java;
- Параметры фильтра перенесены в SearchFilterController.
=> Improved JNI for Booking filter

data/ugc_types.csv
https://jira.mail.ru/browse/MAPSME-5995
Не мержить до подтверждения от @igortomko
=> [ugc] rating categories are changed for several types

generator/generator_tool/generator_tool.cpp, generator/transit_generator.cpp, tools/unix/generate_planet.sh
1. Дорожная сеть общественного транспорта вполне может быть без пересадок;
2. Изменил ряд сообщений в лог в генераторе;
@tatiana-kondakova @Zverik PTAL
=> [transit] GraphData is not empty if m_transfers is empty.

android/res/layout/card_loading.xml, android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java, android/src/com/mapswithme/maps/gallery/ErrorAdapterStrategy.java, android/src/com/mapswithme/maps/gallery/GalleryAdapter.java, android/src/com/mapswithme/maps/gallery/Holders.java, android/src/com/mapswithme/maps/gallery/LoadingAdapterStrategy.java, android/src/com/mapswithme/maps/gallery/OfflineAdapterStrategy.java, android/src/com/mapswithme/maps/gallery/SingleItemAdapterStrategy.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-5967
Добавил переходы по ссылкам для виатора на дискавери экране.
=> [andorid] Added url support for viator in discovery manager

android/src/com/mapswithme/maps/editor/EditorHostFragment.java
https://github.com/mapsme/omim/pull/7694 на релизную ветку
=> [editor] add language fix

generator/generator_tests/transit_graph_test.cpp, generator/transit_generator.cpp, routing_common/transit_types.hpp
cherry-pick 7701
@tatiana-kondakova PTAL
=> [transit] Removing equivalent edges.

indexer/osm_editor.cpp
подробное описание в тикете https://jira.mail.ru/browse/MAPSME-1777
=> [editor] call LoadMapEdits before uploading changes

base/base_tests/mem_trie_test.cpp, base/mem_trie.hpp, indexer/categories_holder.hpp, indexer/categories_index.cpp, indexer/categories_index.hpp, indexer/indexer_tests/categories_test.cpp, indexer/search_string_utils.cpp, indexer/trie.hpp, search/base/inverted_list.hpp, search/base/mem_search_index.hpp, search/cities_boundaries_table.cpp, search/feature_offset_match.hpp, search/geocoder.cpp, search/pre_ranker.cpp, search/retrieval.cpp, search/search_tests/locality_scorer_test.cpp, search/search_tests/mem_search_index_tests.cpp, search/utils.hpp
Old implementation was not too efficient in terms of memory and time. Current implementation compresses paths without branches in trie, i.e. combines single-letter edges without branches to a single edge.
=> [base] Compressed MemTrie.

generator/generator_tool/generator_tool.cpp, platform/platform.cpp, platform/platform.hpp, platform/platform_tests_support/writable_dir_changer.cpp, tools/unix/generate_planet.sh
cherry-pick to master https://github.com/mapsme/omim/pull/7706
@Zverik PTAL
=> transit и transit_cross_mwm section generation.

android/res/layout/item_discovery_search.xml, android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/discovery/DiscoveryActivity.java, android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java, android/src/com/mapswithme/maps/gallery/AdapterStrategy.java, android/src/com/mapswithme/maps/gallery/GalleryAdapter.java, android/src/com/mapswithme/maps/gallery/Holders.java, android/src/com/mapswithme/maps/gallery/ItemSelectedListener.java, android/src/com/mapswithme/maps/gallery/Items.java, android/src/com/mapswithme/maps/gallery/RegularAdapterStrategy.java, android/src/com/mapswithme/maps/gallery/impl/BaseItemSelectedListener.java, android/src/com/mapswithme/maps/gallery/impl/CianAdapterStrategy.java, android/src/com/mapswithme/maps/gallery/impl/Factory.java, android/src/com/mapswithme/maps/gallery/impl/SearchBasedAdapterStrategy.java, android/src/com/mapswithme/maps/gallery/impl/ViatorAdapterStrategy.java, android/src/com/mapswithme/maps/routing/RoutingController.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-5968
=> Mapsme 5968 route to for discovery

generator/generator_tool/generator_tool.cpp, platform/platform.hpp, platform/platform_unix_impl.cpp, platform/platform_win.cpp
@mpimenov @ygorshenin PTAL
Замечание. Данный PR не будет продублирован на release-80, поскольку является косметическим и уточняет сообщение в генераторе.
=> Generator tool comment fix.

android/build.gradle
Original source:
https://developer.android.com/topic/libraries/support-library/setup.html
=> [android] Fix gradle build for mopub dependency

routing/routing_tests/astar_algorithm_test.cpp
cherry-pick
https://github.com/mapsme/omim/pull/7726
=> [RELEASE ONLY] Fix linux gcc build

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/discovery/DiscoveryActivity.java, android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
https://jira.mail.ru/browse/MAPSME-5968
=> [android] Added showing PP from discovery screen

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
If in pending mode defined only 1 point.
=> [MAPSME-5875] [ios] Fixed navigation dashboard display.

drape_frontend/frontend_renderer.cpp, drape_frontend/tile_key.cpp, map/user_mark_container.cpp, map/user_mark_container.hpp
Cherry pick https://github.com/mapsme/omim/pull/7734
=> User marks invalidation fixed.

drape_frontend/text_layout.cpp
https://jira.mail.ru/browse/MAPSME-6161
=> Fixed crash by assert in path text calculation

indexer/edits_migration.cpp, indexer/edits_migration.hpp, indexer/indexer_tests/osm_editor_test.cpp, indexer/osm_editor.cpp, indexer/osm_editor.hpp, map/framework.cpp, search/editor_delegate.cpp, search/editor_delegate.hpp
Зарефакторил метод LoadMapEdits
=> [editor] load map edits refactoring

map/place_page_info.cpp, map/place_page_info.hpp
https://jira.mail.ru/browse/MAPSME-6163
Пока нет возможности протестировать, мержить после появления новогодних объектов и тестирования с ними
=> [editor] disable editing for sonsored-holiday

search/search_quality/assessment_tool/CMakeLists.txt, search/search_quality/assessment_tool/feature_info_dialog.cpp, search/search_quality/assessment_tool/feature_info_dialog.hpp, search/search_quality/assessment_tool/main_view.cpp, search/search_quality/assessment_tool/main_view.hpp, search/search_quality/features_collector_tool/features_collector_tool.cpp, search/search_quality/matcher.cpp, search/search_quality/sample.cpp, search/search_quality/search_quality_tool/search_quality_tool.cpp
=> [search-quality] Fixed tools.

android/res/layout/card_loading.xml, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/discovery/DiscoveryActivity.java, android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java, android/src/com/mapswithme/maps/gallery/Holders.java
https://jira.mail.ru/browse/MAPSME-6166
=> [android] Added TabletUI support for discovery

search/geocoder.cpp, search/search_integration_tests/processor_test.cpp
A temporary measure to be on the safer side while we investigate the regression.
Note that the model was not recalculated.
=> [RELEASE ONLY] [search] Commented out the relaxed parsing for streets.

routing_common/vehicle_model.cpp, routing_common/vehicle_model.hpp
cherry-pick https://github.com/mapsme/omim/pull/7740 на release-80
=> [RELEASE ONLY] Fix additional road types pass through

generator/transit_generator.cpp
cherry-pick https://github.com/mapsme/omim/pull/7759 to master.
@darina PTAL
=> Taking into account cases when a stop is present as a relation.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java, android/src/com/mapswithme/maps/gallery/Holders.java, android/src/com/mapswithme/maps/gallery/ItemSelectedListener.java, android/src/com/mapswithme/maps/gallery/impl/BaseItemSelectedListener.java, android/src/com/mapswithme/maps/gallery/impl/Factory.java, android/src/com/mapswithme/maps/gallery/impl/ViatorOfflineAdapterStrategy.java, android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java, android/src/com/mapswithme/util/Utils.java, android/src/com/mapswithme/util/statistics/Destination.java, android/src/com/mapswithme/util/statistics/GalleryPlacement.java, android/src/com/mapswithme/util/statistics/GalleryState.java, android/src/com/mapswithme/util/statistics/GalleryType.java, android/src/com/mapswithme/util/statistics/PlacePageTracker.java, android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-5972
=> Mapsme 5972 discovery statistics

routing/index_router.cpp
cherry-pick https://github.com/mapsme/omim/pull/7708 на релиз
=> [RELEASE ONLY] Remove twin segments duplication from route.

android/src/com/mapswithme/maps/routing/RoutingBottomMenuController.java
https://jira.mail.ru/browse/MAPSME-6134
=> [android] Added hiding the transit panel when route is being built

android/src/com/mapswithme/maps/routing/RoutingController.java
https://jira.mail.ru/browse/MAPSME-5680
=> [android] Added saving the rout on start click

routing/routing_consistency_tests/CMakeLists.txt, routing/routing_consistency_tests/routing_consistency_tests.pro, routing/routing_integration_tests/CMakeLists.txt, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/routing_integration_tests.pro, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/turn_test.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
cherry-pick починки интеграционных тестов на релиз
https://github.com/mapsme/omim/pull/7746
чтобы собранные из релизной ветки карты лучше тестировались
=> [RELEASE ONLY] Fix routing integration tests

routing/cross_mwm_index_graph.hpp
У пользователей будут возникать ситуации, когда mwm-ка с секциями transit_cross_mwm соседствует с mwm, которая данной секции не содержат. Например, mwm датированые ноябрем 2017 и более ранние не содержат transit_cross_mwm. В этом случае, сегменты близнецы для transit получены быть не должны. С другой стороны, поведение, для автомобильного кросс mwm-го роутинга должно быть сохранено.
@tatiana-kondakova @ygorshenin @alexzatsepin PTAL
=> Transit routing in case of neighboring mwm without transit section.

android/src/com/mapswithme/maps/search/SearchFilterController.java, android/src/com/mapswithme/maps/search/SearchFragment.java
https://jira.mail.ru/browse/MAPSME-6006
=> [android] Added resetting the hotel filter when search result is clicked

map/framework.cpp, map/place_page_info.hpp
не мержить до отмашки от @burivuh
=> [DNM][cian] extended preview is disabled

routing/transit_world_graph.hpp
Increase time on foot for transit routing.
=> [RELEASE ONLY] Adjust transit pedestrian restrictions

routing/transit_world_graph.hpp
cherry-pick 
https://github.com/mapsme/omim/pull/7798
на мастер
=> Adjust transit pedestrian restrictions

data/countries.txt, data/external_resources.txt
=> [planet] Fresh data from 8.12.2017 (→release)

openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.cpp, openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.hpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_mode.cpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_mode.hpp
=> [OpenLR-tool] Mark matched path as golden.

data/categories.txt
Исправил одну ошибку в файле и добавил Рождества.
=> [strings] Update sponsored-holiday description

routing/world_graph.hpp
Фикс крупной утечки памяти при прокладке маршрута.
https://jira.mail.ru/browse/MAPSME-5992
Прошу оч оперативно посмотреть. Это к релизу.
@tatiana-kondakova @ygorshenin
=> Routing memory leak.

ugc/loader.cpp, ugc/loader.hpp
https://jira.mail.ru/browse/MAPSME-6224
=> [ugc] loader crash fix

map/booking_filter.cpp
for https://github.com/mapsme/omim/pull/7823
=> [cherry-pick][booking] race on availability cache fix.

openlr/router.cpp, routing/road_graph.cpp, routing/road_graph.hpp, routing/routing_tests/index_graph_test.cpp
=> [routing] Make fake edges that are part of real remember their real analog.

android/src/com/mapswithme/util/Utils.java
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5a358b958cb3c2fa6309595f?time=last-seven-days
=> [android] Added exception handling during url open

editor/user_stats.cpp, local_ads/local_ads_tests/statistics_tests.cpp, local_ads/statistics.cpp, local_ads/statistics.hpp, map/framework.cpp, map/local_ads_manager.cpp, map/local_ads_manager.hpp, platform/platform.hpp
https://jira.mail.ru/browse/MAPSME-6381
=> [local_ads][user] reduced number of threads

search/geocoder.cpp, search/search_integration_tests/processor_test.cpp
cherry-pick from release
to make the search stats less skewed when working on other features
=> [search] Commented out the relaxed parsing for streets.

search/geocoder.cpp, search/model.hpp, search/pre_ranking_info.hpp, search/ranker.cpp, search/ranking_info.cpp, search/ranking_utils.hpp, search/search_integration_tests/processor_test.cpp
We decided to take into account number of typos made in the city part of an address.
=> [search] Count errors in the city part.

base/math.hpp, openlr/CMakeLists.txt, openlr/candidate_points_getter.cpp, openlr/candidate_points_getter.hpp, openlr/graph.cpp, openlr/graph.hpp, openlr/helpers.hpp, openlr/openlr.pro, openlr/openlr_decoder.cpp, openlr/openlr_decoder.hpp, openlr/openlr_stat/openlr_stat.cpp, openlr/stats.hpp, routing/features_road_graph.cpp, routing/features_road_graph.hpp, routing/road_graph.cpp, routing/road_graph.hpp, xcode/openlr/openlr.xcodeproj/project.pbxproj
В helprs.hpp есть некоторые методы, которые нужны более поздним частям кода.
=> Openlr tool pr

routing/cross_mwm_connector.hpp, routing/cross_mwm_graph.cpp, routing/cross_mwm_graph.hpp, routing/cross_mwm_index_graph.hpp, routing/cross_mwm_osrm_graph.hpp, routing/fake_edges_container.hpp, routing/fake_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_tests/cross_mwm_connector_test.cpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, routing/world_graph.cpp, routing/world_graph.hpp
черри-пик починки крешей в AStar в обратной волне на релиз
состоит из 
https://github.com/mapsme/omim/pull/7794
и первого коммита
https://github.com/mapsme/omim/pull/7856
=> Cherry-pick AStar crash fix to release

map/routing_manager.cpp
Сейчас возможен сценарий, при котором восстанавливается маршрут с использованием общественного транспорта. В этом случае до восстановления маршрута необходимо сначала дождаться результата с размерами иконок общественного транспорта от drape.
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/5a3b3b4a8cb3c2fa635670ed
=> Fixed crash in transit route recovering.

drape_frontend/user_mark_shapes.cpp
Cherry pick https://github.com/mapsme/omim/pull/7886
https://jira.mail.ru/browse/MAPSME-6431
=> [RELEASE ONLY] Fixed crash in user marks caching.

map/routing_manager.cpp
Cherry pick https://github.com/mapsme/omim/pull/7888
https://jira.mail.ru/browse/MAPSME-6430
=> [RELEASE ONLY] Fixed crash in transit route recovering.

tools/unix/generate_planet.sh
=> [generator] Fix unbound OSC error

drape_frontend/frontend_renderer.cpp
CHERRY PICK https://github.com/mapsme/omim/pull/7900
=> Fixed crash in GetBgColor

indexer/editable_map_object.cpp, indexer/indexer_tests/editable_map_object_test.cpp
https://jira.mail.ru/browse/MAPSME-6455
https://github.com/mapsme/omim/issues/7903
=> [editor] names validation fix

map/framework.cpp, map/framework.hpp
https://jira.mail.ru/browse/MAPSME-6449
=> Fixed crash on application exit

map/routing_manager.cpp
https://jira.mail.ru/browse/MAPSME-6450
=> Fixed crash on load route points

openlr/CMakeLists.txt, openlr/candidate_paths_getter.cpp, openlr/candidate_paths_getter.hpp, openlr/helpers.cpp, openlr/helpers.hpp, openlr/router.cpp, openlr/router.hpp
=> [OpenLR] Add CandidatePathsGetter.

data/countries.txt, data/external_resources.txt
Файл `WorldCoasts.mwm`здесь используется старый, потому что новый собрался с ошибками. При этом все остальные файлы нормальные, и используют свежую береговую линию.
=> [planet] Data from 10.01.2018, without new coastlines

drape_frontend/user_event_stream.cpp
https://jira.mail.ru/browse/MAPSME-6280
=> Fixed invalid long duration of animations.

drape_frontend/user_event_stream.cpp
Cherry pick https://github.com/mapsme/omim/pull/7937
=> [RELEASE ONLY] Fixed invalid long duration of animations.
