- map/CMakeLists.txt
- map/bookmarks_search_params.hpp
- map/map_tests/search_api_tests.cpp
- map/search_api.cpp
- map/search_api.hpp
- search/CMakeLists.txt
- search/base/mem_search_index.hpp
- search/bookmarks/processor.cpp
- search/bookmarks/processor.hpp
- search/bookmarks/results.hpp
- search/bookmarks/types.hpp
- search/emitter.hpp
- search/mode.cpp
- search/mode.hpp
- search/processor.cpp
- search/processor.hpp
- search/query_params.hpp
- search/result.cpp
- search/result.hpp
- search/search_params.hpp
- search/search_tests/bookmarks_processor_tests.cpp
- search/search_tests/mem_search_index_tests.cpp
- search/search_tests_support/test_search_request.cpp
@rokuz, feel free to review only SearchAPI.
> [search] BookmarksProcessor is integrated in Processor.

- android/jni/CMakeLists.txt
- android/jni/com/mapswithme/util/Language.cpp
- android/src/com/mapswithme/maps/ads/MopubNativeDownloader.java
- android/src/com/mapswithme/util/Language.java
https://jira.mail.ru/browse/MAPSME-6525
> [android] Added passing user lang as key word in Mopub request

- data/external_resources.txt
А вот и береговая линия подоспела. Оказалось, без неё нельзя.
> [planet] Update WorldCoasts.mwm → relese-80

- data/external_resources.txt
Черри пик с одной релизной ветки на другую.
> [planet] Update WorldCoasts.mwm → release-806

- drape_frontend/frontend_renderer.cpp
- drape_frontend/frontend_renderer.hpp
- drape_frontend/my_position_controller.cpp
- drape_frontend/my_position_controller.hpp
- drape_frontend/user_event_stream.cpp
- drape_frontend/user_event_stream.hpp
https://jira.mail.ru/browse/MAPSME-6321
> Fixed positioning of the arrow after starting of route following.

- data/mapcss-mapping.csv
- data/types.txt
> [types] Add leisure=resort

- CMakeLists.txt
@ygorshenin @mpimenov @greshilov  PTAL
> Fixing warnings in 3party lib.

- map/discovery/discovery_manager.cpp
- map/discovery/discovery_manager.hpp
> [mock] Hotels in discovery manager.

- drape_frontend/CMakeLists.txt
- drape_frontend/user_marks_global.hpp
- drape_frontend/user_marks_provider.hpp
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/bookmarks_search_params.hpp
- map/framework.cpp
- map/framework.hpp
- map/search_api.hpp
- map/user_mark_container.cpp
- map/user_mark_container.hpp
- xcode/drape_frontend/drape_frontend.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-6497
> Getting a bookmark by id.

- android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-6581
> [android] Fixed restoring route behaviour during screen rotation

- android/jni/com/mapswithme/maps/SearchEngine.cpp
- android/jni/com/mapswithme/maps/SearchEngine.hpp
- android/jni/com/mapswithme/maps/discovery/DiscoveryManager.cpp
- iphone/Maps/Core/Search/MWMSearch.h
- iphone/Maps/Core/Search/MWMSearch.mm
- iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.h
- iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
- iphone/Maps/UI/Search/TableView/MWMSearchTableViewController.mm
- map/everywhere_search_params.hpp
- map/framework.cpp
- map/framework.hpp
- map/search_api.cpp
- map/search_api.hpp
- qt/search_panel.cpp
- search/everywhere_search_callback.cpp
- search/everywhere_search_callback.hpp
- search/intermediate_result.cpp
- ugc/api.cpp
- ugc/api.hpp
- ugc/loader.cpp
- ugc/loader.hpp
https://jira.mail.ru/browse/MAPSME-6544
> [search][ugc] UGC ratings in search

- data/categories.txt
массаж-спа
спа-массаж
спассаж
забейте, просто помёржите
не смотрите вовнутрь
там спа
> [types] Add synonyms to shop=massage

- editor/feature_matcher.cpp
- editor/feature_matcher.hpp
- indexer/edits_migration.cpp
https://jira.mail.ru/browse/MAPSME-6593
> [editor] Support migration for old versions of edits.

- routing/async_router.cpp
Fixing some grammar mistakes according to comments in merge PR https://github.com/mapsme/omim/pull/7985/
@mpimenov PTAL
> Grammar fixing

- data/countries.txt
- data/external_resources.txt
> [planet] Fresh data from 26.01.2018

- android/res/drawable-v21/bg_tag_normal.xml
- android/res/drawable-v21/bg_tag_normal_night.xml
- android/res/drawable-v21/button_with_border.xml
- android/res/drawable-v21/button_with_border_night.xml
- android/res/drawable/bg_tag_normal.xml
- android/res/drawable/bg_tag_normal_night.xml
- android/res/drawable/button_with_border.xml
- android/res/drawable/button_with_border_night.xml
- android/res/layout/fragment_search_filter.xml
- android/res/layout/item_tag.xml
- android/res/layout/price_filter.xml
- android/res/layout/rating_filter.xml
- android/res/values/dimens.xml
- android/res/values/styles-text.xml
- android/res/values/themes-attrs.xml
- android/res/values/themes-base.xml
- android/src/com/mapswithme/maps/search/PriceFilterView.java
- android/src/com/mapswithme/maps/search/RatingFilterView.java
https://jira.mail.ru/browse/MAPSME-5819
> [android] Refactored filter UI

- data/countries.txt
- data/external_resources.txt
Переделал #8019 на мастер. Не черри-пик, потому что там была совсем старая версия.
> [planet] Fresh data from 26.01.2018, to master

- generator/road_access_generator.cpp
фикс промежуточного cvs для road access, собрала карты, проверила что работает
> [routing]Fix intermediate road access csv file format

- base/url_helpers.cpp
- map/framework.cpp
- map/framework.hpp
- map/search_api.cpp
- partners_api/booking_api.cpp
- partners_api/booking_api.hpp
https://jira.mail.ru/browse/MAPSME-6543
https://jira.mail.ru/browse/MAPSME-6501
> [booking] Availability params are injected into sponsored URL

- drape_frontend/frontend_renderer.cpp
https://github.com/mapsme/omim/pull/8033
> [Cherry] Fixed infinite memory consumption on start in iOS 10.2

- android/jni/CMakeLists.txt
- android/jni/com/mapswithme/platform/HttpUploader.cpp
- platform/CMakeLists.txt
- platform/http_uploader.hpp
- platform/http_uploader_apple.mm
- platform/http_uploader_dummy.cpp
- xcode/platform/platform.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-6702
Посмотрите пожалуйста, вы этого ожидали?
> [platform] http uploader dummy interface.

- android/jni/com/mapswithme/maps/SearchEngine.cpp
- android/res/layout/fragment_search_filter.xml
- android/res/values/styles-text.xml
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/search/BookingFilterParams.java
- android/src/com/mapswithme/maps/search/FilterActivity.java
- android/src/com/mapswithme/maps/search/FilterFragment.java
- android/src/com/mapswithme/maps/search/HotelsFilterHolder.java
- android/src/com/mapswithme/maps/search/SearchActivity.java
- android/src/com/mapswithme/maps/search/SearchFilterController.java
- android/src/com/mapswithme/maps/search/SearchFragment.java
https://jira.mail.ru/browse/MAPSME-5819
Реализовал фильтрацию по датам. Осталось подкраску в списке, возможно в другом реквесте буду делать, возможно и в этот накину, если успею.
> Mapsme 5819 date filtration

- defines.hpp
- generator/generator_tests/check_mwms.cpp
- indexer/CMakeLists.txt
- indexer/cell_value_pair.hpp
- indexer/data_factory.hpp
- indexer/displacement_manager.hpp
- indexer/feature_covering.cpp
- indexer/feature_covering.hpp
- indexer/feature_loader.cpp
- indexer/geometry_serialization.hpp
- indexer/index.hpp
- indexer/indexer_tests/interval_index_test.cpp
- indexer/indexer_tests/sort_and_merge_intervals_test.cpp
- indexer/interval_index.hpp
- indexer/interval_index_builder.hpp
- indexer/locality_index_builder.cpp
- indexer/locality_index_builder.hpp
- indexer/locality_object.cpp
- indexer/locality_object.hpp
- indexer/scale_index.hpp
- indexer/scale_index_builder.hpp
- search/mwm_context.cpp
- search/mwm_context.hpp
- search/retrieval.cpp
- xcode/indexer/indexer.xcodeproj/project.pbxproj
В этом PR:
- обобщение типа значения, хранящегося в геоиндексе до любого целочисленного типа, помещающегося в int64_t
- построение геоиндекса по файлу с данными о loaclity id и геометрии объектов для геокодера
Код для генерации предварительных данных и код с API LocalityIndex будут в отдельных PR.
> [geocoder] Add LocalityIndexBuilder

- storage/storage.cpp
- storage/storage.hpp
- storage/storage_defines.cpp
- storage/storage_defines.hpp
> Added applying status to nodes.

- drape_frontend/frontend_renderer.cpp
- drape_frontend/user_event_stream.hpp
https://jira.mail.ru/browse/MAPSME-6717
> Fixed crash with follow and rotate event.

- android/res/layout/item_discovery_expert.xml
- android/res/layout/item_discovery_hotel_product.xml
- android/res/layout/item_discovery_search.xml
- android/res/layout/item_search_more.xml
- android/res/layout/item_viator_product.xml
- android/res/values/dimens.xml
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/discovery/DiscoveryActivity.java
- android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
- android/src/com/mapswithme/maps/gallery/Holders.java
- android/src/com/mapswithme/maps/gallery/Items.java
- android/src/com/mapswithme/maps/gallery/impl/HotelAdapterStrategy.java
- android/src/com/mapswithme/maps/gallery/impl/LocalExpertsAdapterStrategy.java
- android/src/com/mapswithme/maps/gallery/impl/ViatorAdapterStrategy.java
- android/src/com/mapswithme/maps/search/SearchResult.java
https://jira.mail.ru/browse/MAPSME-6542
> Mapsme 6542 booking more filter

- xcode/indexer/indexer.xcodeproj/project.pbxproj
Удаление удалённого файла из xcode
> Remove interval_index_iface.hpp from Xcode project

- iphone/Maps/Core/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-6539
> [iOS] Fixed route restoring

- data/categories.txt
По просьбе Ксюши добавляю слово «парикмахерская» в синонимы салону красоты. Двух языков достаточно.
> [strings] Added hairdresser as a beauty salon synonim

- android/jni/com/mapswithme/platform/HttpUploader.cpp
- android/src/com/mapswithme/util/HttpClient.java
- android/src/com/mapswithme/util/HttpUploader.java
- android/src/com/mapswithme/util/KeyValue.java
- android/src/com/mapswithme/util/StorageUtils.java
- android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-6704
> [android] Implemented http file uploader

- configure.sh
Мастер не собирается без приватного репозитория, а никому и дела нет.
Fixes #8075.
> [settings] Add empty cloud URL to configure.sh

- drape_frontend/stylist.cpp
https://jira.mail.ru/browse/MAPSME-5642
> Use depth layer from OSM only for lines

- data/mixed_nodes.txt
- defines.hpp
- generator/CMakeLists.txt
- generator/generator_tests/CMakeLists.txt
- generator/generator_tests/node_mixer_test.cpp
- generator/node_mixer.cpp
- generator/node_mixer.hpp
- generator/osm_source.cpp
- xcode/generator/generator.xcodeproj/project.pbxproj
Доселе фейковые точки — ёлочки на Новый год, артефакты для Тора — я добавлял непосредственно в файл планеты перед сборкой. Это долго и чревато ошибками: помните, как мы вынесли ёлку только в конце января? Здесь я дописал код, который читает файл `data/mixed_nodes.txt` и добавляет объекты с указанными координатами и тегами.
В качестве примера добавлен файл точек для LuggageHero.
>  [generator] Support mixing nodes to the planet 

- android/src/com/mapswithme/maps/bookmarks/data/BookmarkBackupController.java
- android/src/com/mapswithme/maps/search/FilterFragment.java
- android/src/com/mapswithme/maps/ugc/UGCController.java
- android/src/com/mapswithme/maps/ugc/UGCReviewAdapter.java
- android/src/com/mapswithme/util/DateUtils.java
https://jira.mail.ru/browse/MAPSME-6857
> [android] Replaced custom date formatter with system one

- android/AndroidManifest.xml
https://jira.mail.ru/browse/MAPSME-6857
> [android] Added 'https' scheme for ge0 links

- data/countries.txt
- data/external_resources.txt
> [planet] Fresh data from 9.02.2018

- android/src/com/mapswithme/maps/search/SearchFragment.java
- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
https://jira.mail.ru/browse/MAPSME-6854
> [android] Simplified enable logging feature

- drape/CMakeLists.txt
- drape/font_texture.cpp
- drape/font_texture.hpp
- drape/glyph_generator.cpp
- drape/glyph_generator.hpp
- drape/texture.hpp
- drape/texture_manager.cpp
- drape/texture_manager.hpp
- drape_frontend/drape_engine.cpp
- drape_frontend/drape_engine.hpp
- xcode/drape/drape.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-6855
> Extracted glyph generator from font textures

- search/search_integration_tests/downloader_search_test.cpp
- storage/CMakeLists.txt
- storage/http_map_files_downloader.cpp
- storage/http_map_files_downloader.hpp
- storage/map_files_downloader.hpp
- storage/pinger.cpp
- storage/pinger.hpp
- storage/storage.cpp
- storage/storage.hpp
- storage/storage_tests/fake_map_files_downloader.cpp
- storage/storage_tests/fake_map_files_downloader.hpp
- storage/storage_tests/storage_tests.cpp
- storage/storage_tests/test_map_files_downloader.cpp
- storage/storage_tests/test_map_files_downloader.hpp
- xcode/storage/storage.xcodeproj/project.pbxproj
Notice that the following tests are broken now: ```StorageTest_FailedDownloading,
StorageTest_ObsoleteMapsRemoval```
Also, no tests provided for a new functionality. Probably will add some in next prs.
> Ping downloading urls

- map/framework.cpp
- map/user.cpp
- map/user.hpp
- ugc/api.cpp
- ugc/api.hpp
- ugc/storage.cpp
- ugc/storage.hpp
- ugc/ugc_tests/storage_tests.cpp
https://jira.mail.ru/browse/MAPSME-6861
> Added new UGC statistics

- android/jni/com/mapswithme/maps/Framework.cpp
- android/res/layout/item_bookmark_backup.xml
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/auth/AuthorizationListener.java
- android/src/com/mapswithme/maps/auth/Authorizer.java
- android/src/com/mapswithme/maps/auth/BaseMwmAuthorizationFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkBackupController.java
- android/src/com/mapswithme/maps/search/FilterFragment.java
- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
- android/src/com/mapswithme/maps/ugc/UGCController.java
- android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
- android/src/com/mapswithme/maps/ugc/UGCReviewAdapter.java
- android/src/com/mapswithme/maps/widget/BookmarkBackupView.java
- android/src/com/mapswithme/util/DateUtils.java
- map/user.cpp
Что осталось:
1. Прогресс диалог, пока идет авторизация в наш паспорт.
2. Статистику
Оставшиеся доработки появятся либо здесь, либо в новом PR
> [android] Connected bookmark UI with core

- partners_api/yandex_api.cpp
https://jira.mail.ru/browse/MAPSME-6867
> [yandex taxi] price fix

- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/auth/Authorizer.java
- android/src/com/mapswithme/maps/auth/Constants.java
- android/src/com/mapswithme/maps/auth/SocialAuthDialogFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkBackupController.java
- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
- android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-6731
Bookmarks backup statistics and refactored authorization code
> Mapsme 6731 bookmark cloud statistics and fixes

- android/res/values/donottranslate.xml
- map/cloud.cpp
- map/user.cpp
Этот реквест должен быть откатан после появления боевого сервера для облака
> [android] Added stage  urls and facebook for testing bookmarks

- android/jni/com/mapswithme/maps/MwmApplication.cpp
- android/jni/com/mapswithme/platform/Platform.cpp
- android/jni/com/mapswithme/platform/Platform.hpp
- android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/util/StorageUtils.java
- android/src/com/mapswithme/util/sharing/SharingHelper.java
- platform/platform.hpp
- platform/platform_ios.mm
https://jira.mail.ru/browse/MAPSME-6498
IOS:
/Users/a.milchakov/Library/Developer/CoreSimulator/Devices/9A58F4C5-315F-43FF-B728-0CB602D8C0D5/data/Containers/Data/Application/AC893D4D-32FE-44E7-BB82-DD40531BAB84/Library/Application Support/
Android:
/storage/emulated/0/Android/data/com.mapswithme.maps.pro.debug/files
> [platform][ios][android] private dir

- platform/marketing_service.cpp
- platform/marketing_service.hpp
- storage/country.cpp
- storage/storage.cpp
https://jira.mail.ru/browse/MAPSME-6891
> Added min and max mwm version to PW

- indexer/feature_utils.cpp
- indexer/indexer_tests/feature_names_test.cpp
https://jira.mail.ru/browse/MAPSME-6600
> [indexer] similar languages changes.

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/search/SearchActivity.java
- android/src/com/mapswithme/maps/search/SearchFilterController.java
- android/src/com/mapswithme/maps/search/SearchFragment.java
https://jira.mail.ru/browse/MAPSME-6866
> [android] Fixed passing booking filter params across screens

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/search/SearchFilterController.java
https://jira.mail.ru/browse/MAPSME-6868
> [android] Fixed filter reset while pressing back button

- iphone/Maps/Maps.xcodeproj/project.pbxproj
AdHoc configuration was replaced with 'Release' here:
https://github.com/mapsme/omim/pull/7571
> [ios] Fix crashlytics for iOS beta builds

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
https://jira.mail.ru/browse/MAPSME-6947
> [android] Fixed crash on bookmark deletion.

- android/jni/com/mapswithme/maps/Framework.cpp
- android/res/xml/prefs_main.xml
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
https://jira.mail.ru/browse/MAPSME-6597
> [android] Removed simplfied color scheme for traffic

- configure.sh
- partners_api/CMakeLists.txt
- partners_api/maxim_api.cpp
- partners_api/maxim_api.hpp
- partners_api/partners_api_tests/CMakeLists.txt
- partners_api/partners_api_tests/maxim_tests.cpp
- partners_api/partners_api_tests/taxi_engine_tests.cpp
- partners_api/taxi_engine.cpp
- partners_api/taxi_places.hpp
- partners_api/taxi_provider.hpp
- partners_api/yandex_api.cpp
- tools/python/ResponseProvider.py
- tools/python/jsons.py
https://jira.mail.ru/browse/MAPSME-6916
> [partners-api] maxim api core

- android/jni/com/mapswithme/maps/SearchEngine.cpp
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/search/FloatingSearchToolbarController.java
- android/src/com/mapswithme/maps/search/SearchEngine.java
- android/src/com/mapswithme/maps/search/SearchFragment.java
- partners_api/booking_api.cpp
https://jira.mail.ru/browse/MAPSME-6736
https://jira.mail.ru/browse/MAPSME-6868
https://jira.mail.ru/browse/MAPSME-6956
1. На экране поиска и на карте перед выполнением поискового запроса добавил отмену всех существующих вопросов, если такие имеются. Обсудив с @mpimenov , понял, что ничего страшного из-за этого случится не должно.
2. Чтобы отменять запрос **перед** выполнением нового пришлось убрать дополнительное откладывание задачи отмены поиска в UI очередь (Framwork.cpp строчки 596, 605, 614), добавленное @rokuz . Если в нем был глубокий смысл, то расскажите.
> Mapsme 6736 6868 hotel filtration fixes

- android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
https://jira.mail.ru/browse/MAPSME-6940
> [android] Autoupdate fix

- android/res/drawable-v21/button_partner1.xml
https://jira.mail.ru/browse/MAPSME-6729
> [android] Fixed megabonus button selector

- 3party/jansson/myjansson.cpp
- 3party/jansson/myjansson.hpp
- partners_api/booking_api.cpp
https://jira.mail.ru/browse/MAPSME-6967
> [booking] photo ids as integers fix

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- drape_frontend/drape_engine.cpp
- drape_frontend/user_marks_provider.hpp
- map/bookmark.cpp
- map/bookmark.hpp
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/user_mark_layer.cpp
- map/user_mark_layer.hpp
https://jira.mail.ru/browse/MAPSME-6963
https://jira.mail.ru/browse/MAPSME-6974
> Fixed processing of category deletion.

- indexer/interval_index.hpp
> Fix signed unsigned mismatch warning

- android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/routing/SearchWheel.java
- android/src/com/mapswithme/maps/search/FloatingSearchToolbarController.java
- android/src/com/mapswithme/maps/search/SearchEngine.java
- android/src/com/mapswithme/maps/search/SearchFragment.java
[android] Refactored SearchEngine java class
> [android] Added search cancel before 'ShowOnMap' button is clicked

- routing/routing_integration_tests/turn_test.cpp
- routing/turns_generator.cpp
1. Добавил несколько интеграционных тестов на генерацию съездов в крупных дорог;
2. Убрал не используемый теперь метод и warning;
@tatiana-kondakova @mpimenov PTAL
> [routing][turns] Tests on exit from highway implementation.

- storage/storage.cpp
Fix build bug in release branch.
> [gcc] Fix GCC-6 build bug

- drape_frontend/backend_renderer.cpp
- drape_frontend/read_manager.cpp
https://jira.mail.ru/browse/MAPSME-6978
> Fixed user marks generation assignment.

- coding/serdes_json.hpp
- map/cloud.cpp
- map/cloud.hpp
Не мержить, пока Тимофей не раскатит сервер.
Изменена логика согласно новому видению сервера https://confluence.mail.ru/display/MAPSME/Bookmarks+Cloud#BookmarksCloud-Server-sideAPI
> Changed cloud interface

- android/res/values/donottranslate.xml
- map/cloud.cpp
- map/user.cpp
This reverts commit 9bea3a82f5e06a688e74587ba7df6e2c3e079229.
https://jira.mail.ru/browse/MAPSME-6990
> Revert "[android] Added stage  urls and facebook for testing bookmarks"

- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/routing_manager.cpp
- map/transit/transit_display.cpp
https://jira.mail.ru/browse/MAPSME-7002
>  Fixed data race with bookmarks in InsertRoute.

- indexer/osm_editor.hpp
- local_ads/statistics.cpp
- map/local_ads_manager.cpp
https://jira.mail.ru/browse/MAPSME-7006
> Local ads timeout

- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-7013
> [android] Fixed website field showing in PP

- strings.txt
> [strings] Add Persian to strings.txt file

- android/src/com/mapswithme/maps/routing/ResultCodesHelper.java
- iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm
https://jira.mail.ru/browse/MAPSME-7017
https://confluence.mail.ru/display/MAPSME/Rewrite+error+messages
> Fixed transport navigation messages

- android/res/layout/fragment_search_filter.xml
- android/src/com/mapswithme/maps/search/SearchAdapter.java
https://jira.mail.ru/browse/MAPSME-6975
> Mapsme 6975 search filter layout fixes

- android/src/com/mapswithme/maps/routing/ResultCodesHelper.java
- iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm
https://github.com/mapsme/omim/pull/8237
> [CHERRY] Fixed transport navigation messages

- android/jni/com/mapswithme/maps/MapManager.cpp
- android/src/com/mapswithme/maps/downloader/CountryItem.java
- android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
https://jira.mail.ru/browse/MAPSME-7015
> [android] autoupdate total size fix

- android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
https://jira.mail.ru/browse/MAPSME-6994
> [android] Fixed hotels loading indiscovery in offline

- local_ads/CMakeLists.txt
- local_ads/statistics.cpp
- local_ads/statistics.hpp
- map/local_ads_manager.cpp
- map/local_ads_manager.hpp
- xcode/local_ads/local_ads.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-7008
> Multithreaded local ads and stats

- android/src/com/mapswithme/maps/discovery/ItemType.java
https://jira.mail.ru/browse/MAPSME-6988
https://jira.mail.ru/browse/MAPSME-6992
> [android] Fixed discovery 404 error showing

- drape_frontend/read_manager.cpp
https://github.com/mapsme/omim/pull/8260
> CHERRY Fixed crash in read manager

- local_ads/local_ads_tests/CMakeLists.txt
@tatiana-kondakova @rokuz PTAL
> local_ads_tests build bug fix.

- base/buffer_vector.hpp
DNM до JTTP, чтобы убедиться что проблема единственная
> Linux build fix, misprint

- android/jni/com/mapswithme/platform/Platform.cpp
- android/jni/com/mapswithme/util/NetworkPolicy.cpp
- android/jni/com/mapswithme/util/NetworkPolicy.hpp
- android/src/com/mapswithme/util/NetworkPolicy.java
- iphone/Maps/Core/NetworkPolicy/MWMNetworkPolicy.h
- iphone/Maps/Core/NetworkPolicy/MWMNetworkPolicy.mm
- local_ads/statistics.cpp
- map/cloud.cpp
- platform/CMakeLists.txt
- platform/network_policy.hpp
- platform/network_policy_dummy.cpp
- platform/network_policy_ios.h
- platform/network_policy_ios.mm
- xcode/platform/platform.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-6775
> Added support of 3G awareness in core platform

- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-7050
> [android] Fixed website visibility in PP

- coding/internal/xmlparser.hpp
- map/api_mark_point.cpp
- map/bookmark.cpp
https://github.com/mapsme/omim/pull/8291
> [CHERRY-PICK] Removed warnings

- map/transit/transit_display.cpp
https://jira.mail.ru/browse/MAPSME-7071
> Fixed rendering of transit transfer.

- map/routing_manager.cpp
- map/transit/transit_display.cpp
- map/transit/transit_display.hpp
Cherry pick https://github.com/mapsme/omim/pull/8302
> Fixed crash on transit marks creating.

- iphone/Maps/Bookmarks/Categories/Actions/BMCActionsCreateCell.swift
- iphone/Maps/Bookmarks/Categories/Actions/BMCActionsCreateCell.xib
- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.xib
- iphone/Maps/Bookmarks/Categories/Categories/BMCCategoryCell.swift
- iphone/Maps/Bookmarks/Categories/Notifications/BMCNotificationsCell.swift
> [ios] Fixed bookmarks UI in night mode

- iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm
> [ios] Clear routing map search.

- feature_list/feature_list.cpp
В прошлом пул-реквесте добавил `GetWikiURL()` в вопиюще неправильное место.
> [feature_list] Fix error with wikipedia url

- indexer/feature_data.cpp
> [indexer] Pull back entrance type →master

- android/jni/com/mapswithme/maps/SearchEngine.cpp
- android/src/com/mapswithme/maps/search/SearchEngine.java
- map/framework.cpp
- map/framework.hpp
В ядре до SearchApi все было прокинуто, поэтому оставалось только в jni чуть кода дописать.
https://jira.mail.ru/browse/MAPSME-7033
> [jni] search in bookmarks

- indexer/cell_coverer.hpp
- indexer/cell_id.hpp
- indexer/feature_covering.hpp
- indexer/indexer_tests/CMakeLists.txt
- indexer/indexer_tests/bounds.hpp
- indexer/indexer_tests/cell_coverer_test.cpp
- indexer/indexer_tests/cell_id_test.cpp
- indexer/indexer_tests/locality_index_test.cpp
- indexer/locality_index.hpp
- xcode/indexer/indexer.xcodeproj/project.pbxproj
Добавила в CellCoverer режим, в котором интервалы выдаются в порядке увеличения расстояния от центра и соответствующий режим в CoveringGetter и LocalityIndex.
У этого PR приоритет ниже чем у https://github.com/mapsme/omim/pull/8093 (лучше смотреть сначала https://github.com/mapsme/omim/pull/8093).
> [geocoder]Add geo ranking

- android/res/drawable/list_divider_night.xml
- android/res/values/dimens.xml
- android/res/values/themes-base.xml
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/widget/recycler/ItemDecoratorFactory.java
https://jira.mail.ru/browse/MAPSME-7038
> [android] Added vertical divider to bookmark category list

- android/res/layout/fragment_updater.xml
- android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
https://jira.mail.ru/browse/MAPSME-6911
> [android] Cancel button on autoupdate screen.

- android/res/layout/fragment_updater.xml
- android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
https://github.com/mapsme/omim/pull/8333
> [cherry-pick][android] Cancel button on autoupdate screen.

- data/countries.txt
- data/external_resources.txt
Это СНОВА ТА ЖЕ ПЛАНЕТА, ну что за развод.
> [planet] Data from 16.03.2018 → r8.1

- data/countries.txt
- data/external_resources.txt
> [planet] Data from 16.03.2018 → master

- base/internal/message.hpp
- kml/type_utils.hpp
- map/bookmark_manager.cpp
https://jira.mail.ru/browse/MAPSME-7077
> Added bookmarks backup and conversion

- android/res/layout/item_bookmark_backup.xml
https://jira.mail.ru/browse/MAPSME-7038
> [android] Fixed header text style in bookmark backup widget

- android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
https://jira.mail.ru/browse/MAPSME-7182
> [android] Fixed ugc review submition when user is authorized

- android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
https://jira.mail.ru/browse/MAPSME-7182
> [cherry-pick][android] Fixed ugc review submition when user is authorized

- android/src/com/mapswithme/maps/search/SearchAdapter.java
https://jira.mail.ru/browse/MAPSME-7069
> [android] Fixed local ads backgournd in search

- map/bookmark_manager.cpp
Cherry pick https://github.com/mapsme/omim/pull/8374
> Fixed processing of bookmark category removing.

- data/categories.txt
> [strings] Rename Luggage Hero to Luggage Storage → master

- android/res/layout/fragment_updater.xml
- android/res/values/dimens.xml
- android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-7134
> [android] autoupdate layout is updated.

- map/map_tests/CMakeLists.txt
> [cmake] [map] Fixed linking order in map_tests.

- android/res/drawable/bg_ads.xml
- android/res/drawable/bg_ads_action.xml
- android/res/drawable/bg_ads_action_night.xml
- android/res/drawable/bg_ads_night.xml
- android/res/drawable/bg_pp_banner.xml
- android/res/drawable/bg_pp_banner_large_button.xml
- android/res/drawable/bg_pp_banner_large_button_night.xml
- android/res/drawable/bg_pp_banner_night.xml
- android/res/layout/place_page_banner.xml
- android/res/layout/place_page_preview.xml
- android/res/values/colors.xml
- android/res/values/dimens.xml
- android/res/values/themes-attrs.xml
- android/res/values/themes-base.xml
https://jira.mail.ru/browse/MAPSME-6930
> [android] Updated place page banner design

- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/util/statistics/Statistics.java
- iphone/Maps/Common/Statistics/StatisticsStrings.h
- iphone/Maps/UI/Authorization/AuthorizationViewController.swift
- iphone/Maps/UI/Authorization/MWMAuthorizationViewModel.h
- iphone/Maps/UI/Authorization/MWMAuthorizationViewModel.mm
- map/user.cpp
- map/user.hpp
https://jira.mail.ru/browse/MAPSME-6935
> Added core support of login via phone number

- iphone/Maps/Classes/MapsAppDelegate.mm
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/cloud.cpp
- map/cloud.hpp
- platform/http_uploader.hpp
https://jira.mail.ru/browse/MAPSME-6923
> Added cloud restoring

- android/src/com/mapswithme/maps/MwmApplication.java
https://jira.mail.ru/browse/MAPSME-6663
> [android] Extracted MyTracker initialization in application.onCreate()

- map/displayed_categories_modifiers.cpp
- map/displayed_categories_modifiers.hpp
- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-7279
> Added support of FC2018 category in the core

- android/build.gradle
- android/jni/com/mapswithme/platform/Platform.cpp
- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/maps/SplashActivity.java
https://jira.mail.ru/browse/MAPSME-6663
> Mapsme 6663 fix mytracker initialization

- iphone/Maps/Maps.xcodeproj/project.pbxproj
- xcode/omim.xcworkspace/contents.xcworkspacedata
- xcode/open_location_code/open_location_code.xcodeproj/project.pbxproj
- xcode/search/search.xcodeproj/project.pbxproj
Добавил зависимости в xcode для:
https://github.com/mapsme/omim/pull/8426
> [xcode] Fix iOS build for open-location-code

- drape_frontend/user_mark_generator.cpp
- drape_frontend/user_mark_generator.hpp
- drape_frontend/user_mark_shapes.cpp
> Fixed memory corruption in user lines

- iphone/Maps/Categories/UIColor+MapsMeColor.mm
- iphone/Maps/UI/Search/MWMSearchView.xib
> [ios] Fixed crash and wrong banner color.

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- indexer/map_object.cpp
- indexer/map_object.hpp
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- map/bookmark_helpers.cpp
- map/bookmark_helpers.hpp
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
* Сохранение всех переводов имени фичи и типов фичи в BookmarkData.
* Поддержка уникальных имен категорий при загрузке.
* Поиск kml файла внутри kmz после загрузки.
> Bookmarks tasks

- 3party/open-location-code/codearea.cc
> [olc] Fix warning in open location code library

- android/AndroidManifest.xml
- android/build.gradle
- android/flavors/beta/res/values/libnotify.xml
- android/flavors/debug/res/values/libnotify.xml
- android/res/values/libnotify.xml
- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/maps/search/SearchFragment.java
- android/src/com/mapswithme/util/log/LibnotifyLogReceiver.java
- android/src/com/mapswithme/util/log/LoggerFactory.java
- android/src/com/mapswithme/util/push/GCMListenerRouterService.java
- android/src/com/mapswithme/util/push/GcmInstanceIDRouterListenerService.java
- android/src/com/mapswithme/util/statistics/PushwooshHelper.java
https://jira.mail.ru/browse/MAPSME-6925
@texnedo PTAL
> [DNM] [android] Integrated libnotify library

- map/bookmark_manager.hpp
- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-7318
> Fixed showing a bookmark with invalid scale.

- data/mixed_nodes.txt
- data/mixed_tags.txt
Оказалось, точки выдачи паспортов болельщика уже кто-то нарисовал, так что достаточно было проставить им наш тип. Ну и добавил пару магазинов атрибутики в Петербурге.
> [data] Add all fan id points

- android/src/com/mapswithme/util/sharing/SharingHelper.java
- iphone/Maps/Bookmarks/BookmarksVC.mm
- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
https://jira.mail.ru/browse/MAPSME-7242
https://jira.mail.ru/browse/MAPSME-7241
> Fixed sharing bookmarks string usage

- android/res/values/strings.xml
- iphone/Maps/LocalizedStrings/en-GB.lproj/Localizable.strings
- iphone/Maps/LocalizedStrings/en.lproj/Localizable.strings
- strings.txt
> MAPSME-7276

- android/3rd_party/BottomSheet/build.gradle
- android/UnitTests/build.gradle
- android/build.gradle
- android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/KmlImportController.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
https://jira.mail.ru/browse/MAPSME-7326
> Mapsme 7326 fix bookmark import

- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/PPPReview.xib
> [ios] Fixed based on label

- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCViewModel.swift
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.h
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
> [ios] Hide all instead of show all.

- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCViewModel.swift
> [ios] Conversion kml after async load

- search/ranker.cpp
DNM до написания тестов.
При поиске по категориям наблюдалась следующая проблема:
в GetBestMatchName токены из имени фичи не совпадают с токенами ни на одном языке, поэтому выбор происходит по языку. При этом приоритет языков такой:
- язык устройства
- язык ввода
- английский и интернациональный
- язык по умолчанию (`name =`  без указания кода языка).
Поэтому в ситуации, когда нужно на карте России с русской локалью и русским языком ввода найти по категории объект, у которого есть `name:en` и `name`, выдавалось имя `name:en`, т.к. английский язык выше дефолтного в приоритетах, хотя лучше бы выдавалось `name`.
Для решения предлагаю так же как в функциях, которые выбирают на каком языке отображать имя объекта, предполагать что `name` написано на языке mwm. В этом случае при совпадении …
> [search] Ranker::GetBestMatchName: assume default name is in mwm language

- android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
- android/src/com/mapswithme/maps/base/BaseMwmExtraTitleActivity.java
- android/src/com/mapswithme/maps/base/BaseMwmFragmentActivity.java
- android/src/com/mapswithme/maps/base/BaseToolbarActivity.java
- android/src/com/mapswithme/maps/editor/FeatureCategoryActivity.java
- android/src/com/mapswithme/maps/gallery/FullScreenGalleryActivity.java
https://jira.mail.ru/browse/MAPSME-7260
> [android] onCreate fix

- android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
- android/src/com/mapswithme/maps/widget/WheelProgressView.java
https://jira.mail.ru/browse/MAPSME-7112
> [android] pending progress for progress bars

- android/src/com/mapswithme/maps/background/WorkerService.java
https://jira.mail.ru/browse/MAPSME-7338
> [android] Added check core and platform before changes uploading

- docs/INSTALL.md
- docs/MAPS.md
Немного обновил документацию: вырезал упоминания OSRM, обновил параметры вызова `build_omim.sh`.
> [doc] Update building instructions

- iphone/Maps/Common/Statistics/StatisticsStrings.h
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
> [ios] Added user_interrupted

- android/build.gradle
- android/src/com/mapswithme/maps/bookmarks/BookmarkBackupController.java
- android/src/com/mapswithme/maps/bookmarks/ChooseBookmarkCategoryFragment.java
- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-7244
> Mapsme 7244 backup statistic

- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/CategoryValidator.java
- android/src/com/mapswithme/maps/bookmarks/ChooseBookmarkCategoryFragment.java
- android/src/com/mapswithme/maps/dialog/EditTextDialogFragment.java
- android/src/com/mapswithme/maps/editor/Editor.java
- android/src/com/mapswithme/maps/editor/EditorFragment.java
- android/src/com/mapswithme/maps/editor/StreetFragment.java
https://jira.mail.ru/browse/MAPSME-7365
> Mapsme 7365 create edit bookmarks dialog

- generator/routing_index_generator.cpp
- map/routing_manager.cpp
- routing/index_graph.cpp
- routing/index_graph.hpp
- routing/index_graph_loader.cpp
- routing/index_graph_loader.hpp
- routing/routing_integration_tests/routing_test_tools.cpp
- routing/routing_tests/index_graph_test.cpp
- routing/routing_tests/index_graph_tools.cpp
- routing/routing_tests/index_graph_tools.hpp
- routing/single_vehicle_world_graph.cpp
- routing/transit_world_graph.cpp
- routing/world_graph.cpp
- track_analyzing/track_matcher.cpp
cherry-pick https://github.com/mapsme/omim/pull/8543
https://jira.mail.ru/browse/MAPSME-7126
https://jira.mail.ru/browse/MAPSME-7056
https://jira.mail.ru/browse/MAPSME-7127
https://jira.mail.ru/browse/MAPSME-7128
https://jira.mail.ru/browse/MAPSME-7129
https://jira.mail.ru/browse/MAPSME-7302
https://jira.mail.ru/browse/MAPSME-7303
> [release-82] Performance and memory optimization for cross mwm routing.

- indexer/editable_map_object.cpp
https://jira.mail.ru/browse/MAPSME-7152
> [editor] The character '+' is valid for name now

- android/src/com/mapswithme/maps/search/CategoriesAdapter.java
https://jira.mail.ru/browse/MAPSME-6936
> Mapsme 6936 fifa category fix

- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
- android/src/com/mapswithme/util/BottomSheetHelper.java
https://jira.mail.ru/browse/MAPSME-7272
> [android] show/hide delete bookmark

- generator/generator_tests_support/test_feature.cpp
- generator/generator_tests_support/test_feature.hpp
- generator/generator_tests_support/test_mwm_builder.cpp
- generator/generator_tests_support/test_mwm_builder.hpp
- search/keyword_lang_matcher.cpp
- search/keyword_lang_matcher.hpp
- search/ranker.cpp
- search/search_integration_tests/processor_test.cpp
Cherry-pick реквестов https://github.com/mapsme/omim/pull/8487 и https://github.com/mapsme/omim/pull/8528 на мастер и тесты к ним
> [search] Cherry-pick proper feature name selection to master & tests

- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/routing/RoutingController.java
- iphone/Maps/Core/Routing/MWMRouter.mm
- map/routing_manager.cpp
- map/routing_manager.hpp
- qt/draw_widget.cpp
https://jira.mail.ru/browse/MAPSME-7359
> Improved saving route points

- platform/http_uploader_apple.mm
- platform/http_uploader_apple.swift
https://jira.mail.ru/browse/MAPSME-7419
> [iOS] Fixed crash on bookmarks cloud backup

- android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
- android/src/com/mapswithme/maps/widget/WheelProgressView.java
https://jira.mail.ru/browse/MAPSME-7112
> [cherry-pick][android] pending progress for progress bars

- android/jni/com/mapswithme/core/jni_helper.cpp
- android/jni/com/mapswithme/core/jni_helper.hpp
- android/jni/com/mapswithme/maps/MwmApplication.cpp
- android/jni/com/mapswithme/platform/Platform.cpp
- android/jni/com/mapswithme/platform/Platform.hpp
- android/multidex-config.txt
- android/src/com/mapswithme/maps/MwmApplication.java
https://jira.mail.ru/browse/MAPSME-7405
> [android] Initialize settings dir in Platform constructor.

- data/countries.txt
- data/external_resources.txt
> [planet] Data from 17.04.2018 → 8.2

- data/countries.txt
- data/external_resources.txt
> [planet] Data from 17.04.2018

- android/jni/com/mapswithme/maps/MapManager.cpp
- android/src/com/mapswithme/maps/downloader/MapManager.java
- android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
https://jira.mail.ru/browse/MAPSME-7194
> [android] Auto-update screen. Reload info on resume

- routing/routing_integration_tests/bicycle_turn_test.cpp
- routing/routing_integration_tests/turn_test.cpp
- routing/turns_generator.cpp
В случае если маршрут следует по самому правому (самому левому) из возможных выходов из маневра, мы смещаем углы, на базе которых генерируется заданный маневр. Данный PR изменяет данную таблицу углов, чтоб поправить:
https://jira.mail.ru/browse/MAPSME-7428
https://jira.mail.ru/browse/MAPSME-7429
По данным тикетам завтра добавлю тесты.
При этом меняется ряд интеграционных тестов:
Вот street view данного места:
https://www.google.com/maps/@52.16386,5.5661993,3a,75y,6.81h,61.2t/data=!3m6!1e1!3m4!1sSpk0CmmAJOLX3-5IRk75hw!2e0!7i13312!8i6656
> Changing turn angles in rightmost and leftmost direction.

- android/res/layout/fragment_search_filter.xml
https://jira.mail.ru/browse/MAPSME-7236
> [android] Done to Search for hotel filter

- android/gradle.properties
[Cherry pick](https://github.com/mapsme/omim/pull/8594) on master branch.
> [android] Fix obbPush command

- android/res/layout/fragment_bookmark_list.xml
- android/res/layout/item_bookmark.xml
- android/res/layout/item_track.xml
- android/res/layout/simple_list.xml
- android/src/com/mapswithme/maps/bookmarks/BookmarkListAdapter.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
- android/src/com/mapswithme/maps/bookmarks/Holders.java
- android/src/com/mapswithme/maps/bookmarks/data/Bookmark.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkInfo.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
https://jira.mail.ru/browse/MAPSME-7479
> Mapmse 7479 bookmark ui performance

- android/src/com/mapswithme/maps/SplashActivity.java
- android/src/com/mapswithme/maps/base/BaseActivity.java
- android/src/com/mapswithme/maps/base/BaseActivityDelegate.java
- android/src/com/mapswithme/maps/base/BaseMwmFragmentActivity.java
- android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5ae1c43c638393737a4c2da5?time=last-seven-days
> [android] updater dialog crash fix

- base/newtype.hpp
- base/string_utils.hpp
- defines.hpp
- generator/generate_info.hpp
- generator/generator_tests/CMakeLists.txt
- generator/generator_tests/sponsored_storage_tests.cpp
- generator/generator_tool/generator_tool.cpp
- generator/osm_source.cpp
- generator/sponsored_dataset.hpp
- generator/sponsored_dataset_inl.hpp
- generator/sponsored_object_storage.hpp
- generator/viator_dataset.cpp
https://jira.mail.ru/browse/MAPSME-7292
пока не проверил через generate_planet, поэтому DNM
> [generator] added possibility to exclude some booking hotels

- map/search_api.cpp
Быстрый фикс для https://jira.mail.ru/browse/MAPSME-7530 Правильным решением кажется не прокидывать или даже не проставлять даты по-умолчанию в UI.
> [RELEASE ONLY] Booking filter fix

- kml/serdes.cpp
- kml/serdes.hpp
- map/bookmark_helpers.cpp
- map/track.cpp
Cherry pick https://github.com/mapsme/omim/pull/8632
> Fixed crash on track without style

- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCViewModel.swift
- iphone/Maps/Bookmarks/Categories/Categories/BMCCategoriesHeader.swift
- iphone/Maps/Bookmarks/Categories/Permissions/BMCPermissionsHeader.swift
- iphone/Maps/Common/MWMConsts.h
Minor UI fixes on bookmarks screen
Also changed global animation duration
> Bookmarks cosmetics

- android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
https://jira.mail.ru/browse/MAPSME-7570
> [DNM][android] Fixed hidding ugc screen in offline

- android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- indexer/ftypes_sponsored.cpp
- indexer/ftypes_sponsored.hpp
- iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMActionBarButton.mm
- map/framework.cpp
- map/place_page_info.cpp
- partners_api/CMakeLists.txt
- partners_api/mopub_ads.cpp
- partners_api/partners.cpp
- partners_api/partners.hpp
- xcode/partners_api/partners_api.xcodeproj/project.pbxproj
https://github.com/mapsme/omim/pull/8616
>  [CHERRY PICK] Partners refactoring

- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- android/src/com/mapswithme/util/statistics/Statistics.java
- iphone/Maps/Common/Statistics/StatisticsStrings.h
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- map/cloud.cpp
- map/cloud.hpp
https://github.com/mapsme/omim/pull/8637
> [CHERRY PICK]  Fixed false asserts in cloud

- map/local_ads_manager.cpp
- map/local_ads_manager.hpp
https://github.com/mapsme/omim/pull/8629
> [CHERRY PICK] Fixed mwm requesting in local ads manager

- android/build.gradle
https://jira.mail.ru/browse/MAPSME-7560
> [android] Updated mytracker sdk to 1.5.3

- android/jni/CMakeLists.txt
- feature_list/CMakeLists.txt
- generator/feature_segments_checker/CMakeLists.txt
- generator/generator_tests/CMakeLists.txt
- generator/srtm_coverage_checker/CMakeLists.txt
- kml/kml_tests/CMakeLists.txt
- kml/kml_tests/serdes_tests.cpp
- kml/pykmlib/CMakeLists.txt
- kml/serdes.cpp
- kml/serdes_binary.hpp
- map/benchmark_tool/CMakeLists.txt
- map/bookmark_helpers.cpp
- map/mwm_tests/CMakeLists.txt
- map/style_tests/CMakeLists.txt
- mapshot/CMakeLists.txt
- openlr/openlr_match_quality/openlr_assessment_tool/CMakeLists.txt
- qt/CMakeLists.txt
- routing/routing_benchmarks/CMakeLists.txt
- routing/routing_consistency_tests/CMakeLists.txt
- routing/routing_integration_tests/CMakeLists.txt
- routing/routing_tests/CMakeLists.txt
- search/search_quality/assessment_tool/CMakeLists.txt
- storage/storage_integration_tests/CMakeLists.txt
- storage/storage_tests/CMakeLists.txt
- track_analyzing/track_analyzer/CMakeLists.txt
- xcode/kml/kml.xcodeproj/project.pbxproj
* Cherry pick https://github.com/mapsme/omim/pull/8640
* Updated pykmlib dependencies.
> Save to bookmark data persistent feature types based on index.

- android/src/com/mapswithme/maps/bookmarks/BookmarkBackupController.java
- android/src/com/mapswithme/maps/widget/BookmarkBackupView.java
- android/src/com/mapswithme/util/SharedPropertiesUtils.java
https://jira.mail.ru/browse/MAPSME-7535
> Mapsme 7535 backup widget save state

- android/src/com/mapswithme/maps/bookmarks/BookmarkBackupController.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-7362
> [android] Added bookmark restoring statstics

- android/res/layout/fragment_bookmark_categories.xml
- android/src/com/mapswithme/maps/base/BaseMwmRecyclerFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/downloader/DownloaderFragment.java
https://jira.mail.ru/browse/MAPSME-7594
> [android] Fixed progress gravity on bookmark categories screen

- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/auth/Authorizer.java
- iphone/Maps/UI/Authorization/MWMAuthorizationViewModel.mm
- map/user.cpp
- map/user.hpp
https://confluence.mail.ru/display/MAPSME/Passport#Passport-Registerbytoken(GoogleandFacebook)
> Changed authentication scheme

- data/mixed_nodes.txt
- data/mixed_tags.txt
Маркетинговые данные для partner4 и partner5, а также обновления по ЧМ2018.
> [mixed_data] Adidas, Tretyakovka, new Fan Id points

- map/bookmark_manager.cpp
- map/cloud.cpp
- map/cloud.hpp
- partners_api/partners.cpp
Исправлено создание пустого снэпшота, исправлен расчет hash (теперь считается от KML-файла, а не от KMZ)
> Fixed cloud uploading

- map/api_mark_point.cpp
- map/api_mark_point.hpp
- map/mwm_url.cpp
- map/user_mark.cpp
> Fixed api marks style

- kml/serdes.cpp
- kml/types.hpp
- map/bookmark.cpp
- map/bookmark_manager.cpp
- xcode/kml/kml.xcodeproj/project.pbxproj
Восстанавливаем placemark-hotel из бэпака
> Rescue of old-style hotel placemarks

- platform/http_uploader_apple.mm
> [ios] Fix var declaration error

- partners_api/partners.cpp
> Removed Megabonus

- search/pre_ranker.cpp
Cherry-pick https://github.com/mapsme/omim/pull/8690 to release-82
> [search][MAPSME-7370] Filter viewport results for any results size

- data/countries.txt
- data/external_resources.txt
> [planet] Data from 13.05.2018 → 8.2

- data/countries.txt
- data/external_resources.txt
> [planet] Data from 13.05.2018 → master

- map/bookmark_manager.cpp
- map/map_tests/kmz_unarchive_test.cpp
- map/user_mark_id_storage.cpp
- map/user_mark_id_storage.hpp
https://jira.mail.ru/browse/MAPSME-7622
> Disable saving of bookmark ids during bookmarks loading.

- data/categories.txt
See https://github.com/mapsme/omim/issues/7085 for discussion.
> [categories] Minor fix.

- android/res/layout/fragment_downloader.xml
- android/res/layout/fragment_migrate.xml
- android/res/layout/fragment_suggest_country_download.xml
- android/res/layout/item_timetable_add.xml
- android/res/layout/onmap_downloader.xml
- android/src/com/mapswithme/maps/downloader/BottomPanel.java
- android/src/com/mapswithme/maps/downloader/CountrySuggestFragment.java
- android/src/com/mapswithme/maps/downloader/MigrationFragment.java
- android/src/com/mapswithme/maps/downloader/OnmapDownloader.java
- android/src/com/mapswithme/maps/editor/SimpleTimetableAdapter.java
- android/src/com/mapswithme/maps/routing/RoutingBottomMenuController.java
- android/src/com/mapswithme/util/UiUtils.java
https://jira.mail.ru/browse/MAPSME-7648
> [android] Fixed accent button look

- android/res/layout/fragment_auth_passport_dialog.xml
https://jira.mail.ru/browse/MAPSME-7653
> [android] Fixed social auth dialog size for english(other short) locale

- indexer/index_helpers.cpp
- routing/checkpoints.cpp
- routing/joint_index.cpp
Исправил несколько warnings и сделал более удобный вывод checkpoints в лог.
> Warning fixes and correcting some log information.

- generator/restriction_generator.cpp
- indexer/feature_data.cpp
- tools/python/booking_hotels.py
Если вы видели лог от сборщика данных, то знаете, что там слишком много ошибок, с которыми мы ничего не можем сделать. Потому что править 100500 населённых пунктов с адресами никто не будет, а рестрикшенов в Антарктиде не было и нет.
В этом реквесте я уменьшаю важность некоторых сообщений.
> [generator] Less warnings so that proper ones can be found

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- map/CMakeLists.txt
- map/bookmark.cpp
- map/bookmark.hpp
- map/bookmark_catalog.cpp
- map/bookmark_catalog.hpp
- map/bookmark_helpers.cpp
- map/bookmark_helpers.hpp
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/cloud.cpp
- map/map_tests/bookmarks_test.cpp
- map/map_tests/kmz_unarchive_test.cpp
- platform/CMakeLists.txt
- platform/platform_linux.cpp
- platform/platform_mac.mm
- platform/remote_file.cpp
- platform/remote_file.hpp
- xcode/map/map.xcodeproj/project.pbxproj
- xcode/platform/platform.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-7449
https://jira.mail.ru/browse/MAPSME-7450
> [Core] Catalog support

- android/res/values/donottranslate.xml
- iphone/Maps/MAPSME.plist
- map/cloud.cpp
- map/user.cpp
This reverts commit d1410fcb2160b49249decb3a78e9f4ede7241b86.
> Revert "[RELEASE ONLY] [ROLLBACK] Switching to stage servers for Passport, UGC and Cloud"

- routing/index_graph_starter.cpp
- routing/routing_integration_tests/route_test.cpp
cherry-pick to master
https://github.com/mapsme/omim/pull/8728
> Processing the case when the start and the finish of the route is near an Segment with zero length.

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
https://jira.mail.ru/browse/MAPSME-7451
> Check if a bookmark category is editable.

- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
https://jira.mail.ru/browse/MAPSME-7728
> Fixed uploading of empty files

- android/AndroidManifest.xml
- android/build.gradle
- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-7704
> Mapsme 7704 true release 82

- android/res/values/arrays.xml
https://jira.mail.ru/browse/MAPSME-7632
> [android] Changed localbiz link for whatsnew screen

- iphone/Maps/Bookmarks/BookmarksVC.mm
- iphone/Maps/Common/Statistics/StatisticsStrings.h
- iphone/Maps/UI/Settings/MWMAboutController.mm
Also removed email-related dead code from about screen
> [ios] remove share by email from bookmarks group

- android/src/com/mapswithme/maps/news/BaseNewsFragment.java
- android/src/com/mapswithme/util/Utils.java
https://jira.mail.ru/browse/MAPSME-7759
> [android] Added safe getting the string for whats new title

- tools/unix/build_omim.sh
Remove forced gcc on linux platform, add optional forced gcc option on macOS.
> [bash] Update build_omim.sh

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- android/src/com/mapswithme/maps/bookmarks/BookmarkBackupController.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/cloud.cpp
- map/cloud.hpp
https://jira.mail.ru/browse/MAPSME-7764
> Added device name for cloud restoring

- search/geocoder.cpp
- search/geocoder_context.hpp
Закомментировала неиспользуемый код, который планируется включить после включения неполного поиска.
> [search] Comment out unused search::GeocoderContext::m_numEmitted

- tools/python/mwm/mwm_feature_compare.py
- tools/unix/test_planet.sh
[Dashboard](http://coruscant.mapsme.cloud.devmail.ru/bb-quality/#/).
Example of output:
```
In 'Russia_Tambov Oblast.mwm' number of 'sponsored-booking' decreased by 34% (143 → 95)
In 'Abkhazia.mwm' number of 'sponsored-booking' decreased by 100% (1798 → 1)
In 'Russia_Nizhny Novgorod Oblast.mwm' number of 'sponsored-booking' decreased by 62% (3183 → 1208)
In 'Russia_Republic of Mordovia.mwm' number of 'sponsored-booking' decreased by 45% (2283 → 1247)
In 'Russia_Moscow.mwm' number of 'sponsored-booking' decreased by 22% (5458 → 4253)
Warning: some .mwm files lost more than 20% booking hotels
```
> [python] Add booking hotels count test

- android/src/com/mapswithme/maps/auth/Authorizer.java
- android/src/com/mapswithme/maps/auth/BaseMwmAuthorizationFragment.java
- android/src/com/mapswithme/maps/auth/PassportAuthDialogFragment.java
- android/src/com/mapswithme/maps/auth/SocialAuthDialogFragment.java
- android/src/com/mapswithme/maps/auth/TargetFragmentCallback.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkBackupController.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
https://jira.mail.ru/browse/MAPSME-7741
> Mapsme 7741 crash during social auth dialog rotation

- android/src/com/mapswithme/maps/news/BaseNewsFragment.java
https://jira.mail.ru/browse/MAPSME-7632
> [android] Fixed localbix url formatting on whats new

- android/res/layout/place_page_banner.xml
- android/src/com/mapswithme/maps/ads/MopubNativeAd.java
- android/src/com/mapswithme/maps/ads/MwmNativeAd.java
- android/src/com/mapswithme/maps/widget/placepage/BannerController.java
https://jira.mail.ru/browse/MAPSME-7768
> [android] Added showing custom ads choice icon for all mopub native ads

- android/res/layout-land/news_page.xml
- android/res/layout/news_page.xml
https://jira.mail.ru/browse/MAPSME-7787
> [android] Fixed whats new layout to fix all screens correctly

- iphone/Maps/3party/Flurry/Flurry.h
- iphone/Maps/3party/Flurry/FlurryConsent.h
- iphone/Maps/3party/Flurry/FlurrySessionBuilder.h
- iphone/Maps/Classes/Components/MWMViewController.h
- iphone/Maps/Classes/Components/MWMViewController.mm
- iphone/Maps/Classes/CustomAlert/RateAlert/MWMRateAlert.xib
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Core/Settings/MWMSettings.h
- iphone/Maps/Core/Settings/MWMSettings.mm
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/Settings/MWMAboutController.mm
- iphone/Maps/UI/Storyboard/Settings.storyboard
https://jira.mail.ru/browse/MAPSME-7781
Also updated Flurry SDK
> [ios] add opt-out options to about screen.

- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
https://jira.mail.ru/browse/MAPSME-7821
> [android] Added null assertion for opt out pref

- iphone/Maps/UI/Welcome/FirstLaunchController.swift
- iphone/Maps/UI/Welcome/WelcomePageController.swift
https://jira.mail.ru/browse/MAPSME-7815
> [ios] fix automatic map zoom on first launch

- iphone/Maps/Categories/UIKitCategories.h
- iphone/Maps/Categories/UIKitCategories.mm
- iphone/Maps/Classes/CustomAlert/RateAlert/MWMRateAlert.mm
- iphone/Maps/UI/Settings/MWMAboutController.mm
https://jira.mail.ru/browse/MAPSME-7793
> [ios] fix appstore review link

- iphone/Maps/UI/Search/MWMSearchManager.mm
https://jira.mail.ru/browse/MAPSME-7830
> [ios] fix search results panel on iPad

- data/mixed_tags.txt
> [sponsored] Add missing banner_url

- data/countries.txt
Пересобрал Москву и Петербург с правками из #8832 и #8833.
> [planet] Data from 27.05, but with rebuilt Msk and SPb

- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/UI/Welcome/WelcomePageController.swift
https://jira.mail.ru/browse/MAPSME-7832
> [ios] fix terms dialog on first launch

- iphone/Maps/UI/Storyboard/Welcome.storyboard
https://jira.mail.ru/browse/MAPSME-7778
> [ios] fix next button color on terms screen

- android/res/layout-land/news_page.xml
- android/src/com/mapswithme/maps/news/BaseNewsFragment.java
- android/src/com/mapswithme/util/UiUtils.java
https://jira.mail.ru/browse/MAPSME-7787
> Mapsme 7787 whats new layout fix

- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/cloud.cpp
- map/cloud.hpp
- map/framework_light.hpp
https://jira.mail.ru/browse/MAPSME-7845
> Added bookmarks cloud property to the lightweight framework

- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
https://jira.mail.ru/browse/MAPSME-7791
> [ios] exit from routing mode on reroute

- android/src/com/mapswithme/util/Utils.java
- map/framework.cpp
This reverts commit a39cc23deb27384e63c3a0f712eefb8a742d621f.
> Revert "[RELEASE_ONLY][booking] Disable deep links"

- search/pre_ranker.cpp
cherry-pick https://github.com/mapsme/omim/pull/8859 на релиз
> [search] Prefer objects with higher rank while sweeping nearby objects.

- partners_api/booking_api.cpp
https://jira.mail.ru/browse/MAPSME-7890
@burivuh fyi
> [booking] url hot fix

- partners_api/booking_api.cpp
cherry pick for https://github.com/mapsme/omim/pull/8864
> [cherry-pick][booking] url hot fix

- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
- iphone/Maps/Classes/Components/TabView/TabView.swift
- iphone/Maps/Classes/Components/TabView/TabViewController.swift
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Maps.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-7463
> [ios] add tabs to bookmarks screen

- data/categories.txt
Frau Galuschka, die einen Beitrag zu MAPS.ME leisten will, begrüßt euch and bittet, diesen Pull-Request anzunehmen.
Vielen Dank
> Adding DE synonyms to categories which are important to HLA

- android/jni/com/mapswithme/platform/Platform.cpp
- android/src/com/mapswithme/util/Utils.java
- local_ads/statistics.cpp
- platform/platform.hpp
- platform/platform_ios.mm
- platform/platform_linux.cpp
- platform/platform_mac.mm
- platform/platform_win.cpp
https://jira.mail.ru/browse/MAPSME-7847
> Added offline id for local ads statistics

- coding/traffic.hpp
- map/CMakeLists.txt
- map/extrapolation/extrapolator.cpp
- map/extrapolation/extrapolator.hpp
- map/extrapolation_benchmark/CMakeLists.txt
- map/extrapolation_benchmark/extrapolation_benchmark.cpp
- map/framework.cpp
- map/framework.hpp
- map/map_tests/CMakeLists.txt
- map/map_tests/extrapolator_tests.cpp
- map/routing_manager.cpp
- map/routing_manager.hpp
- platform/location.hpp
- platform/platform.cpp
- platform/platform.hpp
- routing/base/followed_polyline.cpp
- routing/base/followed_polyline.hpp
- track_analyzing/track_analyzer/CMakeLists.txt
- track_analyzing/track_analyzer/cmd_match.cpp
- track_analyzing/track_analyzer/cmd_table.cpp
- track_analyzing/track_analyzer/cmd_unmatched_tracks.cpp
- track_analyzing/track_analyzer/track_analyzer.cpp
- track_analyzing/track_analyzer/utils.cpp
- track_analyzing/track_analyzer/utils.hpp
- xcode/map/map.xcodeproj/project.pbxproj
Экстраполятор gps позиции.
Эта версия не плохо работает в поле на android и iOS. Сейчас тестируется на расход аккумулятора: https://jira.mail.ru/browse/MAPSME-7500
До ее мержа в мастер я хочу:
- сделать одно из todo указанных в PR:
// @TODO(bykoinako) Method m_extrapolatedLocationUpdate() is run on gui thread every
// |kExtrapolationPeriodMs| milliseconds. But after changing GPS position
// (that means after a call of method Routine::SetGpsInfo())
// m_extrapolatedLocationUpdate() should be run immediately on gui thread.
- написать юнит тесты на Extrapolator
- сделать, что экстраполятор включался только в режиме авто навигации
@rokuz @mpimenov PTAL
> Linear extrapolation of GPS position.

- data/categories.txt
We don't currently support Malay. This commit removes "ms:"
from the list of recently added translations.
> [categories] A fix.

- android/build.gradle
Оригинальный PR:
https://github.com/mapsme/omim/pull/8857
> [android] Turn ON precompiled headers for android

- map/bookmark_catalog.cpp
- map/bookmark_manager.cpp
Исправлена невозможность повторной закачки из каталога при ошибке скачивания
> Fixed bookmarks catalog downloading

- data/mixed_nodes.txt
- data/mixed_tags.txt
Те самые зелёно-фиолетовенькие точечки для МегаФона и значки на аэропортах.
> [sponsored] Megafon points

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/discovery/DiscoveryActivity.java
- android/src/com/mapswithme/maps/discovery/DiscoveryFragment.java
- android/src/com/mapswithme/maps/discovery/DiscoveryManager.java
- android/src/com/mapswithme/maps/discovery/DiscoveryResultReceiver.java
- android/src/com/mapswithme/maps/discovery/ItemType.java
- android/src/com/mapswithme/maps/gallery/Holders.java
- android/src/com/mapswithme/maps/gallery/impl/BaseItemSelectedListener.java
- android/src/com/mapswithme/maps/gallery/impl/Factory.java
- android/src/com/mapswithme/maps/gallery/impl/SearchBasedAdapterStrategy.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-7902
> [android] Added search for food and attractions on Discovery screen

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- android/src/com/mapswithme/maps/bookmarks/BaseBookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/CachedBookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/OnItemLongClickListener.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
https://jira.mail.ru/browse/MAPSME-7943
> Mapsme 7943 fixed category error import

- routing/turns_generator.cpp
> Compile warning fix.

- iphone/Maps/UI/Discovery/DiscoveryCollectionHolderCell.swift
- iphone/Maps/UI/Discovery/MWMDiscoveryController.mm
- iphone/Maps/UI/Discovery/MWMDiscoveryTableManager.mm
https://jira.mail.ru/browse/MAPSME-7903
> [ios] add more buttons to discovery categories

- data/faq.html
> added the link to online help

- android/res/layout-land/activity_map.xml
- android/res/layout-w1020dp/activity_map.xml
- android/res/layout/activity_map.xml
- android/res/layout/onmap_downloader.xml
https://jira.mail.ru/browse/MAPSME-7910
> [android] Fixed scroll map behaviour during dowloading map

- defines.hpp
- generator/CMakeLists.txt
- generator/generator_tests_support/test_mwm_builder.cpp
- generator/generator_tool/generator_tool.cpp
- generator/popular_places_section_builder.cpp
- generator/popular_places_section_builder.hpp
- indexer/indexer_tests/rank_table_test.cpp
- indexer/rank_table.cpp
- indexer/rank_table.hpp
- map/discovery/discovery_manager.cpp
- map/discovery/discovery_search_params.hpp
- map/search_api.cpp
- search/geocoder.cpp
- search/intermediate_result.hpp
- search/locality_finder.cpp
- search/pre_ranker.cpp
- search/pre_ranking_info.cpp
- search/pre_ranking_info.hpp
- search/rank_table_cache.cpp
- search/ranker.cpp
- search/ranking_info.cpp
- search/ranking_info.hpp
- search/result.cpp
- search/result.hpp
- tools/unix/generate_planet.sh
https://jira.mail.ru/browse/MAPSME-7927
https://jira.mail.ru/browse/MAPSME-7928
> [generator][indexer]Popular places ranks

- map/search_api.cpp
https://jira.mail.ru/browse/MAPSME-8033
> [discovery] Search for discovery fix

- android/res/layout/about.xml
- android/src/com/mapswithme/maps/settings/AboutFragment.java
- android/src/com/mapswithme/util/Constants.java
- android/src/com/mapswithme/util/statistics/AlohaHelper.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-7744
> [android] Deleted deprecated actions

- partners_api/booking_availability_params.cpp
- partners_api/booking_block_params.cpp
https://jira.mail.ru/browse/MAPSME-8048
> [booking] dates by default are changed.

- data/categories.txt
https://jira.mail.ru/browse/MAPSME-8045
> [categories] Synonyms for sights and attractions.

- iphone/Maps/Bookmarks/BookmarksVC.mm
https://jira.mail.ru/browse/MAPSME-8051
> [iOS] fix bookmark deletion

- data/categories.txt
>  [categories] Synonyms for sights and attractions.

- drape/batcher.hpp
- drape_frontend/traffic_generator.cpp
- drape_frontend/traffic_generator.hpp
- drape_frontend/traffic_renderer.cpp
- shaders/CMakeLists.txt
- shaders/GL/shader_index.txt
- shaders/GL/traffic_circle.fsh.glsl
- shaders/GL/traffic_circle.vsh.glsl
- shaders/program_params.hpp
- shaders/programs.hpp
- shaders/shaders_tests/gl_program_params_tests.cpp
https://jira.mail.ru/browse/MAPSME-7191
> Fixed traffic rendering

- android/res/layout/item_track.xml
- android/src/com/mapswithme/maps/bookmarks/BookmarkListAdapter.java
- android/src/com/mapswithme/maps/bookmarks/Holders.java
https://jira.mail.ru/browse/MAPSME-7985
> Mapsme 7985 index out of bounds

- android/res/menu/menu_bookmarks.xml
- android/res/menu/menu_bookmarks_catalog.xml
- android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
- android/src/com/mapswithme/util/sharing/ShareOption.java
https://jira.mail.ru/browse/MAPSME-7305
> [android] Deleted deprecated bookmark ui actions

- android/src/com/mapswithme/maps/discovery/Popularity.java
https://jira.mail.ru/browse/MAPSME-7928
> [android] fix crash on discovery screen

- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesPagerFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksPageFactory.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksPagerAdapter.java
- android/src/com/mapswithme/maps/bookmarks/CachedBookmarkCategoriesFragment.java
- android/src/com/mapswithme/util/statistics/Analytics.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-8039
> [android] Added statistics for catalog

- partners_api/maxim_api.cpp
https://jira.mail.ru/browse/MAPSME-7974
> [maxim] links

- data/faq.html
> FAQ July18 Fix

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/location/LocationHelper.java
- android/src/com/mapswithme/maps/routing/NavigationController.java
- android/src/com/mapswithme/maps/routing/RoutingBottomMenuController.java
- android/src/com/mapswithme/maps/routing/RoutingBottomMenuListener.java
- android/src/com/mapswithme/maps/routing/RoutingController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-8047
> Refactored, fixed and improved routing start/finish statistic

- android/src/com/mapswithme/maps/bookmarks/BookmarkListAdapter.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
- android/src/com/mapswithme/maps/bookmarks/Holders.java
- android/src/com/mapswithme/maps/bookmarks/data/CategoryDataSource.java
- android/src/com/mapswithme/maps/content/DataSource.java
https://jira.mail.ru/browse/MAPSME-8052
> [android] Fixed update category instance when user deleted track

- iphone/Maps/Bookmarks/Catalog/CatalogCategoryCell.swift
- iphone/Maps/Bookmarks/Catalog/CatalogCategoryCell.xib
- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.xib
- iphone/Maps/Bookmarks/Categories/Categories/BMCCategoriesHeader.swift
- iphone/Maps/Bookmarks/Categories/Notifications/BMCNotificationsHeader.swift
- iphone/Maps/Bookmarks/Categories/Permissions/BMCPermissionsHeader.swift
https://jira.mail.ru/browse/MAPSME-7465
> [iOS] fix catalog styles and missing translations

- iphone/Maps/Bookmarks/BookmarksVC.mm
https://jira.mail.ru/browse/MAPSME-8051
> [iOS] fix bookmarks deletion

- android/jni/com/mapswithme/maps/discovery/DiscoveryManager.cpp
- iphone/Maps/UI/Discovery/DiscoveryControllerViewModel.hpp
- iphone/Maps/UI/Discovery/MWMDiscoveryController.mm
- map/CMakeLists.txt
- map/discovery/discovery_manager.hpp
- map/discovery/discovery_search_callback.cpp
- map/discovery/discovery_search_callback.hpp
- map/discovery/discovery_search_params.hpp
- map/everywhere_search_callback.cpp
- map/everywhere_search_callback.hpp
- map/everywhere_search_params.hpp
- map/search_api.cpp
- map/search_api.hpp
- map/search_product_info.hpp
- xcode/map/map.xcodeproj/project.pbxproj
Тикет не нашел
@alexzatsepin fyi
> [discovery][android][ios] ratings for discovery

- android/res/layout/item_discovery_search.xml
- android/res/values/attrs.xml
- android/src/com/mapswithme/maps/widget/RatingView.java
#	android/src/com/mapswithme/maps/discovery/Popularity.java
> [android] Added RatingView ellipsize support

- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.xib
- iphone/Maps/Classes/Components/TabView/TabView.swift
- iphone/Maps/Classes/MapsAppDelegate.mm
especially on iOS 9
https://jira.mail.ru/browse/MAPSME-7465
> [iOS] fix rotation and other layout issues on bookmarks screen

- generator/borders_loader.cpp
- generator/borders_loader.hpp
- generator/feature_sorter.cpp
Не учла что у нас в тестах собираются mwm тем же механизмом и файлов с границами для них нет.
> [generator] Fix test mwms build

- search/intermediate_result.cpp
- search/intermediate_result.hpp
- search/pre_ranker.cpp
- search/ranking_info.cpp
- search/search_quality/scoring_model.py
cherry-pick https://github.com/mapsme/omim/pull/9069
> [search] Prefer objects with higher popularity

- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
https://jira.mail.ru/browse/MAPSME-7983
> [iOS] fixed routing from start point

- data/countries.txt
- data/external_resources.txt
> [planet] Data from 5.07.2018 → master

- data/countries.txt
- data/external_resources.txt
> [planet] Data from 5.07.2018 → r8.3

- android/src/com/mapswithme/maps/location/SensorData.java
- android/src/com/mapswithme/maps/location/SensorHelper.java
https://jira.mail.ru/browse/MAPSME-4347
> [android] Compass throttling

- data/countries.txt
В общем, это всё что поменялось после обновления UGC. Данные уже раскатил. Вмёржите, плз.
> [planet] Update data for 5.07.2018 → r8.3

- data/countries.txt
> [planet] Update data for 5.07.2018 → master

- iphone/Maps/MAPSME.plist
https://jira.mail.ru/browse/MAPSME-7981
> [iOS] fix maxim taxi deeplink

- iphone/Maps/Bookmarks/BookmarksTabViewController.swift
- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
- iphone/Maps/Classes/Components/TabView/TabView.swift
https://jira.mail.ru/browse/MAPSME-8038
> [iOS] add stats for catalog

- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
https://jira.mail.ru/browse/MAPSME-8101
> [iOS] sometimes on iOS10 downloaded categories not displayed, fixed

- map/framework.cpp
- map/search_api.cpp
требуется еще фикс внутри поиска от @tatiana-yan
> [discovery] search distance fix

- iphone/Maps/Classes/MapsAppDelegate.mm
https://jira.mail.ru/browse/MAPSME-8095
> [iOS] fixed multiple rate alerts

- iphone/Maps/UI/Downloader/MWMBaseMapDownloaderViewController.mm
https://jira.mail.ru/browse/MAPSME-7254
> [iOS] show "cancel all" button on maps update screen

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/maplayer/subway/OnSubwayLayerToggleListener.java
- android/src/com/mapswithme/maps/routing/RoutingPlanController.java
https://jira.mail.ru/browse/MAPSME-8134
> [android] Route planning mode : ignore disabling subway map layer

- iphone/Maps/UI/Search/Filters/MWMSearchHotelsFilterViewController.mm
https://jira.mail.ru/browse/MAPSME-7563
> [iOS] don't apply "from" and "to" filters to hotels while offline

- map/discovery/discovery_search_params.hpp
- map/search_api.cpp
https://jira.mail.ru/browse/MAPSME-8137
> [discovery] ratings fix

- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.xib
https://jira.mail.ru/browse/MAPSME-8030
> [iOS] fix megafon banner animation

- iphone/Maps/3party/MoPubSDK/Internal/MPHTTPNetworkSession.m
https://jira.mail.ru/browse/MAPSME-7877
> [iOS] fix crash in MoPub sdk

- iphone/Maps/UI/Storyboard/Welcome.storyboard
- iphone/Maps/UI/Welcome/TermsOfUseController.swift
https://jira.mail.ru/browse/MAPSME-8001
> [iOS] check terms and privacy checkmarks on tap by text

- iphone/Maps/UI/Storyboard/Settings.storyboard
https://jira.mail.ru/browse/MAPSME-8160
> [iOS] fixed backup menu in settings

- android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
https://jira.mail.ru/browse/MAPSME-8162
> [android] Fixed maplayer dialog position

- search/categories_cache.cpp
- search/categories_cache.hpp
- search/geocoder.hpp
- search/intermediate_result.cpp
- search/intermediate_result.hpp
- search/processor.cpp
- search/processor.hpp
- search/ranker.cpp
- search/ranker.hpp
- search/search_integration_tests/CMakeLists.txt
- search/search_integration_tests/utils_test.cpp
- search/utils.cpp
- search/utils.hpp
- xcode/search/search.xcodeproj/project.pbxproj
Черри-пик
https://github.com/mapsme/omim/pull/9108
https://github.com/mapsme/omim/pull/9118
и тесты
> [search] Discovery helpers

- iphone/Maps/Common/Statistics/Statistics.mm
https://jira.mail.ru/browse/MAPSME-7609
> [iOS] fix connection type stats

- android/res/layout/fragment_search.xml
- android/src/com/mapswithme/maps/search/SearchFragment.java
https://jira.mail.ru/browse/MAPSME-8166
> [android] Changed foreground for view

- android/src/com/mapswithme/maps/downloader/UpdaterDialogFragment.java
https://jira.mail.ru/browse/MAPSME-8182
> [android] Fixed NPE during autoupdate error

- android/src/com/mapswithme/maps/downloader/CountryItem.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5b4f283f6007d59fcdef9f4a?time=last-ninety-days
> [android] Fixed npe in place page

- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogActivity.java
https://jira.mail.ru/browse/MAPSME-8192
> [android] Get catalog url from forwarded intent

- geocoder/CMakeLists.txt
- geocoder/geocoder.cpp
- geocoder/geocoder.hpp
- geocoder/geocoder_tests/geocoder_tests.cpp
- geocoder/hierarchy.cpp
- geocoder/hierarchy.hpp
This is the baseline version of the hierarchy-based geocoder.
> [geocoder] Simple hierarchy-assisted backtracking.

- iphone/Maps/Classes/CustomViews/MapViewControls/Layers/LayersViewController.swift
https://jira.mail.ru/browse/MAPSME-8204
> [iOS] fixed traffic and subway stats

- android/src/com/mapswithme/maps/bookmarks/BookmarkListAdapter.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
- android/src/com/mapswithme/maps/bookmarks/data/AbstractCategoriesSnapshot.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkCategory.java
https://jira.mail.ru/browse/MAPSME-8211
> [android] Fixed bookmarks list updated from location listener

- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/BookmarkCell/MWMBookmarkCell.h
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/BookmarkCell/MWMBookmarkCell.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/BookmarkCell/MWMBookmarkCell.xib
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-8212
> [iOS] show description for bookmarks from catalog on PP

- indexer/data_source.cpp
DNM до добавления тестов.
Вручную проверила работу редактора, всё ок.
> [indexer] Fix ReadFeatureType: now we use it to read all features including created.

- editor/editor_tests/osm_editor_test.cpp
Добавила тест на получение FeatureType из EditableDataSorce (ForEachInRect).
Также есть метод для получения FeatureID из EditableDataSorce (ForEachFeatureIDInRect), он работает неожиданным образом, так как внутри DataSorce для получения FeatureType и для получения FeatureID используются разные режимы Coveing, для FeatureID используется режим, который возвращает также родительский прямоугольник квадродерева, поэтому например если у нас есть точки (1.0, 1.0) и (3.0, 3.0) поиск ForEachFeatureIDInRect для прямоугольника (2.0, 2.0, 4.0, 4.0) находит обе, т.к. у них есть общий родитель.
Как должен работать ForEachFeatureIDInRect и нужен ли вообще такой режим каверинга нужно разбираться отдельно и это относится не только к редактору, но и к DataSource вообще.
> [editor] Test count features by EditableDataSorce

- tools/python/mwm_downloader.py
`country_names_generator` based on `check_item` from `cdncheck` repo.
> [python] Update python mwm_downloader

- map/booking_availability_filter.cpp
https://www.fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/5b5922566007d59fcdc4159c?time=last-seven-days
https://www.fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5b5801a06007d59fcdaa6ed8?time=last-seven-days
> [booking] Crash fix in availability filter

- iphone/Maps/Bookmarks/BookmarksTabViewController.swift
- iphone/Maps/Classes/Components/TabView/TabView.swift
https://jira.mail.ru/browse/MAPSME-8240
> [iOS] fixed bookmarks layout on iPhone X

- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/CachedBookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- map/bookmark_manager.cpp
- map/bookmark_manager.hpp
- map/framework.cpp
- map/framework.hpp
https://jira.mail.ru/browse/MAPSME-8234
> [Core] Added support of catalog popup

- drape_frontend/frontend_renderer.cpp
- drape_frontend/message_subclasses.hpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5b5c0ba56007d59fcd025b75
> Fixed crash on texture manager usage before initialization

- drape/framebuffer.cpp
- drape/framebuffer.hpp
- drape_frontend/frontend_renderer.cpp
- drape_frontend/postprocess_renderer.cpp
- drape_frontend/postprocess_renderer.hpp
https://jira.mail.ru/browse/MAPSME-8241
> Fixed false depth-stencil usage on OpenGLES 2.0

- android/jni/com/mapswithme/maps/SearchEngine.cpp
- iphone/Maps/Core/Search/MWMSearch.mm
- map/booking_filter_params.hpp
- map/everywhere_search_callback.cpp
- map/viewport_search_callback.cpp
https://jira.mail.ru/browse/MAPSME-8236
> Hidden loading of booking deals in filters is suppressed when network policy is not allowed.

- android/build.gradle
- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/search/HiddenCommand.java
- android/src/com/mapswithme/maps/search/SearchFragment.java
https://jira.mail.ru/browse/MAPSME-8256
> Mapsme 8526 update fabric and make crashes

- feature_list/feature_list.cpp
Правки feature_list_generator со сборочной машины.
> [feature_list] Pedestrian highways and booking hotels in feed

- indexer/CMakeLists.txt
- indexer/popularity_loader.cpp
- indexer/popularity_loader.hpp
- map/framework.cpp
- map/framework.hpp
- map/place_page_info.hpp
- xcode/indexer/indexer.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-8235
> [indexer] popularity for place page

- partners_api/maxim_api.cpp
- partners_api/partners_api_tests/booking_tests.cpp
https://github.com/mapsme/omim/pull/9231
> [cherry-pick][partners_api] tests fix

- partners_api/maxim_api.cpp
- partners_api/partners_api_tests/booking_tests.cpp
Часть https://jira.mail.ru/browse/MAPSME-8297
> [partners_api] tests fix

- generator/cities_boundaries_builder.cpp
- search/cities_boundaries_table.cpp
@mpimenov @tatiana-yan @ygorshenin PTAL
> Fixing dangling refs in CategoriesCache.

- feature_list/feature_list.cpp
Не давний PR: https://github.com/mapsme/omim/pull/9183 сломал сборку feature_list_generator. Данный PR ее чинит.
@Zverik @tatiana-yan PTAL
> feature_list_generator build fix.

- map/framework.cpp
> Moving up FeaturesLoaderGuard in VisualizeCityBoundariesInRect().

- tracking/reporter.cpp
cherry-pick https://github.com/mapsme/omim/pull/9249
> [tracking] Fix race.

- android/res/layout/fragment_show_on_map_catalog_category.xml
- android/res/values/dimens.xml
- android/res/values/font_sizes.xml
- android/res/values/styles.xml
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/bookmarks/BaseBookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesActivity.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogActivity.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
- android/src/com/mapswithme/maps/bookmarks/CachedBookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/CatalogListenerDecorator.java
- android/src/com/mapswithme/maps/bookmarks/ShowOnMapCatalogCategoryFragment.java
- android/src/com/mapswithme/maps/bookmarks/SystemDownloadCompletedService.java
- android/src/com/mapswithme/maps/routing/NavigationController.java
- android/src/com/mapswithme/util/SharedPropertiesUtils.java
https://jira.mail.ru/browse/MAPSME-8221
> [android] Added show catalog category on map dialog

- android/src/com/mapswithme/maps/maplayer/traffic/TrafficManager.java
- android/src/com/mapswithme/maps/maplayer/traffic/TrafficState.java
- android/src/com/mapswithme/maps/maplayer/traffic/widget/TrafficButtonController.java
- android/src/com/mapswithme/maps/routing/NavigationController.java
https://jira.mail.ru/browse/MAPSME-8037
> [android] Fixed multiple stat calls

- iphone/Maps/Categories/NSAttributedString+HTML.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/BookmarkCell/MWMBookmarkCell.mm
https://jira.mail.ru/browse/MAPSME-8223
> [iOS] fix html formatting in PP bookmark description

- iphone/Maps/UI/PlacePage/MWMPlacePageData.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/MWMPPPreviewLayoutHelper.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/PPPReview.swift
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/PPPReview.xib
- partners_api/booking_api.hpp
https://jira.mail.ru/browse/MAPSME-8344
> [iOS] add booking hot offers to PP

- android/jni/com/mapswithme/maps/Sponsored.cpp
- android/res/layout/place_page_preview.xml
- android/res/layout/place_page_preview_rating.xml
- android/res/values/attrs.xml
- android/res/values/integer.xml
- android/src/com/mapswithme/maps/search/SearchAdapter.java
- android/src/com/mapswithme/maps/search/SearchResult.java
- android/src/com/mapswithme/maps/ugc/Impress.java
- android/src/com/mapswithme/maps/widget/RatingView.java
- android/src/com/mapswithme/maps/widget/placepage/HotelPriceInfo.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- android/src/com/mapswithme/maps/widget/placepage/Sponsored.java
https://jira.mail.ru/browse/MAPSME-8250
см после https://github.com/mapsme/omim/pull/9260
> [DNM] Mapsme 8250 placepage hotel discount

- iphone/Maps/UI/PlacePage/MWMPlacePageData.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/MWMPPPreviewLayoutHelper.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/_MWMPPPTitle.xib
- iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
- iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.xib
https://jira.mail.ru/browse/MAPSME-8348
> [iOS] show popular on PP and search results

- android/res/layout/fragment_auth_editor.xml
- android/res/layout/fragment_auth_editor_dialog.xml
- android/src/com/mapswithme/maps/editor/OsmAuthFragmentDelegate.java
https://jira.mail.ru/browse/MAPSME-8380
> [android] Deleted fb auth

- android/src/com/mapswithme/maps/routing/NavigationController.java
https://jira.mail.ru/browse/MAPSME-8219
> [android] Fixed toggle traffic mode in routing

- android/AndroidManifest.xml
- android/res/layout/item_search_result.xml
- android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
- android/src/com/mapswithme/maps/IntentProcessor.java
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/intent/Factory.java
- android/src/com/mapswithme/maps/intent/IntentProcessor.java
https://jira.mail.ru/browse/MAPSME-8359
> Mapsme 8359 mapsme scheme filter

- android/AndroidManifest.xml
- android/res/layout/fragment_catalog_bookmark_categories.xml
- android/res/layout/fragment_show_on_map_catalog_category.xml
- android/res/layout/menu_content.xml
- android/res/layout/menu_content_grid.xml
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/bookmarks/AdapterResourceProvider.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksPageFactory.java
- android/src/com/mapswithme/maps/bookmarks/CatalogListenerDecorator.java
https://jira.mail.ru/browse/MAPSME-8387
> [android] Updated strings for bookmarks catalog ui

- iphone/Maps/Bookmarks/BookmarksTabViewController.swift
- iphone/Maps/Bookmarks/Catalog/BookmarksLoadedViewController.xib
- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.xib
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/UI/BottomMenu/MWMBottomMenuViewController.mm
https://jira.mail.ru/browse/MAPSME-8386
> [iOS] updated strings

- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
https://jira.mail.ru/browse/MAPSME-8393
> [iOS] open booking.com in external browser

- iphone/Maps/Bookmarks/Catalog/BookmarksLoadedViewController.xib
- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
- iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-8395
https://jira.mail.ru/browse/MAPSME-8397
> [iOS] fix catalog UI bugs

- qt/update_dialog.cpp
- storage/storage.cpp
Сделано согласно https://jira.mail.ru/browse/MAPSME-8368
> Fixed last map downloaded

- map/bookmark_catalog.cpp
- map/bookmark_catalog.hpp
- map/bookmark_manager.cpp
https://jira.mail.ru/browse/MAPSME-8436
> Fixed registration KML in the catalog

- android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
https://jira.mail.ru/browse/MAPSME-8447
> Mapsme 8447 layers button fix

- android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
https://jira.mail.ru/browse/MAPSME-8447
> cherry-pick

- android/jni/com/mapswithme/maps/Framework.cpp
- coding/sha1.cpp
- coding/sha1.hpp
- drape_frontend/map_data_provider.cpp
- drape_frontend/map_data_provider.hpp
- drape_frontend/rule_drawer.cpp
- drape_frontend/rule_drawer.hpp
- drape_frontend/tile_info.cpp
- iphone/Maps/Classes/Widgets/MWMMapDownloadDialog.mm
- iphone/Maps/Core/Search/MWMSearch.mm
- local_ads/statistics.cpp
- local_ads/statistics.hpp
- map/CMakeLists.txt
- map/framework.cpp
- map/framework.hpp
- map/local_ads_manager.cpp
- map/local_ads_manager.hpp
- map/subscription.cpp
- map/subscription.hpp
- partners_api/partners.cpp
- partners_api/partners.hpp
- xcode/map/map.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-8361
> [Core] Added subscription

- android/gradle.properties
- android/multidex-config.txt
Фикс крэша на старте на андроид 4.x (версия 8.3.5)
> No issue fix android 4x crash

- android/src/com/mopub/nativeads/GooglePlayServicesNative.java
https://jira.mail.ru/browse/MAPSME-8322
> [android] Removed logo check in admob implementation in mopub sdk

- android/src/com/mopub/nativeads/GooglePlayServicesNative.java
https://github.com/mapsme/omim/pull/9343
> [android] [cherry-pick]Removed logo check in admob implementation in mopub sdk

- android/jni/com/mapswithme/maps/editor/Editor.cpp
- base/CMakeLists.txt
- base/atomic_shared_ptr.hpp
- editor/config_loader.cpp
- editor/config_loader.hpp
- editor/editable_feature_source.cpp
- editor/editable_feature_source.hpp
- editor/editor_config.hpp
- editor/editor_storage.cpp
- editor/editor_storage.hpp
- editor/editor_tests/config_loader_test.cpp
- editor/editor_tests/osm_editor_test.cpp
- editor/editor_tests/osm_editor_test.hpp
- editor/editor_tests_support/helpers.cpp
- editor/osm_editor.cpp
- editor/osm_editor.hpp
- indexer/data_source.cpp
- indexer/feature_source.cpp
- indexer/feature_source.hpp
- map/framework.cpp
- search/editor_delegate.cpp
- search/mwm_context.cpp
- search/mwm_context.hpp
- search/reverse_geocoder.cpp
- search/reverse_geocoder.hpp
- xcode/base/base.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-8254
продолжение https://github.com/mapsme/omim/pull/9269
> [editor] Synchronization.

- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
- iphone/Maps/Bookmarks/Categories/Categories/BMCCategoriesHeader.swift
https://jira.mail.ru/browse/MAPSME-8386
> [iOS] update downloaded categories title

- android/res/drawable/bg_ads.xml
- android/res/drawable/bg_ads_action.xml
- android/res/drawable/bg_ads_action_night.xml
- android/res/drawable/bg_ads_night.xml
- android/res/drawable/bg_pp_banner_large_button_night.xml
- android/res/drawable/bg_pp_banner_remove_button.xml
- android/res/drawable/bg_pp_banner_remove_button_night.xml
- android/res/layout/place_page_banner_content.xml
- android/res/values/colors.xml
- android/res/values/themes-attrs.xml
- android/res/values/themes-base.xml
- android/src/com/mapswithme/maps/widget/placepage/BannerController.java
> [android] Added removal button in PP banner

- qt/place_page_dialog.cpp
> [desktop] add comma in widget for desktop

- android/build.gradle
- android/res/layout/place_page_banner_content.xml
- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/maps/purchase/AdRemovalPurchaseValidator.java
- android/src/com/mapswithme/maps/purchase/BillingManager.java
- android/src/com/mapswithme/maps/purchase/Factory.java
- android/src/com/mapswithme/maps/purchase/PlayStoreBillingManager.java
- android/src/com/mapswithme/maps/purchase/PurchaseValidator.java
> Mapsme 8407 billing integration

- map/place_page_info.cpp
https://jira.mail.ru/browse/MAPSME-8321
> fix for zero rating

- generator/generator_tests/restriction_test.cpp
> Change road restriction test message to correct variant.

- android/src/com/mapswithme/maps/purchase/AdSubscriptionValidator.java
- android/src/com/mapswithme/maps/purchase/AdValidationCallback.java
- android/src/com/mapswithme/maps/purchase/AdValidationStatus.java
- android/src/com/mapswithme/maps/purchase/Factory.java
- android/src/com/mapswithme/maps/purchase/PurchaseValidator.java
> [adroid] Made purchase validation callback generic

- generator/road_access_generator.cpp
access=permissive означает, что проезд по дороге разрешен, но может быть закрыт владельцем в будущем (частная дорога, граница государства и т.п.).
Данный PR разрешает проезд по дорогам с таким типом доступа, это нужно например для того чтобы лучше прокладывать маршруты через государственную границу.
> [routing][generator] Allow road access for access=permissive

- shaders/GL/arrow3d_shadow.vsh.glsl
https://jira.mail.ru/browse/MAPSME-8518
> Fixed rendering of the 3d-arrow shadow.

- map/framework.cpp
- map/framework.hpp
- map/map_tests/tips_tests.cpp
- map/tips_api.cpp
- map/tips_api.hpp
- metrics/eye.cpp
- metrics/eye.hpp
- metrics/eye_info.hpp
- metrics/metrics_tests/eye_tests.cpp
- metrics/metrics_tests_support/eye_for_testing.cpp
- metrics/metrics_tests_support/eye_for_testing.hpp
Допы для https://jira.mail.ru/browse/MAPSME-8360
> [eye][tips] Additional requirements are supported

- drape_frontend/stylist.cpp
https://jira.mail.ru/browse/MAPSME-8478
> Fixed arrows along oneway roads

- base/assert.hpp
- routing/coding.hpp
> Spelling fixes.

- data/categories.txt
синонимы из запросов в алохалитике
> [search] Add category synonyms

- android/build.gradle
- android/jni/com/mapswithme/maps/Framework.cpp
- android/res/values/colors.xml
- android/res/values/dimens.xml
- android/res/values/themes-attrs.xml
- android/res/values/themes-base.xml
- android/src/com/mapswithme/maps/ClickMenuDelegate.java
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
- android/src/com/mapswithme/maps/tips/AbstractClickInterceptor.java
- android/src/com/mapswithme/maps/tips/ClickInterceptor.java
- android/src/com/mapswithme/maps/tips/ClickInterceptorFactory.java
- android/src/com/mapswithme/maps/tips/TipsAction.java
- android/src/com/mapswithme/maps/tips/TipsApi.java
- android/src/com/mapswithme/maps/tips/TipsClickListener.java
- android/src/com/mapswithme/maps/tips/TipsProvider.java
- android/src/com/mapswithme/maps/widget/menu/MainMenu.java
- data/copyright.html
https://jira.mail.ru/browse/MAPSME-8404
> [android] Tips and tricks supported

- data/categories.txt
Italian translation of "Car shop" was wrong
> Fix italian translation

- android/src/com/mapswithme/maps/location/SensorHelper.java
https://jira.mail.ru/browse/MAPSME-8309
> [android] Fixed compass throttling

- android/res/layout/fragment_catalog_bookmark_categories.xml
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesPageResProvider.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksPageFactory.java
- android/src/com/mapswithme/maps/bookmarks/CachedBookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/Holders.java
https://jira.mail.ru/browse/MAPSME-8412
> [android] Changed bookmarks categories list interface

- generator/regions.cpp
Поправил warning при сборке генератора.
@maksimandrianov PTAL
> Generator build warning fix.

- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Core/Notifications/LocalNotificationManager.h
- iphone/Maps/Core/Notifications/LocalNotificationManager.mm
- iphone/Maps/Core/Notifications/MWMPushNotifications.h
- iphone/Maps/Core/Notifications/MWMPushNotifications.mm
https://jira.mail.ru/browse/MAPSME-8389
> [iOS] fix pushwoosh notifications handling

- configure.sh
> Added ads removal stubs

- android/res/color/booking_filter_title_color.xml
- android/res/color/booking_filter_title_color_night.xml
- android/res/color/filter_date_property_color.xml
- android/res/color/filter_date_property_color_night.xml
- android/res/drawable-v21/button_with_border.xml
- android/res/drawable-v21/button_with_border_night.xml
- android/res/drawable/button_with_border.xml
- android/res/drawable/button_with_border_default.xml
- android/res/drawable/button_with_border_disabled.xml
- android/res/drawable/button_with_border_internal.xml
- android/res/drawable/button_with_border_night.xml
- android/res/drawable/button_with_border_night_default.xml
- android/res/drawable/button_with_border_night_disabled.xml
- android/res/drawable/button_with_border_night_internal.xml
- android/res/layout/fragment_search_filter.xml
- android/res/values/attrs.xml
- android/res/values/colors.xml
- android/res/values/styles-text.xml
- android/res/values/themes-base.xml
- android/src/com/mapswithme/maps/search/FilterFragment.java
https://jira.mail.ru/browse/MAPSME-8402
> [android] Improved filter hotels

- android/src/com/mapswithme/maps/purchase/AdsRemovalPaymentState.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
> [android] Soft 'ads removal' validation strategy

- android/.gitignore
- android/res/xml/network_security_config.xml
- configure.sh
https://jira.mail.ru/browse/MAPSME-8613
> Mapsme 8613 ssl support

- routing/routing_quality/routing_quality_tests/waypoints_tests.cpp
Данный маршрут так же валиден. Он стал так прокладывать после карт 2018.09.11 и после учета городских фичь
> Routing quality tests fix.

- metrics/eye_storage.cpp
https://jira.mail.ru/browse/MAPSME-8635
> eye filename is changed to metrics

- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseCallback.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
- android/src/com/mapswithme/maps/purchase/PlayStoreBillingCallback.java
- android/src/com/mapswithme/maps/purchase/PlayStoreBillingManager.java
- android/src/com/mapswithme/maps/widget/placepage/BannerController.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-8615
> [android] Added ads removal statistic

- drape/drape_tests/testingmain.cpp
- drape/drape_tests/uniform_value_tests.cpp
> Drape test build fix.

- android/src/com/mapswithme/maps/dialog/AlertDialog.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPaymentState.java
[android] Refactore AlertDialog class to use builder to reduce input parameters
https://jira.mail.ru/browse/MAPSME-8644
> [android] Fixed crash during show alert dialog on payment failure

- android/src/com/mapswithme/maps/purchase/AdsRemovalPaymentState.java
https://jira.mail.ru/browse/MAPSME-8649
> [android] Fixed product details failure state

- android/src/com/mapswithme/maps/analytics/MyTrackerEventLogger.java
https://jira.mail.ru/browse/MAPSME-8604
> [android] Removed duplicated methods

- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/MWMPPPreviewLayoutHelper.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/PPPReview.swift
- iphone/Maps/UI/PlacePage/UGCViewModel/MWMUGCViewModel.h
- iphone/Maps/UI/PlacePage/UGCViewModel/MWMUGCViewModel.mm
https://jira.mail.ru/browse/MAPSME-8516
> [ios] fix for empty rating

- android/src/com/mapswithme/maps/ugc/UGCController.java
https://jira.mail.ru/browse/MAPSME-8515
> [android] fix for empty rating

- drape_frontend/frontend_renderer.cpp
- map/address_finder.cpp
> Warning fixes.

- routing/routing_integration_tests/route_test.cpp
- routing/routing_quality/routing_quality_tests/CMakeLists.txt
- routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp
- routing/routing_quality/routing_quality_tests/ferry_tests.cpp
- routing/routing_quality/routing_quality_tests/passby_roads_tests.cpp
- routing/routing_quality/routing_quality_tests/waypoints_tests.cpp
- routing/routing_quality/waypoints.cpp
- routing/routing_quality/waypoints.hpp
- routing_common/car_model.cpp
Данный PR в процессе разработки.
Цель данного PR - улучшить качество прокладки маршрута, задав лучшие коэффициенты. Ввиду ограниченности ресурсов пока действуем так:
- на базе ошибок собранных тех поддержкой пополняем routing_quality_tests
- делаем коэффициенты в car_model такими, чтоб они проходили
Данный PR исправляет тикеты:
https://jira.mail.ru/browse/MAPSME-7281
https://jira.mail.ru/browse/MAPSME-7095
https://jira.mail.ru/browse/MAPSME-7408
https://jira.mail.ru/browse/MAPSME-7412
https://jira.mail.ru/browse/MAPSME-8130
https://jira.mail.ru/browse/MAPSME-8456
https://jira.mail.ru/browse/MAPSME-8060
https://jira.mail.ru/browse/MAPSME-8474
https://jira.mail.ru/browse/MAPSME-7102
https://jira.mail.ru/browse/MAPSME-7122
https://jira.mail.ru/browse/MAPSME-7713 …
> [routing] Car model factors and routing quality tests.

- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseCallback.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
- android/src/com/mapswithme/maps/purchase/PlayStoreBillingCallback.java
- android/src/com/mapswithme/maps/purchase/PlayStoreBillingManager.java
https://jira.mail.ru/browse/MAPSME-8649
> [android] Added careful handling of play store connection failure

- android/src/com/mapswithme/util/Constants.java
https://jira.mail.ru/browse/MAPSME-8515
> [android] incorrect rating constant is changed

- data/categories.txt
- добавила синонимы из пользовательских запросов
- убрала синонимы "магазин" и "развлечения" у объектов, которые входят в соответсвующие категории
- взяла на себя смелость убрать бордель из категории "развлечения" -- запрос довольно безобидный, думаю не стоит на него показывать бордели, пусть конкретизируют, если надо
> [search] Categories: new synonyms & minor

- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/Common/Statistics/Statistics.mm
https://jira.mail.ru/browse/MAPSME-8605
> [iOS] disable third party tracking sdk when "Limit ad tracking" 

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalActivationCallback.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPaymentState.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseCallback.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
https://jira.mail.ru/browse/MAPSME-8671
> [android] Added PP closing after ads removal purchase is successful

- iphone/Maps/Common/Statistics/StatisticsStrings.h
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.h
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.mm
- iphone/Maps/Core/Subscriptions/SubscriptionManager.swift
- iphone/Maps/UI/Ads/AdBanner.swift
- iphone/Maps/UI/Ads/AdBanner.xib
- iphone/Maps/UI/Ads/RemoveAdsViewController.swift
https://jira.mail.ru/browse/MAPSME-8616
> [iOS] ads removal stats

- generator/osm2type.cpp
- generator/osm2type.hpp
Планирую внести изменения в этот файл. Это предварительный реквест с clang-format и мелкими стилевыми правками, чтобы не смешивать с содержательными изменениями.
> [generator] osm2type.cpp clang-format & style.

- android/src/com/mapswithme/maps/SplashActivity.java
- android/src/com/mapswithme/maps/analytics/ExternalLibrariesMediator.java
- android/src/com/mapswithme/maps/analytics/MyTrackerEventLogger.java
- android/src/com/mapswithme/util/LocationUtils.java
- android/src/com/mapswithme/util/PermissionsUtils.java
https://jira.mail.ru/browse/MAPSME-8675
> [android] Added Mytracker configure location methods call

- android/build.gradle
- android/src/com/mapswithme/maps/analytics/LibnotifyEventLogger.java
https://jira.mail.ru/browse/MAPSME-8648
> [android] Updated libnotify

- android/build.gradle
- android/src/com/mapswithme/maps/analytics/LibnotifyEventLogger.java
https://github.com/mapsme/omim/pull/9574
> Release chpick

- generator/generator_tests/osm_type_test.cpp
- generator/osm2type.cpp
cherry-pick https://github.com/mapsme/omim/pull/9572 и https://github.com/mapsme/omim/pull/9575 на релиз, чтобы кухни были лучше обработаны при сборке данных для минорки.
>  [generator][RELEASE ONLY] Split cuisine tag.

- generator/generate_info.hpp
- generator/generator_tool/generator_tool.cpp
- generator/popular_places_section_builder.cpp
- generator/popular_places_section_builder.hpp
- generator/world_map_generator.hpp
- tools/unix/generate_planet.sh
добавление достопримечательностей в world
> [search][generator]Add popular places to world

- android/src/com/mapswithme/maps/analytics/ExternalLibrariesMediator.java
https://jira.mail.ru/browse/MAPSME-8687
> [android] Fixed double initilization of libnotify crash

- android/src/com/mapswithme/maps/location/TrackRecorderWakeService.java
https://jira.mail.ru/browse/MAPSME-8695
> Mapsme 8695 fix given work is not active jobintentservice

- iphone/Maps/Classes/MapsAppDelegate.mm
- iphone/Maps/maps.me dbg.entitlements
https://jira.mail.ru/browse/MAPSME-8680
> [iOS] fix universal links

- editor/osm_editor.cpp
https://jira.mail.ru/browse/MAPSME-8669
> Fixed crash on edits uploading

- android/res/layout/place_page_banner_content.xml
- android/res/values/colors.xml
- android/src/com/mapswithme/maps/widget/placepage/BannerController.java
https://jira.mail.ru/browse/MAPSME-8694
https://jira.mail.ru/browse/MAPSME-8690
> Mapsme 8690 red cross on banner

- android/res/layout/item_bookmark.xml
- android/res/values/styles.xml
https://jira.mail.ru/browse/MAPSME-8698
> Mapsme 8698 fix bookmark name truncating

- iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-8700
> [iOS] fix bottom menu appearance

- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
- iphone/Maps/Core/Routing/MWMRouter.h
- iphone/Maps/Core/Routing/MWMRouter.mm
https://jira.mail.ru/browse/MAPSME-8691
> [iOS] don't show tips'n'tricks when in routing mode

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
https://jira.mail.ru/browse/MAPSME-8489
> [iOS] fix open catalog event

- android/AndroidManifest.xml
- android/build.gradle
- android/res/xml/file_paths.xml
- android/src/com/mapswithme/util/sharing/LocalFileShareable.java
https://jira.mail.ru/browse/MAPSME-7898
> [android] Fixed sharing boomarks from external storage

- base/timer.cpp
- base/timer.hpp
- data/categories_cuisines.txt
- generator/generator_tests_support/test_mwm_builder.cpp
- generator/generator_tests_support/test_mwm_builder.hpp
- generator/generator_tests_support/test_with_custom_mwms.cpp
- generator/generator_tests_support/test_with_custom_mwms.hpp
- indexer/ftypes_matcher.cpp
- indexer/ftypes_matcher.hpp
- platform/mwm_traits.cpp
- platform/mwm_traits.hpp
- platform/mwm_version.cpp
- search/CMakeLists.txt
- search/categories_cache.cpp
- search/categories_cache.hpp
- search/cuisine_filter.cpp
- search/cuisine_filter.hpp
- search/geocoder.cpp
- search/geocoder.hpp
- search/geocoder_context.hpp
- search/processor.cpp
- search/processor.hpp
- search/search_integration_tests/processor_test.cpp
- xcode/search/search.xcodeproj/project.pbxproj
реквест поверх 
https://github.com/mapsme/omim/pull/9447
планирую в рамках этого реквеста ещё написать тесты и собрать данные о скорость работы со старыми картами с включенным обращением к метадате и с новыми с выключенным обращением к метадате.
если окажется что метадата работает слишком медленно, то применять фильтры только при свежей версии данных
> [search] Add simple cuisine filter

- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.h
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.mm
- iphone/Maps/Core/Subscriptions/SubscriptionManager.swift
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/Settings/Cells/SettingsTableViewSelectableProgressCell.swift
- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
- iphone/Maps/UI/Storyboard/Settings.storyboard
https://jira.mail.ru/browse/MAPSME-8704
> [iOS] add restore subscription to settings

- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-8414
> [iOS] open hotel reviews, more info, etc. in booking app (if installed)

- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
- iphone/Maps/Classes/EAGLView.h
- iphone/Maps/Classes/MapViewController.h
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Classes/MapsAppDelegate.mm
https://jira.mail.ru/browse/MAPSME-8692
> [iOS] don't show tips'n'tricks when launched by deeplink

- iphone/Maps/Classes/MapViewController.mm
https://jira.mail.ru/browse/MAPSME-8673
> [iOS] hide place page after purchase complete

- android/src/com/mapswithme/maps/maplayer/ToggleMapLayerDialog.java
https://jira.mail.ru/browse/MAPSME-8476
> [android] Fixed commit fragment transaction

- generator/camera_node_processor.cpp
Добавил координаты камер с плохими данными в логи генератора
> [generator] add more logs about speed of camera

- iphone/Maps/TipsAndTricks/TutorialBlurView.swift
https://jira.mail.ru/browse/MAPSME-8711
disable blur on iOS 9 and workaround layout issue on iOS 9-10
> [iOS] fix tips'n'tricks layout on older iOS versions

- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/MWMPPPreviewLayoutHelper.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/PPPReview.swift
- iphone/Maps/UI/PlacePage/UGCViewModel/MWMUGCViewModel.h
- iphone/Maps/UI/PlacePage/UGCViewModel/MWMUGCViewModel.mm
https://jira.mail.ru/browse/MAPSME-8654
> [iOS] fix review info on place page

- android/jni/com/mapswithme/maps/SearchEngine.cpp
https://jira.mail.ru/browse/MAPSME-8471
> [android] Fixed initialization lan and lon for search items - p2p mode

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
https://jira.mail.ru/browse/MAPSME-8540
> [android] Fixed local references overflow on bookmark categories screen

- android/src/com/mapswithme/maps/SplashActivity.java
https://jira.mail.ru/browse/MAPSME-8686
> [android] Added manual launch tracking for mytracker sdk

- iphone/Maps/UI/AvailableArea/AvailableArea.swift
https://jira.mail.ru/browse/MAPSME-8744
> [iOS] fix map controls layout

- 3party/jansson/myjansson.hpp
- generator/CMakeLists.txt
- generator/generator_tool/generator_tool.cpp
- generator/geo_objects/geo_objects.cpp
- generator/geo_objects/geo_objects.hpp
- indexer/indexer_tests/locality_index_test.cpp
- indexer/locality_index.hpp
Добавлена генерация кв для домов с адресом.
> [generator] Geo objects kv 2

- iphone/Maps/Classes/MapsAppDelegate.mm
https://jira.mail.ru/browse/MAPSME-8755
> [iOS] fix open shared bookmarks

- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
- iphone/Maps/Core/Bookmarks/MWMBookmarksObserver.h
https://jira.mail.ru/browse/MAPSME-8764
> [iOS] fix crash when restoring bookmarks

- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-8563
> [android] Added refresh bookmark btn state after bookmark click

- android/jni/com/mapswithme/maps/SearchEngine.cpp
- android/src/com/mapswithme/maps/search/SearchAdapter.java
- android/src/com/mapswithme/maps/search/SearchResult.java
- indexer/map_object.cpp
- indexer/map_object.hpp
- iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
- map/place_page_info.cpp
- search/intermediate_result.cpp
- search/result.hpp
Добавила коды аэропортов (SVO, VKO и т.п.) в placepage и в отображение результатов поиска. Сами коды появятся в данных после перегенерации карты.
> [android][ios] Display airport IATA code on place page and in search results.

- 3party/jansson/myjansson.hpp
- generator/feature_builder.hpp
- generator/feature_sorter.cpp
- generator/generator_tool/generator_tool.cpp
- generator/geo_objects/geo_objects.cpp
- generator/geo_objects/geo_objects.hpp
- generator/locality_sorter.cpp
- generator/locality_sorter.hpp
- indexer/locality_index.hpp
- platform/platform.cpp
- platform/platform.hpp
Сделана последняя часть генерации key-value для geo objects. Можно смотреть, сильно ничего меняться не будет, но пока не нужно мержить, я хочу немного потестировать.
> [generator] Geo objects kv 3

- generator/translator_planet.cpp
> Adding todo about investigation to obtain city and town boundaries if they mapped without tag place.

- 3party/jansson/myjansson.hpp
- generator/feature_builder.cpp
- generator/feature_builder.hpp
- generator/geo_objects/geo_objects.cpp
- generator/locality_sorter.cpp
Теперь "пустые" дома(без адреса) будут добавляться в kv и индекс. В json в house будет записан null.
> [generator] Added empty houses processing.

- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- data/mixed_nodes.txt
- map/framework.cpp
- map/framework.hpp
cherry-pick https://github.com/mapsme/omim/pull/9686
> Partners 84 cherry

- generator/generator_tests_support/test_mwm_builder.cpp
- generator/generator_tool/generator_tool.cpp
- generator/translator_planet.cpp
- indexer/ftypes_matcher.hpp
cherry-pick https://github.com/mapsme/omim/pull/9666
> [release 84] Generating city_roads section based on cities, town and villages.

- iphone/Maps/UI/Authorization/AuthorizationViewController.swift
- iphone/Maps/UI/Authorization/AuthorizationViewController.xib
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/5bc067c3f8b88c29638cdfd5?time=last-seven-days
> [iOS] fix crash on AutorizationViewController

- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Preview/MWMPPPreviewLayoutHelper.mm
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/5bc07035f8b88c29638da636?time=last-seven-days
> [iOS] fix crash when updating booking data on PP

- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- iphone/Maps/Core/Subscriptions/MWMPurchaseManager.mm
- map/purchase.cpp
- map/purchase.hpp
https://jira.mail.ru/browse/MAPSME-8784
> Added start transaction method

- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
https://jira.mail.ru/browse/MAPSME-8768
> [android] Fixed ads removal monthly saving calculation

- map/tips_api.cpp
- metrics/eye_info.hpp
https://www.fabric.io/mapsme/ios/apps/com.mapswithme.full/issues?time=last-seven-days&event_type=crash&subFilter=state&state=open&build%5B0%5D=8.4.5%20%281%29
> [RELEASE ONLY][tips_api] check and logging are added

- android/jni/com/mapswithme/maps/metrics/UserActionsLogger.cpp
- android/src/com/mapswithme/maps/maplayer/ToggleMapLayerDialog.java
- android/src/com/mapswithme/maps/metrics/UserActionsLogger.java
- android/src/com/mapswithme/maps/tips/AbstractClickInterceptor.java
- android/src/com/mapswithme/maps/tips/TipsApi.java
- coding/serdes_json.hpp
- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
- iphone/Maps/Core/Metrics/MWMEye.h
- iphone/Maps/Core/Metrics/MWMEye.mm
- map/framework.cpp
- map/transit/transit_reader.cpp
- metrics/eye.cpp
- metrics/eye.hpp
- metrics/eye_info.hpp
- metrics/eye_serdes.cpp
- metrics/eye_serdes.hpp
- metrics/eye_storage.cpp
- metrics/eye_storage.hpp
- metrics/metrics_tests/CMakeLists.txt
- metrics/metrics_tests/eye_tests.cpp
- metrics/metrics_tests_support/eye_for_testing.cpp
- metrics/metrics_tests_support/eye_for_testing.hpp
https://jira.mail.ru/browse/MAPSME-8876
> [eye] map object events and subscription mechanism is added to eye.

- data/countries.txt
- data/external_resources.txt
> Revert "[planet] New data from 19.10.2018."

- local_ads/campaign_serialization.cpp
> Local ads release build warning fix.

- android/AndroidManifest.xml
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCatalogController.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadManager.java
- android/src/com/mapswithme/maps/bookmarks/DefaultBookmarkCatalogController.java
- android/src/com/mapswithme/maps/bookmarks/SystemDownloadCompletedService.java
> Mapsme 8807 web view url handling

- platform/platform_tests/downloader_tests/downloader_test.cpp
> Platform test. Removing unused values.

- generator/generator_tests/intermediate_data_test.cpp
> Using WritableDirChanger for camera tests.

- iphone/Maps/Bookmarks/BookmarksVC.mm
- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksDataSource.swift
- iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
- iphone/Maps/Bookmarks/SelectSetVC.mm
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager+Swift.swift
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.h
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
MWMBookmarksManager refactoring
> Bookmarks manager handlers refactoring

- metrics/eye.cpp
- metrics/eye.hpp
- metrics/eye_info.hpp
- metrics/eye_serdes.cpp
- metrics/metrics_tests/eye_tests.cpp
- metrics/metrics_tests_support/eye_for_testing.cpp
- metrics/metrics_tests_support/eye_for_testing.hpp
https://jira.mail.ru/browse/MAPSME-8880
> [eye] events registration + trimming + tests

- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCatalogController.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkDownloadController.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadManager.java
- android/src/com/mapswithme/maps/bookmarks/DefaultBookmarkCatalogController.java
- android/src/com/mapswithme/maps/bookmarks/DefaultBookmarkDownloadController.java
- android/src/com/mapswithme/maps/bookmarks/PaymentDataParser.java
- android/src/com/mapswithme/maps/bookmarks/data/PaymentData.java
- android/src/com/mapswithme/maps/downloader/ChunkTask.java
- android/src/com/mapswithme/util/HttpClient.java
- android/src/com/mapswithme/util/HttpUploader.java
> Mapsme 8807 store meta data for paid route

- android/src/com/mapswithme/maps/scheduling/NativeJobService.java
https://jira.mail.ru/browse/MAPSME-8905
> [android] Fixed crash during logger initialization in NativeJobService

- coding/serdes_json.hpp
- map/CMakeLists.txt
- map/framework.cpp
- map/framework.hpp
- map/framework_light.hpp
- map/map_tests/CMakeLists.txt
- map/map_tests/notification_tests.cpp
- map/notifications/notification_manager.cpp
- map/notifications/notification_manager.hpp
- map/notifications/notification_queue.hpp
- map/notifications/notification_queue_serdes.cpp
- map/notifications/notification_queue_serdes.hpp
- map/notifications/notification_queue_storage.cpp
- map/notifications/notification_queue_storage.hpp
- metrics/eye.cpp
- metrics/eye.hpp
- metrics/eye_info.hpp
- metrics/eye_serdes.cpp
- metrics/eye_storage.cpp
- metrics/metrics_tests/eye_tests.cpp
- metrics/metrics_tests_support/eye_for_testing.cpp
- metrics/metrics_tests_support/eye_for_testing.hpp
- xcode/map/map.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-8881
> Notification manager skeleton

- android/src/com/mapswithme/maps/scheduling/NativeJobService.java
https://github.com/mapsme/omim/pull/9772
> [cherry-pick] [android] Fixed crash during logger initialization in NativeJobService

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalValidationCallback.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseCallback.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseController.java
- android/src/com/mapswithme/maps/purchase/DefaultPurchaseValidator.java
- android/src/com/mapswithme/maps/purchase/PlayStoreBillingManager.java
- android/src/com/mapswithme/maps/purchase/PurchaseFactory.java
- android/src/com/mapswithme/maps/purchase/PurchaseValidator.java
- android/src/com/mapswithme/maps/purchase/ValidationCallback.java
- android/src/com/mapswithme/maps/purchase/ValidationStatus.java
- android/src/com/mapswithme/maps/search/SearchActivity.java
- android/src/com/mapswithme/util/statistics/Statistics.java
> Mapsme 8807 paid routes billing

- map/bookmark_catalog.cpp
Обновил согласно новой документации
> Fixed bookmarks uploading

- android/AndroidManifest.xml
- android/res/layout/fragment_bookmark_payment.xml
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/DefaultBookmarkDownloadController.java
- android/src/com/mapswithme/maps/bookmarks/data/PaymentData.java
- android/src/com/mapswithme/maps/purchase/AbstractPurchaseController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseController.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentActivity.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseController.java
- map/bookmark_catalog.cpp
> Mapsme 8807 activity/fragment skeleton for bookmark puchases

- configure.sh
> Added bookmarks vendor in configure.sh

- android/AndroidManifest.xml
- android/res/layout/fragment_ugc_route_send_link.xml
- android/res/values/strings.xml
- android/src/com/mapswithme/maps/ugc/route/SendLinkPlaceholderActivity.java
- android/src/com/mapswithme/maps/ugc/route/SendLinkPlaceholderFragment.java
https://jira.mail.ru/browse/MAPSME-8808 
Здоровую картинку поменяем позже, пока нет сорцов для нее
> [android] Added send me link placeholder screen, supported link sharing

- android/jni/com/mapswithme/maps/PrivateVariables.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/PrivateVariables.java
- android/src/com/mapswithme/maps/purchase/AbstractPurchaseController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseController.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseController.java
- android/src/com/mapswithme/maps/purchase/DefaultPurchaseValidator.java
- android/src/com/mapswithme/maps/purchase/PurchaseFactory.java
- android/src/com/mapswithme/maps/purchase/PurchaseValidator.java
> [android] Generilized validation logic for all purchase controllers

- android/src/com/mapswithme/maps/bookmarks/BookmarkDownloadController.java
- android/src/com/mapswithme/maps/bookmarks/DefaultBookmarkDownloadController.java
- android/src/com/mapswithme/maps/dialog/ProgressDialogFragment.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentState.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseCallback.java
- android/src/com/mapswithme/maps/purchase/PurchaseStateActivator.java
- android/src/com/mapswithme/maps/purchase/StatefulPurchaseCallback.java
> [android] Added start transaction logic and payment state skeleton

- iphone/Maps/UI/Storyboard/Welcome.storyboard
> Add UI ID's for Welcome.storyboard

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/purchase/AbstractPurchaseController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseControllerProvider.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentState.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseCallback.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseController.java
- android/src/com/mapswithme/maps/purchase/PurchaseCallback.java
- android/src/com/mapswithme/maps/purchase/PurchaseFactory.java
- android/src/com/mapswithme/maps/search/SearchActivity.java
[android] Implemented bookmark payment state stubs
> [android] Generalized billing purchase callback

- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/purchase/AbstractPurchaseController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseController.java
- android/src/com/mapswithme/maps/purchase/BillingManager.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentState.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseController.java
- android/src/com/mapswithme/maps/purchase/ConsumePurchaseRequest.java
- android/src/com/mapswithme/maps/purchase/DefaultPurchaseValidator.java
- android/src/com/mapswithme/maps/purchase/PlayStoreBillingCallback.java
- android/src/com/mapswithme/maps/purchase/PlayStoreBillingManager.java
- android/src/com/mapswithme/maps/purchase/PurchaseFactory.java
- android/src/com/mapswithme/maps/purchase/ValidationCallback.java
> [android] Implemented bookmark purchase consumption

- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkCategory.java
- android/src/com/mapswithme/maps/ugc/routes/UgcRouteEditSettingsFragment.java
https://jira.mail.ru/browse/MAPSME-8808
> [android] Supported menu actions for each access rules

- android/AndroidManifest.xml
- android/res/layout/fragment_ugc_routes_properties.xml
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- android/src/com/mapswithme/maps/bookmarks/data/CatalogCustomProperty.java
- android/src/com/mapswithme/maps/bookmarks/data/CatalogCustomPropertyOption.java
- android/src/com/mapswithme/maps/bookmarks/data/CatalogPropertyOptionAndKey.java
- android/src/com/mapswithme/maps/ugc/routes/UgcRoutePropertiesActivity.java
- android/src/com/mapswithme/maps/ugc/routes/UgcRoutePropertiesFragment.java
- android/src/com/mapswithme/maps/ugc/routes/UgcRouteSharingOptionsActivity.java
- android/src/com/mapswithme/maps/ugc/routes/UgcRouteTagsActivity.java
- android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
https://jira.mail.ru/browse/MAPSME-8808
> [android] Started supporting category custom props functionality

- base/fifo_cache.hpp
> [base] small refact

- map/bookmark_catalog.cpp
> [core] compile fix

- xcode/generator/generator.xcodeproj/project.pbxproj
- xcode/generator_tool/generator_tool.xcodeproj/project.pbxproj
> [generator] xcode build fix.

- map/framework.cpp
- map/framework.hpp
- map/framework_light.hpp
- map/map_tests/notification_tests.cpp
- map/notifications/notification_manager.cpp
- map/notifications/notification_manager.hpp
- map/notifications/notification_queue.hpp
- metrics/eye.cpp
- metrics/eye.hpp
- metrics/eye_info.hpp
- ugc/api.cpp
- ugc/api.hpp
https://jira.mail.ru/browse/MAPSME-8926
> [notifications] ugc rate notification business logic

- routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp
@vmihaylenko @maksimandrianov PTAL ASAP
> Routing quality test fix for maps 181030

- data/countries.txt
- tools/python/hierarchy_to_countries.py
Доаблен расчет sha1. Обновлен countries.txt.
Предлагаю делать проверки поверх этого реквеста и если все сойдется, то смержить его.
> [DNM][generator] Added calculation sha1.

- android/AndroidManifest.xml
https://jira.mail.ru/browse/MAPSME-8808
> [android] Added activity labels

- iphone/Maps/Bookmarks/BookmarksVC.mm
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.h
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
https://jira.mail.ru/browse/MAPSME-8406
> [ios] put user's shared category to "my" tab

- android/res/layout/bookmark_payment_layout.xml
- android/src/com/mapswithme/maps/base/BaseMwmFragment.java
- android/src/com/mapswithme/maps/base/Detachable.java
- android/src/com/mapswithme/maps/base/Savable.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkDownloadController.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkDownloadReceiver.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/DefaultBookmarkDownloadController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentActivity.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentState.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseController.java
- android/src/com/mapswithme/maps/purchase/ProductDetails.java
- android/src/com/mapswithme/maps/purchase/PurchaseUtils.java
- android/src/com/mapswithme/maps/purchase/StatefulPurchaseCallback.java
> Mapsme 8807 bookmark payment fragment ui

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesActivity.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesPagerFragment.java
- android/src/com/mapswithme/maps/bookmarks/BookmarkDownloadController.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/bookmarks/DefaultBookmarkDownloadController.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPaymentState.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseController.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentActivity.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentFragment.java
- android/src/com/mapswithme/maps/purchase/BookmarkPurchaseController.java
- android/src/com/mapswithme/maps/routing/NavigationController.java
- android/src/com/mapswithme/util/statistics/Statistics.java
[android] Added purchase id parameter to ads removal and paid routes statistic
> [android] Added paid routes statistics and deeplink

- android/UnitTests/build.gradle
- android/build.gradle
> [android] To Gradle 3.2.1

- indexer/indexer_tests/locality_index_test.cpp
- indexer/locality_index.hpp
Не прерываем вызов ForClosestToPoint в середине обработки ячейки, т.к. внутри ячейки мы не можем понять какой объект ближе.
> [indexer] Do not stop ForClosestToPoint at the middle of cell processing.

- .gitignore
- android/jni/com/mapswithme/maps/metrics/UserActionsLogger.cpp
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- android/src/com/mapswithme/maps/metrics/UserActionsLogger.java
- android/src/com/mapswithme/maps/ugc/UGCEditorActivity.java
- android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
- defines.hpp
- geometry/mercator.hpp
- indexer/feature_data.cpp
- indexer/feature_utils.cpp
- iphone/Maps/UI/PlacePage/MWMPlacePageData.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- map/CMakeLists.txt
- map/framework.cpp
- map/notifications/notification_manager.cpp
- map/place_page_info.cpp
- map/place_page_info.hpp
- map/routing_manager.cpp
- map/routing_manager.hpp
- map/utils.cpp
- map/utils.hpp
- metrics/eye.cpp
- metrics/eye.hpp
- metrics/eye_info.hpp
- metrics/eye_storage.cpp
- ugc/storage.cpp
- xcode/map/map.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-8882
@alexzatsepin и @beloal посмотрите пожалуйста на платформах
> Notifications events

- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift
- iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCViewModel.swift
- iphone/Maps/Bookmarks/Categories/Category settings/CategorySettings.storyboard
- iphone/Maps/Bookmarks/Categories/Category settings/CategorySettingsViewController.swift
- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
- iphone/Maps/Common/MWMTypes.h
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.h
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/Storyboard/Storyboard.swift
https://jira.mail.ru/browse/MAPSME-8851
> [ios] category settings screen

- routing/routing_session.cpp
Remove warning on ubuntu about initializer list
> [routing] Delete warning in routing_session

- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/maps/intent/Factory.java
- android/src/com/mapswithme/maps/scheduling/JobServiceDelegate.java
- android/src/com/mapswithme/util/StorageUtils.java
- android/src/com/mapswithme/util/Utils.java
- android/src/com/mapswithme/util/log/FileLoggerStrategy.java
- android/src/com/mapswithme/util/log/LoggerFactory.java
- android/src/com/mapswithme/util/log/ZipLogsTask.java
https://jira.mail.ru/browse/MAPSME-8905
> Mapsme 8905 fix crash with static application

- iphone/Maps/Classes/MapsAppDelegate.mm
https://jira.mail.ru/browse/MAPSME-8963
> [iOS] mopub grant consent

- android/src/com/mapswithme/maps/analytics/ExternalLibrariesMediator.java
https://jira.mail.ru/browse/MAPSME-8959
> [android] Mopub adjustment

- data/categories.txt
остались фарси и иврит, если появятся переводы.
> [search] Synonyms for new search categories.

- storage/storage_integration_tests/storage_downloading_tests.cpp
Запускаем и прерываем скачивание несколько раз. Проверяем целостность данных после докачки
> [tests] Added downloader integrity test

- android/res/xml/prefs_main.xml
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
- android/src/com/mapswithme/maps/search/SearchCategoriesFragment.java
- android/src/com/mapswithme/maps/search/SearchFragment.java
- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
- android/src/com/mapswithme/maps/widget/placepage/BannerController.java
- android/src/com/mapswithme/util/Config.java
- android/src/com/mapswithme/util/SharedPropertiesUtils.java
- android/src/com/mapswithme/util/statistics/MytargetHelper.java
https://jira.mail.ru/browse/MAPSME-8809
> [android] Added ads removal dialog in settings

- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/LightFramework.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/LightFramework.java
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/MwmApplication.java
- android/src/com/mapswithme/maps/background/NotificationCandidate.java
- android/src/com/mapswithme/maps/background/NotificationChannelProvider.java
- android/src/com/mapswithme/maps/background/NotificationService.java
- android/src/com/mapswithme/maps/background/Notifier.java
- android/src/com/mapswithme/maps/background/OreoCompatNotificationChannelProvider.java
- android/src/com/mapswithme/maps/background/StubNotificationChannelProvider.java
- android/src/com/mapswithme/maps/ugc/EditParams.java
- android/src/com/mapswithme/maps/ugc/UGC.java
- android/src/com/mapswithme/maps/ugc/UGCController.java
- android/src/com/mapswithme/maps/ugc/UGCEditorActivity.java
- android/src/com/mapswithme/util/statistics/Statistics.java
- map/framework.cpp
- map/framework.hpp
- map/notifications/notification_manager.cpp
- map/notifications/notification_queue.hpp
- map/utils.hpp
- metrics/eye.cpp
https://jira.mail.ru/browse/MAPSME-8967
> [android] Show leave review notifications

- android/src/com/mapswithme/maps/widget/ToolbarController.java
https://jira.mail.ru/browse/MAPSME-8964
> [android] Change setTitle for Toolbar to setTitle ActionBar

- generator/world_map_generator.hpp
- tools/unix/generate_planet.sh
Включила добавление достопримечальностей World.
Используется тот же файл что и для сборки секции popularity.
Нужно использовать новый файл от Артёма.
> [generator] Enable adding popular places to World.mwm

- data/mixed_tags.txt
https://confluence.mail.ru/display/MAPSME/Sixt
> [data] Added partner Sixt

- iphone/Maps/Bookmarks/Categories/Category settings/CategorySettingsViewController.swift
- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingFlow.storyboard
- iphone/Maps/Bookmarks/Categories/Sharing/Tags/SharingTagsViewController.swift
- iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.h
- iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm
- iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.h
- iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm
- iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.h
- iphone/Maps/Classes/CustomAlert/DefaultAlert/MWMDefaultAlert.mm
> [ios] Ugc fixes

- iphone/Maps/Bookmarks/BookmarksVC.h
- iphone/Maps/Bookmarks/BookmarksVC.mm
- iphone/Maps/Bookmarks/BookmarksVC.xib
- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
- iphone/Maps/Bookmarks/Categories/Category settings/CategorySettingsViewController.swift
- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- iphone/Maps/Core/Bookmarks/MWMBookmarksObserver.h
- iphone/Maps/Core/Framework/MWMFrameworkHelper.h
- iphone/Maps/Core/Framework/MWMFrameworkHelper.mm
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
https://jira.mail.ru/browse/MAPSME-8850
> [iOS] update bookmarks list screen

- android/src/com/mapswithme/maps/ugc/routes/UgcRoutePropertiesFragment.java
https://jira.mail.ru/browse/MAPSME-9010
> [android] Empty List Props processing

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
https://jira.mail.ru/browse/MAPSME-9002
> [iOS] fixed authorization popup in bookmarks catalog on iPad

- map/bookmark_manager.cpp
Выставляем автора только при загрузке букмарок на сервер
> Fixed bookmarks author setting up

- xcode/generator_tool/generator_tool.xcodeproj/project.pbxproj
Удалил лишнюю директорию из xcode проект генератор.
@maksimandrianov PTAL
> Removing an unnecessary file for generator_tests  xcode project.

- iphone/Maps/Core/InappPurchase/Impl/PaidRoutePurchase.swift
https://jira.mail.ru/browse/MAPSME-9020
> [iOS] fix crash when requesting product info on Paid Route screen

- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/dialog/AlertDialog.java
- android/src/com/mapswithme/maps/purchase/DefaultPurchaseValidator.java
https://jira.mail.ru/browse/MAPSME-9017
> [android] Fixed purchase validation with null server id

- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
- iphone/Maps/Core/Framework/MWMFrameworkHelper.h
- iphone/Maps/Core/Framework/MWMFrameworkHelper.mm
https://jira.mail.ru/browse/MAPSME-8982
https://jira.mail.ru/browse/MAPSME-9014
> [ios] [mapsme-8982] fix no network connection dialog in bookmark sharing

- iphone/Maps/Bookmarks/Categories/Category settings/CategorySettings.storyboard
- iphone/Maps/Bookmarks/Categories/Category settings/CategorySettingsViewController.swift
https://jira.mail.ru/browse/MAPSME-8978
> [ios] [mapsme-8978] - disable last category deleting from list settings

- iphone/Maps/3party/MyTarget/MWMMyTarget.mm
- iphone/Maps/Core/Search/MWMSearch.mm
- iphone/Maps/Core/Settings/MWMSettings.h
- iphone/Maps/Core/Settings/MWMSettings.mm
- iphone/Maps/UI/Ads/RemoveAdsViewController.swift
- iphone/Maps/UI/Ads/RemoveAdsViewController.xib
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/Settings/Cells/SettingsTableViewSwitchCell.swift
- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
https://jira.mail.ru/browse/MAPSME-8855
> [iOS] remove ads subscription in settings

- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingFlow.storyboard
https://jira.mail.ru/browse/MAPSME-8974
> [ios] fix edit on web screen layout

- android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
https://jira.mail.ru/browse/MAPSME-9063
> [android] Fix sharing scheme

- iphone/Maps/Bookmarks/BookmarksVC.mm
- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
https://jira.mail.ru/browse/MAPSME-9023
https://jira.mail.ru/browse/MAPSME-8410
> [ios] disable 'export as file' option for shared categories

- iphone/Maps/Bookmarks/Categories/Categories/BMCCategoryCell.swift
https://jira.mail.ru/browse/MAPSME-9022
> [ios] [mapsme-9022] fix loc keys for access status

- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
https://jira.mail.ru/browse/MAPSME-9072
> [ios] [mapsme-9072] fix no internet alert when sharing category

- android/src/com/mapswithme/maps/bookmarks/data/BookmarkCategory.java
https://jira.mail.ru/browse/MAPSME-9079
> [android] Changed strings

- android/res/values/donottranslate.xml
- android/res/values/string-arrays.xml
- android/res/xml/prefs_main.xml
- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
https://jira.mail.ru/browse/MAPSME-8815
> Mapsme 8815 speed cameras

- iphone/Maps/Bookmarks/Catalog/CatalogWebViewController.swift
- iphone/Maps/Bookmarks/Catalog/PaidRouteViewController.swift
Do not require author name in catalog deeplink
> [iOS] fix deeplinks to catalog

- android/src/com/mapswithme/maps/discovery/ItemType.java
- iphone/Maps/UI/Discovery/MWMDiscoveryController.mm
https://jira.mail.ru/browse/MAPSME-9084
> [discovery] Fix discovery search more cafes string

- routing/routing_integration_tests/route_test.cpp
- routing/routing_integration_tests/turn_test.cpp
- routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp
- routing/routing_quality/routing_quality_tests/passby_roads_tests.cpp
cherry-pick https://github.com/mapsme/omim/pull/9973
@maksimandrianov PTAL
> [master][routing] Fixing test for 181124 maps.

- map/bookmark_catalog.cpp
Добавили локаль в соответствии с документом
https://confluence.mail.ru/display/MAPSME/Bookmarks+catalogue#Bookmarkscatalogue-Uploadthekmltotheserver
> Added locale for bookmarks uploading

- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseDialog.java
- android/src/com/mapswithme/maps/purchase/QueryProductDetailsRequest.java
https://jira.mail.ru/browse/MAPSME-9092
> [android] Added subscription period validation

- iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm
https://jira.mail.ru/browse/MAPSME-9097
https://jira.mail.ru/browse/MAPSME-9098
> [iOS] fix tips'n'tricks layout issues

- base/string_utils.cpp
- base/string_utils.hpp
- feature_list/feature_list.cpp
- generator/CMakeLists.txt
- generator/descriptions_section_builder.cpp
- generator/descriptions_section_builder.hpp
- generator/extract_addr/extract_addr.cpp
- generator/generator_tests/CMakeLists.txt
- generator/generator_tests/descriptions_section_builder_tests.cpp
- generator/generator_tool/CMakeLists.txt
- generator/generator_tool/generator_tool.cpp
- generator/osm_element_helpers.cpp
- generator/wiki_url_dumper.cpp
- generator/wiki_url_dumper.hpp
- indexer/ftypes_matcher.cpp
- indexer/ftypes_matcher.hpp
- indexer/indexer_tests/checker_test.cpp
- platform/platform.cpp
- platform/platform.hpp
- platform/platform_tests/platform_test.cpp
- platform/platform_tests_support/scoped_mwm.hpp
- tools/python/descriptions_downloader.py
- tools/unix/generate_planet.sh
Что бы добавить новую секцию нужно:
1) generator_tool --intermediate_data_path=path/to/intermediate_data --user_resource_path=path/to/omim/data --dump_wikipedia_urls=path/to/wiki_urls.txt - выгрузить список url.
2) python omim/tools/python/descriptions_downloader.py --i=path/to/wiki_urls.txt path/to/pages_dir - скачать страницы wikipedia с помощью wikipedia api в pages_dir
3) generator_tool --wikipedia_pages=path/to/wiki_urls.txt path/to/pages_dir --user_resource_path=path/to/omim/data --data_path=path/to/mwm --output=mwm_name  - добавить секцию в mwm_name
или воспользоваться скриптом generate_planet.sh с новой опцией -d
Для Артема:
Для https://en.wikipedia.org/wiki/Fran%C3%A7ois_Capois
Пример запроса к api википедия: https://en.wikipedia.org/w/api.php?action=query&prop=extracts&titles=Fra …
> [generator] Added wikipedia descriptions generation.

- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
https://jira.mail.ru/browse/MAPSME-9151
> [android] Added auth token for bookmarks catalog

- android/jni/com/mapswithme/maps/PrivateVariables.cpp
- android/src/com/mapswithme/maps/PrivateVariables.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksCatalogFragment.java
- android/src/com/mapswithme/maps/purchase/AdsRemovalPurchaseController.java
- android/src/com/mapswithme/maps/purchase/PlayStoreBillingManager.java
- android/src/com/mapswithme/maps/purchase/PurchaseCallback.java
- android/src/com/mapswithme/maps/purchase/PurchaseFactory.java
- android/src/com/mapswithme/maps/purchase/SubscriptionPlayStoreBillingManager.java
- android/src/com/mapswithme/util/Utils.java
- configure.sh
cherry-pick from release-85
https://github.com/mapsme/omim/pull/9994
https://github.com/mapsme/omim/pull/9997
> New product ids supporting cherry pick

- iphone/Maps/Common/WebViewController.mm
https://jira.mail.ru/browse/MAPSME-9150
> [iOS] add auth token to route catalog request

- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingFlow.storyboard
- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
https://jira.mail.ru/browse/MAPSME-9153 
+ remove unnecessary else on "edit on web" showing
> [ios] [mapsme-9153] fix edit on web button localization

- iphone/Maps/Bookmarks/Categories/Category settings/CategorySettings.storyboard
- iphone/Maps/Bookmarks/MWMCategoryInfoCell.xib
https://jira.mail.ru/browse/MAPSME-9140
> [ios] [mapsme-9140] fix category settings & bookmarks list in night mode

- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
https://jira.mail.ru/browse/MAPSME-9147
> [ios] [mapsme-9147] fix login popup in sharing options screen for ipad

- android/res/layout/fragment_ugc_routes_sharing_options.xml
https://jira.mail.ru/browse/MAPSME-9167
> [android] Fixed inflating color selector

- android/jni/com/mapswithme/maps/SearchEngine.cpp
- android/jni/com/mapswithme/platform/Localization.cpp
- android/src/com/mapswithme/maps/search/SearchAdapter.java
- android/src/com/mapswithme/maps/search/SearchResult.java
- android/src/com/mapswithme/util/Utils.java
- iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
- platform/localization.hpp
- platform/localization.mm
- platform/localization_dummy.cpp
- search/intermediate_result.cpp
- search/result.hpp
Отображение названия бренда в результатах поиска (там же где тип, кухня и т.п.).
Если есть и бренд и кухня, бренд может отображаться вместе с кухней ("Макдоналдс • Бургеры")
> [search][ios][android] Display brand name in search results

- base/string_utils.cpp
- base/string_utils.hpp
- generator/CMakeLists.txt
- generator/brands_loader.cpp
- generator/brands_loader.hpp
- generator/emitter_planet.cpp
- generator/emitter_planet.hpp
- generator/generate_info.hpp
- generator/generator_tests/CMakeLists.txt
- generator/generator_tests/brands_loader_test.cpp
- generator/generator_tool/generator_tool.cpp
- generator/search_index_builder.cpp
- search/ranker.cpp
- search/search_integration_tests/processor_test.cpp
- xcode/generator/generator.xcodeproj/project.pbxproj
реквест поверх https://github.com/mapsme/omim/pull/9946
> [generator][search] Brands part 2.

- generator/descriptions_section_builder.hpp
- generator/generator_tool/generator_tool.cpp
- tools/python/descriptions_downloader.py
- tools/unix/generate_planet.sh
Добавил:
поддержку фильтра языков на уровне скрипта
удаление ненужных секций(Ссылки и т.д.).
удаление пробельных символов между тэгами. 
удаление тегов, которые не содержат текста.
для Москвы
LOG TID(1) INFO     0.102408 generator/descriptions_section_builder.hpp:130 Build() Found 727 pages for /home/andrianov/Projects/MOSCOW/Russia_Moscow.mwm
LOG TID(1) INFO      0.10281 generator/descriptions_section_builder.hpp:131 Build() Total size of added pages (before writing to section): 12001419
LOG TID(1) INFO      1.84743 generator/descriptions_section_builder.hpp:144 Build() Section descriptions is built for /home/andrianov/Projects/MOSCOW/Russia_Moscow.mwm
LOG TID(1) INFO      1.84747 generator/descriptions_section_builder.hpp:145 Build() Language statistics - en:222 ru:727 es:101 …
> [generator] Descriptions improvements

- iphone/Maps/Bookmarks/BookmarksVC.mm
https://jira.mail.ru/browse/MAPSME-9216
> [iOS] fix "more" menu in bookmarks list on iPad

- android/build.gradle
https://issuetracker.google.com/issues/120759347
> Temp fix google issue jcentr libs

- data/countries.txt
- data/external_resources.txt
Откат данных на версию 181030.
@tatiana-yan , @rokuz , @bykoianko Пожалуйста, проверьте свои изменения, что бы все работало на этих данных
> [RELEASE-ONLY][planet] Planet revert

- search/localities_source.cpp
- search/search_tests/localities_source_tests.cpp
DNM до вливания реквеста @maksimandrianov про откат на данные 8.4.
> [RELEASE_ONLY][search] Revert LocalitiesSource fix for 8.4 data compatibility.

- routing/routing_integration_tests/speed_camera_notifications_tests.cpp
- routing/routing_session.hpp
- routing/speed_camera_manager.cpp
- routing/speed_camera_manager.hpp
Увеличил константу `kTimeForDecision` - из-за нее увеличивается интервал для `VoiceNotification`. Увеличил `kBeepSignalTime` - из-за нее увеличивается зона для `BeepSignal`
> [routing] add more time for making notifications for camera

- routing/speed_camera_manager.hpp
> [routing] Comment fix.

- data/mixed_tags.txt
Изменен объект пина в соотвествии с https://confluence.mail.ru/display/MAPSME/McArthurGlen+Outlets
> [sponsored] Changed pin object for McArthurGlenOutlets

- iphone/Maps/Bridging-Header.h
- iphone/Maps/Core/Location/GeoTracker/Geo.swift
- iphone/Maps/Core/Location/GeoTracker/IGeoTracker.swift
- iphone/Maps/Core/Location/GeoTracker/IMWMGeoTrackerCore.h
- iphone/Maps/Core/Location/GeoTracker/IMWMGeoTrackerZone.h
- iphone/Maps/Core/Location/GeoTracker/Impl/GeoTracker.swift
- iphone/Maps/Core/Location/GeoTracker/Impl/GeoZoneTracker.swift
- iphone/Maps/Core/Location/GeoTracker/Impl/MWMGeoTrackerCore.h
- iphone/Maps/Core/Location/GeoTracker/Impl/MWMGeoTrackerCore.mm
- iphone/Maps/Core/Location/MWMLocationManager.mm
- iphone/Maps/LocalizedStrings/en.lproj/InfoPlist.strings
- iphone/Maps/Maps.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-8788
> [iOS] geo tracking

- iphone/Maps/Classes/MapViewController.h
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Common/WebViewController.mm
- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/PlacePage/MWMPlacePageButtonsProtocol.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/DescriptionCell/MWMPlaceDescriptionCell.h
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/DescriptionCell/MWMPlaceDescriptionCell.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/DescriptionCell/MWMPlaceDescriptionCell.xib
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
> [ios] place description

- android/gradle.properties
> [android] Set version 8.5.4

- map/bookmark_manager.cpp
https://jira.mail.ru/browse/MAPSME-9241
>  Reset last edited category after its uploading to the catalog.

- iphone/Maps/UI/PlacePage/MWMPlacePageData.h
https://jira.mail.ru/browse/MAPSME-9243
> [ios] [mapsme-9243] fix crash when saving place to bookmarks

- android/res/values/themes-base.xml
https://jira.mail.ru/browse/MAPSME-9086
> [android] Fixed sharing options screen dark theme

- drape/metal/metal_base_context.mm
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/5c16a62bf8b88c296311d4a0?time=last-thirty-days
> [Metal] Fixed crash on entering background

- android/src/com/mapswithme/maps/ugc/routes/UgcRouteTagsFragment.java
https://jira.mail.ru/browse/MAPSME-9138
> [android] Processed orientation change - invalidate options menu call

- map/bookmark_manager.cpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5c13f77ef8b88c2963d5abca
> Fixed crash after uploading a bookmark category to the catalog.

- data/faq.html
> [faq] December hotfix

- android/src/com/mapswithme/maps/bookmarks/PlaceDescriptionFragment.java
https://confluence.mail.ru/display/MAPSME/Description+v1
> [android] Added wiki source

- map/framework.cpp
- search/reverse_geocoder.cpp
https://jira.mail.ru/browse/MAPSME-4524
> [editor] Show nearby features list for created features.

- data/countries.txt
- data/external_resources.txt
http://maps-archive1.p.smailru.net/181213/
> [planet] New data from 13.12.2018 (hotels:164308)

- map/notifications/notification_manager.cpp
https://jira.mail.ru/browse/MAPSME-9311
> [notifications] fix incorrect processing UgcSaved event type.

- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/Framework.hpp
- android/src/com/mapswithme/maps/Framework.java
- map/CMakeLists.txt
- map/framework.cpp
- map/framework.hpp
- map/map_tests/CMakeLists.txt
- map/map_tests/power_manager_tests.cpp
- map/power_manager/power_manager.cpp
- map/power_manager/power_manager.hpp
https://jira.mail.ru/browse/MAPSME-9298
> [core][jni] power manager mock

- android/res/menu/menu_bookmark_categories.xml
- android/res/menu/menu_catalog_bookmark_categories.xml
https://jira.mail.ru/browse/MAPSME-9127
> [android] Change string

- search/ranker.cpp
https://jira.mail.ru/browse/MAPSME-9342
> [search] Added search results count check before emitment

- android/src/com/mapswithme/maps/MwmActivity.java
https://jira.mail.ru/browse/MAPSME-9342
> [android] Fixed filter button visibility update on map screen

- iphone/Maps/Bookmarks/BookmarksVC.mm
https://jira.mail.ru/browse/MAPSME-9336
> [iOS] fix popover menu on bookmarks list screen

- routing/async_router.cpp
- routing/routing_integration_tests/route_test.cpp
- routing_common/maxspeed_conversion.cpp
cherry-pick https://github.com/mapsme/omim/pull/10152
> [routing] ETA fix for maxspeed=none.

- drape_frontend/base_renderer.cpp
Cherry pick https://github.com/mapsme/omim/pull/10149
> [drape][android] Fixed message filtering on context restoring

- drape_frontend/backend_renderer.cpp
- drape_frontend/backend_renderer.hpp
- drape_frontend/base_renderer.hpp
- drape_frontend/frontend_renderer.cpp
Cherry pick https://github.com/mapsme/omim/pull/10175
> [Metal] Fixed memory leaks on Metal

- drape_frontend/frontend_renderer.cpp
cherry pick https://github.com/mapsme/omim/pull/10178
> [drape] Fixed rendering statistics

- map/notifications/notification_manager.cpp
https://jira.mail.ru/browse/MAPSME-9386
> [notifications] Show notifications every day!

- map/framework.cpp
- map/notifications/notification_manager.cpp
- map/notifications/notification_manager.hpp
https://jira.mail.ru/browse/MAPSME-9392
> [notifications] Statistic event is added.

- android/src/com/mapswithme/maps/bookmarks/Holders.java
https://jira.mail.ru/browse/MAPSME-9398
> [android] Wrap description in html

- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/MwmActivity.java
- iphone/Maps/Classes/MapViewController.h
- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/Classes/MapsAppDelegate.mm
- map/framework.cpp
- map/framework.hpp
https://jira.mail.ru/browse/MAPSME-9374
> [cherry-pick][deep links] process viewport center parameter for search in viewport

- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/Framework.hpp
- map/CMakeLists.txt
- map/framework.cpp
- map/framework.hpp
- map/map_tests/power_manager_tests.cpp
- map/power_management/power_management_schemas.cpp
- map/power_management/power_management_schemas.hpp
- map/power_management/power_manager.cpp
- map/power_management/power_manager.hpp
- xcode/map/map.xcodeproj/project.pbxproj
кого еще добавить в pr - пока не знаю
> [power manager] concrete facilities and levels for auto scheme are added

- iphone/Maps/UI/PlacePage/MWMPlacePageData.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMPlacePageActionBar.h
- iphone/Maps/UI/PlacePage/PlacePageLayout/ActionBar/MWMPlacePageActionBar.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/MWMPlacePageLayout.mm
https://jira.mail.ru/browse/MAPSME-9399
> [ios] [mapsme-9399] allowed to delete and edit shared bookmarks from the place page

- iphone/Maps/UI/Search/MWMSearchManager.mm
this crash introduced after search refactoring
> [ios] fixed crash when rotating device

- routing/cross_mwm_index_graph.hpp
- routing/routing_integration_tests/CMakeLists.txt
- routing/routing_integration_tests/routing_test_tools.cpp
- routing/routing_integration_tests/routing_test_tools.hpp
- routing/routing_integration_tests/transit_route_test.cpp
По мотивам: https://github.com/mapsme/omim/pull/10181
> [routing] Fix crash because of transit cross mwm section

- android/src/com/mapswithme/maps/bookmarks/data/BookmarkCategory.java
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- kml/pykmlib/bindings.cpp
- kml/serdes.cpp
- kml/types.hpp
https://jira.mail.ru/browse/MAPSME-9428
> [KML] Added new access rules AuthorOnly for web edited bookmarks.

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- map/bookmark_catalog.cpp
- map/bookmark_catalog.hpp
- map/bookmark_manager.cpp
https://jira.mail.ru/browse/MAPSME-9332
> [BM] Added web editor link && Fixed bug with bookmarks duplication

- traffic/pytraffic/bindings.cpp
> [traffic] Adding method to remove temporary traffic blocks for selected mwms.

- map/tips_api.cpp
- map/tips_api.hpp
cherry-pick for https://github.com/mapsme/omim/pull/10108
> [cherry-pick][tips] duration fix

- iphone/Maps/Bookmarks/Categories/Sharing/Tags/TagsCollectionViewLayout.swift
- iphone/Maps/UI/Search/Filters/FilterCollectionHolderCell.swift
- iphone/Maps/UI/Search/Filters/FilterTypeCell.swift
- iphone/Maps/UI/Search/Filters/MWMSearchHotelsFilterViewController.mm
- iphone/Maps/UI/Storyboard/SearchFilters.storyboard
> [ios] improved display of hotel types in search by re-using custom layout

- android/src/com/mapswithme/maps/ugc/routes/TagsResFactory.java
https://jira.mail.ru/browse/MAPSME-9410
> [android] Added production colors for tags screen

- routing/cross_mwm_index_graph.hpp
- routing/routing_integration_tests/CMakeLists.txt
- routing/routing_integration_tests/routing_test_tools.cpp
- routing/routing_integration_tests/routing_test_tools.hpp
- routing/routing_integration_tests/transit_route_test.cpp
cherry pick of: https://github.com/mapsme/omim/pull/10185
> [routing] Crash transit succint1 cherry pick

- data/countries.txt
- data/external_resources.txt
@bykoianko не прошли следующие тесты, посмотри, пожалуйста:
pedestrian_route_test.cpp::RussiaTaganrogSyzranov10k3ToLazo5k2
pedestrian_route_test.cpp::CrossMwmKaliningradRegionToLiepaja
turn_test.cpp::GermanyFrankfurtAirport2Test
turn_test.cpp::GermanyRaunheimAirportTest
> [planet] New data from 13.01.2019 (hotels: 166996)

- routing/routing_integration_tests/route_test.cpp
> [routing] Add test for route=shuttle_train

- map/notifications/notification_manager.hpp
https://jira.mail.ru/browse/MAPSME-9415
> [notifications] Do not disturb from 9p.m. to 10 a.m.

- iphone/Maps/Maps.xcodeproj/project.pbxproj
- iphone/Maps/UI/Settings/MWMPowerManagmentViewController.h
- iphone/Maps/UI/Settings/MWMPowerManagmentViewController.mm
- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
- iphone/Maps/UI/Storyboard/Settings.storyboard
https://jira.mail.ru/browse/MAPSME-9422
> [ios][power_managment] settings UI

- android/src/com/mapswithme/maps/dialog/AlertDialog.java
- android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
https://jira.mail.ru/browse/MAPSME-9410
> [android] Added potential dialogs

- android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
https://jira.mail.ru/browse/MAPSME-9504
> [android][ugc] show toast went review is submitted.

- routing/index_router.cpp
- routing/index_router.hpp
там просочилась бесполезная функция, которая перекладывала один аргумент в другой
> [routing] delete useless functions

- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/UGC/UGCAddReview/UGCAddReviewController.swift
https://jira.mail.ru/browse/MAPSME-9504
> [ios][ugc] show toast when review is submitted.

- coding/string_utf8_multilang.cpp
- coding/string_utf8_multilang.hpp
- generator/CMakeLists.txt
- generator/generator_tests/region_info_collector_tests.cpp
- generator/generator_tests/regions_tests.cpp
- generator/geo_objects/geo_objects.cpp
- generator/place_node.hpp
- generator/regions/city.hpp
- generator/regions/collector_region_info.cpp
- generator/regions/collector_region_info.hpp
- generator/regions/node.cpp
- generator/regions/node.hpp
- generator/regions/region.cpp
- generator/regions/region.hpp
- generator/regions/region_base.cpp
- generator/regions/region_base.hpp
- generator/regions/region_info.cpp
- generator/regions/region_info.hpp
- generator/regions/regions.cpp
- generator/regions/regions_builder.cpp
- generator/regions/regions_builder.hpp
- generator/regions/regions_fixer.cpp
- generator/regions/regions_fixer.hpp
- generator/regions/to_string_policy.cpp
- generator/regions/to_string_policy.hpp
- generator/translator_region.cpp
Добавлена эвристика/аппроксимация городов-точек полигонами.
> [generator] Added approximation regions without a boundary.

- android/jni/com/mapswithme/maps/Framework.cpp
- android/src/com/mapswithme/maps/Framework.java
- android/src/com/mapswithme/maps/search/PromoCategory.java
- iphone/Maps/UI/Search/Tabs/CategoriesTab/SearchCategoriesViewController.swift
- iphone/Maps/UI/Search/Tabs/MWMSearchFrameworkHelper.h
- iphone/Maps/UI/Search/Tabs/MWMSearchFrameworkHelper.mm
- map/framework.cpp
- map/framework.hpp
- partners_api/megafon_countries.cpp
- partners_api/megafon_countries.hpp
https://jira.mail.ru/browse/MAPSME-9501
> [core] Added megafon category banner logic

- drape_frontend/my_position_controller.cpp
Исправлено притягивание к моему местоположению после завершения поиска локации и после перехода по диплинке
> [drape] Fixed my position snapping

- track_analyzing/track_analyzer/cmd_table.cpp
https://github.com/mapsme/omim/pull/10166
изменения связаны с этим пул реквестом
> [track analyzer] Correct usage of none maxspeed and walk maxspeed.

- android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
- map/bookmark_catalog.cpp
- map/bookmark_catalog.hpp
https://jira.mail.ru/browse/MAPSME-9585
> [catalog] Added max tags count retrieving

- routing/index_graph_starter.hpp
- routing/index_graph_starter_joints.cpp
- routing/index_graph_starter_joints.hpp
- routing/single_vehicle_world_graph.cpp
- routing/single_vehicle_world_graph.hpp
- routing/transit_world_graph.cpp
- routing/transit_world_graph.hpp
- routing/world_graph.hpp
По мотивам: https://github.com/mapsme/omim/pull/10265
> [routing] save start and end point

- geocoder/geocoder.cpp
- geocoder/geocoder.hpp
- geocoder/geocoder_tests/geocoder_tests.cpp
- geocoder/index.cpp
- geocoder/index.hpp
> [geocoder] Search locality buildings

- android/res/layout/place_page_banner.xml
- android/res/layout/place_page_banner_content.xml
- android/res/layout/place_page_banner_google.xml
- android/res/layout/place_page_preview.xml
- android/res/values/dimens.xml
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/widget/placepage/BannerController.java
- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-9438
> Mapsme 9438 pp preview banner refactoring

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/bookmarks/CachedBookmarkCategoriesFragment.java
- android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
- android/src/com/mapswithme/maps/ugc/routes/SendLinkPlaceholderFragment.java
- android/src/com/mapswithme/maps/ugc/routes/UgcRoutePropertiesFragment.java
- android/src/com/mapswithme/maps/ugc/routes/UgcRouteTagsFragment.java
- android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
https://jira.mail.ru/browse/MAPSME-9418
> [android] Added tags limit

- android/res/layout/fragment_bookmark_category_restriction.xml
- android/res/layout/fragment_ugc_routes_properties.xml
- android/src/com/mapswithme/maps/ugc/routes/BaseEditUserBookmarkCategoryFragment.java
- android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
https://jira.mail.ru/browse/MAPSME-9418
> Mapsme 9418

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/NavigationButtonsAnimationController.java
- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- android/src/com/mapswithme/util/statistics/PlacePageTracker.java
https://jira.mail.ru/browse/MAPSME-9440
> Mapsme 9440 recover nav button

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/widget/placepage/BannerController.java
- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
- android/src/com/mapswithme/util/statistics/PlacePageTracker.java
- android/src/com/mapswithme/util/statistics/Statistics.java
https://jira.mail.ru/browse/MAPSME-9568
> [android] Recovered and finally fixed place page view tracking statistic

- android/res/layout/fragment_ugc_routes_sharing_options.xml
https://jira.mail.ru/browse/MAPSME-9418
> [android] Removed legacy view

- android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
- android/src/com/mapswithme/util/statistics/Statistics.java
- iphone/Maps/Common/Statistics/StatisticsStrings.h
- iphone/Maps/UI/Settings/MWMPowerManagmentViewController.mm
https://jira.mail.ru/browse/MAPSME-9419
> [android][ios][power managment] statistics

- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageButtonsListener.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-9619
> [android] Added pp moving if bookmark set/unset

- android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
https://jira.mail.ru/browse/MAPSME-9698
> [android] Changed string res id

- map/map_tests/address_tests.cpp
- map/map_tests/bookmarks_test.cpp
- map/notifications/notification_manager_delegate.cpp
- search/city_finder.cpp
- search/city_finder.hpp
- search/locality_finder.hpp
- search/ranker.cpp
- search/ranker.hpp
- search/reverse_geocoder.cpp
https://jira.mail.ru/browse/MAPSME-9664
> [core] GetReadable name is used to translate addreses.

- android/res/layout/update_guide_container.xml
https://jira.mail.ru/browse/MAPSME-9707
> Mapsme 9707

- android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
https://jira.mail.ru/browse/MAPSME-9711
> [android] Changed refresh toast

- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/Closable.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-9630
https://jira.mail.ru/browse/MAPSME-9628
https://jira.mail.ru/browse/MAPSME-9714
https://jira.mail.ru/browse/MAPSME-9629
> Mapsme 9630 pp update issue

- android/UnitTests/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
Fabric plugin produce the similar issue like here https://github.com/firebase/firebase-android-sdk/issues/198#issuecomment-456455002
It will be fixed later
> No issue android studio 3.1.1

- storage/diff_scheme/diff_manager.hpp
- storage/storage.cpp
- storage/storage.hpp
> Build fix.

- android/src/com/mapswithme/maps/search/PromoCategory.java
https://jira.mail.ru/browse/MAPSME-9718
> [android] Added connection state validation

- android/src/com/mapswithme/maps/adapter/TagsCompositeAdapter.java
https://jira.mail.ru/browse/MAPSME-9733
> [android] Began to use new api item decoration

- map/map_tests/power_manager_tests.cpp
- map/power_management/power_manager.cpp
- platform/platform_ios.mm
https://jira.mail.ru/browse/MAPSME-9502
> Power manager fixes

- android/src/com/mapswithme/maps/bookmarks/data/MapObject.java
- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
[android] Added resetting pp scroll and webview for case when new pp opened once after the previos was scrolled or web loaded, i.e. without hidding of previos
https://jira.mail.ru/browse/MAPSME-9628
> [android] Made more accurate map object comparing

- android/res/layout/about.xml
- android/res/values-w1020dp/attrs.xml
https://jira.mail.ru/browse/MAPSME-9739
https://jira.mail.ru/browse/MAPSME-9716
> [android] Disable landscape tablet ui

- routing/index_graph_loader.cpp
- routing/routing_settings.cpp
- routing/speed_camera_ser_des.hpp
> [routing] delete TODO from gmoryes

- android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
https://jira.mail.ru/browse/MAPSME-9668
> Mapsme 9668

- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-9732
> [android] Fixed booking photo gallery clearing in pp

- android/src/com/mapswithme/maps/ugc/UGCController.java
https://jira.mail.ru/browse/MAPSME-9752
> [android] Fixed ugc reviews gallery clearing

- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-9728
> [android] Added refreshing pp views when bookmark updated

- generator/world_map_generator.hpp
Подравняла бубен относительно естественного прироста данных по popularity
> [search] Adjust kPopularityThreshold for World.mwm

- generator/CMakeLists.txt
- generator/collector_interface.hpp
- generator/collector_tag.cpp
- generator/collector_tag.hpp
- generator/descriptions_section_builder.cpp
- generator/descriptions_section_builder.hpp
- generator/generate_info.hpp
- generator/generator_tests/descriptions_section_builder_tests.cpp
- generator/generator_tool/generator_tool.cpp
- generator/osm_element.cpp
- generator/osm_element.hpp
- generator/translator_planet.cpp
- generator/translator_planet.hpp
- generator/wiki_url_dumper.cpp
- generator/wiki_url_dumper.hpp
- tools/python/descriptions_downloader.py
- tools/unix/generate_planet.sh
Протестировано.
Инфа по некоторым мвмкам (для тех объектов, которые есть в популярити):
```
LOG TID(1) INFO     0.323302 generator/descriptions_section_builder.hpp:193 Build() Added 723 pages form wikipedia urls for ./target/Russia_Moscow.mwm
LOG TID(1) INFO     0.323322 generator/descriptions_section_builder.hpp:194 Build() Added 66 pages form wikidata ids for ./target/Russia_Moscow.mwm
```
```
LOG TID(1) INFO     0.389454 generator/descriptions_section_builder.hpp:193 Build() Added 594 pages form wikipedia urls for ./target/UK_England_Greater London.mwm
LOG TID(1) INFO     0.389472 generator/descriptions_section_builder.hpp:194 Build() Added 443 pages form wikidata ids for ./target/UK_England_Greater London.mwm
```
> [generator] Improved descriptions using wikidata.

- tools/python/openlr/quality.py
1. Поправлена ошибка в скрипте по оценке матчинга. Следует брать в расчет только дуги для которых задан тег GoldenRoute.
2. Добавил вывод информации о том, сколько дуг при разметке выборки помечено, как Ignored
> Bug fix and improvement in quality matching script.

- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingFlow.storyboard
- iphone/Maps/Bookmarks/Categories/Sharing/Tags/SharingTagsViewController.swift
- iphone/Maps/Bookmarks/Categories/Sharing/Tags/TagCollectionViewCell.swift
- iphone/Maps/Bookmarks/Categories/Sharing/Tags/TagsCollectionViewLayout.swift
- iphone/Maps/Bookmarks/Categories/Sharing/Tags/TagsDataSource.swift
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.h
- iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm
https://jira.mail.ru/browse/MAPSME-9511
> [iOS] limit maximum number of tags

- iphone/Maps/Bookmarks/Categories/Category settings/CategorySettingsViewController.swift
- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingFlow.storyboard
- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
- iphone/Maps/Bookmarks/Categories/Sharing/EditOnWebAlertViewController.swift
- iphone/Maps/Bookmarks/Categories/Sharing/GuideDescriptionViewController.swift
- iphone/Maps/Bookmarks/Categories/Sharing/GuideNameViewController.swift
- iphone/Maps/Classes/MWMTextView.m
- iphone/Maps/Maps.xcodeproj/project.pbxproj
https://jira.mail.ru/browse/MAPSME-9510
> [iOS] add name and description editing on sharing

- android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
https://jira.mail.ru/browse/MAPSME-9672
> [android] Change category limit

- routing/routing_integration_tests/speed_camera_notifications_tests.cpp
- routing/speed_camera_manager.cpp
- routing/speed_camera_manager.hpp
cherry-pick #10127 to release-90
> [routing] Fix searching closest camera on route + hightliting

- routing/routing_integration_tests/speed_camera_notifications_tests.cpp
- routing/speed_camera_manager.cpp
- routing/speed_camera_manager.hpp
cherry-pick https://github.com/mapsme/omim/pull/10127 to master
> [routing] Fix searching closest camera on route + highlighting

- android/src/com/mapswithme/maps/MapFragment.java
- android/src/com/mapswithme/maps/bookmarks/data/FeatureId.java
- android/src/com/mapswithme/maps/geofence/Factory.java
- android/src/com/mapswithme/maps/geofence/GeofenceRegistryImpl.java
- android/src/com/mapswithme/maps/sound/TtsPlayer.java
- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
https://jira.mail.ru/browse/MAPSME-9788
> Mapsme 9788 geofence crash

- android/jni/com/mapswithme/maps/Framework.cpp
- android/jni/com/mapswithme/maps/Framework.hpp
- android/jni/com/mapswithme/maps/metrics/UserActionsLogger.cpp
- android/jni/com/mapswithme/maps/ugc/UGC.cpp
- android/src/com/mapswithme/maps/ugc/UGC.java
- android/src/com/mapswithme/maps/ugc/UGCController.java
- android/src/com/mapswithme/maps/ugc/UGCEditorFragment.java
- iphone/Maps/UI/PlacePage/MWMPlacePageData.h
- iphone/Maps/UI/PlacePage/MWMPlacePageData.mm
- iphone/Maps/UI/PlacePage/MWMPlacePageManager.mm
- iphone/Maps/UI/PlacePage/PlacePageLayout/Content/UGC/UGCAddReview/UGCAddReviewController.swift
- map/bookmark_catalog.cpp
- map/framework.cpp
- map/utils.cpp
- map/utils.hpp
https://jira.mail.ru/browse/MAPSME-9633
https://jira.mail.ru/browse/MAPSME-9634
https://jira.mail.ru/browse/MAPSME-9712
https://jira.mail.ru/browse/MAPSME-9776
> [android][ios] do not try to save ugc when review is not valid.

- platform/marketing_service.cpp
- platform/marketing_service.hpp
- storage/diff_scheme/diff_manager.cpp
- storage/diff_scheme/diff_scheme_checker.cpp
https://jira.mail.ru/browse/MAPSME-9578
> [statistics] fix statistics for diffs

- android/src/com/mapswithme/maps/bookmarks/BookmarkDownloadReceiver.java
- android/src/com/mapswithme/maps/bookmarks/BookmarksDownloadManager.java
- android/src/com/mapswithme/maps/bookmarks/DefaultBookmarkDownloadController.java
- android/src/com/mapswithme/maps/bookmarks/OperationStatus.java
- android/src/com/mapswithme/maps/bookmarks/SystemDownloadCompletedService.java
- android/src/com/mapswithme/maps/bookmarks/data/Error.java
- android/src/com/mapswithme/maps/bookmarks/data/Result.java
https://jira.mail.ru/browse/MAPSME-9655
> [android] Added additional logs for bookmark payment flow

- coding/simple_dense_coding.cpp
- coding/simple_dense_coding.hpp
- indexer/succinct_trie_reader.hpp
> [3party] delete useless var

- android/src/com/mapswithme/maps/widget/placepage/BannerController.java
- android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java
- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-9799
> Mapsme 9799 pp small fixes

- android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-9790
> [android] Fix hotels price

- iphone/Maps/UI/Search/Tabs/MWMSearchFrameworkHelper.mm
https://jira.mail.ru/browse/MAPSME-9785
> [iOS] Show megafon banner only when online

- ugc/storage.cpp
https://jira.mail.ru/browse/MAPSME-9574
https://jira.mail.ru/browse/MAPSME-9584
> [ugc] Stability improvment + statistics

- iphone/Maps/Core/Notifications/CoreNotificationWrapper.mm
https://jira.mail.ru/browse/MAPSME-9656
> [iOS] fix open app by tapping on review notification

- android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
- android/src/com/mapswithme/maps/MwmActivity.java
- android/src/com/mapswithme/maps/base/BaseActivityDelegate.java
- android/src/com/mapswithme/maps/base/BaseMwmExtraTitleActivity.java
- android/src/com/mapswithme/maps/base/BaseMwmFragmentActivity.java
- android/src/com/mapswithme/maps/base/BaseToolbarActivity.java
- android/src/com/mapswithme/maps/gallery/FullScreenGalleryActivity.java
- android/src/com/mapswithme/maps/purchase/BookmarkPaymentActivity.java
- android/src/com/mapswithme/maps/search/SearchActivity.java
https://jira.mail.ru/browse/MAPSME-9832
> Mapsme 9832 npe crash safedestroy

- data/countries.txt
- data/external_resources.txt
> [planet] New data from 18.02.2019 (hotels:170500)

- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-9793
> [power manager] loading and subscribing on startup are rearranged

- iphone/Maps/Classes/MapViewController.mm
- iphone/Maps/UI/Storyboard/Welcome.storyboard
- iphone/Maps/UI/Welcome/WhatsNewController.swift
Also fix "black screen" bug on first start
https://jira.mail.ru/browse/MAPSME-8701
> [iOS] update onboarding and what's new screens layout

- iphone/Maps/Bookmarks/BookmarksVC.mm
- iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
https://jira.mail.ru/browse/MAPSME-9564
> [iOS] fix crash when deleting bookmarks list from list settings screen

- iphone/Maps/Bookmarks/Categories/Sharing/BookmarksSharingViewController.swift
https://jira.mail.ru/browse/MAPSME-9789
> [iOS] add error when user tries to pushlish list with less then 3 elements

- iphone/Maps/UI/Editor/MWMEditorViewController.mm
https://jira.mail.ru/browse/MAPSME-9829
> [iOS] While editing or creating map object, don't save object name if it's not valid

- android/src/com/mapswithme/maps/widget/placepage/Sponsored.java
https://jira.mail.ru/browse/MAPSME-9848
> [android] Fixed sponsored type order after removing Viator

- android/src/com/mapswithme/maps/ugc/routes/UgcSharingOptionsFragment.java
https://jira.mail.ru/browse/MAPSME-9831
> Mapsme 9831 change strings [DNM]

- iphone/Maps/UI/Settings/MWMSettingsViewController.mm
https://jira.mail.ru/browse/MAPSME-9452
> [iOS] deselect manage subscription cell after selection

- map/framework.cpp
https://jira.mail.ru/browse/MAPSME-9746
> [eye] fix for tracking bookmarked feature opening
