3party/open-location-code/BUILD, 3party/open-location-code/CMakeLists.txt, 3party/open-location-code/LICENSE, 3party/open-location-code/README.md, 3party/open-location-code/codearea.cc, 3party/open-location-code/codearea.h, 3party/open-location-code/openlocationcode.cc, 3party/open-location-code/openlocationcode.h, CMakeLists.txt, data/copyright.html, search/CMakeLists.txt, search/processor.cpp, search/processor.hpp
В строке поиска можно будет ввести код типа `9G7VQGWQ+V4` или его сокращённый вариант `QGWQ+V4` (при условии, что вьюпорт в Москве) и сразу получить результат, наше здание в этом случае.
Задействует опенсорсную гугловскую библиотеку. [Плюс-коды](https://plus.codes/) полностью открыты и поддерживаются в приложении Google Maps.
=> [search] Support searching over Plus Codes

base/CMakeLists.txt, base/base_tests/CMakeLists.txt, base/base_tests/fifo_cache_test.cpp, base/fifo_cache.hpp, routing/geometry.cpp, routing/geometry.hpp, xcode/base/base.xcodeproj/project.pbxproj
Данный PR является результатом исследования проведенного в https://github.com/mapsme/omim/pull/8404.
На текущем мастере, на iPhone 7, с определенным набором карт пешеходные маршруты прокладывались так:
Офис - Велике Луки: 676MB (памяти на прокладку), 36.8 секунды.
Офис - Зеленоград: 72MB(памяти на прокладку), 4.28 секунды.
После данного PR (FIFO c хеш таблицей и list по 5К элементов)
Офис - Велике Луки: 477МБ (памяти на прокладку), 37.6 секунд.
Офис - Зелиноград: 65MB(памяти на прокладку), 4.31 секунд.
Примерно та же скорость, что и без вытеснения, но памяти используемся много меньше.
Что осталось:
1. Поскольку раньше кэш наполнялся и ничего не удалялось до окончания работы было вполне безопасно возвращать ссылки на объекты кеша. После данного PR программа свою корректность сохраняет. Но …
=> FIFO cache implementation and using it for routing geometry

indexer/rank_table.cpp, indexer/rank_table.hpp, search/ranker.cpp
Ранк для фифашных объектов подобран из следующих соображений:
1. Если ищется что-то типа "стадион" и во вьюпорте есть город где проходит ЧМ, то на первом месте должны быть стадионы ЧМ. 
2. Если вьюпорт вообще не рядом , то стадионы ЧМ не должны вылезать.
3. Поднять стадион при поиске по названию стадиона на первое место среди одноименных отелей, остановок и т.п.
Например, если на карте любой кусок москвы, то по запросу "стадион" топ-2 это лужники и спартак. Если на карте Минск, то по запросу "стадион" никаких объектов ЧМ вылезать не должно, должны быть стадионы в минске. Если ищем "казань арена", то среди кучи объектов типа "апартаменты с видом на казань арена" стадион должен быть первым.
todo уберу после тестов по полным данным (надеюсь что сегодня).
=> [search] Increase search rank for FC2018 objects

generator/osm_source.cpp, indexer/feature_visibility.cpp
Во время сборки типа по тегам объекта в `osm2type.cpp` итоговый тип проверяется на `feature::IsDrawableAny()`. Засада в том, что этот метод вызывает не только соответствующий метод классификатора, но и `feature::TypeAlwaysVisible()`. Для спонсорских типов последний всегда возвращает `true`.
Это было бы нормально, если бы в типах присутствовало всё дерево спонсорских типов (т.е. все типы в последовательности вида `tourism` → `tourism-information` → `tourism-information-map`). Но у нас нет типа `event`, хотя есть два подтипа (`fc2018`). В OSM есть другие значения тега `event=*`, поэтому генератор конструировал для таких объектов тип `event`, метод `IsDrawableAny()` возвращал `true` по вышеописанной причине, и тип передавался на сохранение в mwm. Но до туда он не доходил, потому что …
=> [generator] Fix type constructor

base/base_tests/fifo_cache_test.cpp, base/fifo_cache.hpp, base/internal/message.hpp
Использования circular_buffer вместо list для кэша routing не дало ожидаемого результата. Я попробовал использовать его как в одну (методы push_front(), back(), так и в другую сторону метода (push_back(), front()). Для каждого варианта 5 раз подряд проложил пешеходный маршрут Центр Москвы - Великие Луки. Результаты по времени ниже:
circular_buffer (push_front(), back())
51.5286
45.7207
46.3107
45.146
44.8683
circular_buffer (push_back(), front())
45.122
44.4634
44.6121
45.1032
44.7565
list
45.0965
44.4356
44.8116
44.9694
44.9224
Оставляю list, как стандартный и не менее быстрый для нашего случая, чем circular_buffer
Данный PR приведен чтоб показать код исследования и не предназначен для мержа в мастер.
@mpimenov @tatiana-yan @ygorshenin
=> Using circular_buffer instead of list.

indexer/feature_visibility.cpp
Спонсорские типы не должны светиться на не-poi. И не должны добавлять линии в данные.
=> [generator] Disable fake types for lines

android/jni/com/mapswithme/maps/MapManager.cpp, base/thread_checker.hpp, indexer/osm_editor.cpp, map/bookmark_manager.cpp, map/bookmark_manager.hpp, map/discovery/discovery_manager.cpp, map/discovery/discovery_manager.hpp, map/routing_manager.cpp, storage/http_map_files_downloader.cpp, storage/storage.cpp
Основная идея: обнаружение ошибок связанных с многопоточностью на ранней стадии. Т.к. assert thread checker может добавляться в новые места в ядре без соответствующих изменений в коде платформы, то могут возникать "неопределенные" поведения в продакшане. Очень хотелось бы это влить до предстоящей регрессии, возможно найдутся еще места, где платформа обращается к ядру в неправильном потоке.
=> [core] Tightened the thread checker

generator/routing_index_generator.cpp, map/routing_manager.cpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_loader.cpp, routing/index_graph_loader.hpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/single_vehicle_world_graph.cpp, routing/transit_world_graph.cpp, routing/world_graph.cpp, track_analyzing/track_matcher.cpp
При прокладке протяженных авто маршрутов происходит в 2 этапа:
1. прокладка cross mwm -го маршрута (чтоб определить входы и выходы mwm через которые будет проходить маршрута);
1. затем, прокладка маршрута внутри каждой из mwm.
Ранее на первом этапе мы строили IndexGraph для каждой mwm, к которой прикосались. Хотя этого не требовалось. Достаточно просто иметь информацию о геометрии фич в этих mwm.
Данный PR существенно оптимизирует первый этап прокладки маршрута в случае длинных авто маршрутов. Оптимизация достигается за счет того, что если требуется только геометрия mwm, не строится IndexGraph, Например, маршрут из Москвы в центр России памяти уходит в два с половиной - три раза меньше, а время на прокладки в треть быстрее.
Результаты измерений:
Авто маршрут: Москва (55.7395, 37.5869) - …
=> Performance and memory optimization for cross mwm routing.

android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp, android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesActivity.java, android/src/com/mapswithme/maps/bookmarks/BookmarkListActivity.java, android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java, iphone/Maps/Bookmarks/BookmarksVC.mm, iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift, iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCDefaultViewModel.swift, iphone/Maps/Bookmarks/Categories/BMCViewModel/BMCViewModel.swift, iphone/Maps/Core/Bookmarks/MWMBookmarksManager.h, iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm, map/bookmark_manager.cpp, map/bookmark_manager.hpp
Когда мы редактируем категории букмарок или сами букмарки в окнах категорий и списков (не на карте) возникает накапливание изменений для отправки в поиск, графический движок и для сохранения на диск. Если файл с букмарками большой или таких файлов много, изменения могут занимать значительный объем в оперативной памяти, что рано или поздно приведет к завершению свободного места и крэшу, так как изменения будут обработаны только при выходе на карту (для графического движка в случае Android), или память закончится при интенсивной работе с категориями (show/hide all на Android/iOS).
Для того, чтобы избежать этого, были добавлены функции, которые позволяют разрешить/запретить нотифицирование графического движка, поиска и прочих систем. При входе в вышеобозначенные окна мы запрещаем …
=> Fixed redundant notifications in BM

drape/overlay_tree.cpp, drape_frontend/frontend_renderer.cpp, drape_frontend/message_subclasses.hpp
Когда-то в январе 2017-го мы лечили крэш https://github.com/mapsme/omim/pull/5310. На ряду с прочим, мы сделали сообщение SelectObjectMessage контекстозависимым. Это создало гонку в Android при возвращении из разных окон на карту. Из-за этого иногда голубой маркер не показывается, потому как сообщение удаляется из очереди до восстановления GL-контекста.
Крэш, который был исправлен, возникал внутри функции GetSelectedFeatureRect на строке
**if (handle->IsVisible() && handle->GetOverlayID().m_featureId == m_selectedFeatureID)**
Крэш, похоже, был из-за того, что мы получали OnNewVisibleViewport при невалидном дереве оверлеев. Это возможно, так как OnNewVisibleViewport вызывается из ProcessEvents, которые обрабатываются в начале кадра до перестроения дерева оверлеев. Это частично решают …
=> Fixed search mark appearance on Android

indexer/borders.cpp, indexer/borders.hpp
Чтобы правильно писать логи в клиентском коде геокодера, исключения будут перехватываться там.
=> [geocoder] Do not catch Reader::Exception in Borders::Deserialize

kml/kml_tests/serdes_tests.cpp, kml/pykmlib/bindings.cpp, kml/pykmlib/bindings_test.py, kml/serdes.cpp, kml/types.hpp
Добавлена поддержка serverId, который нужен для формирования диплинок
=> Added full support of serverId in KML library

map/local_ads_manager.cpp, map/local_ads_manager.hpp
Исправлена проблема в local ads manager, когда при слабом отклике сети можно было поставить множество запросов на скачивание одной и той же кампании.
=> Fixed mwm requesting in local ads manager

android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java, android/src/com/mapswithme/util/statistics/Statistics.java, iphone/Maps/Common/Statistics/StatisticsStrings.h, iphone/Maps/Core/Bookmarks/MWMBookmarksManager.mm, map/cloud.cpp, map/cloud.hpp
Нельзя было использовать ASSERT на этих переменных класса в отложенных тасках. Переменные могут спокойно изменяться между тасками
=> Fixed false asserts in cloud

routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing_common/bicycle_model.cpp, routing_common/pedestrian_model.cpp
Возникали случаи, когда роутер в случае пешеходного роутинга предлагал ехать на паромах вместо того, чтоб идти пешком: https://jira.mail.ru/browse/MAPSME-7160
Причина этого была в том, что для паромов использовалась максимальная скорость, в случае пешеходного роутинга - 5 км/ч. Исследование кода показало, что та же проблема есть и в вело роутинге. 
- Поправил и пеший и вело роутинг;
- Добавил интеграционный тест на пеший роутинг согласно:  https://jira.mail.ru/browse/MAPSME-7160
- Поставил тикет, на поиск места для аналогичного теста для вело маршрута: https://jira.mail.ru/browse/MAPSME-7546 (Тест будет добавлен отдельным PR)
@mpimenov @rokuz PTAL
PR помечен DNM, т.к. он для минорки. Ждем выхода релиза 82 и потом можно будет мержить.
=> Reducing speed for ferry in case of pedestrian and bicycle routing.

map/map_tests/search_api_tests.cpp
Now that we unconditionally thin out the viewport results,
the test pois had to be moved further apart.
=> [search] Fixed a test.

routing/routing_tests/turns_generator_test.cpp
После PR об изменении логики работы методов для определения угла поворота (RightmostDirection() и LeftmostDirection()): https://github.com/mapsme/omim/pull/8585 оказались сломаны routing_tests. К сожалению об этом дженкинс не сообщил сразу. Данный PR исправляет  routing_tests.
=> Routing tests on slight turn fixing.

iphone/Maps/Classes/Share/MWMActivityViewController.mm
Disable Facebook sharing for bookmark groups since Facebook doesn't allow to post .kmz files. 
Enable AirDrop sharing for bookmarks.
=> MAPSME-7611 Fix Facebook sharing

routing/routing_tests/routing_algorithm.cpp
Релиз версия routing тестов крешилась. Причина была в висящий ссылке.
Поправил.
@tatiana-yan @mpimenov PTAL
=> Removing dangling reference from TAlgorithmImpl::Params in routing tests.

platform/platform_tests/local_country_file_tests.cpp
Данный тест сломался после рефаторинга ScopedFile в коммита:
Subject:  [platform] [tests] Added an option to ScopedFile.
Author:   Maxim Pimenov <m@maps.me>
Date: Fri Nov 17 2017 16:01:54 GMT+0300 (MSK)
Committer:    Arsentiy Milchakov <milcars@mapswithme.com>
Date: Fri Nov 17 2017 17:34:25 GMT+0300 (MSK)
SHA:  50653171ff545219eae083cffa5106baeeea325d
поскольку комит изменил код теста. Данный PR возвращает код к состоянию до коммита + добавляет один комментарий.
@VladiMihaylenko @mpimenov @greshilov PTAL
=> Fixing platform_test LocalCountryFile_DiskFiles

routing/index_graph_starter.cpp, routing/routing_integration_tests/route_test.cpp
Обработка дуги нулевой длины около старта или финиша.
Ближайшей к старту (финишу) сегмент может быть нулевой длины. До данного PR мы падали на чеке (см. ниже), если такой сегмент оказался около старта и финиша. Сейчас прокладываем корректно маршрут. 
Добавил пару интеграционных тестов.
Вот источник бага: https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5af6d27011e9fa0aa55006b0/sessions/latest
@tatiana-yan @mpimenov PTAL
Внимание! После обновления карт 2 routing integratin tests не проходят. Это исправлено в мастере (поправлен код в тестах). К данному исправлению это отношения не имеет.
Прошу оперативно посмотреть к релизу.
=> Processing the case when the start and the finish of the route is near an Segment with zero length.

generator/generator_tool/generator_tool.cpp, generator/osm_source.cpp, generator/osm_source.hpp
Для генерации индекса и границ регионов нужны raw-фичи с регионами.
К сожалению при сохранении raw фичей на разных этапах этого процесса в разных частях кода какие-то фичи отфильтровываются по не вполне прозрачным правилам (те что не видны согласно стилям, те что имеют тег "place=", даже если при этом видимые теги у них тоже есть, мультиполигоны с "type=border" даже если они видны или добавлены в "белый список" видимости и т.д. и т.п.).
Лучший путь решения этой проблемы такой: надо провести рефакторинг кода, отвечающего за генерацию фичей, как часть этого рефакторинга выделить фильтрацию в одно место и разрешить вызывающему emiter коду задавать функцию фильтрации.
Пока на рефакторинг ресурсов нет делаю наименьший из хаков который смогла придумать -- создаю фичу из искуственного "хорошего" …
=> [geocoder] Generate raw features for regions.

routing/edge_estimator.cpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/routing_helpers.cpp, routing/routing_helpers.hpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/routing_algorithm.cpp
Исправила вычисление веса фейковых сегментов типа type of real -- при поиске исходящих берем часть веса исходного пропорционально отношению длины фейкового сегмента к длине полного при помощи CalcSegmentWeight. Исправила проверку соединения сегментов с учетом isOutgoing.
Добавила в тесты index graph проверку времени маршрута (включает проверку корректности веса фейковых сегментов).
=> [routing] Fix fake segment weight, tests

local_ads/statistics.cpp, routing/bicycle_directions.cpp, routing/loaded_path_segment.hpp, routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_integration_tests/turn_test.cpp, routing/routing_result_graph.hpp, routing/routing_tests/turns_generator_test.cpp, routing/turns_generator.cpp, routing/turns_generator.hpp
Основная цель данного PR улучшение генерации маневров в ряде случаев, например, https://jira.mail.ru/browse/MAPSME-7573
При генерации сообщения о маневре, очень важную роль играет правильное вычисление угла поворота. Он вычисляется на базе геометрии маршрута. Чтоб вычислить угол необходимо от точки поворота отступить назад и вперед по маршруту, получить точку до точки поворота, точку после точки поворота и на базе них и точки поворота вычислять угол. Важным вопросом является на сколько отступать по маршруту назад и вперед. 
* На один Segment не годится. Получим не правильный угол, т.к. карта часто нарисована так, что первый Segment отходит от точки бифуркации под не большим углом. 
* На один LoadedPathSegment, но не более чем x метров и n Segment-ов. Так было реализовано ранее. При этом …
=> Better calculation outgoing route points for turn generation and fixing some turn generation issues.

tools/python/.gitignore, tools/python/mixed_to_geojson.py
Написал скрипт, который превращает файлы `mixed_nodes.txt` и `mixed_tags.txt` из каталога `data` в файлы GeoJSON. Затем их можно открыть, например, в http://geojson.io и посмотреть, все ли объекты получают доп. теги.
Заодно добавил пару строк в местный `.gitignore` для удобства. Там кэш координат для этого скрипта и каталоги с бэкапами для графа общественного транспорта.
=> [data] Add mixed_to_geojson script

routing/transit_world_graph.hpp
До этого PR, если пешеходная часть маршрута общественного транспорта превышала 25 минут + 3 минут на каждый км от расстояния по прямой между стартом и финишем, мы давали ошибку прокладки маршрута общественным транспортом.
После этого PR мы дадим ошибку, если пешая часть превысит 50 минут + 3 минуты на км.
@tatiana-yan @burivuh PTAL
=> Increasing pedestrian part for transit route to 50 minutes and 7 minutes per one km.

generator/extract_addr/extract_addr.cpp, tools/python/mwm/decode_id.py, tools/python/mwm/mwm.py
Поправил ошибку в extract_addr: координаты сохранялись как строки. Также попутно исправил ошибку декодирования идентификатора в `mwm.py` и добавил скрипт, чтобы быстро из длинного числа нашего внутреннего osm id получать ссылку на сайт OSM.
Этот реквест заменяет #8430, большая часть которого отъехала в отдельную репу.
=> Fix extract_addr generation and a small bug in mwm.py

routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing_common/bicycle_model.cpp, routing_common/bicycle_model.hpp, routing_common/car_model.cpp, routing_common/car_model.hpp, routing_common/pedestrian_model.cpp, routing_common/pedestrian_model.hpp, routing_common/routing_common_tests/vehicle_model_test.cpp, routing_common/vehicle_model.cpp, routing_common/vehicle_model.hpp
Учет дорожного покрытия при расчете скорости на фиче.
В мае 2016 @Zverik в геометрию (а не в meta data) добавил св-во:
psurface|paved_good
psurface|paved_bad
psurface|unpaved_good
psurface|unpaved_bad
Т.о. любая дорога может содержать информацию о качестве покрытия, которая влияет на скорость на данной дороге.
Данный PR вводит понижающие коэффициент для каждого типа покрытий. Т.е. скорость на фиче рассчитывается (грубо), как скорость заданная для highway класса умножить на понижающей коэффициент. 
Заданы отдельные наборы коэффициентов  для авто, вело и пешего роутинга.
@tatiana-yan @mpimenov @Zverik PTAL
=>  [routing] Taking into account road surface type for speed calculating.

generator/search_index_builder.cpp, indexer/indexer_tests_support/test_with_custom_mwms.hpp, search/search_integration_tests/smoke_test.cpp
У нас при построении индекса типы фичей, которые мы индексируем, обрезались до глубины 2, а типы из категорий -- нет. Поэтому в категорийные типы глубиной больше 2 ничего не индексировалось.
Исправила и добавила тесты.
С теми типами, для которых тест поиска каждой категории не проходит, предлагаю разбираться отдельно.
=> [search] Fix index build for categories which are deeper than 3 levels

routing/routing_integration_tests/bicycle_route_test.cpp
После обновления карт до 28 мая сломался один интеграционный тест. Он связан с тем, что таг cycleway=opposite был снят с односторонней улицы Singel в Амстердаме. Что привело к тому, что вело маршрут перестал прокладываться против движения по односторонней улице (т.к. таг cycleway=opposite был снят).
В качестве исправления, я перенес эту проверку на соседнюю улицу (Keizersgracht), на которой есть таги oneway=yes и cycleway=opposite.
Что касается переименования теста, то новое имя лучше отражает суть происходящего сейчас. Согласно: https://wiki.openstreetmap.org/wiki/Tag:cycleway=opposite?uselang=ru: 
Use cycleway=opposite for situations where cyclists are permitted to travel in both directions on a road which is one-way for normal traffic, in situations where there is no dedicated …
=> Routing integration tests fix for 18.05.28 maps.

generator/search_index_builder.cpp, search/search_integration_tests/smoke_test.cpp
ошиблась когда делала https://github.com/mapsme/omim/pull/8851
не учла что бывает `level < 2`
=> [search] Fix search index build for 1-level categories

data/categories.txt
Dog parks are currently not translated in the app and show up as `leisure-dog_park`.
I suggest to use the word "dog area" because often those dog parks are part of a bigger park.
=> Add a label for leisure-dog_park

search/features_layer_path_finder.cpp, search/features_layer_path_finder.hpp, search/model.cpp, search/search_integration_tests/smoke_test.cpp
У нас было несколько проблем из-за которых не искались POI, имеющие адрес, по запросу типа "Starbucks Ленинградский проспект 39 с79":
- т.к. фича, которой соответствует старбакс, имеет адрес, Model::GetType возвращала для нее тип building и запрос размечался как building street street building building, такая схема недопустима. 
Чтобы это поправить перенесла проверку на POI в начало.
- после парса типов токенов при поиске путей фича, отвечающая за POI, попадала в список фичей, соответсвующих дому (т.к. имеет адрес), поэтому при поиске POI внутри дома игнорировалась из-за проверки `if (parent.find(childFeature) != parent.end())` в addEdge. Но менять это поведение (не добавлять POI в список домов) нельзя, т.к. в этом случае сломается поиск POI по адресу.
Чтобы это поправить поменяла вид …
=> [search] Fix poi address search

configure.sh
Fixed error `use of undeclared identifier 'GOOGLE_WEB_CLIENT_ID'` during  `./gradlew clean assembleWebRelease` command invocation.
=> [android] Fixed compilation

xcode/base/base.xcodeproj/project.pbxproj, xcode/coding/coding.xcodeproj/project.pbxproj, xcode/drape/drape.xcodeproj/project.pbxproj, xcode/drape_frontend/drape_frontend.xcodeproj/project.pbxproj, xcode/editor/editor.xcodeproj/project.pbxproj, xcode/generator/generator.xcodeproj/project.pbxproj, xcode/generator_tool/generator_tool.xcodeproj/project.pbxproj, xcode/geometry/geometry.xcodeproj/project.pbxproj, xcode/indexer/indexer.xcodeproj/project.pbxproj, xcode/kml/kml.xcodeproj/project.pbxproj, xcode/local_ads/local_ads.xcodeproj/project.pbxproj, xcode/map/map.xcodeproj/project.pbxproj, xcode/mwm_diff/mwm_diff.xcodeproj/project.pbxproj, xcode/openlr/openlr.xcodeproj/project.pbxproj, xcode/partners_api/partners_api.xcodeproj/project.pbxproj, xcode/platform/platform.xcodeproj/project.pbxproj, xcode/routing/routing.xcodeproj/project.pbxproj, xcode/routing_common/routing_common.xcodeproj/project.pbxproj, xcode/search/search.xcodeproj/project.pbxproj, xcode/storage/storage.xcodeproj/project.pbxproj, xcode/tracking/tracking.xcodeproj/project.pbxproj, xcode/traffic/traffic.xcodeproj/project.pbxproj, xcode/transit/transit.xcodeproj/project.pbxproj, xcode/ugc/ugc.xcodeproj/project.pbxproj
Xcode 9.3, 12 threads
With PCH - 346 s.
Without PCH - 409 s.
~ 15 % speed up.
=> [xcode] Add precompiled headers

base/levenshtein_dfa.cpp
Исправление ворнингов выявило ошибку, расстояние в эту сторону отрицательное, раньше работало т.к. кастовалось к беззнаковому.
=> [base] Fix infinite loop in LevenshteinDFA

coding/file_reader.cpp
Assertions in FileReader interfered with tests that checked
exceptions from reading broken files.
=> [coding] [map] Fixed tests.

generator/osm2type.cpp
По запросу в почте от пользователя. Предоставлю слово Володе:
> Похоже, разумно. foot=use_sidepath 18K (преимуществено в Германии): https://taginfo.openstreetmap.org/tags/foot=use_sidepath#overview 
Хотя это таг похоже пока не принят "in some countries it is not allowed to walk on the street while there is a sidewalk (e.g. Germany StVO § 25 Fußgänger, Absatz 1), which forces you to add something like foot=use_sidepath - which is not yet proposed.": https://wiki.openstreetmap.org/wiki/Talk:Key:footway
>
> Мне кажется, если есть sidepath на дороге, то разумно эту дорогу запрещать для пешего роутинга.
=> [routing] Parse foot=use_sidepath

map/local_ads_manager.cpp
При запуске приложения у нас читаются закэшированные фичи localads. Для них мы вызываем `framework.GetFeatureByID()`, чтобы получить сами объекты из mwm. Но если mwm заменены или удалены, этот метод вызывает ассерт по `fid.IsValid()`. Мы его не замечали, потому что ассерт сваливает только десктопное приложение в дебаге.
Я добавил проверку валидности featureId пораньше.
=> [localads] Skip invalid localads features

generator/popular_places_section_builder.cpp
Когда в мвмку прописываются объекты, которых нету в осме (границы, спонсорские объекты), то при сборке секции популярных объектов генератор крешится на CHECK.
В качестве быстрого решения убрал чек, сделал вместо него if. 
В будущем можно будет получить список типов, среди которых ищутся популярные места и использовать его для раннего отсечения. И добавить обратно чек.
=> [DNM][generator] popular places section fix

editor/editor_tests/osm_editor_test.hpp, editor/osm_editor.cpp, generator/borders_loader.cpp, generator/borders_loader.hpp, generator/feature_sorter.cpp, indexer/data_header.hpp, indexer/data_source.cpp, indexer/indexer_tests/test_mwm_set.hpp, indexer/mwm_set.hpp, map/benchmark_tool/features_loading.cpp, map/feature_vec_model.cpp, map/framework.cpp, map/map_tests/booking_filter_test.cpp, routing/routing_tests/road_graph_builder.cpp, search/geocoder.cpp, search/locality_finder.cpp, search/nested_rects_cache.cpp, search/search_tests/locality_finder_test.cpp, search/search_tests_support/helpers.cpp, ugc/ugc_tests/storage_tests.cpp
Записываю в bounds для mwm прямоугольник описанный вокруг границ соответствующего региона. Раньше был прямоугольник описанный вокруг всех фичей входящих в mwm, что приводило к тому, что если в mwm попало что-то типа relation описывающего границу соседнего государства или крупную магистраль в соседнем государстве границы слишком сильно раздувались. Это не предполагалось по месту использования данного поля.
=> [generator] Set mwm bounds rect to rect around region borders, not features which cross region border.

map/bookmark_manager.cpp
We don't have a way to use it in this release anyway.
Similar to #8566
=> [RELEASE ONLY] Don't send bookmarks data to the search engine.

routing/routing_integration_tests/street_names_test.cpp
После обновления до карт 2018.07.05 по сообщению @Zverik  сломался тест RussiaTulskayaToPaveletskayaStreetNamesTest.
Причина в том, что ввиду изменения геометрии Валовой улицы получился новый маневр:
2018.05.28
2018.07.05
Соответственно название "следующей улицы" изменилось. Поправил.
@tatiana-yan @Zverik PTAL
=> Routing integration tests fix for maps 180705

base/base_tests/osm_id_test.cpp, base/osm_id.cpp, base/osm_id.hpp, feature_list/feature_list.cpp, generator/cities_boundaries_builder.cpp, generator/coastlines_generator.cpp, generator/extract_addr/extract_addr.cpp, generator/feature_builder.cpp, generator/locality_sorter.cpp, generator/routing_helpers.cpp, generator/ugc_db.cpp, generator/ugc_translator.cpp, indexer/indexer_tests/locality_index_test.cpp, routing/cross_mwm_connector_serialization.hpp, transit/transit_graph_data.cpp
The masks in the higher bits of our osm id encoding
used to be disjoint. After a refactoring, the encoding
was switched to packing 4 values into 2 bits and thus
the masks started to intersect. The checks were left
untouched, though, resulting in Relation passing tests
for being a Node and a Way.
This commit fixes the bug and introduces an enum to
store the osm id type, hoping to make things more clear.
=> [base] Osm::Id fixes.

search/intermediate_result.cpp, search/intermediate_result.hpp, search/pre_ranker.cpp, search/ranking_info.cpp, search/search_quality/scoring_model.py
Коэффициент в ранжировании пока не подбирала, т.к. нет выборки, размеченной на mwm, в которых есть popularity, + желательно разметить категорийную выборку.
В данном PR хочу не переборщить с коэффициентом в ранжировании, чтобы что-то стало лучше, но ничего не сломалось. Вручную оценивала, что объекты с высоким popularity не лезут куда не надо -- например при поиске по слову "Московский " посёлок Московский выше чем Московский Кремль (top-2 popularity), даже если кремль по центру вьюпорта или кремль во вьюпорте, а Московский нет.
=> [search] Prefer objects with higher popularity

drape_frontend/backend_renderer.cpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/message.hpp, drape_frontend/message_subclasses.hpp, drape_frontend/postprocess_renderer.cpp, drape_frontend/route_renderer.cpp, drape_frontend/route_renderer.hpp, map/routing_manager.cpp, map/transit/transit_reader.cpp, map/transit/transit_reader.hpp
* Don't render transit schemes if there is a route. Clear transit cache if the following mode is enabled.
* Enable antialiasing when transit scheme is enabled.
=> Transit scheme display cases

search/intermediate_result.cpp
Не обрезаем длинные типы, например railway-station-subway будем показывать как subway, а не как train station. В placepage категория получается так же, будет консистентно.
=> [search] Fix search result display for long categories.

search/utils.cpp, search/utils.hpp
Функция для быстрого поиска по категориям для Дискавери.
Существующие режимы поиска для Дискавери не подходят, лепить франкенштейна типа "давайте поищем во вьюпорте, а потом обрежем и отранжируем как будто искали в списке" не хочется.
Пока переиспользование этой функции в Geocoder не предполагается, т.к. функция поиска по категориям из геокодера ветвится в зависимости от того, происходит ли поиск во вьюпорте, и переиспользовать можно три строчки, передавая при этом огромную кучу параметров. На мой взгляд такое переиспользование не упрощает код.
=> [search] Add helper for fast DiscoveryButton search

drape/color.hpp, drape/glyph_generator.cpp, drape/glyph_generator.hpp, drape/hw_texture.cpp, drape/hw_texture.hpp, drape/texture_manager.cpp, drape/texture_manager.hpp, drape_frontend/base_renderer.cpp
Причиной появления черных артефактов был конфликт OpenGL-контекста, создаваемого системой Android и наших контекстов в последнем обновлении Samsung Galaxy S. Проблема заключалась в том, что SetRenderingEnabled по сути полностью синхронный. Он останавливает поток, который его вызвал, пока не будут остановлены/возобновлены потоки рендеринга. Это правильно за одним исключением. OnCreateContext для каждого из потоков рендеринга вызывался до нотификации потока, который вызывал SetRenderingEnabled (UI-потока в нашем случае). Таким образом, UI-поток стоял и ждал, пока не будут инициализированы все графические ресурсы в обоих наших потоках, и при этом не мог освободить свой контекст и свои ресурсы. Потом, когда начинал освобождать, по всей видимости, корраптил чужую графическую память.
Однако …
=> Fixed ANR and black artefacts on Samsung Galaxy S

generator/routing_index_generator.cpp, routing/cross_mwm_connector_serialization.hpp, routing/cross_mwm_index_graph.hpp, routing/routing_tests/cross_mwm_connector_test.cpp
Когда делаем serialize transition, то находим максимальное число бит, которое использует один transition. Для этого вызываем GetOsmId(), этот метод снимает биты, отвечающие за transition type. В результате мы не учитываем первые биты 64 битного числа и на данный момент в mvm пишем только 30 младших бит
=> [routing] set osm::Id::Way to transitions

iphone/Maps/Bookmarks/BookmarksVC.mm
There was a problem with info cell on bookmarks list screen. If you tap "more" on description cell, scroll to bottom and back to info cell, description appears collapsed.
This PR fixes the bug.
=> [iOS] fix category info cell expanded state

android/jni/com/mapswithme/opengl/androidoglcontext.cpp, drape/framebuffer.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/postprocess_renderer.cpp, drape_frontend/postprocess_renderer.hpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5b49d1d66007d59fcd82a531?time=last-ninety-days
По всей видимости на некоторых Андроидах нельзя делать не только present, но и glBindFramebuffer после DetachSurface
=> Fixed crash in set default framebuffer on some Android devices

search/intermediate_result.cpp
Бубен для учета и расстояния и популярности при поиске по категорийным запросам (у не категорийных обычно нет проблемы с превышением допустимого кол-ва результатов в преранкере).
=> [RELEASE ONLY][search] Take distance into account when filter results in preranker.

generator/generator_tests_support/test_mwm_builder.cpp, generator/generator_tool/generator_tool.cpp, generator/search_index_builder.cpp, generator/search_index_builder.hpp, search/reverse_geocoder.cpp, search/reverse_geocoder.hpp, tools/unix/generate_mwm.sh
Решил собрать mwm для Беларуси. Скачал bz2, запустил generate_wmw belarus.osm.bz2.
Ждал 3 часа и так не дождался окончания. Посмотрел, что происходит: BuildAddressTable работает бесконечно долго ... Когда генерируется планета, эти тормоза нивелируются тем что на сервере одновременно работает много тасков для **маленьких** mwm.
Там 2 затыка:
- MwmContext пересоздается при обработке каждого нового адреса (для Беларуси ~3 млн). Создание и удаление этого контекста - достаточно тягомотная операция.
- Процесс генерации идет в один поток, хотя он достаточно просто параллелится.
Собственно, этот реквест про это:
- Один раз создается пачка MwmContext по количеству потоков, которые переиспользуются на обработке каждого нового адреса.
- Цикл обработки адресов параллелится на потоки (константа …
=> [generator] Speed up search address section building.

iphone/Maps/Bookmarks/Catalog/DownloadedBookmarksViewController.swift, iphone/Maps/Bookmarks/Categories/BMCView/BMCViewController.swift
App crashes when a user tries to set visibility for bookmarks category and bookmarks' section header is not on screen
=> [iOS] fix crash on bookmarks category visibility change

routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_integration_tests/street_names_test.cpp, routing/routing_integration_tests/turn_test.cpp
Привел routing_integration_tests в соответствие данным карты 2018.08.04. Все тесты сломались ввиду изменения данных за последние 2 месяца.
RussiaMoscowSalameiNerisPossibleTurnCorrectionBicycleWayTurnTest
Генерируемые маневры соответствуют геометрии маршрута.
RussiaMoscowSalameiNerisNoUTurnBicycleWayTurnTest
Генерируемые маневры соответствуют геометрии маршрута.
RussiaTulskayaToPaveletskayaStreetNamesTest
Генерируемые названия соответствуют маршруту и карте.
RussiaMoscowMinskia1TurnTest
Не появляется маневр двигайтесь прямо, который в данном случае и не нужен.
Ввиду ошибки в карте генерируется 2 маневра. С первым все понятно. Поверните на право. Второй так же не обходим. https://www.openstreetmap.org/query?lat=55.74325&lon=37.48087#map=19/55.74304/37.48108
Поскольку согласно карте здесь 2 …
=> Fixing routing integration tests for map 18.08.04.

base/geo_object_id.cpp
Поправил warning 
/Users/vladimirbykoyanko/src_github/omim/base/geo_object_id.cpp:14:16: warning: unused variable 'kReservedMask' [-Wunused-const-variable]
uint64_t const kReservedMask = 0x00FF000000000000;
^
1 warning generated.
В релиз сборке.
@mpimenov @tatiana-yan PTAL
=> Suppress warning for kReservedMask in base/geo_object_id.cpp

tools/ruby/category_consistency/check_consistency.rb, tools/ruby/category_consistency/omim_parsers.rb
**About:**
Tool get categories from `search/displayed_categories.cpp`, and tries to match values from `data/categories.txt` with their analogue from `strings.txt`.
e.g. 
```
categories.txt            |       strings.txt
@police                           |  [police]
fr:4^Police|4gendarmerie          |    fr = Police/gendarmerie
```
Script will try to find `Poli` or `gend` in the begging of the `Police/gendarmerie`
**Usage:**
`tools/ruby/category_consistence/check_consistency.rb`
**Example output:**
First value from `strings.txt`, second list from `categories.txt`
```
Inconsistent category "atm"
es : "ATM" is not matched by ["Cajero"]
Inconsistent category "fuel"
ar : "الغاز" is not matched by ["وقود", "بنزين", "سولار", "ديزل", "غاز"]
```
=> [strings] Add search category consistency tool

3party/ThreadPool/COPYING, 3party/ThreadPool/README.md, 3party/ThreadPool/ThreadPool.h, 3party/ThreadPool/example.cpp, data/copyright.html, generator/CMakeLists.txt, generator/emitter_factory.hpp, generator/generate_info.hpp, generator/generator_tests/CMakeLists.txt, generator/generator_tests/region_info_collector_tests.cpp, generator/generator_tests/regions_tests.cpp, generator/generator_tool/generator_tool.cpp, generator/osm_source.cpp, generator/region_info_collector.cpp, generator/region_info_collector.hpp, generator/regions.cpp, generator/regions.hpp, generator/restaurants_info/restaurants_info.cpp, generator/translator_region.cpp, generator/translator_region.hpp
Пример запуска может быть таким.
--user_resource_path=/home/andrianov/Projects/omim/data --intermediate_data_path=/home/andrianov/Projects/ISLANDS/intermediate_data --node_storage=map --osm_file_type=o5m --osm_file_name=/home/andrianov/Projects/omim/tools/unix/islands.o5m --output=regions_islands --generate_region_features=true --generate_regions_kv=true
Работает только вместе с [generate_region_features].
По итогу работы создаст [output].jsonl в  [intermediate_data_path]
Построение дерева для страны со всеми вложенными регионами - O(n^2).
Так же был добавлен thread_pool с просторов github. Он очень простой, классный и использует возможности C++11, в отличии от нашего старого.
Пример результата работы на островах - прилагается [regions_islands.jsonl.gz](https://github.com/mapsme/omim/files …
=> [generator] Region kv

indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, indexer/rank_table.cpp
Ранг для крупных станций (аэропорты, метро, ж/д вокзалы, но не платформы и не автобусные остановки).
Ранг небольшой, чтобы гарантированно не отбрасывать в преранкере, но и не слишком поднимать в выдаче -- должно стать строго лучше чем было.
=> [search][MAPSME-8519] Set rank for transport stations

generator/region_info_collector.hpp, generator/regions.cpp, generator/regions.hpp
-bash-4.1$ ~/omim-build-debug/geocoder_cli --hierarchy_path=/home/m.andrianov/regions/regions_world.jsonl
LOG TID(1) INFO   3.6189e-05 geocoder/hierarchy.cpp:127 Hierarchy() Finished reading the hierarchy. Stats:
LOG TID(1) INFO  0.000121348 geocoder/hierarchy.cpp:128 Hierarchy() Entries indexed: 173009
LOG TID(1) INFO   0.00013191 geocoder/hierarchy.cpp:129 Hierarchy() Corrupted json lines: 0
LOG TID(1) INFO  0.000141115 geocoder/hierarchy.cpp:130 Hierarchy() Unreadable base::GeoObjectIds: 0
LOG TID(1) INFO  0.000149691 geocoder/hierarchy.cpp:131 Hierarchy() Entries with duplicate address parts: 0
LOG TID(1) INFO  0.000157892 geocoder/hierarchy.cpp:132 Hierarchy() Entries without address: 0
LOG TID(1) INFO  0.000166084 geocoder/hierarchy.cpp:133 Hierarchy() Entries without names: 0
LOG …
=> [generator] Improved regions

base/base_tests/geo_object_id_tests.cpp, base/geo_object_id.cpp, base/geo_object_id.hpp, routing/cross_mwm_connector_serialization.hpp
PR делает 2 вещи.
- было не хорошо, что `std::string DebugPrint(GeoObjectId const & id);` крешился при попытке вывести GeoObjectId созданный конструктором по умолчанию. Поправил (1-й коммит).
- при сборке mwm, где не было дорожных фичь пересекающих границы (острова) падали на недавно добавленном в GeoObjectId чек. Поправил (2-й коммит).
@mpimenov @tatiana-yan @maksimandrianov PTAL
=> Generator fix. Cross mwm section.

generator/camera_node_processor.cpp, generator/camera_node_processor.hpp, generator/osm_element.hpp, generator/osm_source.cpp, generator/towns_dumper.cpp, generator/towns_dumper.hpp
В `World.mwm` терялись куда-то `cities_boundaries`. 
Проблема была в том, что на этапе препроцессинга: `BuildIntermediateDataFromO5M`, итерация по `o5m` файлу написана таким образом, что у элемента можно вызывать методы: `Members()`, `Nodes()`, `Tags()` только один раз, так как внутри них идет итерация по файлу. Для камер мне нужно было вызывать `Tags()`  два раза, поэтому я тэги закешировал. Оказалось, что внутри `Tags()` вызывается `Nodes.Skip()` + `Members.Skip()`. Таким образом, после вызова `Tags()` повторный вызов к `Nodes()` (так получилось в случае с `Way`) не давал никаких результатов.
Пофиксил пока так: закешировал `members`, `nodes`, `tags` в нужном порядке. 
По хорошему, надо написать преобразователь `O5MSource::Entity` => `OsmElement`. Но так как они не совсем идентичны, я …
=> [generator] Fix cities_boundaries in World.mwm problem

coding/endianness.hpp, coding/reader.hpp, coding/write_to_sink.hpp, generator/generator_tool/generator_tool.cpp, indexer/centers_table.cpp, indexer/interval_index.hpp, indexer/interval_index_builder.hpp, indexer/rank_table.cpp, map/framework.cpp, map/gps_track_storage.cpp, tracking/protocol.cpp
В настоящий момент наше приложение поддерживает только little endian архитектуру. Это означает, что и генератор и девайс должны быть little endian.
Хотя, глядя на код это не просто понять. Есть метод: `IsBigEndian()`, который достаточно активно используется в приложении, но не работает (как минимум 8 лет). Более того, поскольку он не работает, то он часто используется ошибочно. Например, в при десериализации секции "centers" он используется. А при сериализации нет. 
Более того. Есть места, где учет endianness важен, но про него забыли. Например, в секции "altitudes".
Если сейчас мы попытаемся запуститься на девайсе big endian, но будем падать в разных неожиданных местах, скорее всего это случится при запуске.
Почему мы сейчас вообще работаем?
Дело в том, что генератор собирает карту на …
=> Explicit check that only little endian architectures are supported.

3party/succinct/CMakeLists.txt
При сборке возникал вот такой warning:
/Users/vladimirbykoyanko/src_github/omim/3party/succinct/util.hpp:205:21: warning: private field 'm_buffer' is not used [-Wunused-private-field]
const char* m_buffer;
@mpimenov @tatiana-yan PTAL
=> Succint warning suppressing.

indexer/features_offsets_table.hpp
Поправил waring, который часто возникал при сборке.
@tatiana-yan @mpimenov PTAL
=> unused-private-field clang warning fix in includes.

generator/regions.hpp
Забыли виртуальный деструктор абстрактного базового класса.
@maksimandrianov @mpimenov PTAL
=> [generator] Virtual destructor of an abstract class was forgotten.

data/replaced_tags.txt
Думаю поддержку диет надо всё же делать через tag_replace, потому что добавлять в классификатор все варианты (diet:vegetarian=yes, diet:vegetarian=only, diet=vegetarian) излишне, надо их как-то объединять.
Для тех diet, которых нет в cuisine можно завести соответствующие cuisine (с ключом cuisine они тоже встречаются но редко).
=> [search][generator] Replace diet:vegetarian, diet:vegan with cuisine

routing/index_router.cpp, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/turn_test.cpp
После обновления до карты 2018.09.11 и после изменения изменений связанных с учетом дорожных фичь нужно поправить интеграционные тесты. Данный PR делает это.
Обновление карты до 2018.09.11
RussiaMoscowMinskia2TurnTest
StrangeCaseInAfrica
RussiaFerryToCrimeaLoadCrossGeometryTest
Учет городских фичь (в городе движение медленнее, кроме магистралей):
NetherlandsAmsterdamBicycleYes
RussiaMoscowKashirskoe16ToCapLongRoute
RussiaSmolenskRussiaMoscowTimeTest
RussiaMoscowLenigradskiy39GeroevPanfilovtsev22TimeTest
BelarusSlonimStartNearZeroEdgeTest
@tatiana-yan @vmihaylenko PTAL
=> Routing integration test fixes

storage/storage_integration_tests/migrate_tests.cpp
Изучил вопрос с падение storage_integration_tests. У нас сейчас падает StorageMigrationTests + некоторое кол-во из остальных тестов. Каждый раз разный набор упавших тестов. Причина в том, что если обращаться к дайрект или к продакшен серверам из под корпоративной сети и закачивать большие объемы, то иногда (раз в несколько карт) происходят сбои в закачке. Что-то вроде: `NSURLConnection finished with error - code -1009` (полный лог ниже).
План действий:
1. Комментируем StorageMigrationTests и оставляем подробный комментарий. Он на миграцию с больших mwm на маленькие. Она не поддерживается и не тестируется и не работает давно. По хорошему ее надо выпиливать и вместе с ней этот тест.
2. Пробуем собрать и запустить storage_integration_tests на удаленном linux сервере maps.me5. Должны пройти …
=> Removing storage integration test on migration.

routing/routing_integration_tests/route_test.cpp, routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp, routing_common/car_model.cpp
Удалил RussiaMosOblSpeedFactorsTest, потому, что он проверяет довольно странный кейс: мы ведем по highway-tertiary с unpaved-bad и огромным крюком вместо highway-path с unpaved-bad по прямой.
Коэффициенты взяты из трэк аналайзера путем усреднения скоростей по разным типам. Данные взяты из логов за 2 месяца.
=> [routing] New speeds in car model and quality tests.

generator/osm2meta.cpp, generator/osm2meta.hpp, generator/search_index_builder.cpp, indexer/feature_meta.cpp, indexer/feature_meta.hpp, indexer/map_object.hpp
В этом PR добавление кодов аэропортов в метадату и индексирование в поиске.
Дальше по плану:
- лучший учёт в поиске в рантайме (не только вытаскивать фичи из индекса, но и вытаскивать при ранжировании airport_iata из метадаты для сравнения с запросом)
- добавить международные аэропорты в world (их около 400 штук).
- поддержать не только тип aeroway aerodrome international (этот тип уже есть у нас в данных), но и aerodrome:type international
- вывод кода аэропорта в placepage, результаты поиска
=> Airport codes to search

map/routing_manager.cpp, map/routing_manager.hpp
Поправил race condition, который мог приводить к тому, что на карте оставался удаленный ранее маршрут.
Идея такова:
1. метод GetSubrouteIds() возвращал копию id, по которым производилось удаления маршрутов в методе RoutingManager::RemoveRoute().
2. После этого из другого потока мог быть вызван GetSubrouteIds() из методов: RoutingManager::UpdatePreviewMode(), RoutingManager::CancelPreviewMode(), или даже из RoutingManager::InsertRoute(), RoutingManager::RemoveRoute() и забрать id-ки, которые скоро потеряют актуальность.
3. Затем по данным id завершиться удаление в (1), но методах RoutingManager::UpdatePreviewMode() и других они будут использоваться.
Данный PR удаляет метод RoutingManager::GetSubrouteIds() и защищает мьютексом работу непосредственно с m_drapeSubroutes
@rokuz @darina PTAL
=> [release 84]  RoutingManager race codition fix which leads to leaving a route on the map.

data/replaced_tags.txt
Мы поддерживаем в типах `aeroway=aerodrome`, `aerodrome=international`, но из 474 аэропортов 79 потеганы по-старому `aeroway=aerodrome`, `aerodrome:type=international`.
Предлагаю на этапе генерации менять старый тег на новый.
https://wiki.openstreetmap.org/wiki/Tag:aerodrome:type%3Dinternational
https://taginfo.openstreetmap.org/tags/aerodrome%3Atype=international
https://taginfo.openstreetmap.org/tags/aerodrome=international
=> [generator][indexer] Replace old international airport tagging.

generator/generator_tests_support/test_mwm_builder.cpp, generator/generator_tool/generator_tool.cpp, generator/translator_planet.cpp, indexer/ftypes_matcher.hpp
Исследования показали, что кол-во дорожных фич, покрытых полигонами деревень (place=village, place= hamlet) соизмеримо  с кол-вом дорожных фич, покрытых городами. Исследования проводились на карте Беларусь, кроме Минска.
Например, 
для Belarus_Hrodna Region.mwm
до учета village и hamlet секция city_roads занимала 29368 байт, а сейчас 46840
для Belarus_Maglieu Region.mwm
до учета village и hamlet секция city_roads занимала 19144 байт, а сейчас 29400
Т.о. секцию city_roads, используемую для прокладки маршрутов имеет смысл генерировать на базе relation (type=boundary, multipolygon), у которых place=city, town, village.
Данный PR реализует это.
@maksimandrianov @tatiana-yan PTAL.
Мне не очень нравится, как я добавил в emitter генерацию границ для routing-га. Если будут лучшие идеи - пишите.
=> Generating city_roads section based on cities, town and villages.

generator/road_access_generator.cpp
Добавила тип доступа designated для конкретных видов транспорта как разрешенный, чтобы он применялся с большим приоритетом чем access=.
designated используется для обозначения что данная дорога предназначена для конкретного вида транспорта, см например
https://wiki.openstreetmap.org/wiki/RU:Tag:access%3Ddesignated
=> [routing] Add *=designated as RoadAccess::Type::Yes

search/intermediate_result.cpp
Теперь в результатах поиска будет как в PP.
Как сейчас см скриншоты в https://jira.mail.ru/browse/MAPSME-8515 в конце.
Похоже так было всегда -- в этом поле всегда была "голая" метадата и дальше она тоже нигде не переводилась.
Т.к. поиск это поле дальше нигде не использует, ничто не мешает хранить там данные сразу в читабельном формате.
После переделывания переводов кухонь на типы можно будет изменить место в котором происходит локализация (переводить на платформах там же где и типы). Переводы метадаты из индексера тащить в платформу считаю нецелесообразным.
=> [search][MAPSME-8515] Localize cuisines in search results.

feature_list/feature_list.cpp, generator/generator_tool/generator_tool.cpp, indexer/classificator.cpp, indexer/classificator.hpp, track_analyzing/track_analyzer/track_analyzer.cpp
Убрала метод Classificator::SortClassificator()
Метод сортирует в дереве типов потомков для каждого узла в зависимости от масштаба на которых они видимы и имени.
В коде приложения не вызывался, вызывался только в тулзах.
Внутри метода Classificator::ReadClassificator и так вызвыается `m_root.Sort();` который делает то же самое, поэтому нет смысла вызывать SortClassificator() после classificator::Load().
=> [indexer] Remove Classificator::SortClassificator()

generator/generator_tool/generator_tool.cpp, generator/regions/regions.cpp, generator/regions/regions.hpp
Проблема была в том, что сначала добавляется избыточная информация о регионах в tmp.mwm. Потом на этапе построения кв уже определяется точно какие регионы будут учавствовать в результатирующей выборке, а какие нет. После построения кв, можно выбрать регионы, которые есть в кв и уже его подавать на вход построения индекса.
https://jira.mail.ru/browse/MAPSB2B-2
=> [generator] Added repacking regions mwm.tmp.

generator/feature_generator.cpp, generator/feature_generator.hpp, generator/feature_sorter.cpp, generator/filter_elements.cpp, generator/geometry_holder.hpp
Первый коммит разрешает запись mwm.tmp более 4 Гб.
Второй исправляет возвращаемое значение Set::Add
=> [generator] Fixes

3party/pugixml/src/utils.hpp, generator/road_access_generator.cpp, openlr/decoded_path.cpp, openlr/openlr_stat/openlr_stat.cpp, routing/road_access.hpp, routing/road_access_serialization.hpp, routing/road_point.hpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/road_access_test.cpp, routing/turns_notification_manager.cpp
В ходе профилирования joint увидел, что среди функций работающих дольше, чем "очень быстро" есть такие две:
```cpp
routing::RoadAccess::GetPointType(routing::RoadPoint const&) const {}
routing::RoadAccess::GetFeatureType(unsigned int) const {}
```
Посмотрел, что у них внутри, а там std::map, хотя по логике нужен hash.
Поменял, посмотрел разницу:
Видно, что разница есть, предлагаю заменить на `unordered_map`.
**Плюс**: можно посмотреть на разницу в работе функций:
```cpp
routing::IndexGraph::GetPenalties(routing::Segment const&, routing::Segment const&) const {}
routing::IndexGraph::CalcSegmentWeight(routing::Segment const&) const {}
```
Они тоже ускорились (внутри себя вызывают первые две функции).
=> [routing] change map to unordered_map for RoadAccess

routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/turn_test.cpp
После сборки данных от 2018.10.19 сломались 3 интеграционные теста:
route_test.cpp::ParisCrossDestinationInForwardHeapCase
route_test.cpp::RussiaSmolenskRussiaMoscowTimeTest
turn_test.cpp::ThailandPhuketNearPrabarameeRoad
1. route_test.cpp::ParisCrossDestinationInForwardHeapCase
Тут очень тонкая причина поломки. Тест на меж mwm-й роутинг через 10 mwm. Успешно строится кросс-mwm-й маршрут, там успешно строятся все маршруты внутри mwm-ок, кроме последнего от входного сегмента mwm центра Парижа до точки в центре Парижа.
Центр Парижа: France_Ile-de-France_Paris.mwm. Входной сегмент: m_featureId = 35796, m_segmentIdx = 0 (48.899719422209074082, 2.3189024799980302305). Входной сегмент на карте: https://www.openstreetmap.org/way/32746681. Точка в центре Парижа (48.85860, 2.34784).
Проблема тут в …
=> routing integration tests fix for 2018.10.19 maps.

routing/bicycle_directions.cpp, routing/bicycle_directions.hpp, routing/features_road_graph.cpp, routing/geometry.cpp, routing/index_road_graph.cpp, routing/routing_tests/CMakeLists.txt
Везде нужна только константная ссылка на родительский по отношению к EditableDataSource класс. По факту это будет EditableDataSource, но родительский класс располагается в индексе и это позволяет роутингу не зависеть от редактора.
=> [routing] Remove editor header includes from routing

generator/search_index_builder.cpp, search/ranker.cpp, search/search_integration_tests/processor_test.cpp
Поддержка брендов будет делаться не через тег operator.
Но operator всё равно надо проиндексировать в поиске, чтобы лучше искать заправки и банкоматы.
=> [search] Index operator tag for search.

routing/segment.hpp
Каждый раз в напрягает в логах читать: `Segment(100, 1231, 1, 0)`, мне кажется было бы удобнее видеть направление сегмента в явном виде: `Segment(100, 1231, 1, false)`
=> [routing] Boolalpha for segment

.gitignore
В gitignore есть секция vim со строчкой tags. В iOS мы создали папку с ресурсами с таким же названием - она заигнорилась. Есть предложение удалить или модифицировать эту строчку, чтобы не возникало в дальнейшем подобных проблем.
=> remove tags from gitignore

indexer/data_source.cpp, indexer/data_source.hpp, indexer/feature_covering.hpp, search/ranker.cpp, search/reverse_geocoder.cpp, search/reverse_geocoder.hpp
Функция восстановления адреса работала так:
1. мы брали все фичи в радиусе 500 метров
2. для каждой фичи проверяли дом ли она
3. если дом, клали в массив
4. потом сортировали
5. потом оставляли 10 ближайших
6. потом для каждого из оставшихся домов искали улицы (тоже поднимали все фичи в радиусе 500 метров и т.п.)
7. потом в части случаев, если расстояние от результата поиска до дома больше 0 всё это выкидывали
сделала 2 вещи:
- если нужно точное попадание в дом, то ищем точное попадание (это дешевле, на шаге 6 вызываем поиск улицы для меньшего кол-ва домов)
- ищем дома при помощи CoveringMode::Spiral, что позволяет найти ближайшие дома и остановиться -- не поднимать все фичи в радиусе 500 метров
Ещё довольно много времени уходит на поиск улиц, но способ хранения информации об улице …
=> [search] Faster GetAddress for ranker and reverse geocoding.

CMakeLists.txt, defines.hpp, descriptions/CMakeLists.txt, descriptions/descriptions_tests/CMakeLists.txt, descriptions/descriptions_tests/descriptions_tests.cpp, descriptions/header.hpp, descriptions/loader.cpp, descriptions/loader.hpp, descriptions/serdes.cpp, descriptions/serdes.hpp, kml/visitors.hpp
Реквест добавляет серилизатор и десереализатор секции, которая будет хранить в себе описания фич. Предполагается, что описание фичи будет показываться в PP, т.е. основной сценарий - точечная вычитка описания для одной фичи и конкретного языка. В описании может храниться строки для разных языков, которые могут быть как короткими, так и достаточно длинными (полная статья из википедии).
Для хранения строк рассматривался вариант хранения переводов описания в строке MultilangUtf8String, которая используется, например, для хранения имен фич.
Поскольку длина описания может быть большой, и нет необходимости вычитывать все доступные переводы, то хранение переводов в MultilangUtf8String не выглядит оптимальным.
В предложенном варианте метаинформация о доступных языках описания и сами строки …
=> [descriptions] Description section serializer and deserializer added.

routing/geometry.hpp
Реализация 2 буферов для двух волн A* не дали ожидаемого эффекта. Добавил комментарий об этом. Ниже время запуска всех интеграционных тестов у меня на машине. Каждый эксперимент, кроме 2 буфера по 500К проводился трижды.
----------
1 буфер в 5К элементов
1th try. All tests take 276.631 seconds.
2th try. All tests take 257.073 seconds.
3th try. All tests take 257.136 seconds.
----------
2 буфера в 500 элементов
All tests take 470.91 seconds.
2 буфера по 2К элементов.FIXED
All tests take 270.481 seconds.
All tests take 274.045 seconds.
All tests take 274.631 seconds.
2 буфера по 2.5К элементов.FIXED
All tests take 272.869 seconds.
All tests take 271.721 seconds.
All tests take 271.761 seconds.
2 буфера по 3K элементов.FIXED
All tests take 286.565 seconds.
All tests take 270.296 seconds.
All …
=> [routing] Adding comment about two geom caches for bidirectional A*.

coding/coding_tests/geometry_serialization_test.cpp, coding/coding_tests/point_coding_tests.cpp, coding/point_coding.hpp, drape_frontend/gui/ruler_helper.cpp, drape_frontend/gui/ruler_helper.hpp, drape_frontend/my_position_controller.cpp, drape_frontend/rule_drawer.cpp, editor/server_api.cpp, generator/feature_builder.cpp, generator/generator_tests/triangles_tree_coding_test.cpp, geometry/geometry_tests/mercator_test.cpp, geometry/mercator.cpp, geometry/mercator.hpp, indexer/data_source_helpers.cpp, indexer/feature_covering.hpp, map/address_finder.cpp, map/extrapolation_benchmark/extrapolation_benchmark.cpp, map/framework.cpp, platform/location_service.cpp, routing/route.cpp, routing/routing_quality/waypoints.cpp, routing/routing_tests/turns_generator_test.cpp, search/geometry_cache.cpp, search/geometry_utils.cpp, search/geometry_utils.hpp, search/house_detector.cpp, search/house_detector.hpp, search/processor.cpp
In was used as eps in meters in some cases and eps in mercator in others.
Its value was hard to justify and so were its use cases. We're better off
with less epsilons for now.
Also renamed Metres to Meters in the mercator code.
=> [coding] Removed the CellId epsilon.

descriptions/descriptions_tests/descriptions_tests.cpp, descriptions/serdes.cpp, descriptions/serdes.hpp
Добавлены тесты:
* запись и чтение секции, которая начинается не в начале буфера (sink.Pos() в начале кода сериализации не равен 0);
* запись и чтение секции, содержащей html-фрагменты на 24 языках.
Добавлены CHECK-и, проверяющие что:
* сериализатор принимает непустую коллекцию DescriptionsCollection;
* строки FeatureDescription::m_description типа StringUtf8Multilang не могут быть пустыми и не могут содержать пустых переводов.
Валидность языковых кодов внутри StringUtf8Multilang должна быть проверена на генераторе, т.к. перевод, добавленный с невалидным отрицательным кодом языка, читается как перевод с неверным положительным кодом языка.
=> [descriptions] Descriptions tests added.

android/jni/com/mapswithme/maps/LightFramework.cpp, iphone/Maps/Core/Notifications/LocalNotificationManager.mm, map/CMakeLists.txt, map/bookmark_manager.cpp, map/bookmark_manager.hpp, map/framework_light.cpp, map/framework_light.hpp, map/map_tests/framework_light_tests.cpp, map/user.cpp, map/user.hpp, ugc/storage.cpp, ugc/storage.hpp, ugc/ugc_tests/storage_tests.cpp, xcode/map/map.xcodeproj/project.pbxproj
Сейчас оказалось, что для того, чтобы использовать легковесный фреймворк в двух местах, потребуется дописать ко всем специализациям метода Get слово inline. Иначе ругается на дублирование методов.
Мне показалось, что лучше сделать обычные методы.
Это все равно когда-нибудь пришлось бы сделать.
=> [lightweight] "Get" methods are renamed

generator/feature_builder.cpp, generator/generator_tests/feature_builder_test.cpp, generator/osm2type.cpp, generator/osm2type.hpp, generator/translator_planet.cpp, indexer/feature_visibility.cpp, indexer/feature_visibility.hpp
У нас для невидимых типов существовало 2 варианта поведения: 
* либо мы удаляем тип из объектов вообще: без специальных костылей от amenity=cafe + internet_access=wlan + cuisine=vegeterian, осталось бы только amenity=cafe при эмите
* либо мы невидимый тип считаем видимым везде и всегда, даже если других видимых тегов нет, на любом зуме и т.п. -- объект wheelchair=yes без каких-либо ещё тегов заэмитится на всех уровнях зума.
В этом реквесте делаю третий вариант поведения -- типы для cuisine, wheelchair, hwtag, psurfaсe оставляем, если у объекта есть другие видимые типы. То есть на кафешках у которых есть тег cuisine он останется, без кафешки объект с cuisine но без других типов эмититься не будет. wheelchair=yes без других типов эмититься не будет (с другими типами -- будет). То же самое …
=> [index][generator] Separate TypeAlways exist. Distinguish always existing types from nondrawable types which we do not want to remove.

routing/routing_integration_tests/turn_test.cpp, routing/segment.hpp, routing/turns_generator.cpp
В случае, если маршрут следует по большой дороге мимо маленьких мы не генерируем маневра. Размер дороги определяется перечислением ftypes::HighwayClass. Это не что иное, как объединение значений тага highway в несколько категорий:
``` c++
// Highway class. The order is important.
// The enum values follow from the biggest roads (Trunk) to the smallest ones (Service).
enum class HighwayClass
{
Undefined = 0,  // There has not been any attempt of calculating HighwayClass.
Error,          // There was an attempt of calculating HighwayClass but it was not successful.
Trunk,
Primary,
Secondary,
Tertiary,
LivingStreet,
Service,
Pedestrian,
Transported,    // Vehicles are transported by train or ferry.
Count           // This value is used for internals only.
};
```
Данный PR вводит уточнение к …
=> [routing] Removing go straight in case of going pass by smaller roads.

routing/base/astar_algorithm.hpp, routing/cross_mwm_index_graph.hpp, routing/world_graph.cpp
Данный PR фиксит некоторые крэши, связанные с тем, что при переходе из одной mwm в другую, если mwm разные, то переходная фича могла иметь разную геометрию, из-за этого мог падать иногда A*.
Добавил функцию - `FilterTwinsByGeometry` в `WorldGraph`, которая проверяет, что twin'ы идентичны по геометрии с исходным сегментом. Добавил эту функцию в `WorldGraph` потому что она общая у `SingleVehicleGraph` и `TransitWorldGraph`
=> [DNM] [routing] add twins checker

routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/turn_test.cpp, routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp, routing/routing_quality/routing_quality_tests/passby_roads_tests.cpp, routing_common/bicycle_model.cpp, routing_common/bicycle_model.hpp, routing_common/car_model.cpp, routing_common/car_model.hpp, routing_common/pedestrian_model.cpp, routing_common/pedestrian_model.hpp, routing_common/routing_common_tests/vehicle_model_test.cpp, routing_common/vehicle_model.cpp, routing_common/vehicle_model.hpp
Сейчас если у фичи есть maxspeed, он используется для задания веса дуги и eta безусловно. Но в ряде случаев (см. тесты ниже) это дает плохие результаты. Это происходит, если у дорог разных категорий задан один и тот же maxspeed, но при этом по дорогам более низкой категории можно доехать короче.
Данный PR исправляет эту ситуацию, что подтверждает ряд routing integration tests и routing quality tests. Он позволяет задать коэффициент для maxspeed в зависимости от highway класса.
Данный PR позволяет вернуть целый ряд outing integration tests и routing quality tests:
RussiaMoscowLenigradskiy39GeroevPanfilovtsev22TimeTest
ETA маршрута увеличено, что в данном случае ближе к правде.
StPetersburgSideRoadPenaltyTest
Не срезаем по дублеру
RoutingQuality_RussiaMoscowTushino
Не срезаем через дворы. …
=> [routing] Adding maxspeed factors for highway classes.

routing/routing_session.cpp, routing/routing_tests/routing_session_test.cpp
Ранее мы перепрокладывали маршрут, когда текущая позиция двигалась только по направлению от маршрута. Данный PR исправляет следующую проблему. Текущая позиция прыгает далеко от маршрута. Маршрут прокладывается. Затем пользователь движется к маршруту и маршрут не перепрокладывается.
@vmihaylenko, @gmoryes PTAL
=> [routing] Route rebuilding when current position is moving to the route.

search/processor.cpp, search/ranker.cpp, search/ranker.hpp
Для категорийных запросов как правило ближайшие результаты наиболее релевантны.
Сейчас в выдаче получается 10 результатов (размер батча) из ближайшей mwm, а дальше результаты до которых 100 км. Предлагаю как и для поиска во вьюпорте не ограничивать количество эмита из текущей mwm для категорийных запросов.
=> [search] Do not limit ranker batch size for categorial requests.

routing/CMakeLists.txt, routing/cross_mwm_graph.cpp, routing/cross_mwm_graph.hpp, routing/cross_mwm_index_graph.hpp, routing/transition_points.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Удалил код из CrossMwmGraph, связанный с поискам переходных сегментов через геометрию. Дальше удалил те, что использовались только в удаленном коде
=> [routing] delete useless code from CrossMwmGraph

search/ranker.cpp, search/search_integration_tests/ranker_test.cpp, search/search_tests_support/test_results_matching.cpp, search/search_tests_support/test_results_matching.hpp
Сейчас, если нашлось много дубликатов, можем заэмитить 2-3 результата из mwm. Получается мало результатов из текущей mwm, сразу результаты за 100 км.
=> [search] Count duplicate results ones for batch.

routing/routing_integration_tests/turn_test.cpp, routing/turns_generator.cpp
Бывают ситуации, когда из точки бифуркации при генерации терна выходит только 2 пути (по одному маршрут, по другому дополнительный). При том сам терн сгенерирован, как CarDirection::GoStraight. При этом оба пути идут прямо или почти прямо. Т.е. второй путь (CarDirection::TurnSlightLeft, CarDirection::GoStraight, CarDirection::TurnSlightRight). Это весьма типичная ситуация, при развилках на крупных дорогах.
В этом случае, если нам нужно ехать по левой дороге мы будем говорить CarDirection::TurnSlightLeft, а если по правой, то CarDirection::TurnSlightRight.
Данный PR повлиял на 2 интеграционных теста и оба улучшил.
RussiaMoscowSvobodaStTest
NetherlandsBarneveldTest
Также добавил еще один routing integration test.
Задача: 
https://jira.mail.ru/browse/MAPSME-9234
Поправлено так же: …
=> [routing] Straight turn correction in case of two go straight or slight ways out.

android/jni/com/mapswithme/core/jni_helper.hpp, base/buffer_vector.hpp, coding/coding_tests/string_utf8_multilang_tests.cpp, coding/string_utf8_multilang.cpp, coding/string_utf8_multilang.hpp, data/countries_meta.txt, map/map_tests/transliteration_test.cpp
Сейчас у нас нет возможности добавить в StringUtf8Multilang новый язык, т.к. поддерживается максимум 64 и все 64 заняты (латынью, эсперанто, верхнелужским языком и т.п.). Например, у нас приложение переведено на датский, норвежский, инденезийский, но в StringUtf8Multilang этих языков нет и нет возможности их сейчас добавить.
Предлагаемое решение такое: задеприкейтить часть непопулярных языков, подождать несколько сборок данных (т.к. они в данных), переиспользовать их места для более популярных.
Языки, которы я планирую задеприкейтить помечены красным:
https://docs.google.com/spreadsheets/d/1COkejwPUhZYNeQx8ky2iNrcOskicHUVMMmZUMjO5t78/edit#gid=0
=> [coding] Deprecate unpopular languages to add more relevant ones.

routing/speed_camera_manager.hpp
https://jira.mail.ru/browse/MAPSME-9278
Если у камеры нет скорости, то мы по умолчанию считаем, что она опасная, если мы находимся на расстоянии 450 + 50 метров. 50 метров было мало, чтобы четко разграничить beepZone и voiceZone, поэтому я увеличил ее до 150 метров, чтобы предупреждали голосом чуть заранее.
Последствие плохой разграниченности - на анроиде звуковой сигнал не воспроизводился, потому что в этот момент играл голосовой, как итоге у пользователя не было звукового вообще, на айфоне не проверял, но, основываясь на то, как там написано, там было бы параллельное воспроизведение двух звуков
=> [DNM] [routing] increase distance for reducing speed before camera without maxpeed data

routing/routing_integration_tests/route_test.cpp
Поправил routing integration test для карты 181213. DNM, т.к. для мержа в релиз требуется одобрение @burivuh 
После перехода на карту 181213 немного изменилась длина маршрута через Ла-Манш. С 64688.5 метров до 64693.6. 60498 попадало в диапазон 64688.5 +/- 7%, но не попадает в диапазон 64693.6 +/- 7%.
Сейчас маршрут выглядит так:
=> [routing] Routing integration test for maps 181213.

drape_frontend/base_renderer.cpp
Исправлен баг привнесенный в коммите https://github.com/mapsme/omim/commit/60e4545dbd7c4fa387f4aafdcc2cd5f1e964aeab
Фильтр сообщений надо снимать до того, как оповещен UI-поток. Иначе происходит гонка по сообщениям
https://jira.mail.ru/browse/MAPSME-9251
=> [drape][android] Fixed message filtering on context restoring

coding/CMakeLists.txt, coding/coding_tests/CMakeLists.txt, coding/coding_tests/map_uint32_to_val_tests.cpp, coding/map_uint32_to_val.hpp, indexer/centers_table.cpp, indexer/centers_table.hpp, xcode/coding/coding.xcodeproj/project.pbxproj
Переношу в coding, чтобы переиспользовать для кодирования house to street.
Т.к. все оффсеты и т.п. считаются для centers table от начала секции, для сохранения обратной совместимости переношу всё включая header(version и т.п.).
=> [coding] Move Elias-Fano based map encoding/decoding to coding library.

routing/async_router.cpp, routing/routing_integration_tests/route_test.cpp, routing_common/maxspeed_conversion.cpp
В случае дорог с maxspeed=none (без ограничений) мы брали скорость 1000км/ч.
https://jira.mail.ru/browse/MAPSME-9358
=> [release-86][routing] ETA fix for maxspeed=none.

routing/routing_integration_tests/speed_camera_notifications_tests.cpp, routing/speed_camera_manager.cpp, routing/speed_camera_manager.hpp
1) Теперь в коде `ближайшая камера` == `текущая красная камера в UI`.
2) Пофиксил баг, когда превышаем + проезжаем камеру и скорость перестает быть красной, несмотря на то, что мы все еще в зоне.
Суть: теперь если мы проезжаем камеру и, в километре от нас есть следующая камера, то мы сразу же переключаемся на нее, иначе камера которую мы проехали горит до тех пор, пока мы не выйдем из зоны.
=> [routing] Fix searching closest camera on route + hightliting

tools/unix/check_cert.sh
This disables checking of user certificate expiring soon.
The check should be enabled back when GDPR requests feature will be
launched.
=> [tools][GDPR][dirty-hack] disable certificate checking

iphone/Maps/Classes/CustomViews/NavigationDashboard/MWMNavigationDashboardManager.mm, routing/async_router.cpp
В ситуации, когда одна или несколько мвмок отсутствует при кросс мвмном роутинге, нам приходит код RouteNotFound, что кажется правильным. Из за ```if (!absent.empty() && code == RouterResultCode::NoError)``` мы не проставляли нужный код, поэтому второе условие в if убрал. 
из за этой ситуации у нас был баг https://jira.mail.ru/browse/MAPSME-8837
=> [routing] Correct routing error when some mwms are absent.

routing/routing_integration_tests/routing_test_tools.cpp
```cpp
namespace
{
void Function()
{ 
int asd = 5;
}
}
```
Became:
```cpp
namespace
{
void Function()
{ 
int asd = 5;
}
}
```
=> [routing] Remove useless spaces

routing/speed_camera_manager.cpp
По мотивам таска: https://jira.mail.ru/browse/MAPSME-9286
В speedlimit отсылался char, и в интерфейсе показывается ">" вместо 60
=> [routing] fix send to aloha a char

configure.sh
Sources can be obtained via download of tarball from github,
and in that case git rev-parse is not possible.
Also, every path in script is not dependent on current workdir.
=> Remove requirement to build from a git checkout

indexer/feature_visibility.cpp
Продолжаю исправлять двойные эмиты фичей и эмиты на неверных масштабах.
В этом реквесте переношу junction-roundabout из типов которые эмитятся везде, всегда, на любом масштабе в типы, которые эмитятся если у фичи есть отображаемый на данном масштабе тип.
Так как для работы junction-roundabout в роутинге требуется, чтобы у дороги был также дорожный тип (highway-* и т.п.) и этот тип является отображаемым, мы не потеряем junction-roundabout для роутинга.
Собрала некоторые карты из этого реквеста, проверила роутинг (сами маршруты и манёвры):
LOG TID(10) DEBUG     116.278 routing/turns_generator.cpp:576 MakeTurnAnnotation() Shortest th length: 147.375
LOG TID(10) DEBUG     116.279 routing/turns_generator.cpp:655 MakeTurnAnnotation() EnterRoundAbout : 4 улица Серёгина -  exit: 4
LOG TID(10) …
=> [indexer] Do not force emit junction-roundabout feature type.

search/processor.cpp, search/ranker.cpp
В конце прошлого года выключила сравнение запроса с именем фичи для категорийного поиска при ранжировании (вычисление количества опечаток и т.п.).
В этом реквесте сделала то же самое при отображении результата: больше не выбираем какое имя отображать на основе сравнение ответа с запросом -- берём исходя из предпочтительных языков.
Подсветку частей запроса в результатах тоже выключила.
=> [search] Do not match name to request while displaying categorial results.

routing/CMakeLists.txt, routing/cross_mwm_connector.hpp, routing/cross_mwm_graph.cpp, routing/cross_mwm_graph.hpp, routing/cross_mwm_index_graph.hpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter_joints.cpp, routing/index_graph_starter_joints.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/joint_segment.cpp, routing/joint_segment.hpp, routing/road_index.cpp, routing/road_index.hpp, routing/road_point.hpp, routing/segment.hpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, routing/world_graph.cpp, routing/world_graph.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Первая версия `JointSegment`. 
`JointSegment` - это прыжок в рамках одной фичи по подряд идущим сегментам.
`routing_integration_tests` полностью прошли, статистика в ссылка на confluence.
Oсновные изменения:
1) routing/joint_segment.[hpp|cpp]
2) routing/index_graph_starter_joints.[hpp|cpp]
3) routing/index_router.cpp
4) routing/single_vehicle_world_graph.cpp
Также был немного затронут `cross_mwm_graph`, так как по умолчанию мы не знаем транзитная фича или нет, а мне это надо было знать.
`astar_algorithm.hpp` никак не затронут, все нужное получилось уместить в `index_graph_starter_joints`
https://confluence.mail.ru/display/MAPSME/Joints+Routing
=> [routing] New IndexGraphStarterJoints, JointSegment, jumps between segments.

generator/search_index_builder.cpp, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, indexer/search_string_utils.cpp, indexer/search_string_utils.hpp, map/map_tests/address_tests.cpp, search/house_detector.cpp, search/reverse_geocoder.cpp, search/reverse_geocoder.hpp, search/search_tests/house_detector_tests.cpp
Небольшие улучшения по матчингу улиц. Помогают распознать примерно четверть нераспознанных улиц (1.7% -> 1.3% для прямоугольника вокруг Москвы).
=> [search] Improve streets matching for HouseToStreet table.

routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp
План таков. Включаем использование высот для интеграционных тестов в этом PR.
Потом учитываем высоту и уточняем коэффициенты для пешего и вело роутинга. Следующий PR.
@tatiana-yan @vmihaylenko PTAL
=> [routing] Switching on altitude for routing integration tests for pedestrian and bicycle routing.

routing/edge_estimator.cpp, routing/index_router.cpp, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/routing_test_tools.hpp
Утяжелил дуги, идущие вверх в случае пешеходного и вело маршрутов.
В случае высокогорья (более 3000 метров над уровнем моря) утяжелил еще сильнее подъемы. Поскольку особенно тяжело идти вверх в таких условиях. 
Добавил тесты.
@tatiana-yan @vmihaylenko PTAL
=> [routing] Adding weight for walking up and riding up in case of pedestrian and bicycle routing.

map/bookmark_manager.cpp
Если экспортировать как файл пошаренную в каталог категорию, то она ни у кого не импортируется. Данный реквест это исправляет.
=> [bookmarks] Fixed KMZ importing

search/geocoder.cpp, search/idf_map.hpp, search/locality_scorer.cpp, search/locality_scorer.hpp, search/search_tests/locality_scorer_test.cpp
При определении топа населённых пунктов, соответствующих запросу, в LeaveTopByNormAndRank idf расчитывался по точному совпадению слова с запросом (без опечаток), а затем фичи брались для неточного совпадения слова с запросом.
Например при запросе "The Villages, Florida" определяется df для the (много, не значимый токен), villages (2 в world, очень значимый токен) и florida (20 в world, не очень значимый токен), после чего по villages из world.mwm вытаскиваются все фичи содержащие village или что-то подобное (>100 штук), им назначается idf исходя из встречаемости "villages" (очень высокий) и они забивают в LeaveTopByNormAndRank всю флориду.
В данном реквесте df для токенов из запроса считается исходя из того, сколько документов вытаскивается из карты для этого токена. Т.к. считать с …
=> [search] Make idf for localities consistent.

openlr/decoded_path.cpp, openlr/decoded_path.hpp, openlr/openlr_match_quality/openlr_assessment_tool/mainwindow.cpp, openlr/openlr_match_quality/openlr_assessment_tool/segment_correspondence.cpp, openlr/openlr_match_quality/openlr_assessment_tool/segment_correspondence.hpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_mode.cpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_mode.hpp, openlr/openlr_match_quality/openlr_assessment_tool/traffic_panel.cpp, openlr/paths_connector.cpp
Для корректной разметки необходимо видеть значение опциональных параметров olr:positiveOffset/olr:negativeOffset в утилите для разметки.
=> Displaying positive and negative offsets for edges in openlr assessment tool.

generator/camera_info_collector.cpp, generator/camera_info_collector.hpp, generator/generator_tool/generator_tool.cpp
Согласно https://confluence.mail.ru/display/MAPSME/Speed+cameras#Speedcameras-SpeedCamdetectorlawsinseveralcountries камеры скорости должны быть удалены из ряда стран. Данный PR реализует это.
https://jira.mail.ru/browse/MAPSME-9705
@gmoryes @vmihaylenko PTAL
=> Removing speed cameras from Turkey, Switzerland, Macedonia, Cyprus.

data/categories.txt, indexer/feature_visibility.cpp
При добавлении типа для sponsored объектов была сделана ошибка: они индексируются на низких уровнях зума, в результате чего вытесняют на своём уровне зума вообще всё, даже то что согласно zindex не должны вытеснять (например, станции метро). Для cuisine, wheelchair и surface она была недавно исправлена (https://github.com/mapsme/omim/pull/9933). В этом реквесте аналогичное исправление для sponsored.
@maksimandrianov собери пожалуйста несколько карт из этого реквеста или скажи мне где взять hotels.csv. Хочу на более "боевых" данных вручную проверить как всё будет выглядеть и вытесняться: рейтинги и т.п. на это влияют.
=> [indexer] Fix sponsored types displacement.

storage/diff_scheme/diff_manager.cpp, storage/diff_scheme/diff_manager.hpp, storage/storage.cpp
Suppose that a user has one mwm and the app has been updated.
It now offers to download the diff, however instead
the user deletes the map and tries to download it again.
The download fails because according to the DiffManager it's
not the mwm but the mwmdiff that should be downloaded which
results in a size mismatch. Moreover, if the download is retried,
the diff is downloaded (because the MapOptions are correct now)
but it cannot be applied because the old mwm has already been removed.
The problem is that we do not account for the change in mwm status
since the start of the application (and, in particular, the DiffManager)
when taking the decision whether to download a diff or a full mwm.
=> [storage] Removing the deleted country from DiffManager.

generator/camera_info_collector.cpp, generator/camera_info_collector.hpp, generator/generator_tool/generator_tool.cpp, routing/CMakeLists.txt, routing/index_router.cpp, routing/index_router.hpp, routing/route.cpp, routing/route.hpp, routing/routing_integration_tests/route_test.cpp, routing/speed_camera_prohibition.cpp, routing/speed_camera_prohibition.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Предупреждение о странах, где камеры скорости запрещены. Часть ядра.
https://jira.mail.ru/browse/MAPSME-9708
@gmoryes @alexzatsepin @beloal PTAL
P.S. Так же, планирую добавить routing integration test на добавленные методы.
=> Adding methods for getting info if route crosses mwm where warnings about speedcams are prohibited.

routing/speed_camera_manager.cpp
Когда в меню выбрано "Камера скорости -> Никогда" необходимо отключать подсветку камер скорости на маршруте. Если настройка возвращается в отличное от "Никогда" положение, подсветка должна быть снова включена. 
https://jira.mail.ru/browse/MAPSME-9706
@gmoryes @vmihaylenko PTAL
=> [routing] Switch off speed camera highlighting in case SpeedCameraManagerMode::Never.

generator/feature_sorter.cpp
При сборке карт камеры должны теперь удаляться и из геометрии для Turkey, Switzerland, Macedonia and Cyprus. Т.е. на экране не будет даже черных камер в режиме движения в этих странах.
https://jira.mail.ru/browse/MAPSME-9705
@gmoryes @maksimandrianov PTAL
=> Removing speed cameras from geometry index for Turkey, Switzerland, Macedonia and Cyprus.

search/categories_cache.cpp
For example, LocalitiesCache is a CategoriesCache that uses IsLocalityChecker.
This checker truncates types to the 2nd level,
thus accepting "place-city-capital" as "place-city".
On the other hand, before this commit only "place-city" was being added
to the categories cache and now we add the whole subtree.
=> [search] Made the categories cache more permissive.

geocoder/hierarchy.hpp
Для 6814442 entries (только Россия) экономит 266 Mb RSS: 8.1g -> 7.8g
=> [geocoder] Add memory optimization

android/jni/com/mapswithme/maps/LightFramework.cpp, iphone/Maps/Core/Notifications/LocalNotificationManager.mm, map/framework.cpp, map/framework.hpp
Оказалось, что у нас могут вместе существовать легковесный и обычный фреймворки.
Из-за этого файл нотификаций оказывается разделяемым ресурсом для обоих фреймворков, и изменения, сделанные легковесным фреймворком не учитываются тяжелым и перезаписываются. 
https://jira.mail.ru/browse/MAPSME-9916
=> [RELEASE ONLY] notifications fix

geocoder/hierarchy.cpp, geocoder/hierarchy.hpp, geocoder/hierarchy_reader.cpp
Не индексируются улицы и строения без насел. пункта.
На данных от 2018-12-14, только по России, отфильтровалось:
[2019-03-07 13:10:55.247717] [0x00007fe17ba83780] [info]    Street entries without a locality name: 44220     
[2019-03-07 13:10:55.247722] [0x00007fe17ba83780] [info]    Building entries without a localtity name: 1571536
Осталось:
[2019-03-07 13:10:55.247667] [0x00007fe17ba83780] [info]    Entries loaded: 5198686
Так много выбросили из-за некачественной генерации jsonl.
По памяти экономия составила 1.5Gb: 8.1g -> 6.7g
=> [geocoder] Optimize CPU: skip streets/buildings without locality

geocoder/index.cpp
Не индексирует улицы состоящие только из служебного слова: улица, набережная, ...
Сильно ускоряет запросы, где присутствуют такие служебные слова.
На примере quality_control.py (посл. колонка - время):
До:
Processed rows                        	10000	193.464906
После:
Processed rows                        	10000	81.060932
=> [geocoder] Optimize CPU: no index street synonym only

android/src/com/mapswithme/maps/MwmActivity.java
nSearchController.hide() could throw a NullPointerException. Furthermore, the check later would then be redundant and should be moved earlier.
=> Fixed possible NullPointerException mSearchController

android/src/com/mapswithme/util/log/ZipLogsTask.java
If an exception would be thrown, the streams would not be closed. The use-try-with-resources will close the resources. Therefore, the `out.close()` has also become unnecessary.
Furthermore, some streams were never closed. All resources will now be closed using the try-with-resources statement.
In my commit messages, I falsely used the words 'memory leak' which should have been 'resource leak'.
⚠️ IMPORTANT: This change assumes the use of Java SE7 or higher.
=> [android] Resource leak in ZipLogTask

data/categories.txt
Improved the translations for Dutch and German by adding new translations, fixing some wrong translations, and reordering some of the translations.
*Below the most important remarks of changes are listed. The changes with warning signs may need an extra review or contain a question.*
A few remarks for the Dutch translations:
- The earlier  used 'autodelen' for 'car sharing' is probably not the most common phrase in Dutch. 'Carpool' is a better translation, as this is the known concept for sharing your car.
- Hospital received an extra synonym for Belgian people. In the Netherlands (Holland) this word is not used, however, Belgian people may use 'hospitaal' as a synonym for 'hospital'.
- The translation of 'Dumpster|trash' was now translated in Dutch as 'uitschot'. This word is more used …
=> Categories.txt improved Dutch and German translations

android/src/com/mapswithme/maps/bookmarks/data/CatalogTag.java
Changes:
* In CatalogTag.java the equals method contained two identical evaluations of equals with an OR. Here I assumed the `mId` to be unique and, therefore, no more checks are required. Alternatively, the `mLocalizedName` could be included in the equality, as well as the `mColor`.
=> [android] Removed identical check in equals

android/src/com/mapswithme/maps/location/PlatformSocket.java
Length can not return a value less than 0, therefore this check is not needed.
Some analysis using Sonar Cube revealed this condition check in the code.
I have signed the CLA btw.
=> Unnecessary length check removed

tools/python/openlr/quality.py
При оценка качества метчинга, печатаем id сегментов, которые замачились, хотя помечены как те, которые замачины быть не должны.
=> False positive matching investigation. Printing openlr ids for segments which are mark as ignored but still matched.

routing/index_graph.cpp
У нас запреты проезда находятся на разных фичах, поэтому 
1) не имеет смысла проверять сегменты одной фичи
2) имеет смысл проверить только один раз в начале построения JointSegment
3) для no_u_turn это и так и так неправильно работает, но сейчас будет быстрее
Для сравнения, если взять длинный маршрут Москва - Минск и построить его в режиме NoLeaps (просто пустить две волны в лоб), то будут такие результаты:
=> [routing] Make restrictions checking faster

drape_frontend/apply_feature_functors.cpp, drape_frontend/apply_feature_functors.hpp, drape_frontend/area_shape.cpp, qt/place_page_dialog.cpp
У некоторых 3Д-зданий пропадают стены, так генератор создает для них вырожденные треугольники, для которых нельзя точно определить обход вершин. Если части таких треугольников формируют опоясывающую здания, то создаем ""двухсторонние" полигоны.
https://jira.mail.ru/browse/MAPSME-3018
https://jira.mail.ru/browse/MAPSME-5362
=> [drape] Fixed some buildings rendering

routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/restriction_test.cpp
Есть два типа restrictions - No, Only. В коде мы используем только No, то есть проверяем, что нам нельзя проехать с фичи A на фичу B. 
Про Only мы не забываем, в момент загрузки секции с restrictions, мы конвертируем их в No 
( если из фичи 1 можно проехать в 2,3,4, и есть Only из 1 в 3, это означает, что нам надо добавить No из 1 в 2, из 1 в 4). 
В тестах же по какой-то причине не было конвертации из Only в No, что делало эти тесты не корректными, я добавил везде, где тестируется Only, конвертацию и добавил еще один тест на проверку Only
=> [routing] repair restrictions tests, add one test

drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/user_event_stream.cpp, drape_frontend/user_event_stream.hpp, map/framework.cpp, map/framework.hpp
Для CarPlay потребовалась возможность двигать карту с помощью кнопок вверх/вниз/влево/вправо.
Во фреймворк добавлен метод
`void Framework::Move(double factorX, double factorY, bool isAnim);`
где `factorX` и `factorY` - коэффициенты перемещения по осям.
Например, `factorX == 1.0` перемещает карту на один экран вправо, `factorX == -0.5` на пол-экрана влево, `factorY == 1.5` на полтора экрана вверх, `factorY == -0.33` на треть вниз.
=> Added new user event Move for scrolling the map by buttons.

tools/unix/generate_planet.sh
В чем проблема - если на какой-то машине нет `python36` или `python3.6`, но есть `python3`, который на самом деле python версии 3.7, то `generate_planet.sh` сразу вылетает, так как `which` возвращает ненулевой код ошибки, этот PR исправляет такое поведение
вывод переменных на mm5:
```bash
/usr/bin/python36
/usr/bin/python2.7
```
На моем маке:
```bash
/opt/local/bin/python
/usr/local/bin//python3
```
=> [generator] find python with bash

generator/generator_tests_support/test_feature.cpp, generator/generator_tests_support/test_feature.hpp, indexer/indexer_tests/scale_index_reading_tests.cpp, search/locality_finder.cpp, search/mwm_context.hpp
При определениии принадлежности результата к деревне сейчас перебираются все фичи на площащи 16км^2 вокруг результата. Для городов это довольно много фичей, это самая дорогая операция после кеширования идентификаторов фичей из вьюпорта (для густо замапленных городов 20-25% от времени первого поиска, дальше может быть лучше, если результаты попадают примерно в те же места).
Предлагается перебирать не все фичи, а только фичи до 13 зум левела, на котором заиндексированы все деревни. Для Москвы это ускоряет этап поиска Locality в 3-4 раза, для Токио в 5-6 раз.
=> [search] Load villages from villages min drawable scale while getting search result locality.

iphone/Maps/Classes/MapsAppDelegate.mm, iphone/Maps/main.mm
AppsFlyer module name has been changed during migration from carthage to cocoapods
=> [iOS] fix iOS release build

tools/python/openlr/quality.py
При вычислении мат ожидания и дисперсии мечинга openlr сегментов мы не учитывали сегменты, которые помечены как ignored. Данный PR обеспечивает учет ignored сегментов при матечиге следующим образом. Если PR помеченный, как ignored помечен, во что-то то он оценивается как полностью не совпавший. Если он ни помечен не во что, то как полностью совпавший.
=> Taking into account ignored segments while calculation mean and std in quality.py.

generator/routing_index_generator.cpp, routing/base/astar_algorithm.hpp, routing/base/astar_graph.hpp, routing/index_graph_starter.hpp, routing/index_graph_starter_joints.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing_tests/applying_traffic_test.cpp, routing/routing_tests/astar_algorithm_test.cpp, routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp, routing/routing_tests/routing_algorithm.cpp
Сейчас есть куча графов и почти каждый пытается использоваться в качестве графа, который можно использовать в AStarAlgorithm.
Points of pr:
1) В процессе работы над restriction, мне необходимо вызывать какие-то методы изнутри AstarAlgorithm, было бы удобно иметь интерфейс, в котором можно прописать методы по умолчанию, и не добавлять в 20 мест по коду ф-ию заглушку (и без добавлений 10-ой лямбды)
2) Это упрощает, на мой взгляд, код, в том в плане, что четко понятно, какой граф у нас используется в AStar, а какой нет.
Например такие вещи, как WorldGraph, которые идеологически не должны быть в AStarAlgorithm, больше в нем и не используются. 
Тот факт, что WorldGraph не используется - это скорее опциональное (можно было и без этого PR сделать), но теперь это явно видно
=> [routing] create interface for graph to AStar

android/build.gradle, android/jni/com/mapswithme/maps/editor/Editor.cpp, coding/internal/file64_api.hpp
https://jira.mail.ru/browse/MAPSME-9894
The arm64-v8a support is added in this PR. You have to:
1. Update NDK to r19c version https://developer.android.com/ndk/downloads
2. If build is failed after the first step please update Cmake to last version throught Android Sdk Manager (which is embedded in Android studio or probable you may find it in SDK folder).
Important note: if you need to make build for the specific arch then you should pass the argument to the gradlew command -Parm32, -Parm64 or -Px86 to make your build process faster.
=> [android][core][ndk] Added ARM64 support

search/geocoder.cpp
Отменяю кеширование фичей из вьюпорта при поиске домов и POI.
Причина: оно занимает до 30% времени первого вызова поиска и при этом не приносит видимых улучшений.
Отсмотрела работу поиска на 400 размеченных случайных запросах на русском.
В большинстве случаев все результаты полностью совпадают (включая нерелевантные и мусор).
Для 28 запросов были различия. В большинстве случаев это замена одного мусора/нерелевантных ответов на другой мусор/нерелевантные ответы. Ни в одном из случаев разница не коснулась лучшего ответа. В целом новый вариант тяготеет к нахождению более далёких, но лучше подходящих под запрос ответов.
В одном случае на мой взгляд был потерян один релевантный ответ (но сохранен витальный), в восьми случаях были найдены ранее не найденные релевантные ответы (витальные были и …
=> [search] Do not cache viewport features for MatchAroundPivot.

drape_frontend/drape_engine.hpp, routing/features_road_graph.cpp, routing/index_graph.hpp, routing/joint.hpp, routing/online_absent_fetcher.cpp, routing/online_cross_fetcher.cpp, routing/online_cross_fetcher.hpp, routing/restriction_loader.cpp, routing/restriction_loader.hpp, routing/restrictions_serialization.cpp, routing/routing_benchmarks/bicycle_routing_tests.cpp, routing/routing_integration_tests/get_altitude_test.cpp, routing/routing_result_graph.hpp, routing/routing_tests/applying_traffic_test.cpp, routing/routing_tests/astar_algorithm_test.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/online_cross_fetcher_test.cpp, routing/routing_tests/road_graph_builder.cpp, routing/routing_tests/road_graph_nearest_edges_test.cpp, routing/routing_tests/route_tests.cpp, routing/routing_tests/turns_generator_test.cpp, routing/routing_tests/turns_tts_text_tests.cpp, routing/turns_sound_settings.hpp, routing/turns_tts_text.cpp
drape engine сломался потому что он заинклюжен после роутинга в map/user_mark_layer.cpp и других местах, раньше туда попадали инклюды и using из роутинга
=>  [std][routing] Use new include style for routing 

search/search_quality/assessment_tool/sample_view.cpp, search/search_quality/assessment_tool/sample_view.hpp
We used to call Framework's methods (OnLocationUpdate/OnLocationError)
here but they come bundled with an unremovable heuristic that keeps the
old position for some time when the position is lost.
This resulted in sometimes showing wrong positions for the samples that
do not have position info (the search params worked correctly
and were not using the old pos).
=> [search] [assessment-tool] Changed the display of the user's position.

drape_frontend/drape_engine.cpp, drape_frontend/user_mark_shapes.cpp, drape_frontend/user_mark_shapes.hpp, drape_frontend/user_marks_provider.hpp, map/framework.cpp, map/place_page_info.cpp, map/routing_manager.cpp, map/routing_manager.hpp, map/routing_mark.cpp, map/routing_mark.hpp, map/user_mark.hpp
Изменена логика отображения предупреждений, теперь все метки видны и вытесняются между собой.
Приоритет вытеснения:
* первая метка платной дороги
* первая метка грунтовой дороги
* первая метка паромной переправы
* остальные метки
=> Road warnings displacement.

generator/CMakeLists.txt, generator/geo_objects/geo_object_info_getter.cpp, generator/geo_objects/geo_object_info_getter.hpp, generator/geo_objects/geo_objects.cpp, generator/geo_objects/geo_objects.hpp, generator/geo_objects/key_value_storage.cpp, generator/geo_objects/key_value_storage.hpp, generator/geo_objects/region_info_getter.cpp, generator/geo_objects/region_info_getter.hpp, indexer/locality_index.hpp
Рефакторинг для фикса проверки границы региона и для повторного использования в генерации улиц.
Перенёс код обратного поиска региона и строения в классы RegionsDecoder и GeoObjectsDecoder.
KeyValueStorage принимает путь, вместо потока.
=> [generator:geo_objects] Refactoring: class RegionsDecoder

generator/generator_tool/CMakeLists.txt, generator/generator_tool/generator_tool.cpp
Данный реквест печает стектрейс при возникновении исключительной ситуации. (exception, CHECK, ASSERT..)
Это помогает быстро понять, где произошла проблема.
Так же теперь нет необходимости писать дублирующий код:
```
try 
{
// some code
}
catch(std::exception const & e)
{
LOG(LCRITICAL, (..., e.what()));
}
```
плюс к этому, платформы тоже умеют печатать стектрейс
реализуется с помощью header only boost
Пример вывода на linux при указании неверного пути файла(удобно читать с конца):
```
Core exception: File types.txt doesn't exist in the scope wrf Have been looking in:
/
/home/andrianov/Projects/omim/dataf/
/home/andrianov/Projects/omim/dataf/
0# ErrorHandler() in /home/andrianov/Projects/build-omim_copy-Desktop_Qt_5_10_1_GCC_64bit-Debug/generator_tool
1# 0x0000563866247474 in …
```
=> [generator] Added handler for exceptions and errors.

generator/regions/collector_region_info.cpp, generator/regions/collector_region_info.hpp, generator/regions/region.cpp, generator/regions/regions_builder.cpp, generator/regions/regions_fixer.cpp
Исключил place=locality для regions. Для b2b эти объекты не интересны.
См. https://wiki.openstreetmap.org/wiki/Tag:place%3Dlocality
=> [generator:regions] Ignore place=locality

routing/CMakeLists.txt, routing/base/astar_progress.cpp, routing/base/astar_progress.hpp, routing/checkpoints.cpp, routing/checkpoints.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing_tests/astar_progress_test.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
Что произошло:
Есть класс AStarProgress, он объединяет в себе под-прогрессы (AStarSubProgress). Они образуют список, так как эти подпрогрессы зависят друг от друга, а именно - у каждого подпрогресса есть свой вклад (contributionCoef)
Пример цепочки:
```cpp
// 1.0 - создается по умолчанию
// 0.4 - это участок между промежут. точками (текущий участок составляет 0.4 от всего, например)
// 0.3 - столько отводим для построения в режиме LeapsOnly
subProgress(1.0 /* contributionCoef */) -> subProgress(0.4)-> subProgress(0.3)
```
Что это означает?
Если где-то вызвали:
```cpp
update(current, finish)
```
То новый прогресс считается так:
```cpp
newProgress = 1.0 * (0.4 * (0.3 * progress(current, finish)))
```
Таким образом мы можем строить "зависимости" в стадиях.
Когда мы завершили последнюю …
=> [routing] Improve A* progress in UI for LeapsOnly mode

routing/routing_tests/astar_progress_test.cpp
В конце предыдущего PR добавил CHECK, а тесты забыл поправить
в обычным коде все написано так, что Erase всегда вызывается
=> [routing] fix tests

generator/cities_boundaries_builder.cpp, generator/descriptions_section_builder.cpp, generator/descriptions_section_builder.hpp, generator/popular_places_section_builder.cpp, generator/ratings_section_builder.cpp, generator/ugc_section_builder.cpp, generator/utils.cpp, generator/utils.hpp
Каждой фиче соответствует один osm элемент (обратное не верно).
По построению файлов мэпинга из OsmId в FeatureId это тоже видно:
файл создается в FeaturesCollector2::operator(FeatureBuilder2 & fb) из generator//feature_sorter.cpp
видно, что там для фичи один раз добавляется OsmId, а оператор вызывается для каждой фичи единожды (и создаёт из временной фичи которая берётся из mwm.tmp конечную, которая идёт в итоговую mwm).
Единственным местом где "использовалось" то что GeoObjectId может быть несколько было построение cities_boundaries, они собираются в процессе построения World.mwm с мэпингом OsmId в FeatureId для World.mwm -- распарсила последний, ещё раз убедилась что нет фичей, которым соответствует несколько OsmId.
Собрала из этого реквеста "маленький мир", всё ок.
=> [generator] Change feature id to osm id mapping type from uint32_t->vector<GeoObjectId> to uint32_t->GeoObjectId

generator/geo_objects/streets_builder.cpp, generator/geo_objects/streets_builder.hpp
Генерация улиц для прямого геокодера и по POI. Ранее это делалось скриптом genin/gen_streets.py (см. [Генератор индексов для геокодера](https://confluence.mail.ru/pages/viewpage.action?pageId=150642306))
=> [generator:geo_objects] Generate surrogate streets for KV by POI

map/framework.cpp, map/framework.hpp
`?fid<space>index<space>` подсвечивает искомую фичу на карте. Сначала ищет по mwm, которые попадают во вьюпорт, потом по всем остальным (затем чтобы было удобнее и не надо было в строке поиска писать имя mwm).
Функцию можно также теоретически переиспользовать для отображения всех mwm, которые содержат фичу с таким индексом. Полезно, когда известен индекс, а mwm нет.
Еще добавлен лог
LOG TID(1) INFO Feature found: { MwmId [Russia_Moscow, 190329], 30510 } ms::LatLon(55.767733055622471738, 37.658749950369809767)
LOG TID(1) INFO Feature found: { MwmId [World, 190328], 30510 } ms::LatLon(33.08056028396005388, 37.916676749786944356)
=> [debug] Added command to “search” by feature id

3party/jansson/myjansson.cpp, 3party/jansson/myjansson.hpp, generator/generator_tool/generator_tool.cpp, generator/geo_objects/geo_objects.cpp, generator/geo_objects/geo_objects.hpp
Фильтрация строений без номера дома (properties.address.building = null).
Сейчас в обратном индексе есть ограничение на размер данных - 4 Gb. Все строения для всего мира не помещаются в индекс. Новый фильтр исключает строения без адреса кроме зданий в странах, указанных в опции --allow_addressless_for_countries=...,... генератора generator_tool.
По факту, всегда запускали генератор для b2b с этим патчем для России, Белоруссии и и Украины.
=> [generator:geo_object] Filtrate addressless buildings

openlr/CMakeLists.txt, openlr/candidate_paths_getter.cpp, openlr/candidate_paths_getter.hpp, openlr/candidate_points_getter.cpp, openlr/candidate_points_getter.hpp, openlr/graph.cpp, openlr/graph.hpp, openlr/helpers.cpp, openlr/helpers.hpp, openlr/openlr_decoder.cpp, openlr/openlr_decoder.hpp, openlr/openlr_stat/openlr_stat.cpp, openlr/paths_connector.cpp, openlr/road_info_getter.cpp, openlr/road_info_getter.hpp, openlr/router.cpp, openlr/router.hpp, openlr/score_candidate_paths_getter.cpp, openlr/score_candidate_paths_getter.hpp, openlr/score_candidate_points_getter.cpp, openlr/score_candidate_points_getter.hpp, openlr/score_paths_connector.cpp, openlr/score_paths_connector.hpp, openlr/score_types.hpp, openlr/stats.hpp, routing/features_road_graph.cpp, routing/features_road_graph.hpp, routing/road_graph.hpp, xcode/openlr/openlr.xcodeproj/project.pbxproj
Данный PR добавляет к программе матчинга openlr сегментов на osm сегменты (openlr_stat) новую версию алгоритма матчинга (версия 3). Идея данного алгоритма в том, чтоб на финальный этап выбора приходило большее число дуг. Кроме того, данный алгоритм использует больше информации об openlr дугах, чем версия 2. Например form of way или functional road class.
Алгоритм работает следующим образом: не далеко от начала и конца openlr дуги ищем osm дуги и на основании: дальности от точки начала (конца), класса дороги (functional road class), типа дороги (form of way), угла под которым уходит osm дуга (набор osm дуг) каждому правдоподобному кандидату дается определенный score. Далее данные кандидаты соединяются маршрутами (все со всеми) и на основании score начала и конца, длины маршрута, functional …
=> Openlr matching. Algorithm version 3.

generator/road_access_generator.cpp, generator/road_access_generator.hpp
Иногда на дорогах встречаются внезапно шлагбаумы, которые мешают роутеру, также в попытках запрещать ехать через дворы мы начинаем творить странные вещи на всяких границах/переходах на платную дорогу, так как там стоит barrier=lift_gate и подобные
Данный PR не рассматривает барьеры для машин без access, если эти барьеры стоят на следующих типах дорог:
```cpp
static std::set<OsmElement::Tag> const kHighwaysWhereIgnoredPrivateAccess = {
{OsmElement::Tag("highway", "motorway")},
{OsmElement::Tag("highway", "trunk")},
{OsmElement::Tag("highway", "primary")},
{OsmElement::Tag("highway", "secondary")},
{OsmElement::Tag("highway", "tertiary")},
{OsmElement::Tag("highway", "motorway_link")},
{OsmElement::Tag("highway", "trunk_link")},
{OsmElement::Tag("highway", "primary_link")}, …
```
=> [generator] Ignore some barriers without access for car routing

drape/vulkan/vulkan_object_manager.cpp, drape/vulkan/vulkan_object_manager.hpp, drape/vulkan/vulkan_staging_buffer.cpp, drape/vulkan/vulkan_staging_buffer.hpp
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5ccbb191f8b88c2963e4e479?time=last-thirty-days
Неправильный размер передавался в m_objectManager->CreateBuffer. Кроме того, добавил фолбэк для девайсов с нестандартным выравниванием.
=> [vulkan] Fixed crash in staging buffer

android/jni/com/mapswithme/maps/Framework.cpp, drape/support_manager.cpp, drape/support_manager.hpp, drape/vulkan/vulkan_pipeline.cpp
Запрет Vulkan для драйверов Adreno c особенностями
https://developer.qualcomm.com/forum/qdn-forums/software/adreno-gpu-sdk/34709
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5ccb5c9bf8b88c2963e02a5a?time=last-thirty-days
=> [vulkan] Forbid Vulkan for not standard compliant Adreno drivers

drape/vulkan/vulkan_base_context.cpp
VK_ERROR_DEVICE_LOST обрабатывается в функциях выше, но не в этой.
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5cd23588f8b88c296352ab90/sessions/latest
=> [vulkan] Process device lost in vkQueuePresentKHR

routing_common/car_model_coefs_default.hpp
Идея в том, что после вычисления скоростей для ряда классов дорог, для дорог unclassified они остались не изменными. Как следствие стали примерно, как у primary. Что давало ошибки вроде такой: 
Этот PR делает скорости для дорог unclassified более соответствующими действительности. Позже они будут посчитаны точно.
=> [routing] Decreasing speed for unclassified roads to tertiary speed.

3party/jansson/myjansson.cpp, 3party/jansson/myjansson.hpp
Рефакторинг: работать с `json_t const *` вместо `json *` для get-операций.
Подготовка для след. PR с многопоточной обработкой JSON.
=> [myjannson] Refactor: add const qualifier

drape_frontend/render_state_extension.cpp
https://fabric.io/mapsme/ios/apps/com.mapswithme.full/issues/5cd94ca0f8b88c2963cadd66
=> Fixed crash with multithreaded static variable initialization.

android/jni/com/mapswithme/core/jni_helper.cpp, android/jni/com/mapswithme/core/jni_helper.hpp, android/jni/com/mapswithme/maps/Framework.cpp, iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController+CPP.h, iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert+CPP.h, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm, iphone/Maps/Classes/CustomAlert/DownloadTransitMapsAlert/MWMDownloadTransitMapAlert.h, iphone/Maps/Classes/CustomAlert/DownloadTransitMapsAlert/MWMDownloadTransitMapAlert.mm, iphone/Maps/Core/Framework/MWMFrameworkHelper.mm, iphone/Maps/Core/Framework/MWMFrameworkListener.mm, iphone/Maps/Core/Framework/MWMFrameworkObservers.h, iphone/Maps/Core/Routing/MWMRouter.mm, map/routing_manager.cpp, map/routing_manager.hpp, qt/draw_widget.cpp, routing/async_router.cpp, routing/async_router.hpp, routing/online_absent_fetcher.cpp, routing/online_absent_fetcher.hpp, routing/routing_callbacks.hpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_tests/async_router_test.cpp, routing/routing_tests/online_cross_fetcher_test.cpp
``` 
set<string> absent;
if (absentFetcher && needFetchAbsent)		
absentFetcher->GetAbsentCountries(absent);
absent.insert(absent.end(), route->GetAbsentCountries().cbegin(), route->GetAbsentCountries().cend());
```
Проблема была в этом коде. Сначала мы получали countryId от онлайн фетчера, потом из route'a.   Исправил ```vector<string>``` на ```set<string>```, т.к. это, кажется, логичнее.
https://jira.mail.ru/browse/MAPSME-8774
https://jira.mail.ru/browse/MAPSME-6748
=> [routing] Fixed duplicate names in absent list.

routing/routing_quality/routing_quality_tests/passby_roads_tests.cpp
Из за понижения скорости на unclassified дорогах мы стали проходить закомменченый тест таким образом:
До этого проходили вот так:
выделеный участок дороги - это unclassified (как видно, довольно длинный и в целом не удивительно, что тест не прошел)
для сравнения гугл кладет через unclassified (по гугл картам я посмотрел, дорога действительно похожа на unclassified)
кажется, что когда будут починены границы городов + сделаны перекрестки - этот тест снова должен работать. 
повышать обратно скорость unclassified дорог неправильно, тк по документации osm'a они должны быть ниже tertiary.
так же добавил тест с ситуацией, которую чинил Владимир @bykoianko, а именно движение по secondary дороге без съезда на unclassified.
=> [routing] Comment test and add another.

3party/kdtree++/kdtree.hpp, generator/emitter_coastline.cpp, generator/emitter_simple.cpp, generator/feature_builder.hpp, generator/feature_generator.cpp, generator/feature_generator.hpp, generator/feature_processing_layers.cpp, generator/generator_tests/coasts_test.cpp, generator/generator_tests/popularity_builder_tests.cpp, generator/generator_tests_support/test_mwm_builder.cpp, generator/geo_objects/geo_objects.cpp, generator/locality_sorter.cpp, generator/polygonizer.hpp, generator/regions/regions.cpp, generator/world_map_generator.hpp, geometry/tree4d.hpp
Отрефакторил класс Polygonizer:
Помимо всяких форматирований, было несколько на мой взгляд важных проблем:
1. Помните не получилось пересобрать Италию для продакшн карт, оказывается вся проблема тут https://github.com/mapsme/omim/blob/master/generator/polygonizer.hpp#L119. В этом switch. Не проверялись точные границы региона. В приниципе понятно зачем авторы так сделали. Это будет работать немного быстрее, но невозможно пересобрать какие то mwm ки. Эта возможность очень нужна. Теперь границы проверяются всегда.
2. Потенциальная гонка в этой строке: https://github.com/mapsme/omim/blob/master/generator/polygonizer.hpp#L203, если пройтись глазами по стеку вызово видно, что emit (внутри write) может вызываться для одного и того же региона для разных фичей. Это очень опасно. Удалил …
=> [generator] Refactored Polygonizer.

openlr/helpers.cpp, openlr/helpers.hpp, openlr/openlr_decoder.cpp, openlr/openlr_model.cpp, openlr/openlr_model.hpp, openlr/openlr_model_xml.cpp, openlr/score_candidate_paths_getter.cpp, openlr/score_candidate_paths_getter.hpp, openlr/score_paths_connector.cpp, openlr/score_paths_connector.hpp, openlr/stats.hpp
В рамках алгоритма 3 по мачингу openlr сегментов теперь используется еще один таг: <coordinates>.
=> [openlr] Parsing and using openlr segment with coordinates tag.

data/countries.txt, data/countries_synonyms.csv, map/map_tests/countries_names_tests.cpp, search/downloader_search_callback.cpp, search/region_info_getter.cpp, search/search_quality/features_collector_tool/features_collector_tool.cpp, search/search_quality/helpers.cpp, search/search_quality/helpers.hpp, search/search_quality/search_quality_tool/search_quality_tool.cpp, storage/country_tree.cpp, storage/country_tree.hpp, storage/storage.cpp, storage/storage.hpp, storage/storage_defines.hpp, tools/python/maps_generator/generator/env.py, tools/python/maps_generator/maps_generator.py, tools/python/post_generation/__main__.py, tools/python/post_generation/hierarchy_to_countries.py, tools/unix/generate_planet.sh
Нам иногда нужно (например при поиске в загрузчике) найти по фиче страны её место в CountryTree.
Сейчас поиск проиходит по CountryId и это не всегда удобно -- CountryId на это не расчитаны и нет возможности их менять для листовых mwm: это потребует миграции данных.
В этом реквесте добавляю в countries.txt новое опциональное поле, которое содержит различные варианты написание имени страны/стран лежащей внутри данного узла CountryTree и будет использоваться для матчинга с фичами.
=> [storage][data] Add country name synonyms to countries.txt

indexer/altitude_loader.cpp
Данный лог сильно тормозит пеший и вело роутинг во всех северных странах. На обращение к каждой фиче получаем по записи в лог. Удалил.
=> [routing] Removing log message about altitude absence.

3party/jansson/myjansson.hpp, generator/geo_objects/geo_object_info_getter.hpp, generator/geo_objects/geo_objects.cpp, generator/key_value_storage.cpp, generator/key_value_storage.hpp, generator/regions/region_info_getter.cpp, generator/regions/region_info_getter.hpp, generator/streets/streets_builder.cpp, generator/streets/streets_builder.hpp
Рефакторинг, подготовка к многопоточной работе с KeyValueStorage: заменил JSON на JsonValue. В JSON обвёртке используется json_incref(), который не thread safe. Подсчёт ссылок в JsonValue происходит через std::shared_ptr, который thread safe
=> [generator] Add parallel ready for KeyValueStorage

generator/emitter_simple.cpp
Оптимизация regions генератора фичей: не хранить в памяти фейковое имя страны "regions" для каждой обрабатываемой фичи. Сохранение происходит в Polygonizer::EmitFeature (`m_currentNames += countryPolygons.m_name;`)
=> [generator] Optimize EmitterSimple

indexer/feature.cpp
У нас EditableDataSource возвращает MapObject, из которого дальше создаётся FeatureType.
FeatureType имеет полностью распаршенное состояние с геометрией BEST_GEOMETRY и у него не заполнено m_loadInfo.
В drape_frontend для правильной отрисовки пробок геометрия сбрасывается и затем парсится на масштабе BEST_GEOMETRY. Но у отредактированного объекта после сброса геометрии нет возможности её распарсить заново.
Это может быть линейный объект, у которого отредактировано название. В этом случае у него есть прообраз, на который накладываются правки. Но брать m_loadInfo из прообраза плохо, т.к. m_loadInfo отвечает за загрузку всего в FeatureType и мы не сможем нормально отличать фичу-прообраз от отредактированной.
В этом PR добавляю игнорирование ResetGeometry для фичей, созданных из MapObject. …
=> [indexer] Do not reset geometry for features created from MapObjects.

generator/generator_tests/feature_builder_test.cpp, indexer/feature_decl.hpp
Фикс падения в генераторе индекс-файла: чтение одного байта, а не 4х в LocalityObject::Deserialize()
=> [indexer] builder fix

generator/feature_helpers.cpp, generator/feature_helpers.hpp, generator/locality_sorter.cpp, indexer/feature_visibility.cpp, indexer/feature_visibility.hpp
Игнорировать тип фичи для регионов B2B при построении индекса, что бы, например, генерировать район города по relation с adim_level и вхождением его в населённый пункт. Сам генератор фич регионов будет строить дерево регионов из нужных типов фич.
=> [generator] Fix regions index generation: ignore features types

routing/features_road_graph.cpp
Объявил константу один раз вместо двух и внес не большие изменения.
=> [routing] Declaring kInvalidSpeedKMPH only once.

generator/CMakeLists.txt, generator/boost_helpers.hpp, generator/generator_tests/CMakeLists.txt, generator/generator_tests/street_geometry_tests.cpp, generator/streets/street_geometry.cpp, generator/streets/street_geometry.hpp, generator/streets/streets_builder.cpp, generator/streets/streets_builder.hpp, geometry/point2d.hpp, storage/storage_tests/country_info_getter_tests.cpp
Для улиц в jsonl добавлено два новых поля: bbox и pin.
bbox - минимальный прямоугольник включающий геометрию дороги (highway из OSM) либо, если нет highway, все точки зданий улицы.
pin - центральная точка позиционирования улицы на карте. Это может быть геометрический цент площади, середина дороги, ближайшее здание в центу bbox.
=> [generator:streets] Add street bbox and center

generator/borders.cpp, generator/borders.hpp
распаковал packed_polygon.bin со старым кодом и новым, сделал `diff` на нескольких полигонах, все идентично
PR нужен для того, чтобы заиспользовать `DumpBordersToPolyFiles` в PR про тулзу с границами
=> [generator] Add separate function for dumping borders to *.poly files

generator/CMakeLists.txt, generator/generator_tests/CMakeLists.txt, generator/generator_tests/street_regions_tracing_tests.cpp, generator/streets/street_regions_tracing.cpp, generator/streets/street_regions_tracing.hpp, generator/streets/streets_builder.cpp, generator/streets/streets_builder.hpp, geometry/CMakeLists.txt, geometry/meter.hpp
Добавление улицы во все регионы, через которые она проходит.
В OSM улица (highway=... node) может проходить через несколько регионов (regions). Например, начинаться в населённом пункте, а заканчиваться в области, или проходить по области сквозь населенные пункты.
В мастере принадлежность улицы региону определяется по первой точке. В этом PR определяются все сегменты дороги, где каждый сегмент принадлежит одному region (сегмент от/до границы region). Сегменты строятся трассировкой вдоль пути: каждые 100 метров проверяется принадлежность региону и с шагом 10 метров для поиска границы между регионами.
В комментариях с TODO представлен код, который нужно вернуть после попадания в мастер геометрии улицы PR #10836
=> [generator:streets] Highway tracing: detect street's regions

generator/generator_tests/regions_tests.cpp, generator/place_node.hpp, generator/popularity.hpp, generator/regions/node.cpp, generator/regions/node.hpp, generator/regions/region.cpp, generator/regions/region.hpp, generator/regions/regions.cpp, generator/regions/regions_builder.cpp, generator/regions/regions_builder.hpp
Очередная порция изменений отменённого PR #10432.
В данном PR перегенерация фичей регионов с геометрией из дерева иерархии. Это нужно будет, когда place node будут получать границы из административной разметки, и когда будут label точки с границами из relation (которому label точка принадлежит) вместо relation.
Нормализация в дереве, которая была раньше, не используется. Удалил.
=> [generator:regions] Generate features with build geometry

generator/geo_objects/geo_objects_filter.cpp
Фикс фильтра фичей geo_objects: возвращён игнор линий, который был раньше. Линии добавлялись для streets, которые теперь генерируется отдельным запуском.
=> [generator:geo_objects] Fix features filter: ignore lines

base/base_tests/levenshtein_dfa_test.cpp, base/dfa_helpers.hpp, search/categories_cache.cpp, search/geocoder.cpp, search/geocoder.hpp, search/geocoder_context.hpp, search/geocoder_locality.hpp, search/intermediate_result.hpp, search/locality_scorer.cpp, search/locality_scorer.hpp, search/pre_ranking_info.cpp, search/pre_ranking_info.hpp, search/ranker.cpp, search/ranking_info.hpp, search/retrieval.cpp, search/retrieval.hpp, search/search_integration_tests/processor_test.cpp, search/search_tests/feature_offset_match_tests.cpp, search/search_tests/locality_scorer_test.cpp, search/streets_matcher.cpp
В этом реквесте признак exactMatch протаскивается в преранкер и ранкер, но пока там не используется.
Используется для предварительного отбора городов/деревень в LocalityScorer.
На размеченной выборке существенной разницы по производительности, профилю времени исполнения функций, результатам нет.
=> [search] Pass |exactMatch| to PreRanker, Ranker. Take |exactMatch| into account in LocalityScorer.

generator/generator_tests/restriction_test.cpp, generator/restriction_collector.cpp, generator/restriction_collector.hpp, generator/restriction_generator.cpp, generator/restriction_generator.hpp, generator/restriction_writer.cpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_loader.cpp, routing/restriction_loader.cpp, routing/restriction_loader.hpp, routing/restrictions_serialization.cpp, routing/restrictions_serialization.hpp, routing/routing_integration_tests/turn_test.cpp, routing/routing_tests/CMakeLists.txt, routing/routing_tests/cumulative_restriction_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/routing_tests/restriction_test.cpp, routing/routing_tests/uturn_restriction_tests.cpp, routing/routing_tests/world_graph_builder.cpp, routing/routing_tests/world_graph_builder.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
Смотреть по коммитам
Тут к секции `RESTRICTIONS_FILE_TAG` добавляется новая информация о u_turn
Это либо no_u_turn, либо only_u_turn
В рамках maps.me считается, что такие маневры это только:
с `feature123` -> `feature123` через точку на `feature123`
Все остальное конвертируется в другие соотвествующие типы
Поворот u_turn может совершаться только либо в начале `feature123` либо в концe `feature123`, поэтому храним так:
Выставляем старший бит в `1` если viaIsFirstPoint (разворот в начале) и ничего не ставим, если разворот в конце (и проверяем, что там действительно стоит 0)
Как сериализуем:
У нас получаются положительные и отрицательные числа, мы делаем для них ZigZag encoding => сортируем => delta coding
=> [routing] [generator] UTurn Restrictions

indexer/indexer_tests/interval_index_test.cpp, indexer/interval_index.hpp, indexer/interval_index_builder.hpp, indexer/locality_index_builder.cpp, indexer/locality_index_builder.hpp
Вариант быстрого решения для индекс-файла более 4 Gb для B2B. Версия 2 в IntervalIndex использует 64-битное представление (variable encoding) для смещений и размеров блоков в индекс файле. Новая версия задаётся явно для B2B в генераторе.
=> [indexer:interval_index] Add interval index version 2: 64 bit offset

search/ranker.cpp
Для некоторых объектов (азс, банкомат) обычно название указывается в operator. Имя при этом пустое, но азс/банкомат по сути не noname. С брендами аналогично.
m_hasName используется только для категорийных запросов, поэтому, раз мы начали читать метадату, занесла под `if (m_params.IsCategorialRequest())`.
=> [search] Set RankingInfo::m_hasName to true for features with brand or operator.

android/res/values/strings-tts.xml
New trendy and simple order for languages plus sk and sv cause now Google TTS supports them
=> [Android Strings TTS] new order for languages plus sk and sv

routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/bicycle_turn_test.cpp, routing_common/bicycle_model.cpp
Данный PR решает 2 проблемы:
1. исправляет ряд ситуаций, когда вело маршрут не прокладывался, хотя должен:
- теперь возможно проложить маршрут от офис (тест: RussiaMoscowServicePassThrough3)
- https://jira.mail.ru/browse/MAPSME-10521
- маршрут в районе Нагатинской набережной (тест: RussiaMoscowServicePassThrough2)
2. приводит в соответствие прокладку веломаршрутов  в России с правилами ПДД.
Согласно ПДД России велосипед является **транспортным средством**:
> "Велосипед" - **транспортное средство**, кроме инвалидных колясок, которое имеет по крайней мере два колеса и приводится в движение как правило мускульной энергией лиц, находящихся на этом транспортном средстве, в частности при помощи педалей или рукояток, и может также иметь электродвигатель номинальной максимальной мощностью в …
=>  [routing] Making passing through living_street and service roads for bicycle in Russia.

generator/regions/regions_fixer.cpp
Круговая аппроксимация только для насел. пункты. Насел. пункты нельзя игнорировать, т.к. jsonl от генератора используется и в прямом геокодере. Районы без границ не страшно потерять, а круговая аппроксимировать ухудшает качество для обратного и прямого геокодеров, как для регионов так и для строений.
=> [generator:regions] Approximate settlement only

generator/geo_objects/geo_objects.cpp, generator/key_value_storage.cpp, generator/key_value_storage.hpp, generator/regions/region_info_getter.cpp
Оптимизация по памяти. Сейчас генератор для geo_objects не помещается в 256 Gb: слишком много занимают десериализованные json объекты строений в KeyValueStorage.
В этом PR KeyValueStorage хранит только заданное кол-во (первых) десер. json объектов, а остальные - в виде json, строки. Когда требуется json для объекта, то он десер. на лету и после обработки уничтожается. Т.к. обработка происходит в неск. потоках и десериализация происходит в них же, то скорость генерация осталось на том же уровне (при большом кол-ве потоков).
=> [generator:geo_objects] Optimize RSS usage: json objects limit

indexer/search_string_utils.cpp, search/search_integration_tests/processor_test.cpp
Предположим что у нас есть фича с названием "улица нахимова", сейчас при построении индекса мы пропустим её через StreetTokensFilter и заиндексируем только за "нахимова".
При этом при поиска по запросу "улица на" мы посчитаем что "на" это префикс от "набережная" и поэтому заэмитим в StreetTokensFilter delayed token "улица", за которым ничего не заиндексировано (т.к. при построении индекса мы этот токен выкинули).
В этом реквесте отменяется эмит отложенного токена для префикса, не являющегося полным синонимом улицы.
=> [search] StreetTokensFilter: do not emit delayed token for incomplete street synonym.

platform/languages.hpp
Исправил ошибку, внесенную вот этим PR: https://github.com/mapsme/omim/pull/11090
PTAL
=> iOS build fix.

base/stl_helpers.hpp, geocoder/geocoder.cpp, geocoder/geocoder.hpp, geocoder/geocoder_tests/geocoder_tests.cpp
Фикс кейса из таска MAPSB2B-65: не находится улица по запросу `Россия, Город Москва, Улица Тверская-Ямская 1-я`.
Причина в том, что для улиц с номерами (которые могут считаться номерами домов) все токены должны быть размечены. В данном примере не размечен токен `Город`.
В этом PR ослабил условие необходимой разметки всех токенов, на обязательное наличие номера в адресе.
Оценка качества и скорости до:
```
Processed rows                        	10000	54.826211
full_matched                          	7853	78.53
```
Оценка качества и скорости после:
```
Processed rows                        	10000	54.133313
full_matched                          	7864	78.64
```
=> [geocoder] Relax number matching for streets

generator/CMakeLists.txt, generator/generator_tests/region_info_collector_tests.cpp, generator/generator_tests/regions_tests.cpp, generator/regions/collector_region_info.cpp, generator/regions/collector_region_info.hpp, generator/regions/country_specifier.cpp, generator/regions/country_specifier.hpp, generator/regions/regions_builder.cpp, generator/regions/specs/rus.cpp, generator/regions/specs/rus.hpp
Генерация административного деления России по admin_level:
- 4  - region
- 5  - subregion (Москва), suburb (Санкт-Петербург, Севастополь)
- 6 - subregion
- 8 - suburb (Москва), sublocality (Санкт-Петербург, Севастополь)
- 9 - suburb
см.
https://wiki.openstreetmap.org/wiki/RU:Tag:boundary%3Dadministrative
https://wiki.openstreetmap.org/wiki/RU:%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B8_%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%86
=> [generator:regions] Add Russsia administrative devisions

generator/streets/street_geometry.cpp, generator/streets/street_geometry.hpp
Фикс HighwayGeometry::Line::Concatenate для колец и развилок, когда две ломанные частично склеивается. Например, склейка [p4, p2] и [p1, p2] [p2, p3] может дать две непустые ломанные [p4, p2] [p2, p1] и [p2, p3] (сперва склейка [p4, p2] и [p1, p2] по p2, и не возможность склеить [p2, p3] с [p4, p2] [p2, p1]). Ожидается, что, либо вся линия добавится в другую, любо они не изменяются.
=> [generator:streets] Fix Line::Concatenate

generator/generator_tests/regions_tests.cpp, generator/regions/collector_region_info.cpp, generator/regions/collector_region_info.hpp, generator/regions/region.cpp, generator/regions/region.hpp, generator/regions/region_base.cpp, generator/regions/region_base.hpp, generator/regions/region_info.cpp, generator/regions/region_info.hpp, generator/regions/regions.cpp, generator/regions/regions_builder.cpp, generator/regions/regions_builder.hpp
Насыщение данных: используются label node для регионов для имени, для определения place-типа, центра региона.
Тесты для них пока закомментарены в PR #11073, что бы не дублировать тестовую инфраструктуру регионов.
=> [generator:regions] Add place label nodes

generator/generator_tests/osm_type_test.cpp, routing/routing_integration_tests/route_test.cpp, routing_common/bicycle_model.cpp, routing_common/car_model.cpp, routing_common/car_model.hpp
В car_model у нас фичи с тагом hwtag-nocar рассматривались как дороги. Этот PR делает поддержку hwtag-nocar, hwtag-yescar как в вело и пешей модели.
@gmoryes PTAL
=> [routing] Support hwtag-nocar hwtag-yescar.

generator/search_index_builder.cpp, indexer/indexer_tests/search_string_utils_test.cpp, indexer/search_string_utils.cpp, indexer/search_string_utils.hpp, search/search_integration_tests/processor_test.cpp, search/streets_matcher.cpp
Добавление опечаточника замедляет StreetsMatcher, но относительно общего времени поиска это не критично.
Раньше StreetsMatcher::Go отнимал примерно 0.1% от общего времени поиска, теперь примерно 0.5%.
=> [search] Match street synonyms with misprints.

indexer/search_string_utils.cpp
1. Поиск в интернете на испанских сайтах не указывает на то, что это часто употребимый синоним для улицы.
2. Я посмотрела имена всех фичей в 15 произвольных испаноговорящих mwm (Испания, Аргентина, Чили, Боливия), нашла там суммарно ровно 0 фичей с cllon в имени.
3. Расстояние всего в 1 букву от Colón (Колумб), имя которого часто встречается в топонимах, поэтому cllon может быть значимым токеном, а мы его сейчас часто игнорируем.
=> [search] Remove cllon from street synonyms.

3party/jansson/myjansson.hpp, coding/string_utf8_multilang.hpp, generator/feature_builder.hpp, generator/generator_tests/translation_test.cpp, generator/geo_objects/geo_objects.cpp, generator/regions/region.cpp, generator/regions/regions.cpp, generator/streets/streets_builder.cpp, generator/streets/streets_builder.hpp, generator/translation.cpp, generator/translation.hpp
Меняем формат jsonl файликов
Словарь address уезжает в locales, получается что-то вроде
``
{
"locales": {
"default": {
"address": {
"country": "Bahamas"
},
"name": "Bahamas"
},
"en": {
"address": {
"country": "Bahamas"
},
"name": "Bahamas"
},
"ru": {
"address": {
"country": "Багамы"
},
"name": "Багамы"
}
},
"rank": 1,
"dref": null,
"code": "BS"
}
``
Усложняем логику перевода имени.
=> [generator]Json locale format

routing/routing_integration_tests/transit_route_test.cpp
На старых данных был маршрут длиной 6320м и строился он всегда таким образом:
На новых данных маршрут каждый раз разный:
6185м
6184м
бывают еще другие варианты, все примерно одинаковой длины
такая ситуация из за того, что станция foggy пренадлежит 3м параллельным веткам: оранжевой, серой и синей. станция shaw-howard пренадлежит желтой и зеленой ветке. 
https://www.wmata.com/schedules/maps/upload/2019-System-Map.pdf
=> [routing] Fixed integration tests.

generator/regions/regions_builder.cpp, generator/regions/regions_builder.hpp
Фикс пространственной вложенности регионов: нестрогая проверка площади, с относительной погрешностью.
Для одного и того же полигона, но с разной последовательностью точек может получаться разная площадь и некоторые регионы не попадали в дерево из-за последовательности проверок.
=> [generator:regions] Fix affilation for equal regions area

generator/feature_builder.hpp
`delayed::ThreadPool` годится для мелких задач, а для параллельных воркеров он не гарантирует сколько тредов будут работать, когда вызывается его деструктор
=> [generator] Fix parallel processing in ForEachParallelFromDatRawFormat()

geocoder/hierarchy_reader.cpp, geocoder/hierarchy_reader.hpp
Оптимизация по памяти при старте. Сервис не мог подняться, не помещался в память.
Проблема: для загрузки треб. в два раза больше памяти чем для работы.
Решение: загрузка частями.
=> [geocoder] Optimize memory at the start

base/base_tests/levenshtein_dfa_test.cpp, base/dfa_helpers.hpp, base/levenshtein_dfa.cpp, base/levenshtein_dfa.hpp, base/uni_string_dfa.hpp, search/ranker.cpp, search/ranking_info.cpp, search/ranking_info.hpp, search/ranking_utils.cpp, search/ranking_utils.hpp, search/search_integration_tests/processor_test.cpp, search/search_tests/ranking_tests.cpp
При определении NameScore не разрешались ошибки, то есть если в запросе была опечатка, то автоматически токен с опечаткой не матчился и это зачастую приводило к тому, что витальный результат, полностью совпаюащий с запросом с точностью до 1 опечатки, имел NameScore Zero.
Кроме того:
- разбор для NameScore выбирался отдельно от разбора для вычисления количества опечаток
- в случае превышения допустимого количества опечаток считалось что количество опечаток 0.
Также в реквесте новые коэффициенты для модели ранжирования.
=> [search] Allow misprints while determing NameScore for ranking.

generator/generator_tests_support/routing_helpers.cpp
Причина проблемы в том, что `*lineIter` возвращает строку. А в c-tor SimpleTokenizer сохранялись ссылки на этот временный объект. Об этом говорят и комментарии к c-tor SimpleTokenizer : 
```c++
// *NOTE* |s| must be not temporary!
TokenizeIterator(std::string const & s, DelimFn const & delimFn)
: m_start(s.begin()), m_end(s.begin()), m_finish(s.end()), m_delimFn(delimFn)
{
Move();
}
// *NOTE* |s| must be not temporary!
TokenizeIterator(UniString const & s, DelimFn const & delimFn)
: m_start(s.begin()), m_end(s.begin()), m_finish(s.end()), m_delimFn(delimFn)
{
Move();
}
```. 
`auto const & line = *lineIter;` продливает время жизни строки.
```c++
2019-07-17 14:08:43.837904+0300 generator_tests[78080:2524775] =================================================================
2019-07-17 …
```
=> Dangling reference fixing.

indexer/search_string_utils.cpp, indexer/search_string_utils.hpp, search/ranker.cpp, search/ranking_info.cpp, search/ranking_info.hpp
Неправильно считался MaxErrors, т.к. мачинг происходит(автомат строится) по токенам из фичей. Токены из фичей могут быть длиннее токенов из запроса, получается что MaxErrors это количество токенов умноженное на максимальное количество опечаток в токене.
=> [search] Remove wrong MaxErrors calculation from ranking

android/build.gradle, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/util/statistics/PushwooshHelper.java
После обновления PW с версии 5.9 до 5.17, скорее всего сломались гуопуши. PW в версии 5.10 вынес поддержку геопушей в отдельную библиотеку. Кроме того, теперь надо явно вызывать start/stop location tracking.
В данном PR это и делается.
Ссылка на доку PW: https://pushwoosh.gitbook.io/platform-docs/pushwoosh-sdk/android-push-notifications/customizing-android-sdk-5.0#geozones-push-notification
=> [android] Fixed geo-pushes

search/ranking_info.cpp
Немного напрягает что kNameScore Zero выше чем Prefix и Substring, но оно таким получается в 10 запусках scoring_model из 10.
=> [search][scoring_model] Update scoring model coeffs after ErrorsMade fix.

search/search_integration_tests/processor_test.cpp
в ранжировании "побеждает" то кафешка без опечатки то город с опечаткой, но тест не об этом -- добавила в него игнорирование ранжирования
=> [search] Ignore ranking for ProcessorTest_ExactMatchTest.

routing/fake_graph.hpp, routing/fake_vertex.hpp, routing/index_graph_starter.cpp, routing/routing_integration_tests/turn_test.cpp, routing/transit_graph.cpp, routing/transit_graph.hpp
При указании старта (финиша) около дублирующихся дорожный фичь на границе mwm теперь файковые дуги корректно достариваются до каждой продублированной фичи. 
Ключевой момент, в класс FakeVertex введено поле: m_numMwmId, по которому мы определяем, какой mwm принадлежит FakeVertex.
Это позволяет корректно строить маршруты, если старт или финиш около границы mwm.
https://jira.mail.ru/browse/MAPSME-11065
=> [routing] Adding num mwm id to FakeVertex to distinguish FakeVertex near mww borders.

routing/fake_graph.hpp, routing/fake_vertex.hpp, routing/index_graph_starter.cpp, routing/routing_integration_tests/turn_test.cpp, routing/transit_graph.cpp, routing/transit_graph.hpp
cherry-pick to release-92 https://github.com/mapsme/omim/pull/11246
https://jira.mail.ru/browse/MAPSME-11065
=> [routing][release-92] Adding num mwm id to FakeVertex to distinguish FakeVertex near mww borders.

map/bookmarks_search_params.hpp, map/map_tests/search_api_tests.cpp, map/search_api.cpp, map/search_api.hpp, search/CMakeLists.txt, search/bookmarks/data.hpp, search/bookmarks/processor.cpp, search/bookmarks/processor.hpp, search/bookmarks/types.cpp, search/bookmarks/types.hpp, search/engine.cpp, search/engine.hpp, search/processor.cpp, search/processor.hpp, search/search_params.hpp, search/search_tests/bookmarks_processor_tests.cpp, xcode/search/search.xcodeproj/project.pbxproj
This commit introduces to the general search params the group id
that has no place there. If we decide on decoupling the general map search
and bookmark search, it is to be done in a separate commit.
Note that currently Processor already does a lot of wasteful initialization
(PreRanker, Ranker, keywords, etc.) when preparing to search in bookmarks
so this commit returns the courtesy.
=> [search] [bookmarks] Implemented Attach/Detach listeners in search.

generator/generator_tests/regions_tests.cpp, generator/regions/specs/russia.inl
Если геометрия округов и районов Москвы/Санкт-Петербурга/Севастополя эквивалентны геометрии regons place=city, то включать их внутрь этих городов.
=> [generator:regions] Fix Moscow administrative regions affiliation

iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.h, iphone/Maps/Classes/CustomAlert/AlertController/MWMAlertViewController.mm, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.h, iphone/Maps/Classes/CustomAlert/BaseAlert/MWMAlert.mm, iphone/Maps/Classes/CustomAlert/LocationAlert/MWMLocationAlert.h, iphone/Maps/Classes/CustomAlert/LocationAlert/MWMLocationAlert.mm, iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtons.mm, iphone/Maps/Classes/MapViewController.mm, iphone/Maps/Core/Location/MWMLocationManager.h, iphone/Maps/Core/Location/MWMLocationManager.mm
- Исправлена логика при включении Location Manager. Теперь проверяется, включился ли Location Manager на самом деле. Это должно исправить баг с бесконечной анимацией кнопки на старте при выключенных геосервисах (https://jira.mail.ru/browse/MAPSME-10548);
- Убрана трех-кадровая анимация с кнопок, так как она создавала data race и была незаметна;
- Вместо системного одноразового диалога при выключенных геосервисах показывается наш собственный диалог;
- Добавлено запоминание отказа пользователя от включения геосервисов, чтобы убрать назойливое появление диалога при любом возможном случае
=> [iOS] Fixed location manager

geocoder/CMakeLists.txt, geocoder/geocoder.cpp, geocoder/geocoder_cli/geocoder_cli.cpp, geocoder/geocoder_tests/geocoder_tests.cpp, geocoder/hierarchy.cpp, geocoder/hierarchy.hpp, geocoder/hierarchy_reader.cpp, geocoder/hierarchy_reader.hpp, geocoder/index.cpp, geocoder/index.hpp, geocoder/name_dictionary.cpp, geocoder/name_dictionary.hpp
Оптимизация по памяти: хранить имена полей адресов в словаре и в `Entry` использовать индексы на имя в словаре.
Расходы на память, на примере России: 6.3 GB в тек. версии и 0.9 GB - в этом PR. Скорость загрузки практически не изменилась.
=> [geocoder] Optimize memory: name dictionary for address parts

routing/index_graph.cpp
Получение геометрии не быстрая операция. В половине случаев в IndexGraph::IsJointOrEnd() ее можно не делать.
@gmoryes PTAL
=> [routing] IndexGraph::IsJoint or end optimization.

routing/routing_integration_tests/bicycle_turn_test.cpp
После обнолвения карт c 190719 до 190727 в ветке release-92 сломался один интеграционый тест: RussiaMoscowSalameiNerisPossibleTurnCorrectionBicycleWayTurnTest
Сейчас маршрут и маневры вполне соответствуют карте.
@gmoryes PTAL
=> [routing] Fixing routing integration tests for map 190727.

generator/generator_tests/regions_tests.cpp, generator/regions/country_specifier.cpp
Столицы в виде точки имеют admin_level=2 и не должны выигрывать у других admin_level регионов для region/subregion с одинаковой геометрией.
=> [generator:regions] Fix capital points affiliation

routing/leaps_postprocessor.cpp, routing/routing_integration_tests/route_test.cpp
Crash about comparison of equals elements during std::sort
=> [routing] Fix crash in LeapsPostprocessor

generator/regions/country_specifier.cpp, generator/regions/country_specifier.hpp, generator/regions/region.cpp, generator/regions/region.hpp, generator/regions/regions_builder.cpp
Фикс: если геометрии двух регионов совпадают, то они должны быть вложены один в другой, а не быть братьями в дереве.
RelateByWeight() возвращает: -1 - левый регион подчинён правому, 1 - правый левому.
=> [generator:regions] Fix commutative property of RelateByWeight()

generator/routing_index_generator.cpp, routing/base/astar_algorithm.hpp, routing/base/astar_graph.hpp, routing/index_graph_starter.hpp, routing/index_graph_starter_joints.hpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/world_graph.cpp, routing/world_graph.hpp
Added DropAStarParents method for AStarGraph, because after
AStarAlgorithm ended, IndexGraph still links with AStar's
parents which are have been already deallocated.
=> [routing] Fix crash in routing in IndexGraph::IsRestricted

routing/index_router.cpp, routing/index_router.hpp, routing/routing_integration_tests/route_test.cpp
In previous version start and finish could have only one
mwm related to them, but after adding several fake
segments, start and finish could be linked with
more than one mwm, because of that AreMwmsNear 
returns false when start or finish placed near mwm's 
border. Because of that LeapsOnly is chosen instead of
Joints mode.
=> [routing] Changed IndexRouter::AreMwmsNear

generator/generator_tests/geo_objects_tests.cpp
Закоменнтированная часть тестирует не самую важную часть логики, но использует временные файлы. На linux это работает, на mac надо отдебажить, или просто убрать
=> [generator_tests] mac fix

android/res/values-de/strings.xml, data/strings/types_strings.txt, iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
Fix German translation for dog park:
"Hundeauflauf" is actually something to eat containing dog meat :(
=> Fix German translation for dog park

search/geocoder.cpp, search/geocoder.hpp, search/search_integration_tests/processor_test.cpp
немногим ранее добавляла игнорирование требования посткода для дома, если он уже указан для всего населенного пункта
теперь добавляю то же самое для poi 
также в WithPostcodes добавлен эмит города, если после нахождения посткода в запросе все токены использованы (поддержка запросов вида "Юрьево 127001")
=> [search] Do not require POI to have a postcode if the city has.

search/reverse_geocoder.cpp
При локализации адреса имя топонима вычитывалось, но использовалось не всегда.
=> [geocoder] Fixed feature name in localized region address.

search/search_integration_tests/tracer_tests.cpp, search/tracer.cpp
Tracer assumed that every token will have a type but we
do not have a special type for unrecognized tokens and
set their type to COUNT instead. With relaxed parsing,
some tokens were left unclassified and this led to an error.
=> [search] Fixed an out-of-bounds error.

iphone/Maps/Classes/CarPlay/CarPlayService.swift
https://jira.mail.ru/browse/MAPSME-11563
Поговорила с Дашей. Вьюпорт настраивается до построения маршрута и, после того как маршрут построен, изменение вьюпорта не приводит к перепозиционированию. Так что после переноса маршрута на карплей, приходится перестраивать маршрут с новым вьюпортом.
=> [iOS] Fixed view port after recovering a trip on the carplay

search/intermediate_result.cpp, search/intermediate_result.hpp, search/pre_ranker.cpp, search/pre_ranking_info.hpp, search/ranker.cpp
Мы можем получить одну и ту же фичу несколькими способами, например в запросе "город улица дом", если в данных нету дома мы можем получить улицу по пути "город-улица", а можем получить заматчив только улицу.
В этом случае единственное отличие между PreRankerResult-ами будет TokenRange-ах, разумнее выбирать тот результат, у которого больше заматченых ранжей.
При прореживании улиц тоже разумно выбирать лучшую с точки зрения ранка, а не просто по расстоянию. Функция расчета ранка не дорогая -- у нас уже посчитаны все опечатки и т.п., вызвана будет только для линейных фичей с одинаковым именем, это не должно сказаться на производительности.
=> [search] Keep better result in PreRanker::Filter and RemoveDuplicatingLinear.

search/bookmarks/data.cpp, search/bookmarks/data.hpp, search/search_tests/CMakeLists.txt
Note that bookmark's custom name is still being indexed when it differs
from bookmark's name. This in fact has been the intended behaviour
all along.
=> [search] [bookmarks] Enabled indexing in the CurrentOrig locale.

generator/generator_tests/metadata_parser_test.cpp, generator/osm2meta.cpp, generator/osm2meta.hpp, indexer/feature_meta.cpp, indexer/feature_meta.hpp, indexer/map_object.hpp, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/geometry.cpp, routing/geometry.hpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/leaps_postprocessor.cpp, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/transit_route_test.cpp, routing/routing_quality/routing_quality_tests/ferry_tests.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, routing/world_graph.hpp
Надо прочитать: https://confluence.mail.ru/display/MAPSME/Ferries
Изменились 3 интеграционных теста:
1) Bicycle
Тут после подсчета статистики выяснилось, что паромом передвигаться почти всегда быстрее велика, поэтому, даже если несмотря штрафа на посадку, предпочитается паром, то видимо надо на паром
Было: 
Стало: 
2) Тут предпочитается один паром другому, причем опять же, скорость на пароме всегда больше, чем у пешехода, поэтому это в целом даже логичнее - поехать сразу на пароме до конца
Pedestrian
Было:
Стало:
3) Car
Тут вместо посадки на shuttle_train, едем по парому, с shuttle-train надо отдельно что-то делать
Было:
Стало:
=> [routing] penalty for ferries

map/routing_manager.cpp, routing/CMakeLists.txt, routing/position_accumulator.cpp, routing/position_accumulator.hpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/CMakeLists.txt, routing/routing_tests/position_accumulator_tests.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
При перепрокладке маршрута сейчас используется направление движения пользователя для лучшего выбора стартового сегмента маршрута. Чтоб вычислить направление используются 2 последние gps координаты.
Это иногда плохо работает. Например, когда клиент останавливается на светофоре и маршрут из-за загрузки пробок перестраивается.
Данный PR сохраняет историю из нескольких последних координат и на базе ряда координат вычисляет направление движения. Если клиент стоит - координаты не добавляются.
=> [routing] Accumulating position to calculate a better end user direction.

routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp
После обновления карт - поправлены 3 теста.
**RoutingQuality_TurkeyIzmirArea**
Около месяца назад подвинули дорогу проходящую около reference point. https://www.openstreetmap.org/way/319972296#map=15/39.0670/27.1086
Точку тоже надо подвинуть.
**RoutingQuality_EindhovenNetherlands**
Предпочитаем highway=motorway дороге highway=primary, что кажется вполне логичным.
**RoutingQuality_KatowicePoland**
Ведем по магистрали с ограничением в 130 вместо магистрали с ограничением 120, что кажется нормально.
@gmoryes PTAL
=> [routing] Routing quality tests fix for 190830.

routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/turn_test.cpp
После обновления карт (190830) поправил routing integration tests.
==================================
EnglandToFranceRouteLeMansTest
В предыдущей версии карт прокладывали авто маршрут через Ламанш по парому. Теперь по туннелю.
==================================
ThailandPhuketNearPrabarameeRoad
20 дней назад дорога, по которой покидаем магистраль потеряла таг link. И поэтому мы вместо ExitHighwayToLeft генерируем TurnSlightLeft. https://www.openstreetmap.org/way/632274299#map=18/7.91015/98.36795
@gmoryes PTAL
=> [routing] Fixing routing integration tests after map update to 190830.

routing/routing_integration_tests/road_graph_tests.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_quality/utils.cpp
В конце прошлой недели `DataSource::RegisterMap(localFile);` стала возвращать ошибку регистрации для WorldCoasts_obsolete.mwm и других устаревших файлов. Данный PR готовит routing integration tests и routing quality tests к тому, что `DataSource::RegisterMap(localFile);` может вернуть что-то отличное от успеха. В этом случае mwm для которых это происходит не используются.
@gmoryes @tatiana-yan PTAL
=> Fixing routing integration and quality test. Getting ready that DataSource::RegisterMap() may return not Success.

data/synonyms.txt
Short names according to ISO:
1. https://en.wikipedia.org/wiki/ISO_3166-2:AU
2. https://en.wikipedia.org/wiki/ISO_3166-2:NZ
All names are present in OSM at the moment. I use Chatham Islands instead Chatham Islands Territory as the name is not present in OSM yet.
=> Added short names for AU and NZ 

routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/features_road_graph.cpp, routing/features_road_graph.hpp, routing/index_graph.cpp, routing/index_graph.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_tests/index_graph_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/index_graph_tools.hpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/transit_graph.cpp, routing/transit_graph.hpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, routing/world_graph.hpp, routing_common/bicycle_model.cpp, routing_common/bicycle_model.hpp, routing_common/car_model.cpp, routing_common/car_model.hpp, routing_common/pedestrian_model.cpp, routing_common/pedestrian_model.hpp, routing_common/routing_common_tests/vehicle_model_test.cpp, routing_common/vehicle_model.hpp, track_analyzing/track_analyzer/cmd_tracks.cpp
Основания для данного PR следующие. Сейчас off road speed для машин 10 км в час. Эта скорость используется, как скорость для дуг соединяющих граф дорог с финишем и стартом. Это очень большая скорость, поскольку файковые дуги всегда выигрывают у реальных дуг с типа highway=track (Мы считаем, что на highway=track скорость 5 км в час) у service (15 км/ч), living_street(10 км/ч), у пирсов (17 км/ч за городом и 10 км/ч в городе), если у них плохое покрытие или они не очень прямые.
Примеры, где возникают проблемы: 
В данном PR мы делаем возможность задавать off road speed отдельно для ETA и для прокладки маршрута.
- это решает известные проблемы;
- это серьезно не ломает ни один тест. Т.е. тесты надо подправить, но маршруты хуже в них не стали;
- это позволяет точнее считать ETA особенно в …
=> [routing] Reducing offroad speed for car routing while route building and not to take into account it for ETA.

search/geocoder.cpp, search/pre_ranker.cpp, search/ranker.cpp
отдельный вопрос -- надо ли инициализировать геокодер/преранкер/ранкер и вызывать m_geocoder.Finish в процессоре при поиске по букмаркам
=> [search] Move UpdateResults from PreRanker::Finish to Geocoder::GoImpl to avoid uncaught CancelException.

routing/route.cpp
Т.к. чисто файковые дуги теперь не учитываются при вычислении ETA, их вес равен 0. А это значит, что чек ниже для них вызван быть не должен.
https://jira.mail.ru/browse/MAPSME-11849
https://jira.mail.ru/browse/MAPSME-11857
=> [routing] Crash fix. Pure fake edges should have zero weight.

generator/generator_tests/cluster_finder_tests.cpp, generator/place_processor.cpp, generator/place_processor.hpp
Это очень важное улучшение!
Вот кейс когда старый код бы работал плохо:
m_isSameFunc пророверяет имена, и если расстояние <= 1, то считет имена равными.
```
obj1(Имя1) obj2(Имя11) obj3(Имя111)
```
В старой реализации это бы отнеслось к одному кластеру
m_isSameFunc не должна делать проверку на близость, за это отвечает квадродерево
=> [generator] Some rework of ClustersFinder.

defines.hpp, generator/CMakeLists.txt, generator/affiliation.cpp, generator/affiliation.hpp, generator/collector_interface.hpp, generator/cross_mwm_osm_ways_collector.cpp, generator/cross_mwm_osm_ways_collector.hpp, generator/generator_tests/CMakeLists.txt, generator/generator_tests/cross_mwm_osm_ways_collector_tests.cpp, generator/generator_tool/generator_tool.cpp, generator/routing_index_generator.cpp, generator/routing_index_generator.hpp, generator/translator_country.cpp, routing/cross_mwm_connector_serialization.hpp, routing/index_router.cpp, routing/single_vehicle_world_graph.cpp
Смотреть после этого: https://github.com/mapsme/omim/pull/11624
На этапе раскидывания фичей по mwm мы используем геометрию более высокой точности, после чего, на этапе роутинга, используем геометрию из mwm (там меньше точности)
Из-за этого получалось так, при генерации одна и та же точка вначале принадлежала mwm, а потом нет, из-за этого случился баг на границе:
В качестве решения: теперь на этапе раскидывания фичей, мы запоминаем переходные фичи и записываем их в файл соответствующей mwm'ки, а на этапе роутинга вычитываем из файла
после PR все лечится:
=> [generator] [routing] Fix points accuracy

routing/base/followed_polyline.cpp, routing/base/followed_polyline.hpp, routing/index_router.cpp, routing/route.cpp, routing/route.hpp, routing/routing_integration_tests/speed_camera_notifications_tests.cpp, routing/routing_integration_tests/street_names_test.cpp, routing/routing_session.cpp, routing/routing_tests/followed_polyline_test.cpp, routing/routing_tests/route_tests.cpp
MAPSME-11809. Fix of 90-degree camera rotation on re-routing.
Screenshot of buggy behaviour while re-routing:
=> [routing] Match location only to real segments

coding/coding_tests/point_coding_tests.cpp, coding/point_coding.cpp, coding/point_coding.hpp
новые методы позволяют кодировать точки из заданного прямоугольника и экономить coordBits без потери качества
=> [coding] Add PointD <-> PointU encoding with limit rect.

editor/editor_tests/osm_editor_test.cpp, editor/osm_editor.cpp, editor/osm_editor.hpp, indexer/indexer_tests/data_source_test.cpp, indexer/mwm_set.cpp, indexer/mwm_set.hpp, map/features_fetcher.cpp, map/features_fetcher.hpp, map/framework.cpp, storage/diff_scheme/diff_manager.cpp, storage/storage.cpp
Fixes a couple of crashes related to map updates.
When an activity such as processing a search request or building a route was being performed during an update, there used to be a possibility of the map file to be deleted by an OnMapUpdated call even if its corresponding MwmValue had been properly locked.
=> [indexer] Removed the UPDATE event type from MwmSet.

ugc/storage.cpp, ugc/storage.hpp, ugc/ugc_tests/storage_tests.cpp
Тесты расчитывали что writable dir и директория в которой лежит файл, полученный через GetUGCFilePath совпадают.  Но это writable dir и config dir, которые в общем случае совпадать не обязаны -- на линуксе не совпадают.
Переписала тесты так, чтобы они "честно" получали имя файла от storage.
=> [ugc] Fix UGC_IndexMigrationFromV0ToV1Smoke test.

iphone/Maps/Bookmarks/BookmarksVC.mm, iphone/Maps/Categories/UIKitCategories.mm, iphone/Maps/Classes/Components/MWMMailViewController.mm, iphone/Maps/Classes/Components/MWMNavigationController.m, iphone/Maps/Classes/CustomAlert/CreateBookmarkCategory/MWMBCCreateCategoryAlert.xib, iphone/Maps/Classes/CustomAlert/MWMPlaceDoesntExistAlert.xib, iphone/Maps/Classes/CustomViews/MapViewControls/MWMMapViewControlsManager.mm, iphone/Maps/Common/MWMCommon.h, iphone/Maps/UI/Downloader/MWMBaseMapDownloaderViewController.mm, iphone/Maps/UI/EditBookmark/MWMBookmarkTitleCell.xib, iphone/Maps/UI/Editor/Cells/MWMEditorAdditionalNameTableViewCell.xib, iphone/Maps/UI/Editor/Cells/MWMEditorTextTableViewCell.xib, iphone/Maps/UI/Editor/Cuisine/MWMCuisineEditorViewController.mm, iphone/Maps/UI/Editor/MWMObjectsCategorySelectorController.mm, iphone/Maps/UI/Editor/Street/MWMStreetEditorEditTableViewCell.xib, iphone/Maps/UI/PlacePage/PlacePageLayout/Content/BookmarkCell/MWMBookmarkCell.xib, iphone/Maps/UI/Search/MWMSearchView.xib, iphone/Maps/UI/Storyboard/Authorization.storyboard
When built with xCode 11, any usage of private API crashes the app. So I removed it to prevent crashes
=> [iOS] remove references to undocumented API

track_analyzing/track_analyzer/cmd_table.cpp
При обработке данных за год, примерно после обработки 1/3 всех данных, нашелся трек, у которого старт и финиш совпадают по времени. Что приводит к ожидаемому check при вычислении скорости. `track_analyzing/utils.cpp:49 CHECK(secondsElapsed > 0) 0 0`. Данный PR выкидывает такие треки из обработки и выводит диагностическую информацию в случае появления такого трека.
@gmoryes PTAL
=> [routing] Handling rare cases when two point of track has the same time.

generator/search_index_builder.cpp, geometry/mercator.cpp, geometry/mercator.hpp, search/postcode_points.cpp, search/postcode_points.hpp, search/search_index_values.hpp, search/search_integration_tests/postcode_points_tests.cpp
Предыдущая реализация была хороша для 75к индексов, но оказалась плоха для 1.7м индексов.
Раньше:
- 10к индексов в Лондоне занимали 280кб
Теперь:
- 190к индексов в Лондоне занимают 1.6Мб.
Различия:
- не храним списки для outer индексов, рекурсивно извлекаем их из дерева
- при хранении значений в индексе испльзуем то, что у каждого ключа ровно одно значение, поэтому храним значение как varuint, а не как cbv.
В качестве дальнейших оптимизаций планируется при сохранении centers table использовать знания про limit rect mwm чтобы уменьшить количество битов на точку без потери качества.
=> [search] Optimize postcodes index.

android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp, android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java, drape_frontend/backend_renderer.cpp, drape_frontend/drape_engine.cpp, drape_frontend/message_subclasses.hpp, drape_frontend/user_mark_generator.cpp, drape_frontend/user_mark_generator.hpp, drape_frontend/user_marks_provider.hpp, map/bookmark_manager.cpp, map/bookmark_manager.hpp, map/map_tests/bookmarks_test.cpp, map/track.hpp
В рамках задачи по оптимизации UI на Андроиде потребовалось кеширование категорий букмарок. Для инвалидации этого кеша в PR добавлен callback, уведомляющий о наличии изменений в букмарках.
Выполнен рефакторинг системы отслеживания изменений букмарок: установка паузы на отправку "тяжелых" уведомлений в поисковый движок и Drape не мешает отправке уведомлений о наличии изменений.
=> [bookmarks] Changes tracker refactoring.

data/replaced_tags.txt, generator/CMakeLists.txt, generator/filter_collection.cpp, generator/filter_collection.hpp, generator/filter_elements.hpp, generator/filter_interface.hpp, generator/filter_planet.cpp, generator/filter_roads.cpp, generator/filter_roads.hpp, generator/filter_world.cpp, generator/filter_world.hpp, generator/generator_integration_tests/features_tests.cpp, generator/translator.cpp, generator/translator_country.cpp, generator/translator_world.cpp
There is a pair of keys in OSM which indicates roads built over land on compacted snow, bare ground or on a floating ice cover: [winter_road](https://taginfo.openstreetmap.org/keys/winter_road#values), [ice_road.](https://taginfo.openstreetmap.org/keys/ice_road#values)
We want to implement functionality (ticket [MAPSME-10786](https://jira.mail.ru/browse/MAPSME-10786)):
- Do not show ice roads on maps (both nodes and ways)
- Handle ice roads in navigation mode: never show routs through ice roads
There is over 15k of ice roads in OSM.
Ice roads example:
=> [generator][routing] Handle ice roads

editor/editor_tests/CMakeLists.txt, feature_list/CMakeLists.txt, generator/booking_quality_check/CMakeLists.txt, indexer/indexer_tests/CMakeLists.txt, map/map_integration_tests/CMakeLists.txt, openlr/openlr_tests/CMakeLists.txt, search/search_integration_tests/CMakeLists.txt, ugc/ugc_tests/CMakeLists.txt
Поправлена сборка. Была ошибка:
```
libgenerator.a(restriction_generator.cpp.o)
vtable for routing::CarModelFactory in libgenerator.a(restriction_generator.cpp.o)
"typeinfo for routing::VehicleModel", referenced from:
typeinfo for routing::CarModel in libgenerator.a(restriction_generator.cpp.o)
"typeinfo for routing::VehicleModelFactory", referenced from:
typeinfo for routing::CarModelFactory in libgenerator.a(restriction_generator.cpp.o)
"vtable for routing::VehicleModel", referenced from:
routing::VehicleModel::~VehicleModel() in libgenerator.a(restriction_generator.cpp.o)
NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
"vtable for routing::VehicleModelFactory", referenced from:
routing::VehicleModelFactory::~VehicleModelFactory() in …
```
=> feature_list_generator build fix.

generator/search_index_builder.cpp, geometry/mercator.cpp, geometry/mercator.hpp, search/search_integration_tests/postcode_points_tests.cpp
Конвертация координат оказалась не так проста -- метры меряются не по поверхности земли, а по собственному варианту проекции меркатора. Не вижу смысла тащить её в проект, предлагаю конвертировать датасет перед использованием, код конвертации тривиальный:
```
import csv
from OSGridConverter import grid2latlong
from OSGridConverter import OSGridReference
with open('~/data/uk_postcodes_grid', newline='') as old:
old_reader = csv.reader(old)
for row in old_reader:
postcode = row[0]
g = OSGridReference(int(row[2]),int(row[3]))
ll = g.toLatLong(tag='WGS84')
print(postcode+","+ll.__str__()) 
```
=> [search] Use pre-converted dataset for UK postcodes.

generator/feature_builder.cpp, generator/generator_integration_tests/features_tests.cpp, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, indexer/indexer_tests/checker_test.cpp
У тага точечного highway=motorway_junction есть поля ref и name. Поле ref - надпись, куда поворачивать. Поле name - название города (местности) куда поворачивать. Часто бывает, что в один город (местность) можно повернуть с многих съездов.
С другой стороны в адресах в Европе часто пишут номер съезда (попадает в поле ref). То что это так, я делаю вывод на основании жалоб пользователей время от времени + мой личный опыт (Испания, Франция. Повороты с магистралей).
Около поворота на магистрали на карте лучше подписывать номер поворота (или название поворота), который попадает в таг ref, а не название города. Название города, в удалении от города смотрится вообще не однозначно.
Данный PR влияет на случай, когда highway=motorway_junction, ref=* и name=* заданы одновременно. Приоритет теперь …
=> [generator] Using ref tag if there's one for highway-motorway_junction.

generator/osm2type.cpp
There is about 14.3k of tags **4wd_only** with values "yes" or "recommended". This tag marks roads only suitable for 4WD-only vehicles. [Ticket MAPSME-12152.](https://jira.mail.ru/browse/MAPSME-12152)
The purpose of this PR is to mark such roads as `unpaved_bad` thus to pessimize the routes on `4wd_only` roads.
[Road](https://www.openstreetmap.org/way/52106287#map=14/60.2530/18.5741) marked with `4wd_only` in OSM on our map before PR:
After PR:
=> [generator] Add 4wd_only to replaced_tags.

drape_frontend/stylist.cpp
Графический движок запрещает ситуацию, когда у объектов существует secondary text без наличия primary text.
Как воспроизводится крэш. Берем объект, у которого название есть только по-русски, а стиль предполагает наличия номера дома (который оказывается не проставленным). Запускаем приложение на английской локали, название на русском транслитерируется. Транслитерированное название становится primary text, русское - secondary. Номер дома (пустая строка) при применении стиля заменяет primary text (в методе ProcessMainTextType). Оказывается, что primary text - пустой, secondary - не пустой.
=> [drape] Fixed crash in stylist

indexer/data_source.cpp, indexer/data_source.hpp, indexer/indexer_tests/mwm_set_test.cpp, indexer/indexer_tests/test_mwm_set.hpp, indexer/mwm_set.cpp, indexer/mwm_set.hpp, routing/routing_tests/road_graph_builder.cpp, traffic/traffic_tests/traffic_info_test.cpp
после этого PR избавлюсь от шаблонности в:
```cpp
handle.GetValue<MwmSet::MwmValue>();
```
=> [indexer] Get rid of MwmValueBase

qt/bookmark_dialog.cpp
Чтобы было удобно выбирать несколько файлов сразу, когда хочешь посмотреть на kml
А не тыкать 10 раз "import"
=> [qt] Add selection of several files in bookmark manager

routing/routes_builder/routes_builder.cpp, routing/routes_builder/routes_builder.hpp, routing/routes_builder/routes_builder_tool/routes_builder_tool.cpp, routing/routes_builder/routes_builder_tool/utils.cpp, routing/routes_builder/routes_builder_tool/utils.hpp
Проблемы:
1) Зачем-то я написал так, что все результаты сохраняются в 
```cpp
std::vector<RoutesBuilder::Result>
```
(ф-ия BuildRoutes возвращала вектор, который потом никак не используется), из-за этого (теоретически) постоянно росло потребление памяти. В этом векторе самое тяжелое - это хранится вся геометрия маршрута (все его точки).
2) Существует N маршрутов, на которых тулза прям застревала, посмотрел на них руками, все они примерно об одном и том же (о Египте). Там landuse-military и стоит border-control (в осме стоит vehicle_motor=no):
И на остальных путях что-то подобное
В итоге получалась такая картина:
Красными стрелочками я примерно обозначил старт и финиш.
Такая картина получается на desktop, если подождать какое-то время, конца построения я естественно не дожидался. …
=> [routing] May be fix enormous memory usage in routes_builder_tool

tools/python/maps_generator/README.md, tools/python/maps_generator/__main__.py
Проблема такая:
1) есть .osm.pbf file
2) хочу сгенерить все mwm, которые попали в этот файл
3) не хочу никаких World/Coast и чего-то еще
пишу:
```sh
python3 -m maps_generator --countries="*" --skip="coastline"
```
на что получаю, что нельзя скипать `coastline`, если генеришь `World*`
А генерю `World*` я из-за `--countries="*"`
Короче новая опция позволяет исключать страны из генерации, работает так же как и `--countries`
Например, если хочется собрать европу, но без Германии и Англии, то можно написать:
```sh
python3 -m maps_generator --countries="*" --skip="coastline" --without_countries="World*, UK*, Germany*"
```
=> [generator] maps_generator --without_countries option

platform/mwm_traits.cpp
В мастере изменился формат centers table, но мы продолжаем выпускать минорки из релизной ветки, поэтому для совместимости с релизными картами нужно апдейтить константу (только для минорок 9.4, в релизной ветке 9.5 будет уже новый код).
=> [platform][mwm_traits] Adjust kLastVersionWithPlainEliasFanoMap for centers table.

defines.hpp, generator/CMakeLists.txt, generator/collector_interface.hpp, generator/collector_mini_roundabout.cpp, generator/collector_mini_roundabout.hpp, generator/final_processor_intermediate_mwm.cpp, generator/final_processor_intermediate_mwm.hpp, generator/generator_integration_tests/features_tests.cpp, generator/generator_tests/CMakeLists.txt, generator/generator_tests/mini_roundabout_tests.cpp, generator/mini_roundabout_info.cpp, generator/mini_roundabout_info.hpp, generator/mini_roundabout_transformer.cpp, generator/mini_roundabout_transformer.hpp, generator/raw_generator.cpp, generator/translator_country.cpp
There is about 51.6k of nodes with tag `highway=mini_roundabout` [in OSM.](https://taginfo.openstreetmap.org/tags/highway=mini_roundabout) But currently we handle only roundabouts marked as `junction=roundabout`. 
**The solution** is to transform mini_roundabout nodes to ways with tag `junction=roundabout` and relevant [highway type.](https://wiki.openstreetmap.org/wiki/Key:highway#Values) 
[Ticket MAPSME-11920](https://jira.mail.ru/browse/MAPSME-11920).
**The purposes** of this PR:
- To prevent errors when driving according to our routs. Make routing algorithms correctly handle this type of roundabouts.
- To make the visual representation of the map more relevant to reality.
- To prepare the algorithmic base for further improvements of handling roundabouts:  highway=turning_circle, …
=> [generator][routing] Handle mini_roundabouts.

android/jni/com/mapswithme/maps/Framework.cpp, iphone/Maps/Core/Framework/ProxyObjects/Routing/MWMRoutingManager.mm, iphone/Maps/Core/Routing/MWMRouter.mm, map/routing_manager.hpp, qt/draw_widget.cpp, routing/async_router.hpp, routing/bicycle_directions.cpp, routing/index_router.cpp, routing/index_router.hpp, routing/router_delegate.cpp, routing/router_delegate.hpp, routing/routes_builder/routes_builder.hpp, routing/routing_helpers.cpp, routing/routing_tests/async_router_test.cpp, routing/routing_tests/routing_algorithm.cpp, routing/routing_tests/routing_session_test.cpp, routing/turns_generator.cpp, routing/turns_generator.hpp
1) переписал RouterDelegate на новый base::Cancellable (@mpimenov написал логику Deadline там недавно)
2) теперь RouterDelegate не является наследником base::Cancellable, потому что в моей голове это должна быть композиция, а не наследование, так как если это наследник base::Cancellable, то почему у него есть OnProgress() PointCheck() и всякое такое
=> [routing] Refactor RouterDelegate

android/build.gradle, android/gradle.properties, android/src/com/mapswithme/maps/scheduling/JobServiceDelegate.java, android/src/com/mapswithme/util/ConnectionState.java
https://jira.mail.ru/browse/MAPSME-12371 Обновил пушвуш сдк. Пофиксил NPE, который в топе в Google developer console:
```
java.lang.RuntimeException: 
at android.app.job.JobServiceEngine$JobHandler.handleMessage (JobServiceEngine.java:112)
at android.os.Handler.dispatchMessage (Handler.java:105)
at android.os.Looper.loop (Looper.java:180)
at android.app.ActivityThread.main (ActivityThread.java:6944)
at java.lang.reflect.Method.invoke (Method.java)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:835)
Caused by: java.lang.NullPointerException: 
at com.mapswithme.util.ConnectionState.getActiveNetwork (ConnectionState.java:57)
at com.mapswithme.util.ConnectionState.isNetworkConnected …
```
=> Mapsme 12371 update pushwoosh

generator/cross_mwm_osm_ways_collector.cpp
Проблема: сборка мира крэшится в `CrossMwmOsmWaysCollector::CollectFeature`:
`Program received signal SIGSEGV, Segmentation fault.`
Верхушка стэка:
```
#0  0x0000000001c76980 in std::_Bit_reference::operator= (this=0x7fed3a72e790, __x=true) at /home/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/stl_bvector.h:87
#1  0x0000000001dfb401 in generator::CrossMwmOsmWaysCollector::CollectFeature (this=0xa25daf0, fb=..., element=...) at /home/o.khlopkova/omim/generator/cross_mwm_osm_ways_collector.cpp:67
```
**Причина:** в цикле в мапу по ключу (имя mwm) в поле-значение (вектор из bool) присвоилось значение по не существующиему индексу  `pointNumber`:
```
for (auto const & mwmName : pointAffiliations)
featurePointsEntriesToMwm[mwmName][pointNumber] = true;
```
Мапа `featurePointsEntriesToMwm` …
=> [generator] Fix for segmentation fault in cross mwm collector.

indexer/indexer_tests/search_string_utils_test.cpp, indexer/search_string_utils.cpp
Полезно если нужно проиндексировать и искать что-то с пробелами (например индексы).
Можно сделать отдельной функцией, но не вижу причин почему не делать сразу в NormalizeAndSimplifyString.
=> [search] NormalizeAndSimplifyString: replace sequence of spaces with single one.

generator/search_index_builder.cpp, search/search_integration_tests/postcode_points_tests.cpp
Разобралась с форматом посткодов, есть возможность однозначано восстановить посткод в формате "outer inner" из данных датасета, потому что inner всегда 3 символа naa.
=> [search] Fix postcodes format for postcodes search index.

generator/generator_tests/metadata_parser_test.cpp, generator/osm2meta.cpp, generator/osm2meta.hpp, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp
Детали о том когда заполнять или не заполнять значения для всех остальных типов убраны в ValidateAndFormat, например:
```C++
string MetadataTagProcessorImpl::ValidateAndFormat_operator(string const & v) const
{
auto const & isATM = ftypes::IsATMChecker::Instance();
auto const & isFuelStation = ftypes::IsFuelStationChecker::Instance();
if (!(isATM(m_params.m_types) || isFuelStation(m_params.m_types)))
return string();
return v;
}
```
=> [generator] Osm2meta minor refactoring.

defines.hpp
Планируется вынести FMD_POSTCODES в отдельную секцию и логично будет назвать ее postcodes, поэтому переименовываю POSTCODE_POINTS_FILE_TAG в postcode_points.
Ещё не было ни одной "боевой" генерации данных с postcodes, поэтому это переименование сейчас ни на что не повлияет.
=> [defines] Rename POSTCODE_POINTS_FILE_TAG to postcode_points.

indexer/ftypes_matcher.cpp
https://confluence.mail.ru/pages/viewpage.action?pageId=287950469#id-%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5admin_centre-formula_after_boost
Что произошло: формула вычисления площади поменялась на boost::area(...)
А коэффициенты последние считались для ф-ии, которая работала не так хорошо
=> [generator] Recount coefs for GetRadiusByPopulationForRouting 

generator/generator_integration_tests/features_tests.cpp
кажется так в месте вызова понятнее что происходит, особенно там где mixed nodes:
`TestCountry(southSouthland, kSouthSouthlandCounters + kSouthSouthlandMixedNodesCounters, ...)`
убрано дублирование для world и для southSouthland, в TestCountry всё собрано в одну структуру
=> [generator][tests] Generator integration tests minor refactoring.

android/jni/com/mapswithme/util/HttpUploader.cpp, map/bookmark_catalog.cpp, map/cloud.cpp, map/user.cpp, platform/CMakeLists.txt, platform/http_payload.cpp, platform/http_payload.hpp, platform/http_uploader.hpp, platform/http_uploader_apple.mm, platform/http_uploader_background.hpp, xcode/platform/platform.xcodeproj/project.pbxproj
- Реализация структуры `HttpPayload`, содержащей поля для отправки данных по HTTP.
- Замена отдельных полей в классе `HttpUpload` на структуру `HttpPayload`, добавление геттеров для полей структуры.
- Класс `HttpBackgroundUploader` с методом-заглушкой `Upload()` и полем `HttpPayload`. Метод `Upload()` **должен быть реализован на платформах** для отправки файла по HTTP по событию подключения wi-fi, в том числе из бэкграунда.
=> [Platform][Android][iOS] Upload file in background.

generator/collector_routing_city_boundaries.cpp, generator/feature_builder.cpp, generator/feature_builder.hpp, generator/feature_maker_base.cpp, generator/feature_maker_base.hpp, generator/feature_processing_layers.cpp, generator/final_processor_intermediate_mwm.cpp, generator/generator_tests/feature_builder_test.cpp, generator/generator_tests/place_processor_tests.cpp, generator/place_processor.cpp, generator/world_map_generator.hpp, indexer/feature_data.cpp, indexer/feature_data.hpp
Текущая сборка карт упала несколько раз, думаю что входные данные поменялись и это привело к падениям генератора.
вот фиксы :
1. [generator] Check -> IsValid: added more logging. Функция  Check вызывала падение, из за этого очень сложно было понять какой именно элемент вызвал ошибку, сейчас просто вернет бул, там где важно что бы фб была валидной есть CECK(fb.IsValid(), (fb));
2 .[generator] Fixed booking processing. Фикс падения при обработке букинга, с элемента удалился тэг отеля, а других типов у объекта не было, это вызвало падение.
3. [generator] Fixed wrong feature builder transformations. Changed functions for feature builder transformation. Изменены функции трансформации, после падения генрации world
=> [generator] Fixed generation.

generator/gen_mwm_info.cpp, generator/gen_mwm_info.hpp, generator/generator_tests/gen_mwm_info_tests.cpp, generator/hierarchy.cpp, generator/hierarchy.hpp
Когда генерил иерахию для популярити столкнулся с некоторыми пролбемами:
[generator] Fixes cyclic connections. 
Испправляет циклические связи, раньше две геометрии проврялись на строгую вложенность, теперь дупоскается погрешность, из за этого проверки IsEqualGeometry теперь недостаточно.
[generator] Fixed GetFeatureId(CompositeId const & id).
Для элемента с одним CompositeId может найтись несколько фичей, самый простой пример: для замкнутого way который мы хотим нарисовать залитым и с обводкой, придется добавить две фичи с типами Area и Line
=> [generator] Fixes for hierarchy

drape_frontend/backend_renderer.cpp, drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/message_subclasses.hpp, map/framework.cpp, map/framework.hpp, qt/draw_widget.cpp, qt/draw_widget.hpp, qt/main.cpp, qt/mainwindow.cpp, qt/qt_common/map_widget.hpp, qt/screenshoter.cpp, qt/screenshoter.hpp
…for positioning on the map.
Теперь можно делать скриншоты не только для kml файлов, но и по списку прямоугольников или списку точка+зум.
Десктопную версию приложения можно запустить в режиме скриншотилки одним из параметров командной строки:
**-kml_path** - путь к kml файлу или директории с kml файлами, для которых нужно снять скриншот.
**-rects** - строка в формате "lat_leftBottom,lon_leftBottom,lat_rightTop,lon_rightTop[;lat_leftBottom,lon_leftBottom,lat_rightTop,lon_rightTop] или путь к файлу с прямоугольниками в этом формате, так же в файле вместо ';' можно использовать '\n'
**-points** - строка в формате "lat,lon,zoom[;lat,lon,zoom]" или путь к файлу с точками в этом формате, так же в файле вместо ';' можно использовать '\n'
дополнительные параметры:
-dst_path - путь к директории, …
=> [qt] Screenshoter accepts viewport center points and zoom or rects

routing/routes_builder/routes_builder.cpp, routing/routes_builder/routes_builder.hpp, routing/routes_builder/routes_builder_tool/routes_builder_tool.cpp, routing/routes_builder/routes_builder_tool/utils.cpp, routing/routes_builder/routes_builder_tool/utils.hpp, routing/routing_quality/routing_quality_tool/routing_quality_tool.cpp, routing/routing_quality/routing_quality_tool/utils.cpp, routing/routing_quality/routing_quality_tool/utils.hpp
Добавляется функционал для бенчмарков, если к routes_builder_tool добавить `--benchmark`, то каждый маршрут построится 3 раза, и сдампится усредненный результат
routing_quality_tool в свою очередь умеет парсить это и выводить всякие статистики через питоновские скрипты:
Пример вывода:
```sh
LOG TID(1) INFO   2.0328e-05 routing_quality_tool/routing_quality_tool.cpp:253 Main() Start loading mapsme results.
LOG TID(1) INFO  0.000492419 routing_quality_tool/utils.hpp:50 LoadResults() Progress: 100 %
LOG TID(1) INFO   0.00464218 routing_quality_tool/routing_quality_tool.cpp:255 Main() Receive: 1 routes from --mapsme_results.
LOG TID(1) INFO   0.00465548 routing_quality_tool/routing_quality_tool.cpp:273 Main() Running in benchmark stat mode.
LOG TID(1) INFO    0.0209546 …
```
=> [routing] Add benchmark modes for routing tools

routing/CMakeLists.txt, routing/base/astar_algorithm.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/junction_visitor.hpp, routing/routing_helpers.cpp, routing/routing_helpers.hpp, routing/routing_tests/astar_algorithm_test.cpp, routing/routing_tests/index_graph_tools.cpp, routing/routing_tests/routing_algorithm.cpp
В коде много повторяющихся частей, типа:
```cpp
uint32_t visitCount = 0;
double lastValue = progress.GetLastPercent();
auto const onVisitJunctionJoints = [&](JointSegment const & from, JointSegment const & to)
{
++visitCount;
if (visitCount % kVisitPeriod != 0)
return;
m2::PointD const & pointFrom = jointStarter.GetPoint(from, true /* front */);
m2::PointD const & pointTo = jointStarter.GetPoint(to, true /* front */);
auto const newValue = progress.UpdateProgress(pointFrom, pointTo);
if (newValue - lastValue > kProgressInterval)
{
lastValue = newValue;
delegate.OnProgress(newValue);
}
delegate.OnPointCheck(pointFrom);
};
```
Вынес эту логику в JunctionVisitor
=> [routing] Add junction visitor

generator/feature_maker.cpp, generator/generator_integration_tests/features_tests.cpp
Код странный, похоже что остался при разделении кода для relation-way-node на разные функции.
В этом коде если у нас есть замкнутый way, то мы берём "дырки" из релейшенов в которые входит этот way и пытаемся применить к нему.  По идее делать этого не надо, мультиполигоны с "дырками" будут получены из релейшенов.
DNM до создания ветки 9.5
=> [generator] Remove setting relation holes geometry to ways from this relation.

defines.hpp, generator/CMakeLists.txt, generator/feature_sorter.cpp, generator/generator_tool/generator_tool.cpp, generator/postcodes_section_builder.cpp, generator/postcodes_section_builder.hpp, generator/search_index_builder.cpp, indexer/CMakeLists.txt, indexer/indexer_tests/CMakeLists.txt, indexer/indexer_tests/postcodes_tests.cpp, indexer/postcodes.cpp, indexer/postcodes.hpp, xcode/indexer/indexer.xcodeproj/project.pbxproj
Сейчас почтовые индексы хранятся в метадате не экономично (как строки с большим количеством дублирования, в среднем один индекс дублируется 60 раз на mwm).
В этом реквесте новая секция для индексов, которая хранит их более сжатым образом. Удаление из метадаты и переход на использование новой секции будет отдельным реквестом, чтобы было проще смотреть.
До создания релизной ветки 9.5 мержить не стоит
=> [indexer][generaror] Add postcodes section.

generator/collector_camera.cpp, generator/collector_camera.hpp, generator/collector_city_area.cpp, generator/collector_city_area.hpp, generator/collector_collection.cpp, generator/collector_collection.hpp, generator/collector_interface.hpp, generator/collector_mini_roundabout.cpp, generator/collector_mini_roundabout.hpp, generator/collector_routing_city_boundaries.cpp, generator/collector_routing_city_boundaries.hpp, generator/collector_tag.cpp, generator/collector_tag.hpp, generator/cross_mwm_osm_ways_collector.cpp, generator/cross_mwm_osm_ways_collector.hpp, generator/feature_maker_base.cpp, generator/feature_maker_base.hpp, generator/holes.cpp, generator/holes.hpp, generator/intermediate_data.hpp, generator/maxspeeds_collector.cpp, generator/maxspeeds_collector.hpp, generator/metalines_builder.cpp, generator/metalines_builder.hpp, generator/restriction_writer.cpp, generator/restriction_writer.hpp, generator/road_access_generator.cpp, generator/road_access_generator.hpp, generator/ways_merger.cpp, generator/ways_merger.hpp
Предлагается создать IntermediateDataReaderInterface -- базовый класс для IntermediateDataReader и использовать его в коллекторах.
Это позволит создавать костомные IntermediateDataReader для тестов (например возвращать значения из захардкоженного map). Без этого очень проблематично тестировать функцию `Collector::Collect(OsmElement const & el)`, если она использует cache.
=> [generator] Create IntermediateDataReaderInterface

generator/generator_tests/CMakeLists.txt, generator/generator_tests/collector_boundary_postcode_tests.cpp, generator/intermediate_elements.hpp
Первый коммит сейчас оформлен отдельным реквестом (https://github.com/mapsme/omim/pull/12115).
Тесты отдельно т.к. для них требовалось 3 технических реквеста в генератор
(https://github.com/mapsme/omim/pull/12113 https://github.com/mapsme/omim/pull/12116 https://github.com/mapsme/omim/pull/12117), которыми не хотелось засорять основной реквест с добавлением CollectorBoundaryPostcode.
К тому моменту как были влиты реквесты в генератор основной реквест уже частично поревьюили.
Драфт до мержа https://github.com/mapsme/omim/pull/12115
=> [generator][tests] Add CollectorBoundaryPostcode tests.

generator/feature_builder.cpp
Забытая тудушка, метод используется только в тестах -- для настойщей сборки карт устанавливается сразу в параметры в osm2type.
Но тесты не парсят osm, а работают сразу с FeatureBuilder, поэтому нужен метод, который добавляет в FeatureBuilder.
=> [generator] Remove setting postcode to metadata for tests.

base/timer.cpp, base/timer.hpp, routing/index_router.cpp, routing/index_router.hpp
Сейчас ф-ия  `CalculateSubroute` это большая ф-ия с кучей `if (mode == WorldGraphMode::LeapsOnly)`  итд итп, разделил весь код вызовов эти трех режимов в разные методы
=> [routing] Split logic of different routings modes into different methods

android/jni/com/mapswithme/maps/Framework.cpp, generator/altitude_generator.cpp, generator/altitude_generator.hpp, generator/feature_segments_checker/feature_segments_checker.cpp, generator/generator_tests/altitude_test.cpp, generator/srtm_parser.cpp, generator/srtm_parser.hpp, geometry/point_with_altitude.cpp, geometry/point_with_altitude.hpp, indexer/altitude_loader.cpp, indexer/altitude_loader.hpp, indexer/feature_altitude.hpp, iphone/Maps/Core/Routing/MWMRouter.mm, map/chart_generator.cpp, map/chart_generator.hpp, map/map_tests/chart_generator_tests.cpp, map/routing_manager.cpp, map/routing_manager.hpp, routing/edge_estimator.cpp, routing/fake_ending.cpp, routing/features_road_graph.cpp, routing/geometry.cpp, routing/geometry.hpp, routing/nearest_edge_finder.cpp, routing/road_graph.hpp, routing/route.cpp, routing/route.hpp, routing/routing_integration_tests/get_altitude_test.cpp, routing/routing_session.cpp, routing/routing_session.hpp
Refactoring of old-style naming of `TAltitude` (TAltitudes)  to `Altitude` (Altitudes).
=> [Geometry] Renamed TAltitude to Altitude.

indexer/ftypes_matcher.cpp, routing/bicycle_directions.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/transit_route_test.cpp
**SwedenStockholmBicyclePastFerry**
Срабатывал ASSERT в debug режиме на тесте SwedenStockholmBicyclePastFerry. В релизе тест проходил. Причина была в том, что к маршруту примыкала фича highway-construction. Это возможный кейс. Такие "дороги" (фичи) сейчас поступают к генератору маневров. А он хочет получить у них HighwayClass. Добавил такие фичи в HighwayClass.
**Transit_London_DeptfordBridgeToCyprus**
Незначительно изменилась длина маршрута.
Стало:
**Transit_Piter_TooLongPedestrian**
В карте 191019 станция Шушары была. 
Но у нее был сломан выход. 
На 191124 вход починился и пешеходная часть маршрута стала не большой. Маршрут стал прокладываться.
Чтоб тест отвечал своему названию, отдаляем точку финиша от станции метро Шушары еще сильнее. Теперь тест говорит, что пешеходная часть слишком …
=> [routing] Routing integration tests fixing.

generator/generator_tests_support/test_mwm_builder.cpp, generator/search_index_builder.cpp
реквест поверх
https://github.com/mapsme/omim/pull/12170
Чтобы можно было добавить в секцию с посткодами дополнительные данные и они автоматически проиндексировались в поиске, нужно использовать для построения поискового индекса данные оттуда (а не полученные напрямую из промежуточного файла). Механизм получения посткодов из секции с посткодами -- FeatureType::GetPostcode().
=> [generator][search] Use postcodes section for search index build.

routing/cross_mwm_index_graph.hpp
Drop twin segments if they have another direction,
this could happend because of different mwms versions.
=> [routing] New filter for cross mwm segments.

geometry/geometry_tests/polyline_tests.cpp, geometry/point_with_altitude.hpp, geometry/polyline2d.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/routing_integration_tests/pedestrian_route_test.cpp
В данном PR обобщен метод CalcMinSquaredDistance(), чтоб его можно было использовать и с vector<m2::PointD> и с buffer_vector<PointWithAltitude>.
Затем он использован в EraseIfDeadEnd(), чтоб начинать поиск не с первого сегмента фичи, а с ближайшего сегмента. Эвристика с поиском с первого сегмента фичи использовалась ранее и оказалась не работоспособной при старте маршрута с фичи, которая пересекает границу mwm, так же прерывается бродом или подобным препятствием.
RussiaSmolenskAriaFeatureCrossingBorderWithFord
=> [routing] Using method for getting the closest segment in EraseIfDeadEnd().

generator/booking_dataset.cpp, generator/feature_builder.cpp, generator/feature_builder.hpp, generator/feature_maker.cpp, generator/feature_maker.hpp, generator/feature_maker_base.cpp, generator/feature_maker_base.hpp, generator/feature_processing_layers.cpp, generator/feature_processing_layers.hpp, generator/generator_tests/descriptions_section_builder_tests.cpp, generator/generator_tests/feature_builder_test.cpp, generator/generator_tests/metadata_parser_test.cpp, generator/generator_tests/osm2meta_test.cpp, generator/generator_tests/osm_type_test.cpp, generator/opentable_dataset.cpp, generator/osm2meta.hpp, generator/osm2type.cpp, generator/osm2type.hpp, indexer/feature_data.cpp, indexer/feature_data.hpp, search/search_integration_tests/generate_tests.cpp
перенесла поля
```C++
bool m_reverseGeometry;
feature::Metadata m_metadata;
feature::AddressData m_addrTags;
```
которые используются только для генерации из FeatureParams в наследника FeatureBuilderParams.
Удалила метод AddAddress, который не использовался (использование было закомментировано) и имеет плохую реализацию -- он пытается распарсить полный адрес, но при этом поддерживает только формат "дом улица", а в реальных данных типичное содержимое поля "addr:full" это что-то типа "Капотня 2-й квартал, 22" (а в букинге ещё хлеще) -- если решим парсить, то нужно писать другой парсер.
Есть альтернативная реализация -- удалить поля из FeatureParams и перенести их сразу в FeatureBuilder: https://github.com/mapsme/omim/pull/12040/files
=> [indexer][generator] Create FeatureBuilderParams with members used for mwm generation only.

generator/routing_index_generator.cpp, routing/base/astar_algorithm.hpp, routing/base/astar_graph.hpp, routing/base/astar_weight.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_graph_starter_joints.hpp, routing/route_weight.hpp, routing/routing_tests/index_graph_tools.hpp, routing/world_graph.cpp
ф-ия routing/cross_mwm_index_graph.hpp:GetTwinsByCrossMwmId
проверяет, что геометрии twin'ов - одинаковые, поэтому этот код бесполезен, потому что:
1) никогда не исполняется
2) был еще до того, как добавилась проверка на геометрию и не гарантирует корректную работу в случае разных геометрий
=> [routing] Remove useless code

routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp
Данная группа outing quality tests на то, чтоб маршруты прокладывались по большим дорогам. В случае этого теста возможны 2 варианта:
Более короткий путь по прямому highway=trunk, как это было в картах 190910:
И более длинный путь, по highway=motorway (с большим maxspeed), как это стало на картах 191124:
Учитывая, что от релиза к релизу карт эти 2 маршрута иногда меняются, и что оба они представляются корректными я задаю 2 варианта, как возможные.
=> [routing] Fixing routing quality test RoutingQuality_IranSouth.

generator/booking_dataset.cpp, generator/booking_quality_check/booking_quality_check.cpp, generator/feature_builder.cpp, generator/feature_builder.hpp, generator/generator_tests/feature_builder_test.cpp, generator/generator_tests_support/test_feature.cpp, indexer/feature_data.cpp, indexer/feature_data.hpp, indexer/feature_meta.cpp, indexer/feature_meta.hpp
FeatureBuilderParams::GetStreet() использовалась только для отладочной печати, переделала там отладочную печать.
FeatureBuilder::Add* использовались только в тестах и booking_dataset. Проблема с ними в том, что можно в этот метод добавить логику и в тестах это работать будет, а "на бою" -- нет, так как при сборке карт это всё заполняется напрямую в FeatureBuilderParams (в ParseNameAndType), поэтому более безопасно везде заполнять напрямую в параметрах.
=> [indexer][generator] Remove FeatureBuilderParams::GetStreet(), FeatureBuilder::AddHouseNumber, FeatureBuilder::AddStreet, FeatureBuilder::AddPostcode.

track_analyzing/track_analyzer/CMakeLists.txt, track_analyzing/track_analyzer/balance_csv_impl.cpp, track_analyzing/track_analyzer/balance_csv_impl.hpp, track_analyzing/track_analyzer/cmd_match.cpp, track_analyzing/track_analyzer/cmd_table.cpp, track_analyzing/track_analyzer/utils.cpp, track_analyzing/track_analyzer/utils.hpp, track_analyzing/track_analyzing_tests/CMakeLists.txt, track_analyzing/track_analyzing_tests/balance_tests.cpp, track_analyzing/track_analyzing_tests/statistics_tests.cpp
Распределение треков до и после мачинга сильно различается. Данный PR реализует необходимую функциональность, чтоб уменьшив кол-во смачиних треков сохранить распределение, как до мачинга. Т.е. все изменения для реализации метода:
```c++
void BalanceDataPoints(std::basic_istream<char> & distributionCsvStream,
std::basic_istream<char> & tableCsvStream, uint32_t ignoreDataPointsNumber,
std::vector<TableRow> & balancedTable);
```
Далее его параметр `balancedTable` будет сохранен в csv и использован вместо csv, которая подается в `tableCsvStream`.
Основные изменения в коммитах "Track balancer implementation." и "Tests on track balancer.". Рекомендую смотреть, начиная с метода BalanceDataPoints(...). И далее в глубину.
=> Track balancer implementation.

generator/generator_tests/mini_roundabout_tests.cpp, generator/mini_roundabout_transformer.cpp
Баг: дороги не соединяются с мини-раундэбаутами.
Причина: в некоторых случаях точка не добавлялась в мини-раундэабут, если в нем находилась _почти_ такая же. 
А routing_index_generator соединяет фичи, если точки сопадают:
`PointToInt64Obsolete(f.GetPoint(i), kPointCoordBits);`
Соответственно совпадения для дороги в мини-раундэбауте не находилось, и они не соединялись.
PR это исправляет, дороги прокладываются.
=> [generator] Fixed mini-roundabouts to roads matching.

indexer/ftypes_matcher.cpp
Значения выбраны консервативно, т.к. наиболее важные объекты лучше замаплены и с большей вероятностью имеют заполенный population.
Согласно https://wiki.openstreetmap.org/wiki/Tag:place%3Dcity
`
As of mid 2019, 63% of place=city have a population=* tag, of which the median value is 130,000, and 95% of place=city have a population=* value over 20,000. However, 13% have a population=* value between 20,000 and 50,000.
`
поэтому 50 000 кажется нормальным консервативным выбором.
Для state выбор тоже консервативный. Для стран -- сейчас в osm есть только 3 страны без population: Монако, Джибути и Шри-Ланка. Население очень разное, но страна -- в любом случае значимый объект, кажется неправильным что мы деревням ранг поднимаем, а странам -- нет.
=> [indexer][search] Set default population for Country and State to avoid zero rank.

shaders/shaders_tests/gl_shaders_mobile_compile_test.cpp
На билд сервере иногда не хватает дефолтного тайм-аута в 30000мс.
=> [shaders] GLSL compiler timeout increased.

track_analyzing/track_analyzer/cmd_table.cpp
В ф-ции, которая разбивает трек на составляющие была ошибка. Все перекрестки, которые попадали на точки разбиения трека учитывались дважды. Т.е. если трек разбивался на n частей (n-1) точкой, которая всегда перекресток, то эти (n-1) точка присутствовали дважды. В конце и в начале каждой части.
В строчке 461 данные о таком перекрестке добавлялись в конец части трека (мержились в инфо)
А в строчке 465, в начало.
=> [track_analyzer] Preventing taking into account crossroads at end of DataPoints twice.

track_analyzing/track_analyzer/balance_csv_impl.cpp, track_analyzing/track_analyzer/balance_csv_impl.hpp, track_analyzing/track_analyzer/utils.cpp, track_analyzing/track_analyzer/utils.hpp, track_analyzing/track_analyzing_tests/balance_tests.cpp, track_analyzing/track_analyzing_tests/statistics_tests.cpp
Кол-во точек в треках за 2 месяца превышает 2G. При обработке больших объемов треков всплыла ошибка связанная с тем, что uint32_t стало не хватать. Данный PR заменяет uint32_t на unit64_t. И добавляет тесты на это изменение.
=> track_analyzer] Moving to uint64_t DataPoints number.

routing/cross_mwm_connector.hpp, routing/cross_mwm_graph.cpp, routing/cross_mwm_graph.hpp, routing/cross_mwm_index_graph.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/leaps_graph.cpp, routing/leaps_graph.hpp
На самом деле это результаты двух оптимизаций - хранение стартовой и финишной точки как ms::LatLon, а не m2::PointD + bidirectional LeapsOnly
в этом PR будет пока только второе, первую оптимизацию я выкачу после того, как этот PR помержат
Результаты сравнения прошлой версии с новой на выборке из 100к маршрутов, где были оставлены только маршруты, которые строятся в режиме LeapsOnly (таких оказалось ~18k)
Для всех маршрутов был выбран timeout = 60s.
**Average time: 6.93344s -> 5.62323s (-18.85%)**
Тут ничего интересного, кроме того, что хуже не стало. Часть маршрутов перестала be Cancelled (== timeout), также кол-во маршрутов "RouteNotFound" уменьшилось. Почему - я не стал разбираться, но видимо из-за того же из-за чего ETA не совпадают иногда (об этом ниже)
Как видно, время построения …
=> [routing] Bidirectional LeapsOnly mode

partners_api/mopub_ads.cpp, partners_api/partners_api_tests/ads_engine_tests.cpp, partners_api/rb_ads.cpp
После того как были задеприкейчены неиспользуемые типы
```
sponsored|banner|lamoda_ru;1140;
sponsored|banner|lamoda_ua;1141;
sponsored|banner|deliveryclub;1142;
sponsored|banner|tutu;1143;
sponsored|banner|geerbest_uk;1144;
sponsored|banner|rentalcars;1145;
sponsored|banner|viator;1146;
sponsored|banner|geerbest_de;1147;
sponsored|banner|geerbest_fr;1148;
sponsored|banner|raileurope;1149;
```
сломались тесты partners_api.
Причина такая: хоть типы действительно не использовались, в рантайме мог существовать тип sponsored-banner (такого типа нет, но если есть тип a-b-c-d, то в классификаторе в рантайме существуют и a и a-b и a-b-c). Этот тип использовался в partners_api.
=> [partners_api] Remove not existing type from partners_api.

map/routing_manager.cpp, routing/routing_session.cpp
После переезда RouterDelegate на новый base::Cancellable (https://github.com/mapsme/omim/pull/11978) в 2 местах в качестве отсутствия timeout-та остался 0. А должен был появиться RouterDelegate::kNoTimeout.
Одна из этих ошибок приводила к прекращению перепрокладки маршрута после ухода с него (https://jira.mail.ru/browse/MAPSME-12826). А другая, к прекращению перепрокладки после загрузки пробок (https://jira.mail.ru/browse/MAPSME-12827). Этот PR так же исправляет баг: (https://jira.mail.ru/browse/MAPSME-12739)
Это происходило, поскольку после вызовова `RouterDelegate::SetTimeout(0 /* timeoutSec */)`, `Cancellable::m_status` принимал значение `Status::DeadlineExceeded`. Что в свою очередь приводило к тому, что метод `Cancellable::IsCancelled()` вызываемый в `FindPathBidirectional(...)` …
=> [routing] Route rebuilding fix.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java, android/src/com/mapswithme/maps/intent/BackUrlMapTaskWrapper.java, android/src/com/mapswithme/maps/intent/Factory.java, android/src/com/mapswithme/maps/scheduling/ConnectivityJobScheduler.java, android/src/com/mapswithme/util/Utils.java, map/mwm_url.cpp
Added support for correct handling of back url parameter in a deeplink. It allows to come back to an external app which MAPSME is called from. Technically, coming back means that 'KeyEvent.KEYCODE_ESCAPE' is encountered. 
For example, going to this link https://dlink.maps.me/route?sll=55.800800,37.532754&saddr=PointA&dll=55.760158,37.618756&daddr=PointB&type=vehicle&back_url=wunderlinq://bla-bla-bla our app stores the back url in memory. And if the user taps on the hardware escape button then MAPSE will fire intent with back url data to lead the user back to the external app.
@kconger please take a look at this PR and if you have any questions let me know. I've implemented  only Android part as you see. To make the same for IOS please communicate with @beloal . Also If your requirements …
=> [android] Back url support for deeplink

data/mapcss-mapping.csv
В правилах для типа amenity|parking требуется чтобы ещё был указан access, но сейчас правила игнорируются и amenity|parking получается из фичей amenity=parking независимо от наличия access.
Предлагаю сохранить текущее поведение, тем более access есть только у 22% amenity=parking:
https://taginfo.openstreetmap.org/tags/amenity=parking#combinations
для этого убираю access из селектора. после этого правило можно записать в сокращенном виде.
на автогенеренные файлы это изменение не влияет
=> [mapcss] Fix amenity parking backward compatibility.

.clang-format
Предлагается настроить сортировку include через clang-format. Он по регулярным выражениям и приоритетам, сам умеет собирать в группы и расставлять их в правильном порядке. Приоритеты выставлял согласно текущим зависимостям (чем **больше** приоритет, тем **ниже** include). Все регулярные выражения в файле идут в порядке от меньшего приоритета, к большему.
Каждое регулярное выражение описывает тест/библиотеку/бинарь. При данной схеме
```cpp
#include "some_library.hpp"
#include "some_library/base/some_base.hpp"
```
превратится (потому что `some_library/base` не является библиотекой/тестом/бинарем) в: 
```cpp
#include "some_library.hpp"
#include "some_library/base/some_base.hpp"
```
Чтобы их разделить, нужно отдельно указать регулярное выражение для `some_library/base` и указать приоритет …
=> [omim] Regexp for includes order

routing/routing_quality/routing_quality_tool/benchmark_results.hpp, routing/routing_quality/routing_quality_tool/benchmark_stat.cpp, routing/routing_quality/routing_quality_tool/utils.cpp, routing/routing_quality/routing_quality_tool/utils.hpp
Добавление очередной картинки в routing_quality_tool
Код разбивает маршруты по группам (сейчас 10 групп) по времени построения маршрута. Соседний столбец характеризует насколько уменьшилось/увеличилось время построения маршрутов в этой группе.
Получается такая картинка:
=> [routing] Refactor routing quality tool smart boost

generator/generator_integration_tests/features_tests.cpp
Cейчас `generator_integration_tests --filter=BuildCountries ` запускает три теста: BuildCountries, BuildCountriesWithComplex и BuildCountriesOneThread. Это не всегда удобно, иногда хочется запустить только 1 самый быстрый тест.
=> [generator][tests] Rename tests to allow single test selection with --filter.

data/mapcss-mapping.csv
По формату короткую запись можно использовать для типов, которые превращаются в теги методом замены `|` на `=` и все наши парсилки на это расчитывают. Для типов длины 1 используется длинная запись.
https://github.com/mapsme/kothic/blob/master/src/libkomwm.py#L141
=> [mapcss] Fix mapcss-mapping for complex entry.

data/mapcss-mapping.csv
Предлагаю задеприкейтить, потому что
- для типов нет стилей, они не используются
- для них неправильно написаны селекторы и не вижу смысла их исправлять (нужно и power_source и generator:type и generator:source и plant:source для каждого)
- нет предпосылок к тому что у нас появятся разные типы для разных типов электростанций, сейчас нет и для общего типа power-generator, но его предлагаю пока не трогать -- там и селектор правильный и больше шансов что поддержим.
=> [mapcss] Deprecate power-generator-*

generator/feature_processing_layers.cpp, generator/generator_integration_tests/features_tests.cpp
Сейчас при добавлении фичи в качестве Area для неё проверяется `feature::IsDrawableLike(params.m_types, feature::GeomType::Area);`, что означает что фича либо имеет тип который "всегда отображается" такой как wifi и complex_entry либо действительно отображается как area.
При добавлении как Line и Point проверяется HasUsefulType, который также приводит к добавлению фичи если у неё есть типы cuisine, wheelchair и т.п.
По плану мы не должны добавлять в карту такие типы, если нет "полезных", то есть не должно существовать объектов с типами только cuisine, wheelchair и т.п. без отображаемых типов.
После исправления меняются generator integration tests, т.к. из карт исчезают эти лишние линии и точки с типами только cuisine, wheelchair и т.п.
дифф с фичами которые исчезли: …
=> [generator] Fix CanBeLine and CanBePoint rules for feature emission.

generator/generator_integration_tests/features_tests.cpp, generator/road_access_generator.cpp
Сейчас если у фичи есть тег ford и есть тег access, то результирующий access зависит от того в каком они порядке: какой первый тег в осм элементе, тот и "победил".
Например: https://www.openstreetmap.org/way/226176257#map=19/-43.20916/171.71059
Меняю предпочтения: если есть дорожный тип, который мы запрещаем, то не важно какой access.
diff road_access.csv в интеграционных тестах генератора:
```diff
> Car No 381672999 0
> Bicycle No 381672999 0
> Pedestrian No 381672999 0
< Car Private 381672999 0
< Bicycle Private 381672999 0
< Pedestrian Private 381672999 0
> Car No 551873851 0
> Bicycle No 551873851 0
> Pedestrian No 551873851 0
< Car Private 551873851 0
< Bicycle Private 551873851 0
< Pedestrian Private 551873851 0
> Bicycle No 193660923 0
> Bicycle No 218327604 0
> Bicycle No …
```
=> [generator] Block fords before access tags parsing.

generator/osm2type.cpp
Корни беды https://jira.mail.ru/browse/MAPSME-11862.
Вот пример:
https://www.openstreetmap.org/relation/62422#map=11/52.5070/13.4243
Сегодня говрили с Лешей и решили что это лучший вариант.
Так же это изменение должно улучшить определение границ городов для роутинга и для геокодера поиска.
=> [generator] Fixed some values of places in Germany.

generator/generator_tests/road_access_test.cpp, generator/road_access_generator.cpp, generator/road_access_generator.hpp
Идея была в том, чтобы игнорировать `barrier=*` на подмножестве `highway=*`, при условии, что у `barrier=*` нет `access tag`.
Почему-то в коде не проверялось - какой дороге принадлежит точка, из-за этого код по сути не работал
=> [generator] Ignore barriers on some highways

generator/generator_integration_tests/features_tests.cpp, generator/road_access_generator.cpp
Tests were broken after ignoring barriers on some highways
I see two types of disappearing accesses:
1) Because of  "ignoring barriers on some highways"
2) Because there are lots of ways with tag barrier=gate or something else, for example this: https://www.openstreetmap.org/way/97663995
The 2) is good for us, because such ways anyway break road graph and we will just store less info about way-accesses
Also there was a bug. If elem has "foot=yes" and "access=no", we will skip "yes" tag and apply only "no", so now we prefer "yes" tags if they exist
=> [generator] Fix generator integration tests

generator/affiliation.cpp, generator/affiliation.hpp, generator/borders.cpp, generator/borders.hpp, generator/final_processor_intermediate_mwm.cpp
Пофикшена проблема с оптимизацией бордерсов при сборке карт с флагом haveBordersForWholeWorld .
Раньше рект бордерса, который был представлен несколькими полигонами, складывался для всех полигонов. Из-за этого получалось что ректы некоторых стран имели большую площадь и перекрывали ректы других стран. -> Чаще возникали конфликты: для одной фичи возвращалось несколько стран, когда должна была вернуться одна.
=> [generator] Fixed optimization with countries borders.

routing/routing_callbacks.hpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/routing_session_test.cpp
Данный PR решает 2 проблемы.
1. Застарелый баг: при использовании Maps.Me иногда ломалась навигация на маршрут. И вплоть до перестроения маршрута не работала. При этом маршрут был отрисован на карте. Причина проблемы была в том, что случай, когда при перестроении маршрута прокладка давала ошибку не был обработан. Это не очень частый случай, но вполне возможный.
https://jira.mail.ru/browse/MAPSME-12924
2. В момент перепрокладки маршрута терялось притягивание к старому (и отрисованному на карте маршруту) и ориентирование на него.
https://jira.mail.ru/browse/MAPSME-12925
Данный PR решает эти 2 проблемы.
Теперь (1) старый маршрут удаляется, только если есть валидный новый и (2) состояния `SessionState::RouteNeedRebuild` и `SessionState::RouteRebuilding` позволяют ориентироваться на старый …
=> [release-96][routing] Continue navigating along a previous route in case of route rebuilding error.

map/routing_manager.hpp, routing/routing_callbacks.hpp, routing/routing_session.cpp, routing/routing_session.hpp
Удалил лишний `SessionState:: RouteBuildingError` и не используемые методы `RoutingSession::IsNotReady()` и `RoutingManager::IsRouteNotReady()`
=> [routing] Removing SessionState::RouteBuildingError state and IsRouteNotReady() methods.

generator/road_access_generator.cpp, routing/routing_quality/routing_quality_tests/barriers_tests.cpp
[MAPSME-12984](https://jira.mail.ru/browse/MAPSME-12984)
PR, аналогичный #12473 на master. Cherry-pick не работает из-за расхождений в road_access_generator.cpp:
git cherry-pick 71ca7f0dc4e67fde64712e58a8b8306f306ab40f
определяет изменения только в тестах routing_quality_tests/barriers_tests.cpp, а road_access_generator.cpp не затрагивает.
=> [RELEASE ONLY] Build routes through fords.

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/maps/Framework.hpp, android/jni/com/mapswithme/maps/LocationHelper.cpp, android/jni/com/mapswithme/maps/MapFragment.cpp, android/src/com/mapswithme/maps/MapFragment.java, android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/location/CompassData.java, android/src/com/mapswithme/maps/location/LocationHelper.java, android/src/com/mapswithme/maps/location/LocationListener.java, android/src/com/mapswithme/maps/location/SensorHelper.java, android/src/com/mapswithme/maps/widget/placepage/BottomSheetPlacePageController.java, android/src/com/mapswithme/maps/widget/placepage/DirectionFragment.java
1. В связи с переездом на сенсор TYPE_ROTATION_VECTOR теперь не нужно во все методы прокидывать trueNorth и magneticNorth, по которым прикидывается просто "north". Он у нас есть и так. Его и передаем вместо этих двух.
2. Мы не использовали accuracy для компаса. Можно удалить.
3. Удален не использовавшийся метод UpdateCompassSensor в Framework.cpp.
=> [Android] Refactoring of north direction handling.

map/routing_manager.cpp, map/routing_manager.hpp, routing/routing_integration_tests/CMakeLists.txt, routing/routing_integration_tests/archival_reporter_tests.cpp, tracking/archival_manager.cpp, tracking/archival_manager.hpp, tracking/archival_reporter.cpp, tracking/archival_reporter.hpp
Интеграционные тесты archival reporter.
**Почему они в роутинге, а не в tracking?** Потому что в routing_integration_tests находятся routing_test_tools, которые собираются в исполняемый файл, а не либу. Правильнее добавить интеграционный тест в роутинг, чем отдельно собирать routing_test_tools в либу и линковать из tracking.
**Откуда много новых зависимостей в CMakeLists?** Они нужны для framework, который используется для получения ссылки на адекватно настроенный routing manager, который в свою очередь запускает archival reporter.
=> [Routing] Archival reporter integration test.

routing/routing_integration_tests/speed_camera_notifications_tests.cpp, routing/speed_camera_manager.cpp
как происходил креш:
ехать по дороге: `m_voiceSignalCounter = 0, m_makeVoiceSignal = false`
1) попасть в зону нотификации голосом 
2) превысить скорость (`m_makeVoiceSignal = true`)
3) произнести уведомление (`m_voiceSignalCounter = 1`, `m_makeVoiceSignal = false`)
4) продолжать превышать  (`m_makeVoiceSignal = true`)
5) несмотря на `m_makeVoiceSignal` мы не произенесем еще одно уведомление, так как m_voiceSignalCounter > 1
6) попасть в зону Beed Signal
7) превышать (`m_makeBeepSignal = true`) => **CRASH**
проблема в том, что если счетчик сигналов какого-то типа больше 1, то уведомление мы не делаем, но и флаг не сбрасываем, из-за этого может упасть в ASSERT
добавил интеграционный тест, который крэшится на мастере (воспроизводит эту проблему выше)
=> [routing] Drop speed cameras notifications flags, fix crash in ASSERT

map/routing_manager.cpp, routing/base/followed_polyline.cpp, routing/base/followed_polyline.hpp, routing/route.cpp, routing/route.hpp, routing/routing_integration_tests/street_names_test.cpp, routing/routing_session.cpp, routing/routing_tests/route_tests.cpp
PR исправляет следующую вещь:
1) когда мы матчимся на фейковый сегмент, то мы продолжаем не привызывать стрелку графически, но при этом расстояние при движении вдоль фейкового сегмента - уменьшается
2) если ты сильно отошли от фейкового сегмента, то маршрут будет перестраиваться
=> [routing] Fix matching to fake segments

generator/generator_integration_tests/features_tests.cpp
#12473
[MAPSME-12984](https://jira.mail.ru/browse/MAPSME-12984)
Был убран Access::No для бродов, и этот PR - починка тестов генератора.
=> [Generator tests] Fixed tests after fords removal.

track_analyzing/log_parser.cpp
При обработке очень большого числа DataPoints в одном случае пакет с бинарными данными о точке оказался поврежден. А именно метод `coding::TrafficGPSEncoder::DeserializeDataPoints(...)` получил пакет размером 244 байта. Первые 112 байт представляли реальные данные. А остальные мусор. Далее происходило присвоение отрицательного значения uint64_t (в DeserializeDataPointsV1()). Далее в цикле `while (src.Size() > 0)` (в DeserializeDataPointsV1()) происходило переполнение.
Причиной появления поврежденного пакета могли быть:
- hardware ошибка при сохранении;
- software ошибка при сохранении;
- коллизия чек суммы в в TCP/IP;
Данный PR делает обработку данного случая. Использован MemReaderWithExceptions, который запускает исключение в случае присвоение uint64_t отрицательного значения.
Я …
=> [track analyzing] Fixing case when a package with DataPoints is corrupted.

generator/generator_integration_tests/features_tests.cpp
для landuse-forest в отличие от natural-wood есть иконки и стили для точек
```diff
> m2::Point<d>(174.64792984970654288, -42.189270129603585247) m2::Rect(174.64792984970654288, -42.189270129603585247, 174.64792984970654288, -42.189270129603585247) ReversedGeometry: false; Metadata []; AddressData [Street = ""; Postcode = ""]; Types: landuse-forest; Name:default:Hutiwai Forest  [1: Osm Node 1683892712 ]
> m2::Point<d>(174.65787983933267924, -42.370124778123681608) m2::Rect(174.65787983933267924, -42.370124778123681608, 174.65787983933267924, -42.370124778123681608) ReversedGeometry: false; Metadata []; AddressData [Street = ""; Postcode = ""]; Types: landuse-forest; Name:default:Makino Forest  [1: Osm Node 1683892842 ]
> m2::Point<d>(174.71213992192610931, -42.450516952621313749) …
```
=> [generator_integration_tests] Fix generator intagration tests.

track_analyzing/track_analyzer/CMakeLists.txt, track_analyzing/track_analyzer/cmd_balance_csv.cpp, track_analyzing/track_analyzer/cmd_balance_csv.hpp, track_analyzing/track_analyzer/cmd_match.cpp, track_analyzing/track_analyzer/cmd_table.cpp, track_analyzing/track_analyzer/track_analyzer.cpp, track_analyzing/track_analyzer/utils.cpp, track_analyzing/track_analyzer/utils.hpp, track_analyzing/track_analyzing_tests/CMakeLists.txt, track_analyzing/track_analyzing_tests/balance_tests.cpp
Добавлены команды и параметры для балансировки треков в track analyzer.
Появилась команда: balance_csv  для балансировки треков
Добавлены параметры: input_distribution, ignore_datapoints_number.
Пример использования track_analyzer для балансировки:
`./track_analyzer -cmd=balance_csv -in=./train.csv -input_distribution=./distribution.csv -ignore_datapoints_number=100 > ./balanced_train.csv`
=> [track_analyzing] Adding balance_csv and some other commands to track analyzer.

routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/transit_route_test.cpp, routing/routing_tests/CMakeLists.txt, routing/routing_tests/edge_estimator_tests.cpp
[MAPSME-12329](https://jira.mail.ru/browse/MAPSME-12329)
[MAPSME-11406](https://jira.mail.ru/browse/MAPSME-11406)
PR решает несколько задач:
- Мы одинаково пессимизируем время на маршруте и для расчета веса ребра в A*, и для расчета ETA, который показываем пользователю. **Решение:** теперь для этих двух целей используются разные формулы.
- Мы завышаем ETA для пеших и вело-маршрутов (баг репорты, тикеты, наблюдения на знакомых маршрутах, сравнение ETA с роутингом конкурентов, сравнение с ETA треков от партнера). **Решение:** на данных поставщика хайкинг и вело-треков обучена модель, и в формуле оценки ETA по углу наклона используются ее коэффициенты. 
- Для пеших маршрутов мы выбираем слишком крутые маршруты, даже если доступны более пологие, но немного более длинные. **Решение:** для …
=> [Routing] Tune pedestrian and bicycle "climb" penalty.

routing/base/followed_polyline.cpp
https://jira.mail.ru/browse/MAPSME-13075
Очень старый крэш в режиме ведения по маршруту.
Крэш возникает в редком случае: при движении по маршруту с промежуточной точкой, до которой достроены фейковые сегменты, срабаывавает чек:
`CHECK_LESS_OR_EQUAL(startIdx, endIdx, ());`
Чек срабатывает внутри метода:
```
Iter FollowedPolyline::GetClosestMatchingProjectionInInterval(m2::RectD const & posRect,
size_t startIdx, size_t endIdx) const
```
То есть `endIdx` оказывается меньше, чем `startIdx`.
**Причина** - отсутствие в вызывающем коде проверки значения hoppingBorderIdx перед вызовом
`GetClosestMatchingProjectionInInterval(posRect, hoppingBorderIdx, m_nextCheckpointIndex);`
Как видно из истории git, такое положение дел было уже очень давно, просто ситуация с попаданием именно в эту ветку кода - …
=> [Routing] Fix for followed_polyline.

drape_frontend/drape_engine.cpp, drape_frontend/drape_engine.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/frontend_renderer.hpp, drape_frontend/message_subclasses.hpp, drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp, map/framework.cpp, routing/routing_settings.cpp, routing/routing_settings.hpp
https://jira.mail.ru/browse/MAPSME-12781
When the user enters the navigation mode for pedestrians, the location arrow is "glued" to the route. It does not point to the real direction. It is very disorienting. For pedestrians we need to untie the direction of the arrow from the route.
This PR:
- Passes new flag from `Framework` to `MyPositionController` - `isArrowGluedInRouting`. It is set to `true` for car, bicycle and transit modes and is set to `false` for pedestrian mode.
- Activates GNSS bearing only if compass is not available on device. It prevents random arrow movements when angle values are switched between compass and GNSS. So the GNSS angle value becomes the reserve option: the precise direction can not be obtained from the GNSS device sensors. [Android …
=> [Routing] Do not match bearing to the route (pedestrian mode)

android/jni/com/mapswithme/maps/editor/Editor.cpp, android/res/layout/fragment_editor.xml, android/src/com/mapswithme/maps/bookmarks/data/MapObject.java, android/src/com/mapswithme/maps/editor/Editor.java, android/src/com/mapswithme/maps/editor/EditorFragment.java, indexer/map_object.hpp
Мотивация состоит в том, чтобы отвязать блок details в редакторе от метадаты, т.к. часть этих полей будет выноситься из метадаты и способ хранения данных в mwm не должен влиять на то где именно в редакторе отображается поле.
задача для перевода в тестирование:
https://jira.mail.ru/browse/MAPSME-13097
=> [android] Use GetEditableProperties instead of GetEditableFields for editor details block.

tools/python/mwm/__main__.py, tools/python/mwm/dump_mwm.py
После улучшений dump_mwm им стало тяжело пользоваться для получения списка секций -- раньше он сразу печатал список секций и дальше тупил на вызове `mwm.iter_features()` (который если что можно было и прибить), теперь -- сразу тупит на `mwm.iter_features()` и списка секций надо ждать минуту.
В этом реквесте отдельный режим для списка секций без `mwm.iter_features()`.
Было:
```
time python3.7 -m mwm dump_mwm --path ~/data/191124/US_California_LA.mwm --format=meta
Tags:
version : offs         8 len       10
header  : offs        24 len       32
rgninfo : offs        56 len        4
dat     : offs        64 len 52636046
geom0   : offs  52636112 len    11814
trg0    : offs  52647928 len    22882
geom1   : offs  52670816 len   136091
trg1    : offs  52806912 len   164977
geom2   : offs …
```
=> [python] Add tags mode for dump_mwm

generator/osm2meta.cpp
Предлагаю не добавлять ele (высота над уровнем моря) в метадату для noname зданий, тем более у нас в следующем релизе будут изолинии.
Тег ele полезен для гор, населенных пунктов и может ещё в каких-то специфических случаях, поэтому пока вместо white list предлагаю black list -- при формировании white list можно что-то упустить.
После этого изменения количество метадаты для US_California_LA уменьшается с 48 до 32 Мб (суммартно meta и metaidx).
Другие "жирные" секции:
```
ele                     2.143.834
height                  2.100.079
turn:lanes                 26.018
turn:lanes:backward        16.870
turn:lanes:forward         16.892
```
height полезна для рендеринга, поэтому её удалить нельзя, предположительно в дальнейшем стоит вынести её из metadata в отдельную секцию.
Также …
=> [generator] Filter metadata.

drape_frontend/my_position_controller.cpp
https://jira.mail.ru/browse/MAPSME-13111
https://jira.mail.ru/browse/MAPSME-13110
После мержа #12344 появились 2 **проблемы:**
1) Если начать ведение по вело/авто маршруту на нулевой скорости, то пока скорость не возрастет, стрелка направления **не будет матчиться** на маршрут, а будет показывать изначальный угол девайса до перехода в режим ведения.
2) На одной из моделей самсунга при запуске приложения вместо стрелки местоположения отображается точка.
**Причина:** в PR #12344 реализована логика поворота стрелки либо на основании данных компаса, либо GPS. Иначе ее колбасит между значениями от двух разных сенсоров. При этом не скорректировано условие отрисовывать направление по GNSS, даже если скорость околонулевая.
**Решение:** изменить условие отрисовки поворота стрелки в методе …
=> [Drape-frontend] Handle arrow direction in routing at low speed.

tools/python/post_generation/inject_promo_ids.py
Парсить питоном метадату долго. Если она не нужна, её можно не парсить.
=> [python][post_generation] Do not parse metadata for inject_promo_ids.

track_analyzing/track_analyzer/cmd_table.cpp, track_analyzing/track_analyzer/crossroad_checker.cpp, track_analyzing/track_analyzer/crossroad_checker.hpp
Цель данного PR улучшить разбиение по трекам, чтоб уменьшить среднюю ошибку.
Ключевое изменение, это изменение в IsCrossroadChecker::operator(). Мы стали по другому считать перекрестки и определять их типы.
1. При переходе трека с сегмента на сегмент может быть не более одного перекрестка. Это отражает измененная сигнатура `IsCrossroadChecker::operator()`. Теперь возвращается только одно значение, а не массив.
2. Ранее перекрестки типов: FromLink, ToLink, IntersectionWithSmall, IntersectionWithLink считались, но не учитываются при расчете ETA, то теперь многие из них учитываются и попадают в одну категорий, которые остались. Например, FromLink это обычно выезд на б_о_льшую дорогу. Соответственно теперь относится к категории TurnFromSmallerToBigger.
Почему это изменение делает лучше? Ниже …
=> [track analyzing] Improving tabling. 

routing/routing_quality/routing_quality_tests/barriers_tests.cpp
Как и планировалось, после генерации новых mwm routing quality тесты, связанные с ford, начали проходить. Кроме одного теста: в нем кроме наличия ford у дороги был тип highway=track, по которому запрещен проезд в соответствующем регионе. 
Тест заменен.
=> [Routing] Update for ford test.

map/routing_manager.cpp, map/routing_manager.hpp, routing/async_router.cpp, routing/async_router.hpp, routing/index_router.cpp, routing/index_router.hpp, routing/route.cpp, routing/route.hpp, routing/router.hpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/async_router_test.cpp, routing/routing_tests/routing_session_test.cpp
[MAPSME-13093](https://jira.mail.ru/browse/MAPSME-13093)
**Cars only.** When the route is built, the user's location is projected on the route if it fits in the corridor of 50 meters.
For cases when **the user's location does not fall into the corridor,** it should be projected to the nearest road of the road graph that corresponds to current vehicle type.
Example of location and bearing matching to the road graph:
=> [Routing] Match location to the road graph when it is not matched to the route.

iphone/Maps/Maps.xcodeproj/project.pbxproj, xcode/coding/coding.xcodeproj/project.pbxproj, xcode/generator_tool/generator_tool.xcodeproj/project.pbxproj, xcode/map/map.xcodeproj/project.pbxproj, xcode/mapshot/mapshot.xcodeproj/project.pbxproj, xcode/minizip/minizip.xcodeproj/project.pbxproj, xcode/minizip/minizip_framework/Info.plist, xcode/platform/platform.xcodeproj/project.pbxproj, xcode/qtMapsMe/qtMapsMe.xcodeproj/project.pbxproj, xcode/routing/routing.xcodeproj/project.pbxproj, xcode/search/search.xcodeproj/project.pbxproj, xcode/storage/storage.xcodeproj/project.pbxproj
It crashed minizip lib was missing. Looks like xcode cant link to custom dylibs, so I changed framework type from .dylib to .framework
https://jira.mail.ru/browse/MAPSME-13161
=> [cherry-pick][iOS] fix a bug in which the app crashes on the device at startup.

coding/coding_tests/url_tests.cpp, coding/url.cpp, coding/url.hpp, map/map_tests/mwm_url_tests.cpp, map/mwm_url.cpp, map/mwm_url.hpp
The bool value in the old version served two purposes
at once: it was used both to control the execution flow
and to indicate the parsing result. As such, the return
value of true meant "the needed key was found and the
callback returned true when executed with the corresponding value"
and the return value of false meant "either the needed key
was not found or the callback returned false even though the
key was present". This is too loaded semantically and is
a false optimization (since the parsed url params need to be stored
in a vector of pairs by the time of this call, early exit won't help much).
=> [coding] [map] Refactored url's ForEachParam.

routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/transit_route_test.cpp, routing/routing_integration_tests/turn_test.cpp
1) HungaryBudapest_AvoidMotorway - минорные изменения
2) SwedenStockholmSlussenHiltonToAfChapmanHostel - минорные изменения
3) BelarusMinksBarURatushiToMoscowBusStation - минорные изменения
4) CrossMwmRussiaPStaiToBelarusDrazdy - снова ведем через броды
5) MoscowKashirskoeShosseCrossing - поставили barrier=block , из-за этого маршрут изменился https://www.openstreetmap.org/node/292788123
6) GermanyBerlinMunichTimeTest - изменился ETA маршрута, при этом длина - не изменилась
7) Transit_London_DeptfordBridgeToCyprus -  минорные изменения
8) RussiaMoscowLeningradskiyPrptToTheCenterUTurnTest - интересный кейс, тут фича разделилась на две: 
из-за этого рисуется новый маневр, надо подумать - баг это или нет, но в любом случае не критичный, я выбрал другие старт и финиш, чтобы маневр был тот же …
=> [routing] Fix RIT on release-96

track_analyzing/track_analyzer/cmd_table.cpp, track_analyzing/track_analyzer/utils.cpp
Тестирование PR https://github.com/mapsme/omim/pull/12574 выявило в нем серьезные ошибки. Данные ошибки произошли в процессе упрощения кода после изменений. Т.о. результаты описанные в описании https://github.com/mapsme/omim/pull/12574 в силе.
Ошибки следующие.
SpeedInfo::GetSummary() заполняет записи в csv для каждого значения в `enum class IsCrossroadChecker::Type` начиная с 1го, а не нулевого. Т.к. начинались значения с `IsCrossroadChecker::Type::None`.
Во-первых, учитывая изменения в `IsCrossroadChecker::Type`(https://github.com/mapsme/omim/pull/12574/files#diff-87fdcfaa7d7525bb928d09027a24055b) нужно записывать, начиная с 0.
Во-вторых, учитывая изменения в том же файле, необходимо изменить и список колонок в csv.
На базе данного PR я запустил тесты. Тесты прошли успешно. …
=> [track analyzer] Tabling. Column number and column order fix.

tools/python/post_generation/localads_mwm_to_csv.py
При создании маппинга feature id to osm id для local ads для каждой mwm в мапинг добавляется FAKE_FEATURE_ID. 
В исходном пулл реквесте сказано что это делается для тестов: https://github.com/mapsme/omim/pull/6549
Соответвтвующие тесты могли бы быть в репозитории https://bitbucket.mail.ru/projects/MS/repos/localads_mapping/browse
но там нет теста, который получает osm id по FAKE_FEATURE_ID. Также по номеру FAKE_FEATURE_ID (100111000) ничего не находится ни в omim ни в других репозиториях сервер-сайда.
Если никто не знает что это за тесты для которых нужен этот код и никаких следов этих тестов не удалось найти, предлагаю удалить.
=> [python][post_generation] Remove fake feature added for unknown tests.

routing/opening_hours_serdes.cpp, routing/opening_hours_serdes.hpp
Текущий сериалайзер в случае фейла, оставляет writer в неконсистентном состоянии. Добавил ф-ию IsSerializable, которая сериализует в память и возвращает результат.
Почему я не сериализую вначале в память: потому что чтобы скопировать потом результат, придется делать Flush() на bitWriter, чего делать нельзя (образуются пустоты из нулей).  Ничего умнее сериализации дважды не придумал
=> [routing] add IsSerializable method

routing/index_graph.cpp, routing/index_graph.hpp
Передавали параметр `Parents<Segment> const & parents` по ссылке, а не по константой ссылке. Поправил.
=> [routing] Parents const correctness fixing.

routing/CMakeLists.txt, routing/road_access_serialization.cpp, routing/road_access_serialization.hpp, routing/routing_tests/road_access_test.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
access:conditional я хочу хранить в той же секции, что и текущие access, сразу после них.
Хочу, чтобы код выглядел как-то так:
```cpp
void Serialize(...)
{
WriteHeader();
SerializeAccess(...);  // old version
SerializeAccessConditional(...);
}
void Deserialize(...)
{
auto version = ReadHeader(...);
DeserializeAccess(...);  // old version
if (version == 2)
DeserializeAccessConditional(...);
}
```
для этого порефакторил код так, чтобы сейчас было:
```cpp
void Serialize(...)
{
WriteHeader();
SerializeAccess(...);  // old version
}
void Deserialize(...)
{
auto version = ReadHeader(...);
DeserializeAccess(...);  // old version
}
```
=> [routing] refactor access serialization

generator/generator_integration_tests/features_tests.cpp
сейчас на машинах с большим количеством процессоров (16+) тест может фейлиться с ошибками ввода-вывода из-за невозможности открыть файл.
=> [generator_integration_tests] Increase max number of open files for features test.

generator/generator_integration_tests/features_tests.cpp
Сейчас при запуске generator_integration_tests если в тестах countries что-то пофейлилось, то мы падаем на 1-й ошибке и остальные не видим -- это не удобно надо или несколько раз править и перезапускать или менять TEST на LOG.
В реквесте функция сначала пишет все фейлы, а потом только падает на TEST. 
Пример вывода:
```
Final processing is finished.
Unexpectad result for kNorthAucklandCounters actual: CountryFeaturesCount(fbs = 1812099, geometryPoints = 12196602, point = 1007482, line = 205502, area = 599115, poi = 212466, cityTownOrVillage = 521, bookingHotels = 3557) expected: CountryFeaturesCount(fbs = 1811974, geometryPoints = 12194844, point = 1007482, line = 205377, area = 599115, poi = 212341, cityTownOrVillage = 521, bookingHotels = 3557) the difference is: …
```
=> [generator_integration_tests] Print all changed counters before fail on TEST macros.

generator/generator_integration_tests/features_tests.cpp, generator/generator_tests/mini_roundabout_tests.cpp, generator/mini_roundabout_transformer.cpp, generator/mini_roundabout_transformer.hpp
[MAPSME-13048](https://jira.mail.ru/browse/MAPSME-13048)
Fix for wrong generation of roundabouts from mini-roundabouts.
Example of wrong generation of roundabout above the road:
After fix:
Example of road with 2 mini_roundabouts:
https://www.openstreetmap.org/node/1250535302
=> [generator] Handle mini-roundabouts in the middle of the road.

tools/python/maps_generator/diff_stats.py, tools/python/maps_generator/generator/statistics.py
Небольшая утилита для вывода разницы по статистике.(генерится файл после каждой генерации)
Такая статистика регулярно требуется для маркетинговых пресс-релизов. 
Запускать так
```sh
python -m maps_generator.diff_stats --old=/path/to/old/build/stats/stats.json --new=/path/to/new/build/stats/stats.json
```
=> [python][generator] Added diff_stats.py.

docs/INSTALL.md
Fix #12649 by updating the documentation to mention an additional dependency needed to build the `generator_tool`
=> Mention the requirement for libsqlite3-dev

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties
Updated NDK version to 21 via build.gradle. Build will failed if the specified NDK is not found. Now it's the last stable version - 21. 
Important note: ndk.dir in local.properties must be point on ndk of same version as build.gradle ndk version or deleted from local.properties.
=> Mapsme 13288 update ndk via buildgradle

routing/routing_session.cpp
Данный PR исправляет следующую ситуацию.
1. Программа загрузилась;
2. Маршрут прокладывается и в процессе прокладки маршрута загрузились пробки;
В этом случае, в процессе прокладки (SessionState::RouteBuilding) вызывается RoutingSession::RebuildRouteOnTrafficUpdate(), который в свою очередь отменяет прокладку маршрута (m_router->ClearState();). Вызывается callback `delegateProxy->OnRemoveRoute(RouterResultCode::Cancelled)`, который не меняется state (SessionState::RouteBuilding). 
Затем из RoutingSession::RebuildRouteOnTrafficUpdate() вызывается   `RebuildRoute(...., SessionState::RouteRebuilding, ...);`, который меняет state на SessionState::RouteRebuilding.
Далее мы крешимся, если в процессе этой перепрокладки после загрузки пробок вызывается OnLocationPositionChanged() мы падали на …
=> [routing] Crashfix in case traffic jam has been downloaded while the first route building.

search/search_integration_tests/smoke_test.cpp
highway ford добавили в стили, 
amenity driving_school судя по этому тесту и по другим теперь считается отображаемым (стилей я не вижу, но drules вижу; судя по всему, у нас где-то есть стиль для amenity=*)
остальное удалили из категорий когда была чистка типов, которые в categories лежали чисто ради переводов
=> [search_integration_tests] Remove some CategoriesTest exceptions.

coding/internal/file_data.cpp, map/bookmark_catalog.cpp, map/bookmark_helpers.cpp, map/bookmark_helpers.hpp, map/bookmark_manager.cpp, map/bookmark_manager.hpp
При сохранении kmb файлов возможны сбои, при которых на диск записывается битая версия файла, что приводит к падениям при последующем чтении на старте. PR заменяет метод сохранения на более безопасную версию через временный файл.
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/5cd8f4c1f8b88c2963c537f3
=> [bookmarks] Use safe version of saving kml and kmb files.

generator/generator_integration_tests/features_tests.cpp
Починка интеграционных тестов генератора после добавления landuse-residential.
Посмотрела разницу по фичам: кроме них ничего не добавилось.
Также вижу что вчера сломался тест CheckGeneratedData* : 
https://client.jenkins.mapsme.devmail.ru/jenkins/job/GeneratorIntegration/232/testReport/junit/(root)/generator_integration_tests/features_tests_cpp_FeatureIntegrationTests_CheckGeneratedDataMultithread/
почему он сломался пока не поняла.
=> [generator_integration_tests] Fix test: add landuse-residential counts.

routing/CMakeLists.txt, routing/car_directions.cpp, routing/car_directions.hpp, routing/index_router.cpp, routing/routing_benchmarks/bicycle_routing_tests.cpp, routing/routing_benchmarks/car_routing_tests.cpp, routing/turns.hpp, xcode/routing/routing.xcodeproj/project.pbxproj
BicycleDirectionsEngine уже много лет является генератором маневров для машин. Переименовал.
=> [routing] Renaming BicycleDirectionsEngine to CarDirectionsEngine.

configure.sh
После обновления carmodel на мастер (https://github.com/mapsme/omim/pull/11686, https://github.com/mapsme/omim-private/pull/125) private-repo потерял совместимость с release-96.
Чтоб продолжилась сборка из  omim-private без дополнительных действий я завел ветку release-96 в omim-private и направил на нее configure.sh.
Альтернативой является не редактировать conigure.sh в release-96, а указывать ветку в omim-private при его запуске.
Что скажите?
@ALL CPP PTAL
=> [RELEASE ONLY] Using release-96 branch in private repo for release-96.

coding/move_to_front.hpp
I am try to build generator_tool with GCC 10 (coming soon with Fedora 32) and has error:
```
In file included from /home/vascom/mapsme/omim/coding/move_to_front.cpp:1:
/home/vascom/mapsme/omim/coding/move_to_front.hpp:12:10: ошибка: «size_t» не является именем типа
12 |   static size_t constexpr kNumBytes = static_cast<size_t>(std::numeric_limits<uint8_t>::max()) + 1;
|          ^~~~~~
/home/vascom/mapsme/omim/coding/move_to_front.hpp:6:1: замечание: «size_t» is defined in header «<cstddef>»; did you forget to «#include <cstddef>»?
5 | #include <limits>
+++ |+#include <cstddef>
6 |
```
With this fix generator_tool built successfully.
=> Fix build with GCC 10

tracking/archival_manager.cpp
Для единообразия добавлен префикс X-Mapsme для хедеров TrackInfo, Aloha.
=> [tracking] Renamed headers for ArchivalReporter.

search/geocoder.cpp, search/geocoder.hpp
OrderCountries сильно усложнилась с момента своего появления (появились mwm с my_position и с городами, соотвествующими запросу). Информации о количестве mwm в первой порции выдачи уже не хватает чтобы с этим всем корректно работать.
Мне реквест нужен чтобы дальше фильтровать какие улицы рассматривать в CreateStreetsLayerAndMatchLowerLayers, но думаю что он полезен независимо от этого:
- если OrderCountries дальше будет усложняться лучше понимать как mwm попадают в первую порцию выдачи (и возможно как-то сортировать их внутри первой порции кроме расстояния от вьюпорта)
- уже сейчас реквест исправляет вызов
https://github.com/mapsme/omim/blob/e03990ef9cf39e4af859e6162e5698f32760655b/search/geocoder.cpp#L566
судя по коду функции нужно передавать в качестве aroundPivot true только для …
=> [search] Keep type of mwm from first batch (ViewportIntersect/UserPosition/MatchedCity).

generator/osm_element_helpers.cpp
На сборке приключилась ошибка: в переменной number была записано большое число, строка не смогла привестись к числу
=> [generator] CHECK->LOG for GetPopulation().

search/geocoder.cpp, search/geocoder.hpp, search/mwm_context.cpp, search/mwm_context.hpp, search/processor.cpp, search/search_integration_tests/processor_test.cpp, search/search_params.hpp, search/search_tests_support/helpers.cpp, search/search_tests_support/test_search_request.cpp, search/search_tests_support/test_search_request.hpp
Фильтрация улиц по расстоянию от ключевой точки: локации пользователя, центра вьюпорта либо центра города из запроса.
По результатам просмотра размеченной выборки витальных результатов меньше не стало, зато стало меньше мусора + MatchPoiAndBuildings довольно дорогой вызов, их стало меньше, а значит стало больше времени для других разборов.
=> [search] Filter street predictions

coding/coding_tests/var_record_reader_test.cpp, coding/var_record_reader.hpp, indexer/feature.cpp, indexer/feature.hpp, indexer/features_vector.cpp, indexer/features_vector.hpp, indexer/indexer_tests/CMakeLists.txt, indexer/indexer_tests/read_features_test.cpp, indexer/indexer_tests/read_features_tests.cpp, xcode/indexer/indexer.xcodeproj/project.pbxproj
Сейчас у нас в FeaturesVector переиспользуется один и тот же буфер для всех фичей. Поэтому такой код как в добавленном тесте ReadFeatures_Smoke приводит к крешам.
Видимо это сделано из соображений производительности -- чтобы было меньше аллокаций и освобождений памяти. Но, как показывают тесты, хранение в каждой фиче её буфера в некоторых случаях работает быстрее, в некоторых -- не сильно хуже. (предполагаю что это происходит потому что сейчас всегда читается минимум 256 байт, хотя на самом деле многие фичи значительно меньше).
Недостатком текущего дизайна также является то, что сложно отслеживать и не допускать использование FeatureType таким образом как это показано в тесте ReadFeatures_Smoke.
Сейчас у нас есть места где чтение фичей происходит "неразрешенным" способом, например в …
=> [indexer] Do not reuse FeaturesVector buffer for different features. Store buffer inside FeatureType.

data/taxi_places/freenow.json
https://jira.mail.ru/browse/MAPSME-13265
=> [taxi] zurich is removed from freenow.

routing/guides_connections.cpp, routing/guides_connections.hpp, routing/index_router.cpp
https://jira.mail.ru/browse/MAPSME-13261
Фикс крэша и логики связывания при невозможности связать одну из точек трека к ОСМу.
Ошибка заключалась в добавлении через IndexGraphStarter "пустых" FakeEnding, соединяющих точки трека и ОСМ граф.
=> [routing] Guides fix.

generator/search_index_builder.cpp, indexer/road_shields_parser.cpp, search/ranker.cpp, search/search_integration_tests/processor_test.cpp
В некоторых случаях мы дополняем FeatureParams ref информацией о дорожной сети из relation.
В generator/osm2type.cpp мы просто заполняем ref как есть, а в generator/relation_tags.cpp можем дополнить его.
Так, например, для фичи https://www.openstreetmap.org/way/343180292 с ref `М-11` мы берём из relation https://www.openstreetmap.org/relation/1168820, в который она входит, `network=ru:national` и итоговое значение FeatureParams ref для этой фичи получается `M-11;ru:national/M-11`.
Очевидно в поиске не нужно индексировать служебную информацию. У нас уже есть парсер который эту информацию парсит.
=> [search] Fix road shields indexing.

generator/affiliation.cpp, generator/borders.hpp
Пояснение фикса:
Баг был когда страна представлялась несколькими многоугольниками + когда точка попадала в пересечение их bbox' ов.
Т.е метод GetAffiliations мог возвращать страны, которые могли дублироваться. 
Это приводило к ряду неприятных последтсвий: от дублирования фичей в мвмке до неправильного подсчета кросс мвмных переходов.
https://github.com/mapsme/omim/pull/12389
=> [generator] Fixed affiliations.

generator/camera_info_collector.cpp, routing/road_access.cpp
Данный PR содержит 2 исправления, которые позволят не задерживать сборку карты:
1. Данное исправление может позволить собрать быстро секцию cross_mwm. Однако это ни финальный фиск. Поскольку пока не ясно, почему вообще при сборке crossmwm-ой секции вызывается RoadAccess::m_currentTimeGetter::operator().
2. В редких ситуациях сохраненная speedcam не находится в точке сочленения сегментов фичи, хотя судя по коду, должна. 
Это случается в:
US_Minnesota_Minneapolis
UK_England_East of England_Essex
Russia_Kabardino-Balkaria
Italy_Piemont_Torino
UK_England_South East_Oxford
Italy_Trentino-Alto Adige Sudtirol
New Zealand North_Auckland
UK_England_East Midlands
Uzbekistan
UK_England_South East_Brighton
В данном PR такие камеры выкидываются, а лог записывается информация о тех камерах, что …
=> [RELEASE ONLY] Fastfix GetCurrentTimestamp(). For crossmwm section fast build.

indexer/feature_utils.cpp, indexer/feature_utils.hpp, indexer/map_object.cpp, map/booking_availability_filter.cpp, map/discovery/discovery_search.cpp, map/framework.cpp, map/map_tests/booking_filter_test.cpp, search/hotels_classifier.cpp, search/intermediate_result.cpp, search/intermediate_result.hpp, search/ranker.cpp, search/result.cpp, search/result.hpp, search/search_tests/results_tests.cpp
При переводе отображения типа кухни  с метадаты на типы сломала отображение в subtitle в поисковом результате.
9.6:
master:
В этом реквесте чиню. С реквестом:
Также считаю нужно переименовать Result::Metadata, т.к. cuisine теперь не metadata и планирую туда положить road shields, которые тоже не metadata. Думаю что cuisine и road shields должны быть в этой структуре, а не отдельными полями и отдельными параметрами конструктора.
=> [search] Fill cuisines for search result.

search/geocoder.cpp
Сейчас мы вызываем для mwm с MatchedCities MatchAroundPivot (т.к. они в первой порции выдачи, для них NumSentResults нулевой). Это приводит к тому что токен названия города, который должен был "израсходоваться" на название города используется для матчинга имён пои. Например при локейшене и вьюпорте в москве получаем такие результаты:
Матчить токен "минск" на poi из mwm  с минском не надо.
На остальные случаи этот фикс не влияет, т.к. для mwm не из первой порции выдачи 
`m_preRanker.NumSentResults() ==0 ` и `m_preRanker().Size() == 0` эквивалентны, а остальные типы mwm из первой выдачи (вьюпорт и локация пользователя) перечислены явно.
На размеченной выборке кол-во витальных не уменьшилось, при этом стало меньше мусора.
После фикса поиск с тем же вьюпортом и gps в Москве:
=> [search] Avoid double pois search for mwm with matched cities.

android/jni/com/mapswithme/maps/SearchEngine.cpp, android/src/com/mapswithme/maps/search/SearchAdapter.java, android/src/com/mapswithme/maps/search/SearchResult.java, generator/search_index_builder.cpp, indexer/feature_utils.cpp, indexer/feature_utils.hpp, indexer/map_object.cpp, indexer/map_object.hpp, indexer/road_shields_parser.cpp, indexer/road_shields_parser.hpp, iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm, map/place_page_info.cpp, search/intermediate_result.cpp, search/ranker.cpp, search/result.hpp
Добавляю отображение номера дороги в place page и в поисковые результаты.
Согласовано с @kgalushka .
Мы умеем искать по идентификаторам дорог, но при этом не подписываем их ни в выдаче ни в плейспейдже, выглядит странно:
не понятна связь между результатом "нева" и запросом "М-11"
В этом реквесте сделано так:
ios:
=> [search][map][ios][android] Show road shields in place page and search results description.

search/search_integration_tests/ranker_test.cpp
в реквесте https://github.com/mapsme/omim/pull/12858 сломала тест
изначально тест сломался т.к. mwm wounderland не пересекала вьюпорт. Но вообще он в целом был не очень корректен: чтобы протестировать ранжирование лучше помещать фичи в одну mwm, иначе на порядок выдачи кроме ранкера существенно влияет порядок вызова PreRanker::UpdateResults из геокодера.
=> [search][tests] Fix RankerTest_PreferCountry.

generator/pygen/CMakeLists.txt
иначе на макоси вот так:
```
[100%] Linking CXX shared module ../../pygen.so
Undefined symbols for architecture x86_64:
"_PyArg_ParseTupleAndKeywords", referenced from:
boost::python::property_init(_object*, _object*, _object*) in libboost_python37.a(class.o)
"_PyBaseObject_Type", referenced from:
boost::python::objects::class_type() in libboost_python37.a(class.o)
boost::python::objects::class_base::class_base(char const*, unsigned long, boost::python::type_info const*, char const*) in libboost_python37.a(class.o)
"_PyBool_FromLong", referenced from:
boost::python::objects::class_base::enable_pickling_(bool) in libboost_python37.a(class.o)
"_PyBool_Type", referenced from:
boost::python::converter::(anonymous namespace)::bool_rvalue_from_python::get_pytype() in …
```
=> [pygen] Fix pygen build under OS X.

data/mapcss-mapping.csv, data/replaced_tags.txt, generator/generator_tests/osm_type_test.cpp, generator/osm2type.cpp
В osm начали мапить несколько типов одновременно в ключе `aerodrome:type`
https://taginfo.openstreetmap.org/keys/aerodrome:type#values
`international;public` 56 штук
в статье не написано что так можно https://wiki.openstreetmap.org/wiki/Key:aerodrome:type?uselang=en-GB
но думаю надо это поддерживать.
=> [generator] Parse multiple aerodrome types. 

routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp
Поправил 2 из 3 routing integration tests. Отавшийся тест - отдельная тема. Похоже мы не прокладывали и не прокладываем маршруты через bicycle=designated, но должны. Буду разбираться отдельно. Это не кажется новой проблемой поскольку дорогу, на которой воспроизводится ошибка, отредактировали месяц назад.
Остальные два - просто изменения в картах. 
CzechPragueHiltonToKvetniceViewpoint
GermanyShuttleTrainTest
=> [routing] Fixing routing integration tests for 200402.

routing/road_access.cpp, routing/road_access_serialization.hpp, routing/routing_tests/road_access_test.cpp
Отключил access:conditional (в runtime и при сборке карты) за счет выключения десериализации.
=> [routing] Switching on access:conditional by preventing deserialization.

routing/routing_integration_tests/bicycle_route_test.cpp
Тест CrossMwmKaliningradRegionToLiepaja на меж mwm-й велосипедный routing. Однако карта была отредактирована месяц назад и на велосипедном пути (https://www.openstreetmap.org/way/615386881) был поставлен barrier=gate (https://www.openstreetmap.org/node/7257314716). Это привело к тому, что маршрут стал строиться в объезд, через Калининград. Я перенес старт, чтоб попрежнему тестировался меж mwm-й велосипедный роутинг.
=> [routing] Fixing the last routing integration test for maps 200402.

search/geocoder.cpp, search/search_integration_tests/processor_test.cpp
Пока отсечка очень консервативная.
=> [search] Do not emit results with low matched fraction.

search/search_integration_tests/ranker_test.cpp, search/search_tests/ranking_tests.cpp
Тест был не стабильным: граница mwm совпадала с границей вьюпорта и пересекает ли mwm вьюпорт зависело от погрешностей.
Чтобы MatchAroundPivot запускался и находил POI (при условии что уже есть найденный результат) нужно чтобы mwm пересекала вьюпорт
=> [search][tests] Fix unstable test: mwm should intersect viewport for MatchAroundPivot.

search/geocoder.cpp, search/pre_ranker.hpp, search/search_integration_tests/processor_test.cpp
ошибалась вчера тут https://github.com/mapsme/omim/pull/12858
когда утверждала что 
> для mwm не из первой порции выдачи
`m_preRanker.NumSentResults() ==0` и `m_preRanker().Size() == 0` эквивалентны
если все результаты relaxed это неверно. Поправила + добавила тест.
=> [search] Continue MatchAroundPivot untill result with all tokens used found.

routing/speed_camera_manager.cpp, routing/speed_camera_manager.hpp
https://jira.mail.ru/browse/MAPSME-13676
Фикс падения
`routing/speed_camera_manager.cpp:365 SendNotificationStat()  CHECK(m_makeBeepSignal != m_makeVoiceSignal) In each moment of time only one flag should be up.`
Следует за #12445.
=> [routing] Fix for speed camera crash.

iphone/Maps/Maps.xcodeproj/project.pbxproj, iphone/Maps/UI/Authorization/AuthorizationViewController.swift, iphone/Maps/UI/Authorization/KeychainStorage.swift, iphone/Maps/UI/Authorization/User+AppleId.swift
Sign in with Apple returns requested user data at first login only.
If we were unable to process login to maps.me, we'll use saved data for subsequent login attempts.
=> [iOS] keep Sign in with Apple data in keychain

generator/camera_info_collector.cpp, generator/camera_info_collector.hpp, generator/metalines_builder.cpp, generator/restriction_collector.cpp, generator/restriction_collector.hpp, generator/road_access_generator.cpp, generator/routing_helpers.cpp, generator/routing_helpers.hpp, routing/routing_integration_tests/speed_camera_notifications_tests.cpp
После корректной поддержки highway=mini_roundabout и highway=turning_loop дорожные фичи стали разбиваться на несколько частей. Т.е. одному osm id теперь может соответствовать несколько дорожных фичь. Более того, возможно, что точка которая ранее принадлежала дорожной фиче, теперь не принадлежит ни какой дорожной фичи. Точки в которых находятся mini_roundabout и turning_loop теперь не принадлежат дорожной сети. Вокруг них круг.
Данный PR начинает серию PR-во по корректной обработке указанной выше ситуации. Он реализует 
1. базовую функциональность по прокидыванию вектора с feature ids для каждого osm id;
2. полностью обрабатывает случай с камерами скорости. Теперь, если камера скорости попадает на разбитую на части фичу, она будет корректно обрабатываться. Если ли же камера скорости …
=> [routing] Correct processing that a osm id of a road may correspond to several road feature ids for speed cameras case.

search/house_to_street_table.cpp
Я запускала у себя приложение в дебаге, в дебаге ридер довольно долго не умирает (хватает чтобы вычитать адреса).
В тестах тоже не успевал умереть.
В релизе умирал быстро, теперь всё ок -- сабридеры не убиваются при уничтожении ReaderPtr.
=> [search] Fix HouseToStreetTable reader lifetime.

search/locality_scorer.cpp, search/search_integration_tests/processor_test.cpp, search/search_tests/locality_scorer_test.cpp
Мы выбрасываем стоп-слова из запроса, поэтому должны выбрасывать и из имён, иначе наличие стоп-слов в имени уменьшает similarity. Например получалось что у запроса "san pedro de atacama" и фичи "san pedro de atacama" similarity меньше, чем у запроса "san pedro de atacama" и фичи "san pedro". Теперь она одинаковая и выбор идёт по рангу. 
Дальше в планах сделать так чтобы при запросе "san pedro de atacama" фича "san pedro de atacama" побеждала независимо от ранга.
=> [search] Fix LocalityScorer similarity calculation.

routing/features_road_graph.cpp
По крешу: https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/c33bd1776ddb3311feeb4b47acfe9f75/sessions/latest
- Внес изменение, которое может приводить к срабатыванию данного CHECK
Если передать в FeaturesRoadGraph::ExtractRoadInfo() `featureId`, у которой featureId.m_mwmId.IsAlive() возвращает false, то скорость будет равна 0 и чек сработает.
- Вывел больше информации в случае срабатывания CHECK
@mesozoic-drones @tatiana-yan PTAL
=> [routing] Fix crash in FeaturesRoadGraph::FindClosestEdges().

routing/fake_feature_ids.cpp, routing/fake_feature_ids.hpp
Мы хотим добавить в секцию transit данные из GTFS фидов. В качестве id берем FakeFeatureId из интервала IsTransitFeature(), а это всего 15 млн (15 728 640). Для хранения не только метро, но и GTFS, этого мало. PR увеличивает это значение до 260 млн (267 386 880). На OSM фичи при этом остается 4 009 754 624 айдишников, то есть фичи OSM не пострадают.
| Интервал  | До PR | После PR |
| ------------- | ------------- | ------------- |
| kIndexGraphStartedId  | 4 294 967 295  | 4 294 967 295  |
| kEditorCreatedFeaturesStart  | 4 293 918 720  | 4 293 918 720  |
| kTransitGraphFeaturesStart  | 4 278 190 080  | **4 026 531 840**  |
| kGuidesGraphFeaturesStart  | 4 261 412 865  | **4 009 754 625**  |
| OSM ids start | 0  | 0  |
=> [routing] Extended fake feature interval for transit.

map/map_tests/countries_names_tests.cpp
После исправления MAPSME-10611  и мержа новых данных в мастер неправильно собранные из осм страны пропали, можно удалить исключения из теста.
=> [data] Remove CountriesNamesTest exceptions after MAPSME-10611 fix.

generator/osm2meta.cpp
Функция раньше использовалась в validate and format cuisine, теперь в том месте где парсятся кухни то же самое делается лямбдой:
https://github.com/mapsme/omim/blob/87074d17b1f30d629ed30fa47b3ecd9ddd339385/generator/osm2type.cpp#L549
=> [generator] Remove unused function.

generator/generator_tests/road_access_test.cpp, routing/index_graph_loader.cpp, routing/road_access_serialization.hpp, routing/routing_tests/road_access_test.cpp
При тесте версии 10.0.2 случился креш у одного клиента:
https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/839fceb4c295a1831f6aefbb193ba68f/sessions/latest
Ставка на то, что одна из карт скаченных в 17 или 18 года повреждена или не совместимой версии. Тем не менее добавлены логи, чтоб в след раз, если такой креш появиться получить больше информации.
=> [routing] Adding logs in case wrong version (wrong header) of access conditional section.

routing/road_access_serialization.cpp, routing/road_access_serialization.hpp
Crash fix: https://fabric.io/mapsme/android/apps/com.mapswithme.maps.pro/issues/839fceb4c295a1831f6aefbb193ba68f?time=last-ninety-days
Теперь мы снова прокладываем маршруты по картам 170728 и более поздним.
@mesozoic-drones @tatiana-yan PTAL
=> [routing] Crash fix for reading zero version of section roadaccess.

routing/features_road_graph.cpp, routing/features_road_graph.hpp
Как в среднем выглядит верхушка стека креша:
`base::Cache<unsigned int, routing::IRoadGraph::RoadInfo>::Find
routing::FeaturesRoadGraph::GetCachedRoadInfo
DataSource::ForEachInRect
routing::FeaturesRoadGraph::FindClosestEdges
routing::IndexRouter::FindClosestProjectionToRoad
routing::RoutingSession::MatchLocationToRoadGraph`
[Креш в firebase](https://console.firebase.google.com/u/1/project/mapsmestats/crashlytics/app/android:com.mapswithme.maps.pro/issues/5409b42e33e4cd568a309f6343d0d0b6?time=last-seven-days&sessionId=5ea0181c037b00016a5f1e42c1dc2c9c_DNE_0_v2)
Ловим segmentation fault при обращении к не инициализированному кешу в методе `FeaturesRoadGraph::RoadInfoCache::Find`:
`return res.first->second.Find(featureId.m_index, found);`
**Причина:** race condition. Обращения к …
=> [routing] Fix for SIGSEGV crash in FeaturesRoadGraph::RoadInfoCache.

generator/feature_generator.hpp, generator/feature_sorter.cpp
Collect в FeaturesCollector никогда не возвращает kInvalidFeatureId. Если что-то пошло не так, то этого вызова просто не будет.
kInvalidFeatureId используется только в классе-наследнике.
=> [generator] Fix comment, move unused static kInvalidFeatureId to derived class.

generator/feature_sorter.cpp
Мы пишем оффсеты для секции features, резмер оффсетов должен помещаться в uint32, поэтому размер секции features не должен превышать 4Гб.
Проверка на это делалась именно в деструкторе FeaturesCollector2, а не FeaturesCollector (хотя только FeaturesCollector пишет m_dataFile), т.к. в FeaturesCollector нет таких ограничений на размер файла -- он пишет и FinalFeatures и MwmTmp, размер MwmTmp не ограничен 4 Гб.
Но в FeaturesCollector2 мы теперь проверяем размер секции features сразу после записи секции, вот тут:
https://github.com/mapsme/omim/blob/61dfcea7b61cf8ec0b1a10c24488ec05c47c2b39/generator/feature_sorter.cpp#L125
поэтому проверка в деструкторе больше не нужна.
=> [generator] Remove features size check. We already check it when we write features section.

qt/mainwindow.cpp
Фикс крэша на старте при обращении к `screenshotParams` при `m_screenshotMode` = `false`.  Причина крэша - #13026.
=> [qt] Fix for crash on start.

search/geocoder.cpp, search/search_integration_tests/processor_test.cpp
Предлагаю не поддерживать разбор `poi - building` без улицы.
Есть два вариант такого разбора: `poi - номер дома` и `poi - название дома`.
Про `poi - номер дома` вроде понятно что разбор странный и сложно придумать сценарий в котором это нужно.
Про `poi - название дома`  менее однозначно.
Например можно искать "МГУ столовая", "Пушкинский музей сувениры", "мэйл ру старбакс" и т.п. Но в данном случае разбор `poi - название дома` всё равно не будет применён, т.к. если у фичи кроме типа building есть ещё значимые типы (`amenity-*`, `tourism-*`, `office-*` и т.п.), то фича не будет считаться домом, а будет считаться poi (разбора `poi - poi` у нас сейчас нет, можно о нём подумать).
Я посмотрела в данных на фичи, которые будут считаться домом с именем (для этого нужно чтобы у них 1) был тип дома, …
=> [search] Forbid poi-building parse.

generator/collector_city_area.cpp, generator/generator_integration_tests/features_tests.cpp, generator/generator_tests_support/test_mwm_builder.cpp, generator/place_processor.cpp, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, search/categories_cache.cpp, search/categories_cache.hpp, search/geocoder.cpp, search/geocoder.hpp, search/processor.cpp, search/processor.hpp
Разделяю кеши для стран, регионов, городов.
Это нужно для того чтобы в дальнейшем при поиске городов учитывать заматченные страны/регионы и при происке регионов учитывать страны.
В FillLocalitiesTable преобразования не эквивалентные: раньше мы "доставали"  100 locality (всех подряд), а потом пытались из их числа выбрать 5 стран с GeomType::Point, 5 штатов с GeomType::Point и 5 городов с GeomType::Point. 
Теперь достаем по 10 стран-штатов-городов и выбираем среди них все у которых геометрия GeomType::Point.
И у того и у другого варианта свои плюсы и минусы (в старом например могло вообще не оказаться стран в кандидатах, а в новом кандидаты могут оказаться сплошными Area, для старого это тоже было проблемой, но меньшей).
Пока по assesment_tool вижу что изменений в кол-ве релевантных …
=> [search] Separate localities caches.

drape_frontend/my_position_controller.cpp, drape_frontend/my_position_controller.hpp
Этот реквест - фикс бага, на который начали жаловаться начиная с 10.3: если использовать мапсми за рулем, но без построенного маршрута и без режима ведения, то стрелку начинает трясти. Не в машине ни мы, ни QA баг не воспроизвели. В машине его отловил Володя. 
https://jira.mail.ru/browse/MAPSME-13797
**Причина бага** - в изменении правил переключения между двумя источниками угла стрелки: GPS и "компас" (на самом деле теперь это связка компас + гироскоп + акселерометр, что дает максимально плавный и точный угол).
**Как было раньше.** До достижения скорости 3.6 км/ч используется угол компаса. После пересечения этого порога - угол GPS. При снижении скорости происходит переключение обратно на компас. При этом если информация об угле от GPS не поступает более 5 секунд, начинает использоваться …
=> [drape_frontend] Switch between GPS and compass bearing.

routing/routing_quality/routing_quality_tool/error_type_counter.cpp, routing/routing_tests/turns_sound_test.cpp, routing/turns_notification_manager.cpp, routing/turns_notification_manager.hpp
Смотреть имеет смысл по комитам.
1. Поправил переинициализированную переменную;
2. Упростил код;
3. Определил неспецифицированную переменную;
=> [routing] Fixing unspecified cases and code refactoring

drape_frontend/gui/gui_text.cpp, drape_frontend/gui/gui_text.hpp
[Порядок](https://github.com/mapsme/omim/blob/0979af18e4494769fd635e9eec626b87c5dd3587/drape_frontend/gui/gui_text.cpp#L94-L103) `dp::BindingDecl` атрибутов в `dp::BindingInfo` должен совпадать с [порядком деклараций](https://github.com/mapsme/omim/blob/0979af18e4494769fd635e9eec626b87c5dd3587/shaders/GL/text_outlined_gui.vsh.glsl#L1-L5) в шейдере, т.к. во вулкановском графическом пайплайне порядок перечесления локаций [жёстко задан](https://github.com/mapsme/omim/blob/0979af18e4494769fd635e9eec626b87c5dd3587/drape/vulkan/vulkan_pipeline.cpp#L355) порядком следования биндингов буфферов аттрибутов вершин (всегда сначала static, затем dynamic, если есть) и номерами деклараций (аргументом `dp::BindingInfo::GetBindingDecl`).
@darina PTAL
https://jira.mail.ru/browse/MAPSME-13322
=> [vulkan] rearrange locations of attributes for outlined gui text MAPSME-13322

tools/python/transit/gtfs/download_gtfs.py
Тулза `download_gtfs.py` для скачивания GTFS фидов. Работает в 2 этапа: обходит сайты-агрегартоы фидов в поисках ссылок на фиды; обходит ссылки, скачивает архивы фидов и разархивирует их по директориям.
**2 источника - агрегатора фидов:**
- Transitland - около 854 не битых ссылок. https://transit.land/feed-registry/
- Openmobilitydata (бывший transitfeeds) - около 902 не битых ссылок на фиды. http://transitfeeds.com/feeds
**Параметры запуска:** 
--path - путь к директории для сохранения файлов. Здесь сохраняются списки урлов фидов, лог и директории, в которые разархивируются фиды.
--mode - режим запуска. От него зависит, какой запустится этап краулинга.
--source - источник - агрегатор фидов, с которого будем качать. Пока поддерживаются 2.
--omd_api_key - пользовательский ключ для API …
=> [tools][transit] Crawl GTFS feeds.

routing/routing_quality/routing_quality_tests/leaps_postprocessing_tests.cpp
Я решил удалить этот тест и вместо него поставить тикет:
https://jira.mail.ru/browse/MAPSME-13865. 
Кратко причины:
- этот тест попадает воспроизводит ошибку на особом случае, в котором я разобрался и эта ошибка не должна исправляться `LeapsPostProcessor`;
- на `LeapsPostProcessor` имеется еще 12 тестов, т.е. проверка достаточна;
Причины детально:
При меж mwm-ом роутинге иногда возникает ситуация, при которой старт и два выхода из mwm соединяется дугами одного веса и оба выхода находятся в одной точке. Например, если из Москвы нужно выехать по Шоссе Энтузиастов, то при меж mwm-ом роутинге, старт будет соединен с этим выходом двумя дугами одинакового веса. Вес одинаковый, поскольку эти дуги приходят в одну точку.
Т.е. вес дуги от сегмента старта (где бы он не находился в Москве) и до …
=> [routing] Removing RoutingQuality_NoLoop_MoscowToKazan because it gives two edges with the same weight.

iphone/Maps/LocalizedStrings/ar.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/cs.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/da.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/el.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/en-GB.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/en.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/es.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/fa.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/fi.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/fr.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/hu.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/id.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/it.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/ja.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/ko.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/nb.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/nl.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/pl.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/pt.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/ro.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/ru.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/sk.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/sv.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/th.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/tr.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/uk.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/vi.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/zh-Hans.lproj/Localizable.strings, iphone/Maps/LocalizedStrings/zh-Hant.lproj/Localizable.strings
У нас в strings.txt имеются фразы:
[routes_card_city],  [routes_card_outdoor] с переводом только на английский.
[routes_card_number_of_points], [routes_card_routes_tag], [routes_card_set_tag] с переводами на множество языков.
Если запустить: ./tools/unix/generate_localizations.sh видно, что для iOS для этих тагов ничего не сгенерировано. В данном PR я делаю это.
@beloal PTAL
=> [strings] Auto generated additional strings for iOS.

routing/opening_hours_serdes.cpp, routing/routing_tests/opening_hours_serdes_tests.cpp
В время сборки карты происходила сериализация opening hours для дорог. При этом инвариант был нарушен. Это и выявлял чек:
`CHECK(start <= end && end >= m_currentYear, (start, end, m_currentYear));` в 
методе `OpeningHoursSerDes::CheckYearRange(...)`. 
Он данные чек проверяет, что если и начало и конец ограничения были до даты сборки, то на более раннем этапе данные ограничения должны быть выкинуты.
Действительно, в начале метода  `OpeningHoursSerDes::SerializeImpl(...)` вызывается `DecomposeOh(...)`, в котором есть код, который отвечает за выкидывание таких ограничений. А в конце метода `OpeningHoursSerDes::SerializeImpl(...)` через цепочку вызовов, вызывается выше указанный чек.
Проблема была в том, что в коде ответственном за удаление старых ограничений в `DecomposeOh(...)` true и false …
=> [routing][map build fix] ShouldSkipYear(...) functions returns a wrong value.

android/src/com/mapswithme/util/LocationUtils.java
[MAPSME-13879](https://jira.mail.ru/browse/MAPSME-13879)
Старый  баг, существует ориентировочно с 2014 года (но так как стрелку трогала я, понятно, на кого пало подозрение =).
Заключается в резком повороте стрелки местоположения пользователя при "не-дефолтном" повороте экрана. Для большинства девайсов - это альбомная ориентация, но могут быть исключения (когда альбомная ориентация принята за дефолтную, а не портретная). 
**Воспроизводится** в том числе на 9.6 и ранее: нужно попробовать описать 360 градусов девайсом в альбомной ориентации по горизонтальной оси (условно положить на стол и покрутить). Будет видно, что стрелка срывается в не соответствующее действительности направление.
**Причина:** мы делаем поправку на поворот девайса (прибавляем pi/2, pi, 3p/2) только если угол поворота от …
=> [Android] Fix for arrow rotation in not-default screen orientation.

map/framework.cpp
[MAPSME-13851](https://jira.mail.ru/browse/MAPSME-13851)
В 10.0.3 пропала синяя стрелка направления движения, которая отображается в PP, если определилось местоположение. Стрелка появляется, если немного подвигать телефон.
**Причина бага:** метод `GetDistanceAndAzimut()` фреймворка рассчитывал азимут только если ему приходил не отрицательный угол от компаса. Нет азимута -> нет стрелки.
Но угол от компаса может быть отрицательным. Причина очень похожа на причину этого бага: #13121
Причем баг #13121 воспроизводится на более старых версиях приложения (что ожидаемо), а этот - только на новой. Возможно, на более ранних версиях приложения он не воспроизводился настолько регулярно, потому что показания от чистого магнитометра, которые мы использовали, дают большой разброс и даже в случае …
=> [map] Fix azimuth disappearance for PP.

.gitmodules
Cherry-pick: #13024
Зачем делать чери-пик добавления сабмодуля: на дженкинсе запускается git submodule update. Для сабмодулей, в которых что-то обновилось, она не подтягивает изменения. Сабмодуль just_gtfs, в котором периодически обновляется код, подтягивается устаревший, и сборка ломается. А с опцией --remote все нормально работает. 
Но @ToshUxanoff  не может ее полноценно добавить (только для этого сабмодуля), пока в release-100 отсутствует этот сабмодуль.
Описание опции --remote:
If you track branches in your submodules, you can update them via the --remote parameter of the git submodule update command. This pulls in new commits into the main repository and its submodules.
=> [3party] Cherry-pick: Added sumbodule just_gtfs for parsing GTFS feeds.

transit/CMakeLists.txt, transit/world_feed/CMakeLists.txt
По аналогии с генератором, benchmark_tool, routes_builder и другими тулзами, которые запускаются на сервер-сайд: world_feed не нужно собирать под платформы. Для этого добавлен` if (PLATFORM_DESKTOP)`.
=> [transit] Fix for android build error on master.

search/locality_finder.cpp
https://jira.mail.ru/browse/MAPSME-11091
Если два населенных пункта находятся на расстоянии меньше 550 метров от результата, то берём тот у которого больше population.
Раньше брали тот который первым попался.
Отдельно можно подумать чтобы для маленького distance учитывать его как-то иначе чем через GetPopulationByRadius
=> [search] Fix locality finder for two close localities.

search/geocoder.cpp, search/locality_scorer.cpp, search/locality_scorer.hpp, search/search_tests/locality_scorer_test.cpp
Реквест поверх https://github.com/mapsme/omim/pull/12982
Предлагается предпочитать localities из уже заматченых регионов.
На размеченной выборке нету отличий ни в количестве результатов ни в скорости работы.
По профайлеру вижу что в FillLocalitiesTable проводим на 20% больше времени, но это всё равно в районе 0.03% от времени поиска.
Теперь работают запросы типа Springfield Tennessee, San Francisco Columbia, San Antonio  Venezuela и т.п.
Правда, есть ещё такой не работающий юз-кейс:
Актуально в основном для штатов для нескольких названий городов которых в стране больше 10 штук (они там любители 88 городов назвать Washington).
Как вариант, можно различать сматчилось ли только state/country или оба. Либо пока забить.
=> [search] LocalityScorer: prefer localities from matched regions.

android/res/values-de/strings.xml, data/strings/strings.txt, iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings
Hello,
I noticed that the German version of maps.me has a typo if Taxi is not available for the chosen route. It says "Taxi ist hie nicht verfügbar." But is has to be "Taxi ist hier nicht verfügbar.". It really annoys me that is way I write you. Can you change it?
=> [strings] Fixed typo in DE

map/bookmark.cpp, map/bookmark.hpp, map/bookmark_manager.cpp
Признак интерактивности для трека - это наличие has_elevation_profile!="0" в kml.
https://jira.mail.ru/browse/MAPSME-13495
=> [elevation] Check has_elevation_profile is set to make track interactive

tools/unix/generate_vulkan_shaders.sh
Под линуксом скрипт фейлится, т.к. путь до бинарников отличается от маковского.
@darina @alexzatsepin
=> [vulkan] support linux NDK in generate_vulkan_shaders.sh

generator/place_processor.cpp, generator/place_processor.hpp
По GetLimitRect: она использовалась в 2 местах -- для квадродерева, там нужны все fb из FeaturePlace и в IsWorsePlace, где мы должны сравнивать только "лучшие" fb (т.к. потом берём только лучший). Поэтому функции надо разделить, иначе мы получали в IsWorsePlace точки ненулевой площади.
По тюнингу функции выбора place:
собрала у себя Онтарио, отсмотрела вручную все изменения в выборе фичей для place.
Всего изменения в 34 объектах в Онтарио.
Основная масса -- при прочих равных мы раньше предпочитали Relation (т.к. одним из факторов отбора была площадь, то если у нас есть relation сконверченный в точку и в нём node, то брался limit rect вокруг этих двух объектов и его площадь), теперь при прочих равных или даже если Node немного хуже (например меньше population) берём Node. На мой взгляд это …
=> [generator] PlaceProcessor: tune IsWorsePlace function, fix GetLimitRect behaviour.

generator/place_processor.cpp
У безымянных объектов имена совпадают, но взаимно вытеснять их не надо
=> [generator] PlaceProcessor: do not use PlaceProcessor for unnamed places.

transit/world_feed/CMakeLists.txt, transit/world_feed/gtfs_converter/gtfs_converter.cpp, transit/world_feed/world_feed.cpp, transit/world_feed/world_feed.hpp, transit/world_feed/world_feed_integration_tests/CMakeLists.txt, transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp
Разбиение json'ов общественного транспорта по регионам до этапа генератора. Теперь для каждой mwm в директории с названием mwm формируется свой набор файлов (networks.transit.json, routes.transit.json, stops.transit.json, etc). Получается иерархия:
```
~/jsons_for_generator
|______Argentina_Buenos Aires_North
...............|______networks.transit.json, routes.transit.json, ...
|______Belgium_Antwerp
...............|______networks.transit.json, routes.transit.json, ...
```
Правила отнесения сущности к mwm соответствуют правилам, действующим сейчас для метро, которые определены в `GraphData::ClipGraph(vector<m2::RegionD> const & borders)`.
=> [transit] Split feeds by borders polygons.

search/search_quality/aloha_to_samples_tool/CMakeLists.txt, search/search_quality/search_quality_tests/CMakeLists.txt, search/search_tests/CMakeLists.txt
на некоторых линуксах бинари не линкуются
ещё вроде бы можно было бы вписать ge0 в ./search/CMakeLists.txt рядом с openlocationcode и удалить из cmakelist для всех бинарей, но почему-то мы так не делаем с остальными библиотеками
=> [search] Add forgotten dependency.

generator/place_processor.cpp
решили отпилить от https://github.com/mapsme/omim/pull/13193 уменьшение kIsCapitalCoeff как самое безопасное изменение, чтобы оно вошло в 10.1, а над остальным ещё поработать.
=> [generator] PlaceProcessor: decrease kIsCapitalCoeff.

routing/routing_integration_tests/route_test.cpp, routing/routing_quality/routing_quality_tests/bigger_roads_tests.cpp, routing/routing_quality/routing_quality_tests/leaps_postprocessing_tests.cpp
**Routing integration tests**.
Поправил тест **MoscowToSVOAirport**. Он сломался, т.к. часть дорог на поле Шереметьево было удалено с карты в 200514. Фейковая дуга стала длиннее, а маршрут короче. Это видно из скринов ниже.
В остально маршрут не изменился.
**Routing quality tests.**
**RoutingQuality_RussiaMoscowTushino** из коментания к тесту следует: `// Secondary should be preferred against residential.`. Т.е. тест на то, что мы предпочитаем дороги secondary, даже, если задан maxspeed, как в этом случае. Если обратиться к кармодели, то видно, что в городе, для residential коэф 0.75, а для secondary 0.85 от maxspeed (==60). Т.е. для residential скорость рассматривается, как 0.75 * 60 км/ч == 45 км/ч, а для secondary 0.85 * 60 км/ч = 51 км/ч. В данном тесте мы проверяем, что маршрут …
=> [routing] Fixing rit and rqt for the map 200514.

drape/drape_tests/testing_graphics_context.hpp, drape/graphics_context.hpp, drape/metal/metal_base_context.hpp, drape/oglcontext.hpp, drape/vulkan/vulkan_base_context.cpp, drape/vulkan/vulkan_base_context.hpp, drape_frontend/frontend_renderer.cpp, drape_frontend/postprocess_renderer.cpp
При хаотичном быстром переключении слоёв крэш случается в драйвере вулкана при [этом](https://github.com/mapsme/omim/blob/e8a5c821e4b010b65ef3898e91b0203a3362c59f/drape/vulkan/vulkan_base_context.cpp#L462) вызове.
`VulkanBaseContext` хранит ресурсы, ассоциированные с фрэймбуфером, в `m_framebuffersData`, который имеет тип `std::map<ref_ptr<BaseFramebuffer>, FramebufferData>`. Фреймбуферы для разлиных нужд создаются в `drape_frontend/postprocess_renderer.cpp`. Например, [здесь](https://github.com/mapsme/omim/blob/e8a5c821e4b010b65ef3898e91b0203a3362c59f/drape_frontend/postprocess_renderer.cpp#L417-L436) создаётся три фреймбуфера для SMAA. Для разных слоёв антиалиасинг включается или выключается (для энергоэффективности). В общем случае объекты типа `dp::Framebuffer` пересоздаются …
=> [drape] [android] [vulkan] sporadic crash on layer switching

tools/python/maps_generator/generator/env.py
Фикс ошибки: на `Stage Mwm` generator_tool всегда запускается с проброшенным параметром `--transit_path_experimental`. Нужно, чтобы он запускался с этим параметром только если заполнен путь к  json'ам с общественным транспортом в конфиге: `TRANSIT_URL`.
=> [python][generator] Fix for transit_path_experimental.

routing/car_directions.cpp
Фикс креша: routing/car_directions.cpp:206 Generate()  CHECK(routeGeometry.size() == pathSize) 0 4478
=> [routing] Fix for crash in CarDirectionsEngine::Generate.

routing/car_directions.cpp
Cherry-pick for #13230 to master from release-100.
=> [routing] Cherry-pick. Fix for crash in CarDirectionsEngine::Generate.

tools/python/maps_generator/generator/gen_tool.py, tools/python/maps_generator/generator/steps.py
Прокидывание второго (и последнего) параметра в generator_tool для сборки экспериментальной транзитной секции. Он уже есть в generator_tool, PR добавляет его в питон.
=> [maps_generator] Pass parameter make_transit_cross_mwm_experimental.

iphone/Maps/UI/Editor/AdditionalNames/MWMEditorAdditionalNamesTableViewController.h, iphone/Maps/UI/Editor/AdditionalNames/MWMEditorAdditionalNamesTableViewController.mm, iphone/Maps/UI/Editor/MWMEditorViewController.mm
Что такое selectedLanguageCode не понятно, сейчас он всегда равен NSIntegerMax и условия типа `languageIndex == self.selectedLanguageCode`, `self.selectedLanguageCode == StringUtf8Multilang::kDefaultCode`, `self.selectedLanguageCode == StringUtf8Multilang::kInternationalCode` не могут выполняться.
=> [ios][editor] Remove conditions which can not be true.

iphone/Maps/UI/Editor/Cells/MWMEditorAdditionalNameTableViewCell.m
При добавлении метод был привязан к экшену в xib:
https://github.com/mapsme/omim/commit/c360e8fb91d2478f6bc6f8ad9265494b1553172e 
но в 2016 году его из xib удалили:
https://github.com/mapsme/omim/pull/4485
насколько я поняла, сначала была реализована более примитивная поддержка языков в редакторе, частью которой был этот метод, потом переписали на более "продвинутую" и в процессе был убран контрол к которому был привязан метод, а метод не удалили.
=> [ios] Remove unused method.

openlr/openlr_decoder.cpp, openlr/score_paths_connector.cpp, routing/road_graph.hpp
В нынешней реализации openlr мачинга, в A* сравниваются дуги (`Edge`). В дуге содержатся поля типа `PointWithAltitude`. Высота в этом типе берется иногда из `FeaturesRoadGraph` и тогда она корректная, а иногда задается равной 0, если точка получается в результате `DataSource::ForEachInRect(...)`.
Сначала мне показался наиболее чистым вариант, при котором везде используется правильная высота. Но он потребовал достаточно большого и не очень хорошего изменения в коде. Чтоб получить высоту на основании PointD, нужно искать эту точку в кэшах `FeaturesRoadGraph` или загружать еще раз секцию с высотами.
Я решил не делать этого, а вместо этого использовать функцию сравнения `AreEdgesEqualWithoutAltitude(...)`, которая не использует высоты. В действительности, она может даже не сравнивать точки …
=> [openlr] Comparing edges in A* without altitude.

openlr/score_candidate_points_getter.cpp
В качестве кандидатов для мачинга имеет смысл использовать только дороги. Иначе есть шанс потерять некоторых кандидатов, поскольку их кол-во ограничено (m_maxJunctionCandidates)
@mesozoic-drones
=> [openlr] Using only roads as candidates for matching.

search/search_quality/aloha_to_samples_tool/aloha_to_samples_tool.cpp
для одного языка обычно несколько локалей, поэтому удобно иметь возможность указать их все
=> [search_quality] aloha_to_samples_tool: support multiple locales.

shaders/CMakeLists.txt
`execute_command` выполняется при начальном парсинге `CMakeLists.txt` файлов и не реагирует на изменения фактических зависимостей. `add_custom_commands`, в свою очередь, позволяет указать как зависимости, так и продукты.
=> [drape] [cmake] Make generated sources dependent on shader and other sources

search/types_skipper.cpp
Исправление креша на Clang 11.0.3.
https://en.cppreference.com/w/cpp/language/range-for
Temporary range expression
If range_expression returns a temporary, its lifetime is extended until the end of the loop, as indicated by binding to the forwarding reference __range, but beware that the lifetime of any temporary within range_expression is not extended.
У нас массив инициалайзер листов, гарантируется что массив доживёт до конца времени работы цикла. Вряд ли под beware that the lifetime of any temporary within range_expression is not extended. имеется в виду что массив будет жить а элементы его умрут (это странно, по идее речь должна идти о более сложных конструкциях).
С компиляторами отличными от Clang 11.0.3 работало.
=> [search] Fix clang 11.0.3 crash.

openlr/helpers.cpp
В процессе разметки выяснилось, что появились дуги с FRC4, которые должны мачится на highway secondary в osm. Этот PR отражает это изменение.
@mesozoic-drones
=> [openlr] Using secondary roads for FRC4.

generator/generator_integration_tests/features_tests.cpp
При сохранении промежуточного файла CITIES_AREAS_TMP_FILENAME мы записываем туда фичи, в том числе name, поэтому после того как мы начали сохранять alt_name/old_name/name:da/name:no/name:id которые ранее не сохраняли размер файла поменялся.
Конкретно на тестовые данные повлиял alt_name.
Место где пишутся фичи включая имя:
```C++
void CityAreaCollector::CollectFeature(FeatureBuilder const & feature, OsmElement const &)
{
auto const & isCityTownOrVillage = ftypes::IsCityTownOrVillageChecker::Instance();
if (!(feature.IsArea() && isCityTownOrVillage(feature.GetTypes())))
return;
auto copy = feature;
if (copy.PreSerialize())
m_writer->Write(copy);
}
```
=> [generator_integration_tests] Fix CheckGeneratedData tests after adding alt_name to StringUtf8Multilang.

openlr/helpers.cpp, search/search_quality/aloha_to_samples_tool/aloha_to_samples_tool.cpp, search/types_skipper.cpp, shaders/CMakeLists.txt
так удобнее разбирать не кликнутые запросы из алохи, но т.к. на выходе много всего не склеено лучше по умолчанию оставить старый режим.
=> [search_quality] aloha_to_samples_tool: add mode to save all events from aloha as samples.

routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/speed_camera_notifications_tests.cpp
После обновления карты до 200607 сломалось 2 routing integration tests.
MoscowToSVOAirport
Изменились пути подъезда к аэропорту
SpeedCameraNotification_AutoAlwaysMode_8
Удалили камеру скорости. Я сделал тест с привязкой к другой камере.
Было:
Стало:
=> [routing] Fixing routing integration tests for map 200607.

transit/world_feed/color_picker.cpp, transit/world_feed/color_picker.hpp, transit/world_feed/world_feed_tests/world_feed_tests.cpp
Было замечено, что в классе ColorPicker для подбора цветов маршрутов из мапсмишной цветовой гаммы не обрабатывается случай цветов для текста, а не для фона. Такие цвета в своем названии содержат специальную подстроку.
Это поведение исправлено, на него добавлен юнит-тест.
Транзитные цвета подгружаются drape-frontend'ом из файла `data/transit_colors.txt`. Пример записи в этом файле:
```json
"purple_light": {
"clear": "CE93D8",
"night": "684A6D",
"text": "4A148C",
"text_night": "684A6D"
},
```
Для цвета `purple_light` мы должны использовать только `clear`-значение, а `text` - нет. Хотя drape-frontend  и добавляет его в контейнер clear.
=> [transit] Fix color-picking of 'text' color variations.

transit/experimental/transit_data.cpp, transit/experimental/transit_types_experimental.cpp, transit/experimental/transit_types_experimental.hpp, transit/transit_experimental_tests/parse_transit_from_json_tests.cpp, transit/transit_experimental_tests/transit_serdes_tests.cpp, transit/transit_tests/transit_tools.hpp
В процессе работы над новой версией транзита стало понятно, что поле "number" в объектах типа Line не нужно. Речь идет об экспериментальной ветке, текущей реализации работы с общественным транспортом (метро) никак не касается. 
В новой реализации у нас есть сущность route, и значение number из line метро может быть перемещено в title route. У метрошных  line есть 2 поля: number и title. title по смыслу относится к конкретной линии, а number - уже к маршруту целиком и может быть привязан к нескольким линиям. Поэтому по логике вещей это и есть title route.
=> [transit] Remove 'number' field from experimental transit line.

map/local_ads_manager.cpp
Ранее были удалены иконки неподдерживаемых партнеров в PR https://github.com/mapsme/omim/pull/9443, но остался код, который продолжает их назначать по адресу сайта из метадаты.
https://jira.mail.ru/browse/MAPSME-14240
=> [local ads] Don't use absent icons for unsupported partners.

generator/mini_roundabout_transformer.cpp
Мы добавляем искусственные линии-раундэбауты с центром в точках из ОСМ, помеченных как раундэбауты. Но к ним нужно приклеивать тег oneway по аналогии с обычными way-раундэабутами в generator/osm2type.cpp, line 668:
`{"junction", "roundabout", [&addOneway] { addOneway = true; }},`.
Реквест подготовлен в процессе выяснения причин бага https://jira.mail.ru/browse/MAPSME-13070.
=> [generator] Roundabouts should have one direction.

coding/string_utf8_multilang.cpp, coding/string_utf8_multilang.hpp, coding/transliteration.cpp, editor/xml_feature.cpp, editor/xml_feature.hpp, indexer/feature_utils.cpp, map/map_tests/transliteration_test.cpp
ja_kana это имя на слоговой азбуке. Но у японцев две слоговых азбуки (катакана и хирагана) и ja_kana это любая из них. У нас поддерживалась только транслитерация катакана.
Вижу несколько вариантов как это можно исправить:
- в coding/transliteration делать костыль для ja_kana
- поддержать несколько транслитераторов и применить один из них (выбрать тот после которого на выходе будет больше латиницы)
- поддержать несколько транслитераторов и последовательно применить все
мне показалось что последний вариант лучше, сделала его.
=> [coding] Support multiple transliterators for lang_code. Support hiragana-latin transliteration.

iphone/Maps/UI/Editor/AdditionalNames/MWMEditorAdditionalNamesTableViewController.mm
в структуре char* стал string, а в коде ios не поменяла
=> [ios] Fix ios build after StringUtf8Multilang::Lang changes.

generator/booking_quality_check/CMakeLists.txt, generator/osm2type.cpp, storage/CMakeLists.txt, storage/country_tree_helpers.cpp, storage/country_tree_helpers.hpp, storage/storage.cpp, storage/storage.hpp, storage/storage_tests/storage_tests.cpp, xcode/storage/storage.xcodeproj/project.pbxproj
В осме есть тег place=province (https://wiki.openstreetmap.org/wiki/Tag:place%3Dprovince), который значит то же самое что place=state, но там где не штаты, а провинции. При этом там где провинции (в Канаде, Франции и т.п.) все всё равно используют place=state, так что зачем province нужен не вполне понятно.
Но в Японии, Турции и Южной Корее административные единицы верхнего уровня (префектуры/иль/провинции) мапят через province, поэтому надо обрабатывать place=province.
Но просто так приравнять его к state нельзя, т.к. в Испании, Италии и ещё нескольких странах примерно 5% административных единиц с уровнем admin_level=6 (следующая ступень деления после state) замаплены как place=province.
Поэтому предлагается конвертить province в state в зависимости от  того в какой мы стране. …
=> [generator][storage] Convert place=province to place=state for Japan, South Korea and Turkey.

android/res/values-zh/strings.xml, data/categories.txt, data/strings/types_strings.txt, iphone/Maps/LocalizedStrings/zh-Hans.lproj/Localizable.strings
酒店, которое использовалось раньше, чаще употребляется в значении "отель", а мы при вводе 酒店 показывали алкомаркеты.
酒店 судя по всему употребляется в значении отель как в traditional так и в simplified, в частности на всех наших букинговских кнопках, вотс нью, пушах и т.п. как для zh-Hans так и для zh-Hant используется 酒店.
=> [categories][search][strings] Fix simplified Chinese wine shop translation.

generator/generator_tool/generator_tool.cpp, generator/routing_index_generator.cpp, generator/routing_index_generator.hpp
Реквест для сериализации кросс-мвм секции для экспериментального транзита. Сводится к тому, что по экспериментальному флагу вместо объекта  типа `routing::transit::GraphData` сериализуется объект `transit::experimental::TransitData`.
=> [generator] Serialize experimental transit cross-mwm section.

routing/routing_tests/index_graph_tools.cpp
Удаление юзингов перед добавлением работы с namespace ::transit::experimental.
=> [routing] Remove using from routing_tests/index_graph_tools.

map/transit/transit_reader.cpp
=> [map] Remove using namespace routing from transit reader.

android/jni/com/mapswithme/maps/Framework.cpp, android/jni/com/mapswithme/vulkan/android_vulkan_context_factory.cpp, android/jni/com/mapswithme/vulkan/android_vulkan_context_factory.hpp, drape/graphics_context.hpp, drape/support_manager.cpp, drape/support_manager.hpp, drape/texture_of_colors.cpp, drape/texture_of_colors.hpp, drape/vulkan/vulkan_base_context.cpp, drape/vulkan/vulkan_base_context.hpp, shaders/CMakeLists.txt
На Android 10 и Mali-G76 обновление региона текстуры приводит к тому, что все старые данные текстуры затираются. Затираются прозрачным чёрным цветом, что в результате даёт такие артефакты, как невидимые глифы и др.
Пример draw call-а наименования улицы, который выглядит как состоящий из одной только (белой) обводки:
здесь в текстуре палитры сине-зелёная точка (поставлена мной) над зелёной четвёркой пикселей указывает на текстурные координаты (0.9219, 0.3594). Как видно первая часть текстуры палитры полностью пустая и заполнена прозрачным чёрным цветом (или очищена).
В [шейдер](https://github.com/mapsme/omim/blob/9556ebaa46532643b0970dfba9604a40649fbbd9/shaders/GL/text_outlined.vsh.glsl) для этого draw call-а передаются текстурные координаты основного цвета текста (0.92188, 0.35938), …
=> [drape] [Vulkan] [Android] Update whole palette texture at once

docs/building_pybindings.txt
Мы с @tatiana-yan вчера потратили некоторое время на сборку pybindings на MacOS 10.15.5 (Catalina) и решили пару проблем при сборке. Чтоб эти решения не потерялись, я добавил их в документацию по сборке bybindings.
@tatiana-yan @vicpopov PTAL
=> [docs] Adding problem solving to building pybindings documentation.

base/base_tests/CMakeLists.txt, base/base_tests/exception_tests.cpp, base/exception.hpp
Иногда возникает необходимость перехватить все исключения и не дать им выйти за пределы вызова.
Я планирую использовать данную ф-цию далее в kml/pykmlib/bindings.cpp, что при не правильном вводе наш сервер не падал и в других подобных местах.
=> [base] All kinds of exceptions catcher.

transit/transit_types.hpp, transit/world_feed/CMakeLists.txt, transit/world_feed/gtfs_converter/gtfs_converter.cpp, transit/world_feed/subway_converter.cpp, transit/world_feed/subway_converter.hpp, transit/world_feed/world_feed.cpp, transit/world_feed/world_feed.hpp, transit/world_feed/world_feed_tests/world_feed_tests.cpp
Реквест реализует подмешивание данных о метро, полученных из OSM, в данные об общественном транспорте, взятые из GTFS. **Юнит-тесты** #13335 успешно проходят локально, будут мержиться на мастер после этого реквеста.
Подмешивание происходит на этапе `gtfs_converter`: 
1. В `gtfs_converter` добавлен опциональный параметр `path_subway_json` - путь к json с метро.  
2. `gtfs_converter` посредством нового класса `SubwayConverter` парсит этот  json и заполняет из него соответствующие поля экземпляра `WorldFeed` - остановки, линии, и т.д. 
3. Экземпляр `WorldFeed` разбивает получившиеся сущности по границам регионов и дампит в line-by-line json. Для этого вызывается метод `WorldFeed::Save()`,  как и в случае с сохранением обычных GTFS фидов.
**Замечания:**
1. **Генерация routes.** В метро-json …
=> [transit] Mixin subway json to the new transit jsons.

indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp, search/geocoder.cpp
У нас сейчас suburb это и район города ("аэропорт", "бутырский" и т.п.) и всякие микрорайоны/жк кторые гораздо меньше и замапаны через landuse=residential/place=neighbourhood. Для последних использование радиуса 2 км приводит к нерелевантным результатам которые для ранкера выглядят хорошо.
Радиусы были получены методом прикладывания "линейки" к выдаче overpass для соответсвующего типа.
=> [search][indexer] Use different radius for different suburb types.

generator/generator_tests_support/test_feature.cpp, generator/generator_tests_support/test_feature.hpp, search/processor.cpp, search/ranker.cpp, search/ranking_info.cpp, search/ranking_info.hpp, search/ranking_utils.cpp, search/ranking_utils.hpp, search/search_integration_tests/processor_test.cpp, search/search_tests/ranking_tests.cpp
Сделала использование в поиске и протаскивание в ranking_info. Осталось сделать какое-то понижение в ранжировании для alt_name и old_name . Варианты: уменьшать компоненты ранжирования полученные из имени на коэффициент или прибавлять отрицательный коэффициент).
Отдельный реквест по другому отображению результатов: https://github.com/mapsme/omim/pull/13389 Пока остался открытым вопрос как отображать если старое имя было использовано не для конечного результата, а для города/района/улицы. Т.к. мы вообще не показываем пользователю какие токены и на что заматчились, полное совпадение/не полное и т.п., то возможно никак.
=> [search] Use alt_name/old_name.

search/ranker.cpp
Отображение alt_name/old_name  в скобочках если по нему заматчилось.
Показала Ксюше, она одобрила.
Выглядит так:
https://www.openstreetmap.org/node/4027027525 
С альтернативными направлениями письма тоже ок:
https://www.openstreetmap.org/way/35201362
https://www.openstreetmap.org/node/2506247280
https://www.openstreetmap.org/way/35201362
=> [search] Add alt/old name in braces when search result is matched by alt/old name.

routing/transit_graph_loader.cpp, transit/CMakeLists.txt, transit/experimental/transit_data.cpp, transit/experimental/transit_types_experimental.hpp, transit/transit_tests/transit_test.cpp, transit/transit_types.cpp, transit/transit_version.cpp, transit/transit_version.hpp
- Добавлена функция, которая читает поле версии транзитного хедера и возвращает версию. 
- В тестах старой транизтной версии и в ее продовой записи расходился номер: в mwm мы пишем 0, в тестах почему-то 1. Это исправлено.
=> [transit] Versioning for transit section.

base/buffer_vector.hpp, coding/transliteration.cpp, coding/transliteration.hpp, indexer/CMakeLists.txt, indexer/search_string_utils.cpp, indexer/transliteration_loader.cpp, indexer/transliteration_loader.hpp, map/framework.cpp, search/search_integration_tests/processor_test.cpp, xcode/indexer/indexer.xcodeproj/project.pbxproj
В японии две слоговых азбуки, которые почти соотвествуют друг другу (но имеют разное написание и соответственно разные коды в юникод):
https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D1%82%D0%B0%D0%BA%D0%B0%D0%BD%D0%B0
https://ru.wikipedia.org/wiki/%D0%A5%D0%B8%D1%80%D0%B0%D0%B3%D0%B0%D0%BD%D0%B0
Нужно уметь искать в случаях если данные в осме не хирагане, а запрос на катакане и наоборот. Предлагается всё приводить к в катакане, т.к. в ней есть несколько символов отсуствующих в хирагане (а для всего что есть в хирагане соотвествующий символ в катакане тоже есть) и т.к. она чаще употребляется в осм (по крайней мере названия городов и стран чаще на ней).
Есть несколько вариантов как это делать: использовать icu который мы используем для транслитерации stringutf8multilang или сделать свой …
=> [search][coding] Normalize ja kana.

transit/world_feed/feed_helpers.cpp, transit/world_feed/world_feed.cpp, transit/world_feed/world_feed.hpp
Ребро определяется по двум остановкам и линии, к которой они относятся. Для них в GTFS-файле stop_times.txt указываются arrival_time и departure_time. Как разницу между отправлением от остановки 1 и прибытием на остановку 2 мы рассчитываем вес ребра в секундах. 
Есть нюанс. В ряде случаев эти времена могут быть не заполнены, и мы получаем ребро с нулевым весом. PR делает следующее:
- Если времена не указаны, но заполнен shape_dist_traveled для обеих остановок, мы вычисляем время по нему (t = s / v_avg).
- Если не указан даже shape_dist_traveled (тогда появляются вопросы к авторам фида, но это другая история), мы сами его вычисляем по отрезку shape между двумя остановками.
=> [transit] If edge weight is zero, calculate it based on the distance.

transit/world_feed/world_feed.hpp, transit/world_feed/world_feed_tests/CMakeLists.txt, transit/world_feed/world_feed_tests/subway_converter_tests.cpp
Юнит-тесты для подмеса метро #13301. Успешно проходят локально. Станут мержепригодными после заливки в мастер реквеста, для которого они и сделаны #13301.
@bykoianko Так как реквест на мастер, в нем видны изменения #13301. На самом деле интересует только файл `subway_converter_tests.cpp.`
=> [transit] Subway mixin unit tests.

geometry/geometry_tests/nearby_points_sweeper_test.cpp, geometry/nearby_points_sweeper.cpp, geometry/nearby_points_sweeper.hpp, map/map_integration_tests/interactive_search_test.cpp, map/search_api.cpp, search/pre_ranker.cpp, search/pre_ranker.hpp, search/processor.cpp, search/search_integration_tests/search_edited_features_test.cpp, search/search_params.hpp
Сейчас у нас расстояния между результатами по вертикали и по горизонтали жестко связаны. В ближайшее время планируется добавить большие плашки с ценами на отели, для этого лучше развязать расстояния, чтобы иметь возможность по вертикали оставить старые, а по горизонтали при необходимости увеличить.
=> [search][map] Allow to set different vertical and horizontal distance between search results.

base/base_tests/exception_tests.cpp, base/exception.hpp
В ExceptionCatcher был один не приятный момент.
Предположим, что ф-ция `fn` возвращает значение по константой ссылке, например, предварительно его где-то отыскав (https://github.com/mapsme/omim/blob/ee133396e229eb7a3a9943060f78a83fab684f43/kml/pykmlib/bindings.cpp#L55).
Предположим, что нам нужно обернуть ее в ExceptionCatcher. Но в случае исключения ExceptionCatcher возвращает значение сгенерированное конструктором по умолчанию. Т.е. код `return std::result_of_t<Fn && (Args && ...)>();` становится не компилируемым.
Предлагаю следующее решение проблемы.
@mpimenov @mesozoic-drones PTAL
=> [base] ExceptionCatcher. Prevent returning reference on a local temporary object.

search/ranking_info.cpp
Пока не смогла посмотреть как это выглядит на наших размеченных данных, т.к. текущие карты не содержат alt_name в строках и в поисковом индексе.
Можно или после сборки данных посмотреть и при необходимости внести правки или дождаться сборки данных (по идее это будет после создания ветки release-102 уже в ветке).
=> [search] Decrease name rank for features matched by alt/old name.

coding/coding_tests/string_utf8_multilang_tests.cpp, coding/string_utf8_multilang.cpp, coding/string_utf8_multilang.hpp, editor/xml_feature.cpp, editor/xml_feature.hpp, generator/feature_builder.cpp, generator/generator_integration_tests/features_tests.cpp, generator/generator_tests/feature_builder_test.cpp, generator/generator_tests/osm_type_test.cpp, generator/osm2type.cpp, generator/osm_element.cpp, generator/relation_tags.cpp
cherry-pick  сохранения alt/old name и использования в редакторе (все сохраненные имена мы показываем в редакторе, поэтому перенести только сохранение, но не редактор нельзя).
cherry-pick нужен чтобы имена пораньше попали в данные и была возможность тестировать функции связанные с наличием alt/old name.
Оригинальные реквесты:
https://github.com/mapsme/omim/pull/13229
https://github.com/mapsme/omim/pull/13260
https://github.com/mapsme/omim/pull/13312
=> [coding][generator] Store alt_name and old_name from osm.

openlr/candidate_paths_getter.cpp, openlr/candidate_paths_getter.hpp, openlr/score_candidate_paths_getter.cpp, openlr/score_candidate_paths_getter.hpp
Новый мачер с новой геометрией в некоторых ситуациях не привязывал корректно. Проблема была в том, что дороги были много кратно продублированы и это давало комбинаторный рост кол-ва вариантов, и потребляемой памяти. И соответственно останавливало мачинг. Чтоб это поправить я добавил фильтр: EdgeSortUniqueByStartAndEndPoints(), который выкидывает дубликаты.
Кроме того, сделал еще 2 улучшения.
- При поиске, коротких путей, как отойти от старта и подойти к финишу в GetAllSuitablePaths() сделал, чтоб не было пройдено слишком много вершин. `Проверка: if (u->m_distanceM > distanceToNextPointM)`;
- Сравнение тоже с высотой не всегда срабатывало. Т.к. в ряде ситуаций, не всегда, высоты в них была равно 0. (Подробнее https://github.com/mapsme/omim/pull/13288) Поэтому сделал проверку: `if …
=> [openlr] Fixing openlr matcher.

search/geocoder.cpp, search/pre_ranker.cpp, search/pre_ranking_info.hpp, search/ranker.cpp, search/ranking_info.cpp, search/ranking_info.hpp, search/result.hpp, search/search_integration_tests/processor_test.cpp, search/search_tests_support/helpers.cpp, search/search_tests_support/helpers.hpp
https://confluence.mail.ru/pages/viewpage.action?pageId=99977256&focusedCommentId=481822067#Booking.comFilters&SearchImprovements-comment-481822067
Отели, которые не прошли фильтр требуется пропускать через поиск (отдавая при этом предпочтения прошедшим фильтр отелям), чтобы в случае когда мало отелей прошло фильтр мы могли показать хотя бы не прошедшие + информацию почему они не прошли.
Сейчас у нас это частично реализовано -- мы сначала применяем оффлайн фильтры, потом прореживаем/ранжируем, потом применяем к результатам онлайн фильтр и показываем по-разному те отели которые прошли и не прошли фильтр.
Но разное поведение при непрохождении онлайн и оффлайн фильтров странно, нужно одинаковое.
=> [search] Pass hotels refused by booking filter.

routing/base/astar_progress.cpp
Во время работы routes_builder_tool в дебаге периодически срабатывает assert:
```
LOG TID(1) INFO      19.7545 routes_builder_tool/utils.cpp:140 BuildRoutes() Progress: 4 %
TID(2) ASSERT FAILED
base/astar_progress.cpp:104
CHECK(m_lastPercentValue <= kMaxPercent) 99 99
Assertion failed: (false), function UpdateProgress, file /Users/o.khlopkova/forked/omim/routing/base/astar_progress.cpp, line 104.
```
Это происходит, когда в `ASSERT_LESS_OR_EQUAL(m_lastPercentValue, kMaxPercent, ());` в `routing/base/astar_progress.cpp` некорректно сравниваются числа с плавающей точкой, которые не могут быть представлены точно. Например m_lastPercentValue=99.000000082 и kMaxPercent=99.000000000.
=> [routing] Fix for crash in debug mode in A* UpdateProgress.

transit/transit_entities.hpp, transit/world_feed/feed_helpers.cpp, transit/world_feed/feed_helpers.hpp, transit/world_feed/gtfs_converter/gtfs_converter.cpp, transit/world_feed/world_feed.cpp, transit/world_feed/world_feed.hpp, transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp, transit/world_feed/world_feed_tests/world_feed_tests.cpp
Класс `WorldFeed` нужен, чтобы конвертировать фиды из формата GTFS и сохранять в специального вида line-by-line json.  Этот класс используется тулзой `gtfs_converter`. Сохраненные с ее помощью json'ы затем отдаются генератору  карт (`generator_tool`) для заполнения новой версии транзитной секции. Более подробное описание WorldFeed есть в реквесте по его добавлению: #12946 
В этом реквесте в `WorldFeed` внесены улучшения:
- Добавлена валидация весов ребер (`edges`), соединяющих остановки в граф для роутинга. В GTFS может попадаться оторванное от нашего пространства-времени расписание, а также удивительные координаты остановок. Например, время в пути между двумя автобусными остановками, разнесенными на 60км, может составлять 40 секунд. Линии маршрута с такими аномалиями мы не сохраняем в …
=> [transit] Validate edge weight in gtfs_converter.

transit/experimental/transit_data.cpp, transit/experimental/transit_types_experimental.cpp, transit/experimental/transit_types_experimental.hpp, transit/transit_experimental_tests/parse_transit_from_json_tests.cpp, transit/transit_experimental_tests/transit_serdes_tests.cpp, transit/transit_tests/transit_tools.hpp, transit/world_feed/subway_converter.cpp, transit/world_feed/world_feed.cpp, transit/world_feed/world_feed.hpp
При подготовке реквеста про работу с экспериментальным транзитом в рантайме #13353 всплыло, что я забыла добавить в объект остановки поле "айди пересадок". В этом поле перечисляются пересадки, в которых фигурирует айдишник остановки. 
Данный реквест это исправляет.
=> [transit] Add links from stop to transfer.

data/replaced_tags.txt
[MAPSME-14244](https://jira.mail.ru/browse/MAPSME-14244)
Судя по маппингу в ОСМ, ситуаций, когда присутствует тег cycleway=opposite_lane, но при этом есть другие теги, говорящие, что по другим полосам велосипедам проезд запрещен ("oneway:bicycle"="yes"), всего 28 штук. И большинство из них некорректны. Поэтому предлагаю присутствие тега cycleway=opposite_lane считать возможностью велосипеда ехать в обе стороны.
Например:
[OSM way](https://www.openstreetmap.org/way/440561496)
До реквеста мы не ведем "против движения": 
После реквеста ведем в обе стороны:
=> [data] Handle cycleway=opposite_lane.

drape_frontend/visual_params.cpp
Исключит ситуацию, когда для некоторых конфигураций viewport-а (ScreenBase) zoomLevel достигает значения 20
=> [drape] Set upper limit for current zoom level calculated for requested tiles

editor/xml_feature.hpp
сохранение/отправка правок в alt/old name работала, а загрузка патча к отредактированной фиче -- нет (и для international name, который у нас давно то же самое)
https://jira.mail.ru/browse/MAPSME-14100
=> [editor] Fix International/Alternative/Old name load for edited feature.

drape_frontend/user_mark_shapes.cpp
`GeneratePoiSymbolShape` используется в двух местах: для основного символа и для бэйджа. Добавил проверку указателя на непустоту.
https://jira.mail.ru/browse/MAPSME-14487
=> [drape] crash fix in df::CacheUserMarks

iphone/Maps/UI/Subscription/AllPass/AllPassSubscriptionViewController.swift, iphone/Maps/UI/Subscription/AllPass/AllPassSubscriptionViewController.xib
https://jira.mail.ru/browse/MAPSME-14484
=> [iOS] Replaced localization of terms in Outdoor subscription screen

data/editor.config, editor/editor_tests/xml_feature_test.cpp, editor/xml_feature.cpp, generator/osm2meta.cpp, indexer/ftypes_matcher.cpp, indexer/ftypes_matcher.hpp
Исправила редактирование recycling centre -- от него при редактировании отваливался recycling_type.
Добавила возможность создавать/редактировать recycling container.
Добавила сохранение оператора для recycling centre + будет в отдельном реквесте приведение в соответствие операторов которые мы подгружаем из osm и которые мы даем редактировать.
=> [editor] Fix recycling centre and recycling container.

data/categories.txt
Неожиданно когда по запросу кремль находится что-то что не содержит в названии слово кремль и кремлем не является (и при этом не находится то что содержит в названии слово кремль).
=> [categories] Remove confusing castle synonym.

drape_frontend/transit_scheme_builder.cpp, iphone/Maps/Core/Routing/MWMRouterTransitStepInfo.mm, map/transit/transit_display.cpp, map/transit/transit_display.hpp, map/transit/transit_reader.cpp, map/transit/transit_reader.hpp, routing/routing_tests/index_graph_tools.cpp, routing/transit_graph.cpp, routing/transit_graph.hpp, routing/transit_graph_loader.cpp, routing/transit_info.hpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, transit/transit_display_info.hpp, transit/transit_entities.hpp, transit/transit_version.hpp, xcode/transit/transit.xcodeproj/project.pbxproj
Реквест реализует работу с новой версией транзитной секции в рантайме:
-  роутинга,
- отрисовки проложенного маршрута.
@bykoianko @tomilov Реквест удобнее всего смотреть по комитам.
В нем делается следующее: 
- в классы, ответственные за хранение данных из транзитной секции, добавляется поле "версия" и поля в формате новой версии, которые частично или полностью соответствуют старым полям (например, line). Старые поля переименовываются путем добавления суффикса Subway (потому что старая версия транзита - это только метро); новые поля именуются с добавлением суффикса PT (public transport).
- в соответствии с этим отрефакторен код, который с этими классами работает. Он разбивается на две ветки: if (старая версия), if (новая версия).
Для обработки новой версии транзита в рантайме в слое со …
=> [transit][routing] Experimental transit in runtime.

data/editor.config
Сейчас мы сохраняем operator из osm только для банкоматов и заправок и при этом позволяем его редактировать для гораздо более широкого круга объектов. Это плохо т.к. мы предлагаем пользователю заполнить то что сами из осма не подтянули -- можно делать дублирующиеся или почти дублирующиеся правки, можно корректное значение заменить на значение хуже и т.п.
В этом реквесте прореживание типов для которых мы даем редактировать operator, отдельно сделаю сохранение оператора из osm для "уцелевших" типов.
=> [editor] Disable operator editing for some object types.

cmake/OmimHelpers.cmake
The project builds using c++17 standard, so if compile headers with
-std=c++14 compiler complains about "optional" and so on things,
that part of c++17 standard
=> [cmake] fix build with USE_PCH=On on Linux/gcc

generator/generator_integration_tests/features_tests.cpp
сломалось после https://github.com/mapsme/omim/pull/13477
=> [generator_integration_tests] Fix CheckGeneratedData

android/src/com/mapswithme/maps/search/SearchAdapter.java
Если tail пустой точка всё равно нужна, т.к. перед tail будет тип размещения.
было:
стало:
баг Саша Блинчиков заведёт, добавлю его сюда когда будет.
=> [android] Fix subtitle for available hotels without rating.

android/build.gradle, android/gradle.properties
Обновил зависимость для WorkManager'a до 2.2.0 версии, в которой был пофикшен крэш https://developer.android.com/jetpack/androidx/releases/work#2.2.0-rc01 . Сам крэш вот :
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 bqHint=4 (has extras) } in androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateBroadcastReceiver@7d7eb5e
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:988)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6917)
at java.lang.reflect.Method.invoke(Method.java)
at …
=> No issue crash in workmanager

data/mapcss-mapping.csv
Различия между этими типами для нас несущественны.
В редакторе этот тип не поддерживается, поэтому не должно быть проблем от склеивания тегов.
=> [types] Save place=quarter as place=neighbourhood.

drape_frontend/transit_scheme_renderer.cpp, map/transit/transit_reader.cpp, transit/transit_display_info.hpp
Декомпозиция большого реквеста про отрисовку слоя метро на новой версии транзитной секции: #13476
Чтение метадаты линий для работы с ней в transit_scheme_builder. Метадата линий - это разбиение линий на кусочки, для каждого из которых определено смещение.
Выдержка из lines_metadata.transit.json:
`{"id":1869729,"shape_segments":[{"order":-3,"start_index": 396,"end_index":1894}]}`
Означает, что у линии 1869729 есть сегмент с 396 по 1894 индексы на полилинии (айди полилинии находится в lines.transit.json), который в дрейпе должен отрисоваться со смещением -3.
А также чтение ребер и пересадок (долг с прошлых реквестов).
=> [transit] Read lines metadata for subway layer rendering.

tracking/tracking_fuzz_tests/tracking_fuzz_tests.cpp
На Linux не собирался tracking_fuzz_test. Теперь собирается.
@mesozoic-drones @ToshUxanoff PTAL
=> Tracking fuzz test linux build fix.

generator/final_processor_country.cpp, generator/mini_roundabout_transformer.cpp, generator/mini_roundabout_transformer.hpp
https://jira.mail.ru/browse/MAPSME-13070
**Баг:** в странах с левосторонним движением (Англия, Индия и тд) мы генерим раундэбауты - линии из мини-раундэбаутов - точек с полилинией, направленной в противоположную сторону. Роутинг ведет по таким раундэбаутам как по дорогам с правосторонним движением, то есть против движения. 
**Фикс:** на этапе генерации раундэбаутов учитывать лево- или право-стороннее движение в стране. 
Пример: [раундэбаут в Англии.](https://www.openstreetmap.org/node/220512990#map=8/50.799/0.297)
| До реквеста | После реквеста |
| ------------- | ------------- |
| <img width="400" alt="Screenshot 2020-08-27 at 13 31 53" src="https://user-images.githubusercontent.com/54934129/91433272-b855d900-e86b-11ea-814b-f9baed7d8250.png">  | <img width="320" alt="Screenshot …
=> [generator] Generate clockwise roundabouts in countries with left-hand traffic.

transit/experimental/transit_data.cpp, transit/experimental/transit_types_experimental.cpp, transit/experimental/transit_types_experimental.hpp, transit/transit_experimental_tests/parse_transit_from_json_tests.cpp, transit/transit_experimental_tests/transit_serdes_tests.cpp, transit/transit_tests/transit_tools.hpp, transit/world_feed/subway_converter.cpp, transit/world_feed/world_feed.cpp, transit/world_feed/world_feed.hpp
Для названий операторов, маршрутов, линий, остановок замена мапы "язык" - "текст" на обычный std::string (пункт 1 для ужатия транзитной секции #13474).
=> [transit][world_feed] Replace translations dict with std::string.

search/emitter.hpp, search/hotels_classifier.cpp, search/hotels_classifier.hpp, search/processor.cpp, search/result.hpp
The main reason is to avoid flickering of the filter button when
zoomed in to an area without hotels.
=> [RELEASE_ONLY] [search] Make HotelsClassifier look at the query too (and not only at results).

routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_integration_tests/route_test.cpp, routing/routing_integration_tests/turn_test.cpp
Новая версия данных сломала 8 интеграционных тестов роутинга:
**RussiaMoscowNoTurnsOnMKADTurnTest.** Количество поворотов - 2 вместо 1.
Добавлен маневр TurnSlightLeft, потому что в ОСМ у дублера МКАДа поменялся тип с линк на транк:
https://www.openstreetmap.org/changeset/88025306#map=15/55.6095/37.4940
Сам тест проверяет съезд с МКАД вправо, который теперь считается не 1ым маневром, а 2ым.
**NetherlandsAmsterdamBicycleYes.** Разница в ETA ~3 секунды. Было 301.8, стало 304.296. В рамках погрешности, все ок. Сам путь не изменился.
**BelarusMinksBarURatushiToMoscowBusStation** - разница в длине маршрута 187 метров. Было 2677.57, стало 2395.3.
Домапили пешую дорожку, теперь не надо строить крюк.
Было:
Стало:
**RussiaPriut11Elbrus** - пеший. Время. Было: 32588.6 стало: 37753.4 разница: 2281 с …
=> [routing][integration tests] Update for new mwm version.

data/countries-strings/ar.json/localize.json, data/countries-strings/cs.json/localize.json, data/countries-strings/da.json/localize.json, data/countries-strings/de.json/localize.json, data/countries-strings/el.json/localize.json, data/countries-strings/en.json/localize.json, data/countries-strings/es.json/localize.json, data/countries-strings/fi.json/localize.json, data/countries-strings/fr.json/localize.json, data/countries-strings/he.json/localize.json, data/countries-strings/hu.json/localize.json, data/countries-strings/id.json/localize.json, data/countries-strings/it.json/localize.json, data/countries-strings/ja.json/localize.json, data/countries-strings/ko.json/localize.json, data/countries-strings/nb.json/localize.json, data/countries-strings/nl.json/localize.json, data/countries-strings/pl.json/localize.json, data/countries-strings/pt.json/localize.json, data/countries-strings/ro.json/localize.json, data/countries-strings/ru.json/localize.json, data/countries-strings/sk.json/localize.json, data/countries-strings/sv.json/localize.json, data/countries-strings/th.json/localize.json, data/countries-strings/tr.json/localize.json, data/countries-strings/uk.json/localize.json, data/countries-strings/vi.json/localize.json, data/countries-strings/zh-Hans.json/localize.json, data/countries-strings/zh-Hant.json/localize.json, data/countries_names.txt
в файле с переводами переводы для боливии были два раза, в "старых" был неправильный перевод на китайский
=>  [strings] Remove duplicates for Bolivia_North, Bolivia_South

drape/vulkan/vulkan_base_context.cpp
Баг:
- В `FrontendRenderer::RenderFrame()` вызов `VulkanBaseContext::BeginRendering()` был вызван успешно (иначе был бы ранний выход и до выполнения `EndRendering` и `Present` не дошло бы), следовательно `m_presentAvailable == true`. `VulkanBaseContext::EndRendering()` также выполнился успешно и установил флаг `m_needPresent == true`, при этом командный буффер был отправлен на выполнение (асинхронное по отношению к текущему потоку). О завершении его выполнения просигнализирует семафор (строка `submitInfo.pSignalSemaphores = &m_renderSemaphores[m_inflightFrameIndex];`).
- При скачивании карты отображается баннер. При клике по баннеру, если в системе не выбран браузер по умолчанию, показывается системное меню выбора браузера, модальное по отношению к приложению. При этом вызывается …
=> [drape] [Vulkan] Make rendering and presentation conditions the same

transit/CMakeLists.txt, transit/transit_schedule.cpp, transit/transit_schedule.hpp, transit/transit_tests/CMakeLists.txt, transit/transit_tests/transit_schedule_tests.cpp, xcode/transit/transit.xcodeproj/project.pbxproj
Класс расписания линий маршрутов  (пункт 2 для ужатия транзитной секции #13474). 
Применение этих классов будет добавлено в следующем реквесте: они заменят `osmoh::OpeningHours` в `gtfs_converter` и классах транзита из `omim/transit/experimental/transit_types_experimental.hpp/cpp`. Кроме того, теперь можно будет склеивать линии с одинаковой геометрией и последовательностью остановок, но разными рабочими днями. 
Иерархия дней работы линии и частоты курсирования по ней транспорта в классе Schedule: есть интервалы дней (формат день, месяц, год), и к ним привязаны дни недели, по которым транспорт ходит. А есть исключения в расписании - не интервалы, а отдельные даты. И к интервалам, и к исключениями привязаны интервалы в сутках, внутри которых транспорт ходит с определенной частотой. …
=> [transit] Schedule class for (de)serialization of transit timetables.

generator/generator_tests/osm_type_test.cpp, generator/osm2type.cpp
В некоторых случаях для old_name указывают даты, например
https://www.openstreetmap.org/relation/421007
сейчас мы такое не сохраняем, а хотелось бы
т.к. отдельных ключей под это в StringUtf8Multilang нет, но мы поддерживаем несколько alt/old name через точку с запятой, предлагается все old_name:dates запихивать в old_name через точку с запятой.
Единственное что плохо -- это может давать side effect на редактор -- если мы собрали old_name из old_name:dates, а потом пользователь его отредактировал, то правка в osm будет отправлена как просто old_name с несколькими разделенными точкой с запятой значениями (сам такой формат ок, но то что оно будет дублироваться с old_name:dates не хорошо, хотя ошибкой мапинга формально вроде не является).
=> [generator] Save old_name:dates.

map/search_mark.cpp, map/search_mark.hpp
https://jira.mail.ru/browse/MAPSME-14776
=> [drape] [Booking] Shift non-Booking and non-hotels searchmarks vertically to fit selection geometry

geometry/screenbase.cpp, geometry/screenbase.hpp, map/search_mark.cpp
Больше чеков, чтобы понять природу креша
https://console.firebase.google.com/project/mapsmestats/crashlytics/app/ios:com.mapswithme.full/issues/1b78b690393ce12fb66d1bc638384e09?time=last-seven-days&sessionId=b64354cb2f8c4663a4498e174aa284e0_DNE_2_v2
в данный момент креш воспроизвести не удалось, аналитически тоже не понятно как он может возникнуть:
внутри SearchMarks изначально значение MaxDimension нулевое и может только увеличиваться
Scale в ScreenBase тоже должен быть положительным.
=> [geometry][map] More checks for SearchMarks and ScreenBase.

search/ranker.cpp, search/search_integration_tests/processor_test.cpp
было:
стало:
Сделать одинаковые UpdateNameScores не придумала как, потому что во втором мы предварительно делаем нормализацию. Если убрать PrepareStringForMatching/ModifyStrasse внутрь второго UpdateNameScores, они всё равно получаются не единообразными. Если вытащить обработку alt/old name из первого, получится много дублирования кода.
=> [search] Support multiple semicolon separated alt/old names.

search/ranker.cpp
Решили пока выбирать имя улицы которое написано в основной строке результата поиска в зависимости от языка запроса.
Адрес в нижней строке решили оставить на языке устройства, т.к. если он написан на языке/алфавите на котором пользователь читает, то и так понятно. А если на языке/алфавите на котором пользователь не читает, то возможно лучше более понятное название региона на родном языке, чем более близкое к запросу, но иероглифыи т.п.
https://docs.google.com/document/d/1m5OaIT1FMt4jr64_eezvGjysJt1qwcrEV_Vfp6WpipM/edit
https://confluence.mail.ru/pages/viewpage.action?pageId=508174374
было:
стало:
=> [search] Choose street name language in the same way as result language.

routing/transit_graph.cpp, routing/transit_graph.hpp, transit/experimental/transit_data.cpp, transit/experimental/transit_types_experimental.cpp, transit/experimental/transit_types_experimental.hpp, transit/transit_entities.hpp, transit/transit_experimental_tests/parse_transit_from_json_tests.cpp, transit/transit_experimental_tests/transit_serdes_tests.cpp, transit/transit_schedule.cpp, transit/transit_schedule.hpp, transit/transit_serdes.hpp, transit/transit_tests/transit_tools.hpp, transit/world_feed/subway_converter.cpp, transit/world_feed/world_feed.cpp, transit/world_feed/world_feed.hpp, transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp
Заключительный реквест по ужатию транзитной секции из серии #13474. Использование пункта 2 (класс Schedule вместо osmoh::OpeningHours) в пункте 3 (склеивание расписаний для линий).
1. Различные trips из GTFS теперь объединяются в одну line при соблюдении условий:
- Одинаковый route id (маршрут один и тот же)
- Одинаковая последовательность остановок (везет по одним и тем же остановкам, без пропусков)
- Одинаковый shape id (полилиния маршрута совпадает)
До этого trip соответствовал line (матчинг по trip id). Поэтому у совпадающих по перечисленным выше параметрам линий могли быть различные service id, а соответственно и расписания. Теперь (что более логично) для одной линии эти расписания склеиваются в общее.
2. В TimeTable остановок osmoh::OpeningHours заменен на вектор объектов нового …
=> [transit] Replace osmoh::OpeningHours with Schedule.

map/isolines_manager.cpp, map/isolines_manager.hpp, map/notifications/notification_manager.hpp
Последнее использование `boost::optional`. Везде используется `std::optional`,
а здесь почему-то остался `boost::optional`.
=> [map] remove last usage of boost::optional

iphone/Maps/Categories/NSAttributedString+HTML.swift
https://jira.mail.ru/browse/MAPSME-14873
Добавлено дополнительное условие на attachement.bounds.  Бывают случаи image.size.width  > estimatedWidth но при этом attachement.bounds имеет меньшую или равную ширину, а бывает наоборот attachement.bounds > estimatedWidth (когда в теге img выставлен width=100% , в этом случае используем фикс из второго условия, при этом есть шанс что картинка будет меньше по ширине).
=> [iOS] Fixed image width in bookmarks description in PP

cmake/BundledBoost.cmake, generator/mwm_diff/pymwm_diff/CMakeLists.txt, generator/pygen/CMakeLists.txt, kml/pykmlib/CMakeLists.txt, local_ads/pylocal_ads/CMakeLists.txt, pyhelpers/setup.py, search/pysearch/CMakeLists.txt, search/pysearch/README.txt, tracking/pytracking/CMakeLists.txt, traffic/pytraffic/CMakeLists.txt
В принципе, линковка с libpythonX.Y.so означает намерение создать внутри собственной программы интерпретатор питона, и начать выполнять python-код в нём.
Мы этого в наших расширениях совсем не делаем, и линковка не должна быть нужной.
Насущная причина, помимо концептуальной - это невозможность сборки `manylinux2010`-wheels. Ноги растут из pypa/manylinux#30 - там было решено, что из-за различий в дистрибутивах linux лучше просто запретить линковку расширений с libpythonX.Y.so.
В итоге, на linux всё собирается и потом работает.
Нужно ещё проверить на маке.
=> [pybindings] remove linking to libpython

drape/utils/gpu_mem_tracker.cpp
Лишнее копирование в том числе и `std::string`, может быть и не критично
по производительности, но вызывает предупреждение от clang,
что немного мешает.
=> [drape] remove extra copy in gpu_mem_tracker

cmake/BundledBoost.cmake
Обнаружил, что свежесконфигурированный проект перестал собираться на Arch.
=> [cmake] Aid CMake 3.18.2 on Linux to find_package a bundled Boost 1.68

drape/CMakeLists.txt, shaders/CMakeLists.txt
При компиляции для iOS некоторые файлы упоминаемые в CMakeLists.txt отсуствуют,
и наоборот некоторые существующие не упоминаются.
Плюс исправление сборки для "чувствительной к регистру" файловой системы.
=> [drape] [shaders] [ios] Fix build with cmake

search/geocoder.cpp, search/geocoder.hpp, search/processor.cpp, search/query_params.cpp, search/query_params.hpp
Не понятно почему m_scale в QueryParams, т.к. к запросу особо отношения не имеет.
Предлагаю или перенести в GeocoderParams или вообще выпилить и заменить на `scales::GetUpperScale()`, т.к. другие значения оно не принимает.
=> [search] Query params minor refactoring.

routing/routing_integration_tests/bicycle_route_test.cpp, routing/routing_integration_tests/transit_route_test.cpp
После обновления карты https://github.com/mapsme/omim/pull/13747 сломалось 2 routing integration tests.
**SwedenStockholmBicyclePastFerry**
Данный тест на то, что велосипедные маршруты прокладываются через паромные переправы. В карте 200822 маршрут выглядел так:
После обновления карты до 200920 он изменился:
И изменилась его длина. От этого сломался тест. Он попрежнему прокладывается через route=ferry, но поскольку обновились фичи:
https://www.openstreetmap.org/way/837464719
https://www.openstreetmap.org/way/220794601
Он стал прокладываться иным путем.
Я сократил маршрут, но сделал так что большая его часть лежит на фичах route=ferry. Теперь он выглядит так:
**Transit_Moscow_NoSubwayTest**
Тест на то, что не стоит ехать на метро, а быстрее пройти пешком. Т.е. не смотря на то, что выбран …
=> [routing] Routing integration test fix for 200920.

search/pre_ranker.cpp, search/pre_ranker.hpp, search/search_integration_tests/pre_ranker_test.cpp
1) При поиске во вьюпорте при скролле периодически происходит отмена не завершенного поиска после чего приходят пустые результаты, которые могут затирать m_prevEmit, в результате чего стабильность результатов страдает.
2) После ограничения результатов на карте через прореживание (SweepNearbyResults) их остаётся не слишком много, нет особой необходимости в уменьшении количества результатов до BatchSize. При уменьшении до BatchSize может страдать стабильность результатов -- в SweepNearbyResults результаты выбираются с учётом их присутствия в m_prevEmit. Если после этого результат будет выкинут при фильтрации по BatchSize, то дальше он не попадёт в m_prevEmit и будет мигать.
3) Лучше выглядит когда мы предпочитаем результаты из прошлой выдачи результатам прошедшим фильтры. На кол-во …
=> [search] Make search results more stable.

base/CMakeLists.txt, base/base_tests/CMakeLists.txt, base/base_tests/lru_cache_test.cpp, base/base_tests/lru_cache_tests.cpp, base/lru_cache.hpp, coding/coding_tests/text_storage_tests.cpp, coding/text_storage.hpp, xcode/base/base.xcodeproj/project.pbxproj
Сейчас у нас TextStorage используется для ugc, википедии и букмарок. Планируется также использовать его для метадаты: https://github.com/mapsme/omim/pull/13653.
В данный момент размер кеша ничем не ограничен и кеш никогда не сбрасывается (только при уничтожении BlockedTextStorageReader), что может быть не очень хорошо с точки зрения потребляемой памяти. Предлагается использовать кеш ограниченного размера.
Выбор реализации и размера кеша делала так:
- по аналитическим оценкам и результатам профилирования наиболее загруженным местом для чтения TextStorage является чтение метадаты (https://github.com/mapsme/omim/pull/13653) при поиске отелей на карте: в этот момент drape читает метадату т.к. использует данные из неё для вытеснения, дрейп читает метадату для высоты зданий (3д), поиск читает …
=> [base][coding] Use LRU cache for TextStorage.

drape_frontend/rule_drawer.cpp, feature_list/feature_list.cpp, generator/generator_tests_support/test_feature.cpp, generator/search_index_builder.cpp, generator/utils.cpp, indexer/drules_selector.cpp, indexer/feature.cpp, indexer/feature.hpp, indexer/indexer_tests/CMakeLists.txt, indexer/indexer_tests/features_vector_test.cpp, indexer/indexer_tests/metadata_serdes_tests.cpp, indexer/metadata_serdes.cpp, indexer/metadata_serdes.hpp, map/booking_availability_filter.cpp, map/map_tests/booking_filter_test.cpp, routing/geometry.cpp, search/hotels_filter.cpp, search/intermediate_result.cpp, search/ranker.cpp, search/search_quality/booking_dataset_generator/booking_dataset_generator.cpp, xcode/indexer/indexer.xcodeproj/project.pbxproj
Чтобы компенсировать потери производительности после перехода на сжатое хранилище строк в метадате, предлагаю читать строки лениво -- то есть не всю метадату, а только нужные строки. По измерениям в поиске/рендеринге так примерно в 3-5 раз быстрее чем читать всё.
=> [indexer] Lazy metadata read.

map/routing_manager.hpp, qt/CMakeLists.txt, qt/draw_widget.cpp, qt/draw_widget.hpp, qt/routing_settings_dialog.cpp, qt/routing_settings_dialog.hpp, qt/routing_turns_visualizer.cpp, qt/routing_turns_visualizer.hpp
Реквест "страшненько, но удобно": в desktop-версию приложения добавлена возможность отображать координаты и названия маневров на построенном маршруте. 
**Зачем нужен этот реквест:** чтобы упростить проверку гипотез об алгоритмах генерации маршрутов, а также поиск и фикс багов.
**1. В настройки роутинга добавлен чекбокс, чтобы можно было включать/выключать визуализацию маневров.**
До реквеста | После реквеста |
--- | --- 
**2. Если чекбокс включен, помимо самого маршрута на карте появляются маневры.** Это точки - координаты на построенном маршруте и рядом с ними "названия" маневров. Название - это индекс на полилинии маршрута + тип маневра (направо, держитесь левее и тд).
=> [qt][map] Visualize routing turns on the map (desktop app).

drape_frontend/transit_scheme_builder.cpp, drape_frontend/transit_scheme_builder.hpp, transit/experimental/transit_data.cpp, transit/world_feed/feed_helpers.cpp, transit/world_feed/feed_helpers.hpp, transit/world_feed/subway_converter.cpp, transit/world_feed/subway_converter.hpp, transit/world_feed/world_feed.cpp, transit/world_feed/world_feed.hpp, transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp, transit/world_feed/world_feed_tests/subway_converter_tests.cpp, transit/world_feed/world_feed_tests/world_feed_tests.cpp
В этом реквесте реализованы изменения в конвертации старого формата метро в новый формат ОТ для корректного рендеринга секции ОТ на слое метро. Рендеринг реализован в замерженном реквесте #13591.
**1. Разбиение линии маршрута на отрезки в зависимости от того, на каком из отрезков сколько имеется параллельных ей линий другого цвета. Сохранение этой информации в lines_metadata.transit.json** 
В формате метро у нас есть 1 большой json-файл с данными о метро по всему миру. В нем полилинии геометрии метро (shapes) не хранятся целиком: каждая линия (line) разбита на ребра (edges), и каждое ребро ссылается на соответствующий отрезок геометрии. Пример ребра, соединяющего две остановки на линии:
```json
{
"line_id": 79174371,
"shape_ids": [
{
"stop1_id": 2678030,
"stop2_id": 35859318
}
], …
```
=> [transit][subway generator] Split lines into segments for rendering on the subway layer.

android/res/values/arrays.xml, android/src/com/mapswithme/maps/bookmarks/BookmarkCollectionAdapter.java, android/src/com/mapswithme/maps/bookmarks/BookmarkHeaderView.java, android/src/com/mapswithme/maps/bookmarks/data/BookmarkCategory.java
https://jira.mail.ru/browse/MAPSME-14856 
Исправлено наименование строки для what's new.
Вставлены переводы для guide's page.
При сборке дебажной версии не могу запуститься, так как все крашится из-за "слишком глубокого сбора логов". Может стоит где-то их подчистить?
@Polas, почему "Content by" строка с двоеточием? Это новое уточнение, в конфлюенсе версия без двоеточия.
=> [android] Fixed whats new screen and strings for lp.

routing/car_directions.cpp, routing/directions_engine.hpp, routing/index_router.cpp, routing/pedestrian_directions.cpp, routing/routing_integration_tests/pedestrian_route_test.cpp, routing/routing_settings.cpp, routing/routing_settings.hpp, routing/routing_tests/turns_generator_test.cpp, routing/turns_generator.cpp, routing/turns_generator.hpp
Для дальнейшей кастомизации маневров потребовалось реализовать эту todo из TurnsGenerator:
```
// @TODO(bykoianko) For the time being |kMaxOutgoingPointsCount| and |kMinOutgoingDistMeters|		
// have value for car navigation. On the other hand it's used for bicycle navigation.		
// But for bicycle navigation the value should be smaller. They should be moved to		
// RoutingSettings structure.
```
Теперь для пешеходов и велосипедов можно задавать свои значения.
=> [routing] Custom turn constants for each vehicle type.

map/guides_manager.cpp
https://jira.mail.ru/browse/MAPSME-15122
Была опечатка и из-за нее в момент отзумливания `m_lastShownViewport` мог быть инициализирован значениями вьюпорта по-умолчанию (это прямоугольник c 640 на 480), центр которого оказывался вне координат меркатора.
=> [guides on map] zoom-out from incorrect place is fixed.

routing/cross_mwm_index_graph.hpp
Данный PR дает 20-25% ускорения прокладки маршрутов на всех типах роутинга при условии, что mwms в районе прокладки маршрута одной версии (одной даты сборки).
Он достигает этого за счет отдельной обработки основного кейса при переходе волны A* через границу mwm: mwm-ки на переходе одной и той же версии. Если версии на данном переходе разные, то будет работать старый код.
Около 2 лет назад мы сделали PR мы заметили, что если соседние mwm содержат разную геометрию переходных фичь, то в A* может сработать чек, мы предполагали, что геометрия переходных фичь совпадает и вес перехода равен 0. Разная геометрия переходных фичь возможна, если соседние mwm имеют разные версии. Мы сделали PR, который исправлял проблему  https://github.com/mapsme/omim/pull/10006. Он проверял геометрию переходных фичь …
=> [routing] Routing performance optimization. Stop checking twin features geometry on the same mwm versions.

routing/routing_integration_tests/bicycle_turn_test.cpp, routing/routing_settings.cpp, routing/turns_generator.cpp
В некоторых случаях мы генерим некорректные маневры. Примеры:
Вело-маршрут 55.915690, 37.589723; 55.915838, 37.575417. Два маневра почти в одной точке:
TurnLeft : 2
TurnSlightRight : 3
И оба некорректные. В этой точке маневр вообще не нужен, потому что фейковая дуга составляет меньше 20 метров.
Фикс:
Вело-маршрут 55.917881, 37.586037; 55.916844, 37.578845. 
TurnLeft : 2
TurnSlightRight : 3  
Нужен TurnRight.
Фикс:
Вело-маршрут 55.869733, 37.458253; 55.870205, 37.460111.
Лишний маневр turnSlightRight:
Фикс:
1. При расчете угла маневра мы используем три точки: саму точку маневра, точку "слегка позади" и точку "слегка впереди" на маршруте. Возможна ситуация, когда две из этих точек совпадают (первая и вторая или вторая и третья), и угол рассчитывается неверно (-10 градусов вместо +150, +20 …
=> [routing] Handle corner-cases in pedestrian & bicycle turns.

indexer/data_source.hpp, routing/routing_integration_tests/CMakeLists.txt, routing/routing_integration_tests/concurrent_feature_parsing_test.cpp, routing/routing_integration_tests/get_altitude_test.cpp, routing/routing_integration_tests/routing_test_tools.cpp, routing/routing_integration_tests/routing_test_tools.hpp
**Цели данного PR**
(1) показать, как я собираюсь парсить фичи в несколько потоков на обособленном примере;
(2) протестировать работоспособность способа.
**Обоснование, почему можно парсить фичи в несколько потоков с несколькими `FeaturesLoaderGuard`**
Под каждый `FeaturesLoaderGuard` создается свой собственный `MwmHandle` в `MwmSet::GetMwmHandleByIdImpl()`. А стало быть свой собственный `MwmValue` в `DataSource::CreateValue()`. А для него создается свой собственный ридер в `platform::GetCountryReader()`. Т.е. для каждого `FeaturesLoaderGuard` создается свой собственный кэш (4MB) для чтения геометрии с диска.
При создании `FeaturesLoaderGuard` вызывается `DataSource::GetMwmHandleById()`. Он, в свою очередь, через цепочку вызовов вызывает `MwmSet::LockValueImpl()`, который в обращается без …
=> Concurrent feature parsing.

generator/generator_tool/generator_tool.cpp, generator/routing_index_generator.cpp, generator/routing_index_generator.hpp, generator/transit_generator_experimental.cpp, generator/transit_generator_experimental.hpp, transit/experimental/transit_data.cpp, transit/experimental/transit_data.hpp, transit/transit_entities.hpp, transit/transit_experimental_tests/parse_transit_from_json_tests.cpp, transit/world_feed/gtfs_converter/gtfs_converter.cpp, transit/world_feed/subway_converter.cpp, transit/world_feed/subway_converter.hpp, transit/world_feed/world_feed.cpp, transit/world_feed/world_feed.hpp, transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp, transit/world_feed/world_feed_tests/subway_converter_tests.cpp
https://jira.mail.ru/browse/MAPSME-14521
Задача: прокладывать маршруты между mwm со старой версией секции транзит (метро-онли) и mwm с новой версией секции (в будущем весь общественный транспорт, пока только метро).
Кросс-мвм маршрут между старой и новой версией транзита:
=> [transit] Implement cross-mwm routing for new transit version.

android/src/com/mapswithme/maps/onboarding/BaseNewsFragment.java, android/src/com/mapswithme/maps/onboarding/NewsFragment.java
https://jira.mail.ru/browse/MAPSME-15130
В тикете приложено видео, на котором можно заметить важный шаг для воспроизведения баги, переворот экрана. Без переворота экрана баг не воспроизводится. Проблема была в том, что при таком кейсе пересоздается сплэш активность, но листенер во фрагменте не обновляется и вызов для перехода в карту не срабатывает.
=> [android] Reset DialogDone listener after screen rotation

base/CMakeLists.txt, base/base_tests/CMakeLists.txt, base/base_tests/optional_lock_guard_tests.cpp, base/optional_lock_guard.hpp, xcode/base/base.xcodeproj/project.pbxproj
IndexGraph подобные классы должны работать для 2 стороннего A*, как в 2 поточном режиме, так и в однопоточном. В однопоточном режиме необходимо исключить накладные расходы на mutex. Для этого нужен класс аналогичный std::lock_guard, но такой, который берет mutex, только если он задан.
=> [base] Optional lock guard.

android/res/layout-land/fragment_ads_removal_purchase_dialog.xml, android/res/layout/ads_removal_pay_button_container.xml, android/res/layout/ads_removal_progress_container.xml, android/res/layout/fragment_ads_removal_purchase_dialog.xml
Половина таски https://jira.mail.ru/browse/MAPSME-15173.
Изменила стили текста на самые похоже по размеру. Ориентир https://scene.zeplin.io/project/58da0a395194ca7f0a361e61 
В фирме этих экранов нет, будут начерчены к 10.4 новые варианты.
Итог:
=> [android] Fixed night theme in ads removal screen.

android/src/com/mapswithme/maps/widget/SearchToolbarController.java
https://jira.mail.ru/browse/MAPSME-15123
By design после поиска и перехода к карте пиктограмма креста означает закрытие поиска - поэтому метод добавлен в обработчик нажатия на крестик, функциональность сокрытия не сработает, если пиктограмма имеет роль чистки строки поиска, так как внутри closeBottomMenu() есть проверка на состояние нижнего меню.
=> [android] Addid closing the filter rooms and guests when closing search.

generator/generator_integration_tests/features_tests.cpp
сейчас тесты падают с 
```
<<<Exception thrown [ Reader::OpenException /var/lib/jenkins/workspace/GeneratorIntegration/omim/coding/internal/file_data.cpp:50, "nodes.dat.short; Read; No such file or directory" ].>>>
```
=> [generator_integration_tests] Set m_genInfo.m_cacheDir.

android/src/com/mapswithme/maps/MwmActivity.java, android/src/com/mapswithme/maps/tips/Tutorial.java
https://jira.mail.ru/browse/MAPSME-15008
Проблема была в том, что показываемый туториал не соответствовал текущему выбранному слою. Решено сбрасывать слой при отображении туториала. При таком подходе туториал отображается верно, подсвечивая нужную кнопку. по нажатию на кнопку сразу выбирается слой, который соответствует показанному туториалу
=> [android] reset layer mode when tutorial is shown

kml/pykmlib/bindings.cpp, kml/pykmlib/bindings_test.py
Fix for
TypeError: No Python class registered for C++ class std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >
=> [pybindings] pykmllib fix

generator/mwm_diff/pymwm_diff/CMakeLists.txt, generator/pygen/CMakeLists.txt, kml/pykmlib/CMakeLists.txt, local_ads/pylocal_ads/CMakeLists.txt, search/pysearch/CMakeLists.txt, tracking/pytracking/CMakeLists.txt, traffic/pytraffic/CMakeLists.txt
cherry-pick of #13766 to release-103
=> [pybindings] Fix linking on Mac

qt/routing_settings_dialog.cpp
Fix for warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result].
=> [qt] Fix for ignoring function's val with 'warn_unused_result'.

android/res/layout-w600dp/pager_fragment_bookmarks_all_subscription.xml, android/res/layout/pager_fragment_bookmarks_all_subscription.xml, android/src/com/mapswithme/maps/onboarding/NewsFragment.java, android/src/com/mapswithme/maps/purchase/BookmarkAllSubscriptionData.java, android/src/com/mapswithme/maps/purchase/BookmarksAllSubscriptionActivity.java, android/src/com/mapswithme/maps/purchase/BookmarksAllSubscriptionFragment.java, android/src/com/mapswithme/maps/purchase/BookmarksAllSubscriptionPage.java, android/src/com/mapswithme/maps/purchase/BookmarksAllSubscriptionPageData.java, android/src/com/mapswithme/maps/purchase/BookmarksAllSubscriptionPageFragment.java, android/src/com/mapswithme/maps/widget/ParallaxBackgroundPageListener.java
https://jira.mail.ru/browse/MAPSME-15207
ParallaxBackgroundPageLiatener пришлось переписать полностью, тк ранее он работал с хардкодными imageView из лэйаута. Суть фикса заключается в следующих моментах:
* Вместо пробрасывая индекса страницы в качестве аргумента теперь надо пробросить список скринов из енама BookmarksAllSubscriptionPage в нужном порядке, которые необходимо отобразить во вьюпейджере. (см BookmarksAllSubscriptionActivity addBookmarkSubscriptionExtra метод)
* Вместо 2 разных массивов для текста на экране и картинок теперь генерируется единый объект, содержащий в себе и текст, и соотв. картинку, что позволяет избежать рассинхронизации текста и картинки (см метод makeItems в BookmarksAllSubscriptionFragment)
* Вместо работы с 4 хардкодными imageView в листенере вьюпейджера …
=> [android] Rework of all pass viewPager

generator/generator_tests/osm_type_test.cpp, generator/osm2type.cpp
В японском есть две слоговых азбуки -- катакана и хирагана. В name:ja_kana может быть записано имя на любой из них. Также есть тег name:ja-Hira в котором содержится имя на хирагане. В OCM 57к name:ja-Hira и 53к name:ja_kana.
У нас в StringUtf8Multilang есть ja_kana и нет ja-Hira (и кажется не нужно добавлять). Предлагается при отсутствии ja_kana и наличии ja-Hira сохранять ja-Hira из ОСМ в ja_kana в StringUtf8Multilang. Т.к. в name:ja_kana может быть как катакана так и хирагана не вижу в этом ничего плохого.
=> [generator] Save name:ja-Hira if there is no name:ja_kana.

android/src/com/mapswithme/maps/bookmarks/BaseBookmarkCategoriesFragment.java, android/src/com/mapswithme/maps/bookmarks/BookmarkListActivity.java, android/src/com/mapswithme/maps/bookmarks/BookmarksListFragment.java
https://jira.mail.ru/browse/MAPSME-14805
Проблема была в том, что при восстановлении стейта Активити из ее интента перекладываются данные в бандл, но к этому моменту в classLoader содержатся только андроидные классы, а пользовательские типы добавляются системой туда позднее
=> [android]: fix for crash on bookmarksCategory unmarshalling during ap restoration

android/res/layout/fragment_search.xml
https://jira.mail.ru/browse/MAPSME-14784
@alexzatsepin, предложенное тобой решение не вышло реализовать, так как плейсхолдер не перекрывает всю страницу и внизу бы все прокликивалось. Тут наглядно тинтанула плейсхолдер.
=> [Android] Hided pager when placeholder is visible

defines.hpp, routing/CMakeLists.txt, routing/cross_border_graph.cpp, routing/cross_border_graph.hpp, routing/routing_tests/CMakeLists.txt, routing/routing_tests/cross_border_graph_tests.cpp, xcode/routing/routing.xcodeproj/project.pbxproj
Мы хотим добавить в World mwm новую секцию для роутинга, из которой будем читать данные об основных дорогах между mwm. По графу из этих "дорог" параллельно нашему обычному роутингу будет запускаться второй поток, который найдет отсутствующие мвм, по которым предположительно проходит маршрут. Запуск потока реализован в #13922 
Это - реквест с классом - графом дорог, (де)сериализацией для него и тестами. Дорога представляет собой координаты начала и конца, привязанные к ним номера мвм и вес дороги (смотри иллюстрацию в реквесте #13922).
@bykoianko Классы с данными для роутинга в этом реквесте слегка отличаются от тех, что в #13922 (смысл тот же, исполнение чуть более инкапсулярное). Поэтому предлагаю сначала мержить этот реквест, а потом - предыдущий.
@maksimandrianov Сериализация секции в …
=> [routing][generator] Ser/des for routing section in new format for World.mwm.

android/src/com/mapswithme/maps/ugc/routes/BaseEditUserBookmarkCategoryFragment.java
https://jira.mail.ru/browse/MAPSME-15294
Тут пришлось изменить, так как если спрятать элемент при переходе на экран описания(где описание пустое), то в дальнейшем отображать так же нужно элемент, а это лишняя операция поиска элемента в одноэлементном списке.
MenuItem item = menu.findItem(R.id.done);
item.setVisible(mEditText.getEditableText().length() > 0);
=> [android] Edit visibility done button in edit category fragment.

iphone/Maps/UI/Search/MWMSearchManager.mm, map/framework.cpp, map/search_mark.cpp, map/search_mark.hpp
На оси поведение ПП и поиска отличается от андроида. Кейс сброса выделения через закрытие PP не был учтён.
Также исправлен баг отсутствия выделения сёчмарки при клике по тексту POI и POI.
Отслеживание просмотренных отелей выполняется до перезапуска.
https://jira.mail.ru/browse/MAPSME-14544
=> [iOS] [Booking] Track selection and visit status for features, which does not have corresponding search mark atm

android/src/com/mapswithme/maps/bookmarks/BaseBookmarkCategoriesFragment.java, android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java, android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesPagerFragment.java, android/src/com/mapswithme/maps/bookmarks/BookmarksPageFactory.java, android/src/com/mapswithme/maps/bookmarks/CachedBookmarkCategoriesFragment.java
https://jira.mail.ru/browse/MAPSME-8244
Проблема была в том, что логика отображения диалога оказалась в базовом классе двух экранов вьюпейджера, соответственно onResume вызывался дважды. Перенес эту логику в рутовый фрагмент вьюпейджера чтобы избавиться от двойного вызова
Пришлось добавить кэширование экранов в адаптере вьюпейджера, до этого на каждый вызов getItem создавался новый фрагмент, что с одной стороны не очень эффективно, а с другой не позволяло нотифицировать страницы вьюпейджера о том, что завершилась конвертация
=> [android] show convert bookmarks dialog only one time

android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
https://jira.mail.ru/browse/MAPSME-14497
Лучше воспроизводить с стр из комментариев.
Проблема заключалась в том, что когда после перехода из поиска мы сворачиваем pp, потом в метод refreshPreview для дискаунт приходит null и цена никак не отображается. Вставила такую проверку, потому что потом колобке все равно вызовет refreshPreview и в итоге цена запросится.
Сам класс довольно большой, поэтому вопрос: это ничего в дальнейшем не сломает? Я повестила, крепей и аномалий не словила.
=> [android] Fixed showing discount in pp.

map/cloud.cpp
If file rename failed (e.g. due to src and dst belongs to different filesystems), then try to copy file from source to dest then delete source if copy succeeded.
https://jira.mail.ru/browse/MAPSME-15284
=> [cloud][backup][base] Try copy if rename failed

defines.hpp, generator/generator_tests_support/routing_helpers.cpp, generator/region_meta.cpp, generator/restriction_generator.cpp, generator/routing_index_generator.cpp, indexer/feature_meta.hpp, routing/edge_estimator.cpp, routing/edge_estimator.hpp, routing/index_router.cpp, routing/leaps_graph.cpp, routing/single_vehicle_world_graph.cpp, routing/single_vehicle_world_graph.hpp, routing/transit_world_graph.cpp, routing/transit_world_graph.hpp, routing/world_graph.hpp, track_analyzing/track_analyzer/cmd_table.cpp, track_analyzing/track_analyzer/cmd_tracks.cpp, track_analyzing/track_matcher.cpp
Добавлено сохранение и загрузка коэффициентов средней скорости движения к точкам въезда/выезда при кросс-MWM роутинге.
=> Add leap weight heuristic for cross-MWM routing

map/routing_manager.cpp, routing/CMakeLists.txt, routing/absent_regions_finder.cpp, routing/absent_regions_finder.hpp, routing/async_router.cpp, routing/async_router.hpp, routing/dummy_world_graph.hpp, routing/fake_ending.cpp, routing/fake_ending.hpp, routing/index_graph_starter.cpp, routing/index_graph_starter.hpp, routing/index_router.cpp, routing/regions_router.cpp, routing/regions_router.hpp, routing/regions_sparse_graph.cpp, routing/regions_sparse_graph.hpp, routing/routing_session.cpp, routing/routing_session.hpp, routing/routing_tests/async_router_test.cpp, routing/single_vehicle_world_graph.cpp, routing/world_graph.hpp
@bykoianko @ldo2 PTAL.
Первый реквест в цепочке реквестов по замене обращения к OSRM-серверу. Реализует логику получения списка мвм, отсутствующих на девайсе пользователя и препятствующих построению заданного маршрута.
**Что есть этом реквесте** 
- Новый класс `AbsentRegionsFinder` - имеет интерфейс, схожий с `OnlineAbsentCountriesFetcher`, и подменяющий его в `AsyncRouter` для получения списка mwm, через которые проходит маршрут.
- Новый класс `RegionsRouter`, который строит маршрут из нового потока, создаваемого в `AbsentRegionsFinder`.
- Новый класс `RegionsSparseGraph`, в который будут подгружаться ребра из секции в WorldMwm (следующие реквесты, пока - заглушка). С этим классом работает `RegionsRouter`.
- Изменения в `IndexGraphStarter` и других классах, необходимые для корректной …
=> [routing] Use client-side for finding absent mwms for route instead of OSRM backend.

map/bookmark_manager.cpp
Do not force visibility to false for categories that does not have visible constituents. 
https://jira.mail.ru/browse/MAPSME-15349
=> [bookmarks][looonely] Allow to turn on visibility for categories having visibilities of all constituents turned off.

map/bookmark_manager.cpp
Rebase #14058 onto master.
Do not force visibility to false for categories that does not have visible constituents.
https://jira.mail.ru/browse/MAPSME-15349
=> cherry-pick [bookmarks][looonely] Allow to turn on visibility for categories having visibilities of all constituents turned off.

routing/cross_mwm_connector_serialization.cpp, routing/cross_mwm_connector_serialization.hpp
В следующем реквесте планирую поменять GeometryCodingParams, добавив туда limitRect. Т.к. coding не зависит от platform, не знает версии mwm и т.п. там делать ветвление по раскодированию разных версий не получится. Пришлось бы сделать здесь. Но если GeometryCodingParams не используются кажется лучше сделать тут ветвление и в новой версии их вообще убрать.
=> [routing] Cross mwm connector serialization: get rid of unused GeometryCodingParams.

map/search_mark.cpp
Fixed compiler warning: 
```
warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
ProcessMarks([this, &featureId](SearchMarkPoint * mark) -> base::ControlFlow
```
=> [map] Removed unused lampda parameter.

generator/boost_helpers.hpp, generator/final_processor_country.cpp, generator/final_processor_country.hpp, generator/hierarchy.cpp, generator/osm2type.cpp, generator/relation_tags.cpp
Presently, a building feature is marked as _has_parts_ if it has _building:parts=yes/vertical/horizontal/..._ tag, or if it's a member of a _type=building_ relation with _outline_ role. Such building won't be rendered in the hope that _building:part_ features would be rendered instead. But both of these methods are not reliable, since:
- a building can have no _building:parts=yes_ tag when it is really cut into parts (very often case)
- a building can have _building:parts=yes_ tag without actually having parts inside it (rare but also occur)
- _type=building_ relation may be broken and not reflect real building-parts relationship (also, currently only ways that are _outline_ members of _building_ relations are considered as buildings to be marked with _has_parts_ property; multipolygon …
=> [generator] Better determination if building has parts

android/jni/com/mapswithme/platform/Platform.cpp, android/src/com/mapswithme/util/BatteryState.java
Crash:
Crashed: Thread :  SIGABRT  0x00002872000005d7
#00 pc 0x7917cd3134 libc.so 
#01 pc 0x7917cd3104 libc.so 
#02 pc 0x78942c5a54 libart.so 
#03 pc 0x79166b15b4 libbase.so 
#04 pc 0x789430a658 libart.so 
#05 pc 0x7893f78304 libart.so 
#06 pc 0x7893f654c0 libart.so 
#07 pc 0x7894331a50 libart.so 
#08 pc 0x78943355ac libart.so 
#09 pc 0x789421cee0 libart.so 
#10 pc 0x789421de68 libart.so 
#11 pc 0x78942e7af0 libart.so 
#12 pc 0x78943093b4 libart.so 
#13 pc 0x78943052b8 libart.so 
#14 pc 0x789431f38c libart.so 
#15 pc 0x7894318794 libart.so 
#16 pc 0x7894317b6c libart.so 
#17 pc 0x78942c56bc libart.so 
#18 pc 0x79166b15b4 libbase.so 
#19 pc 0x78941868c4 libart.so 
#20 pc 0x78941c467c libart.so 
#21 pc 0x78256f3124 libmapswithme.so (_JNIEnv::CallStaticIntMethod(_jclass*, _jmethodID*, ...) …
=> [android] fix for lost jni signature refactoring

transit/world_feed/feed_helpers.cpp
перенесла проверки на метрошность в одно место, чтобы было проще переключаться между метро/не метро
=> [transit] Minor refactoring: move subway checks to single place.

base/base_tests/string_utils_test.cpp, base/string_utils.cpp, base/string_utils.hpp, generator/osm_element.cpp, generator/osm_source.cpp
https://github.com/mapsme/omim/pull/11988 по частям
* d19a55fe344d814a4003fa18b6e31f15157c78bf [generator] Added forgotten ref. (generator/osm_source.cpp)
Избавление от копирования, замена на ссылку.
* a9d73c038e419ecd902a727ac5d446579e887a3a [generator] Clear instead of construct and copy. (generator/osm_source.cpp)
Раньше было очищение element с помощью присваивания пустого объекта. Теперь вызов Clear(). Так быстрее, потому что капасити у контейнеров остается прежней, будет меньше реаллокаций.
* b6c65bb7c5a276fa9bd379eb0a1dda9e72158e28 [generator] Used trim without locale instead of boost::trim. (generator/osm_element.cpp)
Добавлена новая реализация Trim. По Таниному комменту про нестандартные пробелы: можно вставить код от сюда https://www.codepile.net/pile/oP4R1V26 в …
=> [generator] Some optimizations part 1

android/res/layout/dialog_edit_text.xml, android/res/layout/edit_bookmark_common.xml, android/res/layout/fragment_edit_description.xml, android/res/layout/fragment_editor.xml, android/res/layout/fragment_osm_login.xml, android/res/layout/fragment_ugc_editor.xml, android/res/layout/fragment_ugc_route_edit.xml, android/res/layout/item_bookmark_create_group.xml, android/res/layout/item_editor_input.xml, android/res/layout/item_localized_name.xml
Из таски https://jira.mail.ru/browse/MAPSME-15395 исправлен сценарий:
1) слова в полях для редактирования отображены темным шрифтом на темном фоне, если в приложении темная тема включена, а в настройках девайса выключена 
STR
1. Включить светлую тему в настройках телефона 
2. Открыть приложение 
3. Зайти в настройки 
4. Включить ночной режим 
5. Обратить внимание, на слова в полях для ввода:
5.1. редактирование/добавление места на карту
5.2. создание и настройки списка меток, 
5.3. написание отзыва
5.4. вход в профиль OpenStreetMap
ОР: Слова в полях для ввода написаны светлым шрифтом на темном фоне 
ФР: Слова в полях для ввода написаны темным шрифтом на темном фоне
=> [android] Fixed night mode in some edittext fields.

transit/world_feed/world_feed.cpp, transit/world_feed/world_feed.hpp
В некоторых фидах довольно много trip-ов и shape-ов, сейчас с ними работает несколько долго, например
```
cat ~/data/gtfs/omd_0209/trips.txt |wc -l
441773
cat ~/data/gtfs/omd_0209/shapes.txt |wc -l
759457
```
Можно вместо того чтобы делать оптимизацию здесь переделать хранение shape-ов в just_gtfs, но я вижу что там всё является отражением того как хранятся данные в файлах и где-то ради этой простоты поступились производительностью. Поэтому там не стала (но если надо перенесу туда).
=> [transit] Improve get_shape speed.

coding/files_container.cpp
clang 11 generate such error for coding/files_container.cpp:
destructor cannot be declared using a type alias
=> fix build with clang 11: destructor + alias

skin_generator/generator.cpp
If code compiles with "-DQT_USE_QSTRINGBUILDER" (for more fast QString
concatenation) then code with implicit QString -> QDir conversation
cause compile time error:
```
conversion from «QStringBuilder<QString, char [5]>» to non-scalar type «QDir» requested
```
=> Fix build of skin_generator: no explicit QString->QDir conversation

generator/transit_generator_experimental.cpp
У нас в  transit cross mwm (как и в остальном cross mwm) закреплено соответствие между cross mwm id и feature id, при этом на генерации feature id брался из json (причём в  json feature id кросс-мвмного ребра одинаковый внутри разных мвм, чего кажется быть не должно).
В рантайме feature id нумеруются по порядку в графе (с оффсетом чтобы фичи были фейковыми), а в кросс-мвм к считанному идентификатору прибавляют оффсет. И по факту фича на которую "смотрит" кросс-мвм получатся не та.
В этом реквесте сделан тривиальный фикс в генерацию кросс мвм, который вместо featureId из json использует порядковый номер.
В этом реквесте не сделано исправление feature id в json или выпиливание его оттуда поскольку я не разобралась в коде который его создаёт.
Пока мне кажется что целесообразнее выпилить …
=> [transit][generator] Fix cross mwm features numeration for experimental transit.

transit/world_feed/gtfs_converter/gtfs_converter.cpp, transit/world_feed/world_feed.cpp, transit/world_feed/world_feed.hpp, transit/world_feed/world_feed_integration_tests/world_feed_integration_tests.cpp
В идеале хотелось тест который проверит что фид без  generateTrivialShapes не грузится, а с ним грузится, но для этого надо или иметь два одинаковых фида без шейпов отличающихся agency (и тогда в тесте не будет очевидно что этот один и тот же грузится или не грузится в зависимости от опции), либо завести у  WorldFeed метод который сбрасывает статический  m_agencyHashes и сбрасывать в тестах.  Могу оставить как есть или реализовать один из предложенных выше вариантов.
=>  [transit] Generate trivial shapes.
